### ISSUE TITLE
bug: plugins compatibility with the lastest framework

### ISSUE THREAD

**Issue by thulari** [ionic-team/ionic#20818] opened 2020-03-19 10:37 UTC
I had upgraded the IONIC framework to 5.4.6,then after that upgrade, card.io and barcode scanning were not working simultaneously on the app. The one plugin that I installed first will work while the one installed last won't work.so I had to downgrade the framework to 5.2.7 to get the plugin both working in my app. I just want to have the latest framework version without compatibility of plugin issues.

**Comment by liamdebeasi** [comment] 2020-03-19 13:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The framework does not manage any of the native plugins. Additionally, there is no Ionic Framework 5.4.6 or Ionic Framework 5.2.7 -- you might be confusing the Ionic CLI for Ionic Framework.

I recommend you post your question on our [forums](http://forum.ionicframework.com/). Thanks!

**Closed by liamdebeasi** 2020-03-19 13:07 UTC
Labels: triage
