### ISSUE TITLE
Error with ion-input V4.0.0-beta.1

### ISSUE THREAD

**Issue by 777wills** [ionic-team/ionic#15084] opened 2018-08-08 01:14 UTC
**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (C:\Users\wills777\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.1
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.2.0
   OS     : Windows 10

**Describe the Bug**
Ion-input simply does not work

![image](https://user-images.githubusercontent.com/36114477/43810579-0fd926ca-9a7e-11e8-8d82-3d712782764d.png)

![image](https://user-images.githubusercontent.com/36114477/43810647-80c8584c-9a7e-11e8-8cf5-78a97687eb22.png)

**Comment by FilipMatys** [comment] 2018-08-08 07:47
I can also confirm this issue after starting new blank project today. Does not work for "stacked" as well.

**Comment by FilipMatys** [comment] 2018-08-08 07:48
Duplicate of #15082

**Comment by manucorporat** [comment] 2018-08-08 09:04
This is fixed in master! beta.2 will include the fix

**Closed by manucorporat** 2018-08-08 09:04 UTC
Labels: triage
