### ISSUE TITLE
Multiple issues with DeepLinker / url support in PWA

### ISSUE THREAD

**Issue by mmlleevvyy** [ionic-team/ionic#11101] opened 2017-04-06 19:41 UTC
**Ionic version:**  (check one with "x")
**3.0.0**

**I'm submitting a ...**  (check one with "x")
[X] bug report

**Current behavior:**
There are few issues with DeepLinker / url support:
1. When a page (single page, no tabs) is pushed to rootNav from within a tab page, url is not changed
2. When tab page (lets name it B) is pushed from other tab page (lets name it A) and then back button pressed (on the app's navbar), the location is still showing url of B page
3. When in any page modal is presented, the url is cleared to empty anchor... when modal is opened and browser reloaded, then app opens on main page, which is not desired in PWA. I noticed, that it happens as well for popovers.

All those issues applies to application that runs in a browser (I tested on Chrome, but same behaviour on all browsers).

**Expected behavior:**
Issue 1: Url should change
Issue 2: Url should change back to url of A page
Issue 3: Url should not change at all when modal is shown, just like alerts.

**Steps to reproduce:**
I created a repo: https://github.com/lleevvyy/ionic-bugs-example
Run ionic serve and follow steps below.

Reproduce issue 1:
* On Home page, click button "Go to Tab1 page"
* On Tabs1 page, click button "Go to About page" - you should see, that url did not change (should be /#/about

Reproduce issue 2:
* On Home page, click button "Go to Tab1 page" - url should change to /#/tabs1/tab/tabs1tab1
* On Tabs1 page, click button "Go to Tabs2 page" - url should change to /#/tabs2/tab/tabs2tab1
* On Tabs2 page, click back button on the navbar (app navbar, not browser) - url will not change and will be /#/tabs2/tab/tabs2tab1... instead it should be url of tabs1

Reproduce issue 3:
* On Home page, click button "Open modal" - you will notice, that url change from /#/home to /#/

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3 Build version 8E162
Browser: Chrome 57.0.2987.133 (64-bit)

**Comment by brandyscarney** [comment] 2017-04-06 21:07
Thanks for the issue! We are aware of some of these issues and will be working on fixing them. :)

**Comment by mburger81** [comment] 2017-05-05 15:34
I can confirm the issue 3. This is also not usefull because if your developing on ModalPage on livereload the app is always navigate back to start page.

**Comment by lleevvyy** [comment] 2017-07-15 18:20
@danbucholtz can you look at those issues please, maybe some of them you will be able to fix as you work on improved navigation?

**Comment by danbucholtz** [comment] 2017-09-13 14:51
These issues should be fixed now with the updates to Nav over the past few months. Please open another issue if you're still having trouble, but I think they're resolved.

Thanks,
Dan

**Closed by danbucholtz** 2017-09-13 14:51 UTC
Labels: navigation, v3
