### ISSUE TITLE
ion-icon fails in electron

### ISSUE THREAD

**Issue by cpyle0819** [ionic-team/ionic#16749] opened 2018-12-14 20:38 UTC
# Bug Report

**Ionic version:**

[x] **4.0.0-beta.19**

**Current behavior:**

When using `<ion-icon>` icons fail to load in electron with the error _Fetch API cannot load file://path/to/file. URL scheme "file" is not supported._

**Expected behavior:**

`<ion-icon>` displays icon.

**Steps to reproduce:**

1. setup an ionic/angular app and include an ion-icon
2. build an electron app with capacitor
3. run electron app

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
"@ionic/angular": "4.0.0-beta.19",
"@capacitor/cli": "^1.0.0-beta.11",
"@capacitor/core": "^1.0.0-beta.11",
```
`<ion-icon>` works as expected when ionic is include via a script tag instead of an angular module. If this is an inappropriate place for this issue let me know and I can ask elsewhere. I wasn't sure where the responsibility would fall for this one.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/cpyle/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.9.0-rc.3
   @angular-devkit/schematics    : 0.9.0-beta.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/cpyle/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v10.1.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by cpyle0819** [comment] 2018-12-14 20:39
A workaround for this is to either use Ionic via the `unpkg` cdn, or to use the icon font instead of the svgs.

**Comment by paulstelzer** [comment] 2018-12-15 10:07
Thanks for your issue! It's a good question where this report belongs to. Could you maybe open an issue on https://github.com/ionic-team/capacitor too and link to this issue, too? I leave this open because I am self unsure where the problem is exactly ( I think more at capacitor because the electron support is in early stage).

**Comment by cpyle0819** [comment] 2018-12-17 15:14
Still failing in beta.19. Updated issue, and make an issue with capacitor team: https://github.com/ionic-team/capacitor/issues/1059

**Comment by jcesarmobile** [comment] 2018-12-21 16:36
The problem is in Capacitor, closing here.

**Closed** 2018-12-21 16:37 UTC
Labels: needs: investigation
