### ISSUE TITLE
4.0.0-rc.1 missing ion-icons (with updated webpack config)

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic#17019] opened 2019-01-09 18:00 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Icons are missing with the following new configuration:
```
{
  "glob": "**/*.svg",
  "input": "node_modules/ionicons/dist/ionicons/svg",
  "output": "./svg"
}
```

**Expected behavior:**
Icons are working

**Comment by manucorporat** [comment] 2019-01-09 18:13
can you send your angular.json?

**Comment by petrot** [comment] 2019-01-09 18:19
```
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "defaultProject": "app",
  "newProjectRoot": "projects",
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                "input": "src/global.scss"
              }
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "ci": {
              "progress": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          },
          "configurations": {
            "ci": {
              "progress": false,
              "watch": false
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["src/tsconfig.app.json", "src/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        },
        "ionic-cordova-build": {
          "builder": "@ionic/angular-toolkit:cordova-build",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "ionic-cordova-serve": {
          "builder": "@ionic/angular-toolkit:cordova-serve",
          "options": {
            "cordovaBuildTarget": "app:ionic-cordova-build",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "production": {
              "cordovaBuildTarget": "app:ionic-cordova-build:production",
              "devServerTarget": "app:serve:production"
            }
          }
        }
      }
    },
    "app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "ci": {
              "devServerTarget": "app:serve:ci"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "@ionic/angular-toolkit"
  },
  "schematics": {
    "@ionic/angular-toolkit:component": {
      "styleext": "scss"
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    }
  }
}
```

**Comment by manucorporat** [comment] 2019-01-09 18:40
Can you check if `node_modules/ionicons/dist/ionicons/svg` exists?
Can you check if `www/svg` is emitted?

I can't reproduce your issue.

Make sure you remove node_module, and npm i again

**Comment by petrot** [comment] 2019-01-09 18:47
node_modules/ionicons/dist/ionicons/svg exist, but www/svg not emitted.

remove node_modules and run npm install again did'nt solve the problem :/

**Comment by petrot** [comment] 2019-01-09 19:01
I deleted the `www` folder, then ran a fresh build. Now the svg folder exists on the www folder. When I run `ionic serve`, there is an error on the dev toolbar: `zone.js:1050 GET http://localhost:8100/svg/md-settings.svg 404 (Not Found)` and there are empty icons. But if I copy the svg url and paste it into the browser, the svg appears.

**Comment by aces-tm** [comment] 2019-01-09 19:05
It's the same for me. It seems when I open another page that some icons appear... it's weird.

**Comment by aces-tm** [comment] 2019-01-09 19:15
I cleared cache on Google Chrome and everything worked as expected!

**Comment by paulstelzer** [comment] 2019-01-09 19:24
Correct, you have to clear the cache first

**Comment by paulstelzer** [comment] 2019-01-09 19:35
Let us summarize:

1) Delete www folder
2) ng serve
3) Clear browser cache

**Comment by aces-tm** [comment] 2019-01-09 19:36
I didn't delete www, just cleared cache...

**Comment by manucorporat** [comment] 2019-01-09 20:02
Damn, stupid cache! Closing issue! thanks everyone for figuring this out!

**Closed by manucorporat** 2019-01-09 20:02 UTC
Labels: triage

**Comment by elylucas** [comment] 2019-01-09 21:21
If you cleared your cache and its still not working, see if you have your dev tools open. If so, click the 'disable cache' in there on the network tab and try again. This was the trick for me.

**Comment by jmdmao** [comment] 2019-01-15 17:51
Clear cache not work for me.

**Comment by elylucas** [comment] 2019-01-15 17:55
@jmdmao if you look in another browser that you haven't used before, do they still not show up? That should let you know if its a cache problem or something else.

**Comment by peterennis** [comment] 2019-01-17 04:45
@paulstelzer 
Delete www folder fixed it for me.
Thanks!
