### ISSUE TITLE
some issue with Loading Controller looping infinite while pressing Enter or space from keyboard

### ISSUE THREAD

**Issue by aditya-singh-07** [ionic-team/ionic#20967] opened 2020-04-04 15:11 UTC
I Implemented Loading Controller while clicking login button with duration of 1000 ms at that instance when i click Enter or Space button from keyboard three time it looping infinite don't know why??

![bug](https://user-images.githubusercontent.com/45713746/78454157-eddb0980-76b3-11ea-9b22-ff6d0c13a333.gif)
![auth-page](https://user-images.githubusercontent.com/45713746/78454248-82de0280-76b4-11ea-8945-38c6fc7876b0.PNG)
![login-page](https://user-images.githubusercontent.com/45713746/78454249-83769900-76b4-11ea-9f19-b67db4670da5.PNG)

**Comment by indraraj26** [comment] 2020-04-05 06:19
https://github.com/ionic-team/ionic/issues/19882

**Comment by liamdebeasi** [comment] 2020-04-06 13:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19882. (The reference issue is a different component, but the underlying issue appears the same).

**Closed by liamdebeasi** 2020-04-06 13:11 UTC
Labels: triage
