### ISSUE TITLE
bug: iOS bounce flicker when HTML contains li tag or "display: list-item" CSS property

### ISSUE THREAD

**Issue by trabdin** [ionic-team/ionic#20486] opened 2020-02-14 11:19 UTC
# Bug Report

**Ionic version:**

[x] **5.x**
[x] **4.x**

**Current behavior:**
When I have a `li` tag inside the page content or if I just have a `p` tag with the CSS `display: list-item` property, the bounce effect on iOS flickers.

See this GIF for when I have a normal page with just a paragraph with `display: list-item` CSS property:

![flicker](https://user-images.githubusercontent.com/25244123/74526273-5105b680-4f23-11ea-98d5-56aa227dad54.gif)

**Expected behavior:**
The bounce should look the same as when I don't have an `li` tag or text with the `display: list-item` CSS property in the HTML.

See this GIF after I removed the `display: list-item` CSS from the paragraph:

![non-flicker](https://user-images.githubusercontent.com/25244123/74526403-a2ae4100-4f23-11ea-9bea-3eb84bac9a47.gif)

**Steps to reproduce:**
Just create a page with an `li` tag or a text element with `display: list-item`.

**Related code:**

```
<ion-content>
  <li>test</li>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res (update available: 0.9.0) : 0.6.0
   native-run                            : not installed

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-02-14 15:19
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snipped provided.

**Comment by trabdin** [comment] 2020-02-14 18:49
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snippet provided.

Thanks for the reply. I found out what causes it. I have the following in my global.scss:

```
:active {
    outline: 0;
}
```

I don't even know/remember why I put it there to be honest. But if you just add that css snippet to global.scss, along with the code snippet in the OP, you should get the bounce flickering.

**Comment by liamdebeasi** [comment] 2020-02-14 19:52
Is that the full code, or is `:active` supposed to be a pseudo selector for another element?

**Comment by liamdebeasi** [comment] 2020-02-14 20:26
Thanks for the issue. I am going to close this as this does not appear to be a bug in Ionic Framework. 

I was able to reproduce this outside of Ionic: https://codepen.io/liamdebeasi/pen/LYVGaMm (load this on an iOS device).

It looks like your CSS combined with an event listener on the document causes the browser to perform a full Layout when you lift the pointer from the screen. This seems to cause WebKit to reset its scroll position when doing rubber band scrolling.

I will look into reporting this to the WebKit team. As for a workaround, I recommend not setting `:active { outline: 0; }` globally. Thanks!

**Closed by liamdebeasi** 2020-02-14 20:26 UTC
