### ISSUE TITLE
ionic app slow only on windows 10 mobile devices

### ISSUE THREAD

**Issue by toutvasuperbien** [ionic-team/ionic#12611] opened 2017-08-08 09:19 UTC
**Ionic version:**
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**
[x ] performance report
[ ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I have to deploy an app on ios, android and windows devices.
On ios and android I have nothing to say excepted 'wow, fantastic job'.
On windows 10 **desktop** my ionic app works perfectly, I have noticed great improvements of performance, I would like to thank ionic team for that.
However on windows 10 **mobile**, tested with a lumia 550, it is very slow with a systematic delay of several seconds after click on a button or a link. Swipe only works if I press for a long time. 
Yet there is no bug, I can navigate throughout the application without any error but the user experience is just unpleasant.
On my test phone I also have a simple cordova app which works correctly so that I don't think the phone is the cause of the problem.
The strange thing is that the performance is also excellent on windows 10 mobile emulators provided by Visual Studio 2015.

**Expected behavior:**

The expected bahaviour is to have the same performance on windows 10 mobile device as on windows 10 desktop and mobile emulators.

**Steps to reproduce:**
To reproduce, just use a real device with windows 10 mobile and deploy a ionic test app like conference app.  

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2017-08-08 14:40
Hello (: I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11783

**Closed by jgw96** 2017-08-08 14:40 UTC
