### ISSUE TITLE
ion-segment doesnt't show properly after upgrade to ionic V5

### ISSUE THREAD

**Issue by lapid3** [ionic-team/ionic#20692] opened 2020-03-04 19:32 UTC
Ion-segment doesn't show properly after update to V5.
Basically with short labels it works fine but if I use long labels (and I need to) it will cut half of it and overlap the following button (pics on link).

![segment](https://user-images.githubusercontent.com/25478014/75915654-3a35ee00-5e57-11ea-8169-c2f4dd5f1ff0.PNG)
![segment2](https://user-images.githubusercontent.com/25478014/75915671-3efaa200-5e57-11ea-92c2-d4f9c99d3ab1.PNG)

Tried even with fresh/clean project but still.

**Comment by simonhaenisch** [comment] 2020-03-09 19:52
Can confirm this, happens in our app as well. The segment already has horizontal scroll, so each segment-button should take as much space as it needs (at least that's how it behaved before).

**Comment by simonhaenisch** [comment] 2020-03-11 17:51
Duplicate of #20566 I think (at least our segments have `scrollable` enabled).

**Comment by liamdebeasi** [comment] 2020-03-12 16:05
Thanks for the issue.

For the MD spec, there are 2 types of segments (they call them tabs in their docs):

1. Fixed segments (the default in Ionic): These are fixed-width segments that are all displayed on the screen. The width of each segment is determined by dividing the number of segments by the screen width. These segments do not scroll. Due to this behavior, longer text may get truncated in order to show all tabs on the screen without scrolling.

2. Scrollable segments: These segments do not have fixed widths. They are all scrollable, and some will remain off-screen until scrolled. This is likely what you want to use in your application. Note that there is a bug (https://github.com/ionic-team/ionic/issues/20566) where the segments are stuck at a fixed width, but I have a PR coming soon that will fix that.

From their documentation examples it looks like they automatically switch between the two which is something that might be worthwhile doing in Ionic. cc @brandyscarney

**Comment by liamdebeasi** [comment] 2020-03-16 13:51
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20765. Please refer to https://github.com/ionic-team/ionic/issues/20566 for updates on the segment scrollable bug I mentioned previously.

**Closed** 2020-03-16 13:51 UTC
Labels: needs: investigation
