### ISSUE TITLE
Ionic List Reorder - Can’t drop at same spot as beginning

### ISSUE THREAD

**Issue by jasonvdzeeuw** [ionic-team/ionic#12940] opened 2017-09-20 12:35 UTC
**Ionic version:** 
[X ] **3.x**

[X] feature request

**Current behavior:**
ion-list reorder - doesn't allow an item to be put back in the same position immediately.
When I drag the top item and decide I didn’t want to reorder that one, I have to put it in any other spot first, before I can put it back.

**Expected behavior:**
I want to put an item where-ever I want. When I decide not to reorder it, it should be able to be put back at the same index.

**Steps to reproduce:**
It's easy to reproduce in the Demo in the Docs:
https://ionicframework.com/docs/api/components/item/ItemReorder/

**Comment by Sampath-Lokuge** [comment] 2017-09-20 12:45
Hope Ionic team will give this feature soon.

**Comment by kensodemann** [comment] 2017-09-20 16:56
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #12504. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.

Due to the nature of this issue, it is probably something we will not look at until after v4 is out, but we will look at it.

Thank you for using Ionic

**Closed by kensodemann** 2017-09-20 16:56 UTC
