### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by kelzerman** [ionic-team/ionic#21432] opened 2020-06-04 11:26 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When starting a new app I add a new pipe. Then I use the pipe in home.page.html.
When starting the app (ionic serve) it gives an error:

core.js:6260 ERROR Error: Uncaught (in promise): Error: The pipe 'customCurrency' could not be found!

**Expected behavior:**
The value of balance should be shown as the pipe returns it (with dollar sign).

**Steps to reproduce:**

1. Start new ionic app: ionic start myapp blank
2. Add the pipe: ionic generate pipe pipes/CustomCurrency
3. Add the code to CustomCurrency
4. Use pipe in the home.page.html: {{ balance | customCurrency }}
5. Declare balance in home.page.ts: balance: number = 500;

**Related code:**
Contents of CustomCurrency. Other mentoined files are default.
```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'customCurrency'
})
export class CustomCurrencyPipe implements PipeTransform {
  transform(value: any): any {
    return "$" + value;
  }

}
```

**Other information:**
Doesn't work in a plain, new project or existing project.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.9.2 (C:\Users\{username}\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (D:\Programs\NodeJs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-06-04 13:32
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You need to import the pipe into your `home.module.ts` file before you can use it in `home.page.html`.

**Closed by liamdebeasi** 2020-06-04 13:32 UTC
Labels: triage
