### ISSUE TITLE
bug: Form Instances are memory leaking with ionic input. (Memory Leak)

### ISSUE THREAD

**Issue by burdokat** [ionic-team/ionic#21539] opened 2020-06-15 18:19 UTC
# Bug Report
# Please Read Carefully And Test First. Thank You.

**Ionic version:**

[ ] **4.x** (Not tested)
[x] **5.x** (Tested) (Memory Leak)

**Angular version:**
[ ] **8.x** (Tested with Ionic 5) (Not exhibiting memory leak)
[x] **9.x** (Tested with Ionic 5) (Memory Leak)

**Current behavior:**

Any instances pertaining the form keeps piling up in memory. Hence, everything else from the form up to its container (page, component, modal, or anything else) will not be garbage collected. Hence, memory is hugely leaking (See image below of nodes piling up).

![image](https://user-images.githubusercontent.com/20394220/84685649-3c9cef00-af00-11ea-99fc-273c2692f198.png)

![image](https://user-images.githubusercontent.com/20394220/84686233-33f8e880-af01-11ea-9e61-7f246dcffc9b.png)

![image](https://user-images.githubusercontent.com/20394220/84686762-2b54e200-af02-11ea-8bcb-0bbb6120ee11.png)

**Expected behavior:**

Any instance pertaining the form must be garbage collected.

The example demo was tested with the submit button enabled and it did not presented any memory leak at all if the form is left untouched.

![image](https://user-images.githubusercontent.com/20394220/84687965-22651000-af04-11ea-970e-cf33db274fd9.png)

![image](https://user-images.githubusercontent.com/20394220/84691556-f9e01480-af09-11ea-9b1c-263698b8bb79.png)

**Steps to reproduce:**

* Follow the link to this repository:
https://github.com/burdokat/FormDemo

**Related code:**
* Follow the link to this repository:
https://github.com/burdokat/FormDemo

**Additional Information:**
I uploaded a sample demo as an example to represent this bug. It is a simple two page app, a login page and the home page), simplified to its minimum expression using the minimum configurations to represent an angular template driven form. The same behaviour is exhibited in reactive driven forms too.
* For more information and details of this bug, please follow the example code in the link to the repository below and PLEASE CHECK THE README file:
https://github.com/burdokat/FormDemo
May be related to other bugs (requires more thorough investigation).
Help needed.

**SPECIAL NOTES:** 
Check, read and test the appointed repository first.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.1 (C:\Users\BRDKT\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (C:\Program Files (x86)\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 8.1

```

**Comment by liamdebeasi** [comment] 2020-06-15 19:17
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I took a look at your application, and I was able to reproduce the same behavior in an Angular 9 application **without Ionic Framework**: https://github.com/liamdebeasi/ng9-forms-routing.

As I explained in the previous thread (https://github.com/ionic-team/ionic/issues/21521), this behavior is how Angular Routing works. That thread also provides some solutions you can use to get around this behavior. This behavior is not typically an issue as most users are not navigating to and from the same login page many times in a row.

If you still feel this is a bug, I recommend opening an issue on the Angular repo (https://github.com/angular/angular) as any bug fixes would likely be made there.

**Closed by liamdebeasi** 2020-06-15 19:17 UTC
Labels: triage

**Comment by burdokat** [comment] 2020-06-15 21:31
@liamdebeasi True. The problem is in angular 9. Not in Ionic. I was able to reproduce the same issue with only angular 9. Looks like angular 8 doesn't has this kind of problem. It seems other threads has been opened with other side effects related to this issue.

Well, I agree with you that no one will be using login pages repeatedly. But it was just a demo. This bug is still problematic, since forms are used in many other ways... Any type of form tag using angular 9 framework specifically, be it template or reactive driven is having this issue right now. 
Thanks for your help.
