### ISSUE TITLE
feat: Add interfaces for lifecycle hooks like in Angular itself

### ISSUE THREAD

**Issue by RoopeHakulinen** [ionic-team/ionic#20089] opened 2019-12-15 12:46 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
[Ionic's lifecycle hooks](https://ionicframework.com/docs/angular/lifecycle) are missing interfaces describing them. This has few disadvantages:
- No type checking (possibility to have typos)
- No documentation available in code (compare e.g. navigating to source of `OnInit`)
- Poor editor support

**Describe Preferred Solution**
Introduce the following interface somewhere in Ionic code base for it to be importable in the apps:

```
/**
 * A lifecycle hook that is called when the component routing to is about to animate into view.
 */
export interface ViewWillEnter {
  ionViewWillEnter(): void;
}

/**
 * A lifecycle hook that is called when the component routing to has finished animating.
 */
export interface ViewDidEnter {
  ionViewDidEnter(): void;
}

/**
 * A lifecycle hook that is called when the component routing from is about to animate.
 */
export interface ViewWillLeave {
  ionViewWillLeave(): void;
}

/**
 * A lifecycle hook that is called when the component routing to has finished animating.
 */
export interface ViewDidLeave {
  ionViewDidLeave(): void;
}
```

**Additional Context**
[Angular rationale](https://angular.io/guide/lifecycle-hooks#interfaces-are-optional-technically) for having the interfaces available and recommended to be used.

**Comment by liamdebeasi** [comment] 2019-12-16 12:54
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18043.

**Closed by liamdebeasi** 2019-12-16 12:54 UTC
Labels: triage
