### ISSUE TITLE
v4: thumbnail does not resize containing image

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14700] opened 2018-07-03 10:49 UTC
# Bug Report

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI)          : 4.0.0-rc.9 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.1 (/usr/bin/node)
   npm               : 6.1.0
   OS                : Linux 4.15

Environment:
   ANDROID_HOME : /...../android/sdk
```

**Describe the Bug**
We use a list with ion-item which contains an ion-thumbnail and an ion-label. The picture we show in the ion-thubmnail does not have the same size of the picture in ionic3. It would not be resized.

```
This is the sample code:
  <ion-list>
    <ion-item *ngFor="let device of devices">
        <ion-thumbnail slot="start">
            <img src="assets/img/pic.png">
        </ion-thumbnail>
        <ion-label>
            <h2>Bla</h2>
            <p>BlaBla</p>
        </ion-label>
    </ion-item>
</ion-list>
```

This is the look in ionic4
![image](https://user-images.githubusercontent.com/3778892/42215546-14f718f4-7ebf-11e8-8855-f12baf569273.png)

This is the look in ionic3
![image](https://user-images.githubusercontent.com/3778892/42215606-462ab28c-7ebf-11e8-8b65-e1f47f49cd6c.png)

As you can see in ionic3 we are able to see the whole picture, in ionic4 it is truncated.

Having a look to http://ionic-docs.herokuapp.com/docs/api/thumbnail there should nothing magical to do.

Perhaps now on ionic4 we are not able to wrap bigger images in a smaller thumbnail?

**Comment by mburger81** [comment] 2018-07-03 12:46
#14660 similar issue?

**Comment by jgw96** [comment] 2018-07-12 14:48
Hello! I can no longer reproduce this issue with the latest release. Because of this I am going to be closing this issue for now (: Thanks for helping us test Ionic v4!

**Closed by jgw96** 2018-07-12 14:48 UTC
Labels: triage

**Comment by mburger81** [comment] 2018-07-16 09:57
@jgw96 Honestly we are experiencing still the same issue. No change for us on `alpha.10`. Can you share your test?


![image](https://user-images.githubusercontent.com/3778892/42752801-555eb11a-88ef-11e8-937c-134b1b683b8a.png)
