### ISSUE TITLE
bug: ion-datetime scroll inertia/momentum to high

### ISSUE THREAD

**Issue by madmacc** [ionic-team/ionic#18679] opened 2019-07-01 00:46 UTC
# Bug Report

**Ionic version:**
[x] **4.1**

**Current behavior:**
On a physical device (iOS) the picker does not stop as expected at slow scroll speeds, it seems to have to much inertia.  It is subtle but is different to the native iOS time picker e.g. if you try to set an the alarm on an iOS device.  It scrolls a little to long at low speeds and makes it more error prone to pick the correct time. 

**Expected behavior:**
Behave the same as the time picker on iOS used when setting the alarm.  e.g. less inertia and stops on the expected number easier.

**Steps to reproduce:**
Add an ion-datetime to an ionic project page similar to below to pick time:
```
<ion-datetime 
              [(ngModel)]="start"
              displayFormat="HH:mm" 
              minuteValues="0,15,30,45" 
              picker-format="HH:mm"
              (ionChange)="onChangeStartTime($event)"
</ion-datetime>

```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\fullo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by Maikell84** [comment] 2019-07-11 13:00
I can confirm this. In the web-browser it is even worse. 
The timepicker is basically not usable, because it always jumps 1-3 digits further than you would expect.

**Comment by dvrakas** [comment] 2019-07-30 00:20
Is there a solution to this issue. I am encountering the same issue. Its a bit to fast and skips very easily.

**Comment by madmacc** [comment] 2019-07-30 02:47
I couldn't find a solution.  I just had to go with it for now.  It is actually an issue with ion-picker I think as it uses that.
https://ionicframework.com/docs/api/picker

**Comment by RafaelKr** [comment] 2019-07-30 16:00
I just upgraded to `@ionic/angular@4.7.1` and it feels better to me now.

**Comment by dvrakas** [comment] 2019-08-01 11:49
upgrading to @ionic/angular@4.7.1 did not seem to do fix the issue for me.

**Comment by RafaelKr** [comment] 2019-08-01 13:38
/cc @paulstelzer @liamdebeasi 
Hey, this issue seems to be overlooked. I think this belongs into your ion-datetime bug collection #16630
I just checked again and sometimes still behaves as desribed in the initial text.

**Comment by liamdebeasi** [comment] 2019-08-07 12:41
Thanks! I have added this issue to the tracker.

I am going to close this issue in favor of the bug tracker here: https://github.com/ionic-team/ionic/issues/16630.

**Closed by liamdebeasi** 2019-08-07 12:41 UTC
Labels: triage
