### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by 442623641** [ionic-team/ionic#19313] opened 2019-09-10 02:24 UTC
# Bug Report

**Ionic version:**

4.8.1

**Current behavior:**

ion-content will freeze when there are more than two ion-content in a page,
eg
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ion-slides>
    <ion-slide *ngFor='let item of [1,2,3]'>
         <ion-content>
              <div style='height:200vh'>{{item}}</div>
         </ion-content>
   </ion-slide>
</ion-slides>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.3.2
   @angular/cli                  : 8.3.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 17 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 5.0.13
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.11.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment] 2019-09-10 14:08
Thanks for the issue. As per the [ion-content Documentation](https://ionicframework.com/docs/api/content) there should only ever be one `ion-content` in a single view.

I am going to close this issue as this is not a bug in Ionic. Thanks!

**Closed by liamdebeasi** 2019-09-10 14:08 UTC
Labels: triage
