### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by hanibhat** [ionic-team/ionic#20869] opened 2020-03-25 17:03 UTC
# Bug Report

**Ionic version:**
@ionic/angular: 5.0.5

**Current behavior:**
In my app, I am using `ion-slides` in 2 different components, in a page and in a modal. When opening the modal after having visited the page with the `ion-slides`, the `ion-slides` in the modal get stuck when swiping between slides.

**Expected behavior:**
`ion-slides` switching slides completely when swiping between slides.

**Steps to reproduce:**

There `ion-slides` in the modal (has `ion-slides`) can be accessed from the home page. When the app launches, it redirects the user to an introduction page (has `ion-slides`), then navigates back to the home page. At that point, if the user opens the modal and swipes between the slides, the slides get stuck and do not slide all the way. If I remove the `ion-slides` in the introduction page, this behavior vanishes and it be behaves properly.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.0 (/home/hbhat/.nvm/versions/node/v12.14.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.6
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 9.0.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.14.1 (/home/hbhat/.nvm/versions/node/v12.14.1/bin/node)
   npm    : 6.14.2
   OS     : Linux 5.3
```

**Comment by liamdebeasi** [comment] 2020-03-25 17:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20356.

**Closed by liamdebeasi** 2020-03-25 17:26 UTC
Labels: triage

**Comment by hanibhat** [comment] 2020-03-25 17:45
Based on [this](https://github.com/ionic-team/ionic/issues/20356#issuecomment-591301060), I solved it with the following:
In the components HTML:
`<ion-slides *ngIf="didInit">
   
</ion-slides>`

And in the components TS:
`
import { timer } from "rxjs";
...

@Component({
    templateUrl: 'my-component.html'
})
export class MyComponent implements AfterViewInit {
    public loading = true;

    ngAfterViewInit() {
timer(500).subscribe(() => {
      this.loading = false;
    });
    }
}`
