### ISSUE TITLE
feat: Ionic 5 Swipe Tabs

### ISSUE THREAD

**Issue by danaugrs** [ionic-team/ionic#21662] opened 2020-07-02 00:47 UTC
Allow swiping on a page that has tab navigation enabled as an alternative way to change the current selected tab.

Example:

![image](https://aws1.discourse-cdn.com/ionicframework/original/3X/0/6/06dd1f2cc4de9e8a0b0718dd608ad0697d79e93a.gif)

**Comment by liamdebeasi** [comment] 2020-07-02 12:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17804.

**Closed by liamdebeasi** 2020-07-02 12:56 UTC
Labels: triage
