### ISSUE TITLE
ngModel on ion-input of type "number" casts the variable to string

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#12075] opened 2017-06-17 09:08 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Binding to an input of type="number" casts the variable to a string.

**Expected behavior:**
it should be number

**Steps to reproduce:**

`a: number = 100;`
`<ion-input type="number" [(ngModel)]="a"></ion-input>`//this way a is converted to string
`<input type="number" [(ngModel)]="a">`//this way a stays number

**Other information:**
https://github.com/angular/angular/issues/11325

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.7.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.8

**Comment by jgw96** [comment] 2017-06-19 19:56
Thanks for using Ionic, we will take a look into this.

**Comment by brandyscarney** [comment] 2017-06-23 20:56
Thanks for the issue, closing as a duplicate of https://github.com/ionic-team/ionic/issues/7121

**Closed by brandyscarney** 2017-06-23 20:56 UTC
Labels: v2
