### ISSUE TITLE
bug: scroll assist on ion-input and ion-textarea not (always) working

### ISSUE THREAD

**Issue by capc0** [ionic-team/ionic#21196] opened 2020-05-02 15:10 UTC
# Bug Report

**Ionic version:**

[x] **5.1.0**

**Current behavior:**

Clicking inside an input field does not scroll the page up so that the input field becomes visible.

**Expected behavior:**

Page should be scrolled up until input is visible

**Steps to reproduce:**

**Related code:**

https://github.com/capc0/ion-textarea-scroll-assist

**Other information:**

Unfortunatly it is not always reproduceable.

Here is an example with ```<ion-input>``` when inputing in items 10 and 11  the view is only scrolled after typing. should be scrolled after the click into the input instead.

![scroll-assist-1](https://user-images.githubusercontent.com/27284008/80867906-29f39100-8c97-11ea-9ccd-822119aa0380.gif)

and another one with ```<ion-textarea>```  when inputing in items 10 and 11,

![scroll-assist-2](https://user-images.githubusercontent.com/27284008/80867915-34158f80-8c97-11ea-879e-7f6a38779224.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run (update available: 1.0.0)   : 0.2.9

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.14.2
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

I have found many other issues regarding scroll assist, but they were all closed so I thought it would be better to open a new one instead of re-opening one of the old issues.

**Comment by Spinnenzunge** [comment] 2020-05-02 17:28
I have the same issue, occurs since update from 5.0.7 to 5.1.0

**Comment by liamdebeasi** [comment] 2020-05-04 18:20
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic.angular@5.2.0-dev.202005041814.9308f03`

**Comment by liamdebeasi** [comment] 2020-05-04 21:33
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.2.0-dev.202005042113.9308f03`

**Comment by capc0** [comment] 2020-05-05 06:33
For textareas it works in 90% of cases. 

For `<ion-input>` the fix did not work.

![scroll-assist-input](https://user-images.githubusercontent.com/27284008/81040118-e7a29d80-8eaa-11ea-8dda-37805da7ddaa.gif)

**Comment by liamdebeasi** [comment] 2020-05-06 13:25
@capc0 Can you provide some step to reproduce the ion-input behavior?

**Comment by capc0** [comment] 2020-05-06 13:32
@liamdebeasi I just use the repo I linked above, navigate to Tab 2 and focus the inputs at the bottom of the screen. Serving on a iPhone device. Is that not reproduceable for you in that way?

**Comment by liamdebeasi** [comment] 2020-05-06 13:33
What version of iOS are you testing on?

**Comment by capc0** [comment] 2020-05-06 13:38
13.4.1 (17E262)

**Comment by liamdebeasi** [comment] 2020-05-06 17:58
Thanks! Can you try this dev build:

`npm i @ionic/angular@5.2.0-dev.202005061751.1824261`

**Comment by capc0** [comment] 2020-05-07 06:58
That version works great :) Thanks.

**Comment by liamdebeasi** [comment] 2020-05-11 19:45
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21206, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-05-11 19:45 UTC
Labels: package: core, type: bug
