### ISSUE TITLE
bug: ion-menu disappears when navigating...

### ISSUE THREAD

**Issue by canserkanuren** [ionic-team/ionic#21669] opened 2020-07-03 14:26 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using `ion-menu` inside a `ion-split-pane`, when navigating by clicking on a `routerLink` element, the menu disappears and then appears right away.
Though, the menu isn't only disappearing when navigating from one page to another, but when clicking on, for example, buttons that makes a HTTP call to an API and then refreshes some data in the component. (The second use case isn't implemented in the example repository).
***This bug only occurs when running an Ionic App in a iPad simulator.***

**Expected behavior:**

Probably that the menu shouldn't disappear when navigating.

**Steps to reproduce:**

I made a repository where you can reproduce the bug : `https://github.com/canserkanuren/ionic-menu-disappear`

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/canserkanuren/.nvm/versions/node/v12.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   NodeJS : v12.13.1 (/Users/canserkanuren/.nvm/versions/node/v12.13.1/bin/node)
   npm    : 6.14.2
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-07-07 13:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20681 (same underlying issue).

**Closed by liamdebeasi** 2020-07-07 13:25 UTC
Labels: triage
