### ISSUE TITLE
bug: ion-select always show options at start instead of showing selectedItem

### ISSUE THREAD

**Issue by Rehan1579** [ionic-team/ionic#20980] opened 2020-04-07 02:28 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
1- The list of options always appear to be at start even if the selectedItem is at last postion when there are more options (list becomes scroll-able).

2- The options list does not close if i click/select, the already selectedItem, i need to click somewhere else to close it.

**Expected behavior:**
1- if the last item or any other item which gets selected, then the selected option should be shown right away instead of the need to scroll down and see where the selected item is.

2- The options list needs to get close if selectedItem is selected/clicked again, it happens in all other UI kits.

**Steps to reproduce:**

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-22m8i9?embed=1&file=src/app/tab1/tab1.page.html
```
insert short code snippets here
```

**Other information:**

**Ionic info:**

   Ionic CLI                     : 6.2.2
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0
   NodeJS : v12.16.1
   npm    : 6.14.2
   OS     : Windows 10
```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-04-07 15:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19296.

**Closed by liamdebeasi** 2020-04-07 15:07 UTC
Labels: triage
