### ISSUE TITLE
IOS Ionic DevApp missing from App Store 

### ISSUE THREAD

**Issue by NashIlli** [ionic-team/ionic#20205] opened 2020-01-14 18:38 UTC
Cant locate Ionic DevApp in App Store from mi IPad (7th Gen) with IOS 13.3 (latest version).

I found a link in google, but App Store tells that the app isnt available in my region (USA). 
https://apps.apple.com/us/app/ionic-devapp/id1233447133?ls=1

Thanks a lot!

**Comment by liamdebeasi** [comment] 2020-01-14 18:52
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

We recently retired Ionic DevApp in favor of native tooling and building apps with Capacitor. Please see the following page for more information as well as a migration path: https://ionicframework.com/docs/appflow/devapp

**Closed by liamdebeasi** 2020-01-14 18:52 UTC
Labels: triage

**Comment by NashIlli** [comment] 2020-01-14 20:36
Great, My mistake, sorry. So now, I must have XCode to test my app in a IOS device. Right? Previously, I could test with Ionic DevApp application. 

Thanks for your help!

**Comment by liamdebeasi** [comment] 2020-01-14 21:18
Correct, if you want to run your app as a standalone Cordova/Capacitor app you will need to use Xcode or Android Studio.
