### ISSUE TITLE
Datetime used in Angular form has incorrect value (object instead of an ISO string)

### ISSUE THREAD

**Issue by codeinpink** [ionic-team/ionic#15826] opened 2018-10-02 03:30 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Use datetime in an angular form (either with `ngModel` or through reactive forms) and the value after selecting a date/time is always an object (`DatetimeData`?).

**Expected behavior:**

According to the [docs](https://beta.ionicframework.com/docs/api/datetime), the value should be an ISO string, not an object.

**Steps to reproduce:**

**Related code:**

```
@Component({
    selector: 'app-example',
    template: '<ion-datetime displayFormat="YYYY-MM-DD HH:mm" [(ngModel)]="myDate"></ion-datetime>'
})
export class ExampleComponent {
    public myDate; // after selecting something, this will be an object
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Comment by petenunn** [comment] 2018-10-02 10:52
I am also seeing this. For a date the 'value' is an object similar to:

{ day: {text: "3", value: 3, columnIndex: 0}, 
month: {text: "Oct", value: 10, columnIndex: 1}, 
year: {text: "2018", value: 2018, columnIndex: 2} }

**Comment by kensodemann** [comment] 2018-10-02 12:44
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #15408. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2018-10-02 12:44 UTC
Labels: duplicate
