### ISSUE TITLE
bug [ionic 5]: flickering header while using Swipeable Modals [iOS] 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20579] opened 2020-02-21 11:00 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Header part of parent element is flickering
**Expected behavior:**

it should have smooth transition at header 

**Steps to reproduce:**

**Related code:**

![image](https://user-images.githubusercontent.com/23274631/75029118-7bc5b100-54c7-11ea-9a56-3870377b1392.png)
```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-02-21 14:05
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by indraraj26** [comment] 2020-02-21 16:58
branch: ionic-5
Repo: https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/tree/ionic-5/src/app

**Comment by liamdebeasi** [comment] 2020-02-21 18:08
Thanks for the follow up. I am unable to reproduce the behavior you have described using that repo. Which device and version of iOS are you testing this on?

**Comment by indraraj26** [comment] 2020-02-22 06:55
Here is video : https://youtu.be/1AAm4LuIaJ4

**Comment by liamdebeasi** [comment] 2020-02-24 14:38
Thanks for the follow up. Can you test this on an actual device instead of emulating it in Chrome? Backdrop filter in Chrome has a few visual glitches when emulating a device that should not show up on actual devices.

**Comment by indraraj26** [comment] 2020-02-25 06:14
Thank you for replying, okay let me test in real device.

**Comment by liamdebeasi** [comment] 2020-02-25 14:29
Glad to hear it is working fine on a device/emulator. As I mentioned before, the visual glitches you are seeing should only be happening in Chrome when emulating a mobile device. Just using Chrome normally as a web app or PWA should be fine.

I am going to close this issue as the original issue has been resolved.

**Closed by liamdebeasi** 2020-02-25 14:29 UTC
Labels: needs: reply
