### ISSUE TITLE
Range component Material Design disabled style

### ISSUE THREAD

**Issue by westphalen** [ionic-team/ionic#14118] opened 2018-03-05 09:25 UTC
**Ionic version:**  (check one with "x")
[X] **2.x**
[X] **3.x**
[X] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
On Android the disabled Range knob has a white square outline. Normally this square creates the illusion of a gap between the knob and the slide, but when using a non-white background the white square is visible - and ugly.

**Expected behavior:**
I would expect the `.range-md.range-disabled .range-knob` to use `outline-color: $background-color`.

**Steps to reproduce:**
1) In a new project, set `$background-color: #000000;` in `variables.scss`.
2) Add an `<ion-range [disabled]=true]></ion-range>`.
3) Preview for Android (`ionic serve` and emulate Android device). 

**Other information:**
The fix seems so simple, so maybe I'm missing the point here. Otherwise I'd be happy to submit a pull request.

Screenshot before and after:
![Screenshot](https://lh3.googleusercontent.com/1CRDjQ67CdunCI2BoBA9o0xSXGDRa8G9dECNlAZdJRXm1w4zWSIfW6tc-1phIJGAo9nLaM3E2UWYZeVhRdsdqsJClcULgC30znpPJUZ6CaFA7wl4160ueFpkd8EjkY_Z6DztIcVO4ETDMLqxiNq2IO7UvsTOPzLZHB_X2mzF0rxGEhPDAkF0kfCTazuwTxc6GnvXVIftfoyAtSo9x9rIJo7t9l66XXJGYO8CxXfQ6dB0r-HJIhA1txF6hF0LrAfOp7gg1BeFZOPka2jrAAM_ywqSyfHpB0nq3zNHEjEQaM-fk4jw8SDJpGrtRpnLHko5DB3QIn54gvL5frk-sEdv4XGFGLk4W9D9G_naiiU-irbhd0AQoDSZpN79zVQLvp0Uw4fkw34n2kF85W5FRYIj8LhxQUQaR9tkB1OmHCq19-grcCEm_KbpMgKOCrtf2AJqg3jNjvwu_C7E-xgRojfUMi9gila-sweDLLmUHmH8Mo3DXlc15_lv2Eo33vK3-uxJfgiM470-NmldC-KX3o3wFiLN3JZX9oAPE5dj-4MF_sZtNHrT_ytNtUv-6UZ6Zq0QSnASeT4LIl0Mo0u2XTQNoUnQl_xEr8FFgsgDocgvM7iG0Gj1Mqypm9Kx9zdyhKVe6Wti3RYu0no_pVsWEX3LOBdJ-fUQBtjz6w=w606-h192-no)

**Comment by guillefd** [comment] 2018-09-14 22:32
Same here, the issue is still present in **Ionic 4 Beta 9**
in devtool the CSS that adds the border is ```outline:``` , but can´t apply a rule to change it,

```
:host(.range-disabled) .range-knob {
    outline: #fff solid 5px;
}
```

maybe adding a --var?

**Comment by paulstelzer** [comment] 2018-12-08 09:18
Thanks for your issue! This should fixed in latest `@ionic/angular@beta.17`! If no, just let me know :)

**Closed by paulstelzer** 2018-12-08 09:18 UTC
