### ISSUE TITLE
bug: App will not switch to dark mode

### ISSUE THREAD

**Issue by angelofan** [ionic-team/ionic#21334] opened 2020-05-19 03:25 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On the Samsung SM-A9080 mobile phone, after the dark mode is enabled in the system settings, the App will not automatically switch to the dark mode, and it will not be automatically replaced even after restarting the App

**Expected behavior:**

App automatically follows the system whether to enable the dark mode setting

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run                             : not installed

System:

   NodeJS : v12.13.0 (/usr/local/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-05-19 13:37
Thanks for the issue. How are you running your application? Are you running it in a browser or in Capacitor/Cordova?

**Comment by angelofan** [comment] 2020-05-19 13:40
I use Capacitor build

**Comment by liamdebeasi** [comment] 2020-05-19 13:42
When running the app, can you provide the result of logging `window.navigator.userAgent` in the console? You can do this by inspecting the application via `chrome://inspect` in Google Chrome on your computer.

**Comment by angelofan** [comment] 2020-05-19 14:47
```
Mozilla/5.0 (Linux; Android 10; SM-A9080) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Mobile Safari/537.36
```

**Comment by liamdebeasi** [comment] 2020-05-19 15:02
Thanks for the follow up. Can you provide a full code reproduction of the issue?

**Comment by angelofan** [comment] 2020-05-19 15:13
I just created a new tabs according to [this document](https://ionicframework.com/docs/developing/starting), no code was added, then I built Android using Capacitor, and used Android Studio to run the App on the phone.
Then switch the dark mode switch in the phone settings. After returning to the app, the theme is always light mode.

**Comment by angelofan** [comment] 2020-05-19 15:33
For this reason I created a [code repository](https://github.com/angelofan/example.git)

**Comment by liamdebeasi** [comment] 2020-05-19 15:57
Thanks for the follow up. I was able to reproduce this behavior on another Android 10 device. It looks like there is an issue with the Android WebView where it does not honor the OS-level dark theme preference with regards to the `prefers-color-scheme: dark` media query.

I am going to close this as this is not a bug in Ionic Framework, but there is an issue on the Capacitor GitHub with temporary workarounds you can try in your application: https://github.com/ionic-team/capacitor/issues/1978

**Closed by liamdebeasi** 2020-05-19 15:57 UTC
Labels: ionitron: needs reproduction
