### ISSUE TITLE
bug: IonInput fires onIonInput when value is change outside of IonInput

### ISSUE THREAD

**Issue by skmohammadi** [ionic-team/ionic#20718] opened 2020-03-08 11:36 UTC
Same as https://github.com/ionic-team/ionic/issues/20106

**Comment by liamdebeasi** [comment] 2020-03-09 13:22
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20106.

**Closed by liamdebeasi** 2020-03-09 13:22 UTC
Labels: triage
