### ISSUE TITLE
Left 20px on top

### ISSUE THREAD

**Issue by steavengong** [ionic-team/ionic#13625] opened 2017-12-11 08:24 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In my project I run this project in my app content with ios

There have a phenomenon .
In ios 11 is all right.
![jietu20171211-161652](https://user-images.githubusercontent.com/10862092/33821526-00637a2a-de8f-11e7-8a56-e07503636792.jpg)

In ios 10 ,it  left 20px on top .
![jietu20171211-161807](https://user-images.githubusercontent.com/10862092/33821645-8856bac8-de8f-11e7-8a92-aa784ecfdcec.jpg)

is there any setting in ionic can solve this problem?

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
cli packages: (/Users/gongyuwei/.nvm/versions/node/v7.9.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.9.0
    npm  : 5.5.1 
    OS   : macOS Sierra

Misc:

    backend : legacy

**Comment by kensodemann** [comment] 2017-12-11 11:41
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13229. Please make sure you are doing everything mentioned in there (outside of using the nightly builds as the code for that has already been released and you are on a version of the Ionic Framework containing those fixes).

Also double check that you are following all of the advice here: http://blog.ionicframework.com/ios-11-checklist/ including using WKWebView if you are targeting iOS.

Thank you for using Ionic

**Closed by kensodemann** 2017-12-11 11:41 UTC
