### ISSUE TITLE
tabs click not trigger frequently

### ISSUE THREAD

**Issue by Cheng007** [ionic-team/ionic#11855] opened 2017-05-30 08:59 UTC
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Tabs click not trigger frequently，you can see below：
![default](https://cloud.githubusercontent.com/assets/13946264/26575742/09fe6fc4-4559-11e7-9fe8-e212dd974f7f.gif)

**Expected behavior:**
Click event always trigger even though tap on the top of tab

**Steps to reproduce:**
1. 
```dash
npm install -g ionic
```
2. 
```dash
ionic start myProj tabs
```
3.
```dash
npm run ionic:serve
```

**Related code:**

```
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by AmitMY** [comment] 2017-05-30 10:17
Dup: https://github.com/driftyco/ionic/issues/10985

**Comment by jgw96** [comment] 2017-05-30 14:50
Hello, thanks for opening an issue with us. Closing this as a duplicate of https://github.com/ionic-team/ionic/issues/10985.

**Closed by jgw96** 2017-05-30 14:50 UTC
