### ISSUE TITLE
<ion-select>doesn't work on IE / Edge

### ISSUE THREAD

**Issue by athorel** [ionic-team/ionic#9335] opened 2016-11-24 15:19 UTC
**Ionic version:**  
[ ] **1.x**
[x] **2.1.13**

**I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I click on ion-select on IE or Edge browsers, nothing happens.

**Expected behavior:**
A popup should appears with all ion-options.

**Steps to reproduce:**

- Start a new project
- Add the related code in HTML page
- ionic serve on IE / Edge

http://plnkr.co/edit/hDXcxsYzZo2OrGMHT5ST?p=preview

**Related code:**
```
<ion-item>
    <ion-label>Plop</ion-label>
    <ion-select>
        <ion-option value="plop">plop</ion-option>
        <ion-option value="plip">plip</ion-option>
    </ion-select>
  </ion-item>
```
**Other information:**

Issue tested on IE11 / Edge 38

**Ionic info:** 

```
 ordova CLI: 6.4.0
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.7.1
Xcode version: Not installed

```

**Comment by mpaland** [comment] 2016-11-27 12:10
http://plnkr.co/edit/hDXcxsYzZo2OrGMHT5ST?p=preview
This doesn't run here in Edge (14) 38.14393.0.0 on Windows 10 at all.

**Comment by infinnie** [comment] 2016-11-28 00:10
@mpaland #9051

**Comment by webprofusion-chrisc** [comment] 2016-11-30 01:45
FYI, this doesn't work in IE because the select click uses UIevent.detail (which is a numeric result that's not supported in IE 11). my 'monkey patch' approach to supporting IE11 adds special work-around css and overrides the ion-select click event : 
```

detectOldIE() {
    var isOldIE = navigator.userAgent.match(/Trident/);

    if (isOldIE) {
      document.body.classList.add("ie-old");

      (<any>Select).prototype._click = function (ev) {
        //alert("Monkey patched");
        // monkey patch the _click method for ion-select for IE as UIEvent.detail not supported
        /*if (ev.detail === 0) {
            // do not continue if the click event came from a form submit
            return;
        }*/
        ev.preventDefault();
        ev.stopPropagation();
        this.open();
      };
    }
  }
```

**Comment by infinnie** [comment] 2016-11-30 06:04
@webprofusion-chrisc what about Edge 12?

**Comment by webprofusion-chrisc** [comment] 2016-11-30 07:49
@infinnie I haven't had any problems with Edge so far.

**Comment by athorel** [comment] 2016-11-30 09:02
@webprofusion-chrisc Thank you for these information. I will try to patch it myself waiting for an official patch.

**Comment by manucorporat** [comment] 2016-11-30 11:28
@mpaland do you think we can close this issue?

**Comment by morious** [comment] 2017-03-02 02:35
It works well on Edge for me but not working in a native windows build...cordova 6.4.0

**Comment by jgw96** [comment] 2017-06-05 16:38
Hello all! I am going to close this issue as I cannot reproduce this issue on the latest version of edge. Thanks for using Ionic!

**Closed by jgw96** 2017-06-05 16:38 UTC
Labels: platform:windows, v2
