### ISSUE TITLE
feat (picker component) : Use picker inside page

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20938] opened 2020-04-01 14:56 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

![image](https://user-images.githubusercontent.com/23274631/78151988-d9e69c00-7456-11ea-9b20-27813a42a5ff.png)

Current one picker component it opens bottomsheet modal to select
https://ionicframework.com/docs/api/picker

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-04-01 15:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19642.

**Closed by liamdebeasi** 2020-04-01 15:14 UTC
Labels: triage
