### ISSUE TITLE
rc.0 - svg jitter using side menu

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#16793] opened 2018-12-18 05:26 UTC
# Bug Report

![jitterdesktop3](https://user-images.githubusercontent.com/140737/50133471-9572c500-0240-11e9-9f95-a6fc1ec550c0.gif)

![capture469](https://user-images.githubusercontent.com/140737/50132320-69087a00-023b-11e9-8ac7-5bac9bade428.png)

Possibly relates to:
https://github.com/ionic-team/ionic/issues/15216
https://github.com/ionic-team/ionic/issues/15538
https://github.com/ionic-team/ionic/issues/15779
https://github.com/ionic-team/ionic/issues/15798
https://github.com/ionic-team/ionic/issues/16411
https://github.com/ionic-team/ionic/issues/16765

**NOTE:** ISTM that wanting to use tabs with menu and split-pane
is a common element in these reports, i.e. PWA

Ionic CLI does not provide an official example and breaking changes cause issues.

@paulstelzer  @manucorporat helped with this bug: https://github.com/ionic-team/ionic/issues/16776
and this fix: https://github.com/peterennis/aetabs/commit/3d78da72798d6472dcdf7cfd75eb03b740809fd4
but it is a partial solution.

The above error is due to navigating to the side menu Ambigram option and
then the side menu Home option.

Seems like some more navfu is needed :)

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

https://github.com/peterennis/aetabs/commit/3d78da72798d6472dcdf7cfd75eb03b740809fd4
https://aetabs.adaept.com

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
C:\ae\adaept.com\aetabs>ionic info

Ionic:

   ionic (Ionic CLI)             : 4.5.0 (C:\Users\peter\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (2 plugins total)

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by peterennis** [comment] 2018-12-18 06:07
Possibly related: https://github.com/ionic-team/ionic/issues/16783
![sidemenupaths](https://user-images.githubusercontent.com/140737/50135180-15505d80-0248-11e9-9736-60113b1bfcbd.gif)

**Comment by manucorporat** [comment] 2018-12-18 12:46
I don't undestand what the issue is, please follow the issue template

**Comment by peterennis** [comment] 2018-12-18 18:47
@manucorporat Sorry for the confusion.
Key statement:
`The above error is due to navigating to the side menu Ambigram option and
then the side menu Home option.`
This partial fix: peterennis/aetabs@3d78da7
removed jitter when clicking between tabs.
Router outlet destroyed when using the side menu results in jitter and this error:
![capture493](https://user-images.githubusercontent.com/140737/50175518-d951e280-02b1-11e9-81f4-50f1c83c5623.PNG)
Seems related to the new navigation and I am not up to speed on that.

**Comment by paulstelzer** [comment] 2018-12-19 17:44
Please try rc.0

**Comment by peterennis** [comment] 2018-12-20 04:36
@paulstelzer 
No more message for router-outlet destroyed.
Still get errors and jitter.
https://github.com/peterennis/aetabs/commit/60dd933c988d66ac9ba7de719ce609e1fd273975
![capture471](https://user-images.githubusercontent.com/140737/50264012-95ec9680-03cd-11e9-87fe-1e2972419cd5.png)
![capture470](https://user-images.githubusercontent.com/140737/50264017-9dac3b00-03cd-11e9-9647-056f70810caf.png)

**Comment by paulstelzer** [comment] 2018-12-20 08:19
Your jitters issue we already answered (this is not an Ionic issue, you have to solve it inside your code). and setAttributeNs is YOUR code, not Ionic. So your code is wrong.

I close this here

**Closed** 2018-12-20 08:19 UTC
Labels: ionitron: support
