### ISSUE TITLE
VirtualScroll not emptying view after array has been emptied.

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic#7210] opened 2016-07-05 20:23 UTC
#### Short description of the problem:

Somewhere in your code, you want to clear the array of items in and refill it again. This however, cannot be achieved. 
#### What behavior are you expecting?

With `data = []`, our VirtualScroll should also be cleared.

**Steps to reproduce:**
1. VirtualScroll with objects
2. Create a function which would delete your data (`data = []` is enough)
3. Observe VirtualScroll not doing anything.

**Which Ionic Version?** 1.x or 2.x
Ionic2 beta9
#### Plunker that shows an example of your issue

Example 1: Simple example with clearing the data on button press
Plunker that represents the bug is here: http://plnkr.co/edit/tyiZYO7MJXvGZQTccOaC?p=preview

Example 2: Using pipe filterBy which filters and returns filtered array. Check console.log for output. As soon as pipe is returning empty array, VirtualScroll stops working.
http://plnkr.co/edit/SEWhAftqU0XP0En8JJwI?p=preview

**Comment by lordgreg** [comment] 2016-07-13 19:57
Is there any update or is someone assigning/taking care of the issue?

**Comment by AdrianTeh** [comment] 2016-07-16 12:35
Same problem here as well

**Comment by vinlim** [comment] 2016-11-29 06:36
+1 Is the issue addressed?

**Comment by ghenry22** [comment] 2017-01-14 12:22
RC5 looks like it has resolved this, virtualscroll now updates correctly to an empty list

**Comment by ghenry22** [comment] 2017-01-14 12:22
@jgw96 I think this one is resolved

**Comment by jgw96** [comment] 2017-06-27 14:54
Hello all. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/12034

**Closed by jgw96** 2017-06-27 14:54 UTC
Labels: v2, virtualscroll
