### ISSUE TITLE
bug: angular 9 cli livereload -l cause cordova_not_available cordova.js not injected

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic#20450] opened 2020-02-12 12:30 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

ionic cordova run ios -l
casue cordova_not_available

**Expected behavior:**

works fine with angular 8 cli 8.3.25

**Steps to reproduce:**

https://github.com/mohamedsharaf/i5ng9
clone repo and run in ios simulator or device with live reload
npm i
ionic cordova run ios -l

you will see that cordova not injected cordova_not_available

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.0.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/mohamed/Library/Android/sdk/)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.11.1 (/usr/local/Cellar/node/12.11.1/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

mohamed@mbp i5ng9 %
```

**Comment by liamdebeasi** [comment] 2020-02-12 14:14
Thanks for the issue. It looks like the issue is caused by this: https://github.com/ionic-team/angular-toolkit/issues/184.

There is a PR that is open and should be merged soon: https://github.com/ionic-team/angular-toolkit/pull/201

**Closed by liamdebeasi** 2020-02-12 14:14 UTC
Labels: triage

**Comment by danieljameswilliams** [comment] 2020-02-19 10:23
This is still a problem for me

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.2
   @angular-devkit/schematics    : 9.0.2
   @angular/cli                  : 9.0.2
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.13.7
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-02-19 14:02
@danieljameswilliams Can you please open an issue here: https://github.com/ionic-team/angular-toolkit along with a reproduction?
