### ISSUE TITLE
bug: Return to flicker

### ISSUE THREAD

**Issue by eternityBUG** [ionic-team/ionic#19557] opened 2019-10-06 08:59 UTC
"@ionic/angular": "^4.10.0",
  "@ionic/core": "^4.10.0",

The return of a child page causes a flicker

The animation doesn't seem to stop at the end frame

**Comment by liamdebeasi** [comment] 2019-10-07 13:36
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19491.

**Closed by liamdebeasi** 2019-10-07 13:36 UTC
Labels: triage
