### ISSUE TITLE
bug: On AOT with Ionic 5 and Angular 9 Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#21352] opened 2020-05-21 14:17 UTC
# Bug Report

AOT with Ionic 5 and Angular 9 gives the following error:

Seems related to [https://github.com/angular/angular/issues/35788](https://github.com/angular/angular/issues/35788)

Seems something is incompatible with Ivy.

**Ionic version:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.2, (and 13 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.6.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Catalina
   Xcode      : Xcode 11.3 Build version 11C29

```

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

Try with ng serve --aot

**Related code:**

```
"dependencies": {
    "@agm/core": "^1.1.0",
    "@agm/js-marker-clusterer": "^1.1.0",
    "@angular-devkit/build-webpack": "0.901.5",
    "@angular/animations": "^9.1.6",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "^9.1.9",
    "@angular/core": "^9.1.9",
    "@angular/forms": "^9.1.9",
    "@angular/http": "7.2.2",
    "@angular/platform-browser": "^9.1.9",
    "@angular/platform-browser-dynamic": "^9.1.9",
    "@angular/platform-server": "^9.1.9",
    "@angular/router": "^9.1.9",
    "@ionic-native/android-permissions": "^5.26.0",
    "@ionic-native/core": "^5.26.0",
    "@ionic-native/dialogs": "^5.26.0",
    "@ionic-native/geolocation": "^5.26.0",
    "@ionic-native/image-picker": "^5.26.0",
    "@ionic-native/ionic-webview": "^5.26.0",
    "@ionic-native/keyboard": "^5.26.0",
    "@ionic-native/launch-navigator": "^5.26.0",
    "@ionic-native/native-geocoder": "^5.26.0",
    "@ionic-native/native-page-transitions": "^5.26.0",
    "@ionic-native/paypal": "^5.26.0",
    "@ionic-native/splash-screen": "^5.26.0",
    "@ionic-native/status-bar": "^5.26.0",
    "@ionic/angular": "^5.1.1",
    "@ionic/angular-server": "^5.1.1",
    "@ng-toolkit/universal": "^8.1.0",
    "@nguniversal/express-engine": "^9.1.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "4.0.0",
    "@types/chart.js": "^2.8.4",
    "@types/jest": "^25.2.1",
    "@types/mocha": "^7.0.2",
    "acorn": "6.1.1",
    "agm-direction": "^0.7.9",
    "angular": "^1.7.9",
    "angular2-jwt": "^0.2.3",
    "angularx-social-login": "^2.3.1",
    "animate.css": "^4.1.0",
    "balanced-match": "1.0.0",
    "chart.js": "^2.5.0",
    "color": "^3.1.2",
    "com.telerik.plugins.nativepagetransitions": "^0.6.5",
    "cordova-android": "^7.1.4",
    "cordova-browser": "^5.0.4",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-facebook4": "^5.0.0",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "2.5.4",
    "domino": "^2.1.4",
    "easy-pie-chart": "^2.1.7",
    "express": "^4.17.1",
    "hammerjs": "^2.0.8",
    "ionic": "^5.2.7",
    "ionic2-calendar": "^0.6.4",
    "jquery": "^3.4.1",
    "js-marker-clusterer": "^1.0.0",
    "ng-uikit-pro-standard": "git+https://oauth2:1DexEoEKoCjpNzgJc_fw@git.mdbootstrap.com/mdb/angular/ng-uikit-pro-standard.git#9.2.0",
    "ngx-cookie-banner": "^0.1.0",
    "ngx-paypal": "^6.1.0",
    "ngx-pinch-zoom": "^2.4.4",
    "openvidu-browser": "^2.13.0",
    "pinch-zoom-js": "^2.3.4",
    "rxjs": "^6.5.5",
    "rxjs-compat": "^6.5.2",
    "screenfull": "^3.3.0",
    "socket.io": "^2.3.0",
    "ssr-window": "^2.0.0",
    "tslib": "^2.0.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
    "webpack-node-externals": "^1.7.2",
    "zone.js": "^0.10.3"
  },
```

**Other information:**

**Ionic info:**

```
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:548)
    at Function.get (core.js:25892)
    at getNgModuleDef (core.js:1865)
    at new NgModuleFactory (core.js:24245)
    at Compiler_compileModuleSync__POST_R3__ (core.js:27071)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (core.js:27076)
    at MergeMapSubscriber.project (router.js:3632)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (mergeMap.js:61)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (mergeMap.js:51)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at resolvePromise (zone.js:836)
    at resolvePromise (zone.js:795)
    at zone.js:897
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:27453)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
    at drainMicroTaskQueue (zone.js:611)
    at ZoneTask.invokeTask [as invoke] (zone.js:517)
    at invokeTask (zone.js:1671)
```

**Comment by mhartington** [comment] 2020-05-21 14:47
Ionic is fully compatible with Ivy and should not be having this issue. Have you isolated it to a fresh Ionic project? You have quite a few lib listed in your deps that could also be causing the problem.


I have tested a fresh Ionic project and cannot replicate, so the problem is most likely with your other libs.

Closing.

**Closed by mhartington** 2020-05-21 14:47 UTC
Labels: triage

**Comment by indraraj26** [comment] 2020-05-25 10:52
restart ionic serve and you are good to go. it is an angular compiler bug it is failed to pickup AOT.
