### ISSUE TITLE
bug: ion-datetime assigning am/pm automatically

### ISSUE THREAD

**Issue by andremarchezini** [ionic-team/ionic#19260] opened 2019-09-04 05:43 UTC
# Bug Report

**Ionic version:**

[x] **4.8.1**

**Current behavior:**
If you have ion-datetime set to 12 hour the periods am/pm gets changed automatically as you change the hour 

**Expected behavior:**
User manually changes am/pm 

**Steps to reproduce:**
![iondatetime](https://user-images.githubusercontent.com/26728041/64228541-c5bada80-cf19-11e9-8804-8c8672e5c090.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\Andre\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.5.2
   native-run  : 0.2.7

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-09-04 12:51
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19175. Note that the referenced issue has been added to the main datetime issue tracker: https://github.com/ionic-team/ionic/issues/16630

**Closed by liamdebeasi** 2019-09-04 12:51 UTC
Labels: triage
