### ISSUE TITLE
bug: IonTextarea with `autoGrow` set will collapse/disappear in the presence of an IonButton

### ISSUE THREAD

**Issue by GRardB** [ionic-team/ionic#21369] opened 2020-05-25 15:23 UTC
# Bug Report

**Ionic version:** 5.1.1

**Current behavior:**
When using an `<IonTextarea autoGrow . . .` on the same page as an `IonButton`, the textarea is defaults to a height of 0, which almost completely hides it (there is some overflow). In order to get it to display correctly, you must focus on the textarea and type a character, in which case the `autoGrow` behavior kicks in and sets the correct height.

**Expected behavior:**
`<IonTextarea autoGrow . . .` should be displayed correctly no matter what else is on the page.

**Steps to reproduce: / Related code:**
1. [Go to the sandbox example](https://codesandbox.io/s/currying-darkness-qjbjb?file=/src/pages/Home.tsx)
2. Observe how in Firefox, there is only a button displayed. In Chrome, you can see one line of the textarea text on top of the button.
3. Move your cursor to the top of the button. You will notice a text selection cursor. Click to focus on the textarea that's triggering the cursor change.
4. Type a character. You will see the textarea grow to its correct size.

Something to note is that this only seems to happen on page load.  If you remove the `IonButton` from the page (`pages/Home.tsx`) and let the hot reload (or whatever Code Sandbox is doing) do its thing, the bug doesn't get fixed. However, if you refresh the preview browser after removing the `IonButton`, the textarea works as expected.

In my actual application, I'm running into the same issues with `IonMenuButton` and `IonMenu`. Or at least I think so; it's a bit difficult to rule out every possibility, but it's a pretty big issue which I can't seem to find a workaround for.

One last thing to note is that I first thought it was an issue with `IonTextarea`, so I tried using both the `react-textarea-autosize` and `react-autosize-textarea` packages, but the same thing happened with those.

Any help would be _extremely_ appreciated.

**An example gif**
![example](https://user-images.githubusercontent.com/748180/82825651-7712ef00-9e60-11ea-9c8b-caa55f484d2c.gif)

**Ionic info:**
```
Ionic:
   Ionic CLI       : 6.9.1 (/Users/grardb/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:
   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v11.14.0 (/Users/grardb/.nvm/versions/node/v11.14.0/bin/node)
   npm    : 6.7.0
   OS     : macOS High Sierra
```

**Comment by liamdebeasi** [comment] 2020-05-26 13:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21242 (The particular issue is different, but the underlying bug in Ionic Framework looks to be the same).

**Closed by liamdebeasi** 2020-05-26 13:06 UTC
Labels: triage
