### ISSUE TITLE
bug: Hardware button not triggering with subscribeWithPriority

### ISSUE THREAD

**Issue by Ketec** [ionic-team/ionic#18852] opened 2019-07-22 12:26 UTC
```
this.platform.backButton.subscribeWithPriority(100, () => {
      console.log('#triggered');
})
```

In any page. Even app.component does not trigger.
Looking at the source, ionic uses 0 and everything higher should overwrite it.

Could easily get this even in using ionic tabs template and adding the code above to the constructor.
It also does it's own stack navigation instead, and does not close the app (instead routes to / or index.php and causes app to reload).

Is the subscription lost somewhere and the handlers in hardware-back-button.ts  only got ionic handle?

Tested on  Android 9. Cordova event does trigger.

Latest ionic angular and core.

When debugging, I never hit the `ev.register(priority, callback);`  line.

looking at the code it seems to be "ev.detail.register" not "ev.register"

**Comment by liamdebeasi** [comment] 2019-07-22 12:52
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17824.

**Closed by liamdebeasi** 2019-07-22 12:52 UTC
Labels: triage
