### ISSUE TITLE
ion-split-pane and menuToggle problem

### ISSUE THREAD

**Issue by HudsonAfonso** [ionic-team/ionic#11964] opened 2017-06-07 17:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a ion-split-pane and the menuToggle button, when I use the cell phone I have no problem, but when I open it on a tablet, the menu is visible but the button is also visible, if I resize the window the button disappears , but when I load directly into the resolution of the table it continues to show the button.
![](http://penseinteligente.com.br/menuToggle.gif)

**Expected behavior:**
When the menu is visible because of the resolution, the menuToggle button should be hidden.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.0.0 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 5.1.1, ios 4.3.1
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.6 
```

**Comment by godspeed529** [comment] 2017-06-07 18:57
[Here](https://forum.ionicframework.com/t/split-pane-menu-hamburger-visible-when-first-opened-at-large-size/85825) is a two month old discussion thread in the ionic community forum detailing the issue.

**Comment by HudsonAfonso** [comment] 2017-06-07 19:38
Yes there is and even with 2 answers and no solution, it's the same as mine but I created an issue to address the problem and find a solution is either my mistake or a bug.

Is it my mistake or a bug?

**Comment by godspeed529** [comment] 2017-06-07 23:45
My comment was only meant to buttress your ticket with more information about others encountering the same issue. Hopefully the Ionic team can deliver a speedy resolution to this issue ... Lol ... But not before the resolve all blocking issues around lazy loading especially in a PWA context.

Thx for reporting the issue.

😎

**Comment by jgw96** [comment] 2017-06-08 14:18
Hello @HudsonAfonso , would you be able to provide a repo we could use to reproduce this please?

**Comment by jgw96** [comment] 2017-07-03 15:29
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-03 15:29 UTC
Labels: needs info, v3

**Comment by salbahra** [comment] 2017-10-06 17:06
Just to add I had the same issue and it was due to `*ngIf` on the `<ion-menu>`. I simply changed this to `[hidden]` and it works great!

**Comment by felly** [comment] 2017-10-13 10:05
Hello!
I just ran into the same problem and changing ```*ngIf``` to ```[hidden]``` seems to work at first but raises another issue:

If you put an ```<ion-header>``` in the ```<ion-menu>``` the header overlaps the content at first. The issue seems to be somewhere around the ```<ion-content>```:
**At start:**
```html
<ion-content class="content content-md">
  <div class="fixed-content"></div>
  <div class="scroll-content">
```

**After resizing, the elements got updated to:**
```html
<ion-content class="content content-md">
  <div class="fixed-content" style="margin-top: 56px;"></div>
  <div class="scroll-content" style="margin-top: 56px;">
```

@jgw96 can you reopen this issue?

**Ionic Info:**
```
cli packages: (/Users/felly/.nvm/versions/node/v7.5.0/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.2
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v7.5.0
    npm               : 4.1.2
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235
```

**Comment by salbahra** [comment] 2017-10-13 15:43
@felly I also had this issue and it seems putting an `*ngIf` on the `<ion-content>` using the same condition as the hidden on the `<ion-menu>` fixes the issue. At least it's a work around until a fix is out.

**Comment by felly** [comment] 2017-10-13 15:49
@salbahra Thanks for the tip! Works for me too 👍

**Comment by dev-ju** [comment] 2018-01-05 21:17
Hi, 
Any better fix for this issue ?
If i put *ngIf on the <ion-content> of my <ion-menu> the top of the <ion-content> not display well because i use header in my menu, i think i can fix this with scss but it not a very good way to fix that (fix a fix...)

**Comment by salbahra** [comment] 2018-01-05 21:55
You can use ViewChild to grab the content from the menu and update it by calling it’s refresh method after changing the variable which shows/hides the items.
