### ISSUE TITLE
bug: [ionic-5.0.0-rc1] ion-radio with filter dynamic on collection, not selected item

### ISSUE THREAD

**Issue by LOUNNAS** [ionic-team/ionic#20323] opened 2020-01-28 23:37 UTC
**Ionic version:**
[x] 5.0.0-rc1

**Current behavior:**
By filtering on the categories collection, once the category with objectId equal to selectedId is removed from the collection even if it will be present after it is never selected.

**Expected behavior:**
The category with the objectId  is equal to selectedId will be selected if it is present in the categories collection

**Source code:**

```
<ion-list lines="full">
        <ion-radio-group [value]="selectedId" (ionChange)="onSelect($event)">
            <ion-item *ngFor="let category of categories$ | async; trackBy: trackByFn">
                <ion-label>{{category.name}}</ion-label>
                <ion-radio slot="end" [value]="category.objectId"></ion-radio>
            </ion-item>
        </ion-radio-group>
    </ion-list>
```

Thanks for your help.

**Comment by liamdebeasi** [comment] 2020-01-29 00:02
Thanks for the issue. Can you clarify what the issue is and what you are expecting to see? I am not sure I understand the issue description. Also, can you provide a repo with the code required to reproduce this issue? This will help us fix the issue faster rather than trying to reproduce the issue with a code snippet.

**Comment by LOUNNAS** [comment] 2020-01-29 11:27
Hello sorry for my bad english.

Here is the link to the repo [](https://github.com/LOUNNAS/ionic-radio.git )

Command to execute:
1: npm install.
2: ionic serve.

Attached a gif also a showing the behavior.


![3njarv](https://user-images.githubusercontent.com/18683428/73353006-b35b8780-4292-11ea-910c-f95033d2d688.gif)


Thanks.

**Comment by liamdebeasi** [comment] 2020-01-30 17:29
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20343 and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-01-30 17:29 UTC
Labels: triage
