### ISSUE TITLE
iOS: Scrolling in ion-select is too sensitive and checks upon small scrolling

### ISSUE THREAD

**Issue by barajagmartin** [ionic-team/ionic#13552] opened 2017-11-30 16:40 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When using this on an iOS device and I'm scrolling in really small steps, it checks the checkboxes even though I'm not tapping them. There is no problem when doing this on Android or when I run `ionic serve` and view the app on an iOS device.

It doesn't happen when doing long scrolls though.

**Expected behavior:**
I expect the device to not check the checkboxes when scrolling no matter how long the scrollings are.

**Steps to reproduce:**
1. Add the code below to an app
2. Compile and run in an iOS device
3. Click the selector
4. Start scrolling in small distances/scrollings.
5. Note that the checkboxes gets checked.

**Related code:**
```
<ion-select (ionChange)="updateStuff()" [(ngModel)]="model" multiple="true" >
    <ion-option value="{{item.id}}" *ngFor="let item of items; let i = index">
        {{item.name}}
    </ion-option>
</ion-select>
```

**Other information:**
Only happens on iOS. Not on Android!

**Ionic info:**

```
cli packages: (/Users/ctk1/Desktop/Applikation-for-lagerforing-av-material/ionic-app/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.0.1
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.5.0

System:

    Node  : v6.11.4
    npm   : 5.1.0 
    OS    : macOS Sierra
    Xcode : Xcode 9.0 Build version 9A235 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment] 2017-11-30 17:05
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Or provide the TypeScript that goes with your HTML markup above.

Thanks for using Ionic!

**Comment by gixen82** [comment] 2017-12-06 08:00
Hey,
the issue is easily reproduced with the following markup:
`<ion-select multiple="true" >
    <ion-option value="1">
        1
    </ion-option>
    <ion-option value="2">
        2
    </ion-option>
    <ion-option value="3">
        3
    </ion-option>
    <ion-option value="4">
        4
    </ion-option>
    <ion-option value="5">
        5
    </ion-option>
    <ion-option value="6">
        6
    </ion-option>
    <ion-option value="7">
        7
    </ion-option>
</ion-select>`

Just start a blank project, paste this into a page, and run it on iOS.

**Comment by barajagmartin** [comment] 2017-12-18 14:44
I think that what @gixen82 should be enough to reproduce.

**Comment by barajagmartin** [comment] 2017-12-21 09:00
Was that enough?

**Comment by gixen82** [comment] 2017-12-21 13:08
Also, its worth mentioning that it should be tested on an actual device. Not emulator. Not that easy to reproduce on an emulator.

**Comment by kensodemann** [comment] 2017-12-21 20:51
@barajagmartin - probably. I will try to take a look at it tomorrow and see.

**Comment by kensodemann** [comment] 2017-12-22 15:14
I have tried the code from @gixen82 and it works just fine. I can easily scroll without selecting anything and as a matter of fact, I have to be fairly deliberate about selecting something in the popup. I can even sit with my finger on `5` (for example) for a couple of seconds and if I let go it will be selected, but if I do the same and then scroll even a little it will not be selected.

I notice that you are using a fairly old version of the Ionic Framework (3.5.0). My test app used the latest (3.9.2).  Maybe you could try upgrading your libraries and see if that helps you out?

I have included my ionic info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v8.9.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/kensodemann/Library/Android/sdk/

Misc:

    backend : pro

```

I am going to close this as something that cannot be duplicated, but if you can provide a sample application that duplicates the issue using the latest version of the Ionic Framework I will gladly reopen it.

**Closed by kensodemann** 2017-12-22 15:14 UTC
Labels: needs info

**Comment by gixen82** [comment] 2018-01-31 09:41
@kensodemann , did you try this on an actual device, not emulator?

**Comment by kensodemann** [comment] 2018-01-31 11:32
@gixen82 - yes, iPhone 7, iOS 11
