### ISSUE TITLE
ion-searchbar refocuses after cancel on ios

### ISSUE THREAD

**Issue by ivanovvitaly** [ionic-team/ionic#12156] opened 2017-06-26 12:37 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a ion-searchbar component with cancel button set to true in navbar. When I click cancel button, keyboard closes and searchbar loses focus, then immediately sets focus to searchbar again and keyboard pops up. This happens every time you click cancel button. If you click anywhere on the page searchbar blures. 

**Expected behavior:**

Searchbar should not activate focus after cancel was clicked.

**Steps to reproduce:**

**Related code:**

```
<ion-header>
    <ion-navbar>
        <ion-searchbar
            [formControl]="searchQuery" 
            [showCancelButton]="true" 
            (ionCancel)="reset($event)">
        </ion-searchbar>
    </ion-navbar>
</ion-header>

//ts code

import { Keyboard } from "ionic-angular";

public searchQuery = new FormControl('')

constructor(public keyboard: Keyboard) { }

public reset() {
    this.searchQuery.setValue('')
    
    // this code helps to blur the search input, but for user it look weird,  keyboard pops up again after cancel and then hides. 
    setTimeout(() => {
        this.keyboard.close()  
    }, 500)
}
```

**Other information:**

It is stable bug that I'm able to reproduce on the blank project on ios device and emulator. Didn't try on android yet.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.0
    ios-sim    : not installed
    npm        : 5.0.3
```

**Comment by jgw96** [comment] 2017-06-26 15:06
Thanks for using Ionic. Would you mind trying this in Ionic 3.4.2 (the latest) and see if you still have this issue? Thanks!

**Comment by ivanovvitaly** [comment] 2017-06-26 15:43
I don't see 3.4.2 in npm

**Comment by jgw96** [comment] 2017-06-29 15:38
Hello @ivanovvitaly , sorry I mean the framework and not the cli. To install the latest framework run `npm install ionic-angular@latest --save`.

**Comment by ivanovvitaly** [comment] 2017-06-29 15:53
the same behavior, keyboard reopens after canceled

**Comment by jkamboj** [comment] 2017-06-29 20:41
i am also getting the same behavior. keyboard reopens after canceled. this issue has been started ionic 3.3 onwards

**Comment by steveacalabro** [comment] 2017-07-17 03:11
+1

**Comment by jgw96** [comment] 2017-07-18 15:01
Hello all! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/10692. This is something that we will be looking into soon.

**Closed** 2017-07-18 15:03 UTC
Labels: needs info, v2

**Comment by guoyongxin** [comment] 2018-01-08 08:51
Hi @ivanovvitaly, did you resolve this? I got the same issue, but didn't find any elegant solution yet.
