### ISSUE TITLE
No mousemove event working in my component

### ISSUE THREAD

**Issue by arjunkalburgi** [ionic-team/ionic#20008] opened 2019-11-27 17:28 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I've tried `<div #item (mousemove)='drag($event)' class="this_item"></div>`
I've tried `this.container.nativeElement.addEventListener('mousemove', this.drag, false);`
I've tried `@HostListener('mousemove', ['$event']) drag()`

Nothing runs my drag function. Everything works in storybook and in [codepen](https://codepen.io/arjunkalburgi/pen/xxxpzPx) so it must be an issue with Ionic?

**Expected behavior:**
Any of the above 3 should fire my drag function continuously on mouse moving. 

**Steps to reproduce:**
1. Create an ionic project 
2. Make a component exactly like this: https://codepen.io/arjunkalburgi/pen/xxxpzPx (might have to mess around with the .this_item css to make it more clickable in Ionic)
3. Ionic serve and see the component. It doesn't work. 
4. You can also put a `console.log` in the drag() function. it never fires. 

**Related code:**
https://codepen.io/arjunkalburgi/pen/xxxpzPx

**Ionic info:**
```
$ ionic info

Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.13.1 (/usr/local/bin/node)
   npm     : 6.13.1
   OS      : macOS Catalina
   Xcode   : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment] 2019-11-27 19:52
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this issue in an Ionic Angular app using the code provided.

**Comment by arjunkalburgi** [comment] 2019-11-27 21:15
Here ya go: 

https://github.com/arjunkalburgi/ionicside2confirm

If it's working for you then there's some hope for me!

**Comment by liamdebeasi** [comment] 2019-12-05 15:05
Thanks for the follow up. I was able to reproduce the issue you are describing; however, I was also able to reproduce the issue in a fresh Angular project without Ionic Framework. I am going to close this issue as this does not appear to be a bug in Ionic Framework. I recommend you double check your code for any errors. Thanks!

**Closed by liamdebeasi** 2019-12-05 15:05 UTC
Labels: triage
