### ISSUE TITLE
feat: ion-back-button show support location.back() in order to preserve queryParams of previous route

### ISSUE THREAD

**Issue by aavelyn** [ionic-team/ionic#18234] opened 2019-05-09 07:28 UTC
# Feature Request

**Ionic version:**
[x] **4.3**

**Describe the Feature Request**
I have a use case where I have filter properties stored in the queryParams of my listPage, which leads me to a listItemPage. When I use the ion-back-button to navigate back, I would except to see the same queryParams from the previous route which is not the case.

I figure, that underneath the ion-back-button, you are using the router.navigate() instead of location.back()?

**Describe Preferred Solution**
a simple solution would be to add a "useLocationBack" property to the ion-back-button. But i don't know if the transitionBack animation would still work then...

**Comment by liamdebeasi** [comment] 2019-05-09 13:01
Hi there,

Thanks for the feature request. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16744. We are investigating and hope to have this issue resolved soon.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-09 13:01 UTC
Labels: triage
