### ISSUE TITLE
bug: Buggy scrollable segments

### ISSUE THREAD

**Issue by danielsogl** [ionic-team/ionic#18599] opened 2019-06-23 08:44 UTC
# Bug Report
Scrollable segment buttons are overlapping each other on scroll

**Ionic version:**

[x] **4.5**

**Current behavior:**

The segment buttons are overlapping

![](https://media.giphy.com/media/SuI8wRkjj3Jr2tuEGs/giphy.gif)

**Expected behavior:**

Scrolling should not overlap buttons

**Steps to reproduce:**

Create a scrollable segment inside an `ion-footer --> ion-toolbar` element

**Related code:**

```ts
<ion-footer>
  <ion-toolbar>
    <ion-segment
      color="danger"
      mode="md"
      scrollable
      [value]="'readme'"
      (ionChange)="changeTab($event)"
    >
      <ion-segment-button mode="md" value="readme">
        <ion-icon name="book"></ion-icon>
      </ion-segment-button>
      <ion-segment-button mode="md" value="informations">
        <ion-icon name="information-circle"></ion-icon>
      </ion-segment-button>
      <ion-segment-button mode="md" value="dependencies">
        <ion-icon name="cube"></ion-icon>
      </ion-segment-button>
      <ion-segment-button mode="md" value="versions">
        <ion-icon name="flag"></ion-icon>
      </ion-segment-button>
      <ion-segment-button mode="md" value="stats">
        <ion-icon name="stats"></ion-icon>
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-footer>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.1.0 (/Users/danielsogl/.nvm/versions/node/v12.4.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 17 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.4.0)
   native-run  : 0.2.6 

System:

   ios-sim : 8.0.1
   NodeJS  : v12.4.0 (/Users/danielsogl/.nvm/versions/node/v12.4.0/bin/node)
   npm     : 6.9.0
   OS      : macOS Mojave
   Xcode   : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment] 2019-06-24 12:39
Hi there,

Thanks for the issue! I am not able to reproduce this on iOS 12.2 in Safari: https://codepen.io/liamdebeasi/pen/orwjyr

Is this issue only happening in a standalone app? Additionally, which version of iOS are you testing on?

Thanks!

**Comment by danielsogl** [comment] 2019-06-24 19:55
Hey @liamdebeasi, I haven't think about a problem with the latest iOS 13 Beta 2 that im running on my test device. On my iOS 12 device the bug is not existing.

**Comment by liamdebeasi** [comment] 2019-06-25 12:50
Ah that makes sense - I have noticed a similar behavior when scrolling images horizontally on a device running the iOS 13 beta. I am going to close this issue as it seems to be a bug in the iOS beta, but feel free to open a new issue if you encounter this issue again on a stable version of iOS.

Thanks!

**Closed by liamdebeasi** 2019-06-25 12:50 UTC
Labels: triage
