### ISSUE TITLE
Ion Inputs don't have underlines inside of Cards

### ISSUE THREAD

**Issue by dudeofawesome** [ionic-team/ionic#12694] opened 2017-08-18 01:13 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request
**Current behavior:**
I'm noticing that Ion `Input`s inside a `Card` don't have the normal underline beneath them unless they're active. 

![image](https://user-images.githubusercontent.com/1683595/29380268-03cfbfe6-827a-11e7-9366-e4864a8a7ccf.png)

**Expected behavior:**
`Input`s should have an underline beneath them

![image](https://user-images.githubusercontent.com/1683595/29440207-b269ecf4-8377-11e7-8bb7-fa6c0cf6fcf5.png)

**Steps to reproduce:**
http://plnkr.co/edit/I5vapkRia0I3yyP37hgf?p=preview

```html
<ion-card>
  <ion-card-content>
    <ion-card-title>Title</ion-card-title>

    <ion-item>
      <ion-label floating>Test input</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>

  </ion-card-content>
</ion-card>
```

**Other information:**
It looks like it's caused by some styling on `ion-card`.

```css
.card-md .item-md.item-block .item-inner {
    border: 0;
}
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (~/Github/ionic-bug-inputs/node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : macOS Sierra
```

**Comment by kensodemann** [comment] 2017-08-18 01:27
Hello! Thank you for opening an issue with us! This issue is a duplicate of #11640 so I will close this one. Please track issue #11640 for further updates.

Thank you for using Ionic

**Closed by kensodemann** 2017-08-18 01:27 UTC
