### ISSUE TITLE
Not correctly run in android 5 and 4.4 with ionic 4.2.0

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#18011] opened 2019-04-10 06:21 UTC
I updated ionic of 4.0.0rc2 to 4.2.0 and update all plugins then get output but not correctly run android 4.4 and 5.
console log in android 5:

 deviceready not firing
ionic info :

      Ionic:

       ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
       Ionic Framework               : @ionic/angular 4.2.0
       @angular-devkit/build-angular : 0.13.8
       @angular-devkit/schematics    : 7.3.8
       @angular/cli                  : 7.3.8
       @ionic/angular-toolkit        : 1.5.0

      Cordova:

       cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
       Cordova Platforms     : android 7.1.4
       Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)

package.json :

     "dependencies": {
      "@angular/common": "~7.2.12",
      "@angular/core": "~7.2.12",
      "@angular/forms": "~7.2.12",
      "@angular/http": "~7.2.12",
      "@angular/platform-browser": "~7.2.12",
      "@angular/platform-browser-dynamic": "~7.2.12",
      "@angular/router": "~7.2.12",
      "@ionic-native/android-permissions": "^5.4.0",
      "@ionic-native/barcode-scanner": "^5.4.0",
      "@ionic-native/core": "^5.4.0",
      "@ionic-native/deeplinks": "^5.4.0",
      "@ionic-native/device": "5.4.0",
      "@ionic-native/diagnostic": "5.4.0",
      "@ionic-native/file": "5.4.0",
      "@ionic-native/file-opener": "5.4.0",
      "@ionic-native/file-transfer": "5.4.0",
      "@ionic-native/location-accuracy": "5.4.0",
      "@ionic-native/network": "5.4.0",
      "@ionic-native/social-sharing": "5.4.0",
      "@ionic-native/splash-screen": "5.4.0",
      "@ionic-native/status-bar": "5.4.0",
      "@ionic/angular": "4.2.0",
      "@ionic/storage": "^2.2.0",
      "@ngx-translate/core": "^11.0.1",
      "@ngx-translate/http-loader": "^4.0.0",
      "@types/materialize-css": "^1.0.6",
      "com.lampa.startapp": "^6.1.6",
      "cordova": "^8.1.2",
      "cordova-android": "7.1.4",
      "cordova-plugin-android-permissions": "^1.0.0",
      "cordova-plugin-device": "^2.0.2",
      "cordova-plugin-file": "^6.0.1",
      "cordova-plugin-file-opener2": "^2.2.0",
      "cordova-plugin-file-transfer": "^1.7.1",
      "cordova-plugin-inappbrowser": "^3.0.0",
      "cordova-plugin-ionic-keyboard": "^2.1.3",
     "cordova-plugin-ionic-webview": "^4.0.1",
     "cordova-plugin-mauron85-background-geolocation": "^3.0.1",
     "cordova-plugin-network-information": "^2.0.1",
     "cordova-plugin-request-location-accuracy": "^2.2.3",
     "cordova-plugin-sms-receive": "^1.0.2",
     "cordova-plugin-splashscreen": "^5.0.2",
     "cordova-plugin-statusbar": "^2.4.2",
     "cordova-plugin-whitelist": "^1.3.3",
     "cordova-sqlite-storage": "^3.2.0",
     "cordova.plugins.diagnostic": "^4.0.12",
     "core-js": "^3.0.1",
     "ionic-plugin-deeplinks": "^1.0.19",
     "ionicons": "4.5.5",
     "lodash": "4.17.11",
     "materialize-css": "^1.0.0",
     "moment": "2.24.0",
     "moment-jalaali": "0.8.3",
     "parse-push-plugin": "git+https://github.com/taivo/parse-push-plugin.git",
     "phonegap-plugin-barcodescanner": "^8.0.1",
     "rxjs": "6.4.0",
     "rxjs-compat": "^6.4.0",
     "ws": "^6.2.1",
     "zone.js": "^0.9.0"
     },

    "devDependencies": {
     "@angular-devkit/architect": "~0.13.8",
     "@angular-devkit/build-angular": "~0.13.8",
     "@angular-devkit/core": "~7.3.8",
     "@angular-devkit/schematics": "~7.3.8",
     "@angular/cli": "~7.3.8",
     "@angular/compiler": "~7.2.12",
     "@angular/compiler-cli": "~7.2.12",
     "@angular/language-service": "~7.2.12",
     "@ionic/angular-toolkit": "^1.5.0",
     "@ionic/lab": "1.0.24",
     "@types/jasmine": "~3.3.12",
     "@types/jasminewd2": "~2.0.6",
     "@types/node": "~11.13.2",
     "codelyzer": "~5.0.0",
     "jasmine-core": "~3.4.0",
     "jasmine-spec-reporter": "~4.2.1",
     "karma": "~4.0.1",
     "karma-chrome-launcher": "~2.2.0",
     "karma-coverage-istanbul-reporter": "~2.0.5",
     "karma-jasmine": "~2.0.1",
     "karma-jasmine-html-reporter": "^1.4.0",
     "protractor": "~5.4.2",
     "ts-node": "~8.0.3",
     "tslint": "~5.15.0",
     "typescript": "~3.2.4"
     }

**Comment by liamdebeasi** [comment] 2019-04-10 13:10
Hi there,

Thanks for the issue. Can you verify you have done the following:

1. Reviewed the [Breaking Changes](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md) (We have a handy migration linter that can help with this: https://github.com/ionic-team/v4-migration-tslint)
2. Enabled polyfills in your `polyfills.ts` file

If you are still running into this issue, can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by shomid** [comment] 2019-04-10 13:30
> Hi there,
> 
> Thanks for the issue. Can you verify you have done the following:
> 
> 1. Reviewed the [Breaking Changes](https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md) (We have a handy migration linter that can help with this: https://github.com/ionic-team/v4-migration-tslint)
> 2. Enabled polyfills in your `polyfills.ts` file
> 
> If you are still running into this issue, can you provide a repository with the code required to reproduce this issue?
> 
> Thanks!
enabled polyfills.
source code attached.
in android 6 and 7 and 8 work correctly but not correctly in android 4.4 and 5
    
[amyar24servitor-master.zip](https://github.com/ionic-team/ionic/files/3063994/amyar24servitor-master.zip)

**Comment by liamdebeasi** [comment] 2019-04-10 14:10
Hi there,

I was unable to get your project to compile (I had to disable the materialize CSS imports to get it to work). Afterwards, I was unable to build the app using `cordova build android`. Can you please check your project configuration and make sure everything has been setup properly?

**Comment by shomid** [comment] 2019-04-10 15:00
> Hi there,
> 
> I was unable to get your project to compile (I had to disable the materialize CSS imports to get it to work). Afterwards, I was unable to build the app using `cordova build android`. Can you please check your project configuration and make sure everything has been setup properly?

1.npm install
2.ionic cordova platforms add android@7.1.4
3.add below code to build.gradle in platforms/android/app :
     
     configurations.all {
       resolutionStrategy {
          force "com.android.support:support-v4:27.+"
       }
    }

**Comment by liamdebeasi** [comment] 2019-04-10 15:21
Hi there,

Thanks for the follow up. I needed to add the `cordova-android-support-gradle-release` plugin.

I am able to run your application fine on a device running Android 5.1. Can you describe the behavior you are currently seeing and the behavior you are expecting to see?

**Comment by shomid** [comment] 2019-04-10 17:23
also run on android 6 or above to see the difference.
in android 5 or 4.4 not show icons and not work ngx-translate(my app is persian language).
please debug and see console log

**Comment by shomid** [comment] 2019-04-11 08:16
the problem is with zone.js.
convert 0.9.0 to 0.8.29 resolve app in android 5 and 4.4
why ?

**Comment by liamdebeasi** [comment] 2019-04-11 12:32
Hi @shomid,

The `@ionic/angular` package depends on zone.js `0.8.x`, so it's likely that `0.9.x` is not supported yet. Glad to hear the issue is resolved.

Going to close this as it is not an Ionic issue. Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-11 12:32 UTC
Labels: triage
