### ISSUE TITLE
bug: White screen with "blank" App on Android 5.1 device

### ISSUE THREAD

**Issue by andypotato** [ionic-team/ionic#19080] opened 2019-08-13 07:59 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I'm creating a new App using the blank template. I add the Android platform via `ionic cordova platform add android` and finally run the App via `ionic cordova run android`

The App compiles and installs fine, however will be stuck with a white screen after the splash screen.

**Log output shows "TypeError" which I wasn't able to debug any further:**

```
I/chromium( 4802): [INFO:mime_util.cc(161)] calling IsSupportedNonImageMimeType
I/chromium( 4802): [INFO:mime_util.cc(161)] calling IsSupportedNonImageMimeType
I/chromium( 4802): [INFO:synchronous_compositor_impl.cc(453)] [RegisterProgressCheckCallback] chromium.skipbeginmainframe=[] enable=[0]
I/chromium( 4802): [INFO:mime_util.cc(161)] calling IsSupportedNonImageMimeType
I/chromium( 4802): [INFO:mime_util.cc(161)] calling IsSupportedNonImageMimeType
I/chromium( 4802): [INFO:CONSOLE(10)] "The key "viewport-fit" is not recognized and ignored.", source: http://localhost/ (10)
I/chromium( 4802): [INFO:CONSOLE(1219)] "deviceready has not fired after 5 seconds.", source: http://localhost/cordova.js (1219)
I/chromium( 4802): [INFO:CONSOLE(1212)] "Channel not fired: onPluginsReady", source: http://localhost/cordova.js (1212)
I/chromium( 4802): [INFO:CONSOLE(1212)] "Channel not fired: onCordovaReady", source: http://localhost/cordova.js (1212)
I/chromium( 4802): [INFO:CONSOLE(1212)] "Channel not fired: onDOMContentLoaded", source: http://localhost/cordova.js (1212)
I/chromium( 4802): [INFO:CONSOLE(82689)] "Ionic Native: deviceready event fired after 3195 ms", source: http://localhost/vendor-es5.js (82689)
I/chromium( 4802): [INFO:CONSOLE(43062)] "ERROR", source: http://localhost/vendor-es5.js (43062)
I/chromium( 4802): [INFO:CONSOLE(667)] "TypeError: styles_1.forEach is not a function", source: http://localhost/main-es5.js (667)
W/chromium( 4802): [WARNING:password_handler.cc(205)] OnPasswordFormsRendered called
W/chromium( 4802): [WARNING:password_handler.cc(207)] OnPasswordFormsRendered IsEnabledSavePassword is false
```

**Expected behavior:**
The App should install and run

**Steps to reproduce:**
See above, simply create and run an App using the "blank" template. 

**The App will run fine on an emulated Android 7.1 device.**

**Ionic info:**

Ionic:

   Ionic CLI                     : 5.2.4 (/Users/as/.nvm/versions/node/v10.16.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.0 (/Users/as/.nvm/versions/node/v10.16.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

**Comment by liamdebeasi** [comment] 2019-08-14 13:09
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19002.

**Closed by liamdebeasi** 2019-08-14 13:09 UTC
Labels: triage

**Comment by JeongJun-Lee** [comment] 2019-08-15 13:33
same here

![image](https://user-images.githubusercontent.com/11474775/63097925-18dce580-bf8b-11e9-92d2-822e3cd5a725.png)
