### ISSUE TITLE
bug: IonInput autofocus doesn't work if there is a button present, in React at least

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#20628] opened 2020-02-26 20:22 UTC
# Bug Report

**Ionic version:**

[x] **5.0.2**

**Current behavior:**

I have an IonInput in a React app with autofocus set. This works just fine until I put an IonButton on the screen and then it stops working.

**Expected behavior:**

The IonInput with autofocus set should always automatically be given focus.

**Steps to reproduce:**

See below for the demo app I've linked, but it's very simple, just add the IonInput and the IonButton and the input will no longer get focus.

**Related code:**

[Here is a GitHub repo](https://github.com/aub/ion-input-focus-problems) demonstrating the problem. The app here was created with `ionic start focus-problems-ii --type=react --capacitor` and then the only thing that was modified was [ExploreContainer.tsx](https://github.com/aub/ion-input-focus-problems/blob/master/src/components/ExploreContainer.tsx). It contains an IonInput with autofocus set and an IonButton. If you run it as-is, the autofocus won't work. If you comment out the button it will work fine.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.0.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.8.0 (/usr/local/Cellar/node/13.8.0/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by aub** [comment] 2020-02-26 21:14
I tested this on the desktop in Chrome.

**Comment by liamdebeasi** [comment] 2020-02-27 16:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18132.

**Closed by liamdebeasi** 2020-02-27 16:07 UTC
Labels: triage
