### ISSUE TITLE
bug: content with fullscreen does not stretch behind footer if navigated too fast

### ISSUE THREAD

**Issue by UncertaintyP** [ionic-team/ionic#18944] opened 2019-07-30 12:13 UTC
# Bug Report

**Ionic version:**

[x] **4.7.0**

Tested in Chrome 75.0.3770.142

**Current behavior:**

1) The target page needs a content with fullscreen enabled and a footer.
2) When navigating to the target page while the transition to source page is not finished the content's height gets calculated wrong. The content will not expand behind the footer.

**Expected behavior:**

The content should be fullscreen (expand behind the footer)

**Steps to reproduce:**

An example app has been provided (see related code)
When navigating to Schedule a navigateForward is triggered to simulate a fast user response to navigate forward (this could also be achieved by clicking on a session while entering the Schedule page *IF* there is an entering animation).

The scree-capture.webm file in the main directory shows the bug.

**Related code:**

See [link](https://github.com/UncertaintyP/ionic-conference-app)
The related code can be found in the schedule and session-detail pages.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.2 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/mnt/127a337f-d228-4ff8-8edb-bc7a40d4e6e7/AndroidSDK/)
   NodeJS            : v10.14.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15
```

**Comment by liamdebeasi** [comment] 2020-06-25 21:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21623 (same underlying problem)

**Closed by liamdebeasi** 2020-06-25 21:05 UTC
Labels: triage
