### ISSUE TITLE
While using Ionic Local Notification we can't achieve certain Features:

### ISSUE THREAD

**Issue by Prasand-altius** [ionic-team/ionic#20021] opened 2019-11-29 12:08 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2019-12-02 13:31
Closing as a duplicate of https://github.com/ionic-team/ionic/issues/20022.

**Closed by liamdebeasi** 2019-12-02 13:31 UTC
Labels: triage
