### ISSUE TITLE
bug: Ionic 4 HTTP Error 503: POST https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by LLHOYH** [ionic-team/ionic#21019] opened 2020-04-12 04:46 UTC
# Bug Report
Receive 'HTTP Error 503: POST https://res.ionic.io/api/v1/upload' bug after changing the icon and the splash image and hit the 'ionic cordova resources' command.

**Ionic version:**

[x] **4.12.0**

**Current behavior:**

Show Error Message:
⠸ Uploading source images to prepare for transformations 
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
⠹ Uploading source images to prepare for transformations 

**Expected behavior:**

Generate my icon and splash screen resources.

**Steps to reproduce:**

Change icon and splash images in the resource folder and enter 'ionic cordova resources' command.

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/LLH/Documents/IonicProjectsMac/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0, ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/LLH/Library/Android/sdk/)
   ios-sim           : 8.0.2
   NodeJS            : v12.14.0 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3 Build version 11C29
```

**Comment by indraraj26** [comment] 2020-04-12 07:03
npm uninstall -g ionic
npm i -g @ionic/cli
npm i -g cordova-res

**Comment by LLHOYH** [comment] 2020-04-12 09:18
> npm uninstall -g ionic
> npm i -g @ionic/cli
> npm i -g cordova-res

I'm sorry but this isn't working for me.

**Comment by indraraj26** [comment] 2020-04-12 09:34
https://github.com/ionic-team/ionic/issues/20908#issuecomment-606865282

> I can confirm this, all my projects are in ionic 3. I have updated to the latest CLI 6.4.0 and all are working fine without any changes to the code. I ran the following commands to update the CLI.
> 
> 1. Update Ionic CLI
> 
> ```
> npm uninstall -g ionic
> npm i -g @ionic/cli
> ```
> 
> 1. Update NPM
>    `    npm install npm@latest -g `
> 2. Update Node to 10.15.0. I tried first with v12 but this version is not compatible with sharp 1.2 which is required to generate resources
> 
> ```
> sudo npm cache clean -f
> sudo npm install -g n
> sudo n 10.15.0
> ```
> 
> 1. In your project you need to rebuild node-sass since the node environment has changed
>    `    npm rebuild node-sass`
> 2. For generating resources you need to install cordova-res
> 
> ```
> sudo npm uninstall cordova-res
> sudo npm i -g cordova-res --unsafe-perm
> ```
> 
> 1. If you want update these two for better user experience
> 
> ```
> "cordova-plugin-ionic-webview": "^4.1.3",
> "@ionic/lab": "^3.1.3"
> ```
> 
> 1. Install all node modules
>    `npm i`
> 2. Now you may generate resources locally
>    `ionic cordova resources android`
> 3. Add and remove platforms
> 
> ```
> cordova platform remove android
> 
> cordova platform add android
> ```
> 
> Additionally if you face javascript heap max out error increase the max space to 4096 or more
> 
> `export NODE_OPTIONS=--max-old-space-size=4096`
> 
> Also If you face Typescript error ‘=‘ expected. Update typescript to 2.7.2
> 
> `npm i typescript@2.7.2`

**Comment by LLHOYH** [comment] 2020-04-12 11:30
It's still not working. I've done whatever you send and nope, it won't work for me. I've even tried sign up for a new ionic account, start a new ionic project and hit that command, but of course showing the same error result.

**Comment by LLHOYH** [comment] 2020-04-12 11:34
Actually I would really want to know what is causing the error and if there's any work around for this? Since ionic cordova resources is to generate images, instead of using that command, is there any other service providers online that can do the same function? (Just curiosity)

**Comment by kensodemann** [comment] 2020-04-12 14:53
@LLHOYH - try `ionic --version` from your project's root directory. You should see this:

```
~/Projects/Home/personal-task-timer (master ✔) ᐅ ionic --version
6.5.0
```

If you see a version earlier than 6.x, than something is wrong. For example, you may have the CLI installed locally, in which case, you would see `ionic` and `@ionic/angular` in your `package.json`  If that is the case, `ionic` really should not be there as you want to use the global install on your machine. If you need it to be there for some reason (such as your CI/CD server uses the local install), then update it as well.

The root of the issue is that older versions of the CLI used to use a cloud service to generate all of the icons and splash screens required by the platforms. That has been done locally via `cordova-res` for quite some time now, and we have shut down the cloud service as having it operate it is simply a waste of money now that the CLI no longer uses it.

**Comment by LLHOYH** [comment] 2020-04-12 15:51
@kensodemann you are right! Mine was showing 4.12.0! But after I've done a update to my global ionic/cli to 6.5.0 (shown will successfully installed), the version still appear as 4.12.0. Sorry for being kinda ignorant but how do I switch to use the global one instead?

**Comment by NikolaPeevski** [comment] 2020-04-12 18:33
Can you guys post ionic info after you've done what @indraraj26 explained?

**Comment by LLHOYH** [comment] 2020-04-13 01:57
@NikolaPeevski 
Here it is:

Ionic:

   Ionic CLI                     : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res                          : 0.11.0
   native-run (update available: 1.0.0) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/LLH/Library/Android/sdk/)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.5.0 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3 Build version 11C29

**Comment by kensodemann** [comment] 2020-04-13 11:31
> Ionic CLI : 6.5.0 (/usr/local/lib/node_modules/@ionic/cli)

If that is the case but you are still seeing `4.12.0` then something _might_ be hosed in your path, really hard to say. Make sure you did the uninstall of the old package before the install of the new package. That is:

```
npm uninstall -g ionic
npm install -g @ionic/cli 
```

Both should be global.

RE: your `cordova-res` issue: `npm i -g cordova-res`

**Comment by kensodemann** [comment] 2020-04-13 11:32
Also, I am going to close this since it is: a.) off topic and b.) a support issue.

**Closed** 2020-04-13 11:32 UTC
Labels: ionitron: support, triage
