### ISSUE TITLE
bug: AlertController button clicks trigger behind ion-item

### ISSUE THREAD

**Issue by florian72810** [ionic-team/ionic#21515] opened 2020-06-12 18:12 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When tapping a button on an AlertController element, the ion-item behind is also triggered.

It happens
- on iOS 13.4.1 (cordova-ios 5.1.1, WKWebViewOnly=true, cordova-plugin-ionic-webview 4.2.1)
- on Chrome (83.0.4103.97), in developer mode with device toolbar enabled and "iPhone X" selected.

The bug looks a lot like #9884.

**Expected behavior:**
The ion-item behind a AlertController button should not be tapped.

**Steps to reproduce:**

use starter-template tabs and add related code
OR
use this repo: https://github.com/florian72810/ionic-starter-tabs-alertcontroller-trigger-ion-item

**Related code:**

```html
  <ion-list>
    <ion-item *ngFor="let item of [1,2,3,4,5,6,7,8,9]" (click)="open('Alert '+item)">
      <ion-icon slot="start" name="sync"></ion-icon>
      <ion-label>
        <h2>Titre {{item}}</h2>
        <p>Contenu</p>
      </ion-label>
    </ion-item>
  </ion-list>
```

```ts
  async open(content: string) {
    const alert = await this.alertController.create({
      cssClass: 'my-custom-class',
      header: content,
      subHeader: 'Subtitle',
      message: 'This is an alert message.',
      buttons: ['OK']
    });

    await alert.present();
  }
```
**Other information:**

![](https://github.com/florian72810/ionic-starter-tabs-alertcontroller-trigger-ion-item/blob/master/bug-on-ios.gif?raw=true)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment] 2020-06-12 18:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21503.

**Closed by liamdebeasi** 2020-06-12 18:16 UTC
Labels: triage
