### ISSUE TITLE
Scroll bar in safari doesn't follow dark mode

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#20921] opened 2020-03-31 02:52 UTC
My ionic app shows light colored scroll bars even though the app and my system is in dark mode.

Here's the repo:

https://github.com/assman/ticket-ionic

<img width="1913" alt="Screen Shot 2020-03-31 at 10 49 08 AM" src="https://user-images.githubusercontent.com/14093665/77981832-7c126100-733d-11ea-99b1-571366d33bc9.png">

**Comment by liamdebeasi** [comment] 2020-03-31 13:55
Thanks for the issue. Can you check to see if you have `Show scroll bars` set to `Always` on your Mac? You can find this by going to `System Preferences > General > Show scroll bars`. I think the setting you want is either `Automatically based on mouse or trackpad` or `When scrolling`.

**Comment by liamdebeasi** [comment] 2020-03-31 13:59
Thanks for the issue. I was able to reproduce this behavior -- though it looks like an issue with Safari, not Ionic Framework. I am going to dig into this a bit more and will provide an update here when I have it.

**Comment by assman** [comment] 2020-03-31 14:00
> Thanks for the issue. I was able to reproduce this behavior -- though it looks like an issue with Safari, not Ionic Framework. I am going to dig into this a bit more and will provide an update here when I have it.

Thanks Liam

**Comment by assman** [comment] 2020-03-31 14:03
My current setting is  Automatically based on mouse or trackpad

**Comment by liamdebeasi** [comment] 2020-03-31 14:40
Thanks for the follow up. I dug into this a bit more, and it looks like this is a known bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=206771.

I commented on the issue with a reproduction, so hopefully this will get fixed. Unfortunately, it does not look like there is any good workaround right now.

I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2020-03-31 14:40 UTC
Labels: needs: investigation

**Comment by liamdebeasi** [comment] 2020-03-31 17:30
@assman I was able to get in touch with someone at Apple. Apparently Safari needs the following CSS: `color-scheme: light dark` in order for the scrollbars to be styled properly. If you apply that to your `ion-modal` via `cssClass`, the scrollbars should be styled properly.
