### ISSUE TITLE
Ionic 4 hardware back button issue

### ISSUE THREAD

**Issue by meerismail** [ionic-team/ionic#20210] opened 2020-01-15 12:46 UTC
Hardware back button is not working without this code, code is given below.

      this.platform.backButton.subscribeWithPriority(0, () => {
        if (this.routerOutlet && this.routerOutlet.canGoBack()) {
          // this.routerOutlet.pop();
        } else if (this.router.url === '/home') {
          // this.platform.exitApp(); 
  
          // or if that doesn't work, try
          navigator['app'].exitApp();
        } else {
          
          this.confirm();
        }
      });

Is this issue solved or not yet? Can anyone give me any update on this issue? or suggest me a perfect way to solve that.
Thanx in advance.

**Comment by liamdebeasi** [comment] 2020-01-15 13:57
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17824. There are some known issues with the hardware back button which we are tracking in https://github.com/ionic-team/ionic/issues/16611.

**Closed by liamdebeasi** 2020-01-15 13:57 UTC
Labels: triage
