### ISSUE TITLE
Cannot assign to a reference or variable using ModalController lazy loaded

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#12400] opened 2017-07-18 14:54 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm not sure and I'm in difficult to figure out the where this exception comes from, but the problem is on a ModalPage we loaded with LazyLoading.

This error probably says nothing, but I think it should be a problem in ionic-angular or a thrid lib.

```
Error: Uncaught (in promise): Error: Cannot assign to a reference or variable!
Error: Cannot assign to a reference or variable!
    at _AstToIrVisitor.visitPropertyWrite (http://localhost:8100/build/vendor.js:103305:23)
    at PropertyWrite.visit (http://localhost:8100/build/vendor.js:85142:24)
    at convertActionBinding (http://localhost:8100/build/vendor.js:102863:45)
    at http://localhost:8100/build/vendor.js:104564:22
    at Array.forEach (native)
    at ViewBuilder._createElementHandleEventFn (http://localhost:8100/build/vendor.js:104560:18)
    at nodes.(anonymous function) (http://localhost:8100/build/vendor.js:104108:23)
    at http://localhost:8100/build/vendor.js:104510:22
    at Array.map (native)
    at ViewBuilder._createNodeExpressions (http://localhost:8100/build/vendor.js:104509:56)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:46348:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:46336:14)
    at http://localhost:8100/build/vendor.js:46391:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4657:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
global packages:
    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:
    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.2

System:
    Node       : v6.11.1
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.3.0 
```

**Comment by jgw96** [comment] 2017-07-18 15:15
Hello, thanks for using Ionic! Could you post a code sample we could use to reproduce this issue please?

**Comment by mburger81** [comment] 2017-07-19 15:02
It could be, the issue is a side effect from this issue #12409
I' suggest we resolve firstly this issue and then see this issue is still there.

**Comment by kensodemann** [comment] 2018-01-03 03:40
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 03:40 UTC
Labels: needs info, v3
