### ISSUE TITLE
[IONIC 4rc.1] [iOS 10] can not scroll to bottom of page

### ISSUE THREAD

**Issue by charlesRms** [ionic-team/ionic#17038] opened 2019-01-10 13:24 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
the end of content is under the scrollable zone limit. I had to insert an empty div with a height of 60px before the </ion-content> tag.

**Expected behavior:**
Beeing able to scroll to the end of page

**Steps to reproduce:**
(with a iOS 10.3.3 device plugged)
ionic cordova run ios --device

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.3.0 (/usr/local/Cellar/node/10.3.0/bin/node)
   npm        : 6.1.0
   OS         : macOS Mojave
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Comment by ermamud** [comment] 2019-07-13 02:33
I can confirm this still happening. Any solution?

**Comment by liamdebeasi** [comment] 2020-02-13 19:11
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.

**Closed by liamdebeasi** 2020-02-13 19:11 UTC
Labels: needs: investigation
