### ISSUE TITLE
bug: ellipsis-horizontal and ellipsis-vertical icons can't be found in react

### ISSUE THREAD

**Issue by qwenzo** [ionic-team/ionic#20984] opened 2020-04-07 11:43 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Can't import "ellipsis-horizontal" nor "ellipsis-vertical" from "ionicons/icons"

**Expected behavior:**
"ionicons/icons" should have declare for "ellipsis-horizontal" and "ellipsis-vertical" icons

**Steps to reproduce:**
1. Create a new project using ionic start myApp tabs --capacitor
2. Create an IonIcon component
3. Try to import ellipsis icon from "ionicons/icons" and set the icon prop to the imported value

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.14 (C:\Users\power\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.8

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10


```

**Comment by liamdebeasi** [comment] 2020-04-07 14:47
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. `ellipsis-horizontal` and `ellipsis-vertical` are icons found in Ionicons v5, which is included in Ionic Framework v5 only. Ionicons v5 is not included with Ionic Framework v4.

**Closed by liamdebeasi** 2020-04-07 14:47 UTC
Labels: triage
