### ISSUE TITLE
Escape key dismisses both modal and alert

### ISSUE THREAD

**Issue by chancezeus** [ionic-team/ionic#13126] opened 2017-10-12 13:23 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When showing an alert on top of a modal (for example to notify the user of a (network) error), pressing ESCAPE results in both the alert and the modal being dismissed.

**Expected behavior:**

Only the top-most visible element (the alert in this case) should be dismissed

**Steps to reproduce:**

1. Create an ionic app
2. Show a modal
3. Show an alert
4. Press escape
5. Both modal and alert are dismissed

**Related code:**

http://plnkr.co/edit/gXdxz3T100Yjfqbgr0ZY?p=preview

**Other information:**

I am unsure how to fix this, but I assume it will require some "global" service/controller keeping track of all opened overlay views (popover, modal, toast, select, etc) in order to determine which one is the current "top" view and only if the current view is the one on top it should close.
Currently the code checks `viewController.isLast` but this fails (at least in this case) because the modal and the alert have a different `NavController` as root (so both the modal and the alert are the last one in their respective navcontrollers stack, but not in the "display" stack as a whole).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4-201709270437
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.6.1-201709131804

System:

    Android SDK Tools : 26.1.1
    Node              : v7.10.0
    npm               : 4.2.0 
    OS                : Linux 4.10

Misc:

    backend : legacy
```

**Comment by miloslavskacel** [comment] 2017-10-12 13:43
Same as #12843

**Comment by kensodemann** [comment] 2017-10-12 14:09
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #12843. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

@miloslavskacel - thank you for linking the duplicate already. Saved me some time tracking it down. :)

**Closed by kensodemann** 2017-10-12 14:09 UTC

**Comment by chancezeus** [comment] 2017-10-12 15:17
Missed it since #12843 references the select element, I think it might be wise to "generalize" the issue in this case because it does not only relate to select elements...
