### ISSUE TITLE
bug: Windows 10 on Surface has Android Look And Feel

### ISSUE THREAD

**Issue by ErkoKnoll** [ionic-team/ionic#6697] opened 2016-05-30 11:27 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0-beta7</span>

**Cordova CLI**: <span ionic-version>6.0.0</span>

**Platform**: <span ionic-platform>Windows 10 desktop UWP app</span> <span ionic-webview></span>

<span ionic-description>When running Ionic 2 app as a desktop UWP app on Windows 10 powered Microsoft Surface the look and feel is Android. I tested the same app on Lumia 920 that had OS upgraded to Windows 10 and there it recognized it is Windows OS and applied Windows look and feel.

I also checked the platform.platforms() output and it only had 2 items: cordova and core. That's probably the reason why it cannot detect it is a Windows device. App itself was built as "ionic build windows -- --appx=uap".</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2016-05-31 15:55
Would you be able to provide the User Agent of your surface? My guess is that the platform detection is catching surface. Could be specific to surface

**Comment by mhartington** [comment] 2016-05-31 16:06
confirmed, getting this on my laptop as well

**Comment by jgw96** [comment] 2016-05-31 16:49
Hello all! So we have done some testing on this and it looks like the issue stems from the Platform detection looking for Windows Phone, which the user agent for a UWP app on a tablet (such as a surface) or laptop does not have. Here is the UA for a UWP on a Windows 10 Mobile device: `Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; MSAppHost.3.0; Microsoft; Lumia 550) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Mobile Safari/537.36 Edge/14.14322` and here is the UA for a UWP app on a Windows 10 laptop: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost.3.0) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 Edge/14.14342`. Im thinking the fix for this would be to look for `MSAppHost` as that is in the user agent for both Windows 10 mobile and regular Windows 10 but is not in the Edge UA (which should receive MD styling). Here is the relevant code snippet that does the UA sniffing: 
```
Platform.register({
  name: 'windows',
  superset: 'mobile',
  subsets: [
    'phablet',
    'tablet'
  ],
  settings: {
    mode: 'wp',
    autoFocusAssist: 'immediate',
    clickBlock: true,
    hoverCSS: false
  },
  isMatch(p: Platform): boolean {
    return p.isPlatformMatch('windows', ['windows phone']);
  },
  versionParser(p: Platform): any {
    return p.matchUserAgentVersion(/Windows Phone (\d+).(\d+)?/);
  }
});
```

**Comment by joshstrange** [comment] 2016-12-20 16:23
Why was #6725 closed? This appears to be related to #9616

**Comment by joshstrange** [comment] 2016-12-21 20:55
If you, like me, just need to get windows to correctly work and not by setting mode: 'wp' for all platforms I would do the following in your app.component.ts constructor:

````
if(platform.userAgent().indexOf('Windows') !== -1) {
    platform.setUserAgent('Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; MSAppHost/3.0; Microsoft; Lumia 550) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Mobile Safari/537.36 Edge/14.14322');
    platform.init();
}
````

This just looks for "Windows" in the user agent string and if it sees the string then it sets the user agent to a string we know Ionic correctly will pick up as windows. I have not yet run into other issues with this method as I'm just getting started but I wanted to put that out there as a potential quick fix until #6725 or something like it is merged.

**Comment by liuxinhu** [comment] 2017-02-21 13:41
@joshstrange 's solution does not work for me :-(
I am using Ionic 2.2.1 and a surface pro 4.

**Comment by joshstrange** [comment] 2017-02-21 21:51
@liuxinhu Can you try console.log-ing or somehow printing what `platform.userAgent()` is for your device is? My code just looks for "Windows" in the user agent. I was dealing with a Surface Pro 3 and that snippet worked for me. If you post what that is I might be able to help.

**Comment by liuxinhu** [comment] 2017-02-21 22:36
After trying @joshstrange 's solution again, it worked for me! Thank you very much!

**Comment by simonbrazell** [comment] 2017-12-16 09:58
@joshstrange thanks for the fix, Windows 10 desktop version now styles correctly.

Cheers!

**Closed** 2018-11-01 20:43 UTC
Labels: ionitron: v3, platform:windows, v2
