### ISSUE TITLE
Can't copy text data from ionic page

### ISSUE THREAD

**Issue by webmak** [ionic-team/ionic#5198] opened 2016-01-26 11:02 UTC
You can check it in different ionic components http://ionicframework.com/docs/v2/components/#overview. Try to make copy of some text data

**Comment by webmak** [comment] 2016-01-26 11:09
sorry there where same question

**Comment by brandyscarney** [comment] 2016-02-04 15:20
I don't understand the problem. Are you talking about selecting text inside of an Ionic app?

**Comment by webmak** [comment] 2016-02-05 10:00
yes

**Comment by brandyscarney** [comment] 2016-02-11 17:09
This is by design, but we will work on adding some configuration for specific platforms in a future version.

**Comment by webmak** [comment] 2016-02-11 19:52
shure. have fixe this in my case

**Comment by brandyscarney** [comment] 2016-02-17 17:09
Reopening because we need to add some config to make this easier to enable.

**Comment by weolopez** [comment] 2016-03-30 13:33
is there some way to enable this prior to the final fix?  I have a deadline and need to enable text select.

**Comment by brandyscarney** [comment] 2016-03-30 15:02
@weolopez You can override these css properties to use `text`:

```
-webkit-user-select: text;
-moz-user-select: text;
-ms-user-select: text;
user-select: text;
```

this allows you to select the text when not emulating - it hasn't been tested alongside gestures though. :smile:

**Comment by aszmyd** [comment] 2016-04-20 12:58
@brandyscarney Your workaround does not work. Not sure why, are there additionally some javascript blockers for this?

**Comment by PaulSec** [comment] 2016-05-26 12:52
Interested in when this will also available :-) 
Keep it up guys, pretty cool project!

**Comment by jgw96** [comment] 2016-09-02 15:12
Hello! We are moving our feature requests to a new feature request [doc](https://docs.google.com/document/d/1vZ339ibia2DA9JVSfO5eGSvej868vooex61xJ5Za8YM/edit). I have moved this feature request to the doc and because of this I will be closing this issue for now. Thanks for using Ionic!

**Comment by astopo** [comment] 2016-10-31 00:38
Adding those CSS properties worked for me! Thank you!

**Comment by claudioviola** [comment] 2016-11-09 09:04
Not with css for me. Use input readonly :)

**Comment by subin-george** [comment] 2016-11-22 11:00
I got a link and I have no idea about it, please check  as :)
https://forum.ionicframework.com/t/how-to-make-text-selectable/4384

**Comment by billygerhard** [comment] 2017-02-26 17:38
This has been open for over a year, this was removed from all milestones, are there still plans on adding this?

**Comment by brandyscarney** [comment] 2017-02-27 15:00
@billygerhard Yes, we are still planning on adding it. :)

**Comment by ThorConzales** [comment] 2017-03-08 07:58
Would be nice to have official support because I cannot get the individual elements working when adding user-select: text.

**Comment by Notifium** [comment] 2017-03-31 09:56
Hi,
Any update on this? It's a major issue for more content-based apps. I really don't want to have to move away from ionic just for this! (Also - solution needed for ionic 1 as well)
Regards,
Andy

**Comment by deoxen0n2** [comment] 2017-04-04 18:09
Hi everyone, adding CSS from @brandyscarney and this attribute on `ion-content` worked for me:

```html
<ion-content overflow-scroll="true">
   ...
</ion-content>
```

Hope this helps.

**Comment by vishnuvathsan** [comment] 2017-04-24 11:12
is there a plan for the fix? if so, when?

**Comment by malwatte** [comment] 2017-04-25 07:25
Anyone got a workaround please?

**Comment by bdoner** [comment] 2017-04-25 08:02
@malwatte Sure, [right here](https://github.com/driftyco/ionic/issues/5198#issuecomment-203478492).

**Comment by imrvshah** [comment] 2017-09-26 20:15
Hello Guys,

I am trying to get copy/paste options using css

```-webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    user-select: text; 
```


I got it from https://github.com/driftyco/ionic/issues/5198#issuecomment-203478492

It is working fine in Android but when I test in iOS it is select the text even if the user didn’t do a long press on the selectable text.

You can see this video.

https://screencast.com/t/Q6zBpWjR2

**Comment by gvillafanetapia** [comment] 2017-11-15 14:20
Hello,

This worked me. 

In app.module.ts, in imports set properties scrollAssist and autoFocusAssist to false:

```
@NgModule({
  declarations: [
    ....
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp, {
      platforms: {
        ios: {
          scrollAssist: false,
          autoFocusAssist: false
        },
        android: {
          scrollAssist: false,
          autoFocusAssist: false
        }
      }
    }),
    HttpModule
  ]
})
....,
```

Hope it helps!

**Comment by Tanzeel064** [comment] 2018-03-21 06:32
@gvillafanetapia thank u so much it really worked for me also.

**Comment by alenl** [comment] 2018-05-29 21:06
I was looking for a way to make the text selectable in desktop web browser. @brandyscarney 's [solution ](https://github.com/ionic-team/ionic/issues/5198#issuecomment-203478492) above in this thread is good, but you have to apply it to each element you want to be able to select. I.e. add the same CSS to body,text,p,h1,h2,h3.... 
The same can be accomplished globally with the * selector, but that might be too blunt of a tool, perhaps. Some items, like menu options, are better off not being selectable.

**Closed** 2018-11-01 19:53 UTC
Labels: feature, ionitron: v3, v2
