### ISSUE TITLE
bug: iOS 13 word pasting auto space exceeds text max length

### ISSUE THREAD

**Issue by Wingzzzzz** [ionic-team/ionic#20679] opened 2020-03-03 06:16 UTC
# Bug Report
iOS 13 word pasting auto space exceeds text max length

**Ionic version:**
**4-5**
(tested on both 4 and 5)

**Current behavior:**
Paste word on text / text area,
word length exceeds 1 than input `maxlength`

**Expected behavior:**
text input should only be allowed to have max length of `maxlength`

**Steps to reproduce:**
repo: https://github.com/Wingzzzzz/test-ios13-text-maxlength-overflow
1. build and run on iOS 13
2. prepare cut and paste with content "12"
3. paste word on either input(text) / textarea
4. repeat 3. few times
5. result: "12 12 12 12"
length: 11
max length: 10

**Other information:**
This is a bug i am not certain related party:
ionic / angular / cordova / iOS 13 / webkit
Wide guess: If not ionic, iOS 13 word pasting auto space directly injects value to field and bypasses normal html max length attribute

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.9.0)
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.15.0
   npm               : 6.13.4
   OS                : macOS Mojave
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by liamdebeasi** [comment] 2020-03-03 14:35
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

I was able to reproduce this outside of Ionic. It looks like a bug in iOS: https://codepen.io/liamdebeasi/pen/dyozzrP

**Closed by liamdebeasi** 2020-03-03 14:35 UTC
Labels: triage
