### ISSUE TITLE
Error: Network Error raised by polyfills (subscribe-publish events)

### ISSUE THREAD

**Issue by royalcheeseburger** [ionic-team/ionic#13654] opened 2017-12-14 13:09 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running the app on an ios device (run, emulate and build --prod) after some seconds I get the following error
![cioc5](https://user-images.githubusercontent.com/1223627/33988141-b7d90e0a-e0c3-11e7-9eb0-e52949148a9a.png)

I don't know how to debug this in order to provide more details.
However, once this error occurs I notice that Ionic Events don't work anymore.

**Expected behavior:**
I subscribe to an event in a component and emit this event from a parent page (a parent page for me is the main page of a tab).

publish-subscribe works well until this Network Error occurs. After this event is not received anymore.

**Steps to reproduce:**
See StackBlitz

**Related code:**

https://stackblitz.com/edit/ionic-8gr6xf

-->

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/me/Documents/apps/dev/myApp/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v6.11.2
    npm               : 4.6.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/me/Library/Android/sdk/

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment] 2017-12-27 15:52
I am going to close this as something that I cannot duplicate.

I have tried exporting the sample application that you provided via StackBlitz and running it on a device, but never receive the exception. I notice that the

I noticed that the versions of a lot of things are wildly different between the `ionic info` you have above and the StackBlitz supplied sample app so perhaps that is part of the reason I cannot duplicate the issue. Perhaps providing a sample application via GitHub that demonstrates the issue along with instructions on how to duplicate would be helpful.

**Closed by kensodemann** 2017-12-27 15:52 UTC

**Comment by DennisSmolek** [comment] 2018-01-26 00:39
I have this exact same error.

It is the same as posted:
https://forum.ionicframework.com/t/runtime-error-network-error/114618
https://forum.ionicframework.com/t/ios-runtime-error-network-error/114620

@kensodemann please re-open

I think it's clearly something with firebase but there is no way to catch it, and it's only on IOS.

My Ionic Info: 
```
cli packages: (/Users/dennis/GIT/Roam/showman-ionic/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : browser 5.0.3 ios 4.5.4 windows 4.4.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.5
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : /Users/dennis/Library/Android/sdk/

Misc:

    backend : pro
```

**Comment by DennisSmolek** [comment] 2018-01-26 00:41
Rather, something with the pub/sub/sockets in any way..

**Comment by DennisSmolek** [comment] 2018-01-26 00:59
Also, I've noticed that the issue is most present when using `--livereload`

**Comment by jeffreyramia** [comment] 2018-04-21 19:41
@DennisSmolek Any update on this issue?

**Comment by allankiezel** [comment] 2018-05-02 15:06
Same issue only when using livereload.
