### ISSUE TITLE
bug: Inifinite scroll with position="top" does not work as expected in Ionic 5

### ISSUE THREAD

**Issue by chilupa** [ionic-team/ionic#21230] opened 2020-05-07 06:03 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

When scrolled to **top** of the page or even before getting to the top, the `ionInfinite` event should be called. But when reaching to the top, it does not call the `ionInfinite` event. Problem I'm facing is, the scroll does not work after i reach to top of page. I'm expecting the data to be added whenever I'm reaching the top of the screen. However, it works when I scroll down a little bit and then slightly scroll up, the data is being called and gets added to array.

**Expected behavior:**

I expect `ionInfinite` event to be called whenever I reach top of the page with `postion="top"` on `ion-infinite-scroll` like how it works flawlessly with `postion="bottom"`

**Steps to reproduce:**

1. Add `ion-infinite-scroll` element  with `postion="top"` attribute to your `ion-content`
2. Try to scroll to the top, it won't scroll once it reaches top, though I have data incremented to the array.
3. You will need to scroll down a little bit in order for infinite scroll to work and then the data loads.

**Related code:**

Here's the [repository](https://github.com/chilupa/ionic5-infinite-scroll-postion-top) for full code

**HTML**
```
<ion-content [scrollEvents]="true" (ionScroll)="logScrolling($event)">

  <ion-list>
     <ion-item *ngFor="let item of items">
         <ion-label>{{item.name}}</ion-label>
     </ion-item>
  </ion-list>

  <ion-infinite-scroll threshold="10%" postion="top" (ionInfinite)="loadData($event)">
    <ion-infinite-scroll-content
      loadingSpinner="bubbles"
      loadingText="Loading more data...">
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
</ion-content>
```

**TS**

```
  @ViewChild(IonInfiniteScroll, { static: false })
  infiniteScroll: IonInfiniteScroll;
  @ViewChild(IonContent, { static: false }) content: IonContent;

  ...

  loadData(event) {
    setTimeout(() => {
      this.getNewData();
      event.target.complete();
    }, 500);
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.4.0 (/Users/pavanchilukuri/.nvm/versions/node/v10.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.18.1 (/Users/pavanchilukuri/.nvm/versions/node/v10.18.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
   Xcode  : Xcode 11.4.1 Build version 11E503a
```

**Comment by chilupa** [comment] 2020-05-07 06:15
I have figured it out myself. I just need to set the right `threshold` value on `ion-infinite-scroll` element. 

Below is what I did for the fix.

```
  <ion-infinite-scroll
    position="top"
    threshold="90%"
    (ionInfinite)="loadData($event)"
  >
    <ion-infinite-scroll-content
      loadingSpinner="bubbles"
      loadingText="Loading more data..."
    >
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
```

**Comment by indraraj26** [comment] 2020-05-07 07:36
Same behavior i had in ionic 3 and still application has that glitch (chat application), You will have to scroll little bit at top (atleast 2 times in my case)

**Comment by chilupa** [comment] 2020-05-08 19:28
@liamdebeasi Added steps to reproduce section. I was not able to generate CodeSandbox for Stackblitz for you as my repository itself is not loading in both of them and also I'm not able to add Ionic 5 dependency.

**Comment by liamdebeasi** [comment] 2020-05-08 19:34
@chilupa Are you able to create a public GitHub repo and post a link to it here?

**Comment by chilupa** [comment] 2020-05-08 21:08
@liamdebeasi Here's the [link](https://github.com/chilupa/ionic5-infinite-scroll-postion-top) to the repo. It will have the code that should replicate the issue.

**Comment by liamdebeasi** [comment] 2020-05-11 13:08
@chilupa Can you update your repo to not load data from a 3rd party site? The `jsonplaceholder.com` request errors out, and the app does not load for me.

**Comment by chilupa** [comment] 2020-05-11 19:30
@liamdebeasi The mock api that I'm using is `https://jsonplaceholder.typicode.com/users` and it works fine for me. Could you please re check now?

**Comment by liamdebeasi** [comment] 2020-05-11 20:07
The request still times out for me. Can you just hardcode the result from the API in the app?

**Comment by chilupa** [comment] 2020-05-11 20:10
@liamdebeasi Okay, I just added mock users data in `assets` folder. You should be able to fetch the data locally now.

**Comment by liamdebeasi** [comment] 2020-05-11 20:16
Thanks! The app loads now.

One thing I notice is `ion-infinite-scroll` is physically located at the bottom of the `ion-content`. Does the issue resolve itself if you place it at the top on the content?

```html
<ion-content #content [scrollEvents]="true" (ionScroll)="logScrolling($event)">
  <ion-infinite-scroll
    threshold="10%"
    position="top"
    (ionInfinite)="loadData($event)"
  >
    <ion-infinite-scroll-content
      loadingSpinner="bubbles"
      loadingText="Loading more data..."
    >
    </ion-infinite-scroll-content>
  </ion-infinite-scroll>
  
  <ion-card *ngFor="let user of users[0]">
    <ion-card-content>
      <div>{{user.name}}</div>
      <div>{{user.email}}</div>
    </ion-card-content>
  </ion-card>
</ion-content>

```

**Comment by chilupa** [comment] 2020-05-11 20:31
@liamdebeasi No, it does not. I just tried. I placed at `ion-infinite-scroll` element above the `ion-list` It gives an excess padding even though the array has new data.
Also, I updated my code to display data on view accordingly. Please pull the latest. 
Thank you!

**Comment by liamdebeasi** [comment] 2020-05-11 20:37
Can you provide some steps to reproduce the issue? I am scrolling to the top of the page and infinite scroll is firing correctly.

**Comment by chilupa** [comment] 2020-05-11 20:43
@liamdebeasi It will fire correctly for several additions. After that, a blank excess padding appears at top.
**Steps to reproduce**
1. Scroll to top for several times
2. For me, It scrolled to top for 7 times, the data populated correctly. After that, It stopped working.
3. It creates an blank and excess padding at top once it stops working.
4. To make it work, I will need to scroll down a little bit and scroll up, then the data appears.

**Comment by liamdebeasi** [comment] 2020-05-11 21:03
Thanks! Looks like this is a duplicate of https://github.com/ionic-team/ionic/issues/19540, so I am going to close this in favor of the older issue.

**Closed by liamdebeasi** 2020-05-11 21:03 UTC
Labels: triage
