### ISSUE TITLE
iOS 13 Safari Zoom Issue

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#20923] opened 2020-03-31 08:22 UTC
Github doesnt allow video, so I have converted it to a GIF and as can be seen from the GIF, I'm testing my app on iOS 13 Safari. Upon double tapping the screen at one point, the app zooms in and after that I'm unable to zoom back out into the normal view. This only happens when I double tap on <ion-card> elements.

I wonder if this is a bug or is it my code. The repo is:

https://github.com/assman/ticket-ionic

![ezgif-6-8c2f3f97ed67](https://user-images.githubusercontent.com/14093665/78003594-8186a000-736b-11ea-884b-f2df080154c7.gif)

**Comment by liamdebeasi** [comment] 2020-03-31 13:53
Thanks for the issue. Can you provide some steps to reproduce the issue? I am testing this on a device running iOS 13.4 and am unable to reproduce the issue.

**Comment by assman** [comment] 2020-03-31 13:58
> Thanks for the issue. Can you provide some steps to reproduce the issue? I am testing this on a device running iOS 13.4 and am unable to reproduce the issue.

Once you go to tickets/bookings (which is the main home page), tap on the first card - 20890
Doing so will open up the detail view. Now in the detail view, the first thing you see will be an ion card with the date and some lorem ipsum. double tap on that card like how its done for zooming in into things in iOS

**Comment by liamdebeasi** [comment] 2020-03-31 18:30
Thanks for the follow up. I was able to reproduce this on iOS 13.3, but not on iOS 13.4. This looks like a quirk in WebKit that has since been fixed.

In terms of a workaround for those using older versions of iOS, you may be able to use [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to only allow panning. We could add this to the framework, but that might have unintended side effects for developers who want zooming enabled in their apps.

I am going to close this as this does not appear to be a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2020-03-31 18:30 UTC
Labels: triage
