### ISSUE TITLE
bug: Collapsible large titles showing through when navigating on iOS Tabs app

### ISSUE THREAD

**Issue by Taylorsuk** [ionic-team/ionic#20575] opened 2020-02-20 21:43 UTC
# Bug Report

**Ionic version:**
v5.0.1

**Current behavior:**
The bug occurs when using the Collapsible Large Titles feature in conjunction with Tabs navigation. see animation below:

![collapsible title isse](https://user-images.githubusercontent.com/852767/74980902-3357b600-5429-11ea-9f95-6c2173b2c7ca.gif)

**Expected behavior:**
Expect the hidden page titles in the stack to remain hidden and not show through. 

**Steps to reproduce:**
1. Create a tabs app
2. Add Collapsible Large titles to all tabs.  
3. Implement a sub-navigation page and navigate to it and back

**Related code:**

Sample application via GitHub
[https://github.com/Taylorsuk/ionic-header-issue](https://github.com/Taylorsuk/ionic-header-issue)

Sample Stackblitz Code
[https://stackblitz.com/github/Taylorsuk/ionic-header-issue](https://stackblitz.com/github/Taylorsuk/ionic-header-issue)

Sample Running Stackblitz (use dev tools and select iOS to view issue)
[https://stackblitz.com/github/Taylorsuk/ionic-header-issue](https://bnmioqajw.github.stackblitz.io/tabs/tab1)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.1.0 (/Users/taylorsuk/.nvm/versions/node/v12.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   NodeJS : v12.13.1 (/Users/taylorsuk/.nvm/versions/node/v12.13.1/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-02-20 21:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20482.

**Closed by liamdebeasi** 2020-02-20 21:50 UTC
Labels: triage
