### ISSUE TITLE
v4: ion-button text not vertically aligned, with or without icons

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14710] opened 2018-07-04 10:05 UTC
**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
insert the output from ionic info here
```

**Describe the Bug**
If we test simple example we got amongst other things from the documentation we saw the text in an ion-button is not vertically centered, you can see it if you compare it with icon. But you can see it also on the button with only text

```
      <ion-button>
        <ion-icon slot="start" name="star"></ion-icon>
        Left Icon
      </ion-button>

      <ion-button>
        Right Icon
        <ion-icon slot="end" name="star"></ion-icon>
      </ion-button>

      <ion-button>
        <ion-icon slot="icon-only" name="star"></ion-icon>
      </ion-button>

      <ion-button>        
        Without icon
      </ion-button>
```

![image](https://user-images.githubusercontent.com/3778892/42270731-dffa26e6-7f81-11e8-9db6-dab930f54c40.png)

Also in your documentation you can see text is not centered. Perhaps this is new style guide on MD if only have text, but we think it is for sure not right if you have also an icon there

![image](https://user-images.githubusercontent.com/3778892/42271019-98de2a54-7f82-11e8-80d1-82a268f04add.png)

**Comment by mburger81** [comment] 2018-07-04 10:07
We create a PR #14711 to show buttons with icons and document preview for documentation

**Comment by brandyscarney** [comment] 2018-07-05 18:34
Thanks for the issue! I'm not able to see these issues with button fonts and icons in latest including the docs: https://ionic-docs.herokuapp.com/docs/api/button/. Do you have a repository or something I can use to reproduce? 🙂 

<img width="344" alt="screen shot 2018-07-05 at 2 27 12 pm" src="https://user-images.githubusercontent.com/6577830/42341022-a8001b86-805f-11e8-95dc-b98f37d9c7f3.png">

Also, which browser are you using?

**Comment by mburger81** [comment] 2018-07-05 20:09
I'm out of office and I can't do the demo right now.
But I have the same issue open your documentation link in android with latest google chrome browser.
The demo doesn't show icons for now, but also in this case the text is not cemtered. 

My old original screenshots are from ubuntu always with latest chrome. 
Can you attache screen for button without icons?

**Comment by brandyscarney** [comment] 2018-07-05 20:20
Yes, here is the buttons demo using Google Chrome on a Mac running 10.12.6.

<img width="381" alt="screen shot 2018-07-05 at 4 17 13 pm" src="https://user-images.githubusercontent.com/6577830/42346011-2c4e4b10-806f-11e8-936d-72b26a246529.png">

Could you open up developer tools, go to the Application tab, and then Service Workers and see if one exists? If so try unregistering it and refreshing.

**Comment by mburger81** [comment] 2018-07-05 20:38
Hm, I'm testing at home from Windows with latest Chrome using docs link. Not sure if there persist the problem, it's more difficult to see the bug without icon and the tablet  is too small  to debug it with  dev  tools. I had a look on this pc for service workers, there are registered a lot :) Do you intend some specific? Probably I have to check this issue again tomorrow on our dev machine.

BTW your screens are ios design, right? Can you check for MD? Having a look from this PC the bug for  sure is not present on ios, there seems it ok,  but on MD there looks  it  strange,  for sure not strange as  on the dev machine at work.

**Comment by brandyscarney** [comment] 2018-07-05 20:57
You should be able to unregister the service worker on the docs page. There were some issues with it on our docs site so we disabled it for now. You should have no service worker registered when you go to either http://ionic-docs.herokuapp.com/ or https://beta.ionicframework.com/ and open developer tools. I've seen some weird bugs caused by it. 

My screenshots are in MD mode. :) Here is how it looks for me for each mode:

<img width="382" alt="screen shot 2018-07-05 at 4 54 33 pm" src="https://user-images.githubusercontent.com/6577830/42347526-244a7bd2-8074-11e8-9567-963d2566676d.png">
<img width="381" alt="screen shot 2018-07-05 at 4 54 38 pm" src="https://user-images.githubusercontent.com/6577830/42347527-245ae86e-8074-11e8-9389-acf9f07555d6.png">

Let me know if you're still seeing problems without a service worker. Also, if you need to wait until tomorrow there is no rush!

**Comment by mburger81** [comment] 2018-07-05 21:04
Hm, but the service worker problem should be only from documentation. But the screen shot with the  star icons I attached is from a plain ionic4 app, and in this case the problem should have nothing  to  do with service worker, right?

I think we have to wait until tomorrow, I can help more  from the office.

**Comment by mburger81** [comment] 2018-07-06 05:58
Good morning, so I tested it with dev device (ubuntu + chrome)  on this demo link https://ionic-docs.herokuapp.com/docs/content/api//button-demo.html
As you can see button is not centered, in this case i'm selecting API for dev, but alpha.7 has the same problem.

![image](https://user-images.githubusercontent.com/3778892/42361561-6dc1597c-80ef-11e8-98bd-908f1804e749.png)

I have created a demo github repo (https://github.com/mburger81/ionic4-tests), the next screenshot is from it. Here you can see again, the text is not centered in our case.

![image](https://user-images.githubusercontent.com/3778892/42362139-3bb4e5a4-80f2-11e8-913d-1859a2a68199.png)

**Comment by TomDemulierChevret** [comment] 2018-08-16 14:54
In my case, text is vertically centered in serve but not when I run the app on device (Android 8.0).

**Comment by paulstelzer** [comment] 2018-12-03 18:13
Think this is fixed in beta.17. If not, just write here!

**Closed by paulstelzer** 2018-12-03 18:13 UTC
Labels: triage
