### ISSUE TITLE
Slow button click and scroll on iPad 2

### ISSUE THREAD

**Issue by ezekjh** [ionic-team/ionic#11696] opened 2017-05-16 18:40 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request 

**Current behavior:**
I have a list of items like you see in below picture (it is just a demonstration of the real app). Each item has 4 buttons that, when clicked, should change their state. The state change is visualized by changing the color of the button.
I have one component that renders the list, another component that holds the item structure, and a third component that renders the 4 buttons.
The list uses virtualScroll and has an approxItemHeight set.

http://imgur.com/UiTMpm8

When this app runs on an iPad 2 (or some other "older" iOS devices) the time taken for any button to change it's state from the moment it was clicked could be between 1 and 4 seconds.
Below is what I get from the Timeline tab on Safari when I click on a button and wait for it to change:

http://imgur.com/a/ayuI0

Here you can see that a lot of "Styles Recalculated" events show up. The whole process took 1 second, although in our real app (which has bindings, more styling, etc.) this could take 3 or more seconds.
Also, the scrolling is laggy and slow.

**Expected behavior:**
Button clicks should not take more than a few miliseconds tho be processed. Scrolling should be fluid.

**Steps to reproduce:**
Here's a repo with the demo used for above screenshots:
https://github.com/ezekjh/ionic-ipad-issue-test

And here's plunkr code for the same:
http://plnkr.co/edit/OyUIPTiFupkj45WqqyNF?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
Cordova CLI: 7.0.0 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.2 Build version 8E2002

**Additional Info**
Adding WKWebVIew did not make any improvement in either scrolling nor button clicks.

**Comment by jgw96** [comment] 2017-05-17 14:18
This is probably related to https://github.com/driftyco/ionic/issues/11489. If you make the same changes to a button not nested in divs do you have the same issue?

**Comment by ezekjh** [comment] 2017-05-17 16:56
Tried simplifying markup and put the buttons directly inside the ion list removing any nested div that might be generated, just like this:
```
 <ion-list [virtualScroll]="items" [approxItemHeight]="'260px'">
         <div *virtualItem="let item">
            <h2>{{item.itemName}}</h2>
            <button ion-button large [class.action-selected]="item.actionHandler==1" (click)="actionButtonTapped(item, 1)">
                Action 1
            </button>
           
            <button ion-button large [class.action-selected]="item.actionHandler==2" (click)="actionButtonTapped(item, 2)">
                Action 2
            </button>
            
            <button ion-button large [class.action-selected]="item.actionHandler==3" (click)="actionButtonTapped(item, 3)">
               Action 3
            </button>
            
            <button ion-button large [class.action-selected]="item.actionHandler==4" (click)="actionButtonTapped(item, 4)">
                Action 4
            </button>
        </div>
    </ion-list>
```
See plunkr: 
http://plnkr.co/edit/qt2RBd5wqVWKzf5ySxl8?p=preview

It didn't make any improvement. See below Timeline capture:

http://imgur.com/a/e1Wq3

It takes about a second for the button to change state on a list of 50 rows with VirtualScroll.

This works perfectly fine on an iPhone 6. There even our much more complex app doesn't show any if this issues. Though, we definitely need to support iPad 2 and similar devices.

**Comment by jgw96** [comment] 2017-05-18 15:18
Hello, thanks for using Ionic! In the plunker it seems that the color of the button does not change when clicked, but when the button is hovered over. Is this correct behavior?

**Comment by ezekjh** [comment] 2017-05-18 15:27
No. I had to adapt the logic a bit to set it up on plunker. That same code updates without having to hover the button if I run it on the browser or on a device.

**Comment by jgw96** [comment] 2017-05-18 15:43
Thanks for the info. If you put this in a regular *ngFor list instead of virtualscroll do you get the same issue?

**Comment by ezekjh** [comment] 2017-05-18 15:53
Changing to an *ngFor eliminates that issue we just commented. But the lag between the click and the state change persists on the device.

**Comment by jgw96** [comment] 2017-06-02 15:23
Thanks for the info @ezekjh ! Based off of this info I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11668.

**Closed by jgw96** 2017-06-02 15:23 UTC
Labels: needs info, v2
