### ISSUE TITLE
bug ionic 2 and 3 the header in iPhone not take the correct height

### ISSUE THREAD

**Issue by javico2609** [ionic-team/ionic#11724] opened 2017-05-19 01:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ X] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
i tested this behavior on a real iphone, am i see the same problem like see on my local ionic lab

![2017-05-18_22-34-45](https://cloud.githubusercontent.com/assets/12940555/26229792/952d3e06-3c1a-11e7-8a94-a24e19a40790.png)

![d57c3cde-0680-11e7-8c1f-adeccc48f6af](https://cloud.githubusercontent.com/assets/12940555/26229523/b4836b38-3c18-11e7-9116-9d3f81f5ed7b.png)

**Expected behavior:**
the header take the correct height

**Steps to reproduce:**

**REPO**
https://github.com/javico2609/angular-mvd-meetup

-->

**Related code:**

```
@Component({
    selector: 'icbanking-header-navbar, [icbanking-header-navbar]',
    template: `
        <ion-navbar>
            <button ion-button menuToggle>
                <ion-icon name="menu"></ion-icon>
            </button>
            <div class="logo"></div>
            <ion-title class="ion-title-with-logo">{{_menuTitle}}</ion-title>
        </ion-navbar>   
    `
})
export class ICBankingHeaderNavbarComponent implements OnInit {

@Input()
    get title(): string {
        return this._menuTitle;
    }
    set title(val: string) {
        this._menuTitle = val;
  }

  // some logic here
}

////// Home Component

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public navParams: NavParams) { }

  ionViewDidLoad() {
    console.log('ionViewDidLoad HomePage');
  }
}

/// Home html
<ion-header>
  <icbanking-header-navbar title="{{ 'HomePage' | translate }}"></icbanking-header-navbar>
</ion-header>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.1.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.0
    @ionic/cli-plugin-ionic-angular : 1.1.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.7.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by jgw96** [comment] 2017-05-19 14:28
Hello, thanks for using Ionic. Unfortunately, I cannot reproduce this issue locally. Could you post a repo we could use to reproduce this issue?

**Comment by javico2609** [comment] 2017-05-19 15:16
Hi, on session "Steps to reproduce:" can find the repo link

[https://github.com/javico2609/angular-mvd-meetup](REPO)

**Comment by moberwasserlechner** [comment] 2017-05-24 09:57
Hi,

I came across sth similar, when running a IONIC PWA on ios10.

@javico2609 You might be able to fix it adding the following to your index.html.
```
<meta name="apple-mobile-web-app-status-bar-style" content="black">
```
Setting the content attribute 'black-translucent' has the same effect seen in your examples.

See the docs for more information and related [meta tags].(https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html)

Hope this helps

**Comment by marcovtwout** [comment] 2017-10-30 16:42
@javico2609 Did you end up finding a correct fix for this issue?

**Comment by kensodemann** [comment] 2018-01-03 03:25
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. There were a lot of changes made with regard to this for iOS 11, so hopefully those changes addressed this as well. Feel free to comment if you are still running into this issue.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 03:25 UTC
Labels: needs info, v2

**Comment by marcovtwout** [comment] 2018-01-03 08:13
This was probably fixed with https://github.com/ionic-team/ionic/issues/13294
