### ISSUE TITLE
IOS: keyboard keep open and hide when tap text in a contentEditable DIV.

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionic#16901] opened 2018-12-28 16:08 UTC
# Bug Report

**Ionic version:**

[x] **4.6**

**Current behavior:**

RUN on device of IOS 12.1
When tap on an editable block with HTML child content, you will find that, when tap, keyboard open, then tap, keyboard hide, and so on..

**Expected behavior:**

When tap on anywhere in an editable block, the keyboard should always open.

**Steps to reproduce:**

1. Open an ionic v4 app in IOS.
2. Mark up a div as following code
3. Tap on the text in the div, watch keyboard's action.
4. The first line, keyboard works fine. The second line, keyboard start to dance.

**Related code:**
```
<div contentEditable style="-webkit-user-select: auto">
This is a text line.
<div>This is a para with div tag</div>
</div>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/local/Cellar/nvm/0.26.1/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.3.1, (and 15 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/netsesame/Projects/SDK/android)
   NodeJS            : v10.11.0 (/usr/local/Cellar/nvm/0.26.1/versions/node/v10.11.0/bin/node)
   npm               : 6.5.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment] 2019-01-02 08:36
Thanks for your issue! Can also be a problem of `cordova-plugin-ionic-keyboard`. Can you open an issue there too and link to this?

**Comment by netsesame2** [comment] 2019-01-02 08:38
@paulstelzer Agree, maybe a plugin issue.

**Comment by netsesame2** [comment] 2019-01-14 03:41
Any idea?

**Comment by hoxer80** [comment] 2019-05-10 03:40
I have same error... It wasn't happen on ionic3.

**Comment by peterpeterparker** [comment] 2019-05-28 09:15
In the issue I linked I display some screenshot and a video of the problem. It isn't linked with web view I think as the problem is reproducible with Ionic core in iOS Safari

**Comment by paulstelzer** [comment] 2019-06-03 12:18
I close this here because in a new topic (#18368) there are many more information

**Closed by paulstelzer** 2019-06-03 12:18 UTC
Labels: needs: investigation
