### ISSUE TITLE
ion-tabs (Color tab and badgeColor) Not Working Beta.13

### ISSUE THREAD

**Issue by luisgls1807** [ionic-team/ionic#15995] opened 2018-10-18 05:00 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.13
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : not installed
   @ionic/schematics-angular  : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 4 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**

in the update they mention that the beagle thing is working and it still does not work. 

> I attach the section, tabs: badgeColor works again (3d98587), closes #15559 #14840

I also detected that with the update the color of the ion-tabs does not change anymore, neither the position top and bottom

**Related Code**
BadgeColor:
 - I use this: `badgeColor="success"`

Ion-Tabs:
 - I use this: `tabbarPlacement="top" color="danger"`

**Expected Behavior**
I hope you can check and if it is failing or if something is damaged when I made the update.
thanks.

**Comment by brandyscarney** [comment] 2018-10-26 17:54
Thank you for the issue! I'm going to close this as a duplicate of #15942. I know it doesn't mention badge color in the original issue, but please refer to my comment here: https://github.com/ionic-team/ionic/issues/15942#issuecomment-433429959

In `4.0.0-beta.14` badge color will be set by adding an `<ion-badge>` into the tab button with a color property. Thanks!

**Closed by brandyscarney** 2018-10-26 17:54 UTC
