### ISSUE TITLE
Blank page chrome 70.0.3538.110 android 5.0.2

### ISSUE THREAD

**Issue by LautaroLorenz** [ionic-team/ionic#17913] opened 2019-03-29 22:22 UTC
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\coco\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 6 other plugins)

System:

   NodeJS : v10.0.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10

Test on Chrome 70.0.3538.110
Android 5.0.2

If you add the application as PWA it works fine, but as .apk fails

**Comment by LautaroLorenz** [comment] 2019-03-31 15:44
message in console
---------------------
The key "viewport-fit" is not recognized and ignored. localhost/:10
Uncaught TypeError: pre,template,textarea,script,style is not iterable! 

partial solution
----------------
in the directory ./src/
there is the Polyfills.ts file
uncomment the following lines:

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

**also uncomment this line**
import 'core-js/es6/array';

Now the App works, but the styles do not, for the moment I can redirect users to the PWA version.

I would like to understand why styles do not work and thus be able to contribute to find a solution at least to be able to find what the problem is specifically

**Comment by liamdebeasi** [comment] 2019-04-01 12:53
Hi there,

Thanks for the issue. Can you post your user agent string? You can get this by logging `window.navigator.userAgent` when the app is running in Cordova/Capacitor?

Thanks!

**Comment by LautaroLorenz** [comment] 2019-04-01 13:05
@liamdebeasi  

Mozilla/5.0 (Linux; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 **Chrome/37.0.0.0** Mobile Safari/537.36 

Woila!, then that means that in this Android I have an old version of webview?

**Comment by liamdebeasi** [comment] 2019-04-01 13:15
Hi @LautaroLorenz,

Thanks for the follow up. Yeah, a lot of older versions of Android ship with old versions of Chrome. That particular version of Chrome does not support CSS Variables; however, a polyfill should be served up to add support for it.

We are currently investigating an issue where the polyfill is not served on certain versions of Chrome. I am going to close this since it's a duplicate of https://github.com/ionic-team/ionic/issues/17781, but this is an issue I am actively working on, so I expect to have more info to share soon.

Feel free to post any follow up questions/comments here: https://github.com/ionic-team/ionic/issues/17781

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-01 13:15 UTC
Labels: triage

**Comment by pipoa** [comment] 2019-04-02 15:34
> Hi @LautaroLorenz,
> 
> Thanks for the follow up. Yeah, a lot of older versions of Android ship with old versions of Chrome. That particular version of Chrome does not support CSS Variables; however, a polyfill should be served up to add support for it.
> 
> We are currently investigating an issue where the polyfill is not served on certain versions of Chrome. I am going to close this since it's a duplicate of #17781, but this is an issue I am actively working on, so I expect to have more info to share soon.
> 
> Feel free to post any follow up questions/comments here: #17781
> 
> Thanks for using Ionic!

Hi @liamdebeasi , I just bump into this issue too.  "Uncaught TypeError: pre,template,textarea,script,style is not iterable!"  does nothing to do with css styling. I just curious how you conclude it to css var problem?

@LautaroLorenz  I have the same error message porting to android 5.0.1. Did you get this issue solve? can you share how you solve it?

**Comment by LautaroLorenz** [comment] 2019-04-02 15:44
@pipoa to solve 
"Uncaught TypeError: pre,template,textarea,script,style is not iterable"
look at my previous answer
https://github.com/ionic-team/ionic/issues/17913#issuecomment-478352800
After this, the problem with the styles appears

**Comment by pipoa** [comment] 2019-04-02 16:10
@LautaroLorenz  thanks, my bad, I misread uncomment to comment. 
@liamdebeasi  please ignore my curiosity. thanks.
