### ISSUE TITLE
<ion-item-sliding/> right side <ion-item-options/> displayed on both sides

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic#13993] opened 2018-02-09 06:39 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

```
 @stencil/core@0.3.0-5
 @ionic/core@0.0.2-48
 NPM 5.6.0
 Node v8.9.4
 OS Ubuntu 16.04.3 LTS
```

**I'm submitting a ...**  (check one with "x")
x ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using stenciljs, `<ion-item-options/>` are not correctly displayed. The right-side options are displayed on both sides.

**Expected behavior:**

`<ion-item-options/>` should be displayed according to the `side` attribute.

Additionally, with a list of `<ion-item-sliding>`, it is not possible to swipe the list vertically from the center/middle of an item, contrarily to Ionic3. It's only possible to swipe it vertically when doing it on the right side (the scroll bar is slightly visible). 

**Steps to reproduce:**

**Related code:**

(Stenciljs component)

* src/components/my-test/my-test.tsx

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'my-test',
  styleUrl: 'my-test.scss'
})
export class MyTest {
  constructor() {}

  render() {
    return (
      <ion-list>
        <ion-item-sliding>
          <ion-item>
            Item
          </ion-item>
          <ion-item-options side='left' class='options-left'>
            <ion-button>Button Left A</ion-button>
            <ion-button>Button Left B</ion-button>
          </ion-item-options>

          <ion-item-options side='right' class='options-right'>
            <ion-button>Button Right A</ion-button>
            <ion-button>Button Right B</ion-button>
          </ion-item-options>
        </ion-item-sliding>
      </ion-list>
    );
  }
}
```

* src/components/my-test/my-test.scss
```scss
my-test {
  .options-right {
    border-right: solid thick red;
  }
  .options-left {
    border-left: solid thick green;
  }
}
```

**Other information:**

* Swipe right
![swipe-right](https://user-images.githubusercontent.com/2463/36014504-7a697c84-0d6a-11e8-92c5-40aa7182d94f.png)

* Swipe left
![swipe-left](https://user-images.githubusercontent.com/2463/36014542-bff4eedc-0d6a-11e8-8158-e01dfe03b5d6.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below) : Not Applicable

**Comment by brandyscarney** [comment] 2018-02-09 22:30
Thanks for the issue! I have this fixed on a branch, will get it merged in soon and release a new version. :smile:

**Comment by kael** [comment] 2018-02-10 00:35
Thank you !

**Comment by brandyscarney** [comment] 2018-02-10 03:47
@kael I just noticed that you are using `ion-button` inside of `ion-item-options`. We have renamed this to `ion-item-option` so that it doesn't pull in all of the button styles that it doesn't need. More on the breaking changes for v4 can be read here (I just added the item sliding documentation): https://github.com/ionic-team/ionic/blob/core/BREAKING.md#item-sliding

I just released version `@ionic/core@0.0.2-60`. Could you test this version out when you get a chance and let me know if you see any issues? Thanks!

**Comment by kael** [comment] 2018-02-10 05:38
Thanks for the release. But seems not working after upgrading to `@ionic/core@0.0.2-60`.

For the following code (same version than above but updated with the breaking changes):

```tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'my-test',
  styleUrl: 'my-test.scss'
})
export class MyTest {
  constructor() {}

  render() {
    return (
      <ion-list>
        <ion-item-sliding>
          <ion-item>
            <ion-label>Item 1</ion-label>
          </ion-item>
          <ion-item-options side="left" class='options-left'>
            <ion-item-option expandable>
              <ion-icon name="star">Button Left A</ion-icon>
              <ion-icon name="email">Button Left B</ion-icon>
            </ion-item-option>
          </ion-item-options>
          <ion-item-options side="right" class='options-right'>
            <ion-item-option expandable>
              <ion-icon name="alarm">Button Right A</ion-icon>
              <ion-icon name="notification">Button Right B</ion-icon>
            </ion-item-option>
          </ion-item-options>
        </ion-item-sliding>
      </ion-list>
    );
  }
}
```

The following is displayed (on Chrome 64 and Android Chrome 65 beta):


 
![item-sliding-fix1](https://user-images.githubusercontent.com/2463/36058914-c759b618-0e2c-11e8-94bb-7921c615a03f.png)

**Comment by kael** [comment] 2018-02-10 05:42
Also, when testing with the [first example](https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/item-sliding#ion-item-sliding):

```xml
<ion-list>
  <ion-item-sliding>
    <ion-item>
      <ion-label>Item</ion-label>
    </ion-item>
    <ion-item-options side="left">
      <ion-item-option onClick="favorite(item)">Favorite</ion-item-option>
      <ion-item-option color="danger" onClick="share(item)">Share</ion-item-option>
    </ion-item-options>

    <ion-item-options side="right">
      <ion-item-option onClick="unread(item)">Unread</ion-item-option>
    </ion-item-options>
  </ion-item-sliding>
</ion-list>
```

The compiler raises that error:

```bash
[ ERROR ]  typescript: src/components/my-test/my-test.tsx, line: 18
           Type '{ onClick: string; }' is not assignable to type 'IonItemOptionAttributes'. Types of property 'onClick' 
           are incompatible. Type 'string' is not assignable to type 'EventHandler<MouseEvent>'. 

     L17:  <ion-item-options side="left">
     L18:    <ion-item-option onClick="favorite(item)">Favorite</ion-item-option>
     L19:    <ion-item-option color="danger" onClick="share(item)">Share</ion-item-option>

[ ERROR ]  typescript: src/components/my-test/my-test.tsx, line: 19
           Type '{ color: string; onClick: string; }' is not assignable to type 'IonItemOptionAttributes'. Types of 
           property 'onClick' are incompatible. Type 'string' is not assignable to type 'EventHandler<MouseEvent>'. 

     L18:    <ion-item-option onClick="favorite(item)">Favorite</ion-item-option>
     L19:    <ion-item-option color="danger" onClick="share(item)">Share</ion-item-option>
     L20:  </ion-item-options>

```

**Comment by manucorporat** [comment] 2018-02-12 18:51
@kael using strings as event listeners is a "old" feature of JS that basically runs `eval("window.favorite()")`, so it is not possible in JSX.

You need to pass a function:
```
<ion-item-option onClick={(ev) => this.method(ev)}>Favorite</ion-item-option>
```

**Comment by brandyscarney** [comment] 2018-02-12 19:35
Also, the markup is off. Icons shouldn't have text inside of them:

```
<ion-item-options side="left" class='options-left'>
  <ion-item-option expandable>
    <ion-icon name="star">Button Left A</ion-icon>
    <ion-icon name="email">Button Left B</ion-icon>
  </ion-item-option>
</ion-item-options>
<ion-item-options side="right" class='options-right'>
  <ion-item-option expandable>
    <ion-icon name="alarm">Button Right A</ion-icon>
    <ion-icon name="notification">Button Right B</ion-icon>
  </ion-item-option>
</ion-item-options>
```

I think you're looking for something like this:

```
<ion-item-options side="left" class='options-left'>
  <ion-item-option expandable>
    <ion-icon name="star"></ion-icon>
    Button Left A
  </ion-item-option>
  <ion-item-option>
    Button Left B
    <ion-icon name="email"></ion-icon>
  </ion-item-option>
</ion-item-options>
<ion-item-options side="right" class='options-right'>
  <ion-item-option>
    <ion-icon name="alarm"></ion-icon>
    Button Right A
  </ion-item-option>
  <ion-item-option expandable>
    Button Right B
    <ion-icon name="notification"></ion-icon>
  </ion-item-option>
</ion-item-options>
```

I'm not able to reproduce the exact same UI as you though, here's what I see for the first example:

<img src="http://g.recordit.co/swc8yypiOE.gif">

and when I change the options to the second example:

<img src="http://g.recordit.co/EXOS5cnHuP.gif">

It looks off still because those icons don't exist in v4.

**Comment by kael** [comment] 2018-02-14 09:00
@manucorporat Thanks for the clarification.

For which version of Ionic does that [documentation](https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/item-sliding#ion-item-sliding) relate to ? I'd have thought it'd be for Ionic 4 with _stenciljs_, hence using JSX.

Also, the version numbering like _@ionic/core@0.0.2-48_ introduces some confusion if it's related to v4.

**Comment by kael** [comment] 2018-02-14 09:22
@brandyscarney : Thanks for the example. But something's still not working.

Before that, when updating the Ionic version to `@ionic/core@0.0.2-60` seems the CSS was then not applied.

So I re-cloned a new Ionic PWA Toolkit, updated the Ionic version (see below a sample of `package-lock.json`) but it looks fixed partially: only the left-swipe reveals the correct right item-options, the left ones are not displayed, and the left border of the left options (in green) is displayed only with extended left swipe.

* excerpt of package-lock.json:
```bash
$ cat package-lock.json | grep ionic -B 5 -A 5
  "name": "@stencil/starter",
  "version": "0.0.1",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@ionic/core": {
      "version": "0.0.2-60",
      "resolved": "https://registry.npmjs.org/@ionic/core/-/core-0.0.2-60.tgz",
      "integrity": "sha512-dA3aguVGCQrjzXNZ8YMuBegAT/mNnyWRBBSyjBfNVtfWgY1ejhIYJexkJuKHT7YQvnMWPVw7LNpWcBultZiX1A=="
    },
    "@ionic/discover": {
      "version": "0.3.3",
      "resolved": "https://registry.npmjs.org/@ionic/discover/-/discover-0.3.3.tgz",
      "integrity": "sha512-xciPTCEMYHv6sT7e4NwrAGkVQ8prj1NK9xO2z7/MoB+/HhREDsYDreNjU0lZF6G4X/91HcNNPC439D2WkAGd1w==",
      "dev": true,
      "requires": {
        "netmask": "1.0.6"
      }
--
      "version": "0.0.18",
      "resolved": "https://registry.npmjs.org/@stencil/dev-server/-/dev-server-0.0.18.tgz",
      "integrity": "sha512-3ybrK+7G6M+8j2fQ6LiLkONMtEhew0MbhfgcVF/skkqqrCEMioCKSt8uF8EzY38fkV6iH5S1KDVqyFuHv7SM7Q==",
      "dev": true,
      "requires": {
        "@ionic/discover": "0.3.3",
        "chokidar": "1.7.0",
        "ecstatic": "2.2.1",
        "opn": "5.1.0",
        "tiny-lr": "1.0.5"
      }
```

* src/components/app-home.tsx:

```tsx
  render() {
    return (
      <ion-page class='show-page'>
        <ion-header md-height='56px'>
          <ion-toolbar color='primary'>
            <ion-title>Ionic PWA Toolkit</ion-title>
          </ion-toolbar>
        </ion-header>
        <ion-content>
          <ion-list>
            <ion-item-sliding>
              <ion-item>
                <ion-label>Item</ion-label>
              </ion-item>
              <ion-item-options side="left" class='options-left'>
                <ion-item-option expandable>
                  <ion-icon name="star"></ion-icon>
                  Button Left A
                </ion-item-option>
                <ion-item-option>
                  Button Left B
                  <ion-icon name="email"></ion-icon>
                </ion-item-option>
              </ion-item-options>
              <ion-item-options side="right" class='options-right'>
                <ion-item-option>
                  <ion-icon name="alarm"></ion-icon>
                  Button Right A
                </ion-item-option>
                <ion-item-option expandable>
                  Button Right B
                  <ion-icon name="notification"></ion-icon>
                </ion-item-option>
              </ion-item-options>
            </ion-item-sliding>
          </ion-list>
          <stencil-route-link url='/profile/stencil'>
            <ion-button>
              Profile page
            </ion-button>
          </stencil-route-link>
        </ion-content>
      </ion-page>
    );
  }
```

* src/components/app-home.scss

```scss
app-home {
  ion-scroll {
    padding: 15px;
  }

  .options-right {
    border-right: solid thick red;
  }
  .options-left {
    border-left: solid thick green;
  }

  ion-item {
    border: solid thick orange;
  }
}
```

* Swipe Right:
![swipe-right-ionic-0 0 60](https://user-images.githubusercontent.com/2463/36196186-3a259cac-1170-11e8-8c59-c470630c8c74.png)

* Swipe Left:
![swipe-left-ionic-0 0 60](https://user-images.githubusercontent.com/2463/36196187-3a3db2ec-1170-11e8-8037-35d9403f9f2c.png)

What am I missing ? 🤔 

BTW, I'm not able to take a screenshot of the extended left swipe. Which tool do you use for the animated images capture ?

**Comment by kael** [comment] 2018-02-14 09:26
Addendum: In the above example I hadn't changed the icon, but even when testing with the `star` icon only for all buttons, it doesn't change the display of the left options.

**Comment by brandyscarney** [comment] 2018-02-14 15:59
@kael Our documentation in the README of each component uses HTML and vanilla JavaScript. Our plan is to keep the usage in the README files simple and then document different usage based on the framework elsewhere. 

The versioning of `@ionic/core` is lower because it is a new project, there will be a release under the tag `@ionic/angular`/`ionic-angular` for v4. 🙂

Thank you for giving me the steps to reproduce it! I was able to reproduce it in the PWA toolkit. I added a fix and released a new version of `@ionic/core` and tested it in the PWA toolkit and it looks good to me now: `@ionic/core 0.0.2-65` 

I am using [record it](http://recordit.co/) to record gifs of the screen:

<img src="http://g.recordit.co/hCI4JGcz7K.gif">

Please let me know how that version works for you! Thanks. 🙂

**Comment by kael** [comment] 2018-02-14 17:37
It does work now with `@ionic/core 0.0.2-65@, thank you !

Regarding the documentation, having a way to generate some HTML typedoc-based documentation would be nice. All the Ionic versions and their flavours make it a bit difficult to follow, though.

Regarding the scrolling of the list of items, it's not possible to scroll it by swiping vertically the items from the _center/middle_ of them, it has to be done on the right side, nearby the scrollbar. This is a different behaviour than Ionic3, wondering if it is by design.

And at last, I was wondering if you were using some kind of tests to validate your code based on some TS types ? Perhaps some contributors could help, considering tests are very important but so time consuming.

**Comment by brandyscarney** [comment] 2018-09-21 15:09
> Regarding the scrolling of the list of items, it's not possible to scroll it by swiping vertically the items from the center/middle of them, it has to be done on the left or on the right side, nearby the scrollbar. This is a different behaviour than Ionic3, wondering if it is by design.

I'm going to close this issue because the original issue was solved, but if this is still an issue with latest, could you please create a new issue? 🙂 

> And at last, I was wondering if you were using some kind of tests to validate your code based on some TS types ? Perhaps some contributors could help, considering tests are very important but so time consuming.

We have TS linters in our project and then also have e2e tests for the components. I think for this issue it would have been beneficial to have the e2e test check that the attribute was added to the element. We just switched the way we write our e2e tests actually. Here's an example of the latest way: https://github.com/ionic-team/ionic/blob/master/core/src/components/action-sheet/test/basic/e2e.ts

We'll get more documentation up on how to write the e2e tests soon, but it is definitely one of our goals to make sure these tests are extremely thorough in checking for attributes, classes, etc. We'll be working on porting our old e2e tests as we go through components. We definitely welcome all of the help we can get though. :smile:

**Closed by brandyscarney** 2018-09-21 15:09 UTC

**Comment by kael** [comment] 2018-09-21 16:10
Thanks a lot for your help and fixes for that bug. :+1: 

I might be back on the topic of tests, because I think we, as developers, could substantially help the Ionic team, by writing tests based on strongly typed components, and also for "auditing" components (based on our experience with this or that component).

The thing is that there seems to be lots of regressions (due to "stupid bugs", mainly attention ones, I'd say), and the idea is to be able to avoid all these lost time, and reduce the technical debt.

I believe there should be a set of tests for all components, for all Ionic versions (ideally, lol). That way, when incrementing from one version to another, if a component is supposed to have a "constant API", then we could easily detect bugs based on that "super test".

But I'm 1) digressing too much ; 2) don't know much about the tests and workflow of Ionic development. Gotta search a bit on the topic.

Cheers.

**Comment by brandyscarney** [comment] 2018-09-21 16:43
> The thing is that there seems to be lots of regressions (due to "stupid bugs", mainly attention ones, I'd say), and the idea is to be able to avoid all these lost time, and reduce the technical debt.

I completely agree. We just recently merged a new screenshot tool that will run in CI. Previously we used a tool called snapshot which ran on selenium and compared the components against the master look (I actually wrote a blog on it awhile ago [here](https://blog.ionicframework.com/snapshot-ionic-frameworks-fail-safe/)). There were a few issues with our snapshot tool:
- it required us to run it manually on our computers which caused:
  - discrepancies between devices
 - us to not be able to use our computer the entire time it was running
- it was slow, which caused a loss of time because of the above reason
- it broke when we ported to shadow dom

So because of this we started working on a new tool called `screenshot` which will run on puppeteer. We _just_ merged the tool into master, and there are only a few tests migrated over, but it is working well so far. Our plan is to migrate the existing tests that haven't been working for awhile to the new e2e tests, create a master screenshot of all of our components, and then work on adding in more thorough tests and getting it picture perfect. Then, once all of our tests are there, we want to make sure we are submitting PRs and having CI run the screenshot tool against the PR. This way no code would get into master unless the tests are passing, thus avoiding regressions. 

The new tests can do anything jest can do, you can see some examples of what they can do here: https://github.com/ionic-team/stencil/blob/master/test/example/src/dom-api/dom-api.e2e.ts

For example, it will be able to check for classes:

```
expect(elm).toHaveClass('class-c');
expect(elm).not.toHaveClass('class-d');
```

check for attributes:

```
expect(elm).toHaveAttribute('mph');
expect(elm).not.toHaveAttribute('whatever');
```

and of course more, such as checking the value of an attribute on the element:

```
expect(elm.getAttribute('mph')).toBe('88');
```

I think this will really go far in improving our testing and making sure we aren't introducing regressions. Let me know your thoughts. 🙂

**Comment by kael** [comment] 2018-09-22 09:46
Hey @brandyscarney,

I have more ideas on the topjc of tests now, your last message made start investigating the subject and I might have found some interesting stuff.

Give me so days to investigate further and gather my thoughts (I'm focused on another complicated matter for few days), and I'll open a new ticket discussing a feature request.
