### ISSUE TITLE
feat: Support for HTML5 features for Alert Inputs

### ISSUE THREAD

**Issue by cerkiner** [ionic-team/ionic#21290] opened 2020-05-13 14:20 UTC
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
It is necessary to add special attributes such as maxLength, inputmode, pattern, id etc. on inputs while using AlertController.

**Describe Preferred Solution**

Have new options for inputs to set custom attributes while creating alerts;

```
alert.addInput({
      name: 'pin',
      placeholder: 'Pin Code',
      type: 'password',
      maxLength: 4,
      inputmode: 'numeric',
      ...
});
```

**Describe Alternatives**

```
alert.present().then(v => {
   let input = (document.querySelector('ion-alert input') as any);
   if (input) {
      input.setAttribute('maxlength','4');
      input.setAttribute('inputmode','numeric');
      ...
   }
});
```

However, this is just a hacky workaround and it gets complicated really quickly with multiple inputs. I think Ionic team should include a feature to add custom attributes and other native HTML5 features for inputs.

**Comment by liamdebeasi** [comment] 2020-05-13 15:34
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21202.

**Closed by liamdebeasi** 2020-05-13 15:34 UTC
Labels: triage

**Comment by cerkiner** [comment] 2020-05-14 02:19
Oh okay. Sorry for the duplicate. I was working on this issue/improvement for some time. I checked when I started but I didn't re-check when I created the issue.
