### ISSUE TITLE
DateTime pickerFormat dynamic update issue

### ISSUE THREAD

**Issue by mzealey** [ionic-team/ionic#12072] opened 2017-06-16 18:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Trying to change the `displayFormat` based on a different setting does not immediately update the view. Snippet:

```
                    <ion-toggle checked="false" [(ngModel)]="model.all_day" name="all_day" #allDay="ngModel"></ion-toggle>
                    <ion-datetime
                            [displayFormat]="'DD/MM/YYYY' + (model.all_day ? '' : ' HH:mm')" ...>
```

The display's format is only updated when you click on the element. I guess it is not watching the `displayFormat` for changes.

**Comment by jgw96** [comment] 2017-06-19 14:33
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker](http://plnkr.co/edit/cpeRJs?p=preview) that demonstrates this issue? Thanks for using Ionic!

**Comment by digaus** [comment] 2017-06-20 13:42
Might also be related to this issue: https://github.com/ionic-team/ionic/issues/11034

**Comment by mzealey** [comment] 2017-06-24 12:18
http://plnkr.co/edit/cuxzwSYt45kElFFHZixR?p=preview

Choose a date, then toggle the all day toggle and the displayed date picker value does not update. But when you click on the date again, the rendering does update (as does the picker format correctly).

**Comment by bryan-oliveira** [comment] 2018-02-19 07:15
Has anyone been able to find a work around for this issue?

**Comment by manuel-dev** [comment] 2018-02-28 13:59
Hi bryan
While they fix this issue you can do the next to make it work:

In your view html use:

`<ion-datetime [monthNames]="monthNames" ...>`

In your controller, declare a variable in yout class called monthNames, and try to keep it updated with current language, calling translation on every change with:

`this.translate.get('MONTH_NAMES').subscribe((res: string) => {this.monthNames = res;
});`

Hope it works for you.

**Comment by Stian-Scholtz-XTRAPOLATE** [comment] 2018-10-09 13:08
Is there still no fix for this issue? The solution posted by manuel-dev does not work.

**Comment by bryan-oliveira** [comment] 2018-10-09 14:38
@Stian-Scholtz-XTRAPOLATE, I based my solution on @manuel-dev's answer, just with a tiny twist. I use the same string array with the translated month names.

In my case, since changing the language settings requires navigating to a different screen, I make a call to get the array of translated month names inside `ionViewWillEnter()`.

In this way, `_monthNames` always updates to the current language, and renders properly.

HTML:
`<ion-datetime [monthNames]="_monthNames" ... >`

Module:
`private _monthNames: string[];`
```
ionViewWillEnter() {
  this._monthNames = dateTimeService.getTranslatedMonthNames();
  ...
}
```

**Comment by Stian-Scholtz-XTRAPOLATE** [comment] 2018-10-10 10:56
Thank your for providing your solution @bryan-oliveira. Unfortunately I have a button in a sidemenu that changes the current language which means I cannot make use of the lifecycle hooks.

**Comment by NiklasMerz** [comment] 2018-11-01 08:15
I can confirm this issue in v3.8.0. Setting `displayFormat` in the constructor does not update the displayed format. The new format appears after I click on the date.

**Closed** 2018-11-01 19:50 UTC
Labels: ionitron: v3, v2
