### ISSUE TITLE
bug: IonSelect doesnt show selected placeholder sometimes

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21472] opened 2020-06-09 22:08 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

If IonSelect is preselected, it doesnt shows the content of IonSelectOption sometimes. This happens randomly. If I open and close IonSelect, it shows the placeholder again. In the DOM I can see that everything is fine.

**Expected behavior:**

It should show the Content of the Option Element which is selected.

**Steps to reproduce:**

Cannot reproduce. Just try reloading, and hope.

**Comment by BerkeAras** [comment] 2020-06-11 07:14
The Bug happens if an AJAX Call takes a little bit longer. I could simulate an AJAX Call which takes a second (with setTimeout) and there you can see the bug: https://codepen.io/BerkeAras/pen/vYLLqMp

**Comment by liamdebeasi** [comment] 2020-06-11 14:45
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19324.

**Closed by liamdebeasi** 2020-06-11 14:45 UTC
Labels: ionitron: needs reproduction
