### ISSUE TITLE
feat: Add css ::part selector to components or more css variables to allow for further customization of components

### ISSUE THREAD

**Issue by lriostavira** [ionic-team/ionic#21490] opened 2020-06-11 01:22 UTC
# Feature Request

**Ionic version:**

[x] **5.x** @ionic/react

**Describe the Feature Request**

An example would be ion-segment-button, it's shadow dom consists of a button that has a min width of 90px for android styling. there is no clear way of modifying this style. if a --min-width variable was available it would be simple, as well as having a part selector.

**Describe Preferred Solution**

Add css ::part selector to components or more css variables

**Describe Alternatives**

workarounds include adding classes to ionic components and styling the variables to accomadate

**Comment by liamdebeasi** [comment] 2020-06-11 14:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21105.

**Closed by liamdebeasi** 2020-06-11 14:28 UTC
Labels: triage
