### ISSUE TITLE
Ionic 2 Side Menu with tab now Working

### ISSUE THREAD

**Issue by premji1528** [ionic-team/ionic#12857] opened 2017-09-11 13:01 UTC
**Ionic version:** 
[x] **2.x** 
[x] **3.x**

**I'm submitting a ionic version [3.x] bug report**

support request => https://forum.ionicframework.com/t/ionic-2-push-child-view-inside-the-tabs-view-with-side-navigation/102306

****Current behavior:**
When push the new child view clicking the navigation menu push the child-view inside the tabs view it appear only child view and the tabs view automatically will disappearing.

![current begaviour](https://user-images.githubusercontent.com/8487640/30275485-18390f1e-971f-11e7-954f-75d7da88c121.png)

**Expected behavior:**
After clicking the menu link the child_view Should appear inside the tabs view and both tabs view and child view should be display but tab is gone if i did that.
**Push the child view inside the tabs-view.**

![expected](https://user-images.githubusercontent.com/8487640/30275481-148b7366-971f-11e7-8392-a0116232b95e.png)

I have tried with conference app.. in that app they are giving only can access the tabs-pages only.

**Steps to reproduce:**

**Related code:**
[Download the Source file here](https://github.com/Manojkumarr130308012/sample/files/1292488/sample.zip)

[GitHub repository source files](https://github.com/Manojkumarr130308012/sample)
**Other information:**
 I have Attached the source file too.

**Comment by kensodemann** [comment] 2017-09-11 19:23
Hello! Thank you for opening an issue with us! The sample application you provided just appears to be the files from an application somehow all squashed into a single directory and not a normally structured application. Could you modify your git repo such that it is a sample application that can be pulled and built? That would help a lot in us being able to start looking into your issue.

Thanks for using Ionic!

**Comment by kensodemann** [comment] 2017-09-11 19:27
As it turns out, the download link you have above is much better with regard to this than the GitHub repo is. I'll start with that.

Thanks!

**Comment by kensodemann** [comment] 2017-09-11 19:47
Here is what is happening in your application:

```ts
  openPage(page) {
    // Reset the content nav to have just this page
    // we wouldn't want the back button to show in this scenario
    this.nav.setRoot(page.component);
  }
```

The `openPage()` in `app.component.ts` is replacing the root page on the main nav with whatever you choose from the menu. This replaces the tabs, which you don't want to do. You want to leave that set as-is from this line: `rootPage: any = TabsPage;`

What you really want to do is get ahold of the nav controller for the tabs and `push()` the page onto is (not the base nav, but the nav for the tabs page).

I am going to close this issue as it is not a bug with the Ionic Framework itself.

I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/) to determine how to best architect your application for what you want to accomplish.

Thanks for using Ionic!

**Closed by kensodemann** 2017-09-11 19:47 UTC
