### ISSUE TITLE
bug: Keyboard change from AZERTY to QWERTY after openning type="tel" input

### ISSUE THREAD

**Issue by maximedasilva** [ionic-team/ionic#20007] opened 2019-11-27 13:55 UTC
# Bug Report

**Ionic version:**
[x] **4.12.0**

**Current behavior:**
On a Iphone Xr (iOS 13.1.2) default keyboard is in AZERTY mode. 
But after opening an ion-input "type=tel" the keyboard is changed to QWERTY. 

Here you can see a gif that explains the problem. 
![gif](https://user-images.githubusercontent.com/10706836/69728256-735a1600-1124-11ea-9dad-fbcf2f3fc4e5.gif)

**Expected behavior:**
The keyboard doesn't change from AZERTY to QWERTY when we use an ion input with type="tel".

**Steps to reproduce:**
click a text input, the keyboard is in AZERTY. click on a type=tel input, click on a text input, the keyboard changed to QWERTY. 

**Related code:**

```
<ion-item>
    <ion-label>FirstName</ion-label>
    <ion-input type="text"></ion-input>
</ion-item>
     
<ion-item>
    <ion-label>Phone</ion-label>
    <ion-input type="tel" maxlength="10"></ion-input>
</ion-item>
```

**Comment by liamdebeasi** [comment] 2019-11-27 14:18
Thanks for the issue. Do you have multiple keyboards setup on your device? You can find this by going to the Settings app > General > Keyboard > Keyboards. The last screen you land on should show you all keyboards configured on your device as well as the button layout.

**Comment by maximedasilva** [comment] 2019-11-27 14:31
I have one language set up : Français(France) which contains 5 keyboards :

- AZERTY accentué
- AZERTY
- QWERTY accentué
- QWERTY
- QWERTZ

**Comment by liamdebeasi** [comment] 2019-11-27 15:21
Thanks for the follow up. I am unable to reproduce the behavior you are describing. Can you provide a repo with the code required to reproduce this issue?

**Comment by maximedasilva** [comment] 2019-11-27 16:47
We finally found out, 

we've added defaultLocale="fr" in the config.xml.

It seems that the App is launched with the selected keyboard in  `Settings app > General > Keyboard > Keyboards` (AZERTY in our case), but when the keyboard change (to be a type tel in our example), the keyboard configuration follow app language (which was probably english and QWERTY in our app)

**Comment by liamdebeasi** [comment] 2019-11-27 17:35
Glad to hear you were able to figure it out. I am going to close this as the original issue appears to be resolved. Thanks!

**Closed by liamdebeasi** 2019-11-27 17:35 UTC
Labels: triage

**Comment by maximedasilva** [comment] 2019-12-18 13:19
Hi,

Unfortunetly I'll reopen it as my issue is still present.

But, to reproduce it, we added an other keyboard into our app. (Anglais E-U).
When we enter a type=tel input, our app change from AZERTY french keyboard, to QWERTY US Keyboard.

The addition of defaultLocale variable did not repair anything, but in our test we certainly deleted a keyboard which repaired this issue by prevent app from changing to an other keyboard.
