### ISSUE TITLE
Virtual scroll does not work in an empty conditional element

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic#12565] opened 2017-08-03 10:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using virtualScroll in a element that renders on condition (among others *ngIf) and the element is completely empty (besides the virtual scroll elements) the list will not render. Putting in anything inside the div will make it appear  (even a &nbsp; will do)
**Expected behavior:**
It renders always

**Steps to reproduce:**
http://plnkr.co/edit/zJSEfkUWb2c1GzxTXKDV?p=preview

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
version 3.6.0

**Comment by Remco75** [comment] 2017-08-03 10:19
hmm, the behaviour is a bit ore weird: it needs a change-detection cycle to kick in it seems

**Comment by Remco75** [comment] 2017-08-03 10:24
also in more complex situation (like nesting a ngIf inside a  ngSwitchCase which contains a list, i can not get the list to show up

**Comment by Ozzyris** [comment] 2017-08-04 01:26
I'm experiencing the same issue. @Remco75 if you found a stable solution, I am very interested.

**Comment by Remco75** [comment] 2017-08-04 07:20
@Ozzyris  nope, atm I can not use vritualscroll in my usecase. I hope someone has a suggestion ( or better yet, a fix ;-))

**Comment by Ozzyris** [comment] 2017-08-04 08:19
I found a fix to make it work in my case, by replacing "*ngIf=" by "[hidden]=" ! Hope that can help.

**Comment by Remco75** [comment] 2017-08-04 08:47
Cool Will try that. But the whole point of virtual scroll is to be as cheap as possible.... That's why the if, to render less, with the least amount of bindings.. so still I think this needs a fix

**Comment by Ozzyris** [comment] 2017-08-04 08:51
Yes you are right, let's just say that's can be a quick fix until we have a proper one.

**Comment by jgw96** [comment] 2017-08-04 16:04
Hello all! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/9655. Thanks!

**Closed by jgw96** 2017-08-04 16:04 UTC

**Comment by Remco75** [comment] 2017-08-05 10:16
@jgw96 sorry, missed the double. But that has been open for a long time. Is there any change it will be resolved any time soon?

**Comment by Wiki1991** [comment] 2017-11-08 06:32
"[ngClass]='{'hide':!data}'" replace "*ngIf" it works for me
