### ISSUE TITLE
bug: collapsible header: main + inactive header does not have a background color

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic#20385] opened 2020-02-05 15:01 UTC
# Bug Report

**Ionic version:**

[x] **5.0.0-dev.202002041730.fbcf48c**

**Current behavior:**
When using collapsible headers on iOS, the main header cannot have a a background color when it is in inactive state, because the `opacity` of its toolbar is set to `0` and the header itself does not have a background-color:

https://github.com/ionic-team/ionic/blob/215d55f1ebeb93988b513c5869faae14d1d51919/core/src/components/header/header.tsx#L106

While this works well when the root `--ion-background-color` and `--ion-toolbar-background` are the same color, it prevents from using a different color for toolbars because it will look really strange:

Main header inactive:
![Screenshot 2020-02-05 at 15 41 26](https://user-images.githubusercontent.com/7592254/73851580-05ba1c80-482e-11ea-9854-da8fe7262456.png)

Main header active:
![Screenshot 2020-02-05 at 15 42 12](https://user-images.githubusercontent.com/7592254/73851652-23878180-482e-11ea-879f-c4326b119e6b.png)

**Expected behavior:**
Toolbars in inactive headers can have a background color.

**Steps to reproduce:**
- clone sample application
- npm i
- ionic serve

**Related code:**
[A sample application via GitHub](https://github.com/DavidStrausz/ion-header-bug)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-dev.202002041730.fbcf48c
   @angular-devkit/build-angular : 0.900.0-rc.14
   @angular-devkit/schematics    : 9.0.0-rc.14
   @angular/cli                  : 9.0.0-rc.14
   @ionic/angular-toolkit        : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0 (/usr/local/bin/node)
   npm    : 6.11.3
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-02-05 15:24
Thanks for the issue. So typically in native iOS apps, the blank space you are seeing is supposed to be the main content.

This can be seen in the iOS Settings app, where the space above the large "Settings" title has the same background as the main content. Once you collapse the large title, the smaller header fades in and the smaller header's background color is visible.

In the case of your app, you would need to do two things:

1. Set `translucent` on the `ion-header` and `fullscreen` on `ion-content`. When Ionic v5 launches, this will be required in order for the collapsible header to function properly.
2. Set `color="primary"` on the `ion-toolbar` elements as well as `ion-content`.

Your `home.page.html` should look like this:

```html
<ion-header translucent>
  <ion-toolbar color="primary">
    <ion-title>Home</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen color="primary">
  <ion-header collapse="condense">
    <ion-toolbar color="primary">
      <ion-title size="large">
        Home
      </ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-list>
    ...
  </ion-list>
</ion-content>
```

The end result would look something like this:
![image](https://user-images.githubusercontent.com/2721089/73855157-a6deae00-4801-11ea-8daf-318a1d939381.png)

Does this work for your use case?

**Comment by DavidStrausz** [comment] 2020-02-05 16:49
@liamdebeasi I agree, it works if header and toolbar have the same color, but I just noticed this also has a flaw which is clearly visible on high-res devices: 

I changed the markup of my example repo to match yours - so we are on the same page.
If you run it in the browser you can not really see the difference very well but if you run it on a device you will se the difference:

- In the main header `div.header-background` has the backdrop filter applied also in inactive state, this makes it appear slightly lighter (you have to really look closely on a laptop screen to spot the difference, but on an iPhone 11 pro for example the difference is clearly noticeable):

![image0](https://user-images.githubusercontent.com/7592254/73861653-9ba97380-483d-11ea-98fc-09e5791babe9.png)

And regarding our use-case, we _want_  to (and always did) use different colors for content and tab-bar/headers. Maybe screenshots explain it better. 

This is what it currently looks like:
![image2](https://user-images.githubusercontent.com/7592254/73862719-440c0780-483f-11ea-844b-acf994f9b4c0.png)

And this is what it is supposed to look like (I set `opacity: 1` for the toolbar-background in inspector):
![image1](https://user-images.githubusercontent.com/7592254/73862798-5ab25e80-483f-11ea-8fa4-636567c2b191.png)

**Comment by liamdebeasi** [comment] 2020-02-05 19:29
Thanks for the follow up. Can you try the following dev build and let me know if it resolves your issue? `5.0.0-dev.202002051926.2f945a1`

**Comment by DavidStrausz** [comment] 2020-02-06 12:58
@liamdebeasi Yes perfect, thank you!

**Comment by liamdebeasi** [comment] 2020-02-06 14:41
Glad to hear the issue is resolved! This has been resolved via https://github.com/ionic-team/ionic/pull/20388 and will be available in an upcoming release of Ionic Framework.

**Closed** 2020-02-06 14:41 UTC
Labels: triage
