### ISSUE TITLE
Min and max properties of ion-datetime are not working properly

### ISSUE THREAD

**Issue by Artfloriani** [ionic-team/ionic#17060] opened 2019-01-11 12:39 UTC
# Bug Report

**Ionic version:**
[x] **4.0.0-rc.1**

**Current behavior:**
The selected date on the datetime picker does not update while choosing a date, this has a few issues with the min and max properties:

**min property**
If I set the the `min` property to today's date, the datetime picker does not show the past days from the current month as expected. But when scrolling to the next month, the previous days are still not available in the picker. To select a day that is lower than the current day, you need to first select the next month,  tap "Done" and then open the picker again and select the desired day.

E.g.: 
```
<ion-datetime
    displayFormat="DD/MMM"
    min="2019-01-11">
</ion-datetime>
```

If I want to select 2nd of February, I need first to select February, then re-open the picker and select the day. 

**max property**
A similar issue happens with the max property. If you set the `max` property to any month in the future, you can first scroll to a day that is after the max day, and then scroll to the month from the `max` property. This will allow you to select a date that is after the `max` property. When using `(ionChange)` to view these values, you can check that the emitted value is actually after the `max` property. 

**Expected behavior:**
When using the datetime picker, I expect to be able to select any value between the `min` and `max` properties, without having to close and open the picker again to update the available options.

**Steps to reproduce:**

For `min` bug:
Use the code below and scroll down to `Feb`. Days between 1 and 11 are to available unless you click `done` and open again.
```
<ion-datetime
    displayFormat="DD/MMM"
    min="2019-01-11">
</ion-datetime>
```

For `max` bug:
Use the code below and scroll down to day `30`. Scroll down to May and you will be able to select a date after `2019-05-11`. 
```
<ion-datetime
    displayFormat="DD/MMM"
    max="2019-05-11">
</ion-datetime>
```

**Related code:**
Please, update the plunker links to provide a Ionic 4 same app 👍 

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.0.7
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/~username~/Library/Android/sdk/)
   ios-deploy        : 1.9.2
   NodeJS            : v8.12.0 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 9.2 Build version 9C40b
```

**Disclaimer**: English is not my native language so the issue description might be a bit confusing. Please let me know if you need a clearer example in order to reproduce this issue.

**Comment by paulstelzer** [comment] 2019-01-11 12:42
ion datetime has a lot of issues, see collected here -> #16630 

I added yours to the list because you made some easy understandable codes to reproduce :)

**Comment by iAmAnkeeta** [comment] 2019-01-25 04:35
Here is the screenshot of the issues i am running into
#### Scenario # 1
```
<ion-datetime display-format="MMM D, YYYY" min="2019-01-15" max="2020-01-01"></ion-datetime>
```

<img width="385" alt="screen shot 2019-01-24 at 11 26 23 pm" src="https://user-images.githubusercontent.com/18538734/51725392-e049de80-202f-11e9-9698-df27d3210268.png">

--------------------------------------------
#### Scenario # 2
```
<ion-datetime display-format="MMM D, YYYY" min="2019-01-15" max="2019-12-31"></ion-datetime>
```
<img width="384" alt="screen shot 2019-01-24 at 11 30 49 pm" src="https://user-images.githubusercontent.com/18538734/51725440-2c951e80-2030-11e9-8ff2-b7260517a2b1.png">

I cannot select Feb 01 on # 2 unless I select Feb 15 > Done > tap on date picker > then i can select Feb 1.
<img width="385" alt="screen shot 2019-01-24 at 11 32 40 pm" src="https://user-images.githubusercontent.com/18538734/51725525-a6c5a300-2030-11e9-91c1-571fb0e98a1d.png">

**Comment by proartti** [comment] 2019-02-04 23:54
We are having the exact same issue here. A quick fix for this would be awesome. (related to this Ionic 3 bug - [12319](https://github.com/ionic-team/ionic/issues/12319))

**Comment by liamdebeasi** [comment] 2019-02-12 15:02
Hi there,

Thanks for opening an issue with us. I am going to close this for now, but we will be re-evaluating the `ion-datetime` functionality and bugs soon during which we will take a closer look at this issue.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-12 15:02 UTC
Labels: package: core, type: bug
