### ISSUE TITLE
bug: @ionic/react-router not go back expected

### ISSUE THREAD

**Issue by zawaliang** [ionic-team/ionic#19748] opened 2019-10-25 07:03 UTC
Bug Report

**Ionic version:**
**4.11.2**

**Current behavior:** 
At root page A, I redirect to page B, then C, then B again, when I go back,  it go to root page A

**Expected behavior:**
It should not skip page C, it should go B>C>B>A

**Other information:**
I think the reason is @ionic/react-router maintain only a DOM node for each route pattern, when I visit the same route already in DOM, it will change the DOM‘s visibility

I fix the problem by this https://github.com/zawaliang/ionic-react-router-fix/blob/master/index.js
I maintain each DOM node for each page, not for route pattern, it works; but it may has some unexpected problems, so I wish it should be fixed in next version.

**Comment by liamdebeasi** [comment] 2019-10-25 14:09
Thanks for the issue. I am able to reproduce this. We will look into a fix!

**Comment by elylucas** [comment] 2019-10-30 20:51
Hello, this issue should be fixed in 4.11.3. Please give it a try and if you find more issues, comment here and we can reopen this issue.

**Comment by aykamko** [comment] 2019-10-30 21:42
Still experiencing this issue with 4.11.3

**Comment by elylucas** [comment] 2019-10-30 22:06
Thanks, we will look into this one further.

**Comment by elylucas** [comment] 2019-11-07 22:11
ok, think this is resolved now in 4.11.4, give it a try and let me know @aykamko, @zawaliang

**Closed by elylucas** 2019-11-07 22:11 UTC
Labels: package: react, type: bug

**Comment by aykamko** [comment] 2019-11-07 23:22
The bug appears to be resolved! Thank you!

**Comment by zawaliang** [comment] 2019-11-13 03:33
Thank you, the location stack is fixed.

But what I want is to keep every page state when I go back; but now when I go back, the page which be visited twice or more will render again。 

eg:
from: A->B1->C->B2
B1 and B2 are the same route page, maybe has different url params, when go back from B2 to C, the B2 page wil remove from DOM, so when go back from C to B1, the B1 page will rebuild, the state will lost

**Comment by marcoromag** [comment] 2019-11-13 09:13
Hi @zawaliang, I think this is due to the fact that B1 and B2 share the same ViewItem in the Ionic ViewStack. see #19891

**Comment by zawaliang** [comment] 2019-11-14 02:02
@marcoromag Yes, it needs to be optimized
