### ISSUE TITLE
Swipe to go back does not work when page is pushed to rootNav

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/ionic#9558] opened 2016-12-08 17:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After pushing a page to rootNav it's not possible to swipe back (Back button works though).

```
import { Component } from '@angular/core';

import { App } from 'ionic-angular';

@Component({
	selector: 'mini-player',
	templateUrl: 'mini-player.html'
})
export class MiniPlayerComponent {

	public constructor(protected _app: App) { }

	public gotoPlayer(): void {
		this._app.getRootNav().push(PlayerPage);
	}

}
```

**Expected behavior:**
You should be able to swipe back. I'm pretty sure this used to be the case.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201612081620
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by manucorporat** [comment] 2016-12-08 23:09
I can't help you out with so few information. I don't now which Nav is retuning getRootNav() or the structure you are using.

**Comment by biesbjerg** [comment] 2016-12-09 00:59
Sorry to hear that. Here's a repo that hopefully demonstrates it.

https://github.com/biesbjerg/9558-ionic-swipe-back-bug

**Comment by izee** [comment] 2016-12-16 08:31
similar as #9632 , I set swipeBackEnabled to false now.

**Comment by jgw96** [comment] 2016-12-22 17:19
Update: i have a fix for this issue, but i need to heavily heavily test it

**Comment by brandyscarney** [comment] 2017-01-13 19:41
This should be fixed in the next release. I created a nightly with the fix in it, could you test it out and let us know if you find issues?

```
npm install --save --save-exact ionic-angular@2.0.0-rc.5-201701131937
```

Thanks. :)

**Comment by RedEars** [comment] 2018-03-08 01:57
Why is the fix by @jgw96 not present in the current ionic version? The issue is the same on the current version and applying the changes to the nav-controller file from @jgw96 fixes the issue

**Comment by brandyscarney** [comment] 2018-03-08 15:55
It looks like this change was modified here: https://github.com/ionic-team/ionic/commit/5cad96570fe6b5643552222da119122245a067d6#diff-e2ff03d41e79743e24a3a97cabc0c1daR1046

Reopening this so we can keep this in mind.

**Comment by BorntraegerMarc** [comment] 2018-10-30 15:07
I still have the same issue in the newest v3 of ionic.

**Closed** 2018-11-28 21:49 UTC
Labels: ionitron: v3, v2
