### ISSUE TITLE
Ionic execute a function exactly once when the app is brought back to the foreground

### ISSUE THREAD

**Issue by thepiyush13** [ionic-team/ionic#12013] opened 2017-06-12 00:21 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When the user brings the app to the foreground,  I want to able to run a function(refreshApp) exactly once so the app can show the latest view to the user.  I am using platform resume subscription(details below) for 
case 1) when the app is still in memory 
and ionViewDidLoad for 
case 2) when it's not in the memory anymore. 

However, the refreshApp function fires twice(from within platform subscription and ionViewDidLoad) in case 1 which is strange because as per the docs the view should be cached and ionViewDidLoad should fire only once while the page is being created. In my case it is firing every time I bring the app to the foreground.

**Expected behavior:**

Run refreshApp exactly once when:
1.  App-> comes to foreground but still in memory
2. App-> comes to foreground but not in memory

**Steps to reproduce:**

**Related code:**

```
page home.ts


constructor() {
    this.onResumeSubscription = this.platform.resume.subscribe(() => {
      this.refreshApp(); }
);

ionViewDidLoad() {
 this.refreshApp();
}
```

**Other information:**

Only tested this on Android

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info here

Cordova CLI: 7.0.1
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.10.0
Xcode version: Xcode 8.3.3 Build version 8E3004b
```

**Comment by jgw96** [comment] 2017-06-12 14:31
Hello, thanks for opening an issue with us! Would you be able to share a repo we could use to reproduce this issue, please?

**Comment by jgw96** [comment] 2017-06-19 19:46
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-19 19:46 UTC
Labels: needs info, v2
