### ISSUE TITLE
@ionic/core is not transpiled to ES5

### ISSUE THREAD

**Issue by dex4er** [ionic-team/ionic#15398] opened 2018-08-30 15:36 UTC
# Bug Report

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : not available
   Cordova Plugins       : not available

```
insert the output from ionic info here
```

**Describe the Bug**
@ionic/core library is not transpiled to es5 (it is es2017 maybe?)

**Steps to Reproduce**
```
ionic build
```

Check www/vendor.js

**Expected Behavior**
Ionic is an only library not transpiled to es5. 

I don't suspect that ionic v4 will work with old webview but white page only application is not acceptable.

I could use ie https://www.npmjs.com/package/cordova-plugin-webview-checker to detect webview version and redirect to Google Play page if it is too old, but... it won't work because of ionic is not es5 only :(

**Comment by yuankunluo** [comment] 2018-09-05 06:44
yes, same issue

**Comment by yuankunluo** [comment] 2018-09-08 10:27
#15438

**Comment by mhartington** [comment] 2018-09-11 13:51
Closing as a duplicate of #15438

**Closed by mhartington** 2018-09-11 13:51 UTC
Labels: triage
