### ISSUE TITLE
bug: IonRouterOutlet needlessly re-renders route

### ISSUE THREAD

**Issue by OoDeLally** [ionic-team/ionic#20365] opened 2020-02-03 14:55 UTC
# Bug Report

**Ionic version:**
4.11.10

**Current behavior:**
`<IonRouterOutlet>` always renders any page twice for no good reason.
It seems that the prop object is recreated while its values did not.

**Expected behavior:**
`<IonRouterOutlet>` always renders any page twice for no good reason.

**Steps to reproduce:**
Create a starting Ionic project, e.g.
```
ionic start myproject tabs
```
with React.

Then add a log in the render fonction of any tab e.g. `Tab3Page`. You can see it is called twice, while its props did not change a bit.

When testing it with `whyDidYouRender` (https://github.com/welldone-software/why-did-you-render), I get 
![image](https://user-images.githubusercontent.com/1717629/73663308-96adbe00-469d-11ea-96a2-1bfe7721aea8.png)

**Ionic info:**

```
▶ ionic info

Ionic:

   Ionic CLI       : 5.4.4 (/home/pascal/.nvm/versions/node/v8.16.0/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.10

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   NodeJS : v8.16.0 (/home/pascal/.nvm/versions/node/v8.16.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15


```

**Comment by elylucas** [comment] 2020-02-10 22:16
It's not needless :).  Theres quite a bit of setup thats done when an Ionic Page renders the first time, and, unfortunately, it requires us to first render it, then wait for the web component to kick in, then set a state variable to let us know its ready. 

You can control how your particular page renders, though:

1) Don't pass in the location and history props to your component. By using the `component` prop on a route, it passes the route props to your component, so any change to a route will cause your component to rerender. Instead, use the render prop on Route and don't pass any unnecessary props to your page.

2) Memoize your component by using either React.memo (if your page is a FC), or by using PureComponent if you are using a class.

However, these are really micro-optimizations that probably won't increase the performance of your page, unless your render takes a really long time, in which then you should be doing a memo anyways.

Going to close this as its not a bug with the framework, but feel free to post back here if you have more questions or comments.

Thanks

**Closed by elylucas** 2020-02-10 22:16 UTC
Labels: package: react

**Comment by skmohammadi** [comment] 2020-03-11 15:56
I am u

**Comment by skmohammadi** [comment] 2020-03-11 16:31
With thanks to @elylucas. I am using the following function to private routing:
`const PrivateRoute = ({ component, ...rest }: RouteProps) => {
  const { authState } = useAuth()!;
  if (!component) {
    throw Error('component is undefined');
  }
  const Component = component:
  return (
    <Route {...rest} render={(props) => (
      authState.isAuthenticated
        ? <Component />
        : <Redirect to="/login" />
    )} />
  );
}`
So, how to get ride of `props` from `<Component {...props} />`?
