### ISSUE TITLE
bug: Modal is not dismissed when navigating back

### ISSUE THREAD

**Issue by rveerd** [ionic-team/ionic#18070] opened 2019-04-18 08:03 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
If a modal is shown, and the user navigates back using the browser back button, the browser goes to the previous page but the modal remains visible and is not dismissed.

**Expected behavior:**
When the user uses the browser back button and navigation occurs, the modal should be dismissed.

**Steps to reproduce:**
* Create an app with two routes. The second page presents a modal.
* Navigate from the first page to the next.
* Present a modal on the second page.
* Press the browser back button. The browser returns to the first page but the modal is not dismissed.

**Related code:**

https://github.com/rveerd/ionic4-issue-modal-back

**Other information:**

Tested on Windows with Chrome.

The problem was already reported for Ionic 3 in [#13964](https://github.com/ionic-team/ionic/issues/13964).
The problem is already reported in [#15422](https://github.com/ionic-team/ionic/issues/15422), specifically for Android and the hardware back button. However the problem also occurs on the desktop with the browser back button or hotkey.
The problem was already mentioned in [#16946](https://github.com/ionic-team/ionic/issues/16946), which may be a related issue.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.11.0
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : Windows Server 2016
```

**Comment by liamdebeasi** [comment] 2019-04-18 13:08
Hi there,

Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16946. (the issue references popovers, but underlying issue is the same)

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-18 13:08 UTC
Labels: triage
