### ISSUE TITLE
Blue outline around button

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#21027] opened 2020-04-13 10:58 UTC
<img width="1683" alt="Screen Shot 2020-04-13 at 6 54 21 PM" src="https://user-images.githubusercontent.com/14093665/79115552-bad1fd80-7db8-11ea-8bbd-cd98b997b394.png">

Is this a bug or is this something i can disable? It only shows while the button is actively pressed

**Comment by NikolaPeevski** [comment] 2020-04-13 11:33
Can you provide an html snipped of how you've used the button and related styling ?

**Comment by assman** [comment] 2020-04-13 11:37
Yes Nikola, here it is:

<ion-button routerLink="/sign-up" routerDirection="root" expand="block" size="large" fill="solid" color="warning" class="ion-margin">
<ion-icon size="small" name="person-add"></ion-icon>&nbsp;Create New Account
</ion-button>

**Comment by NikolaPeevski** [comment] 2020-04-13 11:40
It seems something with your styling, I don't get this outline.

**Comment by assman** [comment] 2020-04-13 11:47
Which styling?

Here’s the repo

https://github.com/assman/ticket-ionic

**Comment by liamdebeasi** [comment] 2020-04-13 16:01
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20632.

**Closed by liamdebeasi** 2020-04-13 16:01 UTC
Labels: triage

**Comment by NikolaPeevski** [comment] 2020-04-13 21:11
@assman Repo is private

**Comment by assman** [comment] 2020-04-14 03:24
> @assman Repo is private
> 
> 

Sorry I made it private after Liam pointed me to the related issue. I have set the outline to none in the CSS now. Thank you for your help, really appreciated.
