### ISSUE TITLE
bug: weird behavior in ion-content

### ISSUE THREAD

**Issue by peterlai107** [ionic-team/ionic#21028] opened 2020-04-13 14:23 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
If I put the template ngFor inside ion-content, the UI does not reflect the value of the variable in time, unless the mouse moves on the screen.

if I put the template ngFor outside ion-content, the UI does reflect the value of the variable in time.

This problem only occurs in chrome.

**Expected behavior:**
The UI does reflect the value of the variable in time.

**Related code:**
https://stackblitz.com/edit/ionic-angular-v5-base-6yc9xf

**Other information:**
![chrome](https://user-images.githubusercontent.com/8145135/79127589-c0d5d780-7dd4-11ea-9b92-450f4d7760fe.gif)

**Comment by NikolaPeevski** [comment] 2020-04-13 18:59
Weird.. This is on Version 80.0.3987.163, OSX

![2020-04-13 13 57 34](https://user-images.githubusercontent.com/14194863/79150732-dfb17b00-7d8e-11ea-8a0c-9b4cfac32fb3.gif)

**Comment by liamdebeasi** [comment] 2020-04-13 20:48
Thanks for the issue. I can reproduce this behavior. I am seeing new elements added to the DOM, but Chrome does not seem to be rendering them. I will investigate more and provide an update when I have it.

**Comment by liamdebeasi** [comment] 2020-04-13 21:46
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This appears to be an issue in Chrome with dynamic content in a slot.

I was able to create a reproduction outside of Ionic: https://github.com/liamdebeasi/chrome-ngfor-slot.

As a workaround, wrapping your ngFor div in _another_ div seems to work.

```html
<div>
  <div *ngFor="let item of data">
    <h5>{{ item }}</h5>
  </div>
</div>
```

We will look into filing an issue with the Chromium team. Thanks!

**Closed by liamdebeasi** 2020-04-13 21:46 UTC
Labels: needs: investigation
