### ISSUE TITLE
Generating then trying to use a simple directive isn;t working in Ionic 4

### ISSUE THREAD

**Issue by nikmartin** [ionic-team/ionic#15249] opened 2018-08-20 22:13 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/home/nmartin/npm/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v10.6.0 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : Linux 4.18

```

**Describe the Bug**
custom attribute Directives are not working in Ionic 4

**Steps to Reproduce**
1. run `ionic start myApp tabs --type=angular`
2. run `ionic g directive hilite`
3. edit hilite.directive.ts to look like:
```
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[appHilite]',
})
export class HiliteDirective {
  constructor(el: ElementRef) {
    console.log('hilite!!!');
    el.nativeElement.style.backgroundColor = 'yellow';
  }
}

```
4. edit app/home/homt.page.html to look like:
```
<p appHilite>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs">docs</a>
    will be your guide.</p>
```
5. run the app

**Expected Behavior**
the paragraph to have a yellow background

**Actual Behavior**
Nothing. Interestingly, If I move the directive injection from app.module.ts to home.module.ts, it works, BUT only in home.page.html, not any other page in the app, due to duplicate declarations

**Comment by nikmartin** [comment] 2018-08-20 22:29
Looks like since everything is now lazy loaded, directives also need to have a DirectiveModule generated that injects the directive, and that needs to then be imported everywhere the directive is used, So the actual bug may be that ionic g directive needs to genernate a module for the directive too.

**Comment by lgreenAmp** [comment] 2018-09-25 09:44
I have also seen this - it seems that a custom directive will work if declared on a page which uses it directly or imported from a module on a page directly but NOT when it is declared in app.module.ts or imported as a module into app.module.ts ... :( ...

**Comment by paulstelzer** [comment] 2018-12-03 19:37
This is related to Angular, so I close this here

**Closed by paulstelzer** 2018-12-03 19:37 UTC
Labels: triage

**Comment by nickstucko** [comment] 2018-12-12 20:21
@paulstelzer Sorry if I missed it, but is there an open issue on the Angular github that we can follow instead?

**Comment by paulstelzer** [comment] 2018-12-13 08:04
I don't know if there is an open issue because this use case should work. See Angular docs about this topic: https://angular.io/guide/attribute-directives

If you think there is an issue with Ionic, create a repo to reproduce it
