### ISSUE TITLE
bug: ion-menu crashes if there are two side menus on IOS

### ISSUE THREAD

**Issue by tomaszDziedzic2** [ionic-team/ionic#20283] opened 2020-01-24 10:01 UTC
# Bug Report

**Ionic version:**
[x] **4.11.9**

**Current behavior:**
If there are two side menus on IOS (both webapp and native) after some clicking one of the menus hides right after you try to activate it. Therefore there is no way to use it.
video: https://drive.google.com/file/d/1K8ufJulCBTqxsgWo7FK5_t5FyFuSGc_8/view

**Expected behavior:**
Using two side menus with no problems.

**Steps to reproduce:**
repo: https://github.com/kleeb/ionic-issue-19500
I used repository above, run project and opened it externally (iphone6, ios 12.3.1). Steps to reproduce:

1. Open left side menu with button
2. Select list
3. try to swipe open right side menu
4. menus start to behave strange
Sometimes it takes longer to reproduce it - please try to open items from left menu, then right menu and left menu again. After a few attempts you will surely see the buggy behaviour.

**Related code:**
repo: https://github.com/kleeb/ionic-issue-19500

**Comment by liamdebeasi** [comment] 2020-01-24 14:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18974.

**Closed by liamdebeasi** 2020-01-24 14:18 UTC
Labels: triage
