### ISSUE TITLE
bug: ion-tab halts whole app with white screen

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic#19459] opened 2019-09-26 15:26 UTC
# Bug Report

**Ionic version:**
[x] **4.9.1**

**Current behavior:**
The whole component that contains `<ion-tab>` gets displayed as a white space. When the `<ion-tab>` are commented out the component renders fine.

**Expected behavior:**
Component containing "<ion -tab>" renders no matter what.

**Steps to reproduce:**
https://github.com/bitflower/stencil-tab-bug

Slack chat reference with @manucorporat:
https://stencil-worldwide.slack.com/archives/C9LTCKAN8/p1569499721070200

**Comment by bitflower** [comment] 2019-09-26 15:33
I have added some info and an image to the repo.

**Comment by bitflower** [comment] 2019-09-28 13:11
Repo updated to `ionic@4.10.` and `stencil@1.5.3` - still happening.

**Comment by bitflower** [comment] 2019-10-04 09:56
Not sure if this is related but in `--prod` mode in another case I have this:

If `ion-tab.entry.js` is not present in `dist/esm` does it mean it was ruled out by tree shaking? Or is it inside one of the cryptic named files in this case?
Most of the ion-* files are present and they load fine. The `ion-tabs` however don’t and they are missing in that folder:

![Bildschirmfoto 2019-10-04 um 10 23 33](https://user-images.githubusercontent.com/6666636/66198992-fc614d80-e69d-11e9-998a-0afb14d06770.png)

**Comment by bitflower** [comment] 2019-10-11 20:35
Still present with 
```
    "@ionic/core": "^4.11.0",
    "@stencil/core": "^1.7.1",
```

**Comment by corysmc** [comment] 2019-10-11 23:06
For anyone running into this - the issue was with multiple `ion-content`s on the page. Your ion-tabs should not be a child of `ion-content`.

**Comment by liamdebeasi** [comment] 2020-06-25 20:55
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by liamdebeasi** [comment] 2020-06-25 21:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The approach in the repo is not typically recommended. We recommend following the approach found in our Ionic Stencil Conference App instead: https://github.com/ionic-team/ionic-stencil-conference-app/blob/master/src/components/app-root/app-root.tsx. Thanks!

**Closed by liamdebeasi** 2020-06-25 21:01 UTC
Labels: triage
