### ISSUE TITLE
bug: while running on ios app opens and closes instantly

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#20580] opened 2020-02-21 12:01 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

following the command `$ ionic cordova run ios` when the process and compiling is all finished and then the last text shows:
`native-run ios --app "platforms/ios/build/device/<name of project>.ipa" --device`

the application opens and then closes within a second. I get no errors. Don't know where the problem lies.

**Expected behavior:**

launch the app on the iphone natively

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/Users/me/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.17
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                         : 0.9.0
   native-run                            : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.7.0 (/usr/local/Cellar/node/13.7.0/bin/node)
   npm               : 6.13.6
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-02-21 14:06
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The framework does not manage deploying your app to a device. Also it looks like you already have an open issue for this here: https://github.com/ionic-team/native-run/issues/109.

**Closed by liamdebeasi** 2020-02-21 14:06 UTC
Labels: triage
