### ISSUE TITLE
bug: Choppy list scrolling with Toast component

### ISSUE THREAD

**Issue by Scottd125** [ionic-team/ionic#20508] opened 2020-02-17 09:42 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

During the time when a custom toast message is displayed on the screen, attempting to scroll through a list of items becomes choppy and not very user-friendly.

Example of scrolling without a toast message being displayed: https://imgur.com/a/tGe2zJx
Example of scrolling with a toast message being displayed: https://imgur.com/a/j1N3LCk

**Expected behavior:**

The list's scroll performance should not be impacted when a toast message is being displayed to the user

**Steps to reproduce:**

1.) Create a long list that features content such as images and text
2.) Scroll through the list while a toast message is being presented

**Related code:**

N/A

**Other information:**

**Ionic info:**

```Ionic:

   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.9.0)
   native-run  : 0.2.9 (update available: 0.3.0)

System:

   NodeJS : v10.16.3
   npm    : 6.13.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-02-17 14:23
Thanks for the issue. What device are you testing this on?

**Comment by Scottd125** [comment] 2020-02-17 14:24
Hi Liam,

I'm testing this on a Samsung S7 Edge with Android 8.0

**Comment by liamdebeasi** [comment] 2020-02-17 18:11
Thanks for the follow up. Are you able to provide a repo with the code required to reproduce this issue?

**Comment by Scottd125** [comment] 2020-02-17 18:29
Hi,

Sorry but the project i'm working on is closed sourced. I can attempt to reproduce this issue on a StackBlitz project to attempt to investigate further. I'll get round to adding that here when I get the time

**Comment by Scottd125** [comment] 2020-02-18 13:23
After creating a StackBlitz project with a similar layout and populating it with over 100+ items and a constant toast message. I was unable to re-create the same issue I am facing with my app. 

However, I noticed that CPU usage on the device spikes to 100% while I am scrolling through the list and drops right back down to ~1% - ~3% while sitting idle. The CPU spikes to 100% while scrolling is causing the choppy list scrolling. 

I've attempted to use both virtual scrolling (https://github.com/rintoj/ngx-virtual-scroller) and lazy image loading (https://github.com/tjoskar/ng-lazyload-image) to reduce this spiking but to no avail. 

I've also stripped away all the template logic (*ngIf etc.) and just kept a single *ngFor loop over a single static array of 200 items, each containing a single title property and rendered that within my template but still facing the same issue regardless of stripping away all of the content.

**Comment by liamdebeasi** [comment] 2020-02-18 14:21
Thanks for the follow up. Unfortunately a reproduction is going to be the best way for us to be able to resolve the issue. Are you able to reproduce the CPU spike?

**Comment by Scottd125** [comment] 2020-02-18 15:20
I've made a fresh Ionic 5 side menu project and made a bare-bones implementation and was able to reproduce the CPU spike issue. (https://github.com/Scottd125/ScrollingToastIssue) 

I ran the project on my device with debugging and live reloading enabled and within Chrome DevTools under Performance monitor, there are some instances where the CPU usage spikes up to 100% when scrolling (With and without the toast message being displayed)

It doesn't seem to be as impactful in comparison to the gif example I gave however it does seem quite noticeable and I could only imagine it becomes more choppy-er with a larger scale project with more logic happening behind the scenes.

Just want to also say thank you for the quick replies :)

**Comment by liamdebeasi** [comment] 2020-02-21 19:59
Thanks for the follow up. I am unable to reproduce the CPU spikes on the app you have provided. When running in Chrome Dev Tools, I do see an increase in rendering but that is most likely due to the browser trying to render all of the `img` elements. The FPS appears to stay around a consistent 60fps too.

Are there any particular steps I need to take besides scrolling up and down in the app?

**Comment by Scottd125** [comment] 2020-02-24 07:55
Hi Liam,

There shouldn't be any particular steps that need to be taken to reproduce this issue besides scrolling.

I've taken a list of the steps I took to be able to consistently reproduce this issue

1.) Run ionic cordova run android --debug with the device plugged in to build the example app (In my case the Samsung S7 Edge)

2.) Once built and running on the device, open up Chrome and Chrome tools and select the 'Remote devices' tab and inspect the device

3.) Open up 'Performance monitor' in the new window which is inspecting the device

4.) As you begin to scroll (Either in short or long bursts) the CPU usage will spike up to a very high percentage and frequently reach 100% (This can also be achieved with holding down on the screen and scrolling very slowly) but the scrolling will still remain very smooth

5.) Go to the top of the app and press on the display toast message

6.) As you begin to scroll with the toast message on the screen, the same amount of CPU usage from before will apply but there will be visual choppy-ness while scrolling compared to not having a toast message displayed on-screen while scrolling

An example picture of it consistently reaching 100% CPU usage: ![IonicIssue1](https://user-images.githubusercontent.com/31902527/75135649-244b5f00-56da-11ea-99f5-ff6acf1b822a.png)

Gif example of device scrolling alongside Performance Monitor without a toast message being displayed: https://imgur.com/a/h0FWyK6

Gif example of device scrolling alongside Performance Monitor with a toast message being displayed: https://imgur.com/a/pp1fKVf

I've included additional gifs to try and demonstrate of how it looks (I've used SideSync connected via USB to mirror my phone's screen but the same CPU usage spikes and choppy-ness to apply when it's just connected via USB only without SideSync)

The only other factor I can think of that will have an impact is what device you're using to attempt to reproduce this issue.

**Comment by liamdebeasi** [comment] 2020-03-03 18:31
Thanks for the follow up. I am going to close this as this does not appear to be a bug in Ionic Framework.

Android devices typically have lower powered CPUs than iPhones, so performance is generally a bit worse. Additionally, your app is trying to render ~3,000 DOM nodes all at once (including 200 images) this is likely going to cause performance to drop. I was able to reproduce this behavior and saw that the browser was spending a lot of time on its "Update Layer Tree" tasks (between 15-30ms per frame).

I think a better approach would be to use lazy loaded images, infinite/paginated scrolling, or even virtual scrolling. From what it looks like, the device just isn't able to render ~3,000 DOM nodes all at once. 

Hope this clarifies things a bit. Thanks!

**Closed by liamdebeasi** 2020-03-03 18:31 UTC
Labels: triage
