### ISSUE TITLE
Remove unused css during build based on platform and\or mode

### ISSUE THREAD

**Issue by Tankatronic** [ionic-team/ionic#12671] opened 2017-08-15 16:24 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Currently when ionic builds, all css from all components and platforms are built and put into the main.css file. We have experienced some major slowdowns in our apps on mobile because of this, which we do not experience in an ionic-less angualr 2/cordova app. 

While debugging the slowdowns our app experienced on iPad, i noticed the biggest loss in performance was due to styles being recalculated every time the user tapped on an element. The timeline view in Safari showed that styles were being invalidated prior to the touch start, touch end, and click events which caused an expensive recalculate styles to follow each time. 

I first went through and I manually removed all ios and wp styles from all components and css files in the ionic-angular npm package. I did not see any real gain in performance here, but it did decrease the overall size of the final css file which is always a good thing. However after removing all pseudo class selectors (namely hover) that were disabled on mobile anyway by media queries, styles were no longer being invalidated during the touch start or touch end events and my app saw a huge increase in performance.

In my case, I set the mode on my ionic app to md across all platforms. I do not know if it would be feasible to clean css based on both app modes defined and the platform being specified in the build, but at the very least removing the hover pseudo class selectors that are set to be disabled on touch devices anyway would benefit performance greatly.

**Comment by AmitMY** [comment] 2017-08-15 17:09
Coming in Ionic v4!

**Comment by Tankatronic** [comment] 2017-08-15 17:47
@AmitMY Does that include removing the :hover:not(.disable-hover) when building for mobile platforms?

**Comment by AmitMY** [comment] 2017-08-15 17:54
That is interesting.. I never heard of it making problems before. I didn't focus on that part, only on the amount of unused selectors, my bad.

No, what I meant was that when loading Ionic v4, only the components being used will load their core styles, for only the platform being used, and only for the color being used, and changing the color/platform should load the correct code needed for it.

On the hover (desktop support) / recalculating styles for each tap, @brandyscarney may know more.

**Comment by Tankatronic** [comment] 2017-08-15 18:14
Ok thanks! To paint a better picture of what I am working with, here's a brief description of my apps structure.

My app is a split-view app intended to be used on desktop (in chrome) and iPad. I have a menu (intended to be always open) on one side with a list of open orders. Each order is an `ion-list`, with a few `ion-row` and nested `divs` and `labels`. At this point in the app everything is read only, so all my bindings are string interpolations. Each order has a click event which triggers an animation that brings a row of buttons into view.

During development, I primarily was working on desktop, and everything was working swimmingly. When I switched to the iPad, I would notice that tapping on each order would experience a ever so slight delay. This was barely noticeable at low order numbers, but after hitting 30, 50, or more the effect became so much more apparent (~300-500ms delay) and it was unusable on iPad past 60. Virtual Scroll presented its own issues; It did not work right with my custom animation since it changed the height of the selected div and it wouldn't shift elements down. I tried to use ItemSliding but that also did not work (I opened another issue regarding that).

I will see if I can get some sort of demo up for this issue as well as screenshots of the timeline in safari's dev tools

**Comment by AmitMY** [comment] 2017-08-15 18:18
A demo will help.
I don't recommend going out-of-standard with virtual scroll, as although some fixes for it are coming, it is still hard to use for dynamic dimensions.

**Comment by Tankatronic** [comment] 2017-08-15 19:47
Plunkr is not very smooth with animations on iPad so i do not think it will be a good demo. I'd have to post a github repo so that will take a bit longer.

**Comment by Tankatronic** [comment] 2017-08-15 21:49
I was actually mistaken on what was causing the issue. I was attempting to reproduce it but was not able to by removing just the `:hover:not` classes. But I was able to reproduce it when I removed the following from the main.css file prior to running on iPad:

`:hover,
:active {
    outline: none;
}`

Removing that increased the performance on iPad dramatically.

**Comment by jgw96** [comment] 2017-08-16 14:48
@Tankatronic would you mind posting a repo we can use to reproduce this issue?

**Comment by jgw96** [comment] 2017-08-31 18:50
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-08-31 18:50 UTC
Labels: needs info, platform:ios, v2
