### ISSUE TITLE
4.2.1 Active tab color in iOS issue

### ISSUE THREAD

**Issue by scarface382** [ionic-team/ionic#16057] opened 2018-10-24 05:17 UTC
_Originally posted by @ionic-issue-bot in https://github.com/ionic-team/ionic/issues/14758#issuecomment-425650599_

**Comment by brandyscarney** [comment] 2018-10-26 14:11
Thanks for the issue. There's not enough information here for me to give you a solution, but I imagine you're running into one of the following problems:
- Not being able to set the color attribute on `ion-tabs` in latest (`4.0.0-beta.13`), duplicate of https://github.com/ionic-team/ionic/issues/15942 
  - Fixed by adding an `ion-tabbar` (which will become `ion-tab-bar` in `4.0.0-beta.14`). 
  - See https://github.com/ionic-team/ionic/pull/16048 and https://github.com/ionic-team/ionic/blob/master/core/src/components/tab-bar/readme.md
- Not being able to change the active color of the text using CSS variables, duplicate of https://github.com/ionic-team/ionic/issues/15559
  - Will be fixed in `4.0.0-beta.14` by https://github.com/ionic-team/ionic/pull/16003

I am going to close this issue since it is missing the issue template and there is not enough information for us to investigate, but if you are not running into one of the above issues please open a new issue with as much information as possible for us to reproduce the problem. Thanks!

**Closed by brandyscarney** 2018-10-26 14:11 UTC
Labels: triage
