### ISSUE TITLE
Ionic VirtualScroll Not Respecting Pipe

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [ionic-team/ionic#13226] opened 2017-10-24 14:57 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When using VirtualScroll with a sort pipe the list initially renders respecting the pipe. However, if a variable argument of the pipe is updated, the list does not refresh.

**Expected behavior:**
VirtualScroll reloads the list when a pipe's argument changes (search for instance).

In this Plnkr, you should be able to click anywhere on the list and have the list sorted from A-Z instead of Z-A but the list does not refresh when the pipe variable changes:
http://plnkr.co/edit/CSz70r?p=preview

**Comment by kensodemann** [comment] 2017-10-25 10:34
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #12307. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-10-25 10:34 UTC
