### ISSUE TITLE
can't open links with inappbrowser with lazy loading

### ISSUE THREAD

**Issue by palidanx** [ionic-team/ionic#12290] opened 2017-07-07 23:44 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I use lazy loading and invoke In App Browser to launch, I get the error below
```
Runtime Error
Uncaught (in promise): nav controller was destroyed
Stack
Error: Uncaught (in promise): nav controller was destroyed
    at c (http://192.168.0.21:8100/build/polyfills.js:3:12642)
    at Object.reject (http://192.168.0.21:8100/build/polyfills.js:3:11998)
    at Tab.NavControllerBase._fireError (http://192.168.0.21:8100/build/main.js:45794:16)
    at Tab.NavControllerBase._failed (http://192.168.0.21:8100/build/main.js:45773:18)
    at http://192.168.0.21:8100/build/main.js:45837:59
    at t.invoke (http://192.168.0.21:8100/build/polyfills.js:3:8488)
    at Object.onInvoke (http://192.168.0.21:8100/build/main.js:4485:37)
    at t.invoke (http://192.168.0.21:8100/build/polyfills.js:3:8428)
    at r.run (http://192.168.0.21:8100/build/polyfills.js:3:3686)
    at http://192.168.0.21:8100/build/polyfills.js:3:13183
```
https://ionicframework.com/docs/native/in-app-browser/

I removed lazy loading from the entire project, and calling in app browser works again (see related code)

**Expected behavior:**
Without lazy loading, browser links should open

**Steps to reproduce:**
Run the related code where lazy loading is used in the project.

**Related code:**

```
This code is run which doesn't work 
  openLink(url) {
    const browser = this.iab.create(url, "_system");
    browser.show();
  } 
 ```

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.11
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.11.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4 

```

**Comment by alexbainbridge** [comment] 2017-07-09 18:40
FYI this code doesn't work on Android on device (But does work on iOS)

```
const browser = this.iab.create(url, "_system");
    browser.show();
```

I have found that just like this, no const variable, works....... 

`this.iab.create(url, "_system");`

No idea if this addresses the lazy loading issue though..... but give it a go?

**Comment by jgw96** [comment] 2017-07-10 15:03
Hello all! Thanks for using Ionic! Would you mind posting a minimal repo we can use to reproduce this issue?

**Comment by palidanx** [comment] 2017-07-12 20:46
@alexbainbridge hm, that did fix a problem I just discovered on android.  I'll try to see on lazy loading if this.iab.create woudl fix the problem.

**Comment by jgw96** [comment] 2017-07-18 14:40
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-18 14:40 UTC
Labels: needs info, v2
