### ISSUE TITLE
bug: double tap on the IonBackButton navigate to screens back in Ionic 4

### ISSUE THREAD

**Issue by matis-dk** [ionic-team/ionic#20934] opened 2020-04-01 09:32 UTC
# Bug Report
If you double tap on the IonBackButton, it navigate you two screens back.  

**Ionic version:**
[x] **4.x**
Ionic CLI 6.4.0

**Current behavior:**

When clicking on the IonBackButton, it register each click event as separate. This is navigating the user multiple screens back.  This is especially an issue, if you second screen was on another tab.

Zip file with a mp4 video showing the bug:
[ionic-navigation-bug.zip](https://github.com/ionic-team/ionic/files/4414152/ionic-navigation-bug.zip)

**Related code:**
Repo with the bug:
https://github.com/matis-dk/ionic-react-router-bug

**Comment by liamdebeasi** [comment] 2020-04-01 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18455.

**Closed by liamdebeasi** 2020-04-01 13:18 UTC
Labels: triage
