### ISSUE TITLE
Document title not being updated when navigating via popover

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic#9398] opened 2016-11-28 20:00 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The document title is not updated when navigating back from a page that has been opened via a popover.

**Expected behavior:**
The document title shows the same value as in the navbar.

**Steps to reproduce:**
1. Open the conference app in a browser, e.g. from here http://pwa.ionic.io/ionic-conference-app/www/ 
2. Go to About
3. Open Popover
4. Go to Support
5. Click back button
6. Now you're back on the About page, but the document title (in the browser tab) is still Support

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v5.12.0
Xcode version: Not installed
```

**Comment by cogoo** [comment] 2016-11-29 10:25
I can reproduce this issue with steps above

**Comment by pwespi** [comment] 2016-11-29 10:42
I'm not sure if I was clear enough: I'm talking about the document title shown in the browser tab, not the ion-title in the navbar, see screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/24232962/20706669/ac524f7c-b628-11e6-967a-8db5b2131cf4.png)

**Comment by mebibou** [comment] 2017-10-05 11:37
This is a general issue about navigating back from a page to another, where the title remains the same and does not get updated with the new page. So if you navigate like `list > view > edit`, then navigate back, the title remains the one from the edit page.

Still present in ionic `3.7.1`

**Comment by kensodemann** [comment] 2018-01-04 00:49
I am going to close this since there will not be another v3 release and this code should be fixed with the next major release of Ionic and Ionic Angular. If this is still an issue after that release is out please let us know.

**Closed by kensodemann** 2018-01-04 00:49 UTC
Labels: v2
