### ISSUE TITLE
bug: ion-buttons makes the page to reload

### ISSUE THREAD

**Issue by blasco** [ionic-team/ionic#21008] opened 2020-04-10 16:00 UTC
# Bug Report

**Ionic version:**

[x]     "@ionic/angular": "^5.0.0",

**Current behavior:**

When I add a <ion-button> element the header seems to reload which makes blink whatever I put in the toolbar.

So if I've have the following:
```
<ion-buttons slot="end">
  <ion-menu-button></ion-menu-button>
</ion-buttons>
```

The following happens:

![bugionic1](https://user-images.githubusercontent.com/3214400/79002008-d8505e80-7b4f-11ea-83c7-98e538e6da83.gif)

but If I comment those lines, the reloading effect is gone:

![bugionic2](https://user-images.githubusercontent.com/3214400/79002043-ebfbc500-7b4f-11ea-862a-e33768ab1701.gif)

I've tried with an empty project with the sidenav template and I can see the menu button blinking, but the effect is not as extreme as with my app where I have more stuff on the header. What could be causing this issue?

**Comment by liamdebeasi** [comment] 2020-04-10 16:16
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by blasco** [comment] 2020-04-12 07:31
Hi, I've prepared a repo where the issue is present:

https://github.com/blasco/ionic-top-menu-bug

You'll see that if you comment out the following lines in 'app/components/top-toolbar/desktop-top-toolbar':

```
<ion-buttons slot="end">
  <ion-menu-button></ion-menu-button>
</ion-buttons>
``` 

The reloading issue disappears. Hope that helps to identify the problem, let me know if I can help any further.

**Comment by blasco** [comment] 2020-04-12 07:34
If someone else is encountering this issue, a simple walk-around is not to use ion-buttons and to do the menu toggling programmatically with:
```
    this.menuCtrl.open();
```

**Comment by liamdebeasi** [comment] 2020-04-13 17:49
Thanks for the issue. Are you able to reproduce this in an Ionic sidemenu starter? I can see the issue in your application, but I am unable to reproduce the issue when using one of our starter apps.

**Comment by blasco** [comment] 2020-04-13 19:46
The app I've provided is minimal, there is just an ion-toolbar with a div inside with little styling. There is no sidemenu

**Comment by liamdebeasi** [comment] 2020-04-13 20:45
Thanks for the follow up. I am going to close this as this does not appear to be a bug in Ionic Framework. I attempted to reproduce this issue in a fresh Ionic sidemenu starter application (using the same nested component structure your application has) and was unable to reproduce the issue. This typically indicates the issue is in the application's code. I recommend reviewing your approach to your header's styling and markup.

Additionally, we do not recommend using ion-header/ion-toolbar in nested components as it can interfere with the `slot` functionality. In your application, the `ion-buttons` has `slot="end"` but does not appear at the end of the content.

If you find additional information that indicates this is a bug in Ionic Framework, feel free to open a new issue with a code reproduction. Thanks!

**Closed by liamdebeasi** 2020-04-13 20:45 UTC
Labels: triage
