### ISSUE TITLE
bug: Blank screen when fast clicking on ion-back-button

### ISSUE THREAD

**Issue by SerhiDi** [ionic-team/ionic#18104] opened 2019-04-23 12:53 UTC
# Bug Report

**Ionic version:**

[x] **4.3.0**

**Steps to reproduce:**
Try fast click on `ion-back-button` when you have some pages in route history

**Related code:**

HTML
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>
      HEADER 2
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  CONTENT 2
</ion-content>

<ion-footer>
  <ion-button
    (click)="openTest3()">
    <ion-label>OPEN 3</ion-label>
  </ion-button>
</ion-footer>
```

TS
```
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
})
export class Test2Component {

  constructor(private router: Router) {
  }

  openTest3() {
    this.router.navigateByUrl(`index/test3`);
  }

}
```

ROUTES
```
export const testRoutes: Routes = [
  {
    path: 'test',
    component: TestComponent,
  },
  {
    path: 'test2',
    component: Test2Component,
  },
  {
    path: 'test3',
    component: Test3Component,
  },
  {
    path: 'test4',
    component: Test4Component,
  }
];
```
Video with this bug:
https://gyazo.com/fef073d8480218bc79180e7216c34e11

Page in stack invisible:
![](https://gyazo.com/b740b9d1312b4f9b727e42cca139bec4.png)

![](https://i.gyazo.com/cd189464b43ea95b25b31c56351346e1.png)

**Comment by dansiemens** [comment] 2019-04-30 20:14
This is shockingly easy to reproduce. I found that clicking an `ion-item` with a `routerLink` and then clicking the back button twice would consistently produce a blank page.

**Comment by brandyscarney** [comment] 2019-06-12 16:12
Thanks for the issue! Closing as a duplicate of #18455. I'm not able to reproduce this and I've commented on that issue asking for more information. If anyone could please give us more details into how this is reproduced that would be helpful. Thanks.

**Closed by brandyscarney** 2019-06-12 16:12 UTC
Labels: triage
