### ISSUE TITLE
 Please provide a way to set default value to ion-datetime picker

### ISSUE THREAD

**Issue by kceiw** [ionic-team/ionic#12055] opened 2017-06-15 19:56 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ x ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I click the component ion-datetime, it opens the picker with the value set to the first day of the current year if max is not set. or the first day of the year of the value set to max.

**Expected behavior:**

Please provide a way to set the default value of the picker. In my case, I need to set a max value to ion-datetime and want to give a day as the start point for the user to pick a date. But with the current framework, that's impossible. Actually I have two ion-datetime for start date and end date. So when the user picks a start time, I want the default value for the picker for the end date to be the start date.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by astec** [comment] 2017-06-16 10:00
Duplicate of https://github.com/ionic-team/ionic/issues/9846?

**Comment by kceiw** [comment] 2017-06-17 13:49
Yes. It's partially dup to #9846 also describes the bug in #10710

**Closed** 2017-06-17 13:50 UTC
