### ISSUE TITLE
bug: Fixed element messes up layout when changing orientation

### ISSUE THREAD

**Issue by qbikaris** [ionic-team/ionic#19317] opened 2019-09-10 11:53 UTC
# Bug Report

**Ionic version:**

[x] 4.7.1

**Current behavior:**
When a fixed element in present on a page and you change the phone orientation, the layout shown is the one in the other orientation. So: landscape shows portrait and portrait shows landscape. 

**Expected behavior:**
Show landscape when on landscape and show portrait when on portrait.

**Steps to reproduce:**
- create a new project: ionic start fixedPosTest tabs --capacitor
- on tab3, I added a div to the ion content tag with class="floating-button" and some random text
- in global.scss I added:
`
.floating-button{
    position: fixed;
    bottom: 20px;
    right: 20px;
    background: red;
}`
- run project
- in chrome, show the mobile layout and switch orientation

**Related code:**

see above

**Other information:**

When you remove the fixed positioning or force the css to reload, the layout will show correct in the view you are in.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\sc\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.2.0
   @capacitor/core : 1.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-09-10 12:54
Thanks for the issue. This appears to be caused by https://github.com/ionic-team/ionic/issues/19065, so I am going to close this issue in favor of that one.

**Closed by liamdebeasi** 2019-09-10 12:54 UTC
Labels: triage
