### ISSUE TITLE
bug: ionic build error with google services and play services

### ISSUE THREAD

**Issue by Sevensnake** [ionic-team/ionic#19346] opened 2019-09-15 20:10 UTC
Every time I add google-plus to my application this error happens. Not sure how to get rid of it currently. any solutions. We came to far to have small problems like these. Kind of new to the android build.

Task :app:processDebugGoogleServices FAILED Found play-services-identity:11.8.0,

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

> Task :app:processDebugGoogleServices FAILED
Found play-services-identity:11.8.0, but version 11.6.2 is needed for the google-services plugin.
Found play-services-auth:11.8.0, but version 11.6.2 is needed for the google-services plugin.
20 actionable tasks: 20 executed
C:\platforms\android\gradlew: Command failed with exit code 1 Error output:
Note: C:\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.
`

**Comment by liamdebeasi** [comment] 2019-09-16 13:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic Framework does not manage the Cordova build process.

For further help with this issue I recommend you post on our [forums](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com). Thanks!

**Closed by liamdebeasi** 2019-09-16 13:12 UTC
Labels: triage
