### ISSUE TITLE
Ionic life cycle not working in tab inside tab

### ISSUE THREAD

**Issue by rajeevriitm** [ionic-team/ionic#9624] opened 2016-12-13 23:54 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
App have a tab inside another tab. When I move between the parent tabs, ```ionViewDidEnter``` life cycle of child tab's root page is not running. 

**Expected behavior:**
If the parent tab ```FeedPage```, which has two tabs ```UserHuntPage```(root page) and ```HomePage``, is clicked then ```ionViewDidEnter``` on ```UserHuntPage``` should run.

**Steps to reproduce:**

 The parent tab page is
```
export class TabsPage {
  tab2Root: any = DomePage;
  tab3Root: any = FeedPage;
}
```
And inside ```FeedPage``` I have another tab
```
export class FeedPage {
  tab1Root: any = UserHuntsPage;
  tab2Root: any = HomePage;
    ionViewDidEnter(){
    console.log('feed run');
  }
}
```
feed.html
```
<ion-tabs selectedIndex="0" tabsPlacement="top"  >
  <ion-tab [root]="tab1Root" tabTitle="hunts" tabIcon="bonfire"  ></ion-tab>
  <ion-tab [root]="tab2Root" tabTitle="home" tabIcon="book"></ion-tab>
</ion-tabs>
```
UserHuntsPage
```
export class UserHuntsPage {
  ionViewDidEnter(){
    console.log('UserHunts run');
  }
}
```
Here ```UserHuntsPage``` is the root page of  ```FeedPage``` tabs. So a click on feed tab brings ```UserHuntsPage``` into the view and it should run its ```ionViewDidEnter```. But its not running. In the console _feed run_ is printed user _hunts run_ is not printed.

**Other information:**
http://stackoverflow.com/questions/41091621/ionic-life-cycle-ionviewdidenter-not-working

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

```

**Comment by rajeevriitm** [comment] 2016-12-14 12:37
Is there any quick fix I can use to make it work now?

**Comment by jgw96** [comment] 2016-12-14 23:04
Hello @rajeevriitm , hmm I am not sure of a workaround at the moment. Do any of the lifecycle events (ionViewDidLoad for example) fire in this case?

**Comment by jgw96** [comment] 2016-12-14 23:05
As one workaround you could try using the default [Angular lifecycle events](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html).

**Comment by rajeevriitm** [comment] 2016-12-14 23:40
Angular lifecycle didnt help either. It works on the first click on parent tab. Subsequent clicks only trigger the tabs life cycle.

**Comment by kensodemann** [comment] 2017-10-19 11:20
I believe issue #13185 is a duplicate of this and has a sample application to demonstrate the issue (just a note for when we tackle this).

**Comment by paulstelzer** [comment] 2018-12-13 18:03
This should work now with beta.18 :) There are just some breaking changes!

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#400-beta18-2018-12-13

**Closed by paulstelzer** 2018-12-13 18:03 UTC
Labels: type: feature request
