### ISSUE TITLE
bug: forceOverscroll not working on iOS Ionic 4

### ISSUE THREAD

**Issue by samuelfaj** [ionic-team/ionic#19105] opened 2019-08-14 21:39 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
There's no way to prevent ionic 4 from boucing on iOS. 
As you may see:
![Gravação de Tela 2019-08-14 às 18 34 58](https://user-images.githubusercontent.com/12994414/63058389-f8495880-bec2-11e9-85d2-3782c91d1ac0.gif)

**Related code:**
config.xml
```
<preference name="DisallowOverscroll" value="true" />
```
```
<ion-content forceOverscroll="false">
		...
</ion-content>
``` 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (/Users/samuelfajreldines/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 11 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.5

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.9.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```

**Comment by liamdebeasi** [comment] 2019-08-15 13:05
Thanks for the issue. Which version of iOS are you testing on?

**Comment by liamdebeasi** [comment] 2019-08-15 13:08
Thanks for the issue. As per the docs, setting `forceOverscroll=false` does nothing if your content exceeds the bounds of the screen. `forceOverscroll` is only needed when you have content that is not scrollable that you do not want to "bounce". Please see the docs for more info: https://ionicframework.com/docs/api/content#properties

Does this resolve your issue?

**Comment by Juanperezc** [comment] 2019-08-15 18:21
Same bug here

**Comment by samuelfaj** [comment] 2019-08-16 03:09
> Thanks for the issue. As per the docs, setting `forceOverscroll=false` does nothing if your content exceeds the bounds of the screen. `forceOverscroll` is only needed when you have content that is not scrollable that you do not want to "bounce". Please see the docs for more info: https://ionicframework.com/docs/api/content#properties
> 
> Does this resolve your issue?

I want to scroll but without boucing.
In print, it wouldn't be possible to scroll down, do you understand?

**Comment by liamdebeasi** [comment] 2019-08-16 18:37
Thanks for the follow up. We do not currently provide an API to do that.

If you would like to disable it yourself, you would likely need to set `-webkit-overflow-scrolling: auto` on the `.inner-scroll` div inside of `ion-content`.

Please note that as of iOS 13 it will no longer be able to disable this momentum scrolling, so I do not recommend this approach.

I am going to close this as this is not a bug in Ionic. Thanks!

**Closed by liamdebeasi** 2019-08-16 18:37 UTC
Labels: triage
