### ISSUE TITLE
bug: ionModalDidPresent event not firing 

### ISSUE THREAD

**Issue by gnesher** [ionic-team/ionic#20107] opened 2019-12-19 11:36 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ion-modal exposes an event called ionModalDidPresent which does not fire. Looking at the code the event seems to shadow ionViewDidEnter (which does fire).

**Expected behavior:**
The event ionModalDidPresent  should be fired when the after the modal is opened

**Steps to reproduce:**
Follow example in https://ionicframework.com/docs/api/modal to create a simple modal and add an ionViewDidEnter  event 

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\gnesher\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.2.2
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2019-12-19 14:17
Thanks for the issue. Can you try this again on the latest version of Ionic Framework?

**Comment by gnesher** [comment] 2019-12-21 11:28
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.2.2
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.0.0

Still happening, didionViewDidEnter is firing, ionModalDidPresent does not

**Comment by liamdebeasi** [comment] 2020-01-07 14:21
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

**Comment by gnesher** [comment] 2020-01-08 09:35
@liamdebeasi  sure - https://github.com/gnesher/ionic-modal-bug-demo none of the modal specific events are firing, but ionViewDidEnter does. 

It seems that the modal specific events are just aliases of the regular events (which do fire) so something there probably fails to connect, I'm just not familiar enough with the Ionic codebase to fix this :/

**Comment by liamdebeasi** [comment] 2020-03-02 17:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. `ionModalDidPresent` and the other modal events are emitted as custom events on the element, not as Angular lifecycle methods.

It is recommended developers use the standard lifecycle methods that Ionic provides: https://ionicframework.com/docs/angular/lifecycle

The events you see in the documentation are events you can listen to via `addEventListener`: https://ionicframework.com/docs/api/modal#events

**Closed by liamdebeasi** 2020-03-02 17:51 UTC
Labels: triage
