### ISSUE TITLE
bug: IonRouterOutlet and IonTabBar don't work with reach router

### ISSUE THREAD

**Issue by wis** [ionic-team/ionic#20525] opened 2020-02-18 04:39 UTC
# Bug Report

**Ionic version:** 5.0.0

**Current behavior:** Ionic doesn't work with Reach router

**Expected behavior:** Ionic should work with the more popular reach router

**Steps to reproduce:**
put reach router <RouteComponent > components in IonRouterOutlet I get runtime errors.

**Related code:**

``` jsx
import React from "react"
import { render } from "react-dom"
import { Router, Link } from "@reach/router"

const TabRoot: React.FC<IAppProps> = props => {
  return (
    <IonPage>
      <IonTabs>
        <IonRouterOutlet>
           { /*<Router>*/ }
            <Home path="/" />
            <Dash path="dashboard" />
         { /*  </Router>*/ }
          { /* <Route path="/:tab(tab1)" component={Tab1} exact={true} /> */ }
          { /* <Route path="/:tab(tab2)" component={Tab2} /> */ }
        </IonRouterOutlet>
        <IonTabBar slot="bottom">
          <IonTabButton tab="tab1" href="/tab1">
            <IonIcon name="flash" />
            <IonLabel>Tab One</IonLabel>
          </IonTabButton>
          <IonTabButton tab="tab2" href="/tab2">
            <IonIcon name="apps" />
            <IonLabel>Tab Two</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    </IonPage>
  );
};

```

**Other information:**

the stack trace ends here
https://github.com/ionic-team/ionic/blob/45d03baf981d0e10eb1fe689908532adef2ba31d/packages/react/src/components/navigation/IonTabBar.tsx#L56

**Ionic info:**
```
Ionic:
   Ionic CLI : 6.1.0
Utility:
   cordova-res : 0.9.0
   native-run  : 0.3.0
System:
   NodeJS : v13.8.0
   npm    : 6.13.6
   OS     : Linux 5.5
```

**Comment by elylucas** [comment] 2020-02-18 15:48
@ionic/react-router uses React Router, not Reach Router. In order for Ionic React to work with other routers, a wrapper library will need to be implemented for it like was done with @ionic/react-router. 

While it should be possible to make a library around other routers, it is not currently on our roadmap to do so.

Going to close this issue as it's not a bug in the framework.

**Closed by elylucas** 2020-02-18 15:48 UTC
Labels: triage
