### ISSUE TITLE
Ionic serve on cancel is not killing the node process in the background

### ISSUE THREAD

**Issue by IsaacSomething** [ionic-team/ionic#14983] opened 2018-08-02 07:40 UTC
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2 (C:\Users\<username>\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
Canceling after an `ionic serve` does not kill the process it was running on, and leads to massive memory leaking.

**Steps to Reproduce**
1. `ionic serve` run the app and then `ctrl + c` to cancel 
2. Open task manager ( on windows ) and see the Node.js Server-side still running
3. Repeat step one until computer memory is buggered :)

**Related Code**
No related code

**Expected Behavior**
`Ctrl + c` should kill the node process completely 

**Additional Context**
You can also see this, when running `ionic serve` every subseqent serve with be spun up and the next port number
```
ionic-app-scripts serve --address 0.0.0.0 --port 8102 --livereload-port 35735 --dev-logger-port 53709 --nobrowser
```
 Where the port number should be `8000`

**Comment by dwieeb** [comment] 2018-08-02 14:11
Thanks for the issue report!

Duplicate of https://github.com/ionic-team/ionic-cli/issues/3401

**Closed by dwieeb** 2018-08-02 14:11 UTC
Labels: triage

**Comment by baron554** [comment] 2018-08-09 18:47
Experiencing this as well. Is there a fix for this?
