### ISSUE TITLE
ionic geo location is not working in android mobile

### ISSUE THREAD

**Issue by lovepreetsingh03** [ionic-team/ionic#13111] opened 2017-10-11 09:38 UTC
I get location in my mobile ( yuforia 5010A ) but When I install app in my friend mobile then its not working.
i didn't understand why its not working in other mobile.
below is my code .

 this.loact.request(this.loact.REQUEST_PRIORITY_HIGH_ACCURACY).then(() =>{
           
             this.geolocation.getCurrentPosition(enableOption).then((position) => {
               this.geoCuntory(position);
                }).catch((error) => {
                  alert(error);
                 });

          }, (error)=>{
             alert(error);
            }

Please help me out to get solution

**Comment by kensodemann** [comment] 2017-10-11 10:30
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems to be either a support question or a potential issue with a specific Cordova plugin, I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

If the issue is with the plugin itself, please enter an issue in the plugin's repo.

Thanks for using Ionic!

**Closed by kensodemann** 2017-10-11 10:30 UTC

**Comment by lovepreetsingh03** [comment] 2017-10-11 11:05
Thank You sir for reply me .
