### ISSUE TITLE
bug: Clickable Ion list item inconsistency

### ISSUE THREAD

**Issue by NikolaPeevski** [ionic-team/ionic#20976] opened 2020-04-06 04:10 UTC
# Bug Report

**Ionic version:**

[x] **5.x Ionic Angular**

**Current behavior:**
If you have menu with a list of clickable items the only clickable components inside of these items are buttons, even if you add a click event to something else inside it gets stripped down. The same list outside of an ion menu works fine with everything clickable. [Also the 'button' attribute ](https://ionicframework.com/docs/api/item#clickable-items)said to fix this doesn't make the ion item clickable it just adds a detail at the end. I tried adding an href="#" as well which makes the app navigate in a weird manner. Usually href with a pound (#) does not navigate anyway in the angular router. 

Gif of the issue:

https://gfycat.com/ifr/RewardingExemplaryGecko 

The code in both views is the same.

**Expected behavior:**
Ion items with a (click) property to be wholly clickable.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.19.0 (/usr/local/Cellar/node@10/10.19.0/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

**Comment by NikolaPeevski** [comment] 2020-04-06 05:50
Just an update, I found a workaround by creating a button, styling it to look like the list item and having it slot start, then creating another empty blank button with width 100% to fill the space between the actual button and the arrow. Removing the ripple effects and making the background color transparent and removing some margin left. Now it looks as the desired effect, but I still would consider this a bug unless due to the fact that the button attribute in the ion-item should avoid this black magic css and html.

**Comment by liamdebeasi** [comment] 2020-04-06 14:15
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by NikolaPeevski** [comment] 2020-04-06 19:40
@liamdebeasi I got you https://github.com/NikolaPeevski/ion-item-bug

**Comment by liamdebeasi** [comment] 2020-04-06 21:48
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Your app specifies the wrong `contentId` on `ion-menu`. The `contentId` property on `ion-menu` is an identifier that refers to the main page content, not the content of the `ion-menu`.

Normally, a class is added to the main page content that removes pointer-events when the menu is open, but since the wrong `contentId` was specified, Ionic Framework was adding the class to your menu's content.

To fix this, you will need to change your menu's `contentId` property from `content` to `main-content`.

For more information, please see the [ion-menu Documentation](https://ionicframework.com/docs/api/menu). Thanks!

**Closed by liamdebeasi** 2020-04-06 21:48 UTC
Labels: triage

**Comment by NikolaPeevski** [comment] 2020-04-06 21:56
@liamdebeasi I changed the content id and it still strips away the click events. Did you mean change it like this https://github.com/NikolaPeevski/ion-item-bug/commit/e2fcd41ded7fa45f6cf95eb07c9279f668cc2b38 or something different ?

**Comment by liamdebeasi** [comment] 2020-04-06 22:03
No, the `contentId` for your `ion-menu` needs to match the id for your `ion-router-outlet` (the outlet where your main page content will be displayed).
