### ISSUE TITLE
alert message in ionViewCanEnter don't work if push from popover 

### ISSUE THREAD

**Issue by Arnaud49** [ionic-team/ionic#11804] opened 2017-05-26 11:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I put some code to check permission before entering views. The code display an alert when permission are not enough and then reject in the ionViewCanEnter() to not push the page.
This works fine when the page is push from another page but when the page is push from a popover the message is not display.

**Expected behavior:**
The behavior should be the same than a page push from another page, the message should be displayed.

**Steps to reproduce:**

**Related code:**

```
  /**
   * Check authorization before entering the view.
   */
  ionViewCanEnter() {
    return new Promise((resolve, reject) => {
      this.usersService.getAuthorized().then((res) => {
        if (res.status) {
          resolve();
        } else {
          this.alertService.showAlert(res.title, res.restrictedMessage, null, res.buttons).then(() => {

          });
          reject();
        }
      });
    });
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment] 2017-05-26 15:18
Hello, thanks for using Ionic. Would you mind sharing a plunker we could use to reproduce this issue please?

**Comment by Arnaud49** [comment] 2017-05-30 11:10
http://plnkr.co/edit/L37BlfvHXEERkDcS6Dcx?p=preview

**Comment by kensodemann** [comment] 2018-01-03 03:41
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 03:41 UTC
Labels: needs info, v3
