### ISSUE TITLE
[4.2.0] bug: ion-datetime floating label always floats even without a value when in a formgroup

### ISSUE THREAD

**Issue by RobbHerman** [ionic-team/ionic#17979] opened 2019-04-05 15:20 UTC
# Bug Report

**Ionic version:**

[x] **4.x**
4.2.0

**Current behavior:**

When in a formgroup, label always floats on an ion-datetime field when no value

**Expected behavior:**

does not float when no value
**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by amunoz20** [comment] 2019-05-22 17:09
I can confirm this is happening. The ion-item has the class "item-has-value" even when theres no value on the input.

Any ideas for a workaround?

**Comment by dylan-westbury** [comment] 2019-05-29 21:22
Here is a screenshot of the issue, label floats without value for datetime

![visual of issue](https://i.imgur.com/CFWrery.png)

**Comment by kelvindart** [comment] 2019-06-14 09:22
I think this is because `hasValue()` in the `ion-datetime` always returns true, regardless of whether the control actually has a value. As a result, the class `item-has-value` is added to the `ion-item`. This controls the floating label and displays it differently to an empty control.

I had a similar bug, since I style my controls based on whether they have a value or not. As a result, I dug a big deeper, then raised a bug around my issue: #18540 and a PR for a fix: #18541.

Hopefully the guys at Ionic will merge this in soon 🙂.

**Comment by liamdebeasi** [comment] 2019-06-27 14:48
Hi there,

This issue has been resolved and will be in the next release of Ionic.

Thanks!

**Closed** 2019-06-27 14:48 UTC
Labels: package: core, type: bug

**Comment by cparkinsonMYCM** [comment] 2019-07-04 11:01
How is it that this was an issue in 3.x #11547 also and was resolved, and then _the exact same issue_ is present in 4.x..?

Is there a planned date for release of this fix?

**Comment by liamdebeasi** [comment] 2019-07-04 12:24
@cparkinsonMYCM,

This bug has already been fixed and will be in the next release of Ionic. 

You can visit our release schedule page to get a better idea of how we do releases. We typically release patches every 2 weeks (patches only contain bug fixes): https://ionicframework.com/docs/intro/versioning#release-schedule
