### ISSUE TITLE
bug: Keyboard pan got stuck, after keyboard closed on focus off.

### ISSUE THREAD

**Issue by barun-pandit** [ionic-team/ionic#19145] opened 2019-08-21 05:33 UTC
# Bug Report

**Ionic version:**
![ionic-info](https://user-images.githubusercontent.com/17941871/63404295-4947d800-c400-11e9-8a25-371806afc007.PNG)

**Current behavior:**
![Screenshot_20190821-104450_eConnect K12 Admin](https://user-images.githubusercontent.com/17941871/63404472-01758080-c401-11e9-81c7-66336f373551.jpg)

Video for Issue Description:
[https://drive.google.com/file/d/11_VBBkkBLm7rBnwnBKpCOrT-ZopzfqMh/view?usp=sharing](url)

**Expected behavior:**
![Screenshot_20190821-104712_eConnect K12 Admin](https://user-images.githubusercontent.com/17941871/63404540-413c6800-c401-11e9-84ce-dac4c97b1cc6.jpg)
Keyboard pan should hide on click select field.

**Steps to reproduce:**
1. Just focus-in input field.
2. Without focusing-out field click on select field.

**Comment by liamdebeasi** [comment] 2019-08-21 12:49
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

**Closed by liamdebeasi** 2019-08-21 12:49 UTC
Labels: triage
