### ISSUE TITLE
Compilation fails with TypeScript 2.4.x

### ISSUE THREAD

**Issue by RoopeHakulinen** [ionic-team/ionic#12233] opened 2017-07-02 15:51 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

App does not compile with TypeScript 2.4.x since 

```
typescript: ...ments/GitHub/Helvar/AA-mobile/node_modules/ionic-angular/components/nav/nav.d.ts, line: 47 
            Class 'Nav' incorrectly extends base class 'NavControllerBase'. Types of property 'goToRoot' are
            incompatible. Type '(opts: NavOptions) => Promise<any>' is not assignable to type '(opts: NavOptions) =>
            Promise<never>'. Type 'Promise<any>' is not assignable to type 'Promise<never>'. Type 'any' is not
            assignable to type 'never'.

      L47:  export declare class Nav extends NavControllerBase implements AfterViewInit, RootNode, INav {
      L48:      private _root;

[18:44:08]  typescript: ...ents/GitHub/Helvar/AA-mobile/node_modules/ionic-angular/components/tabs/tab.d.ts, line: 121 
            Class 'Tab' incorrectly extends base class 'NavControllerBase'. Types of property 'goToRoot' are
            incompatible. Type '(opts: NavOptions) => Promise<any>' is not assignable to type '(opts: NavOptions) =>
            Promise<never>'. Type 'Promise<any>' is not assignable to type 'Promise<never>'.

     L121:  export declare class Tab extends NavControllerBase implements ITab {
     L122:      private _cd;
```

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by RoopeHakulinen** [comment] 2017-07-02 16:41
This is caused by `new Error()` used in _NavControllerBase's_ [_goToRoot_](https://github.com/ionic-team/ionic/blob/master/src/navigation/nav-controller-base.ts#L1155). I'll take a look at fix and possibly submit a PR.

**Comment by RoopeHakulinen** [comment] 2017-07-02 19:59
PR #12235 fixes this by explicitly typing the promise.

**Comment by jgw96** [comment] 2017-07-03 14:32
Hello @RoopeHakulinen , thanks for using Ionic and thanks for the PR! We will look into getting this merged.

**Comment by vascofernandes** [comment] 2017-07-04 11:02
add this to tsconfig.json temporarily until the issue is fixed:

```
 "compilerOptions": {
     ....
    "skipLibCheck": true,
    "noStrictGenericChecks": true,
    .....

```

**Comment by ssalasgx** [comment] 2017-07-07 05:30
Hi, i suddenly had a problem like that,  and i didn't know why, i will share the screen
![error_navcont](https://user-images.githubusercontent.com/26204147/27944202-87cd63d6-62a2-11e7-8d35-85e73c504a4e.PNG)
I checked ionic info:
![error_nav2](https://user-images.githubusercontent.com/26204147/27944224-b67f9d02-62a2-11e7-92ad-84ad23814d2c.PNG)

And i try the solution from vascofernandes and it works, please can you explain how does it work? 

Best regards!

**Comment by RoopeHakulinen** [comment] 2017-07-07 05:49
It works because in TS 2.4 there was an addition to the compiler that improves generics checking. In this case it relates to checking the generic `Promise<T>` better. The problem is that the base class' (`NavControllerBase`) method returns `Promise<never>` while the child class' (`NavController`) overrides this method and returns `Promise<any>`. These two types are different starting from TS 2.4 and thus the compilation error.

**Comment by fiznool** [comment] 2017-07-10 09:38
Would love to see a fix for this soon! tslint is causing a load of erroneous warnings with ts 2.3.4 due to [this issue](https://github.com/palantir/tslint/issues/2470).

**Closed** 2017-07-10 19:31 UTC
Labels: v2

**Comment by mburger81** [comment] 2017-10-02 07:27
@RoopeHakulinen is it save to use TS 2.4.2 on ionic-angular@3.7.x, we have som libs which requires >2.4 but I saw ionic is for example reverting TS from 2.5.x back again to 2.3.4 so it seems > 2.3.4 should not work properly?

**Comment by RoopeHakulinen** [comment] 2017-10-02 07:43
I haven't had a chance to update yet myself so unfortunately can't tell you that :( @jgw96 probably knows

**Comment by nour05** [comment] 2018-03-20 23:11
it still does not work for me what I have to do!!
