### ISSUE TITLE
bug: I have in trouble when I used ion-item-sliding. If I click ion-item after a incomplete drag at the end of ion-item ，it can trigger ion-item-option

### ISSUE THREAD

**Issue by YueCaiCai** [ionic-team/ionic#18069] opened 2019-04-18 07:42 UTC
# Bug Report
I have in trouble when I used ion-item-sliding.
If I click ion-item after a  incomplete drag at the end of ion-item
 ，it can  trigger ion-item-option
**Ionic version:**

[x] **4.3.0**

**Current behavior:**

When I drag the point that I marked  incompletely and click ，it trigger  ion-item-option
![31299333-4A4F-4091-B3E7-7A1E71A20FD6](https://user-images.githubusercontent.com/46949975/56344041-0a560b80-61ef-11e9-96c1-328e9f4b76f4.png)
![B52F87EA-7A51-4016-9C6F-4B84AA9F720A](https://user-images.githubusercontent.com/46949975/56344043-0aeea200-61ef-11e9-9691-8c4c5558c90b.png)

**Expected behavior:**

It only shoulds trigger  ion-item-option when I drag completely and click  ion-item-option
**Steps to reproduce:**

**Steps to reproduce:**

**Related code:**

```
 <ion-item-sliding onIonDrag={() => {console.log('拖动')}} >
    <ion-item onClick={(e) => {console.log("点击item");e.stopPropagation()}}>
      <ion-label>
        hello world
      </ion-label>
    </ion-item>
    <ion-item-options side="end">
     
      <ion-item-option color="secondary">
     
       <ion-label onClick={() => {console.log('触发删除')}}>删除</ion-label> 
      </ion-item-option>
    </ion-item-options>
  </ion-item-sliding  >
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2019-04-18 14:18
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue? Also can you provide the output of running `ionic info`?

Thanks!

**Comment by YueCaiCai** [comment] 2019-04-19 08:55
> Hi there,
> 
> Thanks for the issue. Can you provide a repository with the code required to reproduce this issue? Also can you provide the output of running `ionic info`?
> 
> Thanks!

The demo that  display on official website  can reproduce the issue

**Comment by liamdebeasi** [comment] 2019-04-19 12:52
Hi there,

Which demo? I am trying to `ion-item` demo that has `ion-item-sliding` and am unable to reproduce this issue.

Thanks!

**Comment by toxsickcoder** [comment] 2019-04-21 13:30
I also have this issue. When you use a list with `ion-item-sliding` items and you slide the actions for an item open, but not far enough to instantly trigger the `ionSwipe` event, any click or slide on the opened item (even while trying to close it again) will emit the `ionSwipe` event.

Sliding or tapping another item while one is open will cause it to close correctly.

**Comment by liamdebeasi** [comment] 2019-04-22 12:28
Hi everyone,

Like I mentioned before, a code reproduction would be very helpful. I am unable to reproduce this on Ionic 4.3.0. 

Additionally, If you open an item partially but not enough to have it stay open, the item should close when you release your mouse. Is this not happening either?

**Comment by toxsickcoder** [comment] 2019-04-24 14:52
I have found my issue whilst making a reproduction (don't think it's same issue as OP). My click event was on `ion-item-options` instead of `ion-item-option`:

Bad:
```ts
  <ion-item-options (ionSwipe)="deleteItem()" (click)="deleteItem()">
    <ion-item-option slot="icon-only" expandable color="danger">
      <ion-icon name="trash" size="large" padding-start padding-end></ion-icon>
    </ion-item-option>
  </ion-item-options>
```

Good:
```ts
  <ion-item-options (ionSwipe)="deleteItem()">
    <ion-item-option slot="icon-only" expandable color="danger" (click)="deleteItem()">
      <ion-icon name="trash" size="large" padding-start padding-end></ion-icon>
    </ion-item-option>
  </ion-item-options>
```

**Comment by YueCaiCai** [comment] 2019-04-25 02:21
> I have found my issue whilst making a reproduction (don't know if it's same issue as OP). My click event was on `ion-item-options` instead of `ion-item-option`:
> 
> Bad:
> 
> ```
>   <ion-item-options (ionSwipe)="deleteItem()" (click)="deleteItem()">
>     <ion-item-option slot="icon-only" expandable color="danger">
>       <ion-icon name="trash" size="large" padding-start padding-end></ion-icon>
>     </ion-item-option>
>   </ion-item-options>
> ```
> 
> Good:
> 
> ```
>   <ion-item-options (ionSwipe)="deleteItem()">
>     <ion-item-option slot="icon-only" (click)="deleteItem()" expandable color="danger">
>       <ion-icon name="trash" size="large" padding-start padding-end></ion-icon>
>     </ion-item-option>
>   </ion-item-options>
> ```
My issue can reproduce when I clicked the ion-item-option

**Comment by YueCaiCai** [comment] 2019-04-25 02:28
> Hi everyone,
> 
> Like I mentioned before, a code reproduction would be very helpful. I am unable to reproduce this on Ionic 4.3.0.
> 
> Additionally, If you open an item partially but not enough to have it stay open, the item should close when you release your mouse. Is this not happening either?

It is right that the item should close when you release。But if I continue to click immediately，my issue can reproduce

**Closed** 2019-06-05 17:23 UTC
Labels: needs: reply
