### ISSUE TITLE
Status Bar cutting off app

### ISSUE THREAD

**Issue by stevepopovich** [ionic-team/ionic#15862] opened 2018-10-05 03:06 UTC
# Bug Report

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

App is cutoff by status bar on IOS app ONLY WHEN the app is pushed through test flight on a real device

![image uploaded from ios](https://user-images.githubusercontent.com/3252375/46514185-6c8a8880-c82a-11e8-9d60-fceb6e634960.png)

App runs fine in `ionic serve`, fine in xcode and then on a real device, it is cut off. If I `ionic cordova run ios --device`, the app is fine. 

In the screen that is cut off, I have tried `this.statusBar.overlaysWebView(false);` with the same result. This started happening when I add `splash-screen` plugin to the project, but reverting it back now yields the same result 

The app should not be cut off

This issue was helpful but is closed now: https://github.com/ionic-team/ionic/issues/13294

I have done everything outlined here to make the app render well on IPhone X: https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493
and here: https://forum.ionicframework.com/t/trouble-with-status-bar-on-ios-11/106339/11

**Comment by stevepopovich** [comment] 2018-11-19 03:36
Further Update: to totally fix this issue, I had to add the above code to the lifecycle hooks `ionViewDidEnter` and `ionViewDidLoad`. The app would still get cut off upon task manager switching

**Comment by paulstelzer** [comment] 2018-12-07 10:17
Thanks for your issue! This is not a bug, as you already found out, you have to use the cordova plugin statusbar to make it work. So I close this here

**Closed by paulstelzer** 2018-12-07 10:17 UTC
Labels: triage

**Comment by stevepopovich** [comment] 2018-12-12 03:42
oh that is definitely not the problem, I have the Cordova plugin installed. I would still call this a bug for sure
