### ISSUE TITLE
ion-input caracters becomes invisible after typing second caracter in some ios devices

### ISSUE THREAD

**Issue by aminefdil2** [ionic-team/ionic#10610] opened 2017-03-01 18:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x ] **2.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

ion-input caracters becomes invisible after typing second caracter in some ios devices (iphone 6 and iphone 7) ,  and once the input field lose the focus and the keyboard hides , the caracters becomes visible again

**Expected behavior:**

all input caracters must be visible all the time

**Steps to reproduce:**

just put a simple ion-input and test its behavior in iphone6 or iphone 7

**Related code:**

```
<ion-input type="email" placeholder="Email" formControlName="email"></ion-input>

this.login = new FormGroup({email: new FormControl('', Validators.required),password: new FormControl('', Validators.required)});

 ```

**Other information:**

- Screenshot of the ongoing problem:

<a href="http://www.hostingpics.net/viewer.php?id=495551Screenshotinputproblem.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_495551Screenshotinputproblem.jpg" alt="Heberger image" /></a>

- Screenshot after a manual focus of another field:

<a href="http://www.hostingpics.net/viewer.php?id=974249Screenshotinputproblemafterfocus.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_974249Screenshotinputproblemafterfocus.jpg" alt="Heberger image" /></a>

- The problem does not come from the scss (there is no scss that would make the text white for example) but from the update of the field. We tried to force the update (with listeners onFocus/onFocusout/KeyboardEvent) with the following code but it did not work:

this.login.controls['email'].updateValueAndValidity();

- The issue only appears on certain devices (ex: it appears on some iPhone 6 but not on iPad Mini)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

**Comment by cguieui4d** [comment] 2017-03-02 08:57
Some more information about the issue:

- Screenshot of the ongoing problem:

<a href="http://www.hostingpics.net/viewer.php?id=495551Screenshotinputproblem.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_495551Screenshotinputproblem.jpg" alt="Heberger image" /></a>

- Screenshot after a manual focus of another field:

<a href="http://www.hostingpics.net/viewer.php?id=974249Screenshotinputproblemafterfocus.jpg"><img src="http://img11.hostingpics.net/thumbs/mini_974249Screenshotinputproblemafterfocus.jpg" alt="Heberger image" /></a>

- Related html and ts code:

`<ion-input type="email" placeholder="Email" formControlName="email"></ion-input>`

`this.login = new FormGroup({email: new FormControl('', Validators.required),password: new FormControl('', Validators.required)});`

- The problem does not come from the scss (there is no scss that would make the text white for example) but from the update of the field. As mentioned above, we tried to force the update (with listeners onFocus/onFocusout/KeyboardEvent) with the following code but it did not work:

`this.login.controls['email'].updateValueAndValidity();`

- The issue only appears on certain devices (ex: it appears on some iPhone 6 but not on iPad Mini)

**Comment by jgw96** [comment] 2017-03-06 15:02
Hello, thanks for using Ionic. Could you post a repo that we could use to reproduce this issue?

**Comment by cguieui4d** [comment] 2017-03-06 15:35
Hello,

Unfortunately we cannot share the full repository with you (or on the forum
post) but please find attached the relevant files to test and the project
main information to reproduce the project (config.xml and package.json
files). Do not hesitate to get back at us if you need more information.

Thank you,

Regards

2017-03-06 16:03 GMT+01:00 Justin Willis <notifications@github.com>:

**Comment by kensodemann** [comment] 2018-01-03 03:16
Hello all! Is this still an issue with the latest version of ionic and with using WKWebView?

I will close this for now, but will happily reopen if it is still and issue and a sample application can be provided via GitHub that can be used to debug the issue (does not have to be your actual app, just a sample app that demonstrates the same issue).

Thanks!

**Closed by kensodemann** 2018-01-03 03:16 UTC
Labels: needs info, v2

**Comment by asdgadg** [comment] 2018-02-17 17:35
Appears to be a dupe of https://forum.ionicframework.com/t/ion-input-shows-only-the-first-entered-character-on-ios/73107
