### ISSUE TITLE
[V4]  ionic start ion4 tabs --type=angular freezes after creating directory

### ISSUE THREAD

**Issue by Liam-Ryan** [ionic-team/ionic#16194] opened 2018-11-02 11:06 UTC
# Bug Report

**Ionic Info**
```
V Gathering environment info - done!
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

ionic (Ionic CLI) : 4.3.0

System:

NodeJS : v10.13.0
npm : 6.4.1
OS : Windows 7
```

**Describe the Bug**
When trying to start a new ionic 4 application using --type=angular from the cmd prompt as described at https://beta.ionicframework.com/docs/installation/cli the build freezes after creating directory

**Steps to Reproduce**
1. Run ionic start |projectName| tabs --type-angular with the shown npm and NodeJS versions in Windows 7 cmd prompt ( administrator or non-administrator doesn't make a difference ) 
2. Observe frozen build process

**Expected Behavior**
Build goes beyond "preparing directory - Done" 

**Additional Context**
I’ve just updated my node & npm. I tried clearing the cache using force. I have angular and ionic installed globally. I’ve run in both admin and normal cmd prompt

Running without the --type=angular and selecting 'y' to start ionic 4 works fine, as does running an ionic 3 project

**Comment by kerosin** [comment] 2018-11-02 16:55
See https://github.com/ionic-team/ionic-cli/issues/3722

**Comment by dwieeb** [comment] 2018-11-02 19:52
Thanks for the bug report @Liam-Ryan.

Duplicate of https://github.com/ionic-team/ionic-cli/issues/3722

**Closed by dwieeb** 2018-11-02 19:52 UTC
Labels: triage
