### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lucabartoli** [ionic-team/ionic#19764] opened 2019-10-27 20:23 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Chrome on Android
Gboard as keyboard (doesn't happen with samsung keyboard)
Two text ion-input

Typing "word1 word2", then clicking on the other field and start typing something (let's say "word3"), at the first space ("word3 ") "word1" is appended to text (resulting in "word3 word1").

**Expected behavior:**
first word of the previous edited text not appended to the input.

**Steps to reproduce:**
Go to
https://ionicframework.com/docs/demos/api/input/index.html?ionic:mode=md
Using Chrome on an android phone with gboard
(mode ios is the same)

Tap on the first text field.
Write something.
Type on the second text field.
Type something with a space.

![Example](https://drive.google.com/uc?export=view&id=13ycGdsxVRBzaWZHjsR1VZajh7-c4mt2v)

**Comment by liamdebeasi** [comment] 2019-10-28 13:41
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I was able to reproduce this behavior outside of Ionic (using two native `input` elements).

**Closed by liamdebeasi** 2019-10-28 13:41 UTC
Labels: triage

**Comment by lucabartoli** [comment] 2019-10-28 22:10
Is it a bug in Vue?

**Comment by lucabartoli** [comment] 2019-10-28 22:47
Guys, the bug is in the gboard.
I'll try to open the issue with Google tomorrow.
Sorry to have bothered you!
