### ISSUE TITLE
bug: the open() of IonItemSliding doesn't work

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic#21216] opened 2020-05-05 21:53 UTC
# Bug Report

**Ionic version:**

[x] **5.1**

**Current behavior:**

open() of IonItemSliding doesn't work

**Expected behavior:**

open() of IonItemSliding should work normally

**Steps to reproduce:**

It look like timing issue like #11729.
So when the sliding value has a instance, I tried the open() function like code below.
The whole code is in stackblitz.

**Related code:**

```
@ViewChild('Sliding') set content(sliding: IonItemSliding) {
    if (sliding) {
      sliding.open('end');
    }
  }
```
https://stackblitz.com/edit/ionic-5-angular-9-start-template-6ugcvy

**Other information:**

**Ionic info:**

```
ionic5.1.0 
angular 9.1.1
```

**Comment by liamdebeasi** [comment] 2020-05-06 14:03
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic components initialize asynchronously, so setting `this.toggle = true` does not mean the sliding component is ready to be opened immediately. This is why calling `open` does not work in this instance.

All Ionic components expose a `componentOnReady` method that you can use to wait for a component to be ready. You may need to wait for the inner `ion-item-options` to be ready as well. Another option would be to just hide the component using `display: none` and toggle the display state rather than add it to the DOM.

**Closed by liamdebeasi** 2020-05-06 14:03 UTC
Labels: triage
