### ISSUE TITLE
[ionic 4] DateTime input wrong maxDay.

### ISSUE THREAD

**Issue by Silvest89** [ionic-team/ionic#17350] opened 2019-02-01 14:52 UTC
The date time input does not update the days range of the selected month.

<img width="495" alt="screenshot 2019-02-01 at 15 48 41" src="https://user-images.githubusercontent.com/2388338/52129939-2a871d00-2639-11e9-947b-16b6c7ce78d4.png">

**Comment by mopo922** [comment] 2019-02-02 05:54
I can confirm - I'm seeing this too.

**Comment by liamdebeasi** [comment] 2019-02-06 13:43
Closing as duplicate of #17385

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-06 13:43 UTC
Labels: triage
