### ISSUE TITLE
[v4 beta-12]: perf: Build process is drastically slower

### ISSUE THREAD

**Issue by lukeisontheroad** [ionic-team/ionic#15965] opened 2018-10-16 12:09 UTC
# Bug Report

**Ionic Info (before upgrade)**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.11
   @angular-devkit/build-angular : 0.8.5
   @angular-devkit/schematics    : 0.8.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : 1.0.0

System:

   NodeJS : v9.11.2 (/usr/local/lib/node_modules/node/bin/node)
   npm    : 6.1.0
   OS     : macOS
```

**Ionic Info (after upgrade)**
```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.8.5
   @angular-devkit/schematics    : 0.8.5
   @angular/cli                  : 6.2.5
   @ionic/angular-toolkit        : 1.0.0

System:

   NodeJS : v9.11.2 (/usr/local/lib/node_modules/node/bin/node)
   npm    : 6.1.0
   OS     : macOS
```

**Describe the Bug**
After upgrading from beta 11 to beta 12, I noticed a big difference in compile time. 

**Before (4.0.0-beta.11):**
[ng] ℹ ｢wdm｣: Compiling...
[ng] 
[ng] Date: 2018-10-16T11:58:26.944Z - Hash: 100fa7e4d25e03303631 - Time: **8463ms**
[ng] 173 unchanged chunks
[ng] chunk {tabs-tabs-module} tabs-tabs-module.js, tabs-tabs-module.js.map (tabs-tabs-module) 25.9 kB  [rendered]
[ng] ℹ ｢wdm｣: Compiled successfully.

**After (4.0.0-beta.12):**
[ng] ℹ ｢wdm｣: Compiling...
[ng] 
[ng] Date: 2018-10-16T12:04:02.336Z - Hash: 9a0c1949d63b849a7238 - Time: **74036ms**
[ng] 173 unchanged chunks
[ng] chunk {tabs-tabs-module} tabs-tabs-module.js, tabs-tabs-module.js.map (tabs-tabs-module) 25.9 kB  [rendered]
[ng] ℹ ｢wdm｣: Compiled successfully.

It's only an incremental change (color from light to dark in one of the components), but it almost takes as long as the initial compile duration.

**Steps to Reproduce**
1. ionic start myApp tabs --type=angular
2. ionic serve
3. wait for the first build
4. make a small change (i.e. tabs.page.html <ion-tabs> to <ion-tabs color="primary">)
5. check the complication time
6. downgrade "@ionic/angular": "4.0.0-beta.12" to "@ionic/angular": "4.0.0-beta.11"
7. repeat steps 2-5

**Related Code**
Starter project & my custom project

**Expected Behavior**
Similar build performance as before (at least not x10 times slower)

**Additional Context**
None

**Comment by kerosin** [comment] 2018-10-16 12:36
> Update to Node 10 is right. Compiling time from 79s to 7s.

Duplicate of https://github.com/ionic-team/ionic/issues/15800 or https://github.com/ionic-team/ionic/issues/15644

**Closed** 2018-10-16 13:02 UTC
Labels: triage
