### ISSUE TITLE
lazy-load-tabs is not working as expected.

### ISSUE THREAD

**Issue by siva563** [ionic-team/ionic#15490] opened 2018-09-07 07:02 UTC
Component is not loading at all, I was tried your Github example in path of 

`ionic-master\angular\test\testapp\src\app\lazy-load-tabs` not working, could you please help what we need to fix it.

**Comment by MrSparklle** [comment] 2018-09-10 20:15
This issue is being treated in https://github.com/ionic-team/ionic/issues/14566

**Comment by mhartington** [comment] 2018-09-12 21:49
Closing as duplicate of https://github.com/ionic-team/ionic/issues/14566

Please track that issue instead of opening new issues.

**Closed by mhartington** 2018-09-12 21:49 UTC
Labels: triage
