### ISSUE TITLE
bug: ion-item border color css variable does not work in production android apk

### ISSUE THREAD

**Issue by gaurav-chandra** [ionic-team/ionic#19989] opened 2019-11-25 05:45 UTC
# Bug Report

**Ionic version:**
4.11.5

**Current behavior:**
In the documents, ion-item border color can be styled by setting ```--border-color``` css variable. It works in case of debug android apk but when we run play store release apk, the border color shows as black instead of the custom color. 

**Expected behavior:**
the play store release apk should show the custom border color.

**Steps to reproduce:**
Start with tabs starter and build for debug and production. In case of debug the border-color styled via css variable works but in case of production apk, the css variable does not work.

**Related code:**

```
.form ion-item, ion-toolbar ion-item,.searchbar-input.sc-ion-searchbar-md, form ion-item {
	border-radius: 4px 4px 4px 4px;
	border-color: #dde5ed; /* works in production apk */
	--border-color: var(--ion-color-border,#dde5ed) !important; /* does not work in production apk */
	margin-top:15px;
}
```

**Other information:**
if the border-color is set via standard css property, it works in production.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.8 (C:\Users\Gaurav's PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 19 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.8.1)
   native-run  : 0.2.2 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (C:\AndroidSDK)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-05-29 19:12
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17781.

Please see https://github.com/ionic-team/ionic/issues/17781#issuecomment-636126472 for an explanation of why this issue is happening and what you can do to work around it. Thanks!

**Closed by liamdebeasi** 2020-05-29 19:12 UTC
Labels: triage
