### ISSUE TITLE
[v4-beta.19] Tabs stop working when moving from a page with tabs to another page with tabs

### ISSUE THREAD

**Issue by Silvest89** [ionic-team/ionic#16773] opened 2018-12-16 20:55 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Navigating from a page with tabs to another one with tabs breaks the tabs. You can still click on the tabs (url also changes) but the page does nothing. It is still stuck at the default tab. I have to navigate to a page without tabs first and then navigate to my desired tab page for it to work.

**Expected behavior:**
Tabs should not break

**Steps to reproduce:**
Just have a page with tabs and navigate to another one with tabs. I use the split pane menu in my case.

EDIT:

It seems to be something related to the router outlet.

**Comment by paulstelzer** [comment] 2018-12-16 21:43
Thanks for your issue! We are aware of this problem and the good news is: We have a fix for it :) But I cannot say when the next beta will be online.

It's a duplicate of #16411 so I close this here

**Closed by paulstelzer** 2018-12-16 21:43 UTC
Labels: triage

**Comment by amitairos** [comment] 2018-12-17 10:34
@paulstelzer I think it's a pretty major issue. Glad you fixed it. I think it's worth pushing a small release for it :-)

**Comment by paulstelzer** [comment] 2018-12-17 10:35
I did not fixed it, it was @manucorporat  ;) I think there will be a new beta soon
