### ISSUE TITLE
Can't set aria label for tab buttons

### ISSUE THREAD

**Issue by Rhaio** [ionic-team/ionic#15588] opened 2018-09-13 19:54 UTC
onic version: (check one with "x")
[ ] 1.x
[] 2.x
[x]3.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
It is not possible to set a meaningful aria label on a tab button. If you set <ion-tab [attr.aria-label]="some label"> then the label doesn't get set on the button. It looks like the aria label is currently pulled from the icon name of the tab.

Expected behavior:
I would expect the aria-label attribute to propagate to the tab's button or by default the tab button should use the [tabTitle] attribute for the default aria label on the button.

Steps to reproduce:

Set [attr.aria-label]="some label" on an <ion-tab>
Enable VoiceOver in iOS.
Tap the tab and it reads out the icon name
Ionic info: (run ionic info from a terminal/cmd prompt and paste output below):

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (C:\Users\cassianosantana\AppData\Roaming\nvm\v8.9.4\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 11 other plugins)

System:

   NodeJS : v8.9.4 
   npm    : 5.6.0
   OS     : Windows 10

**Comment by yannbf** [comment] 2018-10-01 09:32
Experiencing the same issue. As the tabs deal with the icons and not us, in case we use custom icons with different class names it can lead to unexpected labeling which is not nice. Would be great to have a way to define the aria-label of each tab to our own liking.

**Comment by yannbf** [comment] 2018-10-01 09:36
This post is a duplicate of #10302 which was posted on february 2017 and closed due to inactivity, but still, it's a very important matter that should be addressed. 
@jgw96 would you happen to have any updates regarding this? 
Thanks!

**Comment by AdamModus** [comment] 2018-10-03 12:00
I'm feeling this issue as well. My suggestion would be to implement this not just for buttons but for all components that create buttons on their implementation (an example is ion-tabs) 🙂
Another thing that would be nice is for things like  "back button" for navigation or other things like this to have aria-labels configurable on `app.module.ts`.

A good example of it would be things like supporting multiple languages, etc... Where it has to be defined because language and context are almost impossible to predict beforehand. Letting us set it would make things better for our visually impaired clients!

**Comment by brandyscarney** [comment] 2018-10-26 20:28
Thank you for the issue! We have changed the tabs API in v4 so that you will have full access to the tab buttons and be able to add this attribute. I am going to close this issue since it is not something we plan to backport, but please see my comment here for more information on the latest tabs API: https://github.com/ionic-team/ionic/issues/15942#issuecomment-433429959. Thanks!

**Closed by brandyscarney** 2018-10-26 20:28 UTC
Labels: triage
