### ISSUE TITLE
bug: performance issue in Ionic-select control type with interface option "alert" Ionic/Angular

### ISSUE THREAD

**Issue by VenkataPraneethT** [ionic-team/ionic#19345] opened 2019-09-15 13:40 UTC
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**
If we try to use Ion-select with interface="popover" the performance is very slow. However when we use other interface type such as default one the performance is better for the same set of data.

**Expected behavior:**
We expect the same performance for all the interfaces available in ion-select.

**Steps to reproduce:**
Use the control type ion-select with interface="popover" and dynamically render the same control type ion-select 5 times in the web page with each element having 1500 options.

**Comment by liamdebeasi** [comment] 2019-09-16 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17641. 

However, please note that this is not really the intended usage of `ion-select`. It would be better to place these 1500 options in a modal the uses virtual scroll.

**Closed by liamdebeasi** 2019-09-16 13:18 UTC
Labels: triage
