### ISSUE TITLE
Ionic input disabled property cannot contain a function or variable only the string true or false

### ISSUE THREAD

**Issue by cambronjay** [ionic-team/ionic#9468] opened 2016-12-02 16:34 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The Disabled input property only accepts a true or false value.

**Expected behavior:**
The Disabled input property should accept true or false which can be provided by a function call or boolean variable, not just the words true or false. 

**Steps to reproduce:**

**Related code:**

```
<ion-item>
  <ion-label>Gender</ion-label>
  <ion-select disabled="formCheck()" [(ngModel)]="gender">
    <ion-option value="f" selected="true">Female</ion-option>
    <ion-option value="m">Male</ion-option>
  </ion-select>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
OS: Windows 7 SP1
Node Version: v6.9.1
```

**Comment by cambronjay** [comment] 2016-12-02 18:32
So the documents are unclear as to how disabled should be used. Disabled requires interpolation of the function or variable into it to work. Also, placing required on an ionic input works, but it must be set to a boolean value. 
**Example:**
required="true"
disabled="{{!SomeValue.valid || !SomeFunction()}}"

**Comment by jgw96** [comment] 2016-12-02 19:06
Hello! Thanks for opening an issue with us! So the correct way to do property binding in Angular 2/ Ionic 2 is with this syntax `[disabled]="formCheck()"`. You can read more about this [here](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding) in the Angular 2 docs. Thanks!

**Comment by cambronjay** [comment] 2016-12-02 19:10
Doing that does not work.

**Comment by jgw96** [comment] 2016-12-02 19:14
Sorry about that, would you mind posting your `formCheck()` function? Does that function return a boolean?

**Comment by cambronjay** [comment] 2016-12-02 19:27
The issues is that on a button you can place [disabled]="someFunction()", but when it comes to ionic inputs  if you place [disabled]="someFunction()" the function never gets called. I believe this is due to the fact that ionic inputs are custom elements and not native html input elements. In order to make it work disabled="{{someFunction()}}" had to be used. Also, required is not listed in the documentation as a possible property, yet required="true" works on an input. It might be a possible type error where the property expects a boolean, but uses a string. Yes the someFunction() returned a boolean, but interpolation outputted it as a string.

**Comment by cambronjay** [comment] 2016-12-02 19:38
In the code you have _disabled: any = false; However, the code is not handling what can be placed into disabled in the correct manner.

**Comment by jgw96** [comment] 2016-12-05 21:18
Hello @cambronjay we added some tests above to specifically test this issue along with testing this locally on a demo app i have and unfortunately we cannot reproduce this issue still. Could you post your function that your using with `[disabled]` ? Thanks!

**Comment by brandyscarney** [comment] 2017-08-09 18:44
I'm going to close this issue since we are not able to reproduce it and there have been many changes to input since this was opened. Please let us know if you're still experiencing this and we can reopen. I tried with the following code:

```
<ion-item>
  <ion-label>Toggle Disabled</ion-label>
  <ion-input [disabled]="getDisabled()" value="test"></ion-input>
</ion-item>
```

```
export class PageOne {
  private _disabled = true;

  toggleDisabled() {
    this._disabled = this._disabled ? false : true;
  }

  getDisabled() {
    return this._disabled;
  }
}
```

and everything seems to be working correctly.

**Closed by brandyscarney** 2017-08-09 18:44 UTC
Labels: v2
