### ISSUE TITLE
bug: ion-datetime AM/PM resets on hour change

### ISSUE THREAD

**Issue by tomas-c** [ionic-team/ionic#20026] opened 2019-12-02 11:54 UTC
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

AM/PM selection resets to AM when changing hours in ion-datetime with pickerFormat="h:mm A"

**Expected behavior:**

It should not reset to AM.

**Steps to reproduce:**

1) Go to https://ionicframework.com/docs/api/datetime
2) Click on "Start Time" in the preview to the Datetime picker 
3) Select "PM"
4) Change the selected hour
5) Observe that AM/PM column reset to AM
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.803.19
   @angular-devkit/schematics    : 8.3.14
   @angular/cli                  : 8.3.19
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/home/tomas/.nvm/versions/node/v10.16.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 5.0


  ───────────────────────────────────────────────

     Ionic CLI update available: 5.4.4 → 5.4.5
           Run npm i -g ionic to update

  ───────────────────────────────────────────────

```

**Comment by liamdebeasi** [comment] 2019-12-02 13:50
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19260. Please note that the linked issue has been consolidated into a main datetime issue tracker: https://github.com/ionic-team/ionic/issues/16630.

**Closed by liamdebeasi** 2019-12-02 13:50 UTC
Labels: triage
