### ISSUE TITLE
Side Menu Close Delay iOS

### ISSUE THREAD

**Issue by bertdejager** [ionic-team/ionic#12089] opened 2017-06-19 10:06 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm using the sidemenu(ion-menu) on a Iphone 7 and use the menuToggle option.
Clicking the toggle menu opens the menu as expected. If you click the menuToggle within a second or so the menu does not close. If you wait a second or so the menu is closed correctly, but with a delay.  If you use the option type='overlay' the menutoggle is not shown but you can immediately close the menu. I would like to have the same behavior with the togglemenu.
We use the ion-menu within a ion-split-pane, used for ipad users
**Expected behavior:**

the menutoggle should respond directly if you tap it.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
You can reproduce the issue with a clean starter project.
1. create app with CLI
  >ionic start TestApp sidemenu
2. Deploy this on a iphone 7 device.
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 3.10.10

**Comment by AmitMY** [comment] 2017-06-19 11:50
Are you using the `--prod` flag?

**Comment by shawnlan** [comment] 2017-06-19 23:52
already reported here: https://github.com/ionic-team/ionic/issues/9716

**Comment by jgw96** [comment] 2017-06-23 16:37
Hello all, I am going to close this issue as a duplicate of #9716 .

**Closed by jgw96** 2017-06-23 16:37 UTC
Labels: needs info, v2
