### ISSUE TITLE
bug: cssClass is not getting applied to actionSheet 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20883] opened 2020-03-26 13:00 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

It is not overriding style of actionsheet buttons.

**Expected behavior:**

It should override the style of actionsheet buttons.

**Steps to reproduce:**

**Related code:**

Stackblitz playground: https://stackblitz.com/edit/ionic-angular-v5-tvhwya?file=src%2Fapp%2Fapp.component.ts

```
.color-cancel {
  --color:red;
}
```

```
 async presentActionSheet() {
    const actionSheet = await this.actionSheetController.create({
      mode:'ios',
      buttons: [{
        text: 'Share',
        handler: () => {
          console.log('Share clicked');
        }
      }, {
        text: 'Play (open modal)',
        handler: () => {
          console.log('Play clicked');
        }
      }, {
        text: 'Cancel',
        role: 'cancel',
        cssClass: 'color-cancel',
        handler: () => {

          console.log('Cancel clicked');
        }
      }]
    });
    await actionSheet.present();
  }
```

**Other information:**

**Ionic info:**

```
5.0.5
```

**Comment by liamdebeasi** [comment] 2020-03-26 15:18
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. While the `color-cancel` class is getting added to your cancel button, the styles are not reaching it because of Angular's view encapsulation. The generated CSS looks like something similar to this:

```css
.color-cancel[_ngcontent-fts-c0] {
  --color: red;
}
```

For more information regarding view encapsulation in Angular, please see https://angular.io/guide/component-styles#view-encapsulation.

In terms of how to resolve this issue, one option might be to place your action sheet styles in a `global.scss` file. Alternatively, you could disable view encapsulation for your AppComponent, but that may have undesirable side effects.

**Closed by liamdebeasi** 2020-03-26 15:18 UTC
Labels: triage
