### ISSUE TITLE
bug: Tabs navigation animations

### ISSUE THREAD

**Issue by simetin** [ionic-team/ionic#19815] opened 2019-10-31 18:09 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
There is no navigation animation when you navigate to a page that is not a child of one of the tabs.
Example going from /tabs/home to /tabs/items/itemID

Here is a screen recording of the problem: https://youtu.be/Eq7LfXoZL2A

I have create a repo illustrating the issue. https://github.com/simetin/ionic-tabs-nav.

**Expected behavior:**
I get that I could just do example /tabs/home/items/itemID, however with an app bigger than a couple of pages and that has a lot of links between different type of items (think for example of Instagram), it become infeasible.  

**Steps to reproduce:**

**Related code:**

[https://github.com/simetin/ionic-tabs-nav](https://github.com/simetin/ionic-tabs-nav)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 20 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.9 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.0 Build version 11A420a


```

Thanks !

**Comment by liamdebeasi** [comment] 2019-10-31 18:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18857.

**Closed by liamdebeasi** 2019-10-31 18:14 UTC
Labels: triage
