### ISSUE TITLE
bug: Two tabs shown as active on pressing back button on Android

### ISSUE THREAD

**Issue by gurumukhi** [ionic-team/ionic#21322] opened 2020-05-18 09:56 UTC
# Bug Report

**Ionic version:**

 **^5.0.7**

**Current behavior:**

On pressing back button, two icons are shown with active style

**Expected behavior:**

Only one tab should be shown as active

**Steps to reproduce:**

Go to tab1, then go to tab2 & press back button on android device. Kindly note, this issue is not reproducible if you inspect the app via chrome://inspect debugger tools.

**Related code:**
A sample application via GitHub - https://github.com/gurumukhi/ionic-tabs/blob/master/src/App.tsx

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.9.2 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : 0.14.0
   native-run  : not installed

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10                                                                                                           
```

**Comment by liamdebeasi** [comment] 2020-05-18 13:04
Thanks for the issue. Are you testing this on a physical device or an emulator?

**Comment by gurumukhi** [comment] 2020-05-18 14:57
I am testing on the physical device. The issue exist even on the basic Tabs
app created from https://ionicframework.com/start.

**Comment by liamdebeasi** [comment] 2020-05-18 15:00
What device and version of Android are you testing on?

**Comment by gurumukhi** [comment] 2020-05-18 15:34
I am testing on OnePlus 5T, Android version is 9.

**Comment by liamdebeasi** [comment] 2020-05-18 16:52
Thanks for the follow up. I am unable to reproduce this behavior using the reproduction you have provided. Here are the steps I am following:

1. Start application on Tab 1.
2. Tap "Tab 2".
3. Press the hardware back button to return to Tab 1.

After step 3 my understanding is that both the Tab 1 and Tab 2 buttons should appear active; however, they do not appear active at the same time for me. Are these the correct steps to reproduce?

**Comment by gurumukhi** [comment] 2020-05-24 16:02
Yes @liamdebeasi, the steps are correct. If I find some other ways to reproduce this or find issue at my own end, will let you know. Thanks.

**Comment by liamdebeasi** [comment] 2020-05-26 13:04
Ok thanks! I am going to close this for now. If you find another way to reproduce this issue feel free to reply here, and I can reopen the issue.

**Closed by liamdebeasi** 2020-05-26 13:04 UTC
Labels: triage
