### ISSUE TITLE
bug: if routerLink to not brother or children page not trigger ionViewWillLeave()

### ISSUE THREAD

**Issue by liuxi198991** [ionic-team/ionic#18787] opened 2019-07-13 04:10 UTC
Ionic version:

[x] 4.6.x

Current behavior:
HomePage routerLink to GamesPage not trigger ionViewWillLeave(),if HomePage  routerLink to brother Page (Offers,Wallet,Msg,My) is right

Expected behavior:
if routerLink to all Page trigger ionViewWillLeave()

Steps to reproduce:
HomePage routerLink to GamesPage

Related code:

Route in app-routing.module.ts
```
const routes: Routes = [
    {path: '', loadChildren: './tabs/tabs.module#TabsPageModule'},
    {path: 'games', loadChildren: './games/games.module#GamesPageModule'}
];
```
Route in tabs.router..module.ts
```
const routes: Routes = [
    {
        path: 'tabs',
        component: TabsPage,
        children: [
            {
                path: 'home',
                loadChildren: '../home/home.module#HomePageModule'
            },
            {
                path: 'offers',
                loadChildren: '../offers/offers.module#OffersPageModule'
            },
            {
                path: 'wallet',
                loadChildren: '../wallet/wallet.module#WalletPageModule'
            },
            {
                path: 'msg',
                loadChildren: '../msg/msg.module#MsgPageModule'
            },
            {
                path: 'my',
                loadChildren: '../my/my.module#MyPageModule'
            }
        ]
    },
    {
        path: '',
        redirectTo: '/tabs/home',
        pathMatch: 'full'
    }
];
```
ionViewWillLeave in home.page.ts
```
ionViewWillLeave() {
        console.log('ionViewWillLeave');
 }
```

**Comment by liamdebeasi** [comment] 2019-07-16 13:14
Thanks for the issue. I am not sure I understand the issue that you are experiencing. Is `ionViewWillLeave` not firing when switching tabs?

**Comment by liuxi198991** [comment] 2019-07-17 04:11
> 谢谢你的问题。我不确定我是否理解您遇到的问题。被`ionViewWillLeave`切换标签时不触发？

ionViewWillLeave firing when switching tabs,if routerLink to other page(GamesPage) ionViewWillLeave not firing

**Comment by liamdebeasi** [comment] 2019-07-17 13:34
Thanks for the follow up. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16834. Please follow that thread for any updates regarding this issue. Thanks!

**Closed by liamdebeasi** 2019-07-17 13:34 UTC
Labels: triage

**Comment by liuxi198991** [comment] 2019-07-18 03:16
> 感谢您的跟进。我打算将其作为[＃16834](https://github.com/ionic-team/ionic/issues/16834)的副本关闭。请关注该主题以获取有关此问题的任何更新。谢谢！



> Thanks for the follow up. I am going to close this as a duplicate of #16834. Please follow that thread for any updates regarding this issue. Thanks!

Ok,Thanks!
