### ISSUE TITLE
bug: App freeze when we try to open popover twice

### ISSUE THREAD

**Issue by tajinder-logiciel** [ionic-team/ionic#19302] opened 2019-09-09 06:54 UTC
# Bug Report

**Ionic version:**
[x] **4.9.0**

**Current behavior:**
App freeze when we try to open popover twice

**Expected behavior:**
Should not freeze

**Steps to reproduce:**
Create ionic project with @ionic/angular@4.9.0 version
Create popover and then try to open popover twice

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/tajinder/Library/Android/sdk)
   NodeJS            : v12.8.0 (/Users/tajinder/.nvm/versions/node/v12.8.0/bin/node)
   npm               : 6.10.2
   OS                : macOS Mojave

```

**Comment by Noaber** [comment] 2019-09-09 07:45
Having the same issue, reverting back to 4.8.1 solves the problem.

**Comment by DavidStrausz** [comment] 2019-09-09 10:12
duplicate, see #19277

**Comment by manucorporat** [comment] 2019-09-11 13:03
Can you provide some source code that reproduces the issue? what do you mean with open popover twice?

**Comment by tajinder-logiciel** [comment] 2019-09-12 05:58
@manucorporat check this
Related Code https://github.com/tajinder-logiciel/popup-issue

**Comment by tajinder-logiciel** [comment] 2019-09-19 10:31
@manucorporat any update regarding this

**Comment by liamdebeasi** [comment] 2019-09-25 16:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19277. We have a fix in place and should be merging it in shortly.

**Closed by liamdebeasi** 2019-09-25 16:53 UTC
