### ISSUE TITLE
feat: Split imports to minimise bundle

### ISSUE THREAD

**Issue by IljaDaderko** [ionic-team/ionic#19836] opened 2019-11-05 07:18 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I believe it is not possible to have imports like
```ts
import IonApp from "@ionic/react/IonApp"
```

and after examining bundle that is build it seems that current imports bundle full code even for components that are not used?
```ts
import { IonApp } from "@ionic/react"
```

**Describe Preferred Solution**

Perhaps we should re-do export to where it allows specific imports? Libraries like `lodash` and `materila-ui` do this to optimise bundle sizes.

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by IljaDaderko** [comment] 2019-11-05 07:19
I would be glad to work on the pr if this is something you guys are willing to explore?

**Comment by elylucas** [comment] 2020-01-23 20:52
Hello,

Unused components are tree shaken out of the final bundle during a release build. This is handled by webpack and react-scripts.

Going to close this issue as its not a bug with the framework, but please comment here if you have any questions.

**Closed by elylucas** 2020-01-23 20:52 UTC
Labels: package: react
