### ISSUE TITLE
Ionic 4 with Android 4.4

### ISSUE THREAD

**Issue by amitairos** [ionic-team/ionic#16973] opened 2019-01-06 10:41 UTC
# Support Question

Anybody here had any success in running the latest RC of Ionic 4 on Android 4? When I run it the icons and the colors are all messed up. But when I run it as a PWA, it works perfectly.

Any ideas?

Note: I uncommented these polyfills:
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
 import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

**Comment by EugeneNews** [comment] 2019-01-06 16:06
I run successfully on Android 4.4 - while push services and some other stuff is not working (I'm already is not expecting).
I use polyfills like this
```// IE9, IE10 and IE11 requires all of the following polyfills.
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
// import 'core-js/es6/weak-map';
// import 'core-js/es6/set';```

**Comment by amitairos** [comment] 2019-01-06 16:10
@EugeneNews As mentioned, I also imported those polyfills, also the ones you commented out. Could commenting them out be necessary?
Any other changes besides polyfills?

**Comment by EugeneNews** [comment] 2019-01-06 17:42
> Any other changes besides polyfills?
no, actually.
What `webview` you have? Mine is 
```"cordova-plugin-ionic-webview": "^2.3.1"```
old ZTE device with Android 4.4 - and it was not working before RC0

**Comment by Riyaz0001** [comment] 2019-01-07 20:44
it is possible to use ionic all feature run Android 4.4+.
any idea?

**Comment by redwolf2** [comment] 2019-01-08 12:55
You should also use 

"cordova-plugin-ionic-webview": "3.0.0"

And add it to package.json like so:

```
  "cordova": {
    "plugins": {
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
```

**Comment by amitairos** [comment] 2019-01-08 20:49
Tried with latest ionic webview. Still had problems. PWA is perfect on the other hand.

**Comment by ghenry22** [comment] 2019-01-09 00:54
You might want to try using Crosswalk for Android 4.x versions
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

On older Android versions the system webview was not updated through the play store like it is now but only with major OS updates so the system webview was often much older than the version of Chrome that was installed.

Sounds like it might be your issue as Chrome works but the system webview (used by ionic apps) doesn't.

**Comment by redwolf2** [comment] 2019-01-09 09:17
Also make sure your Android Device is using the right Web View implementation. This can be configured inside the Developer Settings. Mine allows for "Android AOSP Webview" and "Chrome Stable", with "Android AOSP Webview" as a system default, where "Chrome Stable" should be the right choice.

**Comment by ghenry22** [comment] 2019-01-09 10:06
You can’t expect users to change that though so you should make your app choose the right webview for them buy using crosswalk with android 4.x versions, 5+ receive webview updates through the play store so should always be reasonably current.

**Comment by redwolf2** [comment] 2019-01-09 15:03
Sure, but keep this in mind: https://crosswalk-project.org/blog/crosswalk-final-release.html

**Comment by ghenry22** [comment] 2019-01-10 00:36
Yes that’s because Android 5+ has auto updates of the webview, if you need to still support 4.4 then crosswalk is still your only option as far as I know to get something newer than the system webview.

**Comment by redwolf2** [comment] 2019-01-10 15:08
I found my icon tinting problem and created this issue: https://github.com/ionic-team/ionicons/issues/652

**Comment by peterennis** [comment] 2019-01-10 22:11
> Have you updated your WebView via [Play Store](https://play.google.com/store/apps/details?id=com.google.android.webview)?
> 
> Icon colors are kinda messed up, even when running with the latest Chrome Windows version.
> 
> ![grafik](https://user-images.githubusercontent.com/4141621/50794417-57127800-12cb-11e9-894c-75e81ba66d17.png)
> 
> (Both icons don't specify a color, but are not tinted in the default grey)

@redwolf2 

I recognize that icon.
See here: https://github.com/ionic-team/ionicons/issues/576#issuecomment-408654237

@manucorporat @bensperry @adamdbradley 

The issue is parsing of the original icons in ionicons
Possibly here:
https://github.com/ionic-team/ionicons/blob/master/scripts/generate.py#L107
svgo is not removing the bad bits and I did not have sufficient
pyfoo to confirm or deny.

Piping a sed into the mix was an option I considered, but I work on Windows
and there were build issues.

There is also a PR put forward for this that has not been adopted.
https://github.com/ionic-team/ionicons/pull/594
I suspect it does not deal with the root problem of the autogeneration of the icons
as I believe the artifact comes from Adobe.

**Comment by paulstelzer** [comment] 2019-01-11 08:04
@peterennis I know the problem of the svgs and have sent a message to the team. I hope it will fixed soon

The newest cordova-plugin-ionic-webview is also not a solution for Android 4.4 problem because until Android 4.4, the webview will not updated via Google Play Store and so keeps the same version . That's the reason why Ionic is not working well on there because there are a lot of missing features.

I would suggest the following:
- Create an app apk with Android 5+ support (here the webview will be updated through play store, so users have a more updated version then you can check via the emulators)
- Create an app with only up to Android 4.4 with Crosswalk (an app with crosswalk has a big size, so it's recommend that only users up to Android 4.4 get this apk and everyone over Android 5 gets the normal apk. And don't forget to add the polyfills.

I will close this topic now, but if you find another issue, just open a new issue :)

**Closed by paulstelzer** 2019-01-11 08:04 UTC
Labels: triage
