### ISSUE TITLE
bug: Could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by mlabieniec** [ionic-team/ionic#20906] opened 2020-03-29 13:08 UTC
# Bug Report

**Ionic version:**

[x] 5.4.16

**Current behavior:**

- Fresh install `npm i -g @ionic/cli && ionic start`
- Chose Blank template / Angular
- Created a page: `ionic g page cart`
- Added an ion-menu to AppComponent
- Ran `npm run build`

```
$ npm run build
> ng build

Generating ES5 bundles for differential loading...
An unhandled exception occurred: [BABEL] /Users/Michael/workspace/plumecraft.com/www/cart-cart-module-es2015.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/michael/workspace/plumecraft.com/node_modules/@babel/preset-env/lib/index.js")
See "/private/var/folders/kk/mjzs5lwx7rq52z8mtkqw7c280000gn/T/ng-lgqh7p/angular-errors.log" for further details.
```
**Expected behavior:**

App builds without errors

**Steps to reproduce:**

- Fresh install `npm i -g @ionic/cli && ionic start`
- Chose Blank template / Angular
- Created a page: `ionic g page cart`
- Added an ion-menu to AppComponent
- Ran `npm run build`

**Related code:**

Added
```
"resolutions": {
    "@babel/preset-env": "7.5.5"
  },
```
https://github.com/mlabieniec/plume/blob/master/package.json#L14-L16

And it worked. Found the resolution here:
https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator

Ionic (ran this after an ionic upgrade, error actually occurred on v5.4.16)
```
   Ionic CLI                     : 6.3.0 (/Users/michael/.nvm/versions/node/v12.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (/Users/michael/.nvm/versions/node/v12.13.1/bin/node)
   npm    : 6.12.1
   OS     : macOS Catalina
```

**Comment by indraraj26** [comment] 2020-03-29 17:03
Wait for sometime it will get fixed by babel team.
https://github.com/angular/angular-cli/issues/17262

**Comment by liamdebeasi** [comment] 2020-03-30 13:46
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Please see the issue linked in https://github.com/ionic-team/ionic/issues/20906#issuecomment-605667423 for a temporary workaround.

**Closed by liamdebeasi** 2020-03-30 13:46 UTC
Labels: triage
