### ISSUE TITLE
Tabindex is getting set on both ion-input and the native input

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic#7178] opened 2016-07-03 10:28 UTC
Hi,

i have 2 problems with ion-input.
First the tabindex gets not only set on the wrapped input but also on the ion-input.
These 2 (redundant) tabindex's break form navigation in browsers.

second the angular form validation classes are not set on the wrapped input field, therefore
form validation is not working at all

**Comment by jgw96** [comment] 2016-07-03 13:04
Hello, thanks for opening an issue with us! Would you be able to provide a plunker that demonstrates this issue? Thanks for using Ionic!

**Comment by jgw96** [comment] 2016-07-07 19:23
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by nickwinger** [comment] 2016-07-08 15:20
just because i don't provide a plunkr in time, does not mean you have a bug here

**Comment by nickwinger** [comment] 2016-07-08 15:20
as you can see in this plunkr:
http://plnkr.co/edit/KwRq17cclcrGIM3EMd8y?p=preview

the tabindex gets set on the ion-input tag AND on the input, it should only be on the input.
This is important for ProgesiveWebApp with tab/keyboard support

**Comment by penrillian-chrisa** [comment] 2016-09-21 16:30
+1

**Comment by brandyscarney** [comment] 2017-01-24 23:23
I confirmed the `tabindex` is an issue still. However, the form classes should be getting set correctly on `ion-item`, `ion-input` and `input`.

**Closed** 2017-06-12 20:50 UTC
Labels: navigation, v2
