### ISSUE TITLE
Ionic 3 breaks back button

### ISSUE THREAD

**Issue by shawnlan** [ionic-team/ionic#11698] opened 2017-05-17 01:15 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

This bug appears on both browser and android using "back" button.

If you push a lazy-loaded page with custom data like this:

`this.navCtrl.push('ListPage', { title: 'abc', id: 123 });`

Using back button to navigate back to this page causes a re-create without custom data, thus breaking this page.

**Comment by jgw96** [comment] 2017-05-17 14:17
Thanks, we will look into this.

**Comment by shawnlan** [comment] 2017-05-17 16:58
With more testing, I found using back button also breaks the navigation stack. On Ionic 2, using back button basically just pops one page, same as clicking the "arrow" on the title bar.

On Ionic 3 this is not the case anymore. Back button produces weird navigation behaviors. This is especially an issue on Android since back button is often used.

Maybe a temporary solution would be having an option to use lazy loading without changing URLs back and forth?

**Comment by emin93** [comment] 2017-05-24 12:48
I can reproduce the issue, but also didn't find a workaround yet.

**Comment by shawnlan** [comment] 2017-05-28 20:01
I tested it again on Android. Now "back" button doesn't change the URLs, thus not breaking the pages. Interesting. I don't remember changing anything.

**Comment by jgw96** [comment] 2017-06-05 16:15
Hello! After further review, I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11469

**Closed by jgw96** 2017-06-05 16:15 UTC
Labels: v3
