### ISSUE TITLE
tabsPlacement returns undefined on default

### ISSUE THREAD

**Issue by prantikv** [ionic-team/ionic#12874] opened 2017-09-13 05:56 UTC
**Ionic version:**  (check one with "x")
[x] **3.9.2**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

`undefined` is retuned when `tabsPlacement` property is accessed on the tabs component istance

**Expected behavior:**

Should return string 'top' or 'bottom'

**Steps to reproduce:**
Create a new app with the tabs template and 

Use the following code in the template

```
<ion-tabs #myTabs>
  <ion-tab [root]="tab1Root"></ion-tab>
  <ion-tab [root]="tab2Root"></ion-tab>
  <ion-tab [root]="tab3Root"></ion-tab>
</ion-tabs>
```
Then in the component we are trying to get the tapPlacment as follows

```
export class TabsPage {

@ViewChild('myTabs') tabRef: Tabs;

ionViewDidEnter() {
  console.log(this.tabRef.tabsPlacement);
 }
}
```

**This only happens when tabsPlacement is not set at all, so the default is not fetched. Also, setting the tabsPlacement in app config in app.module. ts returs undefined as well.**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.4
    Ionic Framework    : ionic-angular 3.6.1

System:

    Node : v6.10.1
    npm  : 5.3.0
    OS   : Windows 10

```

**Comment by kensodemann** [comment] 2017-09-13 21:42
Hello! Thank you for opening an issue with us!

This isn't really a bug. `tabsPlacement` is an `@Input()` parameter (one-way) that allows you to specify the placement. It isn't really something that is otherwise set. 

The code this does the functional equivalent of: `Element.setAttribute('tabsplacement', tabsPlacement || 'bottom');`, so the default is bottom if the `tabsPlacement` input is not set (which you can see by having a look at the DOM).

Is there a reason you need to see this value in the code?

If there is a reason, I can move this over to the "feature requests" repo to provide a `getTabsPlacement()` or some such thing to the API (that would have to be determined at implementation time).

Thank you for using Ionic

**Comment by prantikv** [comment] 2017-09-14 03:04
Hey @kensodemann  

 Thanks for the detailed answer. I wanted to toggle the position of the tab bar based on user input. For that, I need the current position.

Can you let me know if toggling is possible or not?

Thanks

**Comment by kensodemann** [comment] 2017-09-18 22:18
Looking at the code it appears that `tabPlacement` is checked when the tabs control is first constructed. I created a sample application to prove that out.

I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Perhaps someone has done this in a way I am not familiar with.

You are also free to open a feature request and it will be evaluated for potential inclusion in a future version of Ionic.

I am going to close this issue however, as it appears that the framework is working as intended with regard to this.

Thanks for using Ionic!

**Closed by kensodemann** 2017-09-18 22:18 UTC
Labels: needs reply
