### ISSUE TITLE
Searchbar - Keyboard close will push tabs up.

### ISSUE THREAD

**Issue by kabus202** [ionic-team/ionic#11291] opened 2017-04-20 14:29 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

If you click outside the keyboard then tabs will push up. 

![searchbar](https://cloud.githubusercontent.com/assets/5297717/25235447/7045a79a-25e5-11e7-8014-8362ffc2a3fe.gif)

**Expected behavior:**

Same as the close behavior via KeyboardAccessoryBar

**Steps to reproduce:**

**Related code:**

```
    <ion-searchbar placeholder="Zoeken op kenteken/titel/bj/notitie" (ionClear)="getItems($event)" (input)="getItems($event)"></ion-searchbar>

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```
 Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v6.9.4
    Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by jgw96** [comment] 2017-04-20 14:37
Hello, thanks for using Ionic! We will look into this.

**Comment by Manduro** [comment] 2017-04-21 13:36
Duplicate of #10552 ;)

**Closed** 2017-06-12 20:50 UTC
Labels: keyboard, v2
