### ISSUE TITLE
bug: hardware back button in ionic 4 

### ISSUE THREAD

**Issue by kushalkulle** [ionic-team/ionic#18140] opened 2019-04-26 06:55 UTC
this.platform.backButton.subscribeWithPriority(0 ,() => {
        // close action sheet
        this.routerOutlets.forEach((outlet: IonRouterOutlet) => {
          this.appExit();
            if (outlet && outlet.canGoBack()) {
                outlet.pop();
            } 
        });
    });

async appExit(){
    const alert = await this.alertController.create({
      header: 'App termination',
      message: 'Do you want to close the app?',
      buttons: [{
        text: 'Cancel',
        role: 'cancel',
        handler: () => {
          console.log('Application exit prevented!');
        }
      }, {
        text: 'Close App',
        handler: () => {
          navigator['app'].exitApp(); // Close this application
        }
      }]
    });
    return await alert.present();
  }

Apart from this, tried with other ways from Stackoverflow and other forums too. Still unable to solve. Hope I get support from Ionic team ASAP.

These dependencies are using in my applications.

"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/fire": "^5.1.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/app-minimize": "^5.5.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/google-plus": "^5.3.0",
    "@ionic-native/network": "^5.5.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.0.0",
    "@ionic/storage": "^2.2.0",
    "cordova": "^9.0.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-googleplus": "7.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.4",
    "firebase": "^5.9.2",
    "moment": "^2.24.0",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.29"
  }

**Comment by liamdebeasi** [comment] 2019-04-26 12:47
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16611. Note: This is a collection of multiple issues, but the issue you describe is under the `Cordova/App` section.

Thanks!

**Closed by liamdebeasi** 2019-04-26 12:47 UTC
Labels: triage
