### ISSUE TITLE
ion-input placeholder text jumpy/bounces

### ISSUE THREAD

**Issue by ShannonSimpson** [ionic-team/ionic#15895] opened 2018-10-08 23:27 UTC
# Bug Report

**Ionic Info**
Runing `ionic info` from a terminal/cmd prompt outputs:
```
cli packages: (/home/docker-ima/.config/yarn/global/node_modules)

    @ionic/cli-plugin-proxy : 1.5.8
    @ionic/cli-utils        : 1.19.2
    ionic (Ionic CLI)       : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.12.0
    npm               : 6.4.1
    OS                : Linux 4.9

Environment Variables:

    ANDROID_HOME     : /home/docker-ima/androidsdk
    HTTP_PROXY       : <work proxy>
    http_proxy       : <work proxy>
    HTTPS_PROXY      : <work proxy>
    https_proxy      : <work proxy>
    IONIC_HTTP_PROXY : not set
    PROXY            : not set
    proxy            : not set

Misc:

    backend : pro
```

**Describe the Bug**
The bug deals with the placement text in the ion-input component. The placement text jumps when tapped on either device or emulator. 

**Steps to Reproduce**
`ionic start InputScrollJank blank` 
cd InputScrollJank
Edit ./src/pages/home/home.html to include an ion-input. 
      example: 
            ```<ion-item no-padding no-line>
                      <ion-label stacked>IDENTIFICATION NUMBER</ion-label>
                      <ion-input formControlName="vinInputFormControl" placeholder="Enter VIN" clearInput> 
                      </ion-input>
                  </ion-item>```
ionic run ios --device
tap on the ion-input. This must be done on a device or emulator. 
Your placeholder text will flicker/jump.

**Related Code**
Related code may come later if needed.

**Expected Behavior**
It would be expected that the placeholder would be visually smooth as in the browser. 

**Additional Context**
I have viewed Issue #10272 as well as Issue #10257 (IOS setFocus on input make screen jump). Both of which have been closed, but neither match this issue. #10272 matches closely, but the issues are slightly different.

Also, I've uploaded a screen recording of the problem [here](https://github.com/ShannonSimpson/jumpytext/blob/master/jumpy_placeholder_text.mp4)

**Comment by brandyscarney** [comment] 2018-10-09 16:43
Thanks for the issue! Going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15888.

**Comment by ShannonSimpson** [comment] 2018-10-09 21:45
I see #15888 and it is not the same issue. Please note that the issue I am explaining is the jumping action of the placeholder text due to the keyboard popping up.

**Comment by EdwinRikkers** [comment] 2018-10-22 06:06
+1

**Closed** 2018-11-03 00:35 UTC
