### ISSUE TITLE
ion-select prevent url changing when interface is popover

### ISSUE THREAD

**Issue by ChezRD** [ionic-team/ionic#11612] opened 2017-05-11 15:08 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When popover or alert opens we can pass updateUrl: false to prevent url change in browser, but when dismiss called url updates to #/ always

**Expected behavior:**
dismiss cannot change url in browser 

**Steps to reproduce:**
No working demo but it uses IonicPage with segments and popovers in ion-select

**Related code:**

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.3.1 
Ionic Framework Version: 3.1.1-201705081802
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.1

```

**Comment by jgw96** [comment] 2017-05-11 16:27
Hello, thanks for using Ionic. Could you post a repo we could use to reproduce this issue?

**Comment by ChezRD** [comment] 2017-05-13 17:37
@jgw96 here is a repo with error behavior https://github.com/ChezRD/Ionic3-select-issue if there are questions feel free to re ask what do i mean by this issue

**Comment by ChezRD** [comment] 2017-05-14 14:02
@jgw96 actually all overlays needs navOptions passed into dismiss methods one way or another to have an ability to not change url in browser address bar or on the other half modals could have own urls via IonicPage deeplinking

**Comment by ChezRD** [comment] 2017-06-07 10:41
@jgw96 any news on this?

**Comment by jgw96** [comment] 2017-06-19 19:49
Update on this issue: We are currently doing a big overhaul of our navController and how it works with lazy loading. We are also working with the angular team on improving how code splitting works with Angular. We are hoping to have these fixes in the next release if testing of it goes well.

**Comment by kensodemann** [comment] 2018-01-03 03:23
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 03:23 UTC
Labels: v2

**Comment by ChezRD** [comment] 2018-02-15 15:24
@kensodemann there was no activity because of your team ignorance.
