### ISSUE TITLE
Ionic 4 doesn't work on Android emulator

### ISSUE THREAD

**Issue by sirarthurnell** [ionic-team/ionic#15542] opened 2018-09-10 18:08 UTC
# Bug Report

**Ionic Info**
```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/another/Android/Sdk)
   NodeJS            : v10.10.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.15

```

**Describe the Bug**
I tried to run the app on an Android emulator and got a white screen.

**Steps to Reproduce**
Generate a new project with 

`ionic start test4 blank --type=angular`

After that, I execute:

`ionic cordova run android`

**Related Code**
I didn't change anything. It was just the code generated by the ionic cli.

**Expected Behavior**
At least, the being able to see the default home page generated by ionic cli.

**Additional Context**
I tried with two different emulators, Nougat and Mashmallow, on Linux (Ubuntu 18.04) and Windows 10 Professional, on two different computers. I have a working Android development environment on both. In fact, I tried to deploy the app to my Android phone too and it worked, not totally though, because it obscured the Android's status bar, making it black and almost totally opaque, I could barely see the clock and WIFI icons.

I tried doing the same with a just-generated Ionic 3 project and it worked perfectly on the emulators and on my phone.

**Comment by yuankunluo** [comment] 2018-09-11 12:43
if you check out the console log, there will be a syntax error.
This is a bug caused by ES5 , ES6 code, that ionic generated.
Android devices with outdated Android System View can't render this view.
We are waiting for the solution.
Try your code on Android Device or Emulator with Android OS Version 7.1.0 above!

**Comment by yuankunluo** [comment] 2018-09-11 12:45
#15438

**Comment by mhartington** [comment] 2018-09-11 13:51
Closing as a duplicate of #15438

**Closed by mhartington** 2018-09-11 13:51 UTC
Labels: triage

**Comment by Riyaz0001** [comment] 2018-10-09 06:39
> if you check out the console log, there will be a syntax error.
> This is a bug caused by ES5, ES6 code, that ionic generated.
> Android devices with outdated Android System View can't render this view.
> We are waiting for the solution.
> Try your code on Android Device or Emulator with Android OS Version 7.1.0 above!

Your Right, I am trying to Android 8.1, it's work. but doesn't work for android 5.0, 5.1, 6.0 version.
