### ISSUE TITLE
Floating ion-label overlay ion-select value

### ISSUE THREAD

**Issue by eulerchavez** [ionic-team/ionic#17851] opened 2019-03-21 21:30 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Floating ion-label overlay ion-select value

**Expected behavior:**
Floating ion-label should not overlay ion-select value

![image](https://user-images.githubusercontent.com/18647380/54786094-86a7ff80-4bed-11e9-83ba-37bf9fd90f08.png)

**Related code:**

![image](https://user-images.githubusercontent.com/18647380/54786251-06ce6500-4bee-11e9-936f-7bd316fa5eaf.png)

![image](https://user-images.githubusercontent.com/18647380/54786270-1057cd00-4bee-11e9-9835-f40c1806e3b7.png)

**Ionic info:**

![image](https://user-images.githubusercontent.com/18647380/54786195-dd153e00-4bed-11e9-8d50-efa210f58210.png)

**Comment by liamdebeasi** [comment] 2019-03-22 13:01
Hi there,

Thanks for the issue. What browser/version are you seeing this issue on? Additionally, which version of Ionic are you using?

Thanks!

**Comment by eulerchavez** [comment] 2019-03-22 14:53
> Hi there,
> 
> Thanks for the issue. What browser/version are you seeing this issue on? Additionally, which version of Ionic are you using?
> 
> Thanks!

Hi,

I'm using Google Chrome, Version 73.0.3683.86 (64 bits) and Ionic 4.1.2

Greetings

**Comment by liamdebeasi** [comment] 2019-03-22 20:21
Hi there,

Thanks for the follow up! would you be able to provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by mburger81** [comment] 2019-03-23 18:59
Hello we have the same issue! What you habe to say the problem is only on init with pres selecting select. For example on a editing form mask. In our opinion this is a timing problem with async select loading.

**Comment by mburger81** [comment] 2019-03-23 19:05
Hello we have the same issue! What you habe to say the problem is only on init with pres selecting select. For example on a editing form mask. In our opinion this is a timing problem with async select loading.

If you are in this situation you can select manually a value and after that the floating label is moving on top

**Comment by mburger81** [comment] 2019-03-25 14:18
This bug can be related to #15716 and could be fixed with #17860

**Closed** 2019-03-26 15:29 UTC
Labels: package: core, type: bug

**Comment by liamdebeasi** [comment] 2019-03-26 15:31
Hi there,

This issue has been resolved and will be available in the next release of Ionic. I have pushed a nightly build in case you would like to try it out and provide feedback. (`npm i @ionic/core@dev @ionic/angular@dev`)

Thanks for your patience as we worked to resolve this issue!

**Comment by mburger81** [comment] 2019-03-28 14:57
Hello,
I can confirm, using latest @ionic/angular@dev, for us the floating label issue seems to be resolved.

thx!

**Comment by mburger81** [comment] 2019-04-04 14:38
There is a similar issue #17559
