### ISSUE TITLE
swipeback angular routing

### ISSUE THREAD

**Issue by GISerWYJ** [ionic-team/ionic#15636] opened 2018-09-18 00:42 UTC
Ionic4 beta.Can't swipe to go back in angular routing mode. Is it a bug?

**Comment by mhartington** [comment] 2018-09-18 14:46
Closing as duplicate of https://github.com/ionic-team/ionic/issues/15018.

This is still being worked on. 
There's a few bigger priority items to take care of first

**Closed by mhartington** 2018-09-18 14:46 UTC
Labels: triage
