### ISSUE TITLE
bug: Blank screen with Ionic 4.7.4 on Android 5, 5.1 and 6

### ISSUE THREAD

**Issue by nuagoz** [ionic-team/ionic#19048] opened 2019-08-08 14:18 UTC
# Bug Report

**Ionic version:**

[x] **4.7.4**

**Current behavior:**

On Android 5, 5.1 and 6 (API 21, 22 and 23) the application doesn't start. It only displays a blank screen after the splashscreen.

Console output :
![bug1](https://user-images.githubusercontent.com/17503751/62710013-cfbeeb80-b9f6-11e9-8772-4c13c872083b.PNG)

Main.js (line 694) : 
![bug2](https://user-images.githubusercontent.com/17503751/62710020-d2b9dc00-b9f6-11e9-9323-6a5be50dd5f9.PNG)

![bug3](https://user-images.githubusercontent.com/17503751/62710669-f3cefc80-b9f7-11e9-9272-9d778687c75d.PNG)

**Expected behavior:**
The application starts and displays the home page on Android 5, 5.1 and 6.

**Steps to reproduce:**

_**1. Create a new Ionic project**_
`ionic start app sidemenu`

_**2. Build this project for Android**_
`ionic cordova build android`

_**3. Install the `.apk` on an Android 5, 5.1 or 6 emulator**_

_**4. Launch the app**_

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)
```

**Comment by liamdebeasi** [comment] 2019-08-09 13:00
Thanks for the issue. Are you able to reproduce this on a physical device? We do not recommend testing on the Android emulator as they ship with older versions of the WebView that are not updatable (as opposed to physical devices, which typically have autoupdating webviews).

**Comment by Muromi-Rikka** [comment] 2019-08-15 02:49
What version of the latest version of ionic support to webview

**Comment by rafalschmidt97** [comment] 2019-08-15 09:46
You may have uncomment some polyfills. I had same problem someday but I don't care about users with Android 5 that much.

**Comment by Muromi-Rikka** [comment] 2019-08-15 10:09
@nuagoz You can lower the @ionic/angular version to 4.1.2.

**Comment by JeongJun-Lee** [comment] 2019-08-15 14:02
same here

![image](https://user-images.githubusercontent.com/11474775/63097925-18dce580-bf8b-11e9-92d2-822e3cd5a725.png)

**Comment by liamdebeasi** [comment] 2019-08-15 14:06
Thanks for the follow ups. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18939.

We are aware of this issue and are working on a fix. You can follow the thread I linked to above for updates.

Thanks!

**Closed by liamdebeasi** 2019-08-15 14:06 UTC
Labels: triage
