### ISSUE TITLE
bug: Focus input in a ion-alert don't trigger ion-app rezise

### ISSUE THREAD

**Issue by 5im0n** [ionic-team/ionic#19374] opened 2019-09-17 09:11 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Mainly on Android (Cordova and web)
First create a classic `ion-alert` with input text inside and open it.

```
const alert = await this.alertCtrl.create({
  buttons: [ 'Ok', 'Cancel'],
  header: 'Header of the ion-alert',
  inputs: [
     {
       name: 'email',
       placeholder: 'Enter your email',
       type: 'email',
    },
  ],
 message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
});
await alert.present();
```
![Screenshot_20190917-105545](https://user-images.githubusercontent.com/659811/65027099-095e0d00-d93a-11e9-89cf-9523516bc160.png)

> You can see that the `ion-app` has a height of 568px

When you focus the input, the keyboard appear, but the `ion-app` is not resize, so you can not see what you write.

![Screenshot_20190917-105552](https://user-images.githubusercontent.com/659811/65027355-7d001a00-d93a-11e9-9144-e6595664462f.png)
>The `ion-app` has always a height of 568px

**Expected behavior:**
The `ion-app` element should be correctly resized when alert input is focused.
I create a quick hack to demonstrate that reflow the `ion-app` fix the issue:

```
const alert = await this.alertCtrl.create({
  buttons: [ 'Ok', 'Cancel'],
  header: 'Header of the ion-alert',
  inputs: [
     {
       id: 'alert-input',
       name: 'email',
       placeholder: 'Enter your email',
       type: 'email',
    },
  ],
 message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
});
await alert.present();

// Hack to reflow ion-app
const inputEl = document.getElementById('alert-input');
const appEl = document.getElementsByTagName('ion-app')[0];
inputEl.addEventListener('focus', () => { appEl.style.display = 'block'; });
inputEl.addEventListener('blur', () => { appEl.style.display = 'flex'; });
```

![Screenshot_20190917-110533](https://user-images.githubusercontent.com/659811/65027860-5c848f80-d93b-11e9-99d5-63bea24d827d.png)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\Simon\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   Android SDK Tools : 26.0.2 (C:\Users\Simon\AppData\Local\Android\sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.1-next.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-09-17 12:47
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

This was determined to be a bug in Chrome 76 and has since been fixed in Chrome 77.

**Closed by liamdebeasi** 2019-09-17 12:47 UTC
Labels: triage
