### ISSUE TITLE
Cannot style ion-select ion-popover unless you set ViewEncapsulation.None 

### ISSUE THREAD

**Issue by welshcathy** [ionic-team/ionic#17453] opened 2019-02-10 12:04 UTC
# Bug Report

**Ionic version:**
[x] **4.0.1**

**Current behavior:**
I have a form with ion-select using interface popover. 
I assign a custom class using interface options.
My custom styles are not applied to the select popover unless I turn off View Encapsulation.

**Expected behavior:**
My custom styles should be applied with View Encapsulation active.
This comment makes me think that it used to work 
https://github.com/ionic-team/ionic/issues/15711#issuecomment-449192486

**Steps to reproduce:**
Use the related code below.
Tap to select an option on the home page. The popup is pink.
By default I have set ViewEncapsulation.None in home.page.ts.
Comment that line out and reload app.
Tap to select an option on the home page. The popup is white.

**Related code:**
https://github.com/welshcathy/ionic-4-popover

**Ionic info:** 
```
Ionic:
 
   ionic (Ionic CLI)             : 4.10.2 (/Users/welshcathy/.nvm/versions/node/v11.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0
 
System:
 
   NodeJS : v11.6.0 (/Users/welshcathy/.nvm/versions/node/v11.6.0/bin/node)
   npm    : 6.7.0
   OS     : macOS High Sierra
```

**Comment by lucasbasquerotto** [comment] 2019-02-13 12:23
@welshcathy From what I know, when you use Angular encapsulation you can style your component and the components directly defined in it (in your case, the `home.page.ts`), so you could style `ion-select` and `ion-select-option` for example, but not subcomponents of these components (that are created when you create them).

If you run with `ViewEncapsulated.Emulated` (I think is the default) you should see that your css will have some classes `ng_xxxxx` in it so only components with those casses will be able to be styled. When you don't use `ViewEncapsulated` (that is, `ViewEncapsulated.None`) the css will be applied as is (so it will style subcomponents and so on).

You could use some angular specific syntax in the css to pierce the DOM, like `::ng-deep`. In you case, it would be (you can see that `app-popover` is the css class applied to the popover, so it's not in your html):

```css
::ng-deep .app-popover {
  ion-select-popover {
    background: pink;

    ion-list,
    ion-list-header,
    ion-item,
    ion-radio-group {
      --background: transparent;
      background: transparent;
    }
  }
}
```

I don't know now (haven't tested) if the popover is inside your component (or if the popover element will be rendered outside it, in which case the above may not work and you may need to include it in a global css file or make a custom popover and call it instead).

Have in mind that `::ng-deep` is **deprecated**, but from what I know **there is no alternative**:

https://github.com/angular/angular/issues/17867

You can also see:

https://stackoverflow.com/a/49308475/4850646

**Comment by Sunny41** [comment] 2019-08-15 10:17
Hi, 
i kinda have the same problem. encapsulation: VeiweEncapsulation.NONE worked for me, but i'm getting this note from the terminal: 
ERROR in ../auth.page.ts(4,36): error TS2551: Property 'NONE' does not exist on type 'typeof ViewEncapsulation'. Did you mean 'None'?

If type in now "None" instead of "NONE" it doesn't work.

**Comment by liamdebeasi** [comment] 2020-05-20 13:13
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. By default all Angular components are scoped to the host element (the component itself). Ionic components like `ion-popover` and `ion-alert` are placed in the DOM outside of the host element.

What this means is if you want to style your `ion-popover`, you will need to place the styles in your `global.scss` file. Placing the styles in `home.page.scss` will have no effect since those styles are going to be scoped to the home page. Thanks!

**Closed by liamdebeasi** 2020-05-20 13:13 UTC
Labels: triage
