### ISSUE TITLE
Ionic 5 doesn't support Android 5 and Android 6

### ISSUE THREAD

**Issue by ThomasKientz** [ionic-team/ionic#21399] opened 2020-05-29 13:00 UTC
The documentations states that [Ionic fully supports Android 5+](https://ionicframework.com/docs/reference/browser-support) but It doesn't see https://github.com/ionic-team/ionic/issues/17781

**Comment by liamdebeasi** [comment] 2020-05-29 13:14
Thanks for the issue. Please see my response in https://github.com/ionic-team/ionic/issues/17781#issuecomment-635963919. Closing as a duplicate of https://github.com/ionic-team/ionic/issues/17781 since the underlying issue is the same.

**Closed by liamdebeasi** 2020-05-29 13:14 UTC
Labels: triage
