### ISSUE TITLE
Bug: Subscriptions to tab events do not trigger.

### ISSUE THREAD

**Issue by dtaalbers** [ionic-team/ionic#15189] opened 2018-08-15 16:09 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5

System:

   Android SDK Tools : 25.2.5
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.9.4 (/Users/dtaalbers/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /usr/local/Cellar/android-sdk/24.4.1_1
```

**Describe the Bug**
Subscription to the `ionChange` event (or any of the other events) doesn't  trigger.

**Related Code**
My view

```
<ion-tabs #tabs [tabbarHidden]="!isAuthenticated" color="primary">
    <ion-tab label="Home" icon="home" href="/tabs/(home:home)">
        <ion-router-outlet name="home"></ion-router-outlet>
    </ion-tab>
    <ion-tab label="workspace" icon="home" href="/tabs/(workspace:workspace)">
        <ion-router-outlet name="workspace"></ion-router-outlet>
    </ion-tab>
    <ion-tab label="login" icon="home" href="/tabs/(login:login)">
        <ion-router-outlet name="login"></ion-router-outlet>
    </ion-tab>
</ion-tabs>
```

My tabs viewmodel. 

```
export class TabsPage implements OnInit, OnDestroy, AfterViewInit {

    @ViewChild('tabs', { read: Tabs}) private tabs: Tabs;

    private isAuthenticated: boolean;
    private subscription: Subscription;

    constructor(
        private navController: NavController,
        private authService: AuthenticationService
    ) { }

    public async ngOnInit(): Promise<void> {
        this.isAuthenticated = await this.authService.isAuthenticated();
        this.subscription = this.tabs.ionChange.subscribe(async (x) => {
            this.isAuthenticated = await this.authService.isAuthenticated();
        });
    }
}
```

**Expected Behavior**
I expect the to be able to bind to the `ionChange` (or other) event(s).

@brandyscarney

**Comment by ptitjes** [comment] 2018-08-21 13:45
I believe this is due to https://github.com/ionic-team/stencil/issues/1025. (My proposal PR: https://github.com/ionic-team/stencil/pull/1026).

The problem is the same here with `IonContent.ionScroll` here: https://github.com/ionic-team/ionic/issues/15160.

**Comment by manucorporat** [comment] 2018-08-24 02:35
Thanks for reporting this issue! it's already fixed in master of stencil: 
https://github.com/ionic-team/stencil/commit/dabcf5ee74cb14c2a7a9f4801ee64b3f20fd48e5

Next version of IOnic will have this fixed!

**Closed by manucorporat** 2018-08-24 02:35 UTC
