### ISSUE TITLE
bug: Browser status bars not hidden on scroll on mobile and can't zoom

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#19543] opened 2019-10-03 17:55 UTC
# Bug Report

**Ionic version:**

[x] **4.8.1**

**Current behavior:**

Hi. When deploy my Ionic 4 app on the browser to be used as a normal website, on mobile the browser can't recognize the scroll of the content. Seems like the page is not scrolling, so for example on iOS the navigation footer and status bar of Safari are not hidden. Same for the other phones.
Also, the pinch to zoom doest work

**Expected behavior:**

The browser has to catch the on scroll event and hide the status bars.

**Steps to reproduce:**

You can try it on my beta website: https://beta.roomlessrent.com visiting in on mobile

**Related code:**

You can try it on my beta website: https://beta.roomlessrent.com visiting in on mobile
What i just use is, on each page, the <ion-content>, eg:

```
<ion-content></ion-content>

```

**Other information:**

Some problem: https://forum.ionicframework.com/t/ionic-in-web-hide-browser-address-bar/164970/8 
**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.803.2
   @angular-devkit/schematics    : 8.3.2
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61



```

**Comment by ASHFAQPATWARI** [comment] 2019-10-04 10:16
Having the same issue with v4 and had it in V3 as well

**Comment by liamdebeasi** [comment] 2019-10-04 13:17
Thanks for the issue. Ionic does not do its scrolling on the `body`, it does it inside of the `ion-content`. iOS Safari requires scrolling on the `body` for the header/footer to collapse.

Can you describe the pinch to zoom issue? I tried it out on your website, and it worked fine on my iPhone.

**Comment by ilprima** [comment] 2019-10-04 13:53
Does exist a way to handle it? It’s a very big problem for me, because I would like to use my ionic app for apps and for the website (desktop+mobile).
Does exist a workaround to have the scroll also on the body just for browser?

The mobile website now seems like a old fashion website with that limitation. I found a lot of threads opened about this problem. I love ionic and I decided to start my project with it and not with angular because with it is possible to have apps and website with 1 code, but it’s not totally true, the desktop website it’s good as an angular project but the mobile one is not good enough to use it in production just due to this scroll problem because the available portion of the screen it’s too little because of browser status and navigation bars + app footer or/and header.

About the zoom problem, It’s correlated to the same issue: the browser can’t detect the scroll or zoom in/out gestures because the ion-content controls the scroll and zoom.

Thank you

**Comment by liamdebeasi** [comment] 2019-10-04 13:58
We do not do scrolling on the `body` because of some long standing issue in iOS Safari. We are investigating it again as some of those issues may have been fixed, but do not have anything more to share at this point.

Regarding the zoom issue, can you provide steps to reproduce? Like I said previously, I am not seeing any issues with zooming on your website on iOS.

**Comment by ilprima** [comment] 2019-10-04 14:28
Here a video with these problems: scroll not detected by browser, can’t tap on top to scroll top and can’t zoom.

https://ibb.co/GHYr4NL

These 3 problems (I think they are all correlated) reduce the user experience a lot

**Comment by liamdebeasi** [comment] 2019-10-04 15:03
Yes, I think those seem to be related to the fact that we do not do scrolling on the `body` element. 

Unfortunately, we do not have any workarounds regarding this, and switching to scrolling on the `body` is not a quick fix (though we are investigating this change). I am going to close this issue since there are no actionable items at the moment.

**Closed by liamdebeasi** 2019-10-04 15:03 UTC
Labels: triage
