### ISSUE TITLE
v3.5.2 failed to load file://android_asset/www/build/vendor.js at system startup

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic#12351] opened 2017-07-14 04:20 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

the debug console (chrome://inspect/#devices ) displays : "Failed to load resource: net::ERR_FILE_NOT_FOUND     file://android_asset/www/build/vendor.js"  after system start-up
**Expected behavior:**

 there is no such error on before upgrade (v3.5.0)
**Steps to reproduce:**

upgrade to v3.5.2. build and run  the application by "ionic cordova run android" ,  after the apps had been downloaded to the phone and started up on the phone; open Chrome browser, enter "chrome://inspect/#devices" in the address bar, click  the application under the device, and this will open up the debug page, and you will find the error  on the first line in the Console 

**Related code:**

```
ionic cordova run android
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.0.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.4
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 

```

**Comment by jing-zhou** [comment] 2017-07-14 04:47
I attached a screen-shot  of the bug here 
![failed-loading-vendor](https://user-images.githubusercontent.com/3517418/28198682-81babeb2-6892-11e7-98fe-bfcbc488239e.png)

**Comment by peterpeterparker** [comment] 2017-07-14 07:58
Have you read the change log? vendor.js should be added to your index.html?

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by CoDanny** [comment] 2017-07-14 08:14
I have the same problem. The reason I get a 404 on that file is because I have added to the index.html however the build system doesn't produce the file

**Comment by peterpeterparker** [comment] 2017-07-14 08:18
@CoDanny did you update app-scripts too? could you check in node_modules that app-script 2.0.2 is correctly installed (and not a version < 2.0.0)?

**Comment by CoDanny** [comment] 2017-07-14 08:19
@peterpeterparker my ```ionic info```

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.2

System:

    Node       : v8.1.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8 
    npm        : 5.0.3 
```

**Comment by peterpeterparker** [comment] 2017-07-14 08:25
@CoDanny oki doki, still I would check that app-script 2.0.2 is really under node_modules. I had some weird side effect after the introduction of package-lock.json, sometimes better to double check...

     cat node_modules/@ionic/app-scripts/package.json | grep version

**Comment by CoDanny** [comment] 2017-07-14 08:39
Thanks, it's right: 

```
$ cat node_modules/@ionic/app-scripts/package.json | grep version
    "type": "version",
  "version": "2.0.2"
```

**Comment by peterpeterparker** [comment] 2017-07-14 09:45
@CoDanny thx for the check, sorry that these investigation didn't solved your problem :(

**Comment by jgw96** [comment] 2017-07-14 14:10
@CoDanny , would you mind deleting your lock file and your node_modules and doing a fresh install. We have ran into nothing but issues with the lock files in npm 5, even if the lock file looks correct.

**Comment by CoDanny** [comment] 2017-07-14 14:57
@jgw96 I did that a couple of time, no change

**Comment by jgw96** [comment] 2017-07-14 15:22
@CoDanny hmmm mind sharing a repo we could reproduce this with?

**Comment by mehrad-rafigh** [comment] 2017-07-17 08:40
Hi guys. I am experiencing the same issue here. I tried updating from ionic v2 to v3 and literally everything exploded. I think I managed to go through every changelog and applied the changes. 
It didn't help. I deleted everything and reinstalled from scratch.  (Even the plugins)

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.7.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : 1.9.1
    ios-sim    : 6.0.0
    npm        : 4.2.0
```

**Comment by Sampath-Lokuge** [comment] 2017-07-17 08:59
@mehrad-rafigh Can you show your `package.json` file?

**Comment by mehrad-rafigh** [comment] 2017-07-17 11:01
@Sampath-Lokuge there you go

```
{
    "name": "ionic-hello-world",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "clean:install": "rimraf node_modules/ platforms/ plugins/ && npm install",
        "lint": "ionic-app-scripts lint",
        "build": "ionic-app-scripts build"
    },
    "dependencies": {
        "@angular/animations": "4.1.3",
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@angular/platform-server": "4.1.3",
        "@ionic-native/app-version": "3.14.0",
        "@ionic-native/barcode-scanner": "3.14.0",
        "@ionic-native/core": "3.14.0",
        "@ionic-native/device": "3.14.0",
        "@ionic-native/diagnostic": "3.14.0",
        "@ionic-native/geolocation": "3.14.0",
        "@ionic-native/launch-navigator": "3.14.0",
        "@ionic-native/splash-screen": "3.14.0",
        "@ionic-native/status-bar": "3.14.0",
        "@ionic/storage": "2.0.1",
        "@ngx-translate/core": "7.0.0",
        "@ngx-translate/http-loader": "0.1.0",
        "cordova-android": "^6.2.3",
        "cordova-browser": "^4.1.0",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-actionsheet": "^2.3.3",
        "cordova-plugin-app-version": "^0.1.9",
        "cordova-plugin-compat": "^1.1.0",
        "cordova-plugin-console": "^1.0.7",
        "cordova-plugin-crosswalk-webview": "^2.3.0",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-dialogs": "^1.3.3",
        "cordova-plugin-geolocation": "^2.4.3",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.3",
        "cordova-plugin-whitelist": "^1.3.2",
        "cordova-plugin-wkwebview-engine": "git+https://github.com/driftyco/cordova-plugin-wkwebview-engine.git#4221015eb3f309fe593a7d81205b691e27088743",
        "ionic-angular": "3.5.3",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "phonegap-plugin-barcodescanner": "^6.0.7",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.0.1",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.2",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "@types/jasmine": "2.2.34",
        "jasmine-core": "2.5.2",
        "karma": "1.4.0",
        "karma-chrome-launcher": "2.0.0",
        "karma-jasmine": "1.1.0",
        "karma-typescript": "2.1.5",
        "rimraf": "2.6.1",
        "rollup-plugin-replace": "^1.1.1",
        "typescript": "2.3.4"
    },
    "cordovaPlugins": [
        "cordova-plugin-console",
        "cordova-plugin-whitelist",
        "ionic-plugin-keyboard",
        "cordova-plugin-screen-orientation"
    ],
    "cordovaPlatforms": [
        {
            "platform": "android",
            "version": "",
            "locator": "android"
        },
        {
            "platform": "ios",
            "version": "",
            "locator": "ios"
        }
    ],
    "description": "bestellbar-hybrid2: An Ionic project",
    "config": {
        "ionic_rollup": "./config/rollup.config.js",
        "ionic_bundler": "webpack",
        "ionic_source_map_type": "source-map"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-wkwebview-engine": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-console": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-geolocation": {
                "GEOLOCATION_USAGE_DESCRIPTION": " "
            },
            "phonegap-plugin-barcodescanner": {
                "CAMERA_USAGE_DESCRIPTION": " "
            },
            "cordova-plugin-crosswalk-webview": {
                "XWALK_VERSION": "23+",
                "XWALK_LITEVERSION": "xwalk_core_library_canary:17+",
                "XWALK_COMMANDLINE": "--disable-pull-to-refresh-effect",
                "XWALK_MODE": "embedded",
                "XWALK_MULTIPLEAPK": "true"
            },
            "cordova-plugin-app-version": {},
            "uk.co.workingedge.phonegap.plugin.launchnavigator": {}
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}
```

**Comment by danielsogl** [comment] 2017-07-17 11:11
@mehrad-rafigh You can check out my upgrade guide: https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-x/87516

**Comment by mehrad-rafigh** [comment] 2017-07-17 11:14
Hi @danielsogl . I actually used your guide to upgrade :/

**Comment by danielsogl** [comment] 2017-07-17 11:30
Can you downgrade to app-scripts 1.3.12 and try it again (remove the  <script src="build/vendor.js"></script>)

**Comment by mehrad-rafigh** [comment] 2017-07-17 11:55
Hi @danielsogl. I tried your suggestion and it works. Seems to me that there is some issue with app-scripts

**Comment by jgw96** [comment] 2017-07-17 16:01
@mehrad-rafigh would you mind posting a repo we could use to reproduce this? I cannot reproduce it with any of my testing apps.

**Comment by mehrad-rafigh** [comment] 2017-07-17 21:53
Hi @jgw96. Thank you for responding. Unfortunately I cannot share the repo...but...I figured out the problem. It is due to my rollup config, which replaces environment variables for our app, REST API Url and the like. So...where do I get some help about that? :(

**Comment by CoDanny** [comment] 2017-07-17 22:12
I also use a custom rollup.config.js. In case this helps I'm going to paste here:

```
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: process.env.IONIC_APP_ENTRY_POINT,

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: process.env.IONIC_OUTPUT_JS_FILE_NAME,

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs({
      include: 'node_modules/**',
      namedExports: {
        'node_modules/three/build/three.js':
        [
          'PerspectiveCamera',
          'OrthographicCamera',
          'Vector3',
          'Vector2',
          'Scene',
          'AmbientLight',
          'PointLight',
          'WebGLRenderer',
          'Matrix4',
          'MeshPhongMaterial',
          'FlatShading',
          'Mesh',
          'EventDispatcher',
          'Quaternion',
          'MOUSE',
          'DefaultLoadingManager',
          'XHRLoader',
          'BufferGeometry',
          'Geometry',
          'BufferAttribute',
          'Face3'
        ]
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};

module.exports = rollupConfig;
```

the file is at ```/scripts/rollup.config.js``` in my repo.

**Comment by jgw96** [comment] 2017-07-18 14:36
Hello, all! As this now seems to be an issue with you all's custom rollup configs I am going to close this as a support question. To get help with your rollup config's I would recommend that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Closed by jgw96** 2017-07-18 14:36 UTC
Labels: needs info, v3

**Comment by CoDanny** [comment] 2017-07-18 14:53
@jgw96 Wouldn't it be worth find out why our changes break the build and writing a migration guide for people that have done changes to these files? Changes to these files in the way we have done them is a supposedly supported feature.

**Comment by NicolasBehra** [comment] 2017-11-08 16:46
For me, the problem was that I used the wrong root path when importing json file in my code. For instance, I had to change `../../assets/i18n/en.json` to `./assets/i18n/en.json`.
With the --livereload it worked but not in --prod. But now with this changes it works.
Hope it will help!! :)
