### ISSUE TITLE
[V4-beta.7] ERROR: Can't find module interface

### ISSUE THREAD

**Issue by copaste** [ionic-team/ionic#15421] opened 2018-08-31 08:45 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.6
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/home/ynikolov/Android/Sdk/)
   NodeJS            : v10.6.0 (/usr/local/bin/node)
   npm               : 6.1.0
   OS                : Linux 4.13

```

**Describe the Bug**
I can't build my application because of this error:
```
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 695 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 98.3 kB [initial] [rendered]

ERROR in node_modules/@ionic/angular/dist/types/components/toast/toast-interface.d.ts(1,34): error TS2307: Cannot find module '../../interface'.

[ERROR] An error occurred while running subprocess ng.
```

**Steps to Reproduce**
1. update to ionic 4.0.0-beta.6 or higher
2. ionic cordova build android --release
3. ionic serve (you can see it also here, but some how after you change something in the code, application loads)

**Expected Behavior**
To be able to start my application without seeing any errors from Ionic core.

**Additional Context**
This error occurred after i upgrade my **Ionic 4-beta.4** to **beta.7**

**Comment by Majed93** [comment] 2018-09-02 17:45
I had this too, upgrading to typescript 2.9.2 seemed to fix my issue

**Comment by copaste** [comment] 2018-09-03 18:32
I'm with Typescript 2.9.2

**Comment by brandyscarney** [comment] 2018-09-04 18:27
Thanks for the issue! I'm not able to reproduce it by running any of the following commands on the [conference app](https://github.com/driftyco/ionic-conference-app):

```
ionic serve
ionic build
ionic build --prod
ionic cordova build android --release
ionic build --prod --platform=android
```

Here is my `ionic info` for the conference app:

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/Users/brandyscarney/.nvm/versions/node/v8.9.1/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.1.0, ios 4.5.0

System:

   Android SDK Tools : 25.1.7
   NodeJS            : v8.9.1 (/Users/brandyscarney/.nvm/versions/node/v8.9.1/bin/node)
   npm               : 6.1.0
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```

and the TS version:

```
$ npm ls typescript --depth=0
ionic-conference-app@0.0.0 /Users/brandyscarney/Documents/git/ionic-conference-app
└── typescript@2.9.2
```

Could you please provide an example repository that we can use to reproduce this?

**Comment by DBnR1** [comment] 2018-09-05 08:56
I am unable to re-create it with a new app.

For now I'm just adding `// @ts-ignore` to the affected files such as `..\node_modules\@ionic\angular\dist\types\components\toast\toast-interface.d.ts` and everything works.

**Comment by copaste** [comment] 2018-09-11 14:59
I don't think that this is coming from the IDE. I'm getting this error when I do `ionic serve` or `ionic cordova build`, so how the IDE is related to the build process of ionic. I have managed to fix this issue like, I changed 
`../../interface` with `@ionic/core` in `node_modules\@ionic\angular\dist\types\components\toast\toast-interface.d.ts`

**Comment by DBnR1** [comment] 2018-09-11 16:01
@copaste I mean the issue for me was, when writing AlertOptions or ToastOptions to my code, my IDE (PhpStorm) imports AlertOptions or ToastOptions from `@ionic/angular/dist/types/components`. Manually changing it to `@ionic/core` fixes it for me.

It may well be a bug in the IDE rather than any problem with Ionic, but I am still waiting to hear from the Ionic team about this, although I suspect this issue is quite low on their list of priorities at the moment.

**Comment by manucorporat** [comment] 2018-09-13 23:09
seems like a IDE issue, we are exporting this interfaces correctly in the main entry point, if someone find a better solution, please ping me, going to close the issue! Thanks

**Closed by manucorporat** 2018-09-13 23:09 UTC
Labels: triage
