### ISSUE TITLE
bug: animated: false on setupConfig doesn't work REACT BUG IONIC 5

### ISSUE THREAD

**Issue by tomjohnburton** [ionic-team/ionic#21258] opened 2020-05-10 09:23 UTC
# Bug Report

**Ionic version:**

[x] **4.x**
```
    "@ionic/core": "^5.0.7",
    "@ionic/react": "^5.0.7",
    "@ionic/react-router": "^5.0.6",
```
```
▶ ionic version
6.6.0
```
**Current behavior:**

When I set the property `animated: false` on `setupConfig` method it is ignored.

```
setupConfig({
    mode: process.env.NODE_ENV === "production" ? mode : "ios",
    refreshingSpinner: "circles",
    loadingSpinner: "dots",
    hideCaretOnScroll: true,
    swipeBackEnabled: false,
    animated: false,
});
```
**Expected behavior:**

Should disable all animation in the app

**Steps to reproduce:**

Might be only something in my app but use config as specified above.

**Comment by liamdebeasi** [comment] 2020-05-12 13:16
Glad to hear the issue is resolved. I am going to close this issue. Thanks!

**Closed by liamdebeasi** 2020-05-12 13:16 UTC
Labels: ionitron: needs reproduction
