### ISSUE TITLE
feat: Extension of existing ion-segment api

### ISSUE THREAD

**Issue by khashashin** [ionic-team/ionic#18819] opened 2019-07-17 14:11 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

There are two types of segment behavior: scrollable segments and common not scrollable segments. There is no api to control the scrolling of segments.

**Describe Preferred Solution**

Programmatically swipe segments.

**Related Code**

There is the repo with the example https://github.com/khashashin/swiping-segments

**Additional Context**

There are the Stackoverflow Question
https://stackoverflow.com/q/57047922/7986808

![jqwOx1U - Imgur](https://user-images.githubusercontent.com/17837758/61382840-c89c3600-a8ad-11e9-8553-d86d4fe334bf.gif)

**Comment by brandyscarney** [comment] 2019-07-19 18:28
Thanks for the issue, closing as a duplicate of #17804

**Closed by brandyscarney** 2019-07-19 18:28 UTC
Labels: triage
