### ISSUE TITLE
Ionic 4 RC.2: Relative routing doesn't work

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic#17206] opened 2019-01-22 12:24 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I've upgraded my Ionic 4 Beta 17 tabs application to Ionic 4 RC2. Because the tabs can now be lazy loaded, I've re-written my `tabs.router.module`.
When I now try to navigate to a page using relative routing (e.g. Ionic NavControllers `navigateForward` or Angular Routers `navigate`), routing fails with error (see this route specified below).
```
Error: Cannot match any routes. URL Segment: 'article-entity-detail/cjr7jkvt5011c0850nkm0xy6f
```

When I specify the full URL using `this.router.url` + `relativeUrl`, routing works with `navigateForward()`.

I thought `navigateForward()` was meant to support relative routing?

**Expected behavior:**

I'm able to route through the app using relative routing.

**Related code:**

```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      // Tabs
      {
        path: 'home',
        canActivate: [AuthGuard],
        children: [
          {
            path: '',
            loadChildren: '../home/home.module#HomePageModule'
          }
        ]
      }, {
        path: 'search',
        canActivate: [AuthGuard],
        children: [
          {
            path: '',
            loadChildren: '../search/search.module#SearchPageModule'
          }, {
            path: 'article-entity-detail/:id',
            loadChildren: '../article-entity-detail/article-entity-detail.module#ArticleEntityDetailPageModule'
          }, {
            path: 'article-detail/:id',
            loadChildren: '../article-detail/article-detail.module#ArticleDetailPageModule'
          }
        ]
      },
...
  }, {
    path: '',
    redirectTo: '/tabs/home',
    pathMatch: 'full',
    canActivate: [AuthGuard]
  }
];
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 2.0.0, (and 11 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.6.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

```

**Comment by manucorporat** [comment] 2019-01-22 14:01
Probably a duplicate of https://github.com/ionic-team/ionic/issues/16534

**Comment by manucorporat** [comment] 2019-01-22 14:02
However, thanks for opening an issue explaining it, it's very useful data to eventually fix the issue

**Closed by manucorporat** 2019-01-22 14:01 UTC
Labels: triage

**Comment by carstenbaumhoegger** [comment] 2019-01-22 15:48
@manucorporat thanks for linking the issue! I searched for similar issues before, but unfortunately didn't find that one, sorry!
I'll try to provide a minimal sample to reproduce the issue!
