### ISSUE TITLE
Ion-fab show behind the toolbar

### ISSUE THREAD

**Issue by MrSparklle** [ionic-team/ionic#16780] opened 2018-12-17 12:14 UTC
# Bug Report
[x] **4.0 BETA 19**

**Current behavior:**
Afer Beta 18 the ion-fab is showed behind the toolbar.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/992049/50086337-d5f02580-01e3-11e9-9b48-c08d6ecc9b97.png">

**Expected behavior:**
The fab button should appear above the toolbar like previous versions.

**Related code:**
```
<ion-header no-border>
  <ion-toolbar color="primary">
    <ion-title> <img src="assets/imgs/dark.svg" height="46" /> </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
   <ion-fab vertical="top" horizontal="end" edge slot="fixed">
    <ion-fab-button color="tertiary" (click)="navigateToEditProfile(profileId)">
      <ion-icon name="create"></ion-icon>
    </ion-fab-button>
  </ion-fab>

  <ion-list-header color="secondary" no-margin>
    <ion-label>
      <h1 text-uppercase>PERFIL</h1>
    </ion-label>
  </ion-list-header>

  <div>....</div>

</ion-content>

```

**Ionic info:** 
```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/xxx/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   NodeJS : v10.14.1 (/Users/xxx/.nvm/versions/node/v10.14.1/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
   Xcode  : Xcode 9.4 Build version 9F1027a
```

**Comment by brandyscarney** [comment] 2018-12-17 15:46
You need to have `slot="fixed"` on the `ion-fab` if you'd like it to position it over the content & toolbar. Please see the usage here: https://beta.ionicframework.com/docs/api/fab. Thanks!

**Comment by MrSparklle** [comment] 2018-12-17 16:55
@brandyscarney, please reopen:

I'm tried adding `slot="fixed"` but the problem keeps: 
`<ion-fab vertical="top" horizontal="end" slot="fixed" edge>`

I notice the problem occurs when I use `edge` directive to make the button overlapping the head. 

I also update the example provided in the first post.

**Comment by paulstelzer** [comment] 2018-12-17 17:17
@brandyscarney he is right

**beta.17 (ionic docs):**
![firefox_2018-12-17_18-16-03](https://user-images.githubusercontent.com/20501666/50103429-e629f400-0227-11e9-9a8f-765990013f36.jpg)

**current master:**
![chrome_2018-12-17_18-16-15](https://user-images.githubusercontent.com/20501666/50103419-e32f0380-0227-11e9-9fe8-b527880f042c.jpg)

**Comment by brandyscarney** [comment] 2018-12-17 19:10
I'm not sure what's going on here. I am not seeing the same thing on the preview test (on master after running a fresh `npm i`):

<img src="https://user-images.githubusercontent.com/6577830/50109189-17dd9380-0205-11e9-9dd3-217e45b67410.png" width="300px">

I also can't reproduce it in a codepen using `4.0.0-beta.19`: https://codepen.io/brandyscarney/pen/KbgKNw
I was only able to reproduce the problem when `slot="fixed"` was missing, but adding it fixed it.

Is there a specific browser this is happening on or is it on several?

**Comment by paulstelzer** [comment] 2018-12-17 19:12
@brandyscarney At me I have this behaviour on Chrome and Firefox (with compiled code) - both are behind the toolbar. And I tested in Chrome with the current master - very strange

**Comment by brandyscarney** [comment] 2018-12-17 19:23
@paulstelzer Thanks! Apparently I needed to relaunch Chrome to update it, so I can now reproduce it in latest Chrome. This helps narrow the problem down!

<img src="https://user-images.githubusercontent.com/6577830/50110002-33e23480-0207-11e9-9bca-8e69b2543d8b.png" width="300px">

**Comment by brassier** [comment] 2018-12-18 17:31
For more info, this is also appearing in Ionic 3.9.2.  It is also seen in the [Ionic Docs](https://ionicframework.com/docs/api/components/fab/FabContainer/).

**Comment by brassier** [comment] 2018-12-18 20:22
Also note that this works fine in FireFox.  Only seems to be a problem with Chrome 71.

I stink at CSS, but I attempted to break this down into a simpler example that shows something working in FireFox and not in Chrome, based on hunting and pecking the tons of styles going on in the Ionic app I have.  A (semi-embarrassing) example is below.  Again, this shows a fake FAB that appears normal in FireFox, which appears under a fake header in Chrome.  It really seems like z-index is handled differently since the 999 z-index raises the FAB to the top in FF but not in Chrome.
https://js-bjvaxt.stackblitz.io/ 

Of course there are hacks we could do to make this work again.  I'm just not convinced I have a "proper" fix in mind.

**Comment by brassier** [comment] 2018-12-18 22:07
A bit more info.  In my testing it looks like the following style on `ion-content` may be the key trigger point that Chrome and FF are treating differently:

    contain: layout size style;

Disabling that style on Chrome 71 makes the FAB on top again.

**Comment by brandyscarney** [comment] 2018-12-19 16:01
@brassier Thank you for all of the debugging! 

@manucorporat Do you have any ideas here?

**Comment by peterennis** [comment] 2018-12-20 04:55
rc0
I see the same here: https://github.com/peterennis/aetabs/blob/master/src/app/contact/contact.page.html#L38
The suggestion from @brassier works.
![layoutsizestyle](https://user-images.githubusercontent.com/140737/50264595-38a61480-03d0-11e9-8656-c0cd5b4f3f45.gif)

**Comment by redwolf2** [comment] 2018-12-20 10:49
This might also be related: https://stackoverflow.com/questions/53155252/css-property-contain-layout-makes-fixed-footer-not-work

**Comment by brassier** [comment] 2018-12-24 15:37
Any update on this?  I would guess there are many Ionic apps out in the wild with wonky FAB buttons as it stands.  Chrome obviously changed how they handle this `contain: layout` style.  Which is correct?

- Chrome ~71
- Chrome <71 (and current FireFox / Safari)

**Comment by DarkAnivia** [comment] 2019-01-03 16:31
I checked what redwolf2 said and it's like that, just erasing the "layout" allows the fab to be shown on top again

**Comment by brandyscarney** [comment] 2019-01-03 18:07
I created a Chromium bug report for this: https://bugs.chromium.org/p/chromium/issues/detail?id=918889

Since it still works the same in other browsers, I'd like to find out if this is a bug specifically with Chrome before making changes to our code, but worst case scenario we will remove the `contain` CSS if there is no response.

**Comment by brassier** [comment] 2019-01-07 16:54
@brandyscarney - Looks like this won't be fixed in Chrome, and will likely start failing in other browsers too.  Any idea how Ionic would suggest a fix for this in 4.x and 3.x ionic?

**Comment by DarkAnivia** [comment] 2019-01-09 12:48
Sorry for the inconvenience but is there an approximate time to market of this fix? 
We are figuring whether or not is worthwhile to change the composition of our app in the meanwhile

**Comment by redwolf2** [comment] 2019-01-09 14:15
As a crappy workaround try `style="z-index: 999999 !important"`

`<ion-fab style="z-index: 999999 !important" vertical="top" horizontal="end" edge slot="fixed">`

**Comment by brandyscarney** [comment] 2019-01-09 16:03
For v4 we plan to have it in for final, this issue is being tracked in the project board as top priority: https://github.com/ionic-team/ionic/projects/3 and the RC tracking issue: https://github.com/ionic-team/ionic/issues/16819.

v3 will likely take a bit longer to get a fix out as we will need to review our scripts to ensure nothing breaks.

In the meantime the following workaround should work for both versions:

```
ion-content {
  contain: size style;
}
```

Updated the earlier codepen to include this: https://codepen.io/brandyscarney/pen/KbgKNw

I'm not sure if there are any negative side effects from this as we have not started testing it yet. If anyone would like to throw that CSS in their app and report any bugs they see, that would be helpful. Thanks!

**Comment by brandyscarney** [comment] 2019-01-09 17:59
Chrome added it in 52, so while it may have not been working the same from a UI perspective it was still doing something. 🙂We will check it against all of our tests though. 

https://developers.google.com/web/updates/2016/06/css-containment
https://www.chromestatus.com/features/6522186978295808

**Comment by DarkAnivia** [comment] 2019-01-11 08:35
Thank you, we will try aswell

**Closed** 2019-01-17 17:45 UTC
Labels: package: core, type: bug

**Comment by redwolf2** [comment] 2019-02-12 16:52
It's fixed for Ionic 4, but Ionic 3 still has this problem.

**Comment by brandyscarney** [comment] 2019-02-12 18:01
@redwolf2 The fix should've been in the `3.9.3` release, are you using this version? https://github.com/ionic-team/ionic-v3/releases/tag/v3.9.3

**Comment by redwolf2** [comment] 2019-02-12 21:59
@brandyscarney Thx, I will check that out.

**Comment by Frotty** [comment] 2019-03-01 10:42
Hi, my issue https://github.com/ionic-team/ionic/issues/17130 has been locked.
I still have this exact problem, nothing has been fixed.

**Comment by brandyscarney** [comment] 2019-03-01 15:39
@Frotty Could you please open a new issue with your current Ionic version and steps to reproduce please? Thank you!
