### ISSUE TITLE
bug: click on ion-label inside ion-item with an ion-input opens keyboard but input field is not focused (iOS)

### ISSUE THREAD

**Issue by capc0** [ionic-team/ionic#21658] opened 2020-07-01 16:15 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

clicking a label opens the keyboard, but keyboard input does go into the void, because the input element inside the item is not focused properly.

**Expected behavior:**

they keyboard should not open or the input should be focused correctly.

**Steps to reproduce:**

use the code below and click on the label (not on the input)

**Related code:**

```
<ion-content>
    <ion-item>
        <ion-label  [position]="'stacked'">Label</ion-label>
        <ion-input type="string"></ion-input>
    </ion-item>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.1000.0
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.18.0 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment] 2020-07-01 16:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21509. (same underlying issue)

**Closed by liamdebeasi** 2020-07-01 16:41 UTC
Labels: triage

**Comment by capc0** [comment] 2020-07-01 16:52
thanks for the info. i did not found that issue prior opening this one.
