### ISSUE TITLE
Testing Ionic 4 - Spinner not respecting color setting and animation looks different

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14830] opened 2018-07-22 22:31 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
C:\ae\adaept.com\ae-svg-components>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   ionic (Ionic CLI) : 4.0.0-rc.11

System:

   NodeJS : v8.11.1
   npm    : 6.2.0
   OS     : Windows 10


C:\ae\adaept.com\ae-svg-components>
```

**Describe the Bug**
Spinner not respecting color setting

**Steps to Reproduce**
![capture349](https://user-images.githubusercontent.com/140737/43050665-f4138a34-8dc1-11e8-8642-82788581eaa5.png)
![capture348](https://user-images.githubusercontent.com/140737/43050668-fc8451ee-8dc1-11e8-93b9-d40d6518f9ff.png)

**Related Code**
https://aesvg.adaept.com/

**Expected Behavior**
Spinner should respect color setting

**Additional Context**
https://github.com/peterennis/ae-svg-components/blob/master/src/ae-devlist-component/ae-devlist-component.tsx#L55

NOTE: Compare this: https://beta.ionicframework.com/docs/api/spinner
and this: https://aesvg.adaept.com/
The animations do not match.

![ion-spinner](https://user-images.githubusercontent.com/140737/43050790-bf3e90f4-8dc3-11e8-9a6f-ba63b78d1e12.gif)
![ion-spinner2](https://user-images.githubusercontent.com/140737/43050816-0b9d6826-8dc4-11e8-9bbe-6484aae6aac2.gif)

**Comment by peterennis** [comment] 2018-07-22 22:32
Relates to: https://github.com/ionic-team/ionic/issues/14811

**Comment by peterennis** [comment] 2018-07-22 23:30
Adding a color for ion-card-header here: https://github.com/peterennis/ae-svg-components/commit/fcd85faadfd7d9f55f6054f15b2193e1bd865d29
and it affects some spinners.
![ion-spinner3](https://user-images.githubusercontent.com/140737/43051285-674cdb0e-8dcc-11e8-929c-c7ddea1154e4.gif)

**Comment by brandyscarney** [comment] 2018-07-23 22:22
Thanks for the issue! This is caused by the issue reported here: https://github.com/ionic-team/ionic/issues/14840

Since it appears your component that is wrapping the spinners is using shadow DOM, the spinners aren't able to get the global styles that set the colors. Could you try changing an `ion-spinner` to an `ion-badge` with a color and confirm that isn't working?

**Comment by peterennis** [comment] 2018-07-24 03:56
this commit: https://github.com/peterennis/ae-svg-components/commit/fb55f6e737e4254cae11305a689c4699e1178991
this result: https://aesvg.adaept.com/
![ion-spinner4](https://user-images.githubusercontent.com/140737/43116063-d6cc91f6-8eba-11e8-840a-7287864e201a.gif)

**Comment by brandyscarney** [comment] 2018-07-24 15:13
Thanks! Yeah unfortunately this is caused by placing an Ionic component inside of a component using Shadow DOM. I'm going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/14840 but thank you for reporting!

**Closed by brandyscarney** 2018-07-24 15:13 UTC
Labels: triage
