### ISSUE TITLE
bug: ionRefresh gets triggered when scrolling down

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic#20108] opened 2019-12-19 15:36 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Pull to refresh multiple times will randomly fire the ionRefresh event when scrolling down afterwards or some other strange behavior.
![ionRefresh](https://user-images.githubusercontent.com/11312418/71186578-bfa8f980-227d-11ea-9cb1-430a060158d3.gif)

**Expected behavior:**
Scrolling down shouldn't trigger the ionRefresh event.

**Steps to reproduce:**

1. Open [https://ionic-v4-angular-tabs-k1t7vt.stackblitz.io/tabs/tab1](https://ionic-v4-angular-tabs-k1t7vt.stackblitz.io/tabs/tab1) in responsive view
2. Pull to refresh a couple of times;
3. Try to scroll down;
4. Repeat above steps if it didn't trigger the refresh event.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-k1t7vt

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.13
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.20
   @angular-devkit/schematics    : 8.3.20
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-12-20 14:31
Thanks for the issue. I am going to close this as it appears to be a duplicate of https://github.com/ionic-team/ionic/issues/17784.

**Closed by liamdebeasi** 2019-12-20 14:31 UTC
Labels: triage
