### ISSUE TITLE
ion-footer/header issue with keyboard

### ISSUE THREAD

**Issue by dd-here** [ionic-team/ionic#11888] opened 2017-06-01 11:44 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.0.1**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a messaging page, having ion-footer at the bottom. Footer have an ion-textarea and a SEND button inside.

When we focus inside textarea, the keyboard comes up hiding the footer beneath, also the header goes up out of the screen . We want the footer to move along the keyboard and appear above the keyboard.

Also when we click the SEND button, the keyboard is dismissed. Whereas we want the keyboard to remain.

**Expected behavior:**

When keyboard comes up , the footer should appear above the keyboard, also header should be fixed at the top of the screen.
And when send button is clicked the focus should remain in the text area, keeping the keyboard up.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0

Ionic Framework Version: 3.0.1

Ionic CLI Version: 2.2.2

Ionic App Lib Version: 2.2.1

Ionic App Scripts Version: 1.1.4

Node Version: v6.9.1
```

**Comment by Khalid-Nowaf** [comment] 2017-06-01 11:51
Hi @dd-here, this issue related to the keyboard, and the ionic-team is working on it, and this is the tracking issue for keyboard bugs #11501.

**Comment by jgw96** [comment] 2017-06-02 16:06
Hello @dd-here , as @Khalid-Nowaf mentioned, this issue is related to the keyboard and has actually been fixed in the version of the wkwebview plugin that is mentioned in the issue that @Khalid-Nowaf linked too. Because of that I am going to close this issue as a duplicate of that issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-02 16:06 UTC

**Comment by kaushikparmar** [comment] 2018-07-20 13:31
Hello,

In my case, I do not want the footer sliding up with the keyboard.

What can I do?

I could not find any solution on this. 

I use Ionic 3.9.2

Please help.
