### ISSUE TITLE
Multiple ion-slides don`t swipe

### ISSUE THREAD

**Issue by Smoke1987** [ionic-team/ionic#12642] opened 2017-08-11 09:36 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When placed 2 or more components `ion-slides` second and subsequent sleders don't swiping.
Also, if you turn off the loopback of the slides, when you try to drag the first of the slides towards the last one (back to the list), the second and subsequent elements of `ion-slides` behave very strange: the internal component `swiper-wrapper` changes its position in ALL components `ion-slides` synchronously

**Expected behavior:**
Correctly swipe all of `ion-slides`

**Steps to reproduce:**
http://plnkr.co/edit/LzxLGDV86kTP4o0xBH6s?p=preview

Just delete the attribute `loop` from the first element of` ion-slides` and try to drag from the first slide to the side of the last one. Also the second `ion-slide` is not swiping

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:**
```
cli packages: (G:\Projects\xxxx\node_modules)

    @ionic/cli-utils  : 1.7.0
    ionic (Ionic CLI) : 3.7.0

local packages:

    @ionic/app-scripts              : 1.1.4
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 2.0.0

System:

    Android SDK Tools : 25.2.3
    Node              : v8.2.1
    OS                : Windows 7
    npm               : 5.1.0
```

**Comment by kensodemann** [comment] 2017-08-14 17:36
Hello, thank you for opening an issue with us! This is a duplicate of issue #12008. I am closing this issue. Please add any extra information you may have to issue #12008.

**Closed by kensodemann** 2017-08-14 17:36 UTC
