### ISSUE TITLE
Slider width issue in nested slides

### ISSUE THREAD

**Issue by Vishnuraj910** [ionic-team/ionic#11715] opened 2017-05-18 12:07 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Inside slider moves to the right as new slides show up.Main and sub sliders are both dynamic from JSON.
**Expected behavior:**

Slide properly fitting the screen
**Steps to reproduce:**

-->

**Other information:**
![rezpo slide bug](https://cloud.githubusercontent.com/assets/10269326/26201442/06efc40a-3be4-11e7-9f9c-a799d944b59d.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Vishnus-MacBook-Pro:Rezpo vishnurajrajagopal$ ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.3.2 Build version 8E2002```

**Comment by jgw96** [comment] 2017-05-18 14:56
Hello, thanks for using Ionic. Could you post a repo we could use to reproduce this please?

**Comment by jgw96** [comment] 2017-06-05 14:48
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-05 14:48 UTC
Labels: needs info, v2
