### ISSUE TITLE
ion-datetime bug in min max range

### ISSUE THREAD

**Issue by lpsantana** [ionic-team/ionic#12074] opened 2017-06-16 20:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Guys, it occurs in the display of the date picker:

I set hardcoded to an specific date like (2017-10-10) and it always show the current day of operating system ignoring what I had set. Month and year shows okay but the day always appears wrong.

**Expected behavior:**
Get the day corretcly.

Cordova CLI: 7.0.0 
Ionic Framework Version: 3.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.3
Xcode version: Not installed

**Comment by jgw96** [comment] 2017-06-19 14:24
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12070

**Closed by jgw96** 2017-06-19 14:24 UTC
