### ISSUE TITLE
FAB only works if it is a direct child of ion-content

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic#12252] opened 2017-07-04 09:57 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a component that will render (among others) a true FAB button. But being in component will always make it scroll with the content. I narrowed it down to the ion-fab element no being a direct child of ion-content. 

**Expected behavior:**
I would like to use a fab button in any component and it still would be floating like it should. (at this point i am stuck putting the same logic in multiple places)

**Steps to reproduce:**
See the plucker for live demo
 http://plnkr.co/edit/sxcYXhzE5wbxi8P6wSMN?p=preview

**Comment by jgw96** [comment] 2017-07-05 14:13
Thanks for opening an issue with us, we will look into this.

**Comment by Manduro** [comment] 2017-07-17 19:36
Duplicate of #8422, workaround here: https://github.com/ionic-team/ionic/issues/8422#issuecomment-264401297

**Comment by Remco75** [comment] 2017-07-17 19:57
@Manduro thnx, but the issue still stands, I want to wrap the fab in a component.(without writing custom styling) This should be pretty easy to fix. Instead of looking for the direct parent for ion-content, just look for the first ancestor.

**Comment by brandyscarney** [comment] 2017-07-21 17:27
This is actually because of `ng-content` not being able to grab the `ion-fab` to place it in the fixed content div in the `ion-content`: https://github.com/ionic-team/ionic/blob/master/src/components/content/content.ts#L163

Our recommended solution would be to add the `ion-fixed` attribute which tells it to place it in the fixed content:

```
<div ion-fixed style="top: 0; left: 0; right: 0; bottom: 0;">
  the fab-button at the bottom is in this nested div and is only visible after scroll
  <ion-fab bottom center><button ion-button>fails</button></ion-fab>
</div>
```

Note that I removed the `edge` attribute from your FAB because it adds negative margin and should really be used for placing a FAB over the edge of a toolbar. 

Unfortunately, there is not an easy fix for this. We have long ran into issues with nested components, and that is why the best we can offer is using `ngProjectAs` or the attributes that we provide when an element is nested. Here's another issue where it's discussed over custom components inside of an item: https://github.com/ionic-team/ionic/issues/9080

Fortunately, we have figured this out for the next major version, which we are hard at work on, and this will no longer be an issue. We mentioned what's to come in v4 in this blog: http://blog.ionic.io/announcing-ionic-3-5-3/

We'll be reaching out for testers soon, but so far we've seen it resolving some of these long-standing issues.

**Closed by brandyscarney** 2017-07-21 17:27 UTC
Labels: v2
