### ISSUE TITLE
ion-textarea spellcheck output is hidden by keyboard on iOS

### ISSUE THREAD

**Issue by lluc22** [ionic-team/ionic#20161] opened 2020-01-08 11:40 UTC
**Ionic version:**

[x] **4.11.7**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

ion-textarea spellcheck output is hidden by keyboard on iOS

**Expected behavior:**

The output of the spellcheck should be on top of the text.

**Steps to reproduce:**
Create a starter blank project with ionic CLI, add capacitor with iOS. Inside a page put a ion-textarea on the footer, with rows=1 and with spell check on. Run on a iOS device or simulator and deactivate predictive text. Type something with a typo.

**Related code:**

```
<ion-footer>
  <ion-toolbar>
    <ion-item>
    <ion-textarea rows="1" spellcheck="true">
    </ion-textarea>
  </ion-item>
  </ion-toolbar>
</ion-footer>
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v10.16.0 (/usr/local/Cellar/node@10/10.16.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina
```

![image](https://user-images.githubusercontent.com/9134163/71974962-27b28600-3213-11ea-8cda-9b64377e4b69.png)

**Comment by liamdebeasi** [comment] 2020-01-08 14:14
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I am able to reproduce this outside of the framework, so I think this may be a bug in WebKit. We will look into reporting this to the WebKit team. Thanks!

**Closed by liamdebeasi** 2020-01-08 14:14 UTC
Labels: triage
