### ISSUE TITLE
[Ionic 4.beta2] ion-item in ion-list doesn't show separate line 

### ISSUE THREAD

**Issue by teerasej** [ionic-team/ionic#15108] opened 2018-08-09 09:42 UTC
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/teerasejjiraphatchandej/Library/Android/sdk
```

**Describe the Bug**
In Ionic 3, `ion-item` in `ion-list` showed the separate line between each item. 

I put 2 screenshots to compared between 2 version.

**Steps to Reproduce**
1. Create new project
2. Open `home.page.html`
3. Put HTML code from Related Code section in `ion-content`
4. Open `home.page.ts`
5. Replace existing code with TS code from Related Code section
6. Run `ionic serve` or `ionic serve --lab`

**Related Code**
HTML
```
<ion-content padding>
  <ion-list lines>
    <ion-item *ngFor="let contact of contactArray" ">
      <ion-label>
        <h2>
          {{ contact.name }}
        </h2>
        <p>
          {{ contact.phone }}
        </p>
      </ion-label>
    </ion-item>
  </ion-list>
```

TS
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  contactArray = [
    { name:'Teerasej', phone:'191' }
    ,{ name:'Nextflow', phone:'199' }
    ,{ name:'Amaround', phone:'1554' }
  ];

}

```

**Expected Behavior**
`ion-item` should show line as default when stacked up in `ion-list`

**Additional Context**

I see [beta document](https://beta.ionicframework.com/docs/api/list/#usage) suggest we have to put `<ion-label>` inside `ion-item` to make thing happen. I don't sure is this the cause or not.

```
<!-- List of Text Items -->
<ion-list>
  <ion-item>
    <ion-label>Pokémon Yellow</ion-label>
  </ion-item>
 ...
```

Here are screenshot compare between:

`ionic serve --lab` with **ionic4.beta.2** (ionic serve will show android version, but same resulted here)

<a href="https://ibb.co/ec075p"><img src="https://preview.ibb.co/isdukp/2018_08_09_16_30_40.png" alt="2018_08_09_16_30_40" border="0"></a>

`ionic serve --lab` with **ionic 3**

<a href="https://ibb.co/bX075p"><img src="https://preview.ibb.co/eaSWWU/2018_08_09_16_30_31.png" alt="2018_08_09_16_30_31" border="0"></a>

Here ionic info for the screenshot ionic 3

```
ionic (Ionic CLI)  : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.3.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/teerasejjiraphatchandej/Library/Android/sdk
```

**Comment by brandyscarney** [comment] 2018-08-09 15:27
Thanks for the issue! So just to make sure I'm understanding correctly - the problem is that you don't see the lines between items on Android?

**Comment by aam-antonio** [comment] 2018-08-09 16:37
You can set full lines on the list:

```
<ion-list lines="full">
  <ion-item>
    <ion-label>Pokémon Yellow</ion-label>
  </ion-item>
</ion-list>
```

Or, if you want the lines between the items like on iOS, you can specify the mode:
```
<ion-list>
  <ion-item mode="ios">
    <ion-label>Pokémon Yellow</ion-label>
  </ion-item>
</ion-list>
```

**Comment by teerasej** [comment] 2018-08-09 16:46
@brandyscarney yes, I am. In Ionic 3, these lines showed in Android without any special attribute on `ion-list`.

Thank to @aam-antonio, added `lines="full"` make them back. 

At the moment, in beta document for `ion-list` API, there are no **full** value was described for `lines` property, neither `mode` property there. I think we should add them.

**Comment by teerasej** [comment] 2018-08-09 16:53
I'm sorry, just found out they described completely in repo's [readme.md](https://github.com/ionic-team/ionic/blob/master/core/src/components/list/readme.md), but not in [beta documentation](https://beta.ionicframework.com/docs/api/list/).

I think the documentation is really in beta :). I will check repo's read me next time, If I found another issue. cheer!

**Comment by brandyscarney** [comment] 2018-08-09 20:42
@teerasej We just added the documentation for `lines` today so it's not your fault! 🙂We'll have the docs updated to reflect this soon. 

Hiding the lines for Android was intentional to match the Material Design spec, however, they have updated the spec to include more usage of dividers: https://material.io/design/components/dividers.html#types

I'll keep this issue open so we can discuss the defaults.

**Comment by brandyscarney** [comment] 2018-10-09 16:41
The default for Material Design has been changed back to `inset` in latest by the following commit: https://github.com/ionic-team/ionic/commit/f885f7d10a8736a0e77ce47186b64f900b3e2d0b#diff-362a97f6d7a4ca64fe2cde4d5b7c51bfR16

You can still use the `lines` attribute to set them to `full` if desired. This will be in the `4.0.0-beta.13` release. Thanks for the issue!

**Closed by brandyscarney** 2018-10-09 16:41 UTC
