### ISSUE TITLE
Ion-input placeholder flickers on scroll in iOS

### ISSUE THREAD

**Issue by Bouzmine** [ionic-team/ionic#7001] opened 2016-06-21 19:18 UTC
#### Short description of the problem:

I have form in a modal and when I select an input and scrolling is needed, the placeholder flickers.
#### What behavior are you expecting?

The placeholder not to flicker.

**Steps to reproduce:**
1. Put a long form in a modal
2. Tap an input

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
This bug used to work in the browser, but since one of the nightlies, it only works in iOS. It also doesn't work if there's no scrolling.

**Which Ionic Version?** 2.x

Here's a repo for reproduction : [https://github.com/Bouzmine/demo-bug-flicker](https://github.com/Bouzmine/demo-bug-flicker)

Here's a video of the behavior : 
![bug flicker video-3](https://cloud.githubusercontent.com/assets/15067923/15985617/920e6f08-2fc1-11e6-88a3-d3e73c6096c8.gif)

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by paulogr** [comment] 2016-07-22 19:36
Same happens here! But not only the placeholder flicks but the value flicks too.
Any update about this issue?

**Comment by jgw96** [comment] 2016-08-10 16:32
Hello all! Would you mind giving this a try with beta.11? Thanks for using Ionic!

**Comment by Bouzmine** [comment] 2016-08-10 16:52
@jgw96 The bug is still present with the latest beta

**Comment by paulogr** [comment] 2016-08-10 23:15
Unfortunately yes, the bug is still present on the latest beta.11.

Bellow I sent you a new video that reproduces the issue on beta.11

![ionic-issue-7001](https://cloud.githubusercontent.com/assets/30919/17574373/234146cc-5f37-11e6-8bb0-4e4dd32590ff.gif)

Thanks!

**Comment by Bouzmine** [comment] 2016-08-20 17:19
@jgw96 It's also present on WKWebView

**Comment by davorpeic** [comment] 2016-08-24 03:15
+1

**Comment by brandyscarney** [comment] 2017-01-24 23:15
I'm not able to reproduce this using latest. Is anyone still seeing this issue? Thanks. :)

**Comment by Bouzmine** [comment] 2017-01-25 01:20
@brandyscarney I can see this in my project (Bouzmine/metho) when this project is ran on UIWebView and WKWebView. You have to create a project, go into it and then open one of the modals using the blue FAB.

**Comment by kensodemann** [comment] 2018-01-03 20:36
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. If this is still an issue after the next major release of Ionic please let us know.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 20:36 UTC
Labels: modals, needs reply, platform:ios, v2
