### ISSUE TITLE
Footer Visible During Navigation Transition

### ISSUE THREAD

**Issue by saniyusuf** [ionic-team/ionic#8804] opened 2016-10-19 15:30 UTC
I have a footer placed in a View I am navigating into. As soon as I start the navigation, the footer in the view being pushed to is seen even before the transition has ended. So you have a case where the footer is seen for some few milliseconds then the body in the header and content is then seen. See URL below for GIF

http://www.giphy.com/gifs/3oriNV1H6FAxdo5co8

Below is my Ionic Infor result. 
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175

**Comment by manucorporat** [comment] 2016-10-21 21:32
Can you share some code to reproduce the issue?

**Comment by infinnie** [comment] 2016-10-24 06:55
The same problem here in iOS mode.

**Comment by infinnie** [comment] 2016-10-24 06:57
@manucorporat I think that the link above to the GIF image illustrated the problem well.

**Comment by manucorporat** [comment] 2016-10-24 07:59
Well, there are many issues to be fixed, a lot of them are not real bugs but using the API incorrectly.
I still have to reproduce the issue to fix it, illustrate is not enough.

Some source code to reproduce it will increase the chances to get this solved as soon as possible.

**Comment by biesbjerg** [comment] 2016-11-02 19:12
I'm seeing the same thing after upgrading from beta 11 to rc1.

To reproduce:

Navigate from a page to another page using NavController. Destination page should use this template.
```
<ion-header>
	<ion-navbar color="brand">
		<ion-title>Footer Transition</ion-title>
	</ion-navbar>
</ion-header>

<ion-content>
	Content
</ion-content>

<ion-footer>
	This is visible during nav.push(Page) transition
	and does not disappear until transition has completed
</ion-footer>
```

**Comment by biesbjerg** [comment] 2016-11-15 23:25
Same issue reported herr: https://github.com/driftyco/ionic/issues/9121

**Comment by joaoveiga** [comment] 2016-12-09 14:37
Try to wrap your code inside the `ion-footer` inside a `ion-toolbar`, just like this:
`
<ion-header>
    <ion-navbar color="brand">
        <ion-title>Footer Transition</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    Content
</ion-content>

<ion-footer>
    <ion-toolbar>
        This is visible during nav.push(Page) transition
        and does not disappear until transition has completed
    </ion-toolbar>
</ion-footer>
`

**Comment by joaoveiga** [comment] 2016-12-09 14:39
Try to wrap your code inside the `ion-footer` in a `ion-toolbar`, just like this:
```
<ion-header>
    <ion-navbar color="brand">
        <ion-title>Footer Transition</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    Content
</ion-content>

<ion-footer>
    <ion-toolbar>
        This is visible during nav.push(Page) transition
        and does not disappear until transition has completed
    </ion-toolbar>
</ion-footer>
```

**Comment by royipressburger** [comment] 2016-12-12 06:42
@manucorporat I can also see this problem with search bar inside a header. Should I open new task?

**Comment by dylanvdmerwe** [comment] 2016-12-13 10:38
Similar issue here https://github.com/driftyco/ionic/issues/9606

**Comment by jgw96** [comment] 2016-12-16 23:03
A user has submitted a PR that should fix this issue here https://github.com/driftyco/ionic/pull/9597 . I will test this PR.

**Comment by jgw96** [comment] 2016-12-16 23:04
big thanks @lh4111!

**Comment by mhartington** [comment] 2017-01-10 19:36
I am unable to reproduce this in the latest nightly.
Closing for now.
If this is still happening, feel free to open a new issue

**Comment by Flixt** [comment] 2017-01-26 15:57
It seems wrapping things into a `<ion-tooblar>` is indeed a workaround. 
I additionally needed to remove the padding of the `<ion-toolbar>`

```css
.no-padding {
  padding: 0;
}
```

```html
<ion-footer>
  <ion-toolbar class="no-padding">
    <!-- animated footer content here -->
  </ion-toolbar>
</ion-footer>
```

**Comment by jgw96** [comment] 2017-06-23 16:55
Hello all! After some thought, we are going to close this issue as an `ion-footer` should always have its contents wrapped in an `ion-toolbar`. Thanks for using Ionic!

**Closed by jgw96** 2017-06-23 16:55 UTC
Labels: v2

**Comment by haifzhan** [comment] 2018-06-14 19:17
still have the issue even ion-toolbar added

**Comment by maronski** [comment] 2018-06-18 09:11
<ion-header>
    <ion-navbar color="brand">
        <ion-title>Footer Transition</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    Content

<ion-footer>
        This is visible during nav.push(Page) transition
        and does not disappear until transition has completed
</ion-footer>
</ion-content>

**Comment by maronski** [comment] 2018-06-18 09:14
@haifzhan Try to insert your `ion-footer` inside the `ion-content`, just like this:

```
<ion-header>
    <ion-navbar color="brand">
        <ion-title>Footer Transition</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    Content

<ion-footer>
        This is visible during nav.push(Page) transition
        and does not disappear until transition has completed
</ion-footer>

</ion-content>
```

**Comment by aoe2rtw2** [comment] 2018-06-21 04:04
Still seeing it even with ion-toolbar as well.  Tried removing the padding too but no luck.

**Comment by mishanya14228** [comment] 2018-08-13 13:57
Adding a <div> wrapper right after <ion-footer> tag helped me
