### ISSUE TITLE
用命令ionic cordova build browser --prod的时候，某些安卓手机运行起来是白屏，而用ionic cordova build browser打包的手机浏览网页运行起来就不是白屏？？求解答？？

### ISSUE THREAD

**Issue by xiaoman627** [ionic-team/ionic#12249] opened 2017-07-04 06:58 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by janpio** [comment] 2017-07-04 09:36
This sound more like a question to be answered on https://forum.ionicframework.com/ than via an issue here. Please open a topic there, post the URL here and close this issue.

**Comment by jgw96** [comment] 2017-07-05 14:05
Closing this as a duplicate of https://github.com/ionic-team/ionic/issues/12250

**Closed by jgw96** 2017-07-05 14:05 UTC
