### ISSUE TITLE
bug: ionFocus is not working for ion-input in android devices

### ISSUE THREAD

**Issue by rajiramamoorthi** [ionic-team/ionic#20535] opened 2020-02-18 13:25 UTC
ionFocus is not working for ion-input. Please check the below repo URL for example. 
https://github.com/rajiramamoorthi/test3

Android OS version: 7.0
Press the keyboard enter key and  focus again.
Repeat the above steps. It is not working.

**Comment by rajiramamoorthi** [comment] 2020-02-20 16:43
Hi @liamdebeasi 
      Are you able to reproduce this issue? Could provide resolution on this issue?

**Comment by liamdebeasi** [comment] 2020-02-20 17:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Blurring an input automatically closes the keyboard/de-focuses the input -- trying to hide the keyboard yourself without blurring the input is going to cause issues.

It is better to just ensure that the input gets blurred and then let the webview handle the rest of the work:

```typescript
import { IonInput } from '@ionic/angular';

...

@ViewChild('input', { static: true }) input: IonInput;

...

async closeKeyboard() {
    const nativeInput = await this.input.getInputElement();
    nativeInput.blur();
  }
```

**Closed by liamdebeasi** 2020-02-20 17:12 UTC
Labels: triage
