### ISSUE TITLE
ionic4 ion-select The default value cannot be set for the data requested by the network

### ISSUE THREAD

**Issue by ranlu823** [ionic-team/ionic#19828] opened 2019-11-03 05:22 UTC
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**
Network requested data cannot use selected to set default

**Expected behavior:**
Use selected to set the default value

**Steps to reproduce:**

**Related code:**

```
   <ion-list>
    <ion-item>
      <ion-select cancelText="Nah" okText="Okay" placeholder="--select--" (ngModelChange)="change($event)">
        <ion-select-option *ngFor="let item of event.classdata" value="{{item.ClassCode}}" selected="item.checked">
          {{item.ClassName}}
        </ion-select-option>
      </ion-select>
    </ion-item>
   </ion-list>

    const shifts = await this.getClassCode();
    const shiftsdata = await this.getClassData();
    shiftsdata.some((item: any, index: number) => {
      if (item.ClassCode === shifts) {
        this.event.classdata.push({ ClassCode: item.ClassCode, ClassName: item.ClassName, checked: true });
      } else {
        this.event.classdata.push({ ClassCode: item.ClassCode, ClassName: item.ClassName, checked: false });
      }
    });
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\RanLu\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 15 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

 (D:\Android\android-sdk).2.5
   NodeJS            : v10.16.3 (D:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by keo9ren** [comment] 2019-11-07 08:37
Possibly a duplicate of #19324 ? 
You may also find a workaround in my stackblitz there. 
Hope that helps a bit.

**Comment by liamdebeasi** [comment] 2019-11-07 14:23
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19324.

**Closed by liamdebeasi** 2019-11-07 14:23 UTC
Labels: triage
