### ISSUE TITLE
clearInput doesn't seem to work on IOS

### ISSUE THREAD

**Issue by bmagni** [ionic-team/ionic#10393] opened 2017-02-10 13:43 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I want to add clearInput attribute on my ion-inputs. My ion-inputs have ngModel attributes and some have keyup functions bind to them. On IOS, the clearInput icon shows up on focus but nothing happends when clicking it besides the loss of focus on the ion-input. It does work on Android.

**Expected behavior:**
I expect inputs to be empty after clicking on the clearInput icon.

**Steps to reproduce:**

**Related code:**

```
<ion-item>
	<ion-input [(ngModel)]="lastName" clearInput></ion-input>
</ion-item>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by jgw96** [comment] 2017-02-10 21:30
Hello, thanks for using Ionic! I am going to close this issue for now.

**Comment by pinpointpanda** [comment] 2017-02-14 02:53
@bmagni thanks for raising this, you beat me to it!

I'm experiencing the same issue, although I'm binding slightly differently using a FormGroup instead of ngModel.

**Comment by dalemugford** [comment] 2017-02-16 02:27
Same issue, noticed it a few days ago. Have had to disable that feature in app.

**Comment by Killmore** [comment] 2017-05-12 15:08
I was noticing the same issue. After playing around with it I started to notice it would work on some occasions. I think it's due to the 'hitbox' area of the clear button is very small on ios. On rare instances I could click it just right and get the expected behavior but the majority of the time it would just close the keyboard and retain the text. Just an assumption...

**Comment by elvandar06** [comment] 2017-05-18 10:10
I face the same problem, but on desktop, and with an input of type "date" :
the hitbox of the clear button is so tiny that it becomes unusable.
The other input types work well.

**Comment by davibertolini** [comment] 2017-05-22 14:46
Same issue here, changed to `clearInput="true"` and works on browser (ionic serve) but not on device. When tapping on the clear button, it just looses focus and closes the keyboard, but won't clear the text...

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.4.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8

**Comment by jasonfairhead** [comment] 2017-05-24 17:47
Same issue. any update @jgw96 ?

**Comment by flyhuang** [comment] 2017-06-07 02:12
Same issue.

I change "click" to "tap" in  ionic/src/components/input/input.ts

`   '<button ion-button clear [hidden]="!clearInput" type="button" class="text-input-clear-icon" (click)="clearTextInput()" (mousedown)="clearTextInput()"></button>'
`

It works fine.

**Comment by jasonfairhead** [comment] 2017-06-09 11:49
@flyhuang thanks!

**Closed** 2017-06-12 20:50 UTC
Labels: v2

**Comment by jasonfairhead** [comment] 2017-12-22 21:47
anyone notice that if using --prod to build this fix no longer works?
