### ISSUE TITLE
bug:  modalController.dismiss () does not close the modal if several modals are created but not presented.

### ISSUE THREAD

**Issue by root14** [ionic-team/ionic#21173] opened 2020-04-30 19:16 UTC
# Bug Report

**Ionic version:**
[x] **5.0.7**  ionic-angular

**Current behavior:**

When i create multiple modals using modalController's create function, and do not present all of the modal. The modalController's dismiss function does not close any modals. 

**Expected behavior:**
The modal should be dismissed

**Steps to reproduce:**

1. create several modals and present one
```
   const modal = await this.modalController.create({ 
      component: ModalComponentComponent
    });
    const modal2 = await this.modalController.create({ 
      component: ModalComponentComponent
    });
    const modal3 = await this.modalController.create({ 
      component: ModalComponentComponent
    });
    modal.present();
```
2. try to close the modal presented within it's component
modal-components.ts
```
dismiss() {
    this.modaleController.dismiss();
  }
```

modal-component.html
```
<ion-button (click)="dismiss()"> close modale </ion-button>
```

A sample application StackBlitz:
https://stackblitz.com/edit/angular-pmzd2p

**Comment by liamdebeasi** [comment] 2020-04-30 19:30
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. By default, the modal controller attempts to close the most recently created modal. In this case, that is `modal3`. 

It sounds like you want to dismiss `modal`, in which case you can either call the `dismiss` method on the modal itself, or create the modal with an ID and pass that ID into the modal controller `dismiss` method.

For example:

```javascript
const modal = await this.modalController.create({ 
  component: ModalComponentComponent,
  id: 'my-modal-id'
});

...

this.modalController.dismiss(undefined, undefined, 'my-modal-id);
// the other parameters allow you to specify a data object to return and a role but are both optional
```

**Closed by liamdebeasi** 2020-04-30 19:30 UTC
