### ISSUE TITLE
bug: Popover does not show-up - Compatibility with Tabs

### ISSUE THREAD

**Issue by Toto5931** [ionic-team/ionic#21198] opened 2020-05-02 17:59 UTC
# Bug Report

**Ionic version:**
[x] @ionic/react 5.1.0

**Current behavior:**
I have an IonTabButton supposed to open a popover. 
It works in the browser 
On Android, it does not work directly after start of the app. It works only after we touched an other TabButton.

**Expected behavior:**
The popover should show-up

**Steps to reproduce:**
Copy
https://github.com/Toto5931/ionic_popover_bug
Run Ionic serve and click on the right tab button (the 3 dots). The popover opens
Build the android app. Open the app and click on the right tab button. The popover does not open. If you click on the left tab button then the right tab button it works.

**Related code:**
```
const App: React.FC = () => {
  const [showPopover, setShowPopover] = useState<{ open: boolean, event: Event | undefined }>({
    open: false,
    event: undefined,
  });

  return (
    <IonApp>
       <IonReactRouter> 
        <IonTabs>

          <IonRouterOutlet>
          </IonRouterOutlet>

          <IonTabBar slot="bottom">

            <IonTabButton tab="tab1" href="/tab1">
              <IonIcon icon={mailOutline} />
            </IonTabButton>

            <IonTabButton onClick={(e) => {setShowPopover({ open: true, event: e.nativeEvent });}} >
              <IonIcon icon={ellipsisVerticalOutline} />
            </IonTabButton>

          </IonTabBar>

        </IonTabs>

        <IonPopover
          isOpen={showPopover.open}
          event={showPopover.event}
          onDidDismiss={() => setShowPopover({ open: false, event: undefined })}
        >
          Text
        </IonPopover>

      </IonReactRouter>
    </IonApp>
  );
};
```
**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\zorro\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.1.0

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.0.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

Thanks

**Comment by Toto5931** [comment] 2020-05-04 19:04
I just updated the bug report with a link to a github repo
Thanks

**Comment by liamdebeasi** [comment] 2020-05-07 14:08
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The tab button component is not really intended to be used this way, so you are going to need to prevent its regular functionality from firing. After your `setShowPopover` call, you should call `e.preventDefault()` to accomplish this. Thanks!

**Closed by liamdebeasi** 2020-05-07 14:08 UTC
Labels: ionitron: needs reproduction

**Comment by Toto5931** [comment] 2020-05-07 19:12
Thanks a lot !
