### ISSUE TITLE
bug: Collapsible Large Titles don't work if access another pages.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#19668] opened 2019-10-15 15:45 UTC
# Bug Report

**Ionic version:**
[x] **4.11.1**

**Current behavior:**
If access page using `Collapsible Large Titles`:
<img width="376" alt="スクリーンショット 2019-10-16 0 38 40" src="https://user-images.githubusercontent.com/9690024/66846867-6be41080-efad-11e9-9d46-ff939735604a.png">

If access another page(or tab), and move page using `Collapsible Large Titles`:
<img width="376" alt="スクリーンショット 2019-10-16 0 38 30" src="https://user-images.githubusercontent.com/9690024/66846924-8322fe00-efad-11e9-88b0-d1d97bfb08d1.png">

**Expected behavior:**
If access another page, `Collapsible Large Titles` is work.

**Steps to reproduce:**
1. access https://ionic-v4-angular-tabs-eqcuds.stackblitz.io
2. click tab2

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-eqcuds

**Ionic info:**
local.

```
Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.16.2 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Catalina
   Xcode      : Xcode 11.1 Build version 11A1027

```

**Comment by rdlabo** [comment] 2019-10-15 16:02
※ Regardless of `ion-buttons`, `Collapsible Large Titles` has this problem.

**Comment by liamdebeasi** [comment] 2019-10-15 16:25
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19640. There is a dev build available in that thread with a fix.

**Closed by liamdebeasi** 2019-10-15 16:25 UTC
Labels: triage
