### ISSUE TITLE
cordova.js missing when using live reload

### ISSUE THREAD

**Issue by yelhouti** [ionic-team/ionic#15943] opened 2018-10-15 02:04 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.12
   @angular-devkit/build-angular : 0.9.0-beta.3
   @angular-devkit/schematics    : 0.9.0-beta.3
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/yelhouti/Android/Sdk)
   NodeJS            : v8.12.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

```

**Describe the Bug**
cordova.js missing when using live reload (-l) both on emulator and physical device (android)

**Steps to Reproduce**
1. Create a project
2. Add a native plugin and use it in your code (optional)
3. ionic cordova run android -l
4. check cordova.js is missing (and that plugin don't work)

**Expected Behavior**
cordova.js should be present when using live reload

**Comment by JupiterSymphony** [comment] 2018-10-15 17:28
https://github.com/ionic-team/ionic/issues/15893

**Comment by paulstelzer** [comment] 2018-12-07 10:44
Duplicate of #15893

**Closed by paulstelzer** 2018-12-07 10:44 UTC
Labels: triage
