### ISSUE TITLE
Android hardware back button not working in --prod mode

### ISSUE THREAD

**Issue by Muji86** [ionic-team/ionic#12229] opened 2017-07-01 23:13 UTC
I wonder if anyone is experiencing this issue, couldn't find anything reported.

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Android hardware back button doesn't seem to work when creating a prod build (--prod flag)
It works when building without the prod flag however
**Expected behavior:**

The hardware button should behave same as the soft back arrow on the app

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2017-07-03 14:35
Hello, thanks for using Ionic! Unfortunately, i am not able to reproduce this issue. Would you mind posting your `ionic info` and a repo we could use to reproduce this issue?

**Comment by peterkelly** [comment] 2017-07-04 14:43
Possible duplicate of https://github.com/ionic-team/ionic/issues/12238

**Comment by Muji86** [comment] 2017-07-07 22:20
Hi, Apologies for the vague description.
I'm trying to reproduce it on a fresh template and will update you.
Note that this only happened when I started using lazy loading.

Will keep you posted

**Comment by Muji86** [comment] 2017-07-08 01:53
OK, I've figured it out.

The problem is that I have multiple <ion-nav> in my app.html with *ngIf on each so that only one is displayed.
Strange thing is that only happens when built with PROD
I guess I'll try to use only one ion-nav an control the rootpage in the ts

**Closed** 2017-07-17 15:57 UTC
Labels: needs info, v2

**Comment by ufo2mstar** [comment] 2018-04-09 15:32
If anybody is having problems with the back button on the software side, I am able to fix that with this `css` change
```css
.back-button {
  z-index: 1;
}
```
pushes the back button in front of the title bar, without any side-effects..
