### ISSUE TITLE
bug: autocomplete=“username” does not work in iOS

### ISSUE THREAD

**Issue by sinan92** [ionic-team/ionic#19895] opened 2019-11-12 08:20 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I am trying to get my iPhone to save the credentials when I login. But first of all the username field does not show the "Keychain" button to autofill my credentials. The password field does show this. I have tried all possible values for autocomplete for both fields but they never changed a thing (on, off, username, current-password).

I have also tried setting the type of the username to password. This did make the username activate keychain. But of course this is not what I want.

This is what my HTML looks like:

```
  <form [formGroup]="loginForm" (ngSubmit)="login()" novalidate>
    <ion-item lines="none">
      <ion-label position="stacked">Username</ion-label>
      <ion-input formControlName="username" name="username" autocomplete="username" tabindex="1" (keyup.enter)="login()" required></ion-input>
      <ion-text *ngIf="loginForm.controls.username.invalid && loginForm.touched" class="error" color="danger">Username is required</ion-text>
    </ion-item>


    <ion-item lines="none">
      <ion-label position="stacked">Password</ion-label>
      <ion-input formControlName="password" name="password" autocomplete="current-password" tabindex="2" (keyup.enter)="login()" type="password" required></ion-input>
      <ion-text *ngIf="loginForm.controls.password.invalid && loginForm.touched" class="error" color="danger">Password is required</ion-text>
    </ion-item>

    <ion-button color='primary' class="loginBtn" tabindex="3" [disabled]="loginForm.invalid" ion-button type="submit" block float-right>
      {{ 'login.login' |translate }}&nbsp;
      <fa-icon icon='sign-in-alt'></fa-icon>
    </ion-button>
  </form>
```
Another thing is that tabindex also doesn't work. It doesn't activate the arrow buttons.

I have not been able to test this for android, but in chrome, the password manager does work. The tabindex doesn't (when I press tab it selects the area of the field before it selects the password field).

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.6 (C:\Users\Sinan\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-11-12 13:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We have reported this bug to Apple: https://bugs.webkit.org/show_bug.cgi?id=203299.

**Closed by liamdebeasi** 2019-11-12 13:55 UTC
Labels: triage

**Comment by sinan92** [comment] 2019-11-12 14:05
While doing further research on this problem I discovered that the problem is different than expected. If you remove the ion-item tags the username field actually does show the password autocomplete. However it still doesn't get saved to the password autocomplete after successfully logging in.

**Comment by liamdebeasi** [comment] 2019-11-12 14:07
Right, that's because `ion-item` is in the Shadow DOM which is the same as the WebKit issue I linked to.
