### ISSUE TITLE
zoom in ion-scroll not working in beta 2.0

### ISSUE THREAD

**Issue by yelhouti** [ionic-team/ionic#5701] opened 2016-03-03 18:33 UTC
#### Short description of the problem:

zoom option in `<ion-scroll>` is not working in beta 2.0m also the scrollY is poorly working on iOS.
#### What behavior are you expecting?

I'm expecting the zoom to work when I add `zoom="true" and maxZoom="2"` to `<ion-scroll>`

**Steps to reproduce:**
1. use the code provided below (modification of demo)
2. pinch the screen

this the code from the demo modified

```
<ion-content>
    <ion-scroll maxZoom="2" zoom="true" scrollX="true" scrollY="true" style="width: 100%; height: 100%">
        <div class="map-div"></div>
    </ion-scroll>
</ion-content>

<style>
    .map-div {
        width: 2600px;
        height: 1400px;
        background: url('./map.jpeg') no-repeat;
    }
</style>
```

**Ionic Version**:  2.0

**Browser & Operating System**: iOS / Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002 

```

**Comment by jgw96** [comment] 2016-03-23 15:47
Hello thanks for opening an issue with us! Since this issue could be considered a duplicate of the two issues referenced above I will be closing this issue. Please feel free to continue the conversation on this issue over there! Thanks again!

**Comment by arsenslyusarchuk** [comment] 2016-07-23 12:20
The closed one issue is about Ionic1 and not Ionic2.

**Comment by iRoachie** [comment] 2016-10-16 16:39
@jgw96 Could you guys stop closing issues so quickly? The issue is not resolved. The issue you linked to is for Ionic 1. It is still broken in Ionic 2

**Comment by iRoachie** [comment] 2016-10-16 19:00
@manucorporat @jgw96 Can we get an update from the team on the progress of this? I see on this issue #6482 it was removed from the milestone

**Comment by manucorporat** [comment] 2016-10-16 19:05
@iRoachie I am not sure this feature will make it before 2.0 release.
But I agree, `<ion-scroll>` needs some love, it has been abandoned.

I have started cleaning up the code, not sure how to implement the zoom yet (maybe hammer? + scale3d), I have to talk with the team.

**Comment by iRoachie** [comment] 2016-10-16 19:09
@manucorporat Could we at least put a note in the docs saying it doesn't work currently? I tried a workaround using `(pan)` event;

```js
const scale = e.srcEvent.scale;
const newWidth = scale * 100;
```

Only thing is that the pan event fires after the pinch, so it's a delayed zoom

**Comment by zakton5** [comment] 2016-12-06 13:41
Any way this could make it to the next milestone?

**Comment by iliagerman** [comment] 2016-12-27 16:21
Hi, any news?

**Comment by diegofalciola** [comment] 2017-01-31 09:54
Looks like there are a lot of people experiencing this problem, but none of them have been able to find a solution to it. 

The latest thing I found comes from this repo: https://github.com/nikini/ionic-gallery-modal/tree/master/src

It implements a custom zoomable-image, which seems to work fine. Cons are that its complexity is quite high if you need to build it on your own. Also, this must be supported in Ionic2, so eventually it might change.

If anybody has something better, please share!

**Comment by KevRyan2** [comment] 2017-05-10 03:14
@jgw96 have there been any updates made for a solution to this issue?  (following your reference over from issue #6788 )

**Comment by zakton5** [comment] 2017-06-06 13:41
@jgw96 @manucorporat @brandyscarney
Why do bugs in core features (zooming, virtual scroll, etc.) keep getting ignored. Ionic team, you are doing great work, but please take some time to fix these core issues that prevent **many** people from creating production ready applications

**Comment by Stahet** [comment] 2017-08-03 18:00
Any news on this issue?

**Comment by appinasia** [comment] 2017-08-26 04:21
Still looking a solution :((

**Comment by zakton5** [comment] 2017-08-30 19:57
Of course not. I'll probably attempt to make a PR for this soon, as I really need it.

**Comment by 594727294** [comment] 2017-09-08 20:23
Please fix this Ionic Team, it is imperative.

After 3 months of development of an important app in a team for a big corporation we are starting to regret our framework choice, from poor documentation to bugs like this.

**Comment by cukorlyon87** [comment] 2017-09-11 08:49
Hi ionic team,

Please, you fix this, we are waiting a lot of time... I´m also starting to regret of this framework, thanks.

**Comment by leonardosalles** [comment] 2017-09-22 18:53
+1

**Comment by christianwico** [comment] 2017-10-03 04:04
I'm beginning to hate hybrid apps. I mean, something as simple as a "zoom" feature isn't working? This is the exact reason why the native apps peeps keep ripping these technologies and saying that *"Hybrids are never going to be the future of mobile app development."*

The fact that this "bug" *(or piece of tardiness)* has lasted over a year without a clear resolution has absolutely made me regret my framework choice.

![](https://i.ytimg.com/vi/gYNUOkqzcVA/maxresdefault.jpg)

**Comment by christianwico** [comment] 2017-10-03 04:12
This framework is making hybrid look bad. This is a **fundamental feature** and yet it isn't working?

I'm starting to regret this choice of tech stack.

Over a year, guys. Over a year.

**Comment by alejandro-heredia-coderoad-com** [comment] 2017-10-26 20:31
Could you please put the same effort on this issue as you're putting into the CLI? Thank you.

**Comment by adamduren** [comment] 2017-11-06 20:45
My guess is the Ionic team is focused on Ionic 4 in which all components will be rewritten as Stencil components so Ionic 2/3 issues are getting neglected. Although if this is the case it would be nice for it to be communicated vs being left hanging.

Looking at the [scroll](https://github.com/ionic-team/ionic/blob/master/src/components/scroll/scroll.ts) component it's pretty minimal and a lot of the code `zoom`, `maxZoom`, and `addScrollEventListener` is unused throught the codebase.  It's probably best to submit an PR that fixes this issue or implement a custom component while we wait for the Stencil release of Ionic and hope that the issue is no longer present.

**Comment by leonardosalles** [comment] 2017-11-07 03:04
As @adamduren said, I decided to implement a custom component and after that I open sourced the code, you guys can use and submit your issues and PR's at https://github.com/leonardosalles/ionic2-zoom-area

thanks.

**Comment by praveenraji2i** [comment] 2018-03-13 13:14
Still the issue is not resolved...

**Comment by leonardosalles** [comment] 2018-03-14 17:32
Ionic team are working in Ionic 4 release, think this issue will be not solved :rage2:

**Comment by freeweed** [comment] 2018-09-17 18:13
Hello There, Here is my solution. Hope It's help another body.
https://github.com/freeweed/ionic-panzoom

**Comment by leonardosalles** [comment] 2018-09-18 14:00
> Hello There, Here is my solution. Hope It's help another body.
> https://github.com/freeweed/ionic-panzoom

I stopped on jQuery...

**Comment by freeweed** [comment] 2018-09-19 08:19
@leonardosalles I before jQuery I try zoom-area, And it's can't even build with --prod flag. sadly

**Closed** 2018-11-01 19:53 UTC
Labels: ionitron: v3, platform:ios, v2
