### ISSUE TITLE
bug: ion-note incorrect location

### ISSUE THREAD

**Issue by lee-vic** [ionic-team/ionic#19689] opened 2019-10-18 12:01 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

In Google Chrome (version 77.0.3865.120),When ion-label and ion-note coexist, if ion-label is displayed in multiple lines, the ion-note display will be offset. This problem does not exist in ionic3.
![QQ图片20191018200935](https://user-images.githubusercontent.com/2107826/67093263-ca92cf80-f1e3-11e9-8f5f-9b26b8f6e707.png)

**Expected behavior:**
Vertical alignment 

**Steps to reproduce:**

**Related code:**

https://github.com/lee-vic/ionic-demo.git
```
<ion-content>
  <ion-list>
    <ion-item detail>
      <ion-label>
        <h2>Title</h2>
        <p>Details</p>
      </ion-label>
      <ion-note slot="end">Note</ion-note>
    </ion-item>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\lee\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 7
```

**Comment by brandyscarney** [comment] 2019-10-18 16:00
Thanks for the issue! I was able to reproduce this.

**Comment by seravifer** [comment] 2019-10-19 15:52
I think I have the solution, I will send a PR.

**Comment by brandyscarney** [comment] 2019-11-08 00:21
Taking another look at this, this is actually correct per the spec. The Material Design spec aligns the notes to the top of an item:

<img src="https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1-YqqvjVvKr2aWHg6yQ9KOP9yFbk-4o9t%2Flist-spec-doubleline-individual.png">

<img src="https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F12GMB_cxP-3KCbZ2JxkAizaX2pGWXmOMA%2Flist-spec-threeline-individual.png">

Source: https://material.io/components/lists/#specs

See the two line & three line. I think the code in Ionic is correct and this should be handled by your app if you'd like it aligned to the center.

**Comment by brandyscarney** [comment] 2019-11-08 15:38
I'm going to close this as this is by design to match the spec, please see my last comment for images and links to the Material Design spec. Here's a Codepen showing how to customize the CSS alignment: https://codepen.io/brandyscarney/pen/QWWxpOR?editors=1100

Thank you!

**Closed by brandyscarney** 2019-11-08 15:38 UTC
Labels: help wanted, package: core, type: bug
