### ISSUE TITLE
ion-datetime,give Picker a default value,but not write _text nor ngModel

### ISSUE THREAD

**Issue by ACEsLegendary** [ionic-team/ionic#12280] opened 2017-07-07 03:19 UTC
A Feature Request in fact!
Because _max.year's or this year‘s January 1  is the default value for Datetime's Picker,which is not friendly for users and even couldn't be used in some particular situation. So I'd like to have a method to set the Picker's default value.Of course,we just want it to be used only when user open the Datetime's Picker,but should never write to _text until user confirm 'yes' in the Picker, not to mention the ngModel.
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when I used ion-datetime,if I don't set property 'max',the max would be December 31st of this year,which means I can't pick any date in next year,not to mention decades later.Of course,the max need to be set.
Even though, when I open Datetime's Picker, the default choice is January 1st of this year or of the max.year .This is really unfriendly to users.

**Expected behavior:**

We'd like to have a method to give a default value to Datetime's Picker when it's opened, but neither _text nor ngModel would be updated until user click the Picker's 'yes' button.

**Steps to reproduce:**

Just use <ion-datetime>, you will see the problem.
**Related code:**
In my project, I used a extremely way to solve above problem, which is sucking bad code ,AFAS.
Meanwhile, because it has to wait ngModel updated, so _text's setting has a delay after user chose a Date and click 'yes'.
Bellow is the demo code.
```
import { Component, Input, ViewChild, EventEmitter, Output } from "@angular/core";
import { DateTime } from "ionic-angular";
@Component({
    selector: "my-datetime",
    template: `<ion-datetime [max]="max" [min]="min" [(ngModel)]="value" class="tal"></ion-datetime>`,
    styles:[".tal{text-align:left;}"]
})
export class MyDateTime {
    @Input("defaultValue")
    defaultValue: string;
    @Input("max")
    max: string;
    @Input("min")
    min: string;
    @ViewChild(DateTime)
    datetime: DateTime;
    @Output()
    valueChange: EventEmitter<any> = new EventEmitter();
    _value: any;
    @Input()
    get value() {
        return this._value;
    }
    set value(val) {
        this._value = val;
        this.valueChange.emit(this._value);
    }
    ngAfterViewInit() {
        //first,setDefault value
        this.setDefaultValue();
        //second, override updateText to keep _text clean until ngModel;s updated.
        this.datetime.updateText = () => {
            this.datetime._text = this.formatDate(this.value,"yyyy-MM-dd");
        }

    }
    setDefaultValue() {
        let defaultValue = new Date(this.defaultValue);
        this.datetime._value = {
            year: defaultValue.getFullYear(),
            month: defaultValue.getMonth() + 1,
            day: defaultValue.getDate(),
            hour: defaultValue.getHours(),
            minute: defaultValue.getMinutes(),
            second: defaultValue.getSeconds(),
            millisecond: defaultValue.getMilliseconds(),
            tzOffset: defaultValue.getTimezoneOffset()
        };
    }

    formatDate(val, fmt) {
        if(!val){
            return "";
        }
        val=new Date(val);
        var o = {
            "M+": val.getMonth() + 1, //月份 
            "d+": val.getDate(), //日 
            "h+": val.getHours(), //小时 
            "m+": val.getMinutes(), //分 
            "s+": val.getSeconds(), //秒 
            "q+": Math.floor((val.getMonth() + 3) / 3), //季度 
            "S": val.getMilliseconds() //毫秒 
        };
        if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (val.getFullYear() + "").substr(4 - RegExp.$1.length));
        for (var k in o)
            if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
        return fmt;
    }
}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

,

**Comment by AmitMY** [comment] 2017-07-07 10:33
Thanks for opening an issue.
Can you please fill out the template for new issues?

**Comment by patrickmcd** [comment] 2017-07-07 12:18
Look like a duplicate of https://github.com/ionic-team/ionic/issues/9846

**Comment by ACEsLegendary** [comment] 2017-07-07 13:07
The issue has been updated!

**Comment by ACEsLegendary** [comment] 2017-07-07 13:24
Yes,it looks like a similar problem, and I find @nrcrabbe's way is much simpler and more elegant, aha, I'm going to change my code on his way. But it could be better to allow ionic's DateTime to add this feature. After all, thanks a lot!

**Comment by jgw96** [comment] 2017-07-07 14:13
Hello everyone! Thanks for the feature request. I'm going to move this issue over to our internal list of feature requests for evaluation. We are continually prioritizing all requests that we receive with outstanding issues. We are extremely grateful for your feedback, but it may not always be our next priority. I'll copy the issue back to this repository when we have begun implementation. Thanks!

**Comment by jgw96** [comment] 2017-07-07 14:13
This issue was moved to ionic-team/ionic-feature-requests#270

**Closed by jgw96** 2017-07-07 14:13 UTC
