### ISSUE TITLE
item-options appear when swipe item-sliding in opposite direction (Ionic 4-beta.17)

### ISSUE THREAD

**Issue by Majed93** [ionic-team/ionic#16584] opened 2018-12-04 19:07 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Majed\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.1.0

Capacitor:

   capacitor (Capacitor CLI) : not installed
   @capacitor/core           : 1.0.0-beta.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
When i swipe an item-sliding in the opposite direction in which it's allowed then options still appear (no animations they just appear).

Example code below - default swipe RTL

Swipe left will show the options when it should do nothing.

**Steps to Reproduce**
Swipe in opposite direction to which you expect to.

**Related Code**
```
<ion-item-sliding>
    <ion-item>
        <ion-label>
            Test
        </ion-label>
    </ion-item>
    <ion-item-options>
        <ion-item-option>
            Option 1
        </ion-item-option>
        <ion-item-option>
          Option 2
        </ion-item-option>
    </ion-item-options>
</ion-item-sliding>
```

**Expected Behavior**
Options not to show

**Additional Context**
N/A

**Comment by bryce13950** [comment] 2018-12-05 14:56
Is there any chance that you could setup a simple repository with some code that would allow us to help reproduce this issue?

**Comment by Majed93** [comment] 2018-12-05 17:54
Here you are.

https://github.com/Majed93/test-16584/tree/master

Let me know if you need anything else :)

**Comment by bryce13950** [comment] 2018-12-06 14:45
Thanks!

**Comment by brandyscarney** [comment] 2019-01-03 16:20
Closing as a duplicate of #14328

**Closed by brandyscarney** 2019-01-03 16:20 UTC
Labels: needs: investigation, package: core
