### ISSUE TITLE
bug: even and odd in virtualscroll 

### ISSUE THREAD

**Issue by victorsosa** [ionic-team/ionic#20752] opened 2020-03-11 22:24 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
odd and even is not working as expected in the *virtualItem directive.
for example:
```
<ion-virtual-scroll [items]="orden.itemslist" approxItemHeight="320px">
    <ion-item-sliding *virtualItem="let item; let odd = odd; let even=even;">
      <ion-item [color]="even ? 'next' : 'light'" >
....
```
should render a band color 

**Expected behavior:**
Expected to draw band color equal to be using *ngFor directive.

**Comment by liamdebeasi** [comment] 2020-03-12 13:26
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by victorsosa** [comment] 2020-03-12 19:31
I made it work just using the index variable; It seems like only the index var is accesible in the *virtualItem of the ion-virtual-scroll. The odd or even is missing in the component.

Here is some code that works as expected:
```
  <ion-virtual-scroll [items]='filteredItems' lines="none">
    <ion-item *virtualItem="let item; let i = index;" [color]="i % 2 != 0 ? 'next' : 'light'"
     (click)="add(item)">
	{{item.value}}
    </ion-item>
  </ion-virtual-scroll>
```
let i = index;
[color]="i % 2 != 0 ? 'next' : 'light'"

this work as expected.

I just check the code and found this interface responsible for the variables:
https://github.com/ionic-team/ionic/blob/master/angular/src/directives/virtual-scroll/virtual-utils.ts

**Comment by liamdebeasi** [comment] 2020-03-12 20:21
Thanks for the follow up. That is correct, we do not currently expose `even` or `odd` variables like the CDK Virtual Scroll component does. I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2020-03-12 20:21 UTC
Labels: triage
