### ISSUE TITLE
bug: SSR, Flickering when ssr page is replaced

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic#21245] opened 2020-05-08 13:14 UTC
# Bug Report

**Ionic version:**
[x] *5.0.5*

**Current behavior:**
When the app switches from server side rendered to client side rendered version, there is is a blank screen shown, resulting in a flickering on fast-loading devices.

**Expected behavior:**
The user should not recognize the switch, as with original angular universal apps.

**Steps to reproduce:**
Use SSR with Ionic

**Example**
To see it more clearly, check this example (25s video) where I used a slow network speed.
Between "IsServer -> IsBrowser", a blank page appears.

![ionic-ssr-flicker](https://user-images.githubusercontent.com/11556950/81408959-7ed35380-913e-11ea-942e-1bb031b80e77.gif)

**A sample application via GitHub**
Small example to reproduce: [Example on Github](https://github.com/KevinBassaDevelopment/ionic-ssr-working/tree/master)

**Comment by mhartington** [comment] 2020-05-18 14:12
Hey there! So this is to be expected. The way angular universal works, it will clear out the DOM from the server render and do a fresh render from the browser content. This would happen with or without Ionic involved.


There are things you could do to better improve the transition (using TransistionState to prime the components data), but it's not something is caused by Ionic. 

Closing

**Closed by mhartington** 2020-05-18 14:12 UTC
Labels: triage

**Comment by KevinBassaDevelopment** [comment] 2020-05-19 07:13
> 
> 
> Hey there! So this is to be expected. The way angular universal works, it will clear out the DOM from the server render and do a fresh render from the browser content. This would happen with or without Ionic involved.
> 
> There are things you could do to better improve the transition (using TransistionState to prime the components data), but it's not something is caused by Ionic.
> 
> Closing

Hi, as far as I can tell, this is not Angulars default behaviour.

I build a website in Angular only and it switches from server to browser version without notice:

Check this site, where I but "server/browser" in the title. You can switch to the slowest network speed and won't notice anything.

http://test.bassa-solutions.at/bassasolutions

So this means that Ionic introduces this problem.

**Comment by KevinBassaDevelopment** [comment] 2020-05-19 07:21
Also, the Ionic Example is quite minimal, so it should really work the same as basic Angular.

I hope you can reopen the ticket.

**Comment by mhartington** [comment] 2020-05-19 19:04
![Screen Shot 2020-05-19 at 2 08 36 PM](https://user-images.githubusercontent.com/2835826/82362368-3dfafa80-99da-11ea-9c56-993b7a863c33.png)


Seeing as the site you linked to has an app-shell in place, the comparison isn't exactly 1:1.

**Comment by KevinBassaDevelopment** [comment] 2020-05-20 06:07
> 
> 
> ![Screen Shot 2020-05-19 at 2 08 36 PM](https://user-images.githubusercontent.com/2835826/82362368-3dfafa80-99da-11ea-9c56-993b7a863c33.png)
> 
> Seeing as the site you linked to has an app-shell in place, the comparison isn't exactly 1:1.

Ok, I'll build a 1:1 example on the weekend and post it here.

**Comment by KevinBassaDevelopment** [comment] 2020-05-21 11:07
Hi @mhartington,

I now created 2 perfectly comparable applications.

The 1st one is a basic ionic SSR example.
The 2nd one is the same example, with just ionic removed

The repositories can be found here:
[Github Ionic-SSR-Flickering](https://github.com/KevinBassaDevelopment/ionic-ssr-flickering-example)
[Github Angular-SSR-No-Flickering](https://github.com/KevinBassaDevelopment/angular-ssr-no-flickering-example)

The live examples can be compared here:
[Live Ionic SSR example](https://ionic-ssr.bassa-solutions.at/)
[Live Angular SSR example](https://angular-ssr.bassa-solutions.at/)

I hope this validates my point that this behaviour is not angular universals default behaviour.
