### ISSUE TITLE
feat: Default app texts are only english

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic#11880] opened 2017-05-31 18:54 UTC
**Type**: <span ionic-type>feat</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>All the default texts in the app (example: OK and cancel in Alert component) are only English.
I think it will be good idea to add "language" property in the app config, and ionic framework should have default texts for all of the languages.
Or at least, option to edit all of the default texts in one function, and not at every .present() call.</span>

<span is-issue-template></span>

**Comment by AmitMY** [comment] 2017-05-31 19:51
Dup: https://github.com/ionic-team/ionic/issues/10861

**Comment by jgw96** [comment] 2017-06-01 13:39
Hello all, closing this as a duplicate of #10861

**Closed by jgw96** 2017-06-01 13:39 UTC
