### ISSUE TITLE
bug: not run 

### ISSUE THREAD

**Issue by vitthalghodke1** [ionic-team/ionic#21377] opened 2020-05-26 17:48 UTC
> cordova.cmd platform add android --save
(node:12672) Warning: Accessing non-existent property 'android' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "android" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vits\AppData\Roaming\npm-cache\_logs\2020-05-26T17_42_07_346Z-debug.log
    at ChildProcess.whenDone (C:\Users\vits\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\superspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\vits\AppData\Roaming\npm\node_modules\cordova\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  stderr: 'npm ERR! code ENOLOCAL\n' +
    'npm ERR! Could not install from "android" as it does not contain a package.json file.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\vits\\AppData\\Roaming\\npm-cache\\_logs\\2020-05-26T17_42_07_346Z-debug.log\n',
  code: 1
}

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-05-26 17:54
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. It looks like you had previously installed Capacitor before using Cordova instead. Please see this forum thread for a solution: https://forum.ionicframework.com/t/could-not-install-from-ios-as-it-does-not-contain-a-package-json-file/168462.

**Closed by liamdebeasi** 2020-05-26 17:54 UTC
Labels: triage
