### ISSUE TITLE
bug: Knob in a diabled ion-range has a fixed white outline on android... looks ugly against a dark background.

### ISSUE THREAD

**Issue by Martin-Luckow** [ionic-team/ionic#18096] opened 2019-04-22 10:09 UTC
# Bug Report

**Ionic version:**
4.12.0

**Current behavior:**
I have an app with a dark background. If I insert a disabled ion-range and view it on an **android** device I get the attached picture. There is an ugly white frame around the knob. There is no extra-CSS for this ion-range.

The border results from an CSS-outline at
:host(.range-disabled) .range-knob {
    -webkit-transform: scale(.55);
    transform: scale(.55);
    outline: 5px solid #fff;
}

![ion-range](https://user-images.githubusercontent.com/11980340/56495383-e0099400-64f5-11e9-9516-d6866bcb1769.PNG)

If the ion-range is enabled, the outline disappears.

**Expected behavior:**
Remove this outline or make it assessible by variables.

**Steps to reproduce:**
Dark background plus disabled ion-range.

**Related code:**
`<ion-range min="0" max="25" step="5" [(ngModel)]="profile.run[ind]"
                         [disabled]="editMode?null:''" class="ion-no-padding">
                <ion-label slot="start"> -</ion-label>
                <ion-label slot="end">+</ion-label>
              </ion-range>`

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (...\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (...\AppData\Local\Android\Sdk)
   NodeJS            : v8.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.8.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-04-22 12:36
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17549.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-22 12:36 UTC
Labels: package: core, type: bug
