### ISSUE TITLE
bug: Months name in ion-datetime doesn't work as expected

### ISSUE THREAD

**Issue by jiboune** [ionic-team/ionic#21481] opened 2020-06-10 14:25 UTC
# Bug Report

**Ionic version:**
   
Ionic 4

**Current behavior:**
Using <ion-datetime> works has expected when I only set minDate and maxDate.  When I set monthNames values, it provokes a Zone error when I click on the input. 

![image](https://user-images.githubusercontent.com/6116409/84279637-89667b80-ab36-11ea-9e4a-edaa3d0b1a96.png)

Template : 

```
<ion-item>
     <ion-label> Pick a date </ion-label>
     <ion-datetime displayFormat="MMMM DD YYYY" [monthNames]="mymonthNames" doneText="Ok!"></ion-datetime>
</ion-item>
```

Component 

```
public mymonthNames = [];

constructor(..) {
     this.mymonthNames = this.getMonthNames();
}

getMonthNames(): Array<string> {
        return [
           "Janvier", "Fevrier", "Mars", "Avril", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Decembre"
        ];
    }
```
  
**Demo** 

http://plnkr.co/edit/kxqlbabo8SOAE4jK

**Datetime docs** 

[https://ionicframework.com/docs/api/datetime](url)
 

**Ionic info:**

```
   ionic (Ionic CLI)             : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2
```

**Comment by jiboune** [comment] 2020-06-11 08:23
Yes indeed, I can't see the error message but the structure is the same. I created a stackblitz using ionic 4 here (see tabs1) : [https://ionic-v4-angular-tabs-hgrcwv.stackblitz.io](url)

**Comment by liamdebeasi** [comment] 2020-06-11 15:05
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When you provide an array for `monthNames`, you need to provide all the months in the year. 

Your array does not include the month of May:

```
[
  "Janvier",
  "Fevrier",
  "Mars",
  "Avril",
  "Juin",
  "Juillet",
  "Aout",
  "Septembre",
  "Octobre",
  "Novembre",
  "Decembre"
];
```

**Closed by liamdebeasi** 2020-06-11 15:05 UTC
Labels: ionitron: needs reproduction
