### ISSUE TITLE
[4.0.0-rc.0] slidemenu template

### ISSUE THREAD

**Issue by Juexro** [ionic-team/ionic#16992] opened 2019-01-08 01:34 UTC
version: 
"@ionic/angular": "4.0.0-rc.0"

behavior:
1. choose slidemenu template
2. ionic cordova run android -l -c
3. slideslip to open the menu, but all click events will have no effect. bug ?

**Comment by Juexro** [comment] 2019-01-08 01:43
in ionic3, it works ok.

**Comment by paulstelzer** [comment] 2019-01-08 08:36
This could a duplicate of #16863 - I think it's the same root cause

**Comment by paulstelzer** [comment] 2019-01-15 09:21
As said before I htink it's a duplicate so I close this here

**Closed by paulstelzer** 2019-01-15 09:21 UTC
Labels: triage
