### ISSUE TITLE
bug: Tabs with dynamic paths do not update correctly

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#20321] opened 2020-01-28 18:00 UTC
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

If I use an IonTabs with routes that can change based on some condition, the new routes don't correctly take effect. The tabs will continue to link to the old route even when re-rendered with it updating. This is happening in a React app, although it's unclear to me that it's a React-specific problem.

**Expected behavior:**

I should be able to dynamically render the tabs and their routes and have them update correctly.

**Steps to reproduce:**

Please see the example app that I've linked to here, but basically it happens whenever you have dynamic routes in a tab.

**Related code:**
I have reproduced this with a GitHub repo [here](https://github.com/aub/tabpain). It includes a more complete writeup of the problem as well as steps to reproduce it.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.10

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.5.0 (/usr/local/Cellar/node/13.5.0/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by aub** [comment] 2020-01-28 19:40
It looks to me like what's happening is the IonTabBarUnwrapped component is relying on its [getDerivedStateFromProps](https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/navigation/IonTabBar.tsx#L48) function to be called in order to update its collection of current HREF values. But updating the HREFs in the children does _not_ cause that to be called, so the children are not recloned with their new values.

**Comment by austin43** [comment] 2020-01-29 02:29
Can confirm this issue.  I worked around it by setting a key in IonTabs to force a re-render when it changes.  Pretty ugly workaround, but it achieved what I needed at the time (though there's definitely some caveats to re-rendering the tab bar each time).

**Comment by austin43** [comment] 2020-01-29 02:43
May be a duplicate of #20109.

**Comment by aub** [comment] 2020-01-29 14:22
Right, I added a similarly ugly hack where when changing the routes we briefly stop rendering the tabs and then immediately put them back, and this seems to work fine, albeit with a flash. In my case, that's not the end of the world.

**Comment by austin43** [comment] 2020-01-30 18:13
@aub yeah, flicker is unacceptable for my use case unfortunately.  I've had to rethink my routing structure because of this.  I've ended up working around static routes with a top level provider maintaining dynamic data for my tab based views, and any nested views use dynamic routes.  Way less than ideal, but wasn't too hard to implement I suppose.

**Closed** 2020-02-14 20:36 UTC
Labels: package: react
