### ISSUE TITLE
[Ionic v4] override the opacity of ion-button if disabled 

### ISSUE THREAD

**Issue by Nazirovich** [ionic-team/ionic#16965] opened 2019-01-05 11:47 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Expected behavior:**

The 'disabled' rules (opacity: 1) should be applied.

**Steps to reproduce:**

1. Add disabled attribute to ion-button
2. Style it via pseudo or attribute selector of disabled
3. Css rules are not applied

**Related code:**

```
 <ion-button color="success" type="submit" [disabled]="true">
        LOG IN
 </ion-button>

When an ion-button is disabled, the following styles is used

.button-native[disabled] {
     cursor: default;
     opacity: .5;
     pointer-events: none;
}
```
```
/* Not applied */
ion-button[disabled],
ion-button[disabled="true"],
ion-button:disabled {
   --opacity: 1!important;
   opacity: 1!important;
}

/* Not applied */
.button-native[disabled] {
   --opacity: 1!important;
   opacity: 1!important;
}
```
**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.2
   @angular/cli                  : 7.1.0
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : not available

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.3.0
   OS     : Windows 10
```

**Comment by paulstelzer** [comment] 2019-01-15 09:30
Thanks for your issue! Your's is not working because opacity is set at the .button-native and there is no access to it from outside.

We have to add a new css custom property, e.g. `--opacity`. then you can use 

ion-button.button-disabled {
   --opacity: 1;
}

**Comment by giantpeach** [comment] 2019-01-17 08:43
The ability to style a button is a basic requirement. Moving from v3 to v4, styling has become a lot more difficult.

**Comment by paulstelzer** [comment] 2019-01-17 09:17
Ionic 4 is using web components and shadow DOM - of course this has benefits, but also disadvantages. But the benefits are higher. Styling components behind shadow dom is only possible with css custom properties and this is needed here :)

**Comment by Floppy1009** [comment] 2019-01-22 14:39
The opacity is missing in other elements as well. For instance I currently have the issue for ion-checkbox which I want to disable without changing the opacity (including the label).
Please add these css variables as well.
Is there another way to achieve this in the meantime? I tried to add click events and added "stopPropagation()" which didn't work unfortunately.
Any other idea?

**Comment by UntappedSolutions** [comment] 2019-02-05 17:12
I am using this bit of code and the first 2 work but not opacity. Any ideas?``

**Comment by troyanskiy** [comment] 2019-02-07 21:01
Hi @paulstelzer check that out https://www.npmjs.com/package/ngx-shadow-class

**Comment by jtth** [comment] 2019-03-20 23:47
Yeah, this is really frustrating, and the opacity variable does not work to fix things.

**Comment by Levy4u** [comment] 2019-04-26 19:58
I can't figure it out either. I have a bunch of forms that the admin fills out but want it disabled for users and not be hard to see. Right now i have to make a duplicate of every single form but make it a normal grid passing in the values to text fields.

**Comment by Kernolsie** [comment] 2019-04-30 09:11
Ditto, the --opacity variable does not seem to have any effect on my disabled button

**Comment by darkguy2008** [comment] 2019-05-27 03:49
So this issue is like a half a year old, any improvements?

**Comment by rphiller** [comment] 2019-05-28 11:53
Hey. there is a workaround.

Remove  `disabled` Attribute and add

`[style.pointerEvents]="'none'"`

**Comment by brandyscarney** [comment] 2019-06-10 18:31
@darkguy2008 I'd like to kindly remind you that we do have a COC and it should be followed by everyone including those commenting on our GitHub issues: https://github.com/ionic-team/ionic/blob/master/CODE_OF_CONDUCT.md

I'm sorry you think we are being lazy by not adding CSS variables. We're pretty transparent about what we are working on. We update our project board every other week: https://github.com/ionic-team/ionic/projects/3. We also have been doing releases bi-weekly: https://ionicframework.com/docs/release-notes. If you'd ever like to see what each specific member of the team is working on, we update the following public Google doc with our framework meeting notes every Monday: https://docs.google.com/document/d/1LrPDUkfXpqPIsghaSCxHyN1GIZ0TK2bwFxOZx2GKWtI/edit?usp=sharing.

CSS variables and Shadow DOM solve a lot of problems actually. They greatly reduce the bundle size, improving your app's startup time. They remove the need to compile all of Ionic's CSS (thus improving build times) by getting rid of the Sass dependency at build time. They allow you to dynamically change your application's theme at runtime without having to create double the CSS. Components that use CSS variables are required to be Shadow DOM (or scoped).  

The `--opacity` variable was actually added awhile ago, this issue just occurs because it isn't used in the case of a disabled button.  The fix should be changing the following in `button.scss`:

```
:host(.button-disabled) {
  pointer-events: none;
}

:host(.button-disabled) .button-native {
  cursor: default;
  opacity: .5;
  pointer-events: none;
}
```

to

```
:host(.button-disabled) {
  --opacity: .5;

  pointer-events: none;
}

:host(.button-disabled) .button-native {
  cursor: default;

  pointer-events: none;
}
```

If anyone would like to help out with this, PRs force us to take a look at issues and get fixes in faster. Otherwise I will add this to my list to look at in the near future. Thanks!

**Comment by Ivnosing** [comment] 2019-06-11 16:06
I will submit a PR tomorrow implementing this feature (my first one!).

**Comment by brandyscarney** [comment] 2019-06-11 17:47
@Ivnosing That would be great, thank you! Could you please add an example that shows the custom button opacity to one of the tests too, maybe here: https://github.com/ionic-team/ionic/blob/master/core/src/components/button/test/basic/index.html#L84-L87? This will help our testing so that we avoid a future regression. 🙂

**Closed** 2019-06-11 21:56 UTC
Labels: help wanted, package: core, type: feature request
