### ISSUE TITLE
Ionic 4 ion-refresher sometime fired when pulling up at any position

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionic#17891] opened 2019-03-27 01:37 UTC
Here my code.

```
<ion-header>
  <ion-toolbar>
    <ng-container *ngIf="!showSearchbar">
      <ion-title>Burmese Channel</ion-title>
      <ion-buttons slot="end">
        <ion-button (click)="(showSearchbar=!showSearchbar) &&
          focusSearchbar()">
          <ion-icon slot="icon-only" name="search"></ion-icon>
        </ion-button>
        <ion-button (click)="onSort($event)">
          <ion-icon slot="icon-only" name="funnel"></ion-icon>
        </ion-button>
      </ion-buttons>
    </ng-container>
    <ion-searchbar *ngIf="showSearchbar" [(ngModel)]="params.search"
      showCancelButton (ionCancel)="showSearchbar=false"
      (ionClear)="onClearSearch()" (keyup.enter)="onSearch()"></ion-searchbar>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="onReload($event)">
    <ion-refresher-content refreshingSpinner="crescent"></ion-refresher-content>
  </ion-refresher>
  <app-message-view *ngIf="isErrorView" icon="wifi" message="No Connection
    Available"></app-message-view>
  <app-message-view *ngIf="isEmptyView" icon="sad" message="No Data Found"></app-message-view>
  <ng-container *ngIf="isContentView">
    <ion-list>
      <ion-item button *ngFor="let channel of channels"
        [routerLink]="['/channels', channel.id]">
        <ion-thumbnail slot="start">
          <img [src]="getAssets('img/channels/' + channel.name + '.png')"
            src-fallback="assets/img/cover.png">
        </ion-thumbnail>
        <ion-label>{{ channel.name }}</ion-label>
      </ion-item>
    </ion-list>
    <ion-infinite-scroll threshold="100px" (ionInfinite)="onLoadMore($event)">
      <ion-infinite-scroll-content loadingSpinner="crescent"></ion-infinite-scroll-content>
    </ion-infinite-scroll>
  </ng-container>
</ion-content>

```

**Comment by kyawswarthwin** [comment] 2019-03-27 02:41
Same error here
https://github.com/ionic-team/ionic/issues/17784

**Comment by liamdebeasi** [comment] 2019-03-27 12:28
Hi there,

I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17784. Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-27 12:28 UTC
Labels: triage
