### ISSUE TITLE
Split Pane Bug?!

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic#10822] opened 2017-03-17 16:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have to pages which are displayed in a split pane. If the screen is not big enought I will push the 2nd page ontop of the first. Id the screen is big enought (split pane is active), I will just update the 2nd page.

This works really well expect when the screen is small, then I push the 2nd page and then resize so split pane would become active. If I then go back the content of the first page will be placed behind the header of the first page... I tried to resize the first page on view enter but it did not help.

**Expected behavior:**

Content should not be placed behind header.

**Steps to reproduce:**

Start Ionic 2 project, add split pane with two navs, each containing a page. When split pane is not active (screen is small) push 2nd page onto app root and then resize screen so split pane will become active. Then press the back button and content will be placed behind header of first page.

**Related code:**

Split Pane Site:
```
<ion-split-pane class="reversed-split-pane" (ionChange)="changePane()" when="lg">

    <ion-nav [class.mainNav]="applyClass" [root]="rootPage" #myNav swipeBackEnabled="false" main></ion-nav>
    <ion-nav class="secondNav" [root]="rootPage1" #myNav2 swipeBackEnabled="false" ></ion-nav>

</ion-split-pane>
```

Rootpage is Page 1 and rootPage1 is Page 2

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cordova CLI: 6.5.0
Ionic Framework Version: 2.1.0-201703061537
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-03-17 16:14
Hello, thanks for opening an issue with us, we will look into this.

**Comment by digaus** [comment] 2017-03-17 17:14
Seems to be kind of related to this issue but a bit more complex #10518

Basicly have split pane and starr with small screws, then push side ontop resize window to big screen and then pop the pushed side (press back)
Also updated to latest nightly which still has the bug

**Comment by wbhob** [comment] 2017-03-17 22:12
If you're building a mobile app, remember that you can't resize your device.

**Comment by manucorporat** [comment] 2017-03-17 22:32
@digaus the "steps to reproduce" your suggested are not enough to reproduce it.

Can you provide a repo that reproduces the issue? I guess you are using a lot of JS under the hood, to implement the master-detail app.

Also, would you like to help us design a good way to implement a master-detail API in ionic? maybe we could chat in slack?  looks like you are the first oe that have achieved that, and we would like to provide some kind of API to make it easier for the rest of developers.

**Comment by digaus** [comment] 2017-03-17 22:46
@wbhob
This app will be for Windows 10 aswell as you can see in the gif... 

@manucorporat

Doing this project as part of my bachlor and currently only have the code on my work computer. Tomorrow I will try to reproduce with just basic stuff if I can.
I am not very familiar API creation but I will help where I can.

**Comment by wbhob** [comment] 2017-03-17 22:48
Oh I though you were testing in the browser

**Comment by digaus** [comment] 2017-03-17 23:01
@manucorporat

There ja not really that much js involved, just using CSS with flex-direction: row-reverse; and some others stuff to resize the width since row-reverse will position the smaller 'menu' Page (here a nav) on the right. This was done so the 'menu' here the detail Page will be hidden by the split pane feature. Then I have a function which listens to the split pane change and removes the css which limits the with of the left pane. 
When you Click on a list element I just check if the width is below the split pane trashhold and just update the content of the right pane via a provider if not.
If it is below the trashhold I update the provider aswell but also push the page ontop of the rootNav

Hope this helps otherwise I will post code tomorrow

**Comment by digaus** [comment] 2017-03-18 22:56
Here is a short demo app https://github.com/digaus/ionic2-master-detail

**Comment by Jun711** [comment] 2017-03-27 21:53
@wbhob 
The device can't be resized but going from vertical view to landscape view would activate split pane if the device is a phablet(or depending on the threshold).

**Comment by anooprehman** [comment] 2017-06-08 07:43
@digaus 
I handled it by fixing the margin-top of .scroll-content to the required value.
For example: In your [demo app](https://github.com/digaus/ionic2-master-detail), try setting the margin-top for .scroll-content in master.scss.

**Comment by simonmicheal** [comment] 2017-10-09 15:57
Is there a fix for this? 
@anooprehman can you post your fix please 
Thanks

**Closed** 2018-11-01 19:56 UTC
Labels: ionitron: v3, v2
