### ISSUE TITLE
bug: Swiping in menu while page inits breaks touch input

### ISSUE THREAD

**Issue by Starofall** [ionic-team/ionic#18100] opened 2019-04-22 19:47 UTC
# Bug Report

Version: "@ionic/angular": "4.3.0"

**Current behavior:**
On loading a complex ionic app on a slow phone and swiping from left to right while the page loads, the following error is printed (on the animation of the menu):

```
zone.js:682 Unhandled Promise rejection: Cannot read property 'offsetWidth' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'offsetWidth' of undefined
    at Menu.loadAnimation (1hlqf399.entry.js:144)
    at Menu.onWillStart (1hlqf399.entry.js:184)
    at onWillStart (1hlqf399.entry.js:76)
    at tryToCapturePan (chunk-f56eaea8.js:483)
    at HTMLDocument.pointerMove (chunk-f56eaea8.js:459) TypeError: Cannot read property 'offsetWidth' of undefined
    at Menu.loadAnimation (http://192.168.178.93:8100/11.js:162:40)
    at Menu.onWillStart (http://192.168.178.93:8100/11.js:202:21)
    at onWillStart (http://192.168.178.93:8100/11.js:94:37)
    at tryToCapturePan (http://192.168.178.93:8100/0.js:497:13)
    at HTMLDocument.pointerMove (http://192.168.178.93:8100/0.js:473:38)
```
The code where the error happens is this code:
```
  async loadAnimation() {
        const width = this.menuInnerEl.offsetWidth; <- ! undefined error !
        if (width === this.width && this.animation !== undefined) {
            return;
        ....
```

After this exception it is no longer possible to tap anything.
Any following input will get the console message 
```chunk-f56eaea8.js:252 mousedown event dropped because of previous touch```

**Expected behavior:**
The case of "menuInnerEl === undefined" should be handeled for strange timing errors like this and not create an error, thereby not blocking user input.

**Comment by liamdebeasi** [comment] 2019-04-23 12:47
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17948.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-23 12:47 UTC
Labels: triage
