### ISSUE TITLE
bug: Blank project's starting page is scrollable even though it shouldn't be

### ISSUE THREAD

**Issue by JilReg** [ionic-team/ionic#21617] opened 2020-06-23 19:09 UTC
# Bug Report

**Ionic version:**
[x] **5.2.2**

**Current behavior:**
On a fresh blank project the start pages is scrollable by 1 or 2 pixels.

**Expected behavior:**
The page should not be scrollable at all.

**Steps to reproduce:**
ionic start > blank

**Related code:**

Demo Video: https://streamable.com/va026c

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 1.0.0)

System:

   NodeJS : v10.16.1 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2020-06-23 20:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This is due to the `forceOverscroll` property on `ion-content`. It adds 1-2 pixels which causes iOS to activate the rubber band overflow scrolling effect.

For more information, please see https://ionicframework.com/docs/api/content#properties.

**Closed by liamdebeasi** 2020-06-23 20:25 UTC
Labels: triage

**Comment by JilReg** [comment] 2020-06-24 07:02
@liamdebeasi Thanks!

If someone has the same problem, what helped me is to add `[forceOverscroll]="false"` to every `ion-content` including `app.component.html`.
