### ISSUE TITLE
bug: ios cannot connect to server after building to device, livereload works fine

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#20733] opened 2020-03-10 12:49 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

after building to ios, cannot connect to server with error: `[Error] Failed to load resource: A server with the specified hostname could not be found. (socket.io, line 0)`

**Expected behavior:**

connect to server

**Steps to reproduce:**

`$ ionic cordova prepare ios`
`$ ionic cordova run ios --device`

**Related code:**

```
insert short code snippets here
```

**Other information:**

After building to the device and launching it the ios device, ios6/7/8 cannot connect to the server, however, when running the live server with `$ ionic cordova run ios -l --external` the server and everything is connected to just fine. I haven't been able to find the resolution to this and there aren't any articles written about this. I have no idea where the issue can be with this. Android, of course, connects no problem but with ios I cannot, I have removed ios platform, node modules, the lock files, etc, and built again, however, to no avail. 

**Ionic info:**

```

   Ionic CLI                     : 6.2.0 (/Users/me/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res                          : 0.10.0
   native-run                             : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.8.0 (/usr/local/Cellar/node/13.8.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-03-10 13:11
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The framework does not manage deploying your app to devices.

**Closed by liamdebeasi** 2020-03-10 13:11 UTC
Labels: triage
