### ISSUE TITLE
bug(5.2.0): must not manipulate the layer below ion-alert modal.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic#21499] opened 2020-06-11 07:50 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.2.0**

**Current behavior:**
AlertController.create() on **iOS** can manipulate the layer below the alert modal.

**Expected behavior:**
must not control the layer below the alert modal.

**Steps to reproduce:**

**Related code:**

A sample application: https://naughty-saha-7ce12f.netlify.app/

↑Please emulate ios.

This source code: https://github.com/rdlabo/ion-alert-pointer/blob/master/src/app/home/home.page.ts

I didn't do anything special.

**Other information:**

This caused:

- https://github.com/ionic-team/ionic/pull/21060 
- https://github.com/ionic-team/ionic/blob/master/core/src/components/alert/alert.ios.scss#L22-L24

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.1 (/Users/sakakibara/dev/ionic-cli/packages/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res (update available: 0.14.0) : 0.11.0
   native-run                             : not installed

System:

   NodeJS : v12.16.2 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

```

**Comment by rdlabo** [comment] 2020-06-11 14:43
We can avoid this.

```
.alert-button .alert-button-inner {
  pointer-events: auto !important;
}
```

**Comment by liamdebeasi** [comment] 2020-06-11 15:10
Thanks for the issue. Can you please clarify what the bug is that you are seeing?

**Comment by rdlabo** [comment] 2020-06-11 15:20
@liamdebeasi Thanks for reply.

Please access https://naughty-saha-7ce12f.netlify.app in emulate ios.

- ion-content has click event `alert('ion-content clicked now')` .
- ion-button has click event for use alert-controller.

1. Please click center-button, and click `close` in ion-alert.

We expect close ion-alert only. but click event effect ion-content.

![スクリーンショット 2020-06-12 0 18 11](https://user-images.githubusercontent.com/9690024/84404771-3bd73500-ac42-11ea-9edf-83bb05b9146b.png)

**Comment by liamdebeasi** [comment] 2020-06-11 15:29
Thanks! I was able to reproduce this behavior. It looks like this is only happening when running in iOS mode on Google Chrome. I was unable to reproduce this behavior in Safari.

**Comment by liamdebeasi** [comment] 2020-06-11 15:37
Closing as a duplicate of https://github.com/ionic-team/ionic/issues/21503.

**Closed by liamdebeasi** 2020-06-11 15:37 UTC
Labels: needs: investigation
