### ISSUE TITLE
perf: app slowly respond after touch (start or end) on iOS

### ISSUE THREAD

**Issue by luckylooke** [ionic-team/ionic#13526] opened 2017-11-28 15:35 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

We have noticed this issue on iPhone5 using ion-slides component, but also elsewhere.. (not specific to ion-slides). When you drag slide to half of a screen and let it autoscroll, there is about 1 sec delay until animation starts. Also similar delayed reactions on tap controlled changes.

**Expected behavior:**

Instant not delayed reactions of an app

**Steps to reproduce:**

- install ionic blank
- put about 3000 span into html
- tap the content
- see long recalculates in devtools
- you can add some variable incrementation on tap event to see dealyed reaction

I was able to identify the problem, it is causing by universally applied css rule
```
:focus,
:active {
  outline: none;
}
```
I think the main purpose of this reset rule is because of some elements undesired default outlines
so the solution is to specify this elements. Please see the solution code below.

**Related code:**

Problem:
```
:focus,
:active {
  outline: none;
}
```
Solution:
```
:focus, 
input:active, 
textarea:active,
select:active,
button:active,
a:active { 
    outline: none;
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/user/project/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.3.0 ios 4.5.3 windows 5.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.11.3
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

I can make a PR if you are OK with the solution.

**Comment by kensodemann** [comment] 2017-11-28 16:33
Hello! Thank you for opening an issue with us!

This appears to be a duplicate of #12733.

We are always open to PRs. However, it might be best to wait until after v4 is released at this point. Issue #12733 was scheduled for inclusion in a release a while ago but I believe we ran into issues with device testing.

I will cc @mhartington & @brandyscarney to see what the status of this CSS is in the current development.

Thank you for using Ionic

**Comment by luckylooke** [comment] 2017-11-28 17:04
Yes seems to be same cause of both issues, I have not found it with search. But I think my title is more correct because not only scrolling list is problem but all touch actions, which is much worse problem then.

For anyone coming here, I have [posted my temporary fix of both issues here](https://github.com/ionic-team/ionic/issues/12733#issuecomment-347590079)

Happy coding :)

**Closed** 2018-12-08 09:39 UTC
Labels: ionitron: v3
