### ISSUE TITLE
MenuToggle Bug Ionic 3.5

### ISSUE THREAD

**Issue by duducp** [ionic-team/ionic#12349] opened 2017-07-13 21:27 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I created a simple navigation using the tabs. When the application opens, the Toggle menu works correctly; After entering the second page I disable the menu. To go back to the main page I'll root the root and re-enable the menu, but then toogle does not work anymore.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

SCOPED:
Page 1 -> Page 2 -> TAB (Page 3 e Page 4) -> TAB (METHOD EXIT)

-> PAGE 1
Open Menu (OK)
```
openMenu() {
   this.menuCtrl.toggle();
}
```
Go PAGE 2 (OK)
```
this.navCtrl.setRoot('PAGE2');
```

-> PAGE 2
Open PAGE TAB
```
openMenu() {
     let modal = this.modalCtrl.create('TAB-PAGE3', {
            project: this.paramsProject,
            userLogged: this.dataUserLogged,
            socket: this.socket,
            unreadNotifications: this.unreadNotifications,
            dataNotifications: this.dataNotifications
        });
        modal.present();
}
```

Exit PAGE TAB
```
exitProject() {
     this.navCtrl.setRoot('ProjetosPage');
}
```

-> PAGE 1
Open Menu (NOT OPEN)
```
openMenu() {
   this.menuCtrl.toggle();
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

[https://image.prntscr.com/image/QJ3fb60fQfu0QAU8Ze96PA.png](https://image.prntscr.com/image/QJ3fb60fQfu0QAU8Ze96PA.png)

**Comment by jgw96** [comment] 2017-07-14 15:06
Hello! Thanks for opening an issue with us! Would you mind sharing a plunker or repo we could use to reproduce this issue? Thanks!

**Comment by jgw96** [comment] 2017-07-20 16:14
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-20 16:14 UTC
Labels: needs info, v2
