### ISSUE TITLE
bug: Performance and Rendering issues on ion-item-group

### ISSUE THREAD

**Issue by evezzaro** [ionic-team/ionic#19339] opened 2019-09-13 13:40 UTC
# Bug Report

**Ionic version:**
[x] **4.5.0**

**Current behavior:**
When rendering more than 500 entries on a ion-item-group, the app presents heavy performance and rendering issues on the items' rendering and transitions to other pages. This problems are present only on Web/Android.

**Expected behavior:**
the same rendering speed and behavior as iOS which doesn't have any problem.

**Steps to reproduce:**
See video

https://www.dropbox.com/s/qxtkv32m72u4gvh/heartstream-rendering-problems.mp4?dl=0

**Related code:**
```
<ion-item-group *ngFor="let x of XXX">

			<ion-item-divider>
				<ion-label class="ion-text-uppercase">
					<ion-text color="primary">
						<h2>{{ x.letter }}</h2>
					</ion-text>
				</ion-label> 
			</ion-item-divider>

			<ion-item lines="none" on-click="goToDetails(x.id)" *ngFor="let c of CCC">{{ c.name +' '+ c.surname }}</ion-item>
</ion-item-group>
```

**Other information:**
This issue shows up only on Android or Web while iOS is smooth. 

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/elevasrl/.nvm/versions/node/v12.7.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 9 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/elevasrl/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v12.7.0 (/Users/elevasrl/.nvm/versions/node/v12.7.0/bin/node)
   npm               : 6.10.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by DavidStrausz** [comment] 2019-09-13 16:39
You could try adding a `trackBy` function to your `ngFor` loop to improve rendering performance.

https://medium.com/better-programming/improving-angular-ngfor-performance-through-trackby-ae4cf943b878

**Comment by liamdebeasi** [comment] 2019-09-16 13:28
Thanks for the issue. Trying to render 500 `ion-item-group` elements at once is going to cause performance issues no matter how efficient the components are. In addition to using `trackBy` you should also consider using virtual scroll so you only have to render the items that are visible on the screen.

I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2019-09-16 13:28 UTC
Labels: triage
