### ISSUE TITLE
Tabs not working with async pipe unwrapping a firebase list

### ISSUE THREAD

**Issue by littlemercury** [ionic-team/ionic#12529] opened 2017-08-01 06:16 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Tabs are not generated when using a FirebaseListObservable containing tab data, that is unwrapped by the async pipe. It seems like the tab rendering is prioritised over other components and then not refreshed when the async pipe unwraps data. So if I'm correct, the tabs render with an empty array, and when the observable is updated with data from firebase, nothing happens to re-render the tabs.

**Expected behavior:**
Tabs should be generated and destroyed based on the contents of the data coming through the async pipe

**Steps to reproduce:**

- define tabs in firebase
- query firebase to produce a FirebaseListObservable
- route that list through the async pipe to create dynamic tabs
- see that tabs are not created.

- Usethe same list through the async pipe to create any other component and see that component IS created.

- Create dynamic tabs with a regular array and see that tabs are created
 
- Only the combination of the async pipe and <ion-tab> component doesn't seem to work

**Related code:**

```
import { Component } from '@angular/core';
import { AngularFireDatabase, FirebaseListObservable } from 'angularfire2/database';

@Component({
  template: '
<ion-tabs>
  <ion-tab *ngFor="let tab of tabList | async" tabIcon="{{tab.icon}}" tabTitle="{{tab.title}}" [root]="tab.root"></ion-tab>
</ion-tabs>
'})
export class TabsPage {
  
  tabList: FirebaseListObservable<any>;

  constructor(public af: AngularFireDatabase) {
   
          this.tabList = this.af.list('/tabs/'); 
  }
}
```
Use the following firebase data:
```
"tabs" : {
    "age_manager" : {
      "icon" : "people",
      "root" : "ViewNippersPage",
      "title" : "Age Manager"
    },
    "guardian" : {
      "icon" : "home",
      "root" : "ViewNippersPage",
      "title" : "Nippers"
    },
    "settings" : {
      "icon" : "settings",
      "root" : "SettingsPage",
      "title" : "Settings"
    }
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 
    @ionic/cli-plugin-ionic-angular : 1.4.0 
    @ionic/cli-utils                : 1.6.0 
    ionic (Ionic CLI)               : 3.6.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.1.1
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 25.2.3
    Node              : v6.10.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    npm               : 3.10.10 
```

**Comment by jgw96** [comment] 2017-08-01 14:17
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/10632

**Closed by jgw96** 2017-08-01 14:17 UTC
