### ISSUE TITLE
bug: Ionic 5 interaction with TinyMCE editor on iOS

### ISSUE THREAD

**Issue by Jahrenski** [ionic-team/ionic#20672] opened 2020-03-02 18:16 UTC
**Ionic version:**
[x] **5.0.3**

**Current behavior:**
I have an interaction problem between Ionic 5 and TinyMCE in my app on iOS where scrolling when the focus is in the editor, dismisses the keyboard. In Ionic 4, I could use the undocumented "no-blur" attribute which prevented the issue to arise but this behavior does not work anymore in Ionic 5 / Angular 9.

**Expected behavior:**
Scrolling should not dismiss the keyboard. It works fine on an ion-input.

**Steps to reproduce:**
Use this repro: [Ionic-v5-TineMCE](https://stackblitz.com/edit/ionic-v5-tinymce)
On iOS, set the focus in the editor. 
The keyboard should open.
Attempt to scroll the page.
When you stop scrolling, the keyboard gets dismissed. Probably by a forced blur.

**Other information:**
This occurs from safari directly as well.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\richard\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.3
   @angular-devkit/build-angular : 0.900.2
   @angular-devkit/schematics    : 9.0.2
   @angular/cli                  : 9.0.2
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v12.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-03-03 14:19
Thanks for the issue. Can you provide this as a separate GitHub repo? StackBlitz almost never works on any of my mobile devices 😢. (I can download the zip from stackblitz, but it is never exported properly for some reason).

**Comment by Jahrenski** [comment] 2020-03-03 14:58
No problem! Here it is:
[https://github.com/Jahrenski/ionic-v5-tinymce](https://github.com/Jahrenski/ionic-v5-tinymce)

**Comment by liamdebeasi** [comment] 2020-03-03 15:35
@Jahrenski Can you make sure you uploaded all the necessary files? Your package.json seems to be missing.

**Comment by Jahrenski** [comment] 2020-03-03 17:09
My bad, I uploaded a level too deep aha!
It should be up to date, let me know if anything is missing.

**Comment by liamdebeasi** [comment] 2020-03-03 18:44
Hmm I am still getting errors when I try to run the app:

```
An unhandled exception occurred: Project does not exist.

[error] Error: Project does not exist.
    at WorkspaceNodeModulesArchitectHost.findProjectTarget (/Users/liamdebeasi/Ionic/ionic-v5-tinymce/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:122:19)
```

Can you double check that your dependencies are correct?

**Comment by Jahrenski** [comment] 2020-03-03 21:18
This is fixed. I had not tested it after moving it to github, my bad.
It should work now.

**Comment by liamdebeasi** [comment] 2020-03-05 19:29
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. While the `no-blur` attribute is undocumented, its functionality has not changed from v4 to v5. I was able to reproduce this same behavior in Ionic 4.

From what it looks like, the `iframe` inside of your component is what is receiving focus/blur. You will need to set `no-blur` on the iframe not the `editor` component if you would like to achieve the behavior you described in your original post.

**Closed by liamdebeasi** 2020-03-05 19:29 UTC
Labels: triage
