### ISSUE TITLE
bug: Scroll position not restored for android

### ISSUE THREAD

**Issue by Sebadst** [ionic-team/ionic#21540] opened 2020-06-15 18:29 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Scroll a list, click on an item that brings you to another page, then click on the back button. The scroll position is not restored to where you left it for Android, even though it seems to work for iOS.
**Expected behavior:**

The scroll position should be restored.
**Steps to reproduce:**

You can reproduce it by running the ionic conference app. I actually had opened the original issue [there](https://github.com/ionic-team/ionic-conference-app/issues/1316) even though there was also some other issues with the scrolling that I mentioned there.

As far as I can see this issue should have been already solved [here](https://github.com/ionic-team/ionic/issues/14737) however it does not seem to be working for me on Android (I tested it with `ionic serve --lab`).

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/home/seba/Android/Sdk)
   NodeJS            : v10.20.1 (/usr/bin/node)
   npm               : 6.14.4
   OS                : Linux 5.3
```

**Comment by liamdebeasi** [comment] 2020-06-15 18:57
Thanks for the issue. What device/version of Android are you testing on?

**Comment by Sebadst** [comment] 2020-06-15 18:59
I simply used `ionic serve --lab`, didn't test it on a real device yet

**Comment by liamdebeasi** [comment] 2020-06-15 19:13
What browser/platform are you reproducing this issue on?

**Comment by Sebadst** [comment] 2020-06-15 19:47
I am on Firefox 77.0.1 (64 bit) for Ubuntu. Btw, I am having even a bigger issue which is the fact that, whenever I click on an item and the page opens, it is automatically scrolled based on the previous page (still on Android only) :confused: so, basically if I click on the first item the scroll will be fine in the new page, since I didn't scroll the list. If I scroll the list let's say until the middle, the page that opens will be scrolled until middle and so on..please let me know if you think I should open another issue for that.

**Comment by liamdebeasi** [comment] 2020-06-15 21:07
Thanks for the follow up. Looks like this is a duplicate of https://github.com/ionic-team/ionic/issues/20821.

**Closed by liamdebeasi** 2020-06-15 21:07 UTC
Labels: triage
