### ISSUE TITLE
Back button does not route to correct page when using shared components

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic#16928] opened 2019-01-01 23:20 UTC
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.0**

**Current behavior:**
I use a shared header component across several pages which displays a profile picture, name, and followers. When I click on the profile picture, I am sent to the artist page as expected, but when I click the back button I am routed to the tab root page instead of the previous page.

**Expected behavior:**

When clicking the back button, you should be routed back to the previous page instead of the tab navigation root page. 

**Steps to reproduce:**

Here's a short video showing how clicking on the artist header routes to the proper artist page but when clicking back, it routes to the root of each tab navigation stack. **Note:** I made sure to leave in the URL of the browser at the top so you can see how routes are changing on each click:

https://streamable.com/5ind2

On the Home Tab -> Select Artist -> Select Release -> Click on Artist Header -> Click Back -> **routes to Home Page instead of Release Page**

**Related code:**

In order to route to the artist page from the artist header component I use the following code: 

**release.page.html** (where I use my component)
```
    <div *ngIf="artistHeader">
      <app-artist-header [artist]="artistHeader" [user]="userHeader"></app-artist-header>
    </div>
```

**artist-header.component.html** (the html of the header component)

```
  <ion-avatar (click)="goToArtist(artist.artistUID)">
    <img [src]="artist.artistImageURL">
  </ion-avatar>
```

**artist-header.component.ts**
```
  goToArtist(uid: string) {
    this.navCtrl.navigateForward(`tabs/${this.route.parent.snapshot.routeConfig.path}/${uid})`)
  }
```
Where `navCtrl` is the `NavController` and `route` is the `ActivatedRoute`. I figured this was the best way to determine which tab we are on when routing a shared component. Please advise if there is a better way. But regardless, I thought that `navigateForward` explicitly told the router to move forward and that the back button should go to the most previous route.

When using the shared component, I import the `SharedModule` in to that page module. My `shared.module.ts` looks like the following in order to properly declare and export components:

```
@NgModule({
  imports: [
    CommonModule,
    IonicModule,
    FormsModule,
    ReactiveFormsModule
  ],
  declarations: [ArtistHeaderComponent],
  exports: [ArtistHeaderComponent]
})
```

It's also my understanding if I were to put the `(click)` event on the actual component HTML like `<app-artist-header (click)="goToArtist()">` in the `release.page.html` then it should work properly, however, I cant make the entire component clickable (just the profile picture) because I have a follow button on the right hand side of the component.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.12.0-beta.2
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.2.0-beta.2
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 7 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

Let me know what else you need to help debug! Thanks :)

**Comment by paulstelzer** [comment] 2019-01-02 08:07
Thanks for the issue! But what's your problem? If you tap back you come back to the tabs page, which is correct

**Comment by uncvrd** [comment] 2019-01-02 08:37
Hey @paulstelzer ! My issue is that logically, when I hit the back button, I should go back a single page, and not back to the root of the navigation stack.

Here's the desired workflow, I've highlighted the difference:

Home Page -> Click Artist Page -> Routed to Artist Page -> Click release from Artist -> Routed to Release Page -> Click Artist profile picture -> Routed to Artist Page -> Click back button -> **Routed to Release Page**.

Here's what happens: 

Home Page -> Click Artist Page -> Routed to Artist Page -> Click release from Artist -> Routed to Release Page -> Click Artist profile picture -> Routed to Artist Page -> Click back button -> **Routed to Home Page**.

It seems like the routing forgets my history and just resets back to the home page? Does that make sense? If I click the back button at any other stage of the process it correctly jumps back a single page. For example, if I go:

Home Page -> Click Artist Page -> Routed to Artist Page -> Click release from Artist -> Routed to Release Page -> Click back button -> Routed to Artist Page (see how it goes back a single page?)

Does that help?

**Comment by paulstelzer** [comment] 2019-01-02 08:40
Please create a repo here on Github, so I can clone it and test it myself

**Comment by btsiders** [comment] 2019-01-02 15:57
Here's a repo based on my one from #16897 

https://github.com/btsiders/ionic-sub-page/tree/bug-balls

It does the same thing whether you are using

**Comment by paulstelzer** [comment] 2019-01-02 15:59
I will also wait for the issue owner for his repo

**Comment by uncvrd** [comment] 2019-01-02 18:50
Hi @paulstelzer here is a very basic repo you can clone: https://github.com/uncvrd/shared-components-ionic.git

I added two pages and a shared component. You can replicate the problem by doing the following:

1. Press button to route to artist page
(page transitions to artist page)
2. Press button to route to release page
(page transitions to release page)
3. Click the profile picture (this is the shared component)
(this will route you forward to an artist page again
4. Click the back button
**This routes you to the home page**

What should happen:
4. Click back button
(this routes back to the release page as that was the most recent page I was on)

**Comment by supperdsj** [comment] 2019-01-08 09:54
same issue here

**Comment by supperdsj** [comment] 2019-01-09 02:37
means this issue cause by i use components like angular style in route config?
but i can not use IonicPage in ionic4 any more, so what the difference between pages and components and how can i use pages :)

**Comment by supperdsj** [comment] 2019-01-14 10:00
`<ion-button color="primary" fill="clear" (click)="navCtrl.goBack();">
        <ion-icon slot="start" name="arrow-back"></ion-icon>back
      </ion-button>`
work for me

**Comment by Benjvfr** [comment] 2019-01-14 10:03
Yes that works but only if you clicked on the back-button. If you swipe to go back, same issue has before.

**Comment by paulstelzer** [comment] 2019-01-15 09:43
I close this as duplicate of #15216

I think my gif demonstrate the issue well -> https://github.com/ionic-team/ionic/issues/15216#issuecomment-447334318 (after navigating back it opens the first tab)

and I think it's the same issue like described here

**Closed by paulstelzer** 2019-01-15 09:43 UTC
Labels: needs: investigation, package: angular
