### ISSUE TITLE
VirtualScroll not working

### ISSUE THREAD

**Issue by speedtreammanga** [ionic-team/ionic#12429] opened 2017-07-21 13:32 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Trying to display list-items using infiniteScroll and virtualScroll but here's what I end up with:
note that the list is working properly without the virtualScroll.

![y8y6pijqov](https://user-images.githubusercontent.com/10254541/28465527-11f2f97c-6df7-11e7-8d02-7fc4663f2a13.gif)

**Expected behavior:**
The virtualScroll should display the list and its list-items properly in the ion-content div container.

**Steps to reproduce:**
Checkout the related code section

**Related code:**

```
<ion-content class="list-mini-content">
  <div class="list-mini">
    <ion-searchbar [(ng-model)]="queryText" (ionInput)="getItems($event)" class="search-bar"></ion-searchbar>
    <div>
      <ion-list [virtualScroll]="people.items" [approxItemHeight]="'40px'" [headerFn]="myHeaderFn">

        <ion-item-divider *virtualHeader="let header">
            {{ header }}
        </ion-item-divider>

        <ion-item *virtualItem="let person"  (click)="goToProfile(person)">
          <ion-avatar item-left>
            <preload-image class="item item-avatar" [ratio]="{w:1, h:1}" [src]="person.image"></preload-image>
          </ion-avatar>
          <h2>{{person.name}}</h2>
          <p class="item-email">{{person.email}}</p>
        </ion-item>
      </ion-list>
      <ion-infinite-scroll (ionInfinite)="doInfinite($event)">
        <ion-infinite-scroll-content></ion-infinite-scroll-content>
      </ion-infinite-scroll>
    </div>
  </div>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:
    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

System:
    Node       : v6.11.0
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10 
```

**Comment by jgw96** [comment] 2017-07-21 14:29
Hello, thanks for using Ionic. What device/browser is this on?

**Comment by speedtreammanga** [comment] 2017-07-21 19:06
@jgw96 Hi,
Tried it on **safari**@10.0.3 & **chrome**@59.0.3071.115 with both **ios** and **android** browser simulator.

**Comment by jgw96** [comment] 2017-07-25 14:50
Hmm, unfortunately I cannot reproduce this issue. Would you mind posting a small repro case we could use to repro? Thanks!

**Comment by jgw96** [comment] 2017-08-01 15:53
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-08-01 15:53 UTC
Labels: needs info, v2
