### ISSUE TITLE
Runtime Error - Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by AlessandroSchneiderSignUP** [ionic-team/ionic#11564] opened 2017-05-08 21:47 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
It happens in 50% of the times I serve ionic.

**Expected behavior:**
I expect the error not to occur.

**Steps to reproduce:**
ionic serve
open browser

Stack
TypeError: Cannot read property 'indexOf' of null
at Tab.NavControllerBase._cleanup (http://localhost:8100/build/main.js:46089:59)
at Tab.NavControllerBase._transitionFinish (http://localhost:8100/build/main.js:45991:18)
at t.invoke (http://localhost:8100/build/polyfills.js:3:9655)
at Object.onInvoke (http://localhost:8100/build/main.js:38985:37)
at t.invoke (http://localhost:8100/build/polyfills.js:3:9606)
at e.run (http://localhost:8100/build/polyfills.js:3:7019)
at NgZone.run (http://localhost:8100/build/main.js:38854:62)
at Array. (http://localhost:8100/build/main.js:45939:25)
at MDTransition.Animation._didFinish (http://localhost:8100/build/main.js:11897:29)
at MDTransition.Animation._playProgress (http://localhost:8100/build/main.js:11254:18)
at MDTransition.Animation._playDomInspect (http://localhost:8100/build/main.js:11220:14)

Ionic Framework: 2.2.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 7.9.0
OS Platform: OS X Yosemite
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

posted also here: https://github.com/driftyco/ionic-app-scripts/issues/966 
Not really sure where it does belong to. Thanks!

**Comment by jgw96** [comment] 2017-05-08 21:55
Hello, thanks for using Ionic! Are you using lazy loading?

**Comment by rapropos** [comment] 2017-05-08 22:10
I don't believe lazy loading is an option given those framework and app-scripts versions.

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-09 07:50
Hi, thanks for your quick reply. I am not using lazy loading in the manner as it has been introduced with Ionic 3.

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-10 20:44
Today I realized that this error does not occur when I build android for browser platform and use the created files in www folder. Maybe this might be a hint for you. Thank you!

**Comment by jgw96** [comment] 2017-05-11 16:48
Hello @AlessandroSchneiderSignUP, i, unfortunately, cannot reproduce this issue. Could you post a repo we could use to reproduce this?

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-12 09:15
Hello @jgw96 - since it is an enterprise product I invited you to the private repo. I hope you can use this. You have to reload the site a few times to get the error. Thank you.

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-16 12:39
@jgw96  Could you have a look in the repo? Thanks!

**Comment by jgw96** [comment] 2017-05-17 14:27
Hello @AlessandroSchneiderSignUP, unfortunately, i do not see the invitation to the repo. Could you send it to justin@ionic.io ?

**Comment by jgw96** [comment] 2017-06-02 15:49
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-02 15:49 UTC
Labels: needs info, v2
