### ISSUE TITLE
ion-datetime does not display as local time

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic#17666] opened 2019-03-03 13:03 UTC
# Bug Report

**Ionic version:**
[x] **4.0.2**

**Current behavior:**
For ion-datetime when a datetime value such as '1994-12-15T13:47:20.789+05:00', the time is displayed as the UTC Timezone.

**Expected behavior:**
Expect the time to be displayed as the local/offset time. ie 1994-12-14T18:47:20. Also picker should display the local time. 

**Steps to reproduce:**

Try below code using the following offest value: 1994-12-15T13:47:20.789+05:00
```
<ion-item color="light">
  <ion-label>Date</ion-label>
      <ion-datetime value="1994-12-15T13:47:20.789+05:00" display-format="YYYY-MM-DDTHH:mm" ></ion-datetime>
 </ion-item>
```

**Html Display - Showing UTC Time**
<img width="488" alt="screen shot 2019-03-04 at 12 00 07 am" src="https://user-images.githubusercontent.com/10624315/53695524-c9599180-3e10-11e9-88a5-513c74715681.png">

**Picker - Showing as UTC Time**
<img width="494" alt="screen shot 2019-03-04 at 12 00 16 am" src="https://user-images.githubusercontent.com/10624315/53695528-d6768080-3e10-11e9-8d47-c3de1e3157cc.png">

**Comment by liamdebeasi** [comment] 2019-03-04 13:19
Hi there,

Thanks for the issue! I am going to close this as a duplicate of #17587. Please note that there is also a PR open that fixes this issue and will be merged in soon.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-04 13:19 UTC
Labels: triage

**Comment by bkarv** [comment] 2019-03-05 06:53
Well not exactly duplicate #17587 as this refers to the picker value not displaying local time. This item refers to the actual displayed valued once selected not showing as local time. 

Are you able to confirm the pr fix will also display the picked value as local time?

**Comment by liamdebeasi** [comment] 2019-03-05 13:33
Hi there,

These two issues stem from the same problem, so the PR will fix both.

Thanks!

**Comment by bkarv** [comment] 2019-03-11 20:53
Thanks for confirming appreciate your efforts on the datetime bugs
