### ISSUE TITLE
origin file:// versus http://

### ISSUE THREAD

**Issue by teddykh** [ionic-team/ionic#15057] opened 2018-08-05 22:36 UTC
I came across 3 issues on this topic and all 3 are now closed with no solution.
#12607 
#10311 
#8129 

My ionic is first calling a authorization endpoint to get an access-token for further calling other APIs. The first call give a 403 Forbidden and it seems to me it is because of the origin = file://.

Is there any updates about this issue?

**Comment by olegd1c** [comment] 2018-08-07 09:39
Angular6 + Capacitor. I have the same problem.

**Comment by dwieeb** [comment] 2018-08-07 14:38
@olegd1c Capacitor doesn't use `file://` to serve web assets. Perhaps elaborate on what you're referring to?

**Comment by teddykh** [comment] 2018-08-07 18:16
@dwieeb Advanced HTTP Plugin (wrapped in Ionic) seems to solve the problem.
Thanks!!

**Comment by dwieeb** [comment] 2018-08-07 18:30
@teddykh Great to hear! Yes, I believe the Advanced HTTP Plugin is the most common option. 😄

**Comment by dwieeb** [comment] 2018-08-07 21:28
Closing! The resolution I believe is this: make sure you have the latest [Web View plugin](https://github.com/ionic-team/cordova-plugin-ionic-webview), which uses `http://` to serve app assets, not `file://`.

If the service you're using still doesn't like the origin, you should look through the checklist in [my original comment](https://github.com/ionic-team/ionic/issues/15057#issuecomment-410841420) to see available workarounds.

Thanks!

**Closed by dwieeb** 2018-08-07 21:28 UTC
Labels: triage

**Comment by brandyscarney** [comment] 2018-08-07 21:47
I am going to close this since it seems the original issue is resolved by https://github.com/ionic-team/ionic/issues/15057#issuecomment-410841420. Please feel free to continue the discussion on this issue or [open a new issue](https://github.com/ionic-team/ionic/issues/new/choose) with details including ways for us to reproduce if you are still running into this. Thanks!
