### ISSUE TITLE
bug: ion-tabs not working when path is empty

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic#18753] opened 2019-07-10 12:17 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
when defining the tab routes, if using an empty `path` as root of the tabs, no error is thrown but the tab navigation does not work

**Expected behavior:**
This should work or at least be documented that it is not supported, but I don't see why it wouldnt work. The idea is that I want the pages to have `/settings` for example instead of having `/tabs/settings`

**Steps to reproduce:**
Use this as routes for the Tabs component:
```typescript
const routes: Routes = [
  {
    path: '',
    component: TabsPage,
    children: [...]
  }
]
```
Add multiple children, and try to navigate between them in the Tab Bar, nothing will happen

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.2 (/Users/guillaumeroyer/.nvm/versions/node/v10.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.5 (update available: 0.2.7)

System:

   NodeJS : v10.1.0 (/Users/guillaumeroyer/.nvm/versions/node/v10.1.0/bin/node)
   npm    : 6.10.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2019-07-10 13:53
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16949. Please follow that thread for updates on this issue.

Thanks!

**Closed by liamdebeasi** 2019-07-10 13:53 UTC
Labels: triage
