### ISSUE TITLE
TypeError: undefined is not a function at WebAnimationsPlayer.play

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic#13117] opened 2017-10-11 19:40 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When running app on Android `5.0.0` I get an error when tapping on a list item and navigating to some page:
```
"TypeError: undefined is not a function
    at WebAnimationsPlayer.play (file:///android_asset/www/build/vendor.js:140614:22)
    at TransitionAnimationPlayer.play (file:///android_asset/www/build/vendor.js:140019:91)
    at file:///android_asset/www/build/vendor.js:139732:20
    at Array.forEach (native)
    at TransitionAnimationEngine._flushAnimations (file:///android_asset/www/build/vendor.js:139725:21)
    at TransitionAnimationEngine.flush (file:///android_asset/www/build/vendor.js:139409:32)
    at InjectableAnimationEngine.AnimationEngine.flush (file:///android_asset/www/build/vendor.js:140442:32)
    at file:///android_asset/www/build/vendor.js:135163:30
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14356)
    at r.run (file:///android_asset/www/build/polyfills.js:3:9523)"
```

**Expected behavior:**

It should not throw an error.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

cli packages: (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0-201710101530
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v8.6.0
    npm               : 2.15.12
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : pr
```

**Comment by kensodemann** [comment] 2017-10-11 21:00
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

The object you reference is not used in our code at all. It is part of Angular, but I don't see that it is used by us at all.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Closed by kensodemann** 2017-10-11 21:00 UTC

**Comment by rolandjitsu** [comment] 2017-10-14 13:19
@kensodemann thanks for pointing that out (that this is not use by you). It helped!

**Comment by rolandjitsu** [comment] 2018-06-07 06:41
@mnasyrov I cannot recall. But this looks like an Angular issue with `@angular/animations`.

**Comment by mnasyrov** [comment] 2018-06-10 10:47
I found that [web-animations-js](https://github.com/web-animations/web-animations-js) polyfill was missed, it fixed my issue.

**Comment by Ramachandrajoshi** [comment] 2018-08-13 15:17
for me issue was caused by angular mat-tabs.
installed  web-animations-js via npm.
added 
import 'web-animations-js';
to pollyfills.ts file and problem has been fixed.
