### ISSUE TITLE
bug: Ion-ripple not working properly inside a ion-card with ion-item on card-content

### ISSUE THREAD

**Issue by Arieru** [ionic-team/ionic#21210] opened 2020-05-05 04:41 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Ion ripple doesn't cover the whole card component when there is a ion-item inside ion-card-content.
![awB84I4auF](https://user-images.githubusercontent.com/14150736/81035093-05342f00-8ecc-11ea-958c-05b4a9772c25.gif)

**Expected behavior:**
Ion ripple will cover the whole content of card including header and content(body).

**Steps to reproduce:**
Just create a list of `ion-card` and then add` ion-item` to `ion-card-content` then add `ion-ripple effect` between` ion-card` tag and `ion-header` tag

**Related code:**

```
<ion-card class="ion-activatable ripple-parent">
    <ion-ripple-effect></ion-ripple-effect>
   <ion-card-header>HELLO</ion-card-header>
   <ion-card-content>
       <ion-item>
          <ion-avatar slot="start">
              <img src="assets/icon/favicon.png">
          </ion-avatar>
          <ion-label>CONTENT</ion-label>
          <ion-label slot="end">10000</ion-label>
       </ion-item>
    </ion-card-content>
</ion-card>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.0 (C:\Users\ARIEL\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.2
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-05-06 13:31
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `ion-item` has a background color that you should set to `transparent`. The `ion-item` element is layered on top of `ion-ripple-effect` so it gives the appearance that the ripple effect does not cover the entire element.

**Closed by liamdebeasi** 2020-05-06 13:31 UTC
Labels: triage
