### ISSUE TITLE
[v4-beta.19] Navigation broken when using multiple pages with lazy loaded tabs.

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#16772] opened 2018-12-16 18:31 UTC
# Bug Report

**Ionic version:**

[x] **4.0-beta.19**

**Current behavior:**

When I have more than one page using tabs, and navigate from one to another, then clicking on the tab buttons changes the url but does not change the displayed page (router-outlet does not update).

![output](https://user-images.githubusercontent.com/73378/50057315-946a6680-0160-11e9-8c3a-cdd86375e990.gif)

**Expected behavior:**

After clicking on a tab button I see the associated page.

**Steps to reproduce:**

1. Start on a page using tabs.
2. Navigate to a different page using at least two tabs.
3. Clicking on the tab buttons does not update the tab pages.

**Related code:**

First tabs page
+ [template](https://github.com/Eraldo/coapp/blob/602b827a11c9883214a6b7f03aae47877b1c8e40/frontend/src/app/caves/caves.page.html#L1)
+ [routes](https://github.com/Eraldo/coapp/blob/602b827a11c9883214a6b7f03aae47877b1c8e40/frontend/src/app/caves/caves.router.module.ts#L6)

Second tabs page
+ [template](https://github.com/Eraldo/coapp/blob/602b827a11c9883214a6b7f03aae47877b1c8e40/frontend/src/app/fair/fair.page.html#L1)
+ [routes](https://github.com/Eraldo/coapp/blob/602b827a11c9883214a6b7f03aae47877b1c8e40/frontend/src/app/fair/fair.router.module.ts#L6)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.11.3
   @angular-devkit/schematics    : 7.1.3
   @angular/cli                  : 7.1.3
   @ionic/angular-toolkit        : 1.2.0

System:

   NodeJS : v11.0.0 (/usr/local/Cellar/node/11.0.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by paulstelzer** [comment] 2018-12-16 18:58
Thanks for your issue! We are aware of this problem.

It's a duplicate of #16411

PS: We had the same issue today via #16765

I think I have to adjust the issue title of #16411 , so more people find this. There is also a workaround to make it work

**Closed by paulstelzer** 2018-12-16 18:58 UTC
Labels: triage

**Comment by Eraldo** [comment] 2018-12-16 19:20
> There is also a workaround to make it work
I read through the issue and was not able to find a workaround that works around this issue.
@paulstelzer Can you maybe point to what exactly you mean with that? :)

**Comment by Eraldo** [comment] 2018-12-20 12:30
Works nicely now with `4.0.0-rc.0`. Thank you! :D

**Comment by paulstelzer** [comment] 2018-12-20 12:32
Thanks for letting us know :)
