### ISSUE TITLE
NavController insert method not working with ionic 3.5.0

### ISSUE THREAD

**Issue by yekmyk** [ionic-team/ionic#12251] opened 2017-07-04 09:22 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After upgrading to ionic-angular 3.5.0 NavController insert method is not working and breaks navigation.

**Expected behavior:**
Insert method should insert a component at given index.

**Steps to reproduce:**
Plunker to reproduce: https://plnkr.co/edit/JD5PafgqOpoG2h7oJl6C?p=preview
- Click "Push PageC" button to push "Page C" into navigation stack.
- Click "Insert PageB" button to insert "Page B" between "Page A" and "Page C"
- Try to go back with the back button. "Page B" is not inserted to navigation stack. Back button is not working.

Same code with ionic 3.4.0 works as expected: https://plnkr.co/edit/LTCBhxAgub0xRT4IS3ei?p=preview

**Related code:**
NA

insert any relevant code here
NA

**Other information:**
NA

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

```

**Comment by jibon57** [comment] 2017-07-04 10:39
I am facing similar problem with remove() method. I am using ionic latest 3.5.0 :(

**Comment by peterkelly** [comment] 2017-07-04 14:41
Possible duplicate of https://github.com/ionic-team/ionic/issues/12238

**Comment by yekmyk** [comment] 2017-07-04 16:47
I can confirm this problem is solved in nightly.

**Comment by jgw96** [comment] 2017-07-05 14:26
Hello all, i am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12238. Thanks for using Ionic!

**Closed by jgw96** 2017-07-05 14:26 UTC
