### ISSUE TITLE
bug: Segment button checked attribute not working on initial load

### ISSUE THREAD

**Issue by gr99t** [ionic-team/ionic#19289] opened 2019-09-06 16:31 UTC
# Bug Report

**Ionic version:**
[x] **4.9.0**

**Current behavior:**
Segment button is not checked initially when attribute "checked" is set

**Expected behavior:**
Segment button is checked initially 

**Related code:**
```
<ion-segment>
<ion-segment-button checked>
<ion-label>Test 1</ion-label>
</ion-segment-button>
<ion-segment-button>
<ion-label>Test 2</ion-label>
</ion-segment-button>
</ion-segment>
```
[Stackblitz](https://stackblitz.com/edit/ionic-v4-angular-tabs-cczcoh?file=src%2Fapp%2Ftab1%2Ftab1.page.html)

**Other information:**
Now and then it is checked on page reload (at least on Stackblitz using Chrome, never worked on local installation). 
I added two additional segments and reloaded the page lots of times and I got all possible combinations of checked buttons or none at all.

Just some examples:
1:
![one_2](https://user-images.githubusercontent.com/45254028/64442066-74ece280-d0cf-11e9-9599-dc67e058371f.png)
2:
![two_2](https://user-images.githubusercontent.com/45254028/64443255-d1510180-d0d1-11e9-86f9-f82e106d7f0d.png)     
3:
![two](https://user-images.githubusercontent.com/45254028/64442062-71f1f200-d0cf-11e9-8a9d-bf0f53b976e4.png)

**Comment by brandyscarney** [comment] 2019-09-13 20:00
Thank you for the issue! I was able to reproduce this on a Codepen (without Angular): https://codepen.io/ionic/pen/RwbJOEG?editors=1010

I'm not able to reproduce it in `4.8.0` though. Are you all seeing the same?

cc @manucorporat

**Comment by Ivnosing** [comment] 2019-09-16 10:18
I am encountering this issue after upgrading `@ionic/angular` from `4.7.1` to `4.9.0`.

Setting a value for each `ion-segment-button` as @intodevelopment said solves the problem for me.

**Comment by gr99t** [comment] 2019-09-16 14:19
Yes, it was working as expected prior 4.9.0. 

Using values as @intodevelopment mentioned seems to work for mee too.

**Comment by srepollock** [comment] 2019-10-31 20:01
@gr99t have you tried running on a later version or are you locked into 4.9.0?

**Comment by gr99t** [comment] 2019-11-03 13:37
@srepollock still not working for me in `4.11.3` when I omit the `value` property

**Comment by neoemptor** [comment] 2019-11-11 09:10
Yeah, checked doesn't work at all, but the following works.
As a quick fix, just initialise your segment variable to the default value in your page.ts.
Make sure all your segment buttons have a value set.

**Comment by thameurr** [comment] 2019-12-26 06:46
>   <ion-segment-button value="test" checked>

Fixed by adding value. thanks

**Comment by brandyscarney** [comment] 2020-01-02 21:07
Just to update this issue, this is related to this PR: https://github.com/ionic-team/ionic/pull/19449

We're still discussing the pros & cons of this, but it is one of our top priorities.

**Comment by liamdebeasi** [comment] 2020-01-17 23:31
Thanks for the issue! This issue has been resolved via https://github.com/ionic-team/ionic/pull/19449 and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-01-17 23:31 UTC
Labels: package: core, type: bug
