### ISSUE TITLE
bug: Heavy bug with multiple layouts based on routing

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic#21260] opened 2020-05-10 21:20 UTC
We use latest Ionic (Project generated with latest CLI)

For different reasons, we work with different layouts. The problem is, if we change the layout and then go back to the previous layout, we have a bug. The layout is broken and only its reload can fix it.

Here is a stackflash: https://stackblitz.com/edit/ionic-5-layouts-bug

Please open the sideNav > Navigate to Login > Click "To the App" and you will see that the layout is broken.

**Comment by liamdebeasi** [comment] 2020-05-11 21:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic Angular apps require the use of `ion-router-outlet` when doing routing. Replacing `router-outlet` with `ion-router-outlet` in `app.component.html` fixed the issue for me.

**Closed by liamdebeasi** 2020-05-11 21:07 UTC
Labels: triage
