### ISSUE TITLE
Ion-item-sliding BUG - sliding out on ion-item-options 

### ISSUE THREAD

**Issue by cedche99** [ionic-team/ionic#12428] opened 2017-07-21 11:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a problem with ion-item-sliding, the ion-item-options don't want slide out when i slide ion-item out.. 

**Expected behavior:**

The ion-item-options slide out when i slide out the ion-item-sliding

**Steps to reproduce:**

**Related code:**

```
<div padding>
    <ion-list [hidden]="!initDBFinish">
      <ion-item-sliding *ngFor="let site of listSites ">
        <ion-item>

          <button ion-button item-start>
            <ion-icon name="pin"></ion-icon>
          </button>
          <button ion-item text-wrap (click)="start(site)">
            {{site.getName()}}
          </button>

          
        </ion-item>
        <ion-item-options side="right">
          <button ion-button color="danger" (click)="removeSiteList(site)">
            <ion-icon name="trash"></ion-icon>
            {{ 'delete' | translate }}
          </button>
        </ion-item-options>
      </ion-item-sliding>
      
    </ion-list>

   
  </div>
```

**Other information:**

 I'm my app i use : Translate, and the variable "listSites" in the for is setting when i recover the data in my database

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : not installed
    ios-sim    : 5.0.13
    npm        : 3.10.9
```

**Comment by jgw96** [comment] 2017-07-21 14:33
Hello, thanks for opening an issue with us. Would you mind posting a repo we could use to reproduce this? Also, what OS / browser are you seeing this on?

**Comment by jgw96** [comment] 2017-08-10 19:35
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-08-10 19:35 UTC
Labels: needs info, v2
