### ISSUE TITLE
cannot read property 'getattribute

### ISSUE THREAD

**Issue by mobinius-shreesha** [ionic-team/ionic#12204] opened 2017-06-29 14:43 UTC
Hello,
i am getting 'cannot read property 'getattribute' of null' error when i use zoom attribute in ion-slides.please help out this.

**Comment by AmitMY** [comment] 2017-06-29 14:44
- Please fill the issue template fully
- Please supply code/plunker for reproduction

**Comment by mobinius-shreesha** [comment] 2017-06-29 14:46
what issue template

**Comment by AmitMY** [comment] 2017-06-29 14:48
When you open a new issue, It has [this template](https://raw.githubusercontent.com/ionic-team/ionic/master/.github/ISSUE_TEMPLATE.md), and we can't help if you do not fill it out

**Comment by mobinius-shreesha** [comment] 2017-06-29 15:09
**Ionic version:**  (check one with "x")
[ 2.x] 


**I'm submitting a ...**  (check one with "x")
[ x] bug report


**Current behavior:**
When tap on ion-slides,i am trying zoom image,but it throgh error like cannot read property 'getattribute'

**Expected behavior:**
Need to pinch image on ion-slides

**Related code:**

```
insert any relevant code here
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.4.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.6.1
```
insert the output from ionic info here

**Comment by jgw96** [comment] 2017-06-29 15:19
Hey @mobinius-shreesha , would you mind sharing a minimal repo or plunker that we can use to reproduce this please? Thanks!

**Comment by jgw96** [comment] 2017-07-05 16:55
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Sethur** [comment] 2017-08-01 15:00
There is no need to provide a full plunker demo, the issue is trivially reproducible by creating an empty tabs project (using `ionic start testApp tabs`) with a current ionic install and fill in the following code on any page:

```javascript 
  <ion-slides zoom direction="horizontal">
    <ion-slide>  
      <img src="assets/imgs/some-image.png">
    </ion-slide>
  </ion-slides>
```
Then, using the developer tools of any current Chrome install (currently 60.0.3112.78), emulate a touch event by double clicking the single image in the slider. This will produce the above mentioned error:

```
swiper-zoom.js:364 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at toggleZoom (swiper-zoom.js:364)
    at swiper-zoom.js:476
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3863)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (core.es5.js:3837)
    at swiper-events.js:527
```

I came across this error while trying to get the ionic-slider **zoom** option to work. As it seems there is still no fix for this. Issue #5039 mentions that this was moved into a feature request #114, which, however, does not seem to exist any longer. The current framework documentation does however state that **zoom** is a valid option so I would suggest fixing either this issue or removing the option altogether.

For completeness, this is my `ionic info` output:
```
global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    OS                : Windows 7
    npm               : 3.10.10
```

**Comment by AmitMY** [comment] 2017-08-01 15:28
Try `[zoom]="true"`
There is always a need to create a plunker, as with one, anyone can view your bug and have their input, and without it there are extra steps not anyone is willing to do (for me, I will not wait for `npm install`)

**Comment by Sethur** [comment] 2017-08-02 09:48
[zoom]="true" made no difference. I tried creating a plunker by creating a Github repository demonstrating the bug first and pushing that to plnkr.co, but this is apparently not the way to do it. Using the npm package **plunk** gave me a memory error, so I gave up for now.

If you find the time, please either point me towards creating a plunk from a local project or clone my repository at [https://github.com/Sethur/sliderbugtest] and wait for the npm install.

The example sliders are in the about tab, both should give the same issues (no zooming and getAttribute error on double click when using chrome dev tools).

**Comment by dylanvdmerwe** [comment] 2017-08-22 15:45
Please also see https://github.com/ionic-team/ionic/issues/5039 for code on creating a directive which should get you moving in the right direction.

**Closed** 2018-11-01 19:48 UTC
Labels: ionitron: v3, slides, v2
