### ISSUE TITLE
Ion-menu Error

### ISSUE THREAD

**Issue by trevordowdle** [ionic-team/ionic#19571] opened 2019-10-07 17:30 UTC
Steps to reproduce the error.

1.  ionic start myApp tabs
2. Go to app.component.html and add an ion-menu

```
<ion-app>  
    <ion-menu side="start" menuId="first">  
        <ion-header> 
          <ion-toolbar color="primary"> 
            <ion-title>Start Menu</ion-title> 
          </ion-toolbar>
        </ion-header>
        <ion-content>
          <ion-list>
            <ion-item>Menu Item</ion-item>
            <ion-item>Menu Item</ion-item>
          </ion-list>
        </ion-content>
  </ion-menu>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
```

No menu is visible, and the following error shows up in the logs:

**Menu: must have a "content" element to listen for drag events on.**

Expected to see a menu.

**Comment by liamdebeasi** [comment] 2019-10-07 17:42
Thanks for the issue. As per the docs, you should be specifying the content's ID via the `contentId` prop: https://ionicframework.com/docs/api/menu#properties.

Can you give that a try and let me know if it works?

**Comment by trevordowdle** [comment] 2019-10-07 21:57
Thank you, that was the cause of the error.  I assumed that the error was the reason why the menu was not visible.  

But the menu is still not showing up.  Maybe it's just a matter of the **starter tabs template** and ion-menu being incompatible..

**Comment by liamdebeasi** [comment] 2019-10-08 13:10
Glad to hear the issue is fixed. You can definitely add a sidemenu to a tabbed application. The Ionic Conference Demo app is a sidemenu + tabs application. I would recommend looking at the source code for info on how to implement this: https://github.com/ionic-team/ionic-conference-app

I am going to close this as the original issue has been resolved. Thanks!

**Closed by liamdebeasi** 2019-10-08 13:10 UTC
Labels: triage
