### ISSUE TITLE
bug: HTML5 Audio controls disappear when using ion-slides on iOS 13

### ISSUE THREAD

**Issue by hartmanbfl** [ionic-team/ionic#19714] opened 2019-10-21 13:13 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

User has an app with a series of ion-slides, each one containing an audio player.  The first slide shows a normal audio player with controls and a time bar.  Subsequent slides do not have the time bar.  This is seen on multiple devices running iOS 13 (works in iOS 12 and Android). 

**Expected behavior:**

The audio players on each slide should have the same controls as the first slide.

**Steps to reproduce:**

Make a simple app with multiple ion-slides.  Put an HTML5 audio player with the controls attribute set on each slide.  The first slide will show an audio player with pause/play button, and the time control slide.  Subsequent slides will briefly show the time control slide, but it will disappear leaving only a play/pause button. 

**Related code:**

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : 0.6.0 (update available: 0.8.0)
   native-run  : not installed

System:

   NodeJS : v12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment] 2019-10-22 14:14
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I was able to reproduce this outside of Ionic (and Swiper): https://codepen.io/liamdebeasi/pen/zYYNrGN. I believe this may be a bug in Safari 13/WebKit.

**Closed by liamdebeasi** 2019-10-22 14:14 UTC
Labels: triage

**Comment by hartmanbfl** [comment] 2019-10-22 14:59
Yes, I see that as well.  Thanks, Liam, for looking into this from an Ionic perspective and putting together the codepen.  Hopefully I can find an answer elsewhere to the actual root cause.

**Comment by liamdebeasi** [comment] 2019-10-22 15:28
I will likely be submitting an issue on the WebKit bug tracker 👍

**Comment by hartmanbfl** [comment] 2019-10-23 05:27
Ok, sounds good.  Thanks!
