### ISSUE TITLE
android white screen forever after splash

### ISSUE THREAD

**Issue by novaknole** [ionic-team/ionic#17451] opened 2019-02-09 13:43 UTC
# Bug Report

**Ionic version:**

[x] **4.10.2**

**Current behavior:**

When running app on android, it's stuck on white screen forever. but works great when running ionic serve or ionic lab.

**Expected behavior:**

it should run smoothly also for android app.

**Steps to reproduce:**

I tested this on Honor 10 and Redmi Note 6 Pro. both have 8.1.0 android version and android system webview updated as 6th february 2019. So why is it stuck on white screen forever? I am using ionic cordova run android which builds the app directly on my phone through usb.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by StefanRein** [comment] 2019-02-11 13:15
Our application and the starter templates aren't stuck forever, on android 8.
Is the blank starter application working on these devices? If so, then: 
Check out the chrome inspector and debug your application and your requests.

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

Compare with a blank starter for example and track the error down.

**Comment by liamdebeasi** [comment] 2019-02-15 13:49
Hi @novaknole,

Thanks for opening an issue with us! Would you be able to share a repository with the code required to reproduce this issue?

Thanks for using Ionic!

**Comment by robingenz** [comment] 2019-02-19 07:52
same problem on android 8 with cordova android version 6.3.0

Fix: update cordova android (e.g. to version 7.1.4)
`ionic cordova platform remove android`
`ionic cordova platform add android@7.1.4`

**Ionic info:**


```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\robin.genz\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

 (C:\Users\robin.genz\AppData\Local\Android\android-sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-03-28 15:15
Hi @robingenz,

Do you have a code that I can use to reproduce this issue? 

Thanks!

**Comment by robingenz** [comment] 2019-03-28 18:21
Sure. I've created a repository: https://github.com/robingenz/ionic-issue-17451-example

**Comment by liamdebeasi** [comment] 2019-03-29 15:21
Hi there,

`cordova-plugin-ionic-webview` requires `cordova-android` 6.4+, but it looks like you have 6.3.0 installed. I was getting a white screen with 6.3.0 as you suggested, but not with 6.4.0. Please update `cordova-android` to at least 6.4.0.

I am going to close this, but for further questions feel free to post on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-29 15:21 UTC
Labels: triage
