### ISSUE TITLE
Ionic Tab (Tabbar) shown when Keyboard is shown

### ISSUE THREAD

**Issue by sgleser** [ionic-team/ionic#17438] opened 2019-02-08 11:54 UTC
# When using 2 or more input fields on an ionic page which has a Tab-bar, on keyboard show the tab bar is not hidden.
If we click on an input field the keyboard will be shown and the tab bar hidden. After that if we directly click into another input field the keyboard is still shown, but the tab bar is shown too.
If we click outside of the input field the keyboard will be hidden and the tabbar shown. 

**Ionic version:**
[x] 5.0.0

**Current behavior:**
Tabs are shown when Keyboard is shown and because of that the content is moved with the height of the tabbar.

**Expected behavior:**
Do not show `ion-tabs` when keyboard is open.

**Steps to reproduce:**
1. We need an ionic page with a tab bar and at least two input fields.
2. Click on an input field (Keyboard is shown, tabbar hidden)
3. Click on another input field (while the keyboard is still shown)
4. Keyboard will be still shown (correct), but the tab bar will be shown too.

**Related code:**

```
<form [formGroup]="form1">
	<ion-list lines="full">
		<ion-item>
			<ion-label position="fixed">Input 1</ion-label>
			<ion-input class="form-control" formControlName="input1" clearInput></ion-input>
		</ion-item>
		<ion-item>
			<ion-label position="fixed">Input 2</ion-label>
			<ion-input class="form-control" formControlName="input2" clearInput></ion-input>
		</ion-item>
</form>

<ion-tabs>
    <ion-tab-bar slot="bottom">
        <ion-tab-button tab="tab1">
	    <ion-label>Tab 1</ion-label>
	</ion-tab-button>
        <ion-tab-button tab="tab2">
	    <ion-label>Tab 2</ion-label>
	</ion-tab-button>
    </ion-tab-bar>
 </ion-tabs>
```

**Comment by liamdebeasi** [comment] 2019-02-08 13:34
Closing as a duplicate of #17407

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-08 13:34 UTC
Labels: triage
