### ISSUE TITLE
Allow for more than just a string as a toast message

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic#12239] opened 2017-07-03 12:29 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The toastcontroller only accepts strings as a message.

**Expected behavior:**
I would like to be able to add simple makrup / layout to the message: italic, links, bold to make more meaningful toasts for my users

**Other information:**

**Comment by AmitMY** [comment] 2017-07-03 13:18
Duplicate of https://github.com/ionic-team/ionic/issues/12106
Has an open PR https://github.com/ionic-team/ionic/pull/12108
That PR will be reviewed soon

**Comment by Remco75** [comment] 2017-07-03 13:22
thnx, and sorry, could not find an open issue for this. (and of course did not look into the PR's ;-))

**Comment by jgw96** [comment] 2017-07-03 14:33
Hello all! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12106

**Closed by jgw96** 2017-07-03 14:33 UTC
