### ISSUE TITLE
bug: not show side menu in android 4.4 in ionic 4

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#18032] opened 2019-04-14 18:21 UTC
# Bug Report

**Ionic version:**
4.2.0

**Current behavior:**
when click on icon menu only darking page not show side menu in android 4.4.
in another android version this work correctly.

**Expected behavior:**
when click on icon menu show side menu

**Related code:**

```
<ion-app>
  <ion-menu (ionWillOpen)="initUser()">
    <ion-header text-center>
      <!-- <ion-toolbar color="primary">
        <ion-title>Menu</ion-title>
      </ion-toolbar> -->
      <ion-grid>
        <ion-row>
          <ion-col >
            <div>
              <ion-avatar style="width: 100px;height: 100px;">
                <img [src]="user.imgPath" *ngIf="user && user.imgPath">
                <ion-icon name="contact" *ngIf="!user || !user.imgPath" style="font-size:128px;color: lightgray;"></ion-icon>
              </ion-avatar>
            </div>
          </ion-col>
          <ion-col align-self-center>
            <div>
              <h2 no-margin *ngIf="user">{{ user.firstName + ' ' + user.lastName }}</h2>
              <h5 no-margin *ngIf="user">{{ '0'+user.mobile }}</h5>
              <ion-badge color="danger" style="font-size: 14px;">{{('VERSION' | translate)+' : '+
                appVersion}}</ion-badge>
            </div>
          </ion-col>
        </ion-row>
      </ion-grid>
      <ion-badge color="light" *ngIf="user" style="font-size: 18px;color:blue">{{('CREDIT' | translate)+' :
        '+(user.Balance | rial)}}</ion-badge>
      <ion-spinner name="dots" color="light" *ngIf="!user"></ion-spinner>

    </ion-header>

    <ion-content>
      <ion-list>
        <!-- <ion-list-header>
          Navigate
        </ion-list-header> -->
        <span *ngFor="let mnu of menuItems">
          <ion-menu-toggle auto-hide="true" *ngIf="mnu.url && mnu.url.length>0">
            <ion-item tappable (click)="processUrl(mnu.url)" style="border-bottom:1px solid lightgrey;">
              <ion-icon slot="start" color="secondary" [name]="mnu.icon"></ion-icon>
              <ion-label>
                {{mnu.title | translate}}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
          <!-- <ion-item style="border-bottom:1px solid lightgrey;" *ngIf="!mnu.url || mnu.url.length===0">
            <ion-icon slot="start" color="secondary" [name]="mnu.icon"></ion-icon>
            <ion-label>
              {{mnu.title | translate}}
            </ion-label> -->
            <!-- <ion-badge color="success" *ngIf="mnu.value" style="font-size: 16px;">{{mnu.value}}</ion-badge>
            <ion-badge color="primary" *ngIf="mnu.title==='CREDIT' && user" style="font-size: 16px;">{{user.Balance |
              rial}}</ion-badge>
            <ion-spinner name="dots" color="primary" *ngIf="mnu.title==='CREDIT' && !user"></ion-spinner> -->
          <!-- </ion-item> -->
        </span>
      </ion-list>
    </ion-content>
  </ion-menu>
  <ion-router-outlet main></ion-router-outlet>
</ion-app>
```
package.json:
```
"dependencies": {
    "@angular/common": "~7.2.13",
    "@angular/core": "~7.2.13",
    "@angular/forms": "~7.2.13",
    "@angular/http": "~7.2.13",
    "@angular/platform-browser": "~7.2.13",
    "@angular/platform-browser-dynamic": "~7.2.13",
    "@angular/router": "~7.2.13",
    "@ionic-native/android-permissions": "^5.4.0",
    "@ionic-native/barcode-scanner": "^5.4.0",
    "@ionic-native/core": "^5.4.0",
    "@ionic-native/deeplinks": "^5.4.0",
    "@ionic-native/device": "5.4.0",
    "@ionic-native/diagnostic": "5.4.0",
    "@ionic-native/file": "5.4.0",
    "@ionic-native/file-opener": "5.4.0",
    "@ionic-native/file-transfer": "5.4.0",
    "@ionic-native/location-accuracy": "5.4.0",
    "@ionic-native/network": "5.4.0",
    "@ionic-native/social-sharing": "5.4.0",
    "@ionic-native/splash-screen": "5.4.0",
    "@ionic-native/status-bar": "5.4.0",
    "@ionic/angular": "4.2.0",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/materialize-css": "^1.0.6",
    "com.lampa.startapp": "^6.1.6",
    "cordova": "^8.1.2",
    "cordova-android": "7.1.4",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-opener2": "2.2.0",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "4.0.1",
    "cordova-plugin-mauron85-background-geolocation": "^3.0.1",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-request-location-accuracy": "^2.2.3",
    "cordova-plugin-sms-receive": "^1.0.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "3.2.0",
    "cordova.plugins.diagnostic": "4.0.12",
    "core-js": "^2.6.5",
    "ionic-plugin-deeplinks": "^1.0.19",
    "ionicons": "4.5.6",
    "lodash": "4.17.11",
    "materialize-css": "^1.0.0",
    "moment": "2.24.0",
    "moment-jalaali": "0.8.3",
    "parse-push-plugin": "git+https://github.com/taivo/parse-push-plugin.git",
    "phonegap-plugin-barcodescanner": "^8.0.1",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.4.0",
    "ws": "^6.2.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.13",
    "@angular/compiler-cli": "~7.2.13",
    "@angular/language-service": "~7.2.13",
    "@ionic/angular-toolkit": "^1.5.1",
    "@ionic/lab": "1.0.24",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~11.13.4",
    "codelyzer": "~5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.0.3",
    "tslint": "~5.15.0",
    "typescript": "~3.2.2"
  }
```
**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)

```

**Comment by royanon** [comment] 2019-04-15 04:06
Same issue in iOS 10

**Comment by shomid** [comment] 2019-04-15 04:51
problem is css style.
-webkit-transform attribute is problem.

**Comment by liamdebeasi** [comment] 2019-04-15 13:34
Hi there,

I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17729.

Thanks for using Ionic!

**Closed** 2019-04-15 13:37 UTC
Labels: triage
