### ISSUE TITLE
plane-outline icon is not ouline

### ISSUE THREAD

**Issue by nimamyscreen** [ionic-team/ionic#10583] opened 2017-02-28 01:26 UTC
as you closed my first issue and asked me to report based your issue template, I have to say I'm using Ionicons in my react native app and I realized that plane-outline icon is not actually outline.

**Current behavior:**
plane-outline Icon is not outline

**Expected behavior:**
plane-outline should be outline

![eee](https://cloud.githubusercontent.com/assets/16332824/23387517/f8e19b84-fd97-11e6-9ffa-cf62ac9a779b.PNG)

**Comment by brandyscarney** [comment] 2017-03-02 21:02
@nimamyscreen Thanks for the issue! We ask that issues be reported through our template so that we have enough information to understand and reproduce the issue. :) Where are you seeing the plane not using outline? Is it only in the browser at http://ionicframework.com/docs/v2/ionicons/? Here is what I'm seeing on that page:

<img width="980" alt="screen shot 2017-03-02 at 3 52 05 pm" src="https://cloud.githubusercontent.com/assets/6577830/23526602/aa29b3e4-ff60-11e6-91c2-cc5adc3db77c.png">

If you're seeing the incorrect icon in your React Native app - could you give us some more information on how you're including and using [Ionicons](https://github.com/driftyco/ionicons)? Thanks in advance!

**Comment by nimamyscreen** [comment] 2017-03-03 01:40
this is so weird, I'm using exactly the same link in my browsers (Chrome,Firefox) but the Icon is not outline.

**Comment by jgw96** [comment] 2017-03-06 15:05
Hey @nimamyscreen , on my macbook pro with both the latest stable version of chrome, the latest stable version of firefox and the latest stable version of safari I see the correct icons. Are you on a windows machine?

**Comment by jgw96** [comment] 2017-03-13 16:17
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by antoine92190** [comment] 2017-05-09 00:31
I am also experiencing this issue on iOS device.
You can reproduce and see that "plane-outline" is not outline on either Xcode simulator or real device.

**Comment by brandyscarney** [comment] 2018-05-15 19:16
Thanks @oleh-kolinko! I was able to reproduce it from an iPhone in Safari. I don't believe this is something that will be fixed, since we have redesigned ionicons and the latest version doesn't include outline icons: http://ionicons.com/

I will confirm this with @bensperry.

**Closed** 2018-11-28 22:19 UTC
Labels: icons, ionitron: v3, v2
