### ISSUE TITLE
 Cannot find module '@ngx-translate/core'. 

### ISSUE THREAD

**Issue by webmobiles** [ionic-team/ionic#12210] opened 2017-06-30 07:30 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.5**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

$ ionic start myionic
```
? What starter would you like to use: super
✔ Creating directory ./myionic - done!
[INFO] Fetching app base
       (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template super
       (https://github.com/ionic-team/ionic-starter-super/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
> git init
✔ Running command - done!
> git add -A
✔ Running command - done!
> git commit -m "Initial commit" --no-gpg-sign
✔ Running command - done!

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

Run your app in the browser (great for initial development):
  ionic serve

Run on a device or simulator:
  ionic cordova run ios

Test and share your app on a device with the Ionic View app:
  http://view.ionic.io
  
? Link this app to your Ionic Dashboard to use tools like Ionic View? Yes

You will need to login in order to link this app. Please run the following commands to do so.
  ionic login - login first
  ionic link - then link your app

Go to your newly created project: cd ./myionic

```

then I did:

$ionic serve:

```
Errors display:

[INFO] Starting app-scripts server: --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0 - Ctrl+C to
       cancel
[09:21:15]  watch started ... 
[09:21:15]  build dev started ... 
[09:21:15]  clean started ... 
[09:21:15]  clean finished in less than 1 ms 
[09:21:15]  copy started ... 
[09:21:15]  transpile started ... 
[09:21:17]  typescript: src/app/app.component.ts, line: 23 
            Cannot find module '@ngx-translate/core'. 

      L23:  import { TranslateService } from '@ngx-translate/core'

[09:21:17]  typescript: src/app/app.module.ts, line: 29 
            Cannot find module '@ionic-native/camera'. 

      L29:  import { Camera } from '@ionic-native/camera';
      L30:  import { GoogleMaps } from '@ionic-native/google-maps';

[09:21:17]  typescript: src/app/app.module.ts, line: 30 
            Cannot find module '@ionic-native/google-maps'. 

      L29:  import { Camera } from '@ionic-native/camera';
      L30:  import { GoogleMaps } from '@ionic-native/google-maps';
      L31:  import { SplashScreen } from '@ionic-native/splash-screen';

[09:21:17]  typescript: src/app/app.module.ts, line: 34 
            Cannot find module '@ngx-translate/core'. 

      L34:  import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
      L35:  import { TranslateHttpLoader } from '@ngx-translate/http-loader';

[09:21:17]  typescript: src/app/app.module.ts, line: 35 
            Cannot find module '@ngx-translate/http-loader'. 

      L34:  import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
      L35:  import { TranslateHttpLoader } from '@ngx-translate/http-loader';

[09:21:17]  typescript: src/pages/item-create/item-create.ts, line: 5 
            Cannot find module '@ionic-native/camera'. 

       L5:  import { Camera } from '@ionic-native/camera';

[09:21:17]  typescript: src/pages/login/login.ts, line: 8 
            Cannot find module '@ngx-translate/core'. 

       L8:  import { TranslateService } from '@ngx-translate/core';

[09:21:17]  typescript: src/pages/map/map.ts, line: 4 
            Cannot find module '@ionic-native/google-maps'. 

       L4:  import { GoogleMaps, GoogleMap, GoogleMapsEvent, LatLng, CameraPosition } from '@ionic-native/google-maps';

[09:21:17]  typescript: src/pages/settings/settings.ts, line: 7 
            Cannot find module '@ngx-translate/core'. 

       L7:  import { TranslateService } from '@ngx-translate/core';

[09:21:17]  typescript: src/pages/signup/signup.ts, line: 7 
            Cannot find module '@ngx-translate/core'. 

       L7:  import { TranslateService } from '@ngx-translate/core';

[09:21:17]  typescript: src/pages/tabs/tabs.ts, line: 3 
            Cannot find module '@ngx-translate/core'. 

       L2:  import { NavController } from 'ionic-angular';
       L3:  import { TranslateService } from '@ngx-translate/core';

[09:21:17]  typescript: src/pages/tutorial/tutorial.ts, line: 6 
            Cannot find module '@ngx-translate/core'. 

       L6:  import { TranslateService } from '@ngx-translate/core';

[09:21:17]  typescript: src/providers/user.ts, line: 38 
            Property 'share' does not exist on type 'Observable<Response>'. 

      L37:    login(accountInfo: any) {
      L38:      let seq = this.api.post('login', accountInfo).share();

[09:21:17]  typescript: src/providers/user.ts, line: 60 
            Property 'share' does not exist on type 'Observable<Response>'. 

      L59:    signup(accountInfo: any) {
      L60:      let seq = this.api.post('signup', accountInfo).share();

[09:21:17]  dev server running: http://localhost:8100/ 

[INFO] Development server running
       Local: http://localhost:8100
       
[09:21:17]  copy finished in 2.35 s 
[09:21:17]  watch ready in 2.41 s 

```
**Expected behavior:**
no erros

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.0
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 

```

**Comment by danielsogl** [comment] 2017-06-30 07:53
This is not an ionic related problem.

**Comment by janpio** [comment] 2017-06-30 08:13
Please post at the forum, where problems like this can be debugged individually with you: https://forum.ionicframework.com/

**Comment by webmobiles** [comment] 2017-06-30 11:05
sorry, but 1: I did know the packages problem is not ionic problem,  i've solved installing those packages, but someone wrote the ionic templates, the sources are where, 2 forum is for individual problems if you change the code i think

**Comment by janpio** [comment] 2017-06-30 11:22
Actually you are right and I can reproduce the problem!

Still, wrong repo to report this: The packages you had/have problem with are required by the starter, not `ionic`, which is this repo for the actual Ionic Framework part (`ionic-angular`) and where you posted. This issue could have been created with `ionic-cli` or `ionic-starter-super` to be in the right place.

So I went ahead and did just that: https://github.com/ionic-team/ionic-starter-super/issues/118

Thanks for reporting this, but you can close it here now.

**Comment by webmobiles** [comment] 2017-06-30 11:25
thanks, i'm an new on Ionic, just i've started today, must to learn all about those packages...

**Closed** 2017-06-30 11:30 UTC

**Comment by janpio** [comment] 2017-06-30 11:31
As this turns out to be an actual CLI problem (the new lock files for npm aren't merged together as the old package.json was ) I created another issue here: https://github.com/ionic-team/ionic-cli/issues/2485
