### ISSUE TITLE
Ionic 5: "The key "viewport-fit" is not recognized and ignored." error on Android 5

### ISSUE THREAD

**Issue by giuse-m** [ionic-team/ionic#20568] opened 2020-02-20 15:33 UTC
Hi, i have a problem with Ionic on Android 5. I must develope my Android app for an Android 5 device.
On app startup appears this error:  "The key "viewport-fit" is not recognized and ignored." and some app's elements (buttons, modals etc...) don't works.
Android System WebView on device is up to date.
I tried to update Cordova, Ionic, Npm, and Android platform and read lot of other issues but problem persists.
On Android 6 and later all works correctly.
Please I need help.

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Ionic info:** 

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\giuse\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\Users\giuse\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2020-02-20 15:47
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

Older versions of the Android webview do not support `viewport-fit` which is fine. It is really only for newer devices which have the "notch", and those devices typically have newer versions of the Android webview which support `viewport-fit`.

If you are running into additional issues, please open separate issues with specific details as to what is not working, along with steps to reproduce.

**Closed by liamdebeasi** 2020-02-20 15:47 UTC
Labels: triage
