### ISSUE TITLE
VirtualScroll rendering issue after altering source array

### ISSUE THREAD

**Issue by spacepope** [ionic-team/ionic#11851] opened 2017-05-29 16:28 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The scrolling behavior is as expected until some elements are added to the source array.
Afterwards rapidly scrolling the list results in visible flickering of items or even empty item slots, which are filled after a short timeout or sometimes only triggered by an additional small scrolling push.
This seems to occur with or without using headerFn and/or virtualTrackBy.

(Loading the complete list content within a VirtualScroll without altering the source array results in smooth and solid scrolling without the mentioned issue..)

**Expected behavior:**
Altering the source array (adding or removing items) should not result in VirtualScroll rendering issues; scrolling should be as smooth and solid as after initialization.

**Steps to reproduce:**

1. Use VirtualScroll and intialize source array
2. Rapidly scroll up and down to verify smoothness of scrolling
3. Alter source array by adding more items (could be done by simple setTimeout or by using InfiniteScroll)
4. Rapidly scroll up and down; you eventually see the described flickering issue.

**Related code:**

```
<ion-content>
  <ion-list no-lines [virtualScroll]="Measures" approxItemHeight="'50px'"
        approxHeaderHeight="'50px'" [headerFn]="myHeaderFn" [virtualTrackBy]="trackByFn">
    <ion-item-divider *virtualHeader="let header" class="header">
      <h2>{{ header }}</h2>
    </ion-item-divider>

    <ion-item *virtualItem="let measure">
      <ion-icon [name]="measure.Icon" item-left></ion-icon>
      {{ measure.Value }} {{ measure.Unit}}
      <ion-note item-right>
        {{ measure.Caption }}
      </ion-note>
    </ion-item>
  </ion-list>

  <ion-infinite-scroll (ionInfinite)="doInfinite($event)">
    <ion-infinite-scroll-content></ion-infinite-scroll-content>
  </ion-infinite-scroll>
</ion-content>
```

```
  trackByFn(index, item) {
    if (!item) {
      return undefined;
    }
    return item.TrackID;
  }

  myHeaderFn(record, recordIndex, records) {
    if (!record || !record.FormattedTime) {
      return null;
    }

    // show header on first item and each new measure time
    if (recordIndex === 0 || (recordIndex > 0 && record.FormattedTime !== records[recordIndex-1].FormattedTime)) {
      return record.FormattedTime;
    }
    return null;
  }

  // method for infinite scroll
  doInfinite(infiniteScroll) {
    // load next measures to display
    this.dataProvider.loadMeasureHistory(OFFSET, LIMIT).then(measures => { 
        measures.forEach(m => {
          this.Measures.push(m);
        });

        // report end of loading process, so that list can hide spinner
        infiniteScroll.complete();
    }).catch(err => { 
      infiniteScroll.complete();
    });
  }
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.4.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.4
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by wmaurer** [comment] 2017-05-30 10:52
I am also experiencing similar issues. In my case I'm not using `ion-infinite-scroll`.
In my case, I'm updating a single item in the list immutably (via `@ngrx/store`), and the array gets newly created (as it's also immutable).

I see no refresh/flicker using `*ngFor`.
I also checked the behaviour with ionic-angular 2.2.0, and that worked flawlessly, so this problem has been introduced since then.

The Ionic documentation says:
>Changing the dataset requires the entire virtual scroll to be reset, which is an expensive operation and should be avoided if possible

... however in my opionion the `[virtualScroll]` should work as well as `*ngFor`.

**Comment by jgw96** [comment] 2017-05-30 14:48
Hello, thanks for opening an issue with us, we will look into this.

**Comment by wmaurer** [comment] 2017-05-31 13:19
Is there an Ionic 3.3.0 plnkr or codepen that I could fork to demonstrate the problems I'm having with virtualScroll?

**Comment by wmaurer** [comment] 2017-06-02 08:05
Okay, I now have a Ionic 3.3.0 plnkr that demonstrates this problem:
http://plnkr.co/edit/wcsNrJ?p=preview

Click on any item in the `[virtualScroll]` and the content of the `ion-item` get increased. You can see also that all the items get redrawn and the list flickers.

I hope this helps in being able to replicate the problem.

**Comment by masimplo** [comment] 2017-06-02 08:18
This seems related to #11294. Situation was improved by #11297 but just for edits outside the viewable port and additions deletions after the viewable port (fast path update).
The rest take the slow path which essentially destroys and recreates all rendered items, thus causing the flickering and other side effects like closing a ion-slide-item that was open etc.  
@manucorporat had mentioned that there might be a solution for not destroying the elements when a slow path is taken.

**Comment by jgw96** [comment] 2017-06-02 18:30
Hello all! After further review I am going to close this issue as a duplicate of #11788

**Closed by jgw96** 2017-06-02 18:30 UTC
Labels: needs info, v3
