### ISSUE TITLE
bug: iOS (Safari) scroll bounce jitters when IonButton is target of touch scroll

### ISSUE THREAD

**Issue by combondrn** [ionic-team/ionic#21536] opened 2020-06-15 16:11 UTC
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
In iOS, using @ionic/react, if a user scrolls until triggering the Safari "scroll bounce" while an IonButton is under the user's finger, the bounce will jitter.

This jitter is similar - if not identical - in appearance to that depicted in issue https://github.com/ionic-team/ionic/issues/20486

Presumably the technical explanation is similar to what is described in this comment of the same issue:
https://github.com/ionic-team/ionic/issues/20486#issuecomment-586459674
(Please note, the cause is not the same as in this issue; no custom CSS is involved in the behavior described here.)

Additionally, this behavior can be triggered by an IonItem if it is set as a button (button={true}) and forced to display as "md" (mode="md"), then scrolling in iOS as described above.

**Expected behavior:**
Expected behavior is a smooth scroll and single bounce, as occurs when other elements are under the finger on a touch scroll.

**Steps to reproduce:**
This behavior appears in Ionic's Conference demo app: 
https://github.com/ionic-team/ionic-conference-app

Load the demo app in iOS, navigate to the "About" page, and drag downward on either of the buttons appearing at the top (IonMenuButton on the left; IonButton with ellipsis icon on the right). The behavior is exaggerated by faster and longer drags.

**Related code:**
Please see Ionic's Conference demo app, page "About": 
https://github.com/ionic-team/ionic-conference-app

I have recreated the behavior in other contexts; it appears to require nothing more than:

`
 <IonPage>
      <IonContent>
              <IonButton />
      </IonContent>
</IonPage>
`

**Other information:**
N/A

**Ionic info:**
Ionic:

   Ionic CLI       : 6.10.0
   Ionic Framework : @ionic/react 5.0.5

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.2
   npm    : 6.13.1
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment] 2020-06-15 17:27
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

I have seen this bug appear a few times before, and it turns out this is a bug in WebKit. I have reported this bug to the WebKit team, so hopefully they can resolve it soon: https://bugs.webkit.org/show_bug.cgi?id=209968.

**Closed by liamdebeasi** 2020-06-15 17:27 UTC
Labels: triage

**Comment by combondrn** [comment] 2020-06-15 18:09
Thank you Liam for your swift response!
