### ISSUE TITLE
VirtualScroll making page very slow on ios with many nested components

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic#12392] opened 2017-07-18 07:51 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I'm using two level on lazy loaded modules in my VirtualScroll component with about 300 items in the VirtualScroll. On browser, android & ios simulator it's working fine. On iPhone 5s, it makes the page feel very slow: when I click on a button inside one of the components, it wait for 1 to 2 seconds to be activated and open an alert ; when I click on the alert dismiss button, this button is only activated after 1 or 2 seconds.  
The scroll is very smooth, so there doesn't seem to be a CPU kind of bug.

**Expected behavior:**
Using nested components with VirtualScroll should not make the buttons feeling unresponsive or slow on the page.

**Steps to reproduce:**
I don't have enough time to set up a demo repo for now (as it's only appearing on iPhone a plunkr wouldn't be useful), maybe later.

**Other information:**
We're using wkwebview for ios.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : not installed
    npm        : 5.2.0```

**Comment by HugoHeneault** [comment] 2017-07-18 11:21
Some update:

We're not sure anymore that it is only about nested components, but... nested blocks (which is implied by nested components, of course).

If we have this kind of stuff (pseudocode, not so much time, sorry): 
```
<virtualScroll>
   <virtualItem>
      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <button (click)="someFunc()">I'm nested and slow on iphone5</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </virtualItem>
</virtualScroll>
```

It's taking about 1 to 2 sec to trigger someFunc()

But with a more simple layout, like 
```
<virtualScroll>
   <virtualItem>
      <button (click)="someFunc()">I'm nested and slow on iphone5</button>
  </virtualItem>
</virtualScroll>
```

It's blazing fast. 

So, what's happening? 😭

**Comment by jgw96** [comment] 2017-07-21 16:03
Hello, thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/10269

**Closed by jgw96** 2017-07-21 16:03 UTC
