### ISSUE TITLE
feat: Ionic tab swipe

### ISSUE THREAD

**Issue by nguyenduclong-ict** [ionic-team/ionic#21451] opened 2020-06-08 09:19 UTC
Please Add Swipe between tab in ionic tab

**Comment by BerkeAras** [comment] 2020-06-08 09:28
I think, that would only good for MD, not for iOS.

**Comment by liamdebeasi** [comment] 2020-06-08 13:22
Thanks for the feature request. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17804.

**Closed by liamdebeasi** 2020-06-08 13:22 UTC
Labels: triage
