### ISSUE TITLE
v3.5.3 ItemReorder does not work on Desktop firefox 54.0.1

### ISSUE THREAD

**Issue by jasekiw** [ionic-team/ionic#12372] opened 2017-07-15 01:39 UTC
**Ionic version:**
[x ] **3.5.3**

**I'm submitting a:**
[x ] bug report

**Current behavior:**
When clicking and dragging an ion-item the item goes dark but does not move.

**Expected behavior:**
That you can click and drag an ion-item like you can in other browser. (click and drag via the hamburger)

**Related code:**

```
<ion-list  reorder="true" (ionItemReorder)="reorderPages($event)">
<ion-item-sliding *ngFor="let page of template.pages; let index = index">
   <button ion-item><p><b>test</p></button>
    <ion-item-options side="right">
        <button ion-button color="danger">
                            <ion-icon name="trash"></ion-icon>
                            Delete
         </button>
      </ion-item-options>
</ion-item-sliding>
<ion-item-sliding *ngFor="let page of template.pages; let index = index">
   <button ion-item><p><b>test1</p></button>
    <ion-item-options side="right">
        <button ion-button color="danger">
                            <ion-icon name="trash"></ion-icon>
                            Delete
         </button>
      </ion-item-options>
</ion-item-sliding>
</ion-list>
```
**Ionic info:** 

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 5.2.2 browser 4.1.0 ios 4.2.1
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.9.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4
```

**Comment by jgw96** [comment] 2017-07-17 15:26
Hello! Thanks for using Ionic! Unfortunately i cannot reproduce this issue on my surface book running the latest version of firefox for windows. Can you try https://ionicframework.com/docs/api/components/item/ItemReorder/ and see if that works for you?

**Comment by jgw96** [comment] 2017-07-20 16:14
Hello, thanks for using Ionic. Because i cannot seem to reproduce this issue either in firefox for windows or Firefox for Android I am going to close this issue for now. Thanks for using Ionic!

**Closed by jgw96** 2017-07-20 16:14 UTC
Labels: needs info, v2

**Comment by robert-j** [comment] 2017-12-04 13:24
The sample code from @jasekiw  doesn't work in Firefox 57.0.1 (Quantum) either.

While https://ionicframework.com/docs/api/components/item/ItemReorder/  does indeed work, it's not the same as the sample code from @jasekiw . It doesn't leverage an ion-item-sliding component, and ion-list reorder="true" is triggered by a button.
