### ISSUE TITLE
[4.0.0-beta.17] sliding-item doesn't work in RTL

### ISSUE THREAD

**Issue by 3adeling** [ionic-team/ionic#16546] opened 2018-12-01 01:50 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v11.1.0
   npm               : 6.4.1
   OS                : Linux 4.15
```

**Describe the Bug**
when setting dir="rtl" on html tag the sliding item doesn't show. 

**Steps to Reproduce**
1. Go to `<html>`
2. add `dir="rtl"`
3. the sliding item is not showing

**Comment by abennouna** [comment] 2018-12-04 09:36
Seems to be the same issue [here](https://github.com/ionic-team/ionic/issues/15883) and [here](https://github.com/ionic-team/ionic/issues/14328)

**Comment by brandyscarney** [comment] 2019-01-03 16:17
Closing as duplicate of #14328

**Closed by brandyscarney** 2019-01-03 16:17 UTC
Labels: needs: investigation, package: core
