### ISSUE TITLE
bug: Bug: ion-input number

### ISSUE THREAD

**Issue by ThiagoSPereira** [ionic-team/ionic#13595] opened 2017-12-06 13:30 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>The problem in "ion-input". It is converting number to string.</span>

<span is-issue-template></span>

**Comment by mhartington** [comment] 2017-12-06 17:27
Hi there! This is an underlying issue in Angular, https://github.com/angular/angular/issues/19577. 

Im going to be closing this for now since it is not an Ionic specific issue.

**Comment by ThiagoSPereira** [comment] 2017-12-06 23:04
You don't understand. The problem is 'ion-input'. 
If you use "ion-input type="number". You will receive a text.
That is the problem.

**Comment by ThiagoSPereira** [comment] 2017-12-06 23:08
When a use <input type="number"> works. But I lose CSS from Ionic Component.

**Comment by kensodemann** [comment] 2017-12-07 14:55
Updated previous comment just to add back-ticks around HTML...

**Comment by kensodemann** [comment] 2017-12-07 15:35
I have a sample application here that duplicates the issue as described by @ThiagoSPereira 
https://github.com/kensodemann/test-input-number

I will re-open this and mark as something to look into after v4 is out.

**Comment by brandyscarney** [comment] 2017-12-07 15:41
This is a duplicate of https://github.com/ionic-team/ionic/issues/7121

See my comment here: https://github.com/ionic-team/ionic/issues/7121#issuecomment-287143709

**Comment by kensodemann** [comment] 2017-12-11 20:50
This is fixed in version 4 via the addition of a Control Value Accessor specifically for `ion-input[type=number]`.

https://github.com/ionic-team/ionic/commit/903a12dc399531d179911816b3a088855d76edb4#diff-3f2034ee9030febf9f3da748371456c4

**Closed by kensodemann** 2017-12-11 20:50 UTC

**Comment by msevestre** [comment] 2017-12-11 21:42
@kensodemann very nice. When can we expect version 4 to be released? Thanks

**Comment by kensodemann** [comment] 2017-12-11 22:54
@msevestre - here is the current timeline:
https://blog.ionicframework.com/ionic-2017-18-roadmap/

That was written in October.
