### ISSUE TITLE
Ionic searchbar: filtered items are updated only when keyboard is dismissed in android

### ISSUE THREAD

**Issue by Alb93** [ionic-team/ionic#12160] opened 2017-06-26 23:22 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
 Filtered items are updated only when keyboard is dismissed.

**Expected behavior:**
 Filtered items updated real time when input changes. As we can see on the official documentation

**Steps to reproduce:**
Copy and past offical docs and run in real android device.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0
```

**Comment by AmitMY** [comment] 2017-06-27 07:32
- Which doc exactly did you copy?
- What is your android's version?

**Comment by Alb93** [comment] 2017-06-27 07:46
1) [](https://ionicframework.com/docs/components/#searchbar)
2) 7.1.1 my phone, but also some other which I don't know the version.

I add that also the search button displayed on the keyboard does nothing

**Comment by jgw96** [comment] 2017-06-27 15:09
Hello @Alb93 , would you mind posting a repo we could use to reproduce this issue? I am not able to repro this issue on my device (A nexus 6 running 7.1.1)

**Comment by Alb93** [comment] 2017-06-27 16:49
Hi @jgw96 , can you share with me your attempt? If you have done only this page this will be this faster way and then I can try on my android.

**Comment by jgw96** [comment] 2017-06-29 15:54
Hello @Alb93 , I'm just using our [conference app demo](https://github.com/ionic-team/ionic-conference-app) to test this. The schedule page (first tab that shows when you open the app) has a searchbar on it.

**Comment by jgw96** [comment] 2017-07-18 14:49
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-18 14:49 UTC
Labels: needs info, v2
