### ISSUE TITLE
Ionslide: error loading for the first time. Ionic 4

### ISSUE THREAD

**Issue by jhonattanbulls** [ionic-team/ionic#20537] opened 2020-02-18 14:48 UTC
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

When I enter the page where the slide is, the translation does not work, nor does it load the default options.
**Expected behavior:**

What I hope is that when you enter the page the translation can work at the moment the user wants to see the other slides and load the options for defects

**Steps to reproduce:**

**Related code:**

```

search.html

`<ion-slides
    [options]="slideOpts"
    *ngIf="searchText=='' && pressInput == false"
  > <ion-slide
      (click)="getUserAleatoria(); allTagSelect = true; sportSelect = ''"
      [ngClass]="{'bg-col-active':allTagSelect === true}"
      class="img-bg tagAll"
      style="background-image: url(tag.jpg);"
    >
      <h6>{{ 'search.sports.all' | translate }}</h6>
    </ion-slide>
    <ion-slide
      *ngFor="let tag of sports; let i = index"
      (click)="getSearchTag(tag.id, tag.name); sportSelect = i; allTagSelect = false;"
      [ngClass]="{'bg-col-active':sportSelect === i}"
      class="img-bg"
      [style.background-image]="sanitizeImage(tag.photo)"
    >
      <h6>{{ 'search.sports.'+tag.tag | translate }}</h6>
    </ion-slide>
  </ion-slides>`
```
`search.ts
slideOpts = {
    initialSlide: 1,
    slidesPerView: 4,
    speed: 400
  };`
**Other information:**

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\Usuario\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\Usuario\AppData\Local\Android\Sdk)
   NodeJS            : v12.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 7

**Comment by liamdebeasi** [comment] 2020-02-18 15:53
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by jhonattanbulls** [comment] 2020-02-18 16:02
> Gracias por el problema ¿Puede proporcionar un repositorio con el código requerido para reproducir este problema?

En un momento lo subo, voy a crearlo

**Comment by jhonattanbulls** [comment] 2020-02-18 19:42
I pass the link if you realize the slide does not work properly when starting for the first time, not all slides are shown. 
https://github.com/jhonattanbulls/dotest.git

**Comment by jhonattanbulls** [comment] 2020-02-18 19:43
@liamdebeasi link ready.

**Comment by jhonattanbulls** [comment] 2020-02-18 19:50
@liamdebeasi  please you must place your browser in development mode and then use some device so that it takes the mobile size screen and can reproduce the error.

**Comment by liamdebeasi** [comment] 2020-02-20 15:43
Thanks for the follow up. The transition is not working properly because of the CSS you have applied. When you tell Swiper to display 4 slides per view, it is going to resize each slide to a width that allows it all to fit on the screen. 

For example, if you have a screen width of 400px, Swiper is going to resize each of the 4 slides in the view to have a width of 100px.

You CSS has a `width: auto !important;` rule which prevents Swiper's resizing to take effect.

Removing `width: auto !important` fixes the issue. I am going to close this as this is not a bug in Ionic Framework.

**Closed by liamdebeasi** 2020-02-20 15:43 UTC
Labels: triage
