### ISSUE TITLE
bug: autofocus not working

### ISSUE THREAD

**Issue by aub** [ionic-team/ionic#21391] opened 2020-05-27 20:00 UTC
# Bug Report

**Ionic version:**

[x] **5.1.1**

**Current behavior:**

I have made a simple demo app that has three pages. The pages don't contain much, with an input and a submit button on top of the basic starter app things. The inputs have autofocus set but when navigating to them their pages they don't receive focus. On the second page I added a thing to force a call to `setFocus` on the input after the page comes into view, and that works. The app prints out the current thing with focus, and it looks like on pages 1 and 3 the link you click on to get there has focus and then it goes directly to the `<body>`.

**Expected behavior:**

When transitioning to the pages having inputs with autofocus set to true, those inputs get focus.

**Steps to reproduce:**

See demo app. Tested on Chrome and FF on a Mac.

**Related code:**
[https://github.com/pegulabs/ionic-autofocus](https://github.com/pegulabs/ionic-autofocus) is a super simple demo app to show the problem. 

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.1.1

Capacitor:

   Capacitor CLI   : 2.1.1
   @capacitor/core : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.0.0 (/usr/local/Cellar/node/14.0.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-05-27 20:39
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `autofocus` property is not very useful on child pages as most browsers will block `autofocus` from working if there is already an active element. 

For example, if you open the console in Chrome and click "Page 1", you should see a message that says `Autofocus processing was blocked because a document already has a focused element.`.

We recommend manually setting focus using `setFocus` instead.

Hope this clears things up!

**Closed by liamdebeasi** 2020-05-27 20:39 UTC
Labels: triage
