### ISSUE TITLE
bug: Ion icon doesnt work when open the app in safari without a webserver

### ISSUE THREAD

**Issue by jbadano-kc** [ionic-team/ionic#21342] opened 2020-05-19 16:43 UTC
# Bug Report

**Ionic version: "@ionic-native/core": "^5.26.0"**

**Current behavior:**
I've an ionic application that should run into another (on an iOS device) one which loads the web opening the index.html.
The problem is that the ion-icons are not being displayed.

**Expected behavior:**
Icons should be displayed.

**Steps to reproduce:**
Using angular cli 6.9.1
1) Create a new project:
- ionic start test
->Angular
->Tabs template
->Integrate with capacitor Yes

2) In the generated projejct, add an ion-icon into a template
example: src/app/explore-container/explore-container.component.html

```
<div id="container">
  <strong>{{ name }}</strong>
  <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
  <ion-icon icon="person"></ion-icon>
</div>
```

3) build the app
ng build --base-href "./" --prod

4) open in safari
rigth click in www/index.html -> open with safari

NOTE: in order to do that you should disable CORS in safari. In the menu, DEVELOP -> Disable Cross-origin restrictions

**Other information:**
Im using Safari Technology Preview Release 106 (Safari 13.2, WebKit 15610.1.12.2)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.1 (/Users/jbadano/.nvm/versions/node/v10.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/Users/jbadano/.nvm/versions/node/v10.16.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2020-05-19 16:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Loading Ionicons requires a cross origin request which is not possible when just previewing the `index.html` file in a browser.

You can start a simple HTTP server to preview your page locally with Python: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server.

Thanks!

**Closed by liamdebeasi** 2020-05-19 16:50 UTC
Labels: triage
