### ISSUE TITLE
bug: input looses autocapitalize after setFocus()

### ISSUE THREAD

**Issue by rpragesh** [ionic-team/ionic#21115] opened 2020-04-23 13:10 UTC
in ionic4 project which should default capitalizes the first letter when text area is focused and keyboard opens (The shift-arrow on the iOS keyboard is solid). 

```
@ViewChild('focusInput', { static: false }) myInput;

    ionViewWillEnter() {
        setTimeout(() => {
          this.myInput.setFocus();
          this.nativeKeyboard.show();
        }, 1300);
      }
```
this code set focus in text area and opens the keyboard but the shift-key is no longer solid and the first letter is not automatically uppercased. How do I force the first letter to be automatically uppercased?

![keyboard](https://user-images.githubusercontent.com/33778579/80103136-5e799580-8591-11ea-972e-af2bf6f9fc04.png)

it is all working properly in ionic 3.

**Comment by rpragesh** [comment] 2020-04-24 05:00
https://github.com/rpragesh/rpragesh

does this enough? Its ionic 4 project

**Comment by liamdebeasi** [comment] 2020-04-24 13:51
@rpragesh I need a full app that compiles in order to test this. I recommend trying to reproduce the issue on a blank Ionic starter application.

**Comment by rpragesh** [comment] 2020-04-27 09:50
@liamdebeasi  here is the repo [https://github.com/rpragesh/Keyboard-Focus-Demo](keyboard demo app) can you please try? 

I have same issue with newly created app as well.

**Comment by liamdebeasi** [comment] 2020-04-27 14:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

`autocapitalize` defaults to `"off"` on `ion-textarea`, so you will need to enable it in order to get the default capitalization to work. For more information, please see the docs: https://ionicframework.com/docs/api/textarea#properties

**Closed by liamdebeasi** 2020-04-27 14:50 UTC
Labels: triage

**Comment by rpragesh** [comment] 2020-04-28 04:56
`autocapitalize='sentences' `  I used this instead of `autocapitalize='true'`. It was a mistake :(

Thank you for clarification.
