### ISSUE TITLE
Ionic 2 - <ion-select> issue on Windows Mobile 10

### ISSUE THREAD

**Issue by SkogDev** [ionic-team/ionic#6609] opened 2016-05-22 06:24 UTC
#### Short description of the problem:

I am having some styling-issues on WM10. The '< ion-select >' is having the same height as if there were no item selected.

Here are three images:

Android (ion-select looks ok)
![screenshot_2016-05-22-07-46-00](https://cloud.githubusercontent.com/assets/2014746/15452550/4a12dc26-1ff3-11e6-9ddf-91b4e3fe0e89.png)

iOS (ion-select looks ok)
![img_3050](https://cloud.githubusercontent.com/assets/2014746/15452553/51109efa-1ff3-11e6-9b5e-b5764a5028f5.PNG)

WM10 (ion-select is having some trouble)
![wp_ss_20160522_0001](https://cloud.githubusercontent.com/assets/2014746/15452551/4e6ff894-1ff3-11e6-9288-f9d3618a9b6f.png)

I suspect that the use of an "item-left icon" and a "stacked" label may be the source of the problem?
If I am using the ion-icon, and the ion-label wrong, please let me know.

`<ion-item class="transparency noborder">`
       `<ion-icon light ios="ios-map-outline" md="ios-map-outline" item-left></ion-icon>`
           `<ion-label stacked>Type</ion-label>`
            `<ion-select [(ngModel)]="pagedata.type" item-right class="whitecolor">`
               `<ion-option *ngFor="let p of pointTypes" [value]="p.Id" class="whitecolor">{{ p.Descr }}</ion-option>`
           `</ion-select>`
       `</ion-item>`
#### What behavior are you expecting?

Expected behavior would be a list of inputs with the same height on all platforms.

**Steps to reproduce:**
Setup an ion-list with this item:

```
<ion-item>
  <ion-icon light ios="ios-map-outline" md="ios-map-outline" item-left></ion-icon>
  <ion-label stacked>Type</ion-label>
  <ion-select [(ngModel)]="someModel.type" item-right>
    <ion-option *ngFor="let item of madeUpItems" [value]="item.Id" >{{ item.description }}</ion-option>
  </ion-select>
</ion-item>
```

**Which Ionic Version?** 1.x or 2.x
Ionic 2
#### Plunker that shows an example of your issue

No plunker set-up for this issue

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v6.2.0

**Comment by brandyscarney** [comment] 2016-06-02 02:48
Does this happen when emulating in a browser or only on a windows device? I am seeing the following with your markup using the dark theme:

![screen shot 2016-06-01 at 10 47 55 pm](https://cloud.githubusercontent.com/assets/6577830/15732419/ef1f7512-284a-11e6-9a46-bbc059153e58.png)

I may have fixed this recently though.

**Comment by Daforest** [comment] 2016-06-02 03:51
@brandyscarney This was tested on a Windows 10 Device (640). I will test this on an emulator later today.

**Comment by jgw96** [comment] 2016-06-06 19:16
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Daforest** [comment] 2016-06-07 16:34
@brandyscarney Sorry for the late response, here is a screenshot from the WM 10 emulator:

![capture](https://cloud.githubusercontent.com/assets/2014746/15866324/671447fe-2cde-11e6-930f-110b286d803e.PNG)

**Comment by jgw96** [comment] 2016-06-30 18:02
Hello @Daforest Is this still an issue on beta.10? Thanks!

**Comment by Daforest** [comment] 2016-06-30 20:47
@jgw96 Tested with Beta.10 just now. Sorry to say, the issue is still present.

**Comment by jgw96** [comment] 2017-06-05 16:42
Hello all! I am going to close this issue for now as I cannot reproduce this issue with the latest release of ionic on the latest release of edge. Thanks for using Ionic!

**Closed by jgw96** 2017-06-05 16:42 UTC
Labels: platform:android, platform:ios, select, v2
