### ISSUE TITLE
ionic cordova run -l -c => platforms not returning cordova

### ISSUE THREAD

**Issue by clarako** [ionic-team/ionic#16113] opened 2018-10-27 04:54 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/Users/clarako/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 6 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.12.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
When running
`ionic cordova run ios -l -c`
cordova is not showing up in the platforms for @ionic/angular.
platform.platforms() = iphone,ios,mobile

However, when running without -l -c
`ionic cordova run ios`
platform.platforms() = iphone,ios,cordova,mobile,hybrid

**Steps to Reproduce**
1. Create a starter project: ionic start ...
2. In home.page.ts
```
import { Platform } from '@ionic/angular'
...
  constructor(...private platform: Platform...) {
  }
...
```
3. In home.page.html, add
```
{{platform.platforms()}}
```
4. ionic cordova run ios -l -c

**Expected Behavior**
Expected: iphone,ios,cordova,mobile,hybrid
Actual: iphone,ios,mobile

**Comment by ajcrites** [comment] 2018-10-30 17:44
This seems to happen because of the `-l` (and possibly `-c`)... it doesn't inject cordova in the app build when running a server. This might be due to the cordova serve builder, but I haven't checked. This makes some testing difficult.

**Comment by shaxxx** [comment] 2018-11-21 21:53
Fixed in beta16

**Comment by brandyscarney** [comment] 2018-11-28 23:51
Thanks @shaxxx! Closing as a duplicate of #15893 and fixed in latest.

**Closed by brandyscarney** 2018-11-28 23:51 UTC
Labels: triage
