### ISSUE TITLE
ion-checkbox: inner button is taking the whole ion-item container

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic#17832] opened 2019-03-20 15:48 UTC
# Bug Report

**Ionic version:**

[x] **4.0.2**

**Current behavior:**

i put ion-checkbox & some other ionic components inside an ion-item, when pressing in padding spaces around other components, the checkbox event is called 

**Expected behavior:**

when pressing in any other components padding area nothing should happened

Steps to reproduce:**

1. create new project with version 4.0.2.
2. add ion-checkbox , ion-input respectively inside ion-item
3. put [checked]="console.log('tapped')";
3. run the app and click the padding are around ion-input
4.  the checkbox is event checked is called

**Other information:**

what i figured out after inspecting the element that the button element inside ion-checkbox is taking the whole ion-item width & height so whenever you press in a blank space it will fire
![ion-checkbox](https://user-images.githubusercontent.com/40992542/54698500-7be36100-4b40-11e9-9d8e-047f95b29de6.png)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\sshalaby\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.2
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by SherifMoShalaby** [comment] 2019-03-21 19:58
@liamdebeasi thx

**Comment by liamdebeasi** [comment] 2019-03-27 12:50
Hi there,

I am going to close this as a duplicate of #15850. Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-27 12:50 UTC
Labels: triage
