### ISSUE TITLE
bug: Cannot create card style modal inside app.component.ts

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic#20698] opened 2020-03-05 13:25 UTC
# Bug Report

**Ionic version:**

[x] **^5.0.4**

**Current behavior:**

When you try to create an card style modal in app.component.ts you'll get a error message

<img src="https://i.imgur.com/pqVtSjj.png">

**Expected behavior:**

card style modal should be presented
**Steps to reproduce:**
1. add IonRouterOutlet and modalController to constructor()
```  
constructor(
    ...
    private routerOutlet: IonRouterOutlet,
    private modalController: ModalController,
    ...
  ) {}
```
2. create modal
```  
 public async onOpenModal() {
    const modal = await this.modalController.create({
      component: TestPage,
      swipeToClose: true,
      presentingElement: this.routerOutlet.nativeEl
    });
    return await modal.present();
  }
```
3. run ionic serve
4. you should get following error message in console:
```
NullInjectorError: R3InjectorError(AppModule)[IonRouterOutlet -> IonRouterOutlet -> IonRouterOutlet]: 
  NullInjectorError: No provider for IonRouterOutlet!
```

[Link to repo](https://github.com/DwieDima/ionic-multiple-modal-bugs)

**Other information:**

Creating modal by using the ViewChild of IonRouterOutlet instead of constructor in app.component.ts is working fine.
```
@ViewChild('outlet', { read: IonRouterOutlet }) routerOutlet: IonRouterOutlet;
```
using IonRouterOutlet in constructor for childpages is working.
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.0 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-03-05 14:43
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.  The `IonRouterOutlet` dependency injection only works if the component is inside of an ion-router-outlet. `app-root`, the component for `app.component.ts`, exists outside of an ion-router-outlet.

As an alternative, you can use `ViewChild` to grab the `ion-router-outlet` that is found in `app.component.html`.

**Closed by liamdebeasi** 2020-03-05 14:43 UTC
Labels: triage

**Comment by henryavila** [comment] 2020-04-02 22:15
Hi, I have the same problem while implementing swipeable modals using the app with tabs.

My solution is:
```
// add an id to ion-router-outlet
<ion-router-outlet id="root-router"></ion-router-outlet>
```

```
// Get an HTMLElement usign the id
document.getElementById('#root-router')
```

And it works perfectly

**Comment by Taylorsuk** [comment] 2020-04-26 12:57
Thanks @henryavila that fix worked for me!
