### ISSUE TITLE
bug: strange error j9sczdb9.entry.js:1 icon was not resolved

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic#18271] opened 2019-05-13 20:42 UTC
# Bug Report

**Ionic version:**

[x] **4.4.0**

**Current behavior:**

getting this error in browser 
j9sczdb9.entry.js:1 icon was not resolved

**Expected behavior:**

**Steps to reproduce:**

cannot describe the issue as it shown suddenly when upgrading to ionic 4.4.0

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\sheri\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.1.0 (cordova-lib@8.1.2)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 11 other plugins)

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by brandyscarney** [comment] 2019-05-13 21:13
Please provide a repository for us to reproduce this. We cannot see this in our apps. Thanks!

**Comment by brandyscarney** [comment] 2019-05-15 18:21
Thanks for the response! We definitely don't recommend adding `ion-activatable`, using the `button` property to get an item as a button or an `href` property to get an item as an anchor is recommended. I am going to close this since you have fixed the error, thanks!

**Closed by brandyscarney** 2019-05-15 18:21 UTC
Labels: triage
