### ISSUE TITLE
bug: ion refresher not hiding on IOS

### ISSUE THREAD

**Issue by olaisen81** [ionic-team/ionic#21291] opened 2020-05-13 15:19 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:** The refresher is not hiding in IOS until I tap anywhere on the screen, it hides itself as normal behavior if you touch outside of the ionic list component. If you tap down from ones of the item in the ion list it doesn't hide.
 
**Expected behavior:** The refresher should hide after calling event.target.complete() function

**Steps to reproduce:** I run the refresher and when I finish loading the content I call event.target.complete() function. The bug reproduce if you tap down slowly, i notice that if i tap down fast it works. I can't reproduce it on a new sidemenu projects, here it works, incredible. It seems like the problem is due to list fetching from DB, with static list it works.
![91385BCA-96B8-4E91-8D1A-B7C6B1FE2D4C](https://user-images.githubusercontent.com/20971348/81927079-571f3800-95e3-11ea-9ecf-dc4356853add.gif)

**Other information:**

**Ionic info:**

Ionic CLI                     : 6.9.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

**Comment by olaisen81** [comment] 2020-05-14 10:30
**Code reproduction:**

**page.component.html**
```
<ion-header [translucent]="true">
    <ion-toolbar>
        <ion-buttons slot="start">
            <ion-menu-button></ion-menu-button>
        </ion-buttons>
        <ion-title>{{'interfaces.menu.notifiche' | translate}}</ion-title>
    </ion-toolbar>
</ion-header>
<ion-content [fullscreen]="true">
    <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
    <ion-header collapse="condense">
        <ion-toolbar>
            <ion-title size="large">{{'interfaces.menu.notifiche' | translate}}</ion-title>
        </ion-toolbar>
    </ion-header>
    <ion-list>
        <ion-list-header lines="inset">
            <ion-label color="primary">{{'interfaces.menu.gestione' | translate}}</ion-label>
        </ion-list-header>
        <ion-item-sliding *ngFor="let notifica of this.listaNotifiche">
            <ion-item (click)="this.goToGestioneNotifica(notifica)">
                <ion-label>
                    <ion-text>
                        <h2 class="font-weight-bold text-overflow-ellipsis">{{notifica.Title}}</h2>
                    </ion-text>
                    <ion-text color="medium">
                        <h3 class="text-overflow-ellipsis">{{notifica.Body}}</h3>
                    </ion-text>
                </ion-label>
            </ion-item>
            <ion-item-options side="end">
                <ion-item-option (click)="invia(notifica)"><i class="fal fa-paper-plane"
                        slot="top"></i>{{'interfaces.notifica.invia' | translate}}
                </ion-item-option>
                <ion-item-option (click)="cancella(notifica)" color="danger"><i slot="top"
                        class="fal fa-trash-alt"></i>{{'interfaces.notifica.cancella' | translate}}
                </ion-item-option>
            </ion-item-options>
        </ion-item-sliding>
    </ion-list>
</ion-content>
```
**page.component.ts**

```
doRefresh(event) {
   this.currentSubscribe = this.notificheService.getListaNotifiche().subscribe(res => {
   this.listaNotifiche = res.risultato;
   },
      error => {
        this.showError(error);
        event.target.complete();
      },
      () => {
        event.target.complete();
})}
```

**Comment by liamdebeasi** [comment] 2020-05-14 13:16
Can you please provide this as a full reproduction? Code snippets are typically not enough to reproduce the issue. The easiest way is to add an Ionic app to a GitHub repo and include a link to it in this thread.

**Comment by olaisen81** [comment] 2020-05-14 13:36
Hi Liam, I'm sorry but I can't play it with a repository on github due to corporate privacy policies. The problem can probably be caused by the speed of execution of the asynchronous request to my backend. In fact, using a timeout function (for example 3 seconds) everything always works.
Sorry again, I hope you can reproduce the bug the same even without my code and correct it.
Thanks.

**Comment by liamdebeasi** [comment] 2020-05-14 13:37
Can you reproduce this issue in a blank Ionic starter application? That way you do not have to publish your private code.

**Comment by olaisen81** [comment] 2020-05-14 13:39
In a blank ionic starter app using a dummies list of 50 elements added on the fly it alway works. Here for test the issue, i use the setTimeout function and wait 3 second before calling event.target.complete(), everythings works fine.

**Comment by liamdebeasi** [comment] 2020-05-14 13:47
Thanks for the follow up. This issue seems specific to your project and its configuration. Unfortunately, without a reproduction I am unable to fix the issue.

I am going to close this issue for now. If you are able to create a code reproduction of the issue, feel free to reply here with a link to the repo, and I can reopen the issue. Thanks!

**Closed by liamdebeasi** 2020-05-14 13:47 UTC
Labels: ionitron: needs reproduction

**Comment by olaisen81** [comment] 2020-05-15 07:09
Ok Liam, here you can find repo for reproduction. 
https://github.com/olaisen81/ionic-demo

**Comment by liamdebeasi** [comment] 2020-05-15 13:45
Thanks! I was able to reproduce this behavior. This looks like another instance of https://bugs.webkit.org/show_bug.cgi?id=209968. I reported the issue to the WebKit team last month, but have not heard anything back since.

The problem is that when you update the DOM while rubber band scrolling (pulling from the top/bottom of the screen), the scroll position is reset. This also appears to interfere with the gesture that controls the refresher as the native `touchend` event is not called. This is why the refresher does not hide.

As a temporary workaround, you can add a `setTimeout` of `500ms` in the `doRefresh` method:

```javascript
setTimeout(() => {
  Storage.get({ key: "listTestObj" }).then(res => {
    this.listaNotifiche = JSON.parse(res.value);
    event.target.complete();
  })
}, 500);
```

While the workaround is not ideal, it should allow the refresher to function properly. I will follow up with the WebKit team and see if I can get any update.

**Comment by olaisen81** [comment] 2020-05-15 15:48
Ok, i'll try this workaround, is not the optimal solution but for now it may be fine. I hope the Webkit team will help you correct it, thanks for the collaboration, I will stay tuned for updates
