### ISSUE TITLE
Application screen shift up (on Android device and emulator)

### ISSUE THREAD

**Issue by BeliliFahem** [ionic-team/ionic#12038] opened 2017-06-14 12:23 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior :**
Application screen shift up when device keybord is shown.
Then the offset remains until the application is launched again.
When the keyboard is not displayed, there is no offset.

**Steps to reproduce :**
1. Select / Tape / Focus on any input field.

**Other information:**

- Tested on two Android real devices
- tested on many android emulatotrs

**_Screen capture before focus on input (keyboard is shown)_**

![screenshot_2017-06-14-12-10-09](https://user-images.githubusercontent.com/6841040/27131382-c8d08e66-510a-11e7-8a7b-bac129f8e735.png)

**_Screen capture after focus on input (keyboard is shown)_**

![screenshot_2017-06-14-12-10-34](https://user-images.githubusercontent.com/6841040/27131399-dc91b204-510a-11e7-8c3b-46813c25fe97.png)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:
    @ionic/cli-utils : 1.3.0
 You have been opted out of telemetry. To change this, run: cordova telemetry on. 7.0.1
    Ionic CLI        : 3.3.0

local packages:
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : You have been opted out of telemetry. To change this, run: cordova telemetry on.  android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:
    Node       : v6.10.3
    OS         : Windows 10
```

**Comment by jgw96** [comment] 2017-06-14 18:57
Hello, thanks for opening an issue with us. Would you be able to share a repo we could use to reproduce this issue?

**Comment by trebor678** [comment] 2017-06-23 08:37
+1

**Comment by jgw96** [comment] 2017-07-05 16:57
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-05 16:57 UTC
Labels: needs info, v2
