### ISSUE TITLE
Ionic 3 Slides Keyboard bug

### ISSUE THREAD

**Issue by zamecki** [ionic-team/ionic#12661] opened 2017-08-14 19:37 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When opening the keyboard inside of ion-slides it mess up with the content.
I don't know why but only when the third input is focused the bug occur

**First input**
When the first input is focused, it behaves as expected
![screenshot_20170814-151110](https://user-images.githubusercontent.com/14822803/29288070-75acc88c-8105-11e7-9e98-84acd6766050.jpg)

**Third input**
Now with the whole screen moved up, even the pager is overlapping input
![screenshot_20170814-151114](https://user-images.githubusercontent.com/14822803/29288078-7a273ba4-8105-11e7-9964-0a564eb634b7.jpg)

**Expected behavior:**
The expected behavior would be like the first screenshot with the content being visible or scrolled up

**Steps to reproduce:**
Create a ion-slides with some input fields and try to fill up all of them, the opening of the keyboard will reproduce the bug

**Related code:**

```
    <ion-slides pager>
      <ion-slide>
          <ion-item>
            <ion-label>Nome do Animal: </ion-label>
            <ion-input type="text" [(ngModel)]="resenha.nomeAnimal" name="nome" required></ion-input>
          </ion-item>
          <ion-item>
            <ion-label>Inscrição: </ion-label>
            <ion-input type="number" [(ngModel)]="resenha.inscricao" name="inscricao" required></ion-input>
          </ion-item>
          <ion-item>
            <ion-label>Número Iagro:</ion-label>
            <ion-input type="number" [(ngModel)]="resenha.numeroIagro" name="numeroIagro"></ion-input>
          </ion-item>
          <ion-item>
            <ion-label>Chip:</ion-label>
            <ion-input type="number" [(ngModel)]="resenha.numeroChip" name="chip"></ion-input>
          </ion-item>
      </ion-slide>
</ion-slides>
```
My scss

```
    .slide-zoom {
        height: 100%;
    }
    .swiper-pagination-bullet-active {
        
        background: color($colors, secondary, base);
        opacity: 1;
    }
```

**Other information:**
I know that already exist some issues opened about this, but none of them is an ionic 3.
I Hope that i'm not being too redundant.

**Ionic info:** 

```
cli packages: (E:\ResenhaVirtual\node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-plugin-proxy         : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.2.3 browser 4.1.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.10.3
    OS                : Windows 10
    npm               : 5.2.0

```

**Comment by kensodemann** [comment] 2017-08-16 16:11
Hello! Thank you for opening an issue with us! This is a duplicate of issue #10183. Please monitor that issue and reply to it with any other information you may have.

Thank you for using Ionic

**Closed by kensodemann** 2017-08-16 16:11 UTC

**Comment by avinashjgtp10** [comment] 2018-01-14 15:26
you can use following CSS it will work.

.scroll-content{
            margin-bottom: 0px !important;
            padding-bottom: 0px !important;
        }

**Comment by dirk-theshiftleft** [comment] 2018-08-07 02:25
We encountered the same issue when testing on one particular android device (the others didn't show this behaviour). The said device is an Asus Phone and apparently has 2 keyboard modes (android and zenui) that can be switched. Could the problem be related to this higher level keyboard control?
