### ISSUE TITLE
bug: IonSlides are going crazy after re-open modal with slides

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic#21525] opened 2020-06-14 19:33 UTC
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
IonSlides are going crazy after re-open modal with slides

**Steps to reproduce:**
1. Open modal with slides component 
2. Slide few items
3. Dismiss modal
4. Open modal again
5. Slide few items

**Other information:**
Please check that swiper initialized/destroyed properly with modal present/destroy function. 
Note: if i set `*ngIf="initialized"` to ion-slides component, and will initialize it each modal opening, slides works properly. 

![ezgif-1-22c096963c16](https://user-images.githubusercontent.com/10646478/84602297-7e9e4480-aeb0-11ea-9902-61b613219d6e.gif)

**Comment by DwieDima** [comment] 2020-06-14 22:10
I can confirm this issue. After reopening modal, ion-slides transition is broken.

**Comment by roman-rr** [comment] 2020-06-21 22:52
@liamdebeasi To reproduce
```bash
git clone https://github.com/roman-rr/ionic-bugs.git
cd ionic-bugs
npm install
ionic serve
```
Open modal -> Slide -> Close modal -> Open Modal -> Slide

**Comment by liamdebeasi** [comment] 2020-06-22 13:48
Thanks for the issue. I am going to close this as a duplicate of: https://github.com/ionic-team/ionic/issues/19638.

**Closed by liamdebeasi** 2020-06-22 13:48 UTC
Labels: ionitron: needs reproduction
