### ISSUE TITLE
bug: <ng-content> does not work with <ion-header> and <ion-content>

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic#21597] opened 2020-06-22 06:25 UTC
# Bug Report

**Ionic version:**
[x] **5.1**,   on Angular!

**Current behavior:**
Using ng-content results in an additional wrapper element between ion-page and ion-header/content , which breaks the ionic behaviour.

**Expected behavior:**
ng-content is one of the main ways in angular to create reusable and composable components.
It should work to create reusable ionic pages.

**Steps to reproduce:**

Create a generic angular ion page component that contains ion-header + ion-content, and where the actual page content can be passed in via ng-content.

**Related code:**

Here is a full example of it:

1. App-Shell-Basic:  Reusable component that implements ionheader + ioncontent for every page
```
<ion-header> 
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-button (click)="backButtonAction()">
        <ion-icon slot="icon-only" name="arrow-back" color="light"></ion-icon>
      </ion-button>
    </ion-buttons>   
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-refresher *ngIf="isPlatformBrowser" slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <!-- here is the actual page content, different for each page -->
  <ng-content></ng-content>  
</ion-content>

<!-- here comes all ion-fabs and ion-footers, different for each page-->
<ng-content select="ion-fab"></ng-content>
<ng-content select="ion-footer"></ng-content>
```

2. Example-page:  A page that uses this reusable component, and passes in the actual content
```
<app-shell-basic class="ion-page"> 
	   <!-- page content-->
	  <div>
		  I am the content of the page
	  </div>
	  
	 
	   <!-- page fab buttons-->
	  <ion-fab vertical="bottom" horizontal="end" slot="fixed">
		<ion-fab-button (click)="doFabAction()>
		   Click me
		</ion-fab-button>
	  </ion-fab>
	  
	   <!-- page footer->	   
	  <ion-footer>
		<ion-toolbar>
		  <ion-button (click)="doFooterAction()">
			My Footer Button
		  </ion-button>
		</ion-toolbar>
	  </ion-footer>	  
</app-shell-basic>
```

3. This results in following final page (which breaks ionic resizing/scrolling behaviour, unless the class "ion-page" os added manually to the additional wrapper element.
```
<ion-app>
     <ion-router-outlet>
         <example-page class="ion-page"> 
			<!-- Here we must add the additional element 'app-shell-basic' between ion-app + ion-content leads to ionic wronly sizing the ion-content. Adding class 'ion-page' manually fixes this problem.-->
			<app-shell-basic class="ion-page">
				<ion-header> 
				  <ion-toolbar>
					<ion-buttons slot="start">
					  <ion-button (click)="backButtonAction()">
						<ion-icon slot="icon-only" name="arrow-back" color="light"></ion-icon>
					  </ion-button>
					</ion-buttons>   
				  </ion-toolbar>
				</ion-header>

				<ion-content>

					<ion-refresher *ngIf="isPlatformBrowser" slot="fixed" (ionRefresh)="doRefresh($event)">
						<ion-refresher-content></ion-refresher-content>
					</ion-refresher>

					<!-- here is the actual page content, different for each page -->  
					<!-- page content-->
					<div>
						I am the content of the page
					</div>
					  

				</ion-content>

				<!-- here comes all ion-fabs and ion-footers, different for each page-->
				<!-- page fab buttons-->
				<ion-fab vertical="bottom" horizontal="end" slot="fixed">
					<ion-fab-button (click)="doFabAction()>
					   Click me
					</ion-fab-button>
				</ion-fab>
				  
				<!-- page footer->	   
				<ion-footer>
					<ion-toolbar>
					  <ion-button (click)="doFooterAction()">
						My Footer Button
					  </ion-button>
					</ion-toolbar>
				</ion-footer>
			</app-shell-basic>
		</example-page>
    </ion-router-outlet>
</ion-app>
```

**Other information:**
The angular team determined that the inserted wrapper elements are part of how angular works, and will not be changed (So its a bad idea to create a workaround that removes this additional element from the dom).

I found a possible workaround by manually applying the class "ion-page" to the new wrapper element. But here I was told by mhartington that this not something that should be done (manually using internal classes like ion-page).

**Comment by NikolaPeevski** [comment] 2020-06-22 10:37
From my recollection ng content is used for dynamic components that are parsed at runtime? So the app won't know what's inside a <ng-content></ng-content> scope thus not adding the appropriate classes etc. We used to run ng content back in the day for custom modal windows with event emitters (way back). But if you're going to reuse a whole page, why not put it in a shared module as an EntryComponent/Declaration and just use it's tags instead ? @KevinBassaDevelopment

**Comment by KevinBassaDevelopment** [comment] 2020-06-22 15:09
@NikolaPeevski 

The use case is in the example I provided.

An **reusable ionic page** that has the **same** 
- header
- refresher
- content-scroll behaviour
but has a **different**
- actual content
- ion-fab-buttons
- ion-footer

So I'm not reusing the whole page, I'm reusing a part of the "container" and a part of the content.
This is only doable with ng-content.

**Comment by NikolaPeevski** [comment] 2020-06-23 00:48
@KevinBassaDevelopment 
From my experience the header and footer have dedicated per page positioning. I did a reusable header on one of my past projects and it was a mess, ended up just using a dedicated pair for each page. It does pile up to be a lot of repeatable code, but it saves you a lot of hassle and ends up being more readable in the end, especially if two or more people are working on the same project. You can provide a repo I could look at but otherwise my suggestion would be have dedicated sharable components for the fab and content and just inject them with a shared module to where you'd desire. Also the way I see it pages in Ionic are not ment to be reusable, unless I am missing something.

**Comment by KevinBassaDevelopment** [comment] 2020-06-23 05:21
@NikolaPeevski

Why shouldnt good software patterns be used in ionic?

Repeating the same code on 100 pages is exactly what should not be done. 

NgContent can help. 
The only problem is the additional layer in Dom, which breaks some ionic behaviour.

As this can be fixed with a workaround, there probably is also a fix that can be provided by ionic.

**Comment by NikolaPeevski** [comment] 2020-06-23 05:28
@KevinBassaDevelopment 

This being a good software pattern is very subjective. Sometimes overcomplicating an implementation ruins readability and intuitiveness. I don't think pages should be reusable but if you provide a repo for reproduction and how this is not a feat/feature request and a bug I am sure @liamdebeasi will look at it :)

**Comment by KevinBassaDevelopment** [comment] 2020-06-23 05:33
I will provide a repo on the weekend.

It reduces the complexity a lot, thats why I am using it.

**Comment by indraraj26** [comment] 2020-06-23 16:11
i dont know but i have used ng-content a lot in ionic 4/5 projects but for only ion-content content tht works for me. As nikola said you shouldn't use ion header and footer common component for each page you will loose animation and endup with glitch, Its already been discussed in slack and reported by so many devs.

**Comment by KevinBassaDevelopment** [comment] 2020-06-25 08:13
There must be a way to have generic headers, otherwise any big project would be a pain to do in Ionic.

**Comment by KevinBassaDevelopment** [comment] 2020-06-26 14:57
Here is an example to show the behaviour: https://github.com/KevinBassaDevelopment/ionic-ng-content

Please keep in mind that I created this example as small as possible, just to show the behaviour of ng-content with ion-header/content.

It is not an example to display the actual use case, where many different pages would different generic page layouts.

**Comment by liamdebeasi** [comment] 2020-07-07 14:19
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When using `ng-content` or wrapping a page as a custom component, you need to ensure that any CSS from `.ion-page` is inherited. That being said, Ionic pages are not intended to be wrapped.

In this case, it looks like setting `height: 100%` on `app-shell-basic` does the trick.

**Closed by liamdebeasi** 2020-07-07 14:19 UTC
Labels: ionitron: needs reproduction
