### ISSUE TITLE
Wrong platform detected with android 5.1, android 4.4

### ISSUE THREAD

**Issue by pipoa** [ionic-team/ionic#17933] opened 2019-04-02 17:24 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

I have created 3 different simulators all base on Nexus 5X (1080x1920 density 420dpi) but got  different platforms message output.
To clarify, it's a mobile phone, not tablet not desktop.

I log the the platforms as command below:
console.log("platforms=>", this.platform.platforms());

with result: 

[android 4.4]
platforms=> ["android", "phablet", "cordova", "desktop", "hybrid"] 

[android 5.1]
platforms=> ["android","phablet","cordova","desktop","hybrid"]

[android 8]
platforms=> (5) ["android", "phablet", "cordova", "mobile", "hybrid"]

**Expected behavior:**

should as  android 8 output: "mobile" , not "desktop"

**Steps to reproduce:**

Just print out using command:
console.log("platforms=>", this.platform.platforms());

**Comment by liamdebeasi** [comment] 2019-04-03 12:55
Hi there,

Thanks for opening an issue with us. This is a known limitation with the way we do platform detection. Unfortunately, in order to fix this issue breaking changes are required.

I have a proposal for a revamp of platform detection, but this likely won't come until the next major version of Ionic (we follow semantic versioning for releases, so major versions are the only versions with breaking changes). You can view the proposal here: https://github.com/ionic-team/ionic/issues/17631

I am going to close this issue since the issue is already noted in the thread I attached, but I am going to link these issues together to ensure your use case is covered when we update our platform detection methods.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-03 12:55 UTC
Labels: triage
