### ISSUE TITLE
bug: alert buttons propagate to the below page 

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/ionic#21517] opened 2020-06-13 13:19 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
All my Alerts now seem to propagate any alert button click through to the page below it. Therefore any buttons on the page underneath are activated by using the alert buttons.

**Expected behavior:**
the alert should have no impact on the page below from taps/clicks

**Steps to reproduce:**
I tested with the exact code from the docs - pasted that into the app and exactly the same thing - so that can be used to reproduce

**Other information:**

**Ionic info:**

Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.0.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

**Comment by thiennm2905** [comment] 2020-06-14 11:51
same problem with version 5.2.1

**Comment by liamdebeasi** [comment] 2020-06-15 13:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21503. The bug has been resolved, and a fix will be available in the next release of Ionic Framework.

**Closed by liamdebeasi** 2020-06-15 13:02 UTC
Labels: triage
