### ISSUE TITLE
Prod build Ionic V4 Angular V6 issue

### ISSUE THREAD

**Issue by IT-MikeS** [ionic-team/ionic#14427] opened 2018-05-04 13:13 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
When using the released angular 6 and running `ionic build --prod` an error is returned `ERROR in Error during template compile of 'AppModule' Function calls are not supported in decorators but 'IonicModule' was called` this does not happen on `serve` or when running build without `--prod` flag

**Expected behavior:**
Build should complete.

**Other information:**
This most likely has to do with how IonicModule is exported, 
```
var IonicModule = /** @class */ (function () {
    function IonicModule() {
    }
    IonicModule.forRoot = function (config) {
        setupConfig(config);
        return {
            ngModule: IonicModule,
            providers: PROVIDERS
        };
    };
    IonicModule.decorators = [
        { type: NgModule, args: [{
                    declarations: DECLARATIONS,
                    exports: DECLARATIONS,
                    providers: [
                        p.AngularDelegate,
                        p.ModalController,
                        p.PopoverController,
                    ],
                    imports: [
                        CommonModule,
                    ]
                },] },
    ];
    return IonicModule;
}());
export { IonicModule };
```
as opposed to being defined as a class like angulars RouterModule

**Comment by alexcheng1982** [comment] 2018-05-07 08:58
I think this is caused by this [commit](https://github.com/ionic-team/ionic/commit/329a34892bbc5059c47c2c57ca2153c1c78d911a#diff-6014a5c3a03fb71e291a71f5f9e489b6) which added the function call `setupConfig(config)` to `forRoot`. I just down-graded to `4.0.0-alpha.3` to work-around this issue. 

There is already an Angular [issue](https://github.com/angular/angular/issues/14707) about this.

**Comment by mhartington** [comment] 2018-05-08 13:07
Thanks for the issue repot. This has been fixed in master and will be part of the next alpha. Closing for now!

**Closed by mhartington** 2018-05-08 13:07 UTC
Labels: triage

**Comment by thorizer** [comment] 2018-05-20 01:01
I have the same issue in ionic 3 with angular 6 in prod build.  ionic serve works great
