### ISSUE TITLE
bug: ionViewWillEnter, ionViewDidEnter not working

### ISSUE THREAD

**Issue by SerhiDi** [ionic-team/ionic#18131] opened 2019-04-25 15:35 UTC
# Bug Report

**Ionic version:**

[x] **4.3.0**

**Current behavior:**
ionViewWillEnter, ionViewDidEnter not always work

**Expected behavior:**
Call ionViewWillEnterand, ionViewDidEnter events for each page navigation

**Steps to reproduce:**

I have a simple app with 2 pages:
Login - for user sign in
Data - user page with current user data

On the Login page, I have only email/password submit button
On the Data page, I have user details.

I can't show correct user data because in ionic lifecycle ngOnInit working only when component init. But ionViewWillEnter working only first time after user login and redirect to the Data page.

After Logout and sign in with another user data ionViewWillEnter/ionViewDidEnter not working because of this page already in stack. And I see previous user data

**Comment by liamdebeasi** [comment] 2019-04-25 15:53
Hi there,

Thanks for the issue! Can you provide an example of how you are routing/removing views? I am pushing and popping between 2 pages, and the lifecycles events are working fine for me.

Also can you provide the output of running `ionic info`?

Thanks!

**Comment by SerhiDi** [comment] 2019-04-26 10:18
Hello,
Please see repo and video below:
https://github.com/SerhiDi/ionViewWillEnterBug

https://monosnap.com/file/QVq9h4P4OCRQxHQcIstJCDb6ereJXA

**Comment by SerhiDi** [comment] 2019-04-26 13:24
Maybe this problem between two `ion-router-outlet`. I am not sure about that. It should be checked.
I added lazy modules to Login and Index pages and now lifecycle events working as expected.

```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'login',
    pathMatch: 'full'
  },
  {
    path: 'login',
    loadChildren: 'login/login.module#LoginModule'
  },
  {
    path: 'index',
    loadChildren: 'index/index.module#IndexModule'
  }
];
```

**Comment by liamdebeasi** [comment] 2019-04-26 13:45
Hi there,

Thanks for the follow up. I am going to close this issue as it is a duplicate of https://github.com/ionic-team/ionic/issues/17992.

As a work around you can place the `ion-split-pane` content in `app.component.html` (thus preventing the nested `ion-router-outlet` scenario that you had before). The sidemenu starter project as well as the [Ionic Conference App](https://github.com/ionic-team/ionic-conference-app) both have examples on how to do this.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-26 13:45 UTC
Labels: triage

**Comment by SerhiDi** [comment] 2019-04-26 13:52
But I need `ion-split-pane` only on the Index page. Login page must be simple.

**Comment by liamdebeasi** [comment] 2019-04-26 13:55
Hi there, 

You can disable the side menu when on the login page. See the [ion-split-pane Docs](https://ionicframework.com/docs/api/split-pane) for more info.

Alternatively, if the lazy loading approach you mentioned works feel free to use that too! 🙂
