### ISSUE TITLE
Testing Ionic 4 - Remove padding and set background color but there is still white space

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic#14353] opened 2018-04-19 05:24 UTC
Details in this ticket:

https://github.com/ionic-team/ionic-cli/issues/3090

**Comment by brandyscarney** [comment] 2018-04-23 18:10
Duplicate of https://github.com/ionic-team/ionic/issues/14356

**Closed by brandyscarney** 2018-04-23 18:10 UTC
Labels: triage
