### ISSUE TITLE
Getting npm WARN ionic-angular@3.8.0 requires a peer of @angular/compiler@4.4.4

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic#13278] opened 2017-10-29 21:07 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

**I am getting the below error when trying to update Ionic :** 

```
npm WARN ionic-angular@3.8.0 requires a peer of @angular/compiler@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/compiler-cli@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/core@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/forms@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/http@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/platform-browser@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of @angular/platform-browser-dynamic@4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of rxjs@5.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.8.0 requires a peer of zone.js@0.8.18 but none is installed. You must install peer dependencies yourself.

```

**Comment by pwespi** [comment] 2017-10-30 09:32
The [changelog](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md) has been updated. In addition to installing ionic-angular@3.8.0 you should also update the dependencies in `package.json` to match [this](https://github.com/ionic-team/ionic2-app-base/blob/master/package.json) and then run `npm install`.

**Comment by kensodemann** [comment] 2017-10-30 10:38
Hello! Thank you for opening an issue with us!

I am going to close this because it is not a bug but is expected behavior if you do not update all of the dependencies that have been updated between the version you are coming from and the version you are going to as documented in the CHANGELOG file. Depending on your starting version, there may be other changes as well. Please be sure and read the CHANGELOG for any library you are updating.

Thank you for using Ionic

**Closed by kensodemann** 2017-10-30 10:38 UTC
