### ISSUE TITLE
npm run build --prod: compile errors for angular 5 / rxjs5.5x

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#13407] opened 2017-11-13 14:45 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
`npm run build --prod`
errors out with:
```
[15:30:35]  webpack started ... 
[15:30:36]  ionic-app-script task: "build" 
[15:30:36]  Error: Entry module not found: Error: Can't resolve '@angular-devkit/build-optimizer/webpack-loader' in 
            '/Users/__ME__/Ionic/__PRJ__' resolve 
            '@angular-devkit/build-optimizer/webpack-loader' in 
```

**Expected behavior:**
Should compile with  **--prod** without errors.

**Other information:**
Using:
    "ionic-angular": "^3.9.2",
    "rxjs": "^5.5.2",
    "sw-toolbox": "3.6.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "0.8.18",
    "ionic/app-scripts": "^3.1.0",
    "typescript": "^2.4.2"

Also:
1. I went through the Ionic 3.9.x **CHANGELOG upgrade tasks**
2. made sure to refactor **rxjs** (.pipe, imports etc.)
3. removed **node_modules**

Do we need to (re)add/update webpack ?
Any help highly appreciated.

**Comment by olivermuc** [comment] 2017-11-13 15:16
Addendum:
I once more removed **node_modules/** and did a fresh `npm install`, now resulting in:
```
[16:14:13]  webpack started ... 
[16:14:21]  ionic-app-script task: "build" 
[16:14:21]  Error: ./src/app/main.ts Module not found: Error: Can't resolve './app.module.ngfactory' in 
            '/Users/__ME__/Ionic/__PRJ__/src/app' resolve './app.module.ngfactory' in 
            '/Users/__ME__/Ionic/__PRJ__/src/app' using description file: 
            /Users/__ME__/Ionic/__PRJ__/package.json (relative path: ./src/app) Field 
            'browser' doesn't contain a valid alias configuration after using description file: 
            /Users/__ME__/Ionic/__PRJ__/package.json (relative path: ./src/app) using 
            description file: /Users/__ME__/Ionic/__PRJ__/package.json (relative path: 
            ./src/app/app.module.ngfactory) no extension Field 'browser' doesn't contain a valid alias configuration 
            /Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory doesn't exist .ts 
            Field 'browser' doesn't contain a valid alias configuration 
            /Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.ts doesn't exist .js 
            Field 'browser' doesn't contain a valid alias configuration 
            /Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.js doesn't exist 
            .json Field 'browser' doesn't contain a valid alias configuration 
            /Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.json doesn't exist 
            as directory /Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory doesn't 
            exist [/Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory] 
            [/Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.ts] 
            [/Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.js] 
            [/Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory.json] 
            [/Users/__ME__/Ionic/__PRJ__/src/app/app.module.ngfactory] @ 
            ./src/app/main.ts 2:0-60 
```

**Comment by olivermuc** [comment] 2017-11-13 15:42
Wow. 
It just went through fine, compiled with **--prod**.
I had 2 directives (folders) that weren't referenced in app.module and I also removed ./www.
Perhaps a combination of the two or the removal of ./www who knows.

**Comment by kensodemann** [comment] 2017-11-13 16:45
Hello! Thank you for opening an issue with us! I am closing this issue because I believe it is a duplicate of Issue https://github.com/ionic-team/ionic-app-scripts/issues/1309 (and a couple of others). Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-11-13 16:45 UTC
