### ISSUE TITLE
feat (calendar) : Ionic calendar 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20937] opened 2020-04-01 14:47 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

![image](https://user-images.githubusercontent.com/23274631/78150935-9b9cad00-7455-11ea-940c-fa44496e9b83.png)

Fourth view: Full View

**Describe Preferred Solution**

we can implement this with ion-slide with date logic

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-04-01 15:12
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15500.

**Closed by liamdebeasi** 2020-04-01 15:12 UTC
Labels: triage
