### ISSUE TITLE
bug: Issue with the default IDs added to labels of <ion-input> and <ion-textarea> 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#21555] opened 2020-06-16 17:17 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Ionic framework adds a default ID for the immediate previous label for both ion-input and ion-textarea. . (ion-input-0-lbl, ion-input-1-lbl... ). 

When we use both ion-input and ion-textarea, the auto generated id is same.  AXE chrome extension is catching it as a non-unique id for labels.  And it causes the label to be read out wrongly in the application by screen readers. 

Issue is there when we use the example below provided in the ionic website:
https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/input/index.html

Refer to item 6 in the document shared in Slack for further details.
https://ionicteam.slack.com/archives/C7CGXAVTL/p1592319616186200

**Comment by liamdebeasi** [comment] 2020-06-16 17:23
Looks like this is a duplicate of https://github.com/ionic-team/ionic/issues/21542.

**Closed by liamdebeasi** 2020-06-16 17:23 UTC
Labels: package: core, type: bug
