### ISSUE TITLE
bug: ion-segment swipe gesture triggers value change when gesture does not end anywhere near component

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic#21251] opened 2020-05-08 17:49 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Swiping down on a segment will result in a value change, even though the gesture is arguably not applicable to the segment itself. You can swipe down and actually trigger a value change. 

Demo video best explains the problem:
https://media.giphy.com/media/jmr2oeVVEPTA5LyrTY/giphy.gif
![giphy](https://user-images.githubusercontent.com/362329/81433494-a58b8d00-9132-11ea-9aca-c0dae1a5a27c.gif)

**Expected behavior:**

I'd argue that a swipe gesture in the vertical axis should probably not trigger a value change, and that the gesture should probably need to end within some vicinity of the component itself regardless of the direction. E.g. within 50-100px of the segment box itself or something reasonable.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
sharktop:topdecked-unified lincoln$ ionic info

Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.4
   @angular-devkit/schematics    : 9.1.4
   @angular/cli                  : 9.1.4
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/lincoln/Library/Android/sdk)
   NodeJS            : v12.13.0 (/usr/local/lib/node_modules/node/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a


```

**Comment by liamdebeasi** [comment] 2020-05-08 18:41
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This behavior matches the native iOS spec.

For example, if you open up the Phone app on an iPhone and go to the "Recents" tab, there is a segment at the top. The same behavior is reproducible there.

**Closed by liamdebeasi** 2020-05-08 18:41 UTC
Labels: triage

**Comment by lincolnthree** [comment] 2020-05-08 20:02
@liamdebeasi Interesting. The same thing happens in MD mode if that makes any difference. I just used iOS view as an example.

**Comment by lincolnthree** [comment] 2020-05-08 20:02
This definitely doesn't happen in native Android apps. Just tried in the Phone app.
