### ISSUE TITLE
Ionic app for windows device

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [ionic-team/ionic#18566] opened 2019-06-18 11:14 UTC
Hello,

I am new to ionic development and I need to know how do I make app which could be supported in windows phones also. I am not able to find any help from the docs...

Can anyone please provide help as to how could I add support for windows phones ?

**Comment by liamdebeasi** [comment] 2019-06-18 13:39
Hi there,

I am going to close this as this is a support request and not a bug. Ionic 4 does not provide support for Windows Phone built in.

Thanks!

**Closed by liamdebeasi** 2019-06-18 13:39 UTC
Labels: triage
