### ISSUE TITLE
v4: Some bugs on ion-list

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#14726] opened 2018-07-06 12:59 UTC
**Describe the Bug**
We try to use your `ion-list` using alpha.7 with latest beta documentation.
We also created a demo repo https://github.com/mburger81/ionic4-tests where you can navigate to Lists menu to see bugs and simulate them.

This is what we have figured out, or we think we have figured out :)

1. Breaking change, in v3 `ion-list` for default used `lines`, in v4 it seems the default is none`.` 
2. Having a look on the demo site https://beta.ionicframework.com/docs/api/list, it seems on IOS the default is with `lines`, in MD the default is `none`, in v3 there was no difference between v3 and v4 between the two modes
![image](https://user-images.githubusercontent.com/3778892/42380131-203f60ca-812d-11e8-82bf-6de82521c117.png)

3. The `full` attribute wasn't in v3, but having a look at the screenshots the `inset` property has a different look and behavior

**v3**
![image](https://user-images.githubusercontent.com/3778892/42379993-b58383d8-812c-11e8-8854-c40b4746f8a3.png)

**v4**
![image](https://user-images.githubusercontent.com/3778892/42380036-d82bf7ee-812c-11e8-8824-44bce3f819ee.png)

**Comment by brandyscarney** [comment] 2018-07-09 21:40
Thanks for the issue! I'm not sure I understand what the bug is here. From the screenshots of v4 and the code here https://github.com/mburger81/ionic4-tests/blob/master/src/app/pages/list/list.page.html, it appears to be working as intended. Could you explain more on what you're expecting?  

In v3 it wasn't possible to change the borders/lines on items unless you modified the Sass/CSS directly. Without seeing the code for that example, I think you are using the `inset` property of a list, which is a boolean property that adds some margin around the list (see the old documentation https://ionicframework.com/docs/components/#inset-list), but this is different from the newly added `lines` property.

Please let me know if I am misunderstanding you. Thanks! 🙂

**Comment by brandyscarney** [comment] 2018-08-09 20:37
I'm going to close this because it seems to be working as it should, but please let me know if I am wrong. Thanks!

**Closed by brandyscarney** 2018-08-09 20:37 UTC
Labels: needs reply
