### ISSUE TITLE
Ion-title and ion-buttons not vertical aligned on IOS device

### ISSUE THREAD

**Issue by loicShake** [ionic-team/ionic#12393] opened 2017-07-18 08:12 UTC
**Ionic version:**  
3.4.0

**I'm submitting a** 
bug report

**Current behavior:**
I have a problem with the status bar on ios device, ion-title and ion-buttons aren’t vertically aligned.
I saw that this problem is bound to the StatusBarOverlaysWebView plugin but I don’t know how to fix it.

**Steps to reproduce:**
That bug appear when I run ionic project on ios device.

**Related code:**
config.xml file :
```
<preference name="StatusBarOverlaysWebView" value="false"/>
```

app.component.ts file : 
```
platform.ready().then(() => {
      this.statusBar.styleLightContent();
      this.splashScreen.hide();
      this.initPushNotification();
    });
```

**Other information:**

**Ionic info:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0 ios copy 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.1 Build version 8T61a 
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10 
```

**Comment by jgw96** [comment] 2017-07-18 14:31
Hello, thanks for using Ionic! Would you mind posting a screenshot of the issue? And a code sample we could use to reproduce?

**Comment by jgw96** [comment] 2017-07-24 15:58
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-24 15:58 UTC
Labels: needs info, v2

**Comment by xyklex** [comment] 2017-11-27 16:51
Hi @jgw96, I don't know if the description of the issue is the same for what I'm facing, but I do have a screenshot of one app I'm doing. 

![screenshot](https://user-images.githubusercontent.com/483287/33277915-5306ebc4-d370-11e7-8a12-a98583047e5b.jpg)

On desktop, the title it is vertically centered correctly, but when I open it on any iOS browser it breaks down.
