### ISSUE TITLE
bug:  ion-slides [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic#21214] opened 2020-05-05 19:21 UTC
# Bug Report

**Ionic version:**

[x] **5.1**

**Current behavior:**
When trying to slide horizontaly I get this error message
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Expected behavior:**
Should not be trowing the error when sliding horizontaly

**Steps to reproduce:**
Slide clicking on the border of the ion-card
Here are a github repo with a reproducible code:
https://github.com/conde2/ionicbug

**Related code:**
```
<ion-content>
  <div *ngFor="let item of musicsCategoryList" class="category-block">
    <ion-row no-padding class="category-header">
      <ion-col button tappable>
        {{ item.category }}
      </ion-col>
    </ion-row>

    <ion-slides [options]="sliderConfig">
      <ion-slide *ngFor="let music of item.musics">
        <ion-card>
          <ion-card-header>
            <ion-card-title>
              {{ music.name }}
            </ion-card-title>
          </ion-card-header>
          <ion-card-content>
            <img src="https://via.placeholder.com/300x300" />

          </ion-card-content>
        </ion-card>
      </ion-slide>
    </ion-slides>
  </div>
</ion-content>
```

**Other information:**
https://imgur.com/a/shmTAUq

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.12.0 (/usr/bin/node)
   npm    : 6.14.4
   OS     : Linux 5.6
```

**Comment by conde2** [comment] 2020-05-06 13:56
Here are a github repo with a reproducible code:

https://github.com/conde2/ionicbug

**Comment by liamdebeasi** [comment] 2020-05-07 13:57
Thanks for the follow up. I am going to close this as this is not a bug in Ionic Framework. The source of the error is coming from Swiper, the library that powers `ion-slides`. Swiper is trying to cancel a non-cancelable event. Looks like the issue is here: https://github.com/nolimits4web/swiper/blob/master/src/components/core/events/onTouchMove.js#L106

We will look into reporting this bug to the Swiper team. Thanks!

**Closed by liamdebeasi** 2020-05-07 13:57 UTC
Labels: ionitron: needs reproduction
