### ISSUE TITLE
date picker not working as expected when specifying max :date:

### ISSUE THREAD

**Issue by harshzalavadiya** [ionic-team/ionic#17385] opened 2019-02-05 09:36 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
On setting up max param in datepicker months are not getting changed even if you change year
![ionic_datepicker_issue](https://user-images.githubusercontent.com/5774849/52264070-cf199f80-2956-11e9-839b-f0222e1b6f4d.gif)

**Expected behavior:**
Datepicker should show months and dates properly

**Steps to reproduce:**
Below is the code as reference let me know if I am doing anything wrong

**Related code:**

```html
<!-- home.page.html -->
<ion-item>
  <ion-label position="stacked">
    Choose Date
  </ion-label>
  <ion-datetime
    [max]="maxDate"
    display-format="DD MMMM YYYY"
    picker-format="DD MMMM YYYY"
    [(ngModel)]="date"
  ></ion-datetime>
</ion-item>
```
```typescript
// home.page.ts
export class HomePage implements OnInit {
  maxDate;

  ngOnInit() {
    this.maxDate = new Date().toISOString();
  }
}
```

**Other information:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v10.15.0 (/usr/bin/node)
   npm    : 6.5.0
   OS     : Linux 4.15
```

**Comment by liamdebeasi** [comment] 2019-02-13 14:03
Hi there,

Thanks for opening an issue with us. I am going to close this as a duplicate of #17060.

Please note that the referenced issue was closed and consolidated into a master list here: https://github.com/ionic-team/ionic/issues/16630

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-13 14:03 UTC
Labels: package: core, type: bug
