### ISSUE TITLE
bug: Popovers are not correctly positioned when opened inside shadow elements

### ISSUE THREAD

**Issue by adrm** [ionic-team/ionic#21154] opened 2020-04-29 09:23 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

I have a stencil project in which I have some shadow elements that trigger a popover. I use the popoverController exported from Ionic, passing the click event as directed in the docs. If this process is done from a shadow custom element, the popover is always positioned in the top left corner. If I change the configuration so that the parent component is not shadow, it works as expected, positioning the popover correctly.

To fix this, I am manually extracting the position info from the click and creating a fake event object with that info that I then pass onto the popoverController.

**Expected behavior:**

The popover should be correctly positioned according to the click event passed regardless of the type of element it has been triggered from.

**Steps to reproduce:**

1. Create a shadow element (in my case, using Stencil) in a project with Ionic enabled.
2. Trigger a popover from a click event inside the shadow element using `popoverController` and passing the `event` property as specified in the docs.

When clicking, the popover will open in the wrong position.

**Related code:**

I'd be happy to whip up an example but none of the demo environments you recommend allow for stencil projects AFAIK.

**Other information:**

**Ionic info:**

- @ionic/core@5.0.7
- @stencil/core@1.12.4

**Comment by liamdebeasi** [comment] 2020-04-29 14:49
When creating a new Stencil app, if you select `ionic-pwa` from the CLI options that should create a blank Stencil/Ionic application. From there if you add that to a GitHub repo and send a link, I can take a look.

**Comment by adrm** [comment] 2020-05-04 11:16
I created a repo that shows the problem: https://github.com/adrm/bug-ionic-popover-shadow-positioning

I added a button that shows a popover in the profile view. Now, the profile view is shadow and the popover is not positioned correctly. If you make that component non shadow you'll see that the popover is indeed positioned correctly.

Let me know if you need anything more.

**Comment by adrm** [comment] 2020-05-04 11:17
Also, you can clearly see that theme colors do not go through shadow elements. I don't really know if that can be fixed.

**Comment by liamdebeasi** [comment] 2020-05-08 15:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The reason why this behavior is happening is because the `target` in your MouseEvent is `app-profile`, not the `ion-button` that users click to present the popover. As a result, the popover was being presented relative to `app-profile`.

When setting `app-profile` to be a shadow component, any inner events are going to be retargeted to only expose the Shadow DOM host. Since `app-profile` is the host, that will be the target instead of `ion-button`. 

You can "fake" your own event by doing something like:

```typescript
await popoverController.create({
  event: {
    target: // get ion-button reference in event.path
  } as any,
  component: 'test-popover'
});
```

The other option would be to not have `app-profile` be in the shadow dom. You may find it easier to style your application by having the pages in the light dom, but have individual components (such as `ion-button`, `ion-item`, etc) remain in the shadow dom. Hope this clears things up!

**Closed by liamdebeasi** 2020-05-08 15:07 UTC
Labels: ionitron: needs reproduction
