### ISSUE TITLE
bug: In ion-input of type number, adding a dot valid the field with a pattern validator

### ISSUE THREAD

**Issue by rangzen** [ionic-team/ionic#21461] opened 2020-06-09 07:26 UTC
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**

If I add "number" type in an ion-input with a formcontrol with a pattern validator, adding a dot valid the field.

**Expected behavior:**

Adding number to type must give a hint to the browser, not changing behavior.

**Steps to reproduce:**

Check the StackBlitz.
In the preview, add 2 digits and 2 dots. The field become valid.
In the code of tab1.page.html, remove `type="number"`, the field is valid only with 7 digits like the pattern is set with `new FormControl('', Validators.pattern('[0-9]{7}'))`.

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-985xtj

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/home/bob/.nvm/versions/node/v12.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.17.0 (/home/bob/.nvm/versions/node/v12.17.0/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment] 2020-06-09 13:30
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I was able to reproduce the same behavior with a regular `input` element. Ionic does not handle form validation, so it is possible this is a bug in Angular.

**Closed by liamdebeasi** 2020-06-09 13:30 UTC
Labels: triage
