### ISSUE TITLE
bug: previous page nav bar stays for a while until transition animation finish 

### ISSUE THREAD

**Issue by danaamiri** [ionic-team/ionic#19294] opened 2019-09-07 04:50 UTC
hi, I'm trying to use ion-back-button on my nav bar and when I navigate to other pages everything goes fine. but my problem is that when I click on the back button in pushed page after showing prev page, the last pages nav header stays for a while until transition animation finish

is it a bug or if anyone knows how to solve this problem please tell me how to solve it

**Comment by michielcrabbe96** [comment] 2019-09-07 06:39
I had the same problem in iOS mode. Turns out, it was just because you specifically need to specify your ion-toolbar inside your ion-header for the animation to work as expected.

**Comment by danaamiri** [comment] 2019-09-07 06:50
it fixed when I moved my ion-toolbar to pages but is there any way that I can use a general custom component for the header?

**Comment by michielcrabbe96** [comment] 2019-09-07 07:30
I have been struggling with this myself. But as far as I know of, it's not possible. If you want your back animation to work on iOS, that is.

On Android there should be no problems.

**Comment by danaamiri** [comment] 2019-09-07 07:38
> I had the same problem in iOS mode. Turns out, it was just because you specifically need to specify your ion-toolbar directly inside your ion-header for the animation to work as expected. You can't put it inside a custom component.



> I have been struggling with this myself. But as far as I know of, it's not possible. If you want your back animation to work on iOS, that is.
> 
> On Android there should be no problems.

yes it's a challenging bug I think. btw thanks. I hope they fix it soon

**Comment by liamdebeasi** [comment] 2019-09-10 12:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18130.

**Closed by liamdebeasi** 2019-09-10 12:41 UTC
Labels: triage
