### ISSUE TITLE
bug: setting mode:ios breaks font on latest Chrome update

### ISSUE THREAD

**Issue by skotturi** [ionic-team/ionic#21061] opened 2020-04-16 21:52 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Fonts are not rendering correctly after the latest Google Chrome update Version 81.0.4044.113 (Official Build) (64-bit). 
Specifically, I have set 
```
    IonicModule.forRoot({
      mode: 'ios'
    }),
```
globally because I prefer the iOS styles to the android options. 

**Expected behavior:**
For the past month while developing this website, the default font that Ionic uses has been rendering perfectly fine in Chrome. The latest chrome update has changed something and now the font that ships with Ionic doesn't work in Chrome.

**Steps to reproduce:**

You can checkout https://santekotturi.com for a live demo
OR
1. generate a new ionic app (angular for for)
2. in app.module.ts set:
```
 IonicModule.forRoot({
      mode: 'ios'
    }),
```
3. run the app with `ionic serve` in Chrome (im using a Mac)
4. all bold fonts will be rendered as `font-weight:400`

**Related code:**
see above

**Other information:**

If you inspect the computed font, it shows up as: `-apple-system`
maybe chrome has changed something here?
I noticed the font changed in the url bar with the latest update. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.5.0 (/Users/santekotturi/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.900.5
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 9.0.5
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/Users/santekotturi/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-04-16 22:12
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

This appears to be a known bug in Chromium and should be fixed in an upcoming release: https://bugs.chromium.org/p/chromium/issues/detail?id=1057654

**Closed by liamdebeasi** 2020-04-16 22:12 UTC
Labels: triage
