### ISSUE TITLE
 Uncaught (in promise): invalid views to insert

### ISSUE THREAD

**Issue by JerryMissTom** [ionic-team/ionic#13759] opened 2018-01-04 06:04 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

I want to write a Contact, as follows :
<img width="334" alt="13" src="https://user-images.githubusercontent.com/15966403/34551657-ead0e32a-f156-11e7-8611-85f915fd2b3c.png">
html:
<img width="341" alt="14" src="https://user-images.githubusercontent.com/15966403/34551707-416a4140-f157-11e7-9ef0-cfa4f566226a.png">
<img width="832" alt="15" src="https://user-images.githubusercontent.com/15966403/34551730-60030d4e-f157-11e7-94d7-e6488dfe9404.png">

**Current behavior:**
when I click the tag `li`, it will cause a error, the detail is below:
<img width="996" alt="12" src="https://user-images.githubusercontent.com/15966403/34551752-909bbc30-f157-11e7-9132-f7624e6c002b.png">

**Ionic info:** :

<img width="475" alt="16" src="https://user-images.githubusercontent.com/15966403/34551777-c93feaac-f157-11e7-94ac-25e9f393bb61.png">

**Comment by kensodemann** [comment] 2018-01-04 11:50
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by davec21** [comment] 2018-01-04 14:41
I don't think using Anchors works properly with ionic.. at least I've never had them work.

**Comment by JerryMissTom** [comment] 2018-01-05 02:35
@kensodemann  In fact, I use HTML anchors to go to specific location. Do anchors works well in ionic3.10? just as @davec21  said.

**Comment by kensodemann** [comment] 2018-01-06 04:54
@JerryMissTom - I will have to research that some more. I have never personally tried using anchors in an Ionic app for any reason, but I believe that what you have above will be interpreted as a view name, at least if you are using lazy loading. Like I said, though, I will have to look into that some more.

**Comment by JerryMissTom** [comment] 2018-01-06 08:29
@kensodemann do you mean that the value of `href` in tag `a` will be interpreted as a view name like `LoginPage` ? My demo is simple without lazy loading, forward to your future research.

**Comment by kensodemann** [comment] 2018-01-08 17:00
@JerryMissTom - I confirmed that our nav system is going to take the URL change and try to find a view that matches rather than taking into account that this could be an anchor within the same page. I do not see a way around this in the current version of Ionic.

For the next major release of Ionic, we plan on relying more heavily on whatever router is used by the Framework (Angular in this case). That may resolve this issue.

Since all current work is focused on getting the next major release ready for release, I will mark this as something to look at again at that time.

**Comment by JerryMissTom** [comment] 2018-01-09 01:33
@kensodemann Thanks, and look forward to next major release.

**Closed** 2018-12-08 09:38 UTC
Labels: ionitron: v3
