### ISSUE TITLE
bug: error on starting ionic project

### ISSUE THREAD

**Issue by devsalimsulaiman** [ionic-team/ionic#21277] opened 2020-05-12 00:28 UTC
C:\Users\school\Desktop\Salim\MyDev>ionic start helloMinna sidemenu

Pick a framework!

Please select the JavaScript framework to use for your new app. To bypass this
prompt next time, supply a value for the --type option.

? Framework: Angular
√ Preparing directory .\helloMinna - done!
√ Downloading and extracting sidemenu starter - done!

Installing dependencies may take several minutes.

  ──────────────────────────────────────────────────────────────────────────────

         Ionic Advisory, tailored solutions and expert services by Ionic

                             Go to market faster
                    Real-time troubleshooting and guidance
        Custom training, best practices, code and architecture reviews
      Customized strategies for every phase of the development lifecycle

               Learn more: https://ion.link/advisory

  ──────────────────────────────────────────────────────────────────────────────

> npm.cmd i
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellane
ous Warning ETIMEDOUT: request to https://registry.npmjs.org/rxjs failed, reason
: connect ETIMEDOUT 104.16.18.35:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a req
uest error during revalidation.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade
to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git
hub.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and coul
d be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprec
ated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep
recated
npm ERR! Unexpected end of JSON input while parsing near '...37KrMCe2uTs4nNIj5mD
cF'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\school\AppData\Roaming\npm-cache\_logs\2020-05-12T00_20_24
_714Z-debug.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i exited with exit code 1.

        Re-running this command with the --verbose flag may provide more
        information.

C:\Users\school\Desktop\Salim\MyDev>

**Comment by devsalimsulaiman** [comment] 2020-05-12 00:29
please any help on how to solve this error?

**Comment by liamdebeasi** [comment] 2020-05-12 03:00
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. You might want to run `npm cache verify` which verifies the contents of the cache folder and garbage collects any unneeded data. This may also have just been a temporary glitch on npm's end.

Thanks!

**Closed by liamdebeasi** 2020-05-12 03:00 UTC
Labels: triage
