### ISSUE TITLE
bug: [Ionic React] Multiple <IonToast> components render on top of one another

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic#19132] opened 2019-08-19 11:21 UTC
# Bug Report

**Ionic version:**
[x] **4.7.1**
**Ionic React version:**
[x] **0.0.9**

**Current behavior:**
As `ToastController` doesn't seem to be working in React package yet, I had to implement a simple module to display all of my notifications from one place.
I simply map my global `notifications` with `IonToast` component.
I expected the toasts to render in one container, but they're actually render a separate overlay for each one. Moreover, if I wrap them in any container, they get ejected out of it and up into `IonApp` component.
IonToast also ignores `style` prop, so I can't style it's position dinamically.

**Expected behavior:**
Multiple `IonToast` components should appear one after the other and not overlap.
`IonToast` component should at least have a mode to display inside a custom wrapper component to have more control over its position;

**Steps to reproduce:**
Create a blank Ionic React app, and add `<Notifications />` component with the code from here:
https://pastebin.com/cSxHzpsD

**Ionic info:**

```
Ionic:
   Ionic CLI       : 5.2.3 (C:\Users\sato\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 0.0.9

Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by elylucas** [comment] 2019-08-23 03:30
Hi @SatoAV,

Going to address a few things here:

Toasts do in fact appear out of their container (or component) that you define them in. This is by design and how toasts work from ionic/core. The IonToast component itself actually doesn't render anything on its own, it calls into core apis to show the toast. Therefore, adding a style attribute isn't supported since there's no html tag to put the style on.  

To make up for this, you can use the cssClass property to add a custom css class that will show on the toast.

You can also position a toast with the position property, with values of "bottom" | "middle" | "top".

Toasts don't stack on top of each other when multiple ones are shown at the same time. We have considered implementing this feature but have not gotten to it yet.

Going to close this issue for now, but if you have more questions let us know.

Thanks

**Closed by elylucas** 2019-08-23 03:30 UTC
Labels: package: react
