### ISSUE TITLE
<ion-reorder-group> freezes list on reorder: Ionic 4.0.0-beta.13

### ISSUE THREAD

**Issue by conorseed** [ionic-team/ionic#16115] opened 2018-10-27 08:25 UTC
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.8
   @capacitor/core           : 1.0.0-beta.8

System:

   NodeJS : v8.12.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
```

**Describe the Bug**
List freezes in place on release of drag+drop reorder. List is still clickable and will respond in other ways, but the items remains EXACTLY where it was dropped and no other re-ordering can take place.  Using <ion-reorder-group> inside an <ion-list> on an array of <ion-item>. 

**Steps to Reproduce**
1. Setup a list, with some items inside a reorder-group
2. Drag an item to reorder it
3. On release, the item will freeze exactly where it was, with drop-shadow around the item being moved

**Related Code**
`<ion-list lines="full">
    <ion-reorder-group disabled="false">
      <ion-item>
        <ion-reorder slot="start"></ion-reorder>
        <ion-label text-wrap>
          <h2>Item 1</h2>
          <p>Yup items.
            <span>Created ages ago.</span>
          </p>
        </ion-label>
      </ion-item>
      <ion-item>
        <ion-reorder slot="start"></ion-reorder>
        <ion-label text-wrap>
          <h2>Item 2</h2>
          <p>Yup items.
            <span>Created ages ago.</span>
          </p>
        </ion-label>
      </ion-item>
      <ion-item>
        <ion-reorder slot="start"></ion-reorder>
        <ion-label text-wrap>
          <h2>Item 3</h2>
          <p>Yup items.
            <span>Created ages ago.</span>
          </p>
        </ion-label>
      </ion-item>
    </ion-reorder-group>
  </ion-list>`

**Expected Behavior**
Freely re-order all items in a list without freezing.

**Additional Context**
This is my first proper submission to Github to please excuse the noobiness! Happy to provide any extra info required.

**Comment by mmlleevvyy** [comment] 2018-10-27 23:42
Duplicate of #16068

**Comment by conorseed** [comment] 2018-10-28 00:45
> Duplicate of #16068

Thanks @mmlleevvyy. That fixes it. Nice to see some more docs on it too. I knew there was docs at https://beta.ionicframework.com/docs/, but didn't realise there was some on here!

**Comment by brandyscarney** [comment] 2018-11-28 23:50
Closing as duplicate of https://github.com/ionic-team/ionic/issues/16068, thanks!

**Closed by brandyscarney** 2018-11-28 23:50 UTC
Labels: triage
