### ISSUE TITLE
feat: Support for ion-alert with date type input on Safari

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#21571] opened 2020-06-17 20:05 UTC
# Feature Request

**Ionic version:**

[x] **5.2.1**

**Describe the Feature Request**

Support type date in ion-alert input for Safari

**Describe Preferred Solution**

Right now setting type: 'date' on an input within an ion-alert works in chrome and formats it properly but does not work in Safari.  I'm hoping there is a way to make this work on Safari.

**Describe Alternatives**

Allow variable with type date to always be emitted from the data object in the dandler.

**Comment by liamdebeasi** [comment] 2020-06-17 20:28
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Safari does not support `type="date"`, so it is not something that will work at the moment in `ion-alert`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date.

**Closed by liamdebeasi** 2020-06-17 20:28 UTC
Labels: triage
