### ISSUE TITLE
bug: Position calculation of popover produces negative top position (offscreen)

### ISSUE THREAD

**Issue by VektorPixel** [ionic-team/ionic#21000] opened 2020-04-09 06:58 UTC
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**

When using a popover (either with ion-select or not) and there is not enough room below the related control the popover will open above the control. That's fine.
But: The popover opens upwards when the space above the control is smaller than the popover height. It seems that the calculation does not consider the height of the related control.
So the top value of the popover is negative.

**Expected behavior:**

The popover should only open upwards when there is enough space.

**Steps to reproduce:**

1. Create a new Ionic sidemenu project (I used framework version 5.0.7)
2. Replace the div with the content-id in the folder.page.html with the following code.
3. Serve it, switch to responsive mode and set the height of the viewport to 309 px.
4. Click on Popover

**Related code:**

```
<div style="padding-top:110px">
    <ion-item>
      <ion-label>Popover</ion-label>
      <ion-select interface="popover" placeholder="Select One">
        <ion-select-option value="brown">I'm off screen. No!</ion-select-option>
        <ion-select-option value="blonde">Blonde</ion-select-option>
        <ion-select-option value="black">Black</ion-select-option>
        <ion-select-option value="red">Red</ion-select-option>
      </ion-select>
    </ion-item>
  </div>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.14
   @angular-devkit/schematics    : 8.3.14
   @angular/cli                  : 8.3.14
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.16.2
   npm               : 6.11.3
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-04-09 13:31
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by VektorPixel** [comment] 2020-04-09 14:46
Sure @liamdebeasi 
Here you go:
https://github.com/VektorPixel/Ionic-Popover-position-issue-example

**Comment by liamdebeasi** [comment] 2020-04-09 15:14
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

Ionic Framework does a few calculations in order to position the popover as best it can. One requirement is that the popover does not overlap the `ion-select` that it is presented from (I.e. the popover should not cover the `Select One` label).

If there is not enough space above or below the popover, the popover will appear slightly offscreen. In this scenario, you are likely going to need to reduce the height of the popover and have it scroll when it comes to viewports of 300px. Alternatively, you could apply a `margin-top` on `ion-select-popover` to move the select popover over the "Select One" label if that is something you are comfortable doing.

Hope this helps!

**Closed by liamdebeasi** 2020-04-09 15:14 UTC
Labels: triage
