### ISSUE TITLE
bug: ios page transition opacity/shadow issues

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [ionic-team/ionic#19973] opened 2019-11-22 17:17 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Below are two samples - one is application in mode 'ios', the other is in mode 'md', but with navAnimation: iosTransitionAnimation (pulled straight from ionic sources). On both, some shadow/opacity issues can be observed during the transition (on the leaving view). It's especially annoying on the header, where you can clearly see it's bottom border looking differently during transition.

![ios](https://user-images.githubusercontent.com/11352013/69446161-1f31e900-0d54-11ea-9008-be72167801bf.gif)
![md](https://user-images.githubusercontent.com/11352013/69446162-20fbac80-0d54-11ea-9a37-dfc61a1cc39b.gif)

**Expected behavior:**
No visual artifacts.

**Steps to reproduce:**
Navigate from one route to the other using router (this.router.navigate). Alternatively, same behavior can be observed on ion-nav.

**Related code:**

Both views look like this:
```
<ion-header>
  <ion-toolbar>
    <ion-title>Test #</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div class="ion-padding">
  </div>
</ion-content>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.6 (/opt/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/rattkin/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/opt/local/bin/node)
   npm               : 6.13.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500
```

**Comment by liamdebeasi** [comment] 2019-11-22 17:30
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I'm not seeing this on my end.

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 17:33
Unfortunately, no - sorry! I'm not very good with this whole plunker things, etc. - and my examples come straight from projects for clients, cannot directly share that. I can provide some more info when needed or try things at my end.

**Comment by liamdebeasi** [comment] 2019-11-22 18:06
Just so I understand -- in that second gif, you are running the app in MD mode, but overriding the nav animation to be the iOS animation?

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 18:08
Yes. But it doesn't really matter, I think. The same shadow effect can be observed when the app is in ios mode, without overriding transitions.

**Comment by liamdebeasi** [comment] 2019-11-22 18:09
Ok interesting. Where is the "shadow effect" appearing? I'm not sure I'm seeing it in the first gif.

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 18:12
Well, on the whole area. During transition, the view that leaves, seems to have a much darker color/background, than when not in transition. It might be intended, but in that second case, I think it's exactly this, that affects the ion-header border (it getting darker, etc.).

**Comment by liamdebeasi** [comment] 2019-11-22 18:19
Thanks for the clarification. For the issue in the first gif, are you referring to this?

![image](https://user-images.githubusercontent.com/2721089/69450161-89359880-0d2a-11ea-8c01-311fe81f4019.png)

If so, then this is the standard iOS navigation transition behavior. Native iOS apps have a page shadow on transition with a backdrop darkening the leaving view.

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 18:26
Fair enough. But I think we agree that it doesn't work well with header, that has a border. Now, I guess this is the part, where I learn again "it is not supported", so I just would like to learn, which part of `@ionic/core/dist/collection/utils/transition/ios.transition.js` is responsible for adding that shadow, as I couldn't pinpoint it. I could create my new custom transition basing on this, but don't know how to remove that shadow.

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 18:28
I've managed to create a sample project, after all, to show that issue.

[test.zip](https://github.com/ionic-team/ionic/files/3880893/test.zip)

**Comment by liamdebeasi** [comment] 2019-11-22 19:11
Thanks for the reproduction. I think there may be two different issues:

The first issue, as seen in the first gif, is standard iOS navigation behavior and not a bug (See my comment above for an explanation).

The second issue, as seen in the second gif, looks like you just need to customize the animation a bit. The behavior shown in the second gif is not caused by the transition shadow. The iOS animation is intended for apps running in iOS mode, and the MD animation is intended for apps running in MD mode. As a result, there may be some visual glitches when using the iOS animation in MD mode.

The easiest solution here is to just copy the iOS animation into your app and customize it as you see fit: https://github.com/ionic-team/ionic/blob/master/core/src/utils/transition/ios.transition.ts

I think the main difference stems from the fact that the iOS animation attempts to animate the page as well as the toolbars, but the MD animation just animations the page as a whole (rather than also animating the toolbars).

Does that clear things up?

**Comment by sebastian-zarzycki-es** [comment] 2019-11-22 19:18
I think so, yes. Thanks for looking into it.

**Comment by liamdebeasi** [comment] 2019-11-22 19:23
Great! I am going to close this issue as the main issue seems to be resolved. Thanks!

**Closed by liamdebeasi** 2019-11-22 19:23 UTC
Labels: triage
