### ISSUE TITLE
Building --prod with 29 colors in variables.scss causes white screen

### ISSUE THREAD

**Issue by Yunksi** [ionic-team/ionic#12751] opened 2017-08-25 07:04 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**
1. ionic start whiteScreenWithALotOfColors tabs
2. replace $colors with code above
3. ionic cordova platform add android
4. ionic cordova run android --prod

**Related code:**

```
$colors: (
  primary: #97ca44,
  secondary: #38a550,
  tertiary: #db584a,
  quaternary: #b53d78,
  quinary: #613a94,
  danger: #f53d3d,
  light: #f4f4f4,
  dark: #222,
  divider: #d7d7d8,
  loginLinks:#808080,
  shortcutColor0: #cfd8dc,
  shortcutColor1: #f44336,
  shortcutColor2: #e91e63,
  shortcutColor3: #9c27b0,
  shortcutColor4: #3f51b5,
  shortcutColor5: #2196f3,
  shortcutColor6: #00bcd4,
  shortcutColor7: #009688,
  shortcutColor8: #4caf50,
  shortcutColor9: #8bc34a,
  shortcutColor10: #cddc39,
  shortcutColor11: #ffeb3b,
  shortcutColor12: #ffc107,
  shortcutColor13: #ff9800,
  shortcutColor14: #ff5722,
  shortcutColor15: #795548,
  shortcutColor16: #000000,
  pendingLogColor: #ffc107,
  durationInputHeeader: #00897b
);
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\brokenAppWithMultipleColors\node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v7.10.0
    npm  : 4.0.2
    OS   : Windows 10
```

**Comment by AmitMY** [comment] 2017-08-25 11:37
In theory, this generates s 50kb*30 colors css bundle which is 1.5mb.
This is a duplicate of https://github.com/ionic-team/ionic-app-scripts/issues/506

**Comment by kensodemann** [comment] 2017-08-25 11:49
Hello! Thank you for opening an issue with us!

@Yunksi - if you look at the issue @AmitMY linked there is a good explanation as to why the issue exists and also some ways people have worked around it.

And thank you @AmitMY. I was just about to move this, but no point creating duplicate issues... :)

Thank you for using Ionic

**Closed by kensodemann** 2017-08-25 11:49 UTC

**Comment by Yunksi** [comment] 2017-08-25 11:52
I'm sorry for opening duplicate issue, didn't see that one before. Thanks for pointing that one out.
