### ISSUE TITLE
Cordova is not working with Angular 9.

### ISSUE THREAD

**Issue by Ahmadtawfik-10** [ionic-team/ionic#20479] opened 2020-02-13 20:34 UTC
When i upgraded my project to ionic 5 with latest version of angular 8, cordova plugins works perfectly, but when i upgrade to angular 9, plugins don't work.
i use: ionic cordova run android --consolelogs -l --no-native-run --address=0.0.0.0

**Comment by liamdebeasi** [comment] 2020-02-13 20:40
Thanks for the issue. It looks like the issue is caused by this: https://github.com/ionic-team/angular-toolkit/issues/184.

There is a PR that is open and should be merged soon: https://github.com/ionic-team/angular-toolkit/pull/201

**Closed by liamdebeasi** 2020-02-13 20:40 UTC
Labels: triage
