### ISSUE TITLE
bug: Issued start a new Project

### ISSUE THREAD

**Issue by alfredoizjr** [ionic-team/ionic#12174] opened 2017-06-27 13:41 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>3</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>when I try create a new project I have this error

```
C:\Users\Alfredo\Desktop>ionic start appstore sidemenu
? The directory appstore contains file(s) that could conflict. Would you like to overwrite the directory with this new
project? Yes
✔ Creating directory .\appstore - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template sidemenu (https://github.com/ionic-team/ionic2-starter-sidemenu/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Alfredo\AppData\Roaming\npm-cache\_logs\2017-06-27T13_24_41_639Z-debug.log
```

this is my ionic info

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

System:

    Node       : v8.1.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3</span>

```
<span is-issue-template></span>

**Comment by AmitMY** [comment] 2017-06-27 14:40
- Please make sure you have `git` installed and added to `PATH`, by running `git` in command line

**Comment by alfredoizjr** [comment] 2017-06-27 14:44
Yes I do I have the git installed I my machine I cut before create a new project, but not now

**Comment by jgw96** [comment] 2017-06-27 14:45
Hello all! We are actively looking into this issue. I am setting up the oldest similar issue as a tracking issue and therefore and closing this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12158. Thanks!

**Closed by jgw96** 2017-06-27 14:45 UTC
