### ISSUE TITLE
bug: Uncaught (in promise) overlay does not exist

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21126] opened 2020-04-24 21:06 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

If Loader is closing after a few milliseconds, it returns this error.
Uncaught (in promise) overlay does not exist

**Expected behavior:**
It should directly close the loader.

**Steps to reproduce:**

I am using this code:
```
showLoader(); // This creates a loader
stopLoader(); // This stop the loader (dismiss)
```

**Related code:**
```
async function showLoader() {
   const loading = await loadingController.create({
      message: 'Loading...',
   });
   await loading.present();
}
async function stopLoader() {
   await loadingController.dismiss();
}
```

**Ionic info:**

```
@ionic/core@5.0.7
```

**Comment by liamdebeasi** [comment] 2020-04-24 22:08
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The presenting/dismissing of the overlay is asynchronous. In your code, you make a call to show the loader, but then you immediately try to dismiss it. It is possible that the component has not even been created by the time you call `dismiss`. Since you are not waiting for any of the promises to resolve, you are introducing a race condition in your code.

**Closed by liamdebeasi** 2020-04-24 22:08 UTC
Labels: triage
