### ISSUE TITLE
feat: change the border radius of the ion-searchbar

### ISSUE THREAD

**Issue by Kernolsie** [ionic-team/ionic#18247] opened 2019-05-10 06:25 UTC
# Feature Request

**Ionic version:**
Anything 4 really...
[x] **4.x**

**Describe the Feature Request**
I have the intense desire to change the border radius of the ion-searchbar, is it possible to expose a **--border-radius** CSS custom property variable for the component?

**Describe Preferred Solution**
Please expose a **--border-radius** CSS custom property variable for the ion-searchbar

**Describe Alternatives**
No normal CSS styling reaches the component because of shadowDOM. This is what I have tried:

ion-searchbar{
    .searchbar-input-container{
        .searchbar-input{
            border-radius: 30px !important;
        }
    }
}

**Related Code**
Not relevant

**Additional Context**
Not relevant

**Comment by SulimanTwfiq** [comment] 2019-05-18 16:43
remove .searchbar-input-container ,so at the end it should be like this
ion-searchbar{
.searchbar-input{
border-radius: 30px;
}
}
it works for me .

**Comment by RadGade** [comment] 2019-07-09 05:41
same problem 
`ion-searchbar{
    .searchbar-input{
    border-radius: 90px;
    }
    }`

**Comment by Kernolsie** [comment] 2019-07-09 06:40
@RadGade  As a workaround you can simply move your CSS styling to the global.scss and then it works for me:

``` 
ion-searchbar{
    .searchbar-input-container{
        .searchbar-input{
            border-radius: 30px !important;
        }
    }
}
```

**Comment by RadGade** [comment] 2019-07-10 10:10
@Kernolsie  Thanks man, it worked

**Comment by sebinbenjamin** [comment] 2019-09-29 17:47
```
ion-searchbar {
  input {
    border-radius: 30px !important;
  }
}
```
Also works !

**Comment by sebinbenjamin** [comment] 2019-09-29 17:49
#18247 seems to be a duplicate of #17426

**Comment by liamdebeasi** [comment] 2020-04-03 17:01
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20662 and will be available in an upcoming release of Ionic Framework.

**Closed** 2020-04-03 17:01 UTC
Labels: package: core, type: feature request
