### ISSUE TITLE
bug: ios cannot type non-english in ionic input correctly

### ISSUE THREAD

**Issue by royanon** [ionic-team/ionic#18816] opened 2019-07-17 10:41 UTC
# Bug Report

**Ionic version:**
[x] **4.6.2**

**Current behavior:**
ios cannot type non-english input, it will fire on every type, even backspace will fire non-finished typing in ionic input.

**Expected behavior:**
ios can type non-english input correctly in ionic input.

**Steps to reproduce:**
* use ionic input with any non-english input

Wong behavior: (@ionic/angular 4.6.2)
![wrong](https://user-images.githubusercontent.com/16112016/61368302-28034180-a8c0-11e9-9e0a-0f5e930f7798.gif)

Correct behavior: (@ionic/angular 4.4.2)
![correct](https://user-images.githubusercontent.com/16112016/61368320-2fc2e600-a8c0-11e9-94e4-4a88decde698.gif)

**Related code:**
N/A

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/bin/node)
   npm    : 6.10.1
   OS     : Linux 3.10

**Comment by maxtacco** [comment] 2019-07-17 14:31
Looks like a duplicate of https://github.com/ionic-team/ionic/issues/18768

**Comment by liamdebeasi** [comment] 2019-07-17 15:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18768.

**Closed by liamdebeasi** 2019-07-17 15:56 UTC
Labels: triage
