### ISSUE TITLE
bug: variable --border-width not work in ion-toolbar 

### ISSUE THREAD

**Issue by Rodrigo54** [ionic-team/ionic#18471] opened 2019-06-05 19:20 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
in ios mode the css variable border-width in the elemet ion-toolbar is not work

**Expected behavior:**
this works when I set the variable --border-width: 0px;

**Steps to reproduce:**
customise ion-toolbar element and see in ios mode

**Related code:**
```css
ion-toolbar{
  --border-width: 0px;
}
```

**Other information:**
this it work
```css
ion-toolbar{
  --border-width: 0px !important;
}
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.1 (/Users/rodrigoklayton/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   ios-sim : 8.0.1
   NodeJS  : v12.4.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm     : 6.9.0
   OS      : macOS High Sierra
   Xcode   : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment] 2019-06-07 13:39
Hi there,

Thanks for the issue! I was able to reproduce this. Looks like the issue is here: https://github.com/ionic-team/ionic/blob/master/core/src/components/header/header.ios.scss#L8

We will look into a fix for this. Thanks!

**Comment by Rodrigo54** [comment] 2019-06-07 14:04
in the footer too

https://github.com/ionic-team/ionic/blob/master/core/src/components/footer/footer.ios.scss#L8

**Comment by Simbaclaws** [comment] 2020-02-10 13:36
Any news on this? I have tried doing this in a footer but am getting the same issue. I'm experiencing this for MD as well.

**Comment by liamdebeasi** [comment] 2020-02-10 14:46
Hi everyone,

I just wanted to provide an update here. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17425. This looks to be a bug with scoped components and overriding styles.

As a workaround, you can either:

a) match the CSS selector exactly (I.e. `.header-ios ion-toolbar:last-of-type`)
b) use `!important`

Here is an example: https://codepen.io/liamdebeasi/pen/NWqqRWv

We will provide updates regarding this issue in the thread I linked to. Thanks!

**Closed by liamdebeasi** 2020-02-10 14:46 UTC
Labels: package: core, type: bug
