### ISSUE TITLE
floating ion-textarea not floating up 

### ISSUE THREAD

**Issue by jtushar53** [ionic-team/ionic#17559] opened 2019-02-21 12:15 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
using ion-textarea floating in reactive form, while updating form using patchValue floating placeholder is not moving up. maybe the issue is also with ion-input 

**Expected behavior:**
Floating placeholder should move up if value is set into the field programatically
**Steps to reproduce:**
1. create a reactive form in ts file
2. add ion-textarea in the html 
3. add value to the form using patchValue (didn't tried it with setValue, currently my json has additional fields) in ngOnInit or ionViewDidEnter

**Related code:**

```
**HTML**
<form [formGroup]="adminForm">
 <ion-item>
            <ion-label position="floating">Remarks</ion-label>
            <ion-textarea rows="6" formControlName="remarks"></ion-textarea>
  </ion-item>
</form>

**TS**
inside ngOnInit
 this.adminForm = this._fb.group({
        remarks: ['', Validators.required]
    });

inside ionViewDidEnter or ngOnInit
 this.adminForm.patchValue({remarks : 'test remarks'});
      this.adminForm.updateValueAndValidity();


```

**Other information:**
Below is the screenshot, ion-textarea is having ion-label as Remarks with value test
![image](https://user-images.githubusercontent.com/5780117/53168202-29298e80-3600-11e9-8854-fc4ae83c7b21.png)

Is should look like below

![image](https://user-images.githubusercontent.com/5780117/53168309-61c96800-3600-11e9-8db9-5ab51966b484.png)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by hsnbrji** [comment] 2019-02-25 11:22
I have the same issue as well. Did you manage to fix this @jtushar53 ?

**Comment by jtushar53** [comment] 2019-02-27 04:11
as of now i am using below workaround

```
  <ion-col>
            <ion-item lines="none">
              <ion-label
                position="{{
                  adminForm.controls['remarks'].value ? 'stacked' : 'floating'
                }}"
                >Remarks</ion-label
              >
              <ion-textarea
                #textarea
                rows="6"
                formControlName="remarks"
              ></ion-textarea>
            </ion-item>
          </ion-col>
```

Where adminForm is the formgroup

**Comment by mburger81** [comment] 2019-04-04 14:38
@liamdebeasi we have have the same issue, very similar to #17851

**Comment by mburger81** [comment] 2019-04-04 14:41
@jtushar53 please rename the issue, the problem is for `ion-textarea` and not for `ion-input`, you also describe in your issue that the problem is textarea ;)

**Comment by brandyscarney** [comment] 2019-04-11 21:52
Thanks for the issue! Is this a duplicate of #17555?

**Comment by mburger81** [comment] 2019-04-11 21:58
@brandyscarny I think you set the needs replay label on the wrong issue, your intention was probably to set it to #17555 😊

**Comment by brandyscarney** [comment] 2019-04-11 22:05
@mburger81 No I wanted the reply of if this was a duplicate :grin:

**Comment by mburger81** [comment] 2019-04-11 22:07
Ok sorry, yes IMO this is a duplicate, tomorrow I'll do the test with ngmodel

**Comment by brandyscarney** [comment] 2019-04-11 22:30
Haha okay, thank you! I will close this one then.

**Closed by brandyscarney** 2019-04-11 22:30 UTC
Labels: triage
