### ISSUE TITLE
ionViewCanLeave does not work on tab change.

### ISSUE THREAD

**Issue by Creawebs** [ionic-team/ionic#11845] opened 2017-05-29 08:24 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

` ionViewCanLeave() {
      if (this.showAlertMessage) {
          let alertPopup = this.popUp.create({
              title: '',
              message: 'Su perfil no ha sido guardado ¿Desea salir?',
              buttons: [{
                  text: 'Ok',
                  handler: () => {
                      alertPopup.dismiss().then(() => {
                          this.exitPage();
                      });
                  }
              },
              {
                  text: 'Cancelar',
                  handler: () => {
                      // need to do something if the user stays?
                  }
              }]
          });

          // Show the alert
          alertPopup.present();

          // Return false to avoid the page to be popped up
          return false;
      }
  }`
The function is executing but the tab still changes. When I return to the tab, I can see the alert.
**Expected behavior:**

The behavior should not allow me to change tabs if the condition isn't met.

**Steps to reproduce:**

**Related code:**
I have a few customs on the tabs code.
`<ion-tabs #myTabs class="tabs-home ios" (ionChange)="tabChanged($event)">
    <ion-tab [root]="tab1Root" (ionSelect)="changeTab('Inicio')" tabTitle="Inicio" tabIcon="fa-home"></ion-tab>
    <ion-tab tabBadge="{{badge}}" tabBadgeStyle="danger" [root]="tab2Root" tabTitle="Mensajes" tabIcon="fa-envelope"></ion-tab>
    <ion-tab [root]="tab3Root" tabTitle="Mis Notas" tabIcon="fa-pencil-square-o"></ion-tab>
    <ion-tab [root]="tab4Root" tabTitle="Networking" tabIcon="fa-id-card"></ion-tab>
</ion-tabs>`
`export class TabsPage {
  // this tells the tabs component which Pages
  // should be each tab's root Page
  tab1Root: any = HomePage;
  tab2Root: any = MensajesPage;
  tab3Root: any = NotasPage;
  tab4Root: any = NetworkingPage;
  subscription: Subscription;
  badge: any;
  tabBarElement: any;
  @ViewChild('myTabs') tabRef: Tabs;

  constructor(public app: App, private keyboard: Keyboard, public navCtrl: NavController, public navParams: NavParams,public ph: PushProvider,public platform: Platform, public sh: SharedProvider) {
      this.platform.ready().then(() => {
          
          this.subscription = this.ph.badge_counter
              .subscribe(result => {
                  this.badge = result;
              });
          this.tabBarElement = document.querySelector('.tabbar');
          platform.ready().then(() => {
              keyboard.onKeyboardShow().subscribe(() => {
                  if (this.tabBarElement != null) {
                      this.tabBarElement.style.display = 'none';
                  }
                  console.log("Keyboard open");
              });

              keyboard.onKeyboardHide().subscribe(() => {
                  if (this.tabBarElement != null) {
                      this.tabBarElement.style.display = 'flex';
                  }
                  console.log("Keyboard close");
              });
          });

      }); 
  }
  
  ionViewWillEnter() {
      
  }
  changeTab(name) {
      console.log(name);
      console.log(this.tabRef.getSelected());
      /*
      if (name == "Inicio") {
          this.tabRef.select(0);
      }
      */
  }
  tabChanged(ev) {
      console.log("remove tabs");
      if (ev.length() > 1) {
          ev.popToRoot();
      }
      
  }
}`
```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
` Cordova CLI: 6.5.0
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installe
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.9.4
Xcode version: Not installed`
```

**Comment by jgw96** [comment] 2017-05-30 14:40
Hello! Thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11694.

**Closed by jgw96** 2017-05-30 14:40 UTC
