### ISSUE TITLE
bug: ion-img not showing on mobile phone

### ISSUE THREAD

**Issue by alainbelez** [ionic-team/ionic#18926] opened 2019-07-28 08:08 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

when there's a two ion-toolbar, the first ion-img inside a ion-card doesn't show. (this is only happening on a sidemenu template)

**Expected behavior:**

it should still show the image

**Steps to reproduce:**

* create new ionic project (sidemenu) with capacitor
* copy code below to home.page.html
* build and deploy to mobile phone (Android. not tested on iOS)

**Related code:**

```
//home.page.html
<ion-header>
  <ion-toolbar>
    <ion-title>
      Home
    </ion-title>
  </ion-toolbar>
  <ion-toolbar *ngIf="!searchBarVisible">
    <ion-buttons slot="start">
      <ion-button (click)="showSearchBar()">
        <ion-icon slot="icon-only"
                  name="search"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-buttons slot="primary">
      <ion-button>
        <ion-icon slot="icon-only"
                  name="contact"></ion-icon>
      </ion-button>
      <ion-button>
        <ion-icon slot="icon-only"
                  name="search"></ion-icon>
      </ion-button>
      <ion-button color="secondary">
        <ion-icon slot="icon-only"
                  name="more"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
  <ion-toolbar *ngIf="searchBarVisible">
    <ion-searchbar showCancelButton="always"
                   debounce="800"
                   #searchBar
                   placeholder="Search products"
                   (ionCancel)="hideSearchBar()"></ion-searchbar>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-card class="welcome-card">
    <ion-img src="/assets/shapes.svg"></ion-img>
    <ion-card-header>
      <ion-card-subtitle>Get Started</ion-card-subtitle>
      <ion-card-title>Welcome to Ionic</ion-card-title>
    </ion-card-header>
    <ion-card-content>
      <p>Now that your app has been created, you'll want to start building out features and components. Check out some of the resources below for next
        steps.</p>
    </ion-card-content>
  </ion-card>
  <ion-card class="welcome-card">
    <ion-img src="/assets/shapes.svg"></ion-img>
    <ion-card-header>
      <ion-card-subtitle>Get Started</ion-card-subtitle>
      <ion-card-title>Welcome to Ionic</ion-card-title>
    </ion-card-header>
    <ion-card-content>
      <p>Now that your app has been created, you'll want to start building out features and components. Check out some of the resources below for next
        steps.</p>
    </ion-card-content>
  </ion-card>
  <ion-list lines="none">
    <ion-list-header>
      <ion-label>Resources</ion-label>
    </ion-list-header>
    <ion-item href="https://ionicframework.com/docs/">
      <ion-icon slot="start"
                color="medium"
                name="book"></ion-icon>
      <ion-label>Ionic Documentation</ion-label>
    </ion-item>
    <ion-item href="https://ionicframework.com/docs/building/scaffolding">
      <ion-icon slot="start"
                color="medium"
                name="build"></ion-icon>
      <ion-label>Scaffold Out Your App</ion-label>
    </ion-item>
    <ion-item href="https://ionicframework.com/docs/layout/structure">
      <ion-icon slot="start"
                color="medium"
                name="grid"></ion-icon>
      <ion-label>Change Your App Layout</ion-label>
    </ion-item>
    <ion-item href="https://ionicframework.com/docs/theming/basics">
      <ion-icon slot="start"
                color="medium"
                name="color-fill"></ion-icon>
      <ion-label>Theme Your App</ion-label>
    </ion-item>
  </ion-list>

</ion-content>

```

**Other information:**

**Ionic info:**

```
   Ionic CLI                     : 5.2.3 (C:\Users\Alain\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.6.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2019-07-29 13:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18734. If you have a repo with the code required to reproduce this issue, please post it in that thread.

Thanks!

**Closed by liamdebeasi** 2019-07-29 13:15 UTC
Labels: triage
