### ISSUE TITLE
ionic start myapp tabs  

### ISSUE THREAD

**Issue by songjinb** [ionic-team/ionic#14294] opened 2018-04-09 10:29 UTC
I can use angualr4, my ionic is ok, but i can not download. i am very confuse, can you tell me why and how?
here the wrong:

Creating directory .\myapp - done!
Doenloading and extracting tabs starter - failed!
rror: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net,js:615:25)

**Comment by brandyscarney** [comment] 2018-04-09 19:35
Closing as a duplicate of https://github.com/ionic-team/ionic-cli/issues/3073

Please post any comments on that issue. Thanks!

**Closed by brandyscarney** 2018-04-09 19:35 UTC
Labels: triage
