### ISSUE TITLE
bug: searchbar not aligned

### ISSUE THREAD

**Issue by KyDenZ** [ionic-team/ionic#20244] opened 2020-01-20 13:41 UTC
# Bug Report

**Ionic version:**
[x] **4.11.8**

**Current behavior:**
I created a modal with a search bar in the header.
In version 4.7 the rendering corresponds well to the native, but not in since 4.10 :

![image](https://user-images.githubusercontent.com/7247673/72730719-30e80f00-3b92-11ea-97ec-f5fd7f589a79.png)

The native screen comes from the message application on IOS 13

I read the already open issue https://github.com/ionic-team/ionic/issues/19502 but there is no solution. I think there is a concern for the modals. As indicated by @rossholdway, removing the "padding-top: 1px" fix the problem.

**Expected behavior:**
The search bar aligned in the header

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-modal

Thanks

**Comment by liamdebeasi** [comment] 2020-01-21 13:42
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. This change was made to better fit the iOS spec. Please see the explanation from one of my colleagues here: https://github.com/ionic-team/ionic/issues/19502#issuecomment-537522707.

As noted in the thread (https://github.com/ionic-team/ionic/issues/19502#issuecomment-541699629) you can apply custom padding to the searchbar in order to achieve the desired effect.

**Closed by liamdebeasi** 2020-01-21 13:42 UTC
Labels: triage
