### ISSUE TITLE
bug: <ion-slides>:Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays. Error: Cannot find a differ supporting object '[object Object]' of type 'object'.

### ISSUE THREAD

**Issue by anysunflower** [ionic-team/ionic#19999] opened 2019-11-26 01:57 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

When I use **slides** as @Input name of the ```in-slides``` in component,
meet with the error
![2019-11-26 09-52-19 的屏幕截图](https://user-images.githubusercontent.com/40011822/69592940-84c2f580-1032-11ea-82eb-95b10325597b.png)
When I changed te @Input parameter name, the error dispeared

**Related code:**
Here is my code:

```
<ion-slides 
#slides (ionSlideWillChange)="onSlideChangeStart($event)" pager="true">
        <ion-slide *ngFor="let slide of slides">
            <img src="{{slide.mobile_image}}"  class="slide-image" />
        </ion-slide>
</ion-slides>

```
```
export class HomeBannerComponent {
  @Input() slides:SliderItem[];
  constructor() { }
  ngOnInit() {
  }
  onSlideChangeStart($event){
  }
}
```

I think it might be a bug, or it would be appreciated that the error info could be more specific

**Comment by liamdebeasi** [comment] 2019-11-26 13:57
It looks like you have an element reference named `slides` and an input reference also named `slides`, so there is likely a naming conflict there. Resolving that conflict should fix the issue. I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2019-11-26 13:57 UTC
Labels: triage
