### ISSUE TITLE
bug: Page does not resize when keyboard is dismissed...

### ISSUE THREAD

**Issue by cmeuser** [ionic-team/ionic#19088] opened 2019-08-13 21:29 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Android Only:
In situations where the keyboard is dismissed, and a loading controller is displayed, the page does not resize until the loading controller is dismissed.

**Expected behavior:**

The page should resize as the keyboard is dismissed or resize immediately as the keyboard is dismissed.

**Steps to reproduce:**

Example app:
https://github.com/cmeuser/LoadingController

Steps to reproduce:
1. launch app
2. touch input field
- keyboard appears
3. touch button 
- loading controller appears, keyboard dismisses but page does not resize leaving a blank space on the page where the keyboard was until the loading controller is dismissed.

**Related code:**

There's nothing special about the code, present a loading controller after the keyboard is presented.

```
insert short code snippets here
```

**Other information:**

Observed in every location where the keyboard is displayed and a loading controller is presented, but consistent in tab pages.

**Ionic info:**

```
insert the output from ionic info here
```
Ionic:

   Ionic CLI                     : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.2 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/meusercx/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.10.3
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

**Comment by kerosin** [comment] 2019-08-14 04:15
https://github.com/ionic-team/ionic/issues/19065

**Comment by liamdebeasi** [comment] 2019-08-15 13:26
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

**Closed by liamdebeasi** 2019-08-15 13:26 UTC
Labels: triage
