### ISSUE TITLE
[Ionic v4] ion-datetime not binding data using ngModel 

### ISSUE THREAD

**Issue by lance-parcero** [ionic-team/ionic#14988] opened 2018-08-02 10:01 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
 ngModel Binding in <ion-datetime [( ngModel)]="data"> is undefined

**Expected behavior:**
Bind to "data" variable

**Steps to reproduce:**
ionic serve
Pick a date
Press button "Test"
Check Console Logs 

**Related code:**

**app.html**
```
<ion-datetime [(ngModel)]="data"></ion-datetime>
<ion-button (click)="print()">Test</ion-button>
```
**app.ts**
```

public data:any
print() {
    console.log(this.data);
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (C:\Users\lance.parcero\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.0
```

**Comment by peterpeterparker** [comment] 2018-08-02 10:14
Did you import `FormsModule` in your corresponding page/component module?

If no, might be your solution

**Comment by brandyscarney** [comment] 2018-08-02 14:48
Thank you for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/14755 but please let me know if I am wrong. 🙂

**Closed by brandyscarney** 2018-08-02 14:48 UTC
Labels: triage
