### ISSUE TITLE
[Ionic V4.0.0-beta.12] [ion-item-sliding] Item Option Sliding not working in RTL

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic#15883] opened 2018-10-07 06:47 UTC
# Bug Report

Sliding of item-options is not working on RTL (with proper dir='rtl' on html tag)

**Ionic Info**
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.4
   @angular-devkit/schematics : 0.8.4
   @angular/cli               : 6.2.4
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v10.1.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra

**Describe the Bug**
Not able to swipe item towards right in rtl mode.
We can only slide it like ltr (towards left) and the options are not being visible.

**Expected Behavior**
Item sliding options should be working on both ltr and rtl

**Comment by samirebrahim** [comment] 2018-10-07 06:52
This is also happened with me 
+1

**Comment by touch2hussain** [comment] 2018-10-07 07:50
Same here, on V4-beta-12

**Comment by MOOCSK** [comment] 2018-11-05 09:00
This is also happening with me in V4-beta-15

**Comment by abennouna** [comment] 2018-12-04 09:37
Same issue described in https://github.com/ionic-team/ionic/issues/14328

**Comment by paulstelzer** [comment] 2018-12-07 10:20
closed as duplicate of #14328

**Closed by paulstelzer** 2018-12-07 10:20 UTC
Labels: triage
