### ISSUE TITLE
Child tab not running lifecycle hooks when navigating outside of parent tabs

### ISSUE THREAD

**Issue by RafaelLiendo** [ionic-team/ionic#13185] opened 2017-10-19 03:09 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Lifecycle hooks are not called when navigating outside of a Tab nor when popping back to it.
To make it work I had to place my code in the parent tabs.

**Expected behavior:**
Navigating to Tabs also fires lifecycle hooks in child tabs.

**Steps to reproduce:**

In the sample below I created a TabsPage with a child TabPage, 
then I navigated to another page outside of tabs
```typescript
this.appCtrl.getRootNav().push(ListPage);
```
notice that ionViewWillLeave and ionViewDidLeave were not called
and when I popped back ionViewWillEnter and ionViewDidEnter were also not fired

**Related code:**

[A sample application via GitHub: https://github.com/RafaelLiendo/ionic-lifecycle-hooks.git](https://github.com/RafaelLiendo/ionic-lifecycle-hooks.git)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\___\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

local packages:

    @ionic/app-scripts : 3.0.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment] 2017-10-19 11:19
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #9624. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-10-19 11:19 UTC
