### ISSUE TITLE
Geolocation taking too much time to get position

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/ionic#12090] opened 2017-06-19 10:32 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When I try to get my current position, the device just takes a really long time (2-3 minutes) to get it, while my browser does it perfectly. Also, native geolocation works good with other apps at my phone, so it's not a device issue, but software's.

**Expected behavior:**
Should get the current position really quick, as it does with other apps.

**Steps to reproduce:**
It stops for so long time, at this particular line:

`this.geolocation.getCurrentPosition().then((position) => {`
-->

**Related code:**

```
insert any relevant code here
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.1
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 4.2.0

```

**Comment by AmitMY** [comment] 2017-06-19 11:51
This issue is not in ionic. it might be ionic-angular, or the plugin itself.

**Comment by Zerokk** [comment] 2017-06-19 11:52
Some more info: Xiaomi Mi5s is being so special-ish. This code just doesn't work in it, but it does in Samsung S5. Navigator GPS geolocation doesn't work well in Xiaomi either, but it does work perfect in Google Maps. 

So... must be this a problem with MIUI? In that case, this problem is critical, since it affects all Ionic developers with this platform.

**Comment by AmitMY** [comment] 2017-06-19 11:55
Again, this is not an issue with ionic and as such here is not the place for it.
You can open it in https://github.com/driftyco/ionic-native, but there is a low chance it is an issue with that either. Probably the plugin itself - https://github.com/apache/cordova-plugin-geolocation

**Comment by Zerokk** [comment] 2017-06-19 12:21
@AmitMY Already posted it in the ionic-native place, let's see if somebody finds out what's going on.

**Comment by jgw96** [comment] 2017-06-19 14:35
Hello all. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic-native/issues/1703

**Closed by jgw96** 2017-06-19 14:35 UTC

**Comment by ansarikhurshid786** [comment] 2018-06-27 07:59
Please check this issue: https://github.com/ionic-team/ionic-native/issues/2571
