### ISSUE TITLE
bug: action sheet button handler triggered twice

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic#21503] opened 2020-06-11 13:08 UTC
# Bug Report
Since ionic 5.2.0 the action sheet button handler is triggered twice (I just tested action sheet, maybe the same problem happens with other overlay buttons as well, e.g. ion-alert)

**Ionic version:**

[x] **5.2.0**

**Current behavior:**
Action sheet button handler triggered twice

**Expected behavior:**
Action sheet button handler triggered only once

**Related code:**

```
public async presentHandleAttachmentActionSheet(): Promise<void> {
    const actionSheetOptions: ActionSheetOptions = {
      buttons: [
        {
          text: this.translationService.translate('action.delete'),
          role: 'destructive',
          handler: () => {
            console.log('delete clicked');
          }
        },
        {
          text: this.translationService.translate('action.show'),
          handler: () => {
            console.log('open clicked');
          }
        },
        {
          text: 'cancel'
          role: 'cancel'
        }
      ]
    };

    const actionSheet = await this.actionSheetController.create(actionSheetOptions);
    await actionSheet.present();
  }
```

Console log is triggered twice in this example on click on one of the buttons

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/pascalgraf/.nvm/versions/node/v12.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.4.1, (and 26 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.2.9

System:

   Android SDK Tools : 26.1.1 (/Users/pascalgraf/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.11.1 (/Users/pascalgraf/.nvm/versions/node/v12.11.1/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c
```

**Comment by Spinnenzunge** [comment] 2020-06-11 14:03
Here is a repo for reproduction https://github.com/Spinnenzunge/action-sheet-button-bug

**Comment by liamdebeasi** [comment] 2020-06-11 15:14
Thanks for the follow up. I am unable to reproduce the issue you are reporting. Can you provide some steps to reproduce?

**Comment by rdlabo** [comment] 2020-06-11 15:32
I confirmed this problem. This seems ios mode only.
![スクリーンショット 2020-06-12 0 32 00](https://user-images.githubusercontent.com/9690024/84406193-295dfb00-ac44-11ea-869e-7f0af8ad99f5.png)

Thanks.

**Comment by liamdebeasi** [comment] 2020-06-11 15:37
I was able to reproduce this behavior as well. It looks like https://github.com/ionic-team/ionic/issues/21499 and this issue are caused by the same underlying issue.

It looks like Chrome dispatches a click event (even when doing the haptic gesture) whereas Safari does not. 

This appears to be a browser issue, but I will see if there is a fix we can apply in Ionic Framework.

**Comment by rdlabo** [comment] 2020-06-11 15:40
Thank you for confirmation.
Is true! I also confirmed that it works fine on Safari and Capacitor iOS: https://github.com/ionic-team/ionic/issues/21499

**Comment by liamdebeasi** [comment] 2020-06-11 16:25
Can you try the following dev build and let me know if it resolves the issue?

`5.3.0-dev.202006111615.b37c158`

**Comment by rdlabo** [comment] 2020-06-12 01:38
I confirmed fix of double click at action-sheet👍

**Comment by aces-tm** [comment] 2020-06-12 11:42
@liamdebeasi To confirm that this is happening on alert. Also when I click on ok button on alert and if there is a button under it it will trigger that action as well.

**Comment by kuzinkovdmitry** [comment] 2020-06-12 12:39
When this issue will be fixes?
Because i still have it in my project

**Comment by aces-tm** [comment] 2020-06-12 13:57
@kuzinkovdmitry If it is critical for you to release your app use 5.1.1 and everything will work fine.

**Comment by liamdebeasi** [comment] 2020-06-12 13:59
Glad to hear the bug is resolved! I get this merged soon. To be clear, this bug should not affect apps running in a production environment.

The bug only appears when running in iOS mode in Google Chrome. In other words, if your app runs in iOS mode on an iOS device, you will not have this issue.

**Comment by liamdebeasi** [comment] 2020-06-12 14:36
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21506, and a fix will be available in the next release of Ionic Framework.

**Closed by liamdebeasi** 2020-06-12 14:36 UTC
Labels: triage

**Comment by aces-tm** [comment] 2020-06-16 18:26
@liamdebeasi FYI I see this issue running ionic/angular 5.1.1 in production
