### ISSUE TITLE
bug: Multiple routes strange behavior with the DOM

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic#21372] opened 2020-05-25 21:55 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

I'm trying to have multiple routes, but I'm getting strange behaviours with the DOM, sometimes the tabbar button stop displaying the ripple effect, sometimes it does not even work, I cannot even change the tabs! 

Tried some help in the forum but no success:
https://forum.ionicframework.com/t/tabs-does-not-load-pages/190009

**Expected behavior:**

Doesn't break the DOM with multiple routes.

**Steps to reproduce:**

https://imgur.com/a/ey8i5eh

**Related code:**

https://github.com/conde2/tab_bug

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/home/joao/Documentos/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.2.0 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.6
```

**Comment by liamdebeasi** [comment] 2020-05-26 13:20
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The issue is that you are using a `router-outlet` instead of `ion-router-outlet` here: https://github.com/conde2/tab_bug/blob/master/src/app/index/index.page.html#L2. `ion-router-outlet` is required in Ionic apps.

Using `ion-router-outlet` instead resolved the issue on my end.

**Closed by liamdebeasi** 2020-05-26 13:20 UTC
Labels: triage

**Comment by conde2** [comment] 2020-05-26 13:51
Thank you, sorry for the wrong report.
