### ISSUE TITLE
large http get response crashing the application

### ISSUE THREAD

**Issue by danger1** [ionic-team/ionic#13482] opened 2017-11-22 13:02 UTC
**Ionic version:**  (check one with "x")
 [ x] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

I am developing a cordova application with ionic 2.I request the API, the thing causing the problem is response size of the API.The size of response is 9,3MB. After I call the requestCall()function, it is not print my output to the console like codes below.and the value of this.case never happen "success".After some time(0-1 min after call) the application is closing.Not giving any error or something,it is simply closing.Btw in chrome://inspect/#devices I can see the API request is working and getting the datas.The screenshot of request is [here](https://i.stack.imgur.com/dZOTs.png).
By the way, if I reduce the data size to 6MB everything is working fine.
 Could you please help me to solve this problem?
This is my API service,I request getAll() function from my page.
```

@Injectable()
export class ApiService {

constructor(private http: Http) { 
  } 
 getAll(){
     return this.http.get(`${API_URL+'/List?accId='+ ACC_ID+'&appCode='+APP_CODE}`)
            .map((res:Response)=>{ 
              return res.json();
            })
            .catch((error:any)=>Observable.throw(error)||'server error');
    }
}
```
Within this page, I call requestServer function by clicking the button.

```
import { ApiService } from '../../services/api/api-service';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
 case:any="";

  constructor(private apiService:ApiService) {
   }
 requestServer(){
    this.case="pending";
      this.apiService. getAll().subscribe(res=>{
          console.log("viiiii");
          this.case="success";

         });
 }
```

btw, I opened same issue [here](https://stackoverflow.com/questions/47434138/ionic-large-http-get-response-causing-shut-down-the-application)

**Comment by graphefruit** [comment] 2017-11-22 14:28
That should be a "standard" issue. I already had this issue on Angular 1 applications.

The problem is that nearly 10 MB need to be parsed as a JSON-String and iOS / Android limits exceed than.

The problem is not downloading the JSON its parsing the json.

**Comment by danger1** [comment] 2017-11-22 17:16
Thank you, @graphefruit Then the only way is reducing the data.

**Comment by graphefruit** [comment] 2017-11-23 09:33
Maybe you can crawl through the string with regex, or index of if you have unique namings and split the string.

Reducing the data would be the best step, but if this is not possible you need to cut the the data in smaller pieces

**Comment by kensodemann** [comment] 2017-11-27 12:25
Hello! Thank you for opening an issue with us!

I am closing this as it does not appear to be an issue with the Ionic Framework.

Thank you for using Ionic

**Closed by kensodemann** 2017-11-27 12:25 UTC
