### ISSUE TITLE
UI breaks when OSKB displays on iOS 12 - Ionic 4 Beta 7, Capacitor 1 beta-8

### ISSUE THREAD

**Issue by nikmartin** [ionic-team/ionic#15824] opened 2018-10-01 18:47 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
ionic (Ionic CLI)          : 4.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

System:

   NodeJS : v8.11.4 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**
When the on screen keyboard is displayed and hidden (from a footer input), it causes the UI to be scrolled up, the user interface is 'shifted' up by the width of the keyboard. When the keyboard then disappears, all the UI input is still shifted up by the width of the keyboard. This means all clicks in the UI are too high (ie inputs, etc). Also, when an input is in the content area, the keyboard will hide the input instead of scrolling it as it should.

**Steps to Reproduce**
1. Clone: https://github.com/grabitlogistics/ios12kbd
2. run npm i && ng build && npx cap add ios && npx cap copy ios && npx cap open ios
3. Run the project on an ios 12 device
4. Click in an upper input to display the keyboard, then click outside to hide the keyboard and lose focus.
5. Click on an input in the footer, making the keyboard appear and shift the inputs up. Click outside the input to hide the keyboard.
6. All touch events have now been shifted up by the height of the keyboard, so to click in the input in the content OR the footer, you must click a few inches above the respective input (about the height of the keyboard)

**Related Code**
sample test case: https://github.com/grabitlogistics/ios12kbd

**Additional Context**
This ONLY happens on iOS 12, on a hardware device OR emulator. To test in an emulator, you must use the emulated keyboard in order to cause the UI to shift up.

**Comment by Monierv** [comment] 2018-10-02 09:42
Got the same issue :(

**Comment by nicdichiara** [comment] 2018-10-02 14:11
@Monierv We were advised that this is the same as:
https://github.com/ionic-team/capacitor/issues/814

Which is suspected to stem from an iOS 12 SDK issue:
http://www.openradar.me/44655885

We are going to test today, but there's talk that building with Xcode 9 fixes it until an actual fix is released. Hope the links help.

**Comment by booleanbetrayal** [comment] 2018-10-02 14:36
Confirming that building with XCode9 fixes it @nicdichiara

**Comment by Monierv** [comment] 2018-10-03 11:32
Is your _<ion-input>_ inside an _<ion-slide>_ or something ?
This problem disappears if I put my _<ion-input>_ outside of my _<ion-slide>_

**Comment by luke-rogers** [comment] 2018-10-10 18:41
Any progress on this one?
I can also confirm that this is not an issue with Xcode 9 even if using iOS 12.

**Comment by hghammoud** [comment] 2018-10-10 19:08
I did some testing on multiple ios/emulators
XCode 10.0

iPhone 8 Plus iOS 11 -> no view shits everything is ok
iPhone 8 Plus iOS 12 -> no view shits everything is ok
IPhone X iOS 11.3 -> view shits but clicks are in place ()
IPhone X ans XS iOS 12 -> view shits and clicks are not accurate (the click action triggers lower the the touch point - same amount of view shit)

it seems related seems related to the extra track pad.
![image](https://user-images.githubusercontent.com/8034427/46759715-5a986200-ccd0-11e8-98cf-84f004e5b16d.png)

**Comment by paulstelzer** [comment] 2018-12-07 10:10
If it's not fixed since then, I think this problem is more related to https://github.com/ionic-team/cordova-plugin-ionic-keyboard - So I close this issue here

**Closed by paulstelzer** 2018-12-07 10:10 UTC
Labels: triage

**Comment by nikmartin** [comment] 2018-12-07 19:10
The issue also exists in capacitor, so I don't think it's specific to that issue.

**Comment by paulstelzer** [comment] 2018-12-07 19:15
Capacitor is also using a plugin to display the keyboard. @ionic/core has no functionality to show the keyboard, so it's not related to Ionic itself, that I want to say :)

**Comment by jcesarmobile** [comment] 2018-12-07 19:58
As it was commented by @nicdichiara, this is a bug in the iOS 12 SDK (Xcode 10).
The issue is already reported on 
https://github.com/ionic-team/capacitor/issues/814

There are a few workarounds mentioned
