### ISSUE TITLE
hideWhen="landscape" not working on the browser & Android 

### ISSUE THREAD

**Issue by hamzahamidi** [ionic-team/ionic#11767] opened 2017-05-24 08:14 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[x ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

`<ion-fab hideWhen="landscape" bottom right>
    <button ion-fab>
             <ion-icon name="add"></ion-icon>
        </button>
</ion-fab>`
the button still shows in landscape orientation
**Expected behavior:**

The button should be hidden in landscape orientation
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by jgw96** [comment] 2017-05-24 17:53
Hello, thanks for using Ionic. Unfortunately I cannot reproduce this issue on my devices, could you share a repo we could use to reproduce this?

**Comment by hamzahamidi** [comment] 2017-05-24 19:00
After several tests, I noticed that this bug is on Ionic 2.3.0. When I reverted to Ionic 2.0.1, it works perfectly.

**Comment by hamzahamidi** [comment] 2017-05-24 19:19
It works on Ionic 2.0.1 & 2.1.0 but fails to work on Ionic 2.2.0 & 2.3.0
{
    "name": "ionic-hello-world",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "2.4.8",
        "@angular/compiler": "2.4.8",
        "@angular/compiler-cli": "2.4.8",
        "@angular/core": "2.4.8",
        "@angular/forms": "2.4.8",
        "@angular/http": "2.4.8",
        "@angular/platform-browser": "2.4.8",
        "@angular/platform-browser-dynamic": "2.4.8",
        "@angular/platform-server": "2.4.8",
        "@ionic-native/core": "^3.4.4",
        "@ionic-native/splash-screen": "^3.7.0",
        "@ionic-native/status-bar": "^3.7.0",
        "@ionic/storage": "2.0.0",
        "highcharts": "^5.0.10",
        "intl": "^1.2.5",
        "ionic-angular": "2.3.0",
        "ionic-native": "2.4.1",
        "ionicons": "3.0.0",
        "moment": "^2.18.1",
        "rxjs": "5.0.1",
        "sw-toolbox": "3.4.0",
        "zone.js": "0.7.2"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.1.4",
        "typescript": "2.0.9"
    },
    "cordovaPlugins": [
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "cordova-plugin-device",
        "cordova-plugin-splashscreen",
        "ionic-plugin-keyboard"
    ],
    "cordovaPlatforms": [],
    "description": "Tgestionv2: An Ionic project",
    "config": {
        "ionic_copy": "./config/copy.config.js"
    }
}

**Comment by hamzahamidi** [comment] 2017-05-26 23:38
I tested on Ionic 3.3.0 and it works. So the only versions where it doesn't work are 2.2.0 & 2.3.0

**Comment by jgw96** [comment] 2017-06-02 15:28
Awesome, thanks for testing! Since we do not support 2.2.0 or 2.3.0 any more (we only support the latest version), and it works in the latest version of ionic, I am going to close this issue for now.

**Closed by jgw96** 2017-06-02 15:28 UTC
Labels: needs info, v2
