### ISSUE TITLE
ion-content does not resize when header or footer or not direct sibblings

### ISSUE THREAD

**Issue by Remco75** [ionic-team/ionic#12120] opened 2017-06-21 09:05 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I Have a footer I want to appear on all pages, with some navigation and a custom component in it. To achieve this I placed it in the app.html, below the ion-nav. In my page templates I place a ion-content element. 

Problem: the content height is not adjusted to correct for the footer. (I looked in the content-component code, and it expects them to be sibblings).

**Expected behavior:**
I would expect the content-component to resize even if header or footer are NOT sibblings

**Steps to reproduce:**
Create a app with uses ion-nav.
 in app.html
<ion-nav [root]=rootPage>
<ion-footer>
  <ion-toolbar>
   My static footer content
  </ion-toolbar>
</ion-footer>

in somepage.html 
<ion-header>
    <ion-title>
      My App
    </ion-title>
</ion-header>

<ion-content >
  My content
</ion-content>

For Ionic issues - http://plnkr.co/edit/cpeRJs?p=preview
-->

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment] 2017-06-21 09:49
It does it with tabs, but correct, not if the footer is not a sibling. However, can you try to put your `<ion-nav` inside `ion-content`? I know it is a bit weird, but it might solve it for you.

**Comment by Remco75** [comment] 2017-06-21 10:00
@AmitMY thanx for the reply! 
I think your solution would create new problems: I want the footer NOT to move during page transitions, and always be visible.
Putting the whole <ion-nav inside the <ion-content would mean you can also scroll the footer right?

**Comment by AmitMY** [comment] 2017-06-21 10:18
ahm no, it would mean that the footer will stay in place, and the navigation will be inside a content that has `margin-bottom: footer-height` (automatically). I think it will work, I have experimented with several contents in the past, pretty delicate stuff.

so try this out:

```
<ion-content>
  <ion-nav [root]=rootPage></ion-nav>
</ion-content>
<ion-footer>
  YOUR FOOTER
</ion-footer>
```

**Comment by Remco75** [comment] 2017-06-21 10:20
Hmm Ii will start experimenting. Hard part is that i do not want the Whole page to scroll. There is a header in the page as well. I think this way the whole nav will be scrollable.

**Comment by Remco75** [comment] 2017-06-21 10:29
Cool, I was working on something similar already, thnx! Would be nice if ion-content would be able to account for scenarios like this though.

**Comment by Remco75** [comment] 2017-06-21 10:51
@AmitMY your first solution seems to work for now, only down side is now i have nested ion-content elements. So double scrollbars show up-> will leave it for now to see what the app does on true devices. 

Other solution works as well, with some workaroud, but it feels like adding to much overhead.
Still think this is a valid 'bug' , or maybe a feature request if this line of UI is not supported yet?

**Comment by AmitMY** [comment] 2017-06-21 11:12
So technically second solution adds less overhead, because first solution does the same, and much much more.
It is not a bug, as this was not intended to work like this, however, it may be a feature request, although I doubt it will get in.

@jgw96 can rule on that

**Comment by Remco75** [comment] 2017-06-21 11:18
ok, But i think it makes sence as a feature request: atm you cannot create a app with a static footer like described in this issue. (and is is a frequently used model, look at the spotify app for instance)

thnx for all the swift responses and help!

**Comment by davec21** [comment] 2017-06-21 13:36
Not sure if this has anything to do with it.. but make sure you wrap your footer content in an <ion-toolbar> this will fix height issues.

**Comment by jgw96** [comment] 2017-06-21 15:57
Hello everyone! I am not going to consider this as a feature request at the moment as in this case `ion-footer` is working like it should and this use case seems to be very custom to your app. `ion-footer` should always be a sibling to `ion-content` as that is how the content figures out how to size its scrollable area. In this case it sounds like to me that if you want a static "footer" on each page of your app that you would be better served by using an `ion-toolbar` in your `app.html` and using `position: fixed` and `bottom: 0` to make it stick to the bottom. You will probably need some custom css to size your content correctly too.

**Closed by jgw96** 2017-06-21 15:57 UTC

**Comment by Remco75** [comment] 2017-06-21 18:38
Yeah I know how to fix this, But still I think it is a valid use-case to want a 'static footer' (for lack of a better word ;-)

And thats something that's not very easy to do: you have to re-build the ion-content in order to get the same flexibility: resizing on DOM height changes.

So i think it would be a nice addition to the ion-content component to be able to tell it to what element it should 'listen'. 

But then again, who am I ? ;-)

thnx again guys!
remco
