### ISSUE TITLE
`ionViewDidEnter` does not fire when navigating back to tabbed page

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#17473] opened 2019-02-12 16:28 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When I go navigate from a tabbed page to another page and then use the ion-back-button from there, the tabbed page's `ionViewDidEnter` method is not triggered.

Video showing the bug live on a different code base: 
[![Video showing the bug live on a different code base:](https://img.youtube.com/vi/hCnbvcsm-Yg/sddefault.jpg)](https://youtu.be/hCnbvcsm-Yg)
**Expected behavior:**

When I click on the back button the `ionViewDidEnter` method of the tabbed page fires since it has been entered again. (Consistent with non tabbed pages.)

**Steps to reproduce:**

Issue demo repo: https://github.com/Eraldo/ionic4-tabs-back-issue
1. Clone the repo
2. Make sure the latest ionic version is installed.
3. Run `ionic serve`.
4. Close the alert which shows on page enter.
5. Click on on the ion button in the content section of the page (tab1 page).
5. On the opened page ("Some" page) click on the `back` button.
6. Verify that there is no alert showing up anymore.

**Related code:**

https://github.com/Eraldo/ionic4-tabs-back-issue

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

System:

   NodeJS : v11.0.0 (/usr/local/Cellar/node/11.0.0/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2019-02-14 15:14
Hi @Eraldo,

Thanks for opening an issue with. I'm not seeing the content you're describing in your steps to reproduce with the repo you provided. It looks like the base tab starter app. Can you double check to make sure you included the link to the correct repo?

Thanks!

**Comment by Eraldo** [comment] 2019-02-14 18:18
Oh! I forgot to commit before pushing and I already deleted the repo locally. What a pity!
Well I will recreate it today. Thanks for letting me know.

**Comment by Eraldo** [comment] 2019-02-14 18:28
Update: I pushed that the repo: https://github.com/Eraldo/ionic4-tabs-back-issue
Can you please retry. :)

**Comment by liamdebeasi** [comment] 2019-02-14 20:55
Thanks @Eraldo,

I was able to reproduce the issue using the code you provided. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16834. We've added that issue to our backlog and hope to have it resolved soon. 🙂 

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-14 20:55 UTC
Labels: triage
