### ISSUE TITLE
[beta 11] Side ion-menu doesn't show on IOS mode

### ISSUE THREAD

**Issue by marticrespi** [ionic-team/ionic#15733] opened 2018-09-24 07:51 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (C:\Users\XXX\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6
```

**Describe the Bug**
The menu doesn't appear in IOS mode. If you click on the ion-menu-toggle doesn't appear, and If I try to show it through code, like this `this.menuCtrl.open();` either.  In MD mode works both ways.

**Steps to Reproduce**
1. Put the above code after your login, and nothing happens. Or try to click on the ion-menu-toggle. It try to add "show-menu" class but it disappears immediately.

**Related Code**
````
ion-menu contentId="nav" swipeGesture="false">
  <ion-header>
    <ion-item no-lines>
      <ion-thumbnail slot="start">
        <img src="{{currentUser != null && currentUser.avatarUrl != undefined && currentUser.avatarUrl != '' ? currentUser.avatarUrl : 'assets/estshan/profile.png'}}">
      </ion-thumbnail>
      <h2 *ngIf="currentUser != null">{{currentUser?.completeName ? currentUser.completeName : (currentUser.name + '
        ' + currentUser.firstSurname +( currentUser.secondSurname
        ? (' ' + currentUser.secondSurname) : '')) }}</h2>
    </ion-item>
    <div style="margin-left:20px;">
      <p *ngIf="currentUser != null">{{currentUser.email}}</p>
    </div>
  </ion-header>

  <ion-content class="outer-content" no-border-top>

    <ion-list lines="full">
      <ion-list-header>
        Explorar
      </ion-list-header>
      <ion-item button menuClose *ngFor="let p of tabPages" (click)="openPage(p)">
        <ion-icon slot="start" name="{{p.icon}}"></ion-icon>
        <ion-label>{{p.title}}</ion-label>
      </ion-item>
    </ion-list>
  </ion-content>

  <ion-footer>
    <ion-grid>
        <ion-row>
            <ion-col offset="8">
            <ion-item button (click)="logout()">
                <ion-label color="primary" fill="clear" class="logout">
                    SALIR
                    <ion-icon slot="end" name="log-out"></ion-icon>
                </ion-label>
              </ion-item>          
        </ion-col>
      </ion-row>
    </ion-grid>
  </ion-footer>
</ion-menu>

<ion-nav id="nav"></ion-nav>
<ion-app>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
````

**Expected Behavior**
Obviously, that it shows in both ways.

**Comment by manucorporat** [comment] 2018-09-25 15:05
The sample code looks wrong, you can't use ion-nav and router-outlet at the same time, they both take care of navigation.

In addition, the menu should be inside ion-app, nothing should be placed outside `ion-app`. Closing, since there is not a clear issue to reproduce.

**Closed by manucorporat** 2018-09-25 15:05 UTC

**Comment by marticrespi** [comment] 2018-09-26 05:49
I think something are wrong. With this configuration works well in MD, but not in IOS. If the placement of the items are wrong, it should not work in any mode. I have fixed it, if helps somebody here is how I have it working in both modes.

````
<ion-app>
    <ion-menu contentId="nav" swipeGesture="false">
        <ion-header>
          <ion-item no-lines>
            <ion-thumbnail slot="start">
              <img src="{{currentUser != null && currentUser.avatarUrl != undefined && currentUser.avatarUrl != '' ? currentUser.avatarUrl : 'assets/estshan/profile.png'}}">
            </ion-thumbnail>
            <h2 *ngIf="currentUser != null">{{currentUser?.completeName ? currentUser.completeName : (currentUser.name + '
              ' + currentUser.firstSurname +( currentUser.secondSurname
              ? (' ' + currentUser.secondSurname) : '')) }}</h2>
          </ion-item>
          <div style="margin-left:20px;">
            <p *ngIf="currentUser != null">{{currentUser.email}}</p>
          </div>
        </ion-header>
      
        <ion-content class="outer-content" no-border-top>
      
          <ion-list lines="full">
            <ion-list-header>
              Explorar
            </ion-list-header>
            <ion-item button menuClose *ngFor="let p of tabPages" (click)="openPage(p)">
              <ion-icon slot="start" name="{{p.icon}}"></ion-icon>
              <ion-label>{{p.title}}</ion-label>
            </ion-item>
          </ion-list>
        </ion-content>
      
        <ion-footer>
          <ion-grid>
            <ion-row>
              <ion-col offset="8">
                <ion-item button (click)="logout()">
                  <ion-label color="primary" fill="clear" class="logout">
                    SALIR
                    <ion-icon slot="end" name="log-out"></ion-icon>
                  </ion-label>
                </ion-item>
              </ion-col>
            </ion-row>
          </ion-grid>
        </ion-footer>
      </ion-menu>
  <ion-nav id="nav">
      <ion-router-outlet></ion-router-outlet>
  </ion-nav>
</ion-app>
````
