### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by divinetouch** [ionic-team/ionic#20095] opened 2019-12-16 17:53 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Regardless of whether I choose date-format `DDD or DDDD`, the day format that is shown in the picker is always in `D`  format `1 to 31`

**Expected behavior:**

According to the doc (https://ionicframework.com/docs/api/datetime) Day of the week `Mon to Sun` or `Monday to Sunday` should be shown instead of the `1 to 31` as it's currently shown.

**Steps to reproduce:**

https://codepen.io/divinetouch/pen/eYmBvex?editors=1010

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.7

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.3.0 (/usr/local/Cellar/node/13.3.0/bin/node)
   npm    : 6.13.2
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2019-12-17 14:32
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16487. Please note that this issue has been merged with the main datetime issue tracker: https://github.com/ionic-team/ionic/issues/16630

**Closed by liamdebeasi** 2019-12-17 14:32 UTC
Labels: triage
