### ISSUE TITLE
CanDeactivate guard does not prevent swiping back on iOS

### ISSUE THREAD

**Issue by jkronborg** [ionic-team/ionic#17895] opened 2019-03-27 15:08 UTC
# Bug Report

**Ionic version:**
[x] **4.1.2**

**Current behavior:**
On iOS, you can swipe back from a page that has a CanDeactivate guard that should prevent navigating away from it. After swiping back, the resulting page does not take any input (e.g. button presses are ignored).

**Expected behavior:**
You should not be able to swipe back from a page where a CanDeactivate guard returns `false`.

**Steps to reproduce:**
1. Clone https://github.com/jkronborg/ionic-can-deactivate-swipe. This is the "blank" starter project, with an added page with a CanDeactivate guard that always returns `false`.
2. Run `npm install`.
3. Run `npm run start`.
4. Open the served page in Chrome, and open Chrome Developer Tools.
5. Enable the Device Toolbar, and choose an iPhone as the simulated device.
6. Reload the page so that the simulated user agent is used.
7. Click the "Go to page two" button.
8. Click-drag from the left edge towards the right, to simulate a back-swipe.
9. Observe that you could swipe back to the home page, and that you can't click the "Go to page two" button.

**Related code:**
See _Steps to reproduce_.

**Other information:**
None.

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/[redacted]/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

System:

   NodeJS : v10.11.0 (/Users/[redacted]/.nvm/versions/node/v10.11.0/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2019-03-27 16:47
Hi there,

I am going to close this as a duplicate of #17600.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-27 16:47 UTC
Labels: triage
