### ISSUE TITLE
bug: iOS page-back animation ends with "flash" of previous page (Ionic 4.11.1)

### ISSUE THREAD

**Issue by bZez** [ionic-team/ionic#19680] opened 2019-10-17 13:15 UTC
# Bug Report
Similar to https://github.com/ionic-team/ionic/issues/16988

Ionic Studio
**Ionic version:**
[x] **4.11.1**
iOS device

As in previous version, the flashing bug is here again....

![demo](https://i.ibb.co/hdBZBhD/demo.gif)

**Comment by liamdebeasi** [comment] 2019-10-17 14:16
Thanks for the issue. Is this happening in iOS mode or MD mode? The MD mode flicker was a different issue.

**Comment by liamdebeasi** [comment] 2019-10-17 14:24
Ok I think I see what the issue is. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19674.

**Closed by liamdebeasi** 2019-10-17 14:24 UTC
Labels: needs: reply
