### ISSUE TITLE
Issue with NavController and Google Maps SDK

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic#11962] opened 2017-06-07 15:30 UTC
**Ionic version:**  (check one with "x")
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report

**Current behavior:**
In the root view I have a Google Maps (JS SDK) and I have a button, when clicked it pushes to the next view. When hitting back button, it hides the map !
I've tried the same using **Modal** instead of a **NavController** and it worked (i.e shown the map).

I believe that bug appears for the simple reason is that a Google Map has a unique div id, when using a **navcontroller** and coming back to the main map view the nav appends for the second time the same map with the same id that what makes it disappear; However, on the case of the **viewController** **dismiss()** method only hides the opened modal without appending a new whole view.

**Expected behavior:**
When using a navController, pushing the view and going back to the main map page it should show the map.

**Steps to reproduce:**
Create an empty app while embedding in the root view a google map and put a button (when clicked) it pushes to the next view. Once you are on the second view, hit the back button, and BOOM the map will disappear!

```
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 6.3.0 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : browser 4.1.0 ios 4.2.1
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 
```

**Comment by jgw96** [comment] 2017-06-08 14:01
Hello, thanks for using Ionic! Would you mind creating a repo we could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-06-13 15:28
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-13 15:28 UTC
Labels: needs info, v2
