### ISSUE TITLE
bug: Angular 4.7.4 Broken in IE11

### ISSUE THREAD

**Issue by mharrisn** [ionic-team/ionic#19118] opened 2019-08-16 18:17 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
In IE 11, The blank started template does not render. The browser window is blank. There were no console errors, but it does not render. It renders correctly with the starter template content in Edge, Chrome, & Safari

**Expected behavior:**
Blank template project would render the same as other supported browsers.

**Steps to reproduce:**
```
npm install -g ionic
ionic start test-blank blank
cd test-blank
ionic serve
```

**Other information:**
I've done some lightweight testing on this and  the earliest version of Ionic Angular that I'm able to run in IE11 without issue is 4.3.2

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
```

**Comment by GuilhermeBCC** [comment] 2019-08-17 06:23
IE has been discontinued. Microsoft itself recommends not using it.

**Comment by savilaf** [comment] 2019-08-28 09:21
any update on this?

**Comment by savilaf** [comment] 2019-08-28 12:44
You need to set `"target": "es5"` in `tsconfig.json` to work in IE11.

The problem is that in Angular 8, "es2015" is by default now.

**Comment by liamdebeasi** [comment] 2020-03-11 16:40
Thanks for the issue. I am going to close this as we recently released Ionic Framework v5 which dropped support for IE11 and older versions of Edge. Moving forward, Ionic Framework v4 will only receive critical security patches.

**Closed by liamdebeasi** 2020-03-11 16:40 UTC
Labels: triage
