### ISSUE TITLE
bug: ion-title in ion-toolbar excessive padding left

### ISSUE THREAD

**Issue by carlosnewmusic** [ionic-team/ionic#18556] opened 2019-06-17 07:53 UTC
# Bug Report

**Ionic version:**
[x] **4.5**

**Current behavior:**
to past 12 to 20 the padding left in ion title, being wrong/out of square

**Expected behavior:**
that had a padding left to 12 px as in version 4.4.2

**Steps to reproduce:**
use any ion-title contained in ion-toolbar

**Photos**
behavior in ionic 4.5
![image](https://user-images.githubusercontent.com/19379457/59585366-9a75db80-90e0-11e9-858e-d8de4384509c.png)
![image](https://user-images.githubusercontent.com/19379457/59585984-158bc180-90e2-11e9-84e6-c3a4f2529d53.png)
![image](https://user-images.githubusercontent.com/19379457/59587179-f9d5ea80-90e4-11e9-90de-8ea3eb1c49fc.png)
![image](https://user-images.githubusercontent.com/19379457/59586173-8f23af80-90e2-11e9-8167-9243b91ef5d4.png)
the expected behavior or the previous version (4.4.2)
![image](https://user-images.githubusercontent.com/19379457/59586745-e8d8a980-90e3-11e9-8602-0c783a193751.png)
![image](https://user-images.githubusercontent.com/19379457/59587031-99df4400-90e4-11e9-8497-b85673615306.png)
![image](https://user-images.githubusercontent.com/19379457/59587095-c5fac500-90e4-11e9-945e-371a0376a832.png)
![image](https://user-images.githubusercontent.com/19379457/59586276-d873ff00-90e2-11e9-9268-ebb7bbb66697.png)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\Administrador\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 6 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-06-17 13:52
Hi there,

Thanks for the issue. This change was intentional. It was done to bring our components in line with the Material Design spec.

Here is an example of what you can expect with these changes (Ionic is on the left, Material Design is on the right):

![image](https://user-images.githubusercontent.com/2721089/59609321-2ee23d00-90e5-11e9-8193-e630537d1e0b.png)

Here is a link to the related changes if you are interested in seeing what else has been updated: https://github.com/ionic-team/ionic/pull/17537

I am going to close this as this is not a bug. Thanks for using Ionic! 🙂

**Closed by liamdebeasi** 2019-06-17 13:52 UTC
Labels: triage
