### ISSUE TITLE
[ionic v4] Unable to style scrollbars

### ISSUE THREAD

**Issue by IsaacHub** [ionic-team/ionic#18691] opened 2019-07-02 11:23 UTC
I'm targeting desktop browser using this framework, for any HTML projects I would add the following css globally so any scrollable container can have some nice looking scrollbar.

But in an ionic v4 project, when I add this to `global.scss` nothing happens because of its own web component's implementation. I don't want to see the same old ugly looking OS based scrollbars in ionic v4 desktop browser application.

How to achieve this?

```
::-webkit-scrollbar-track {
  background-color: rgba(0, 0, 0, 0);
  border-radius: 10px; 
}

::-webkit-scrollbar {
  width: 12px;
  background-color: transparent; 
}

::-webkit-scrollbar-thumb {
  border: 1px solid rgba(0, 0, 0, 0);
  background-clip: padding-box;
  border-radius: 3em;
  background-color: rgba(0, 124, 182, 0.69) 
}

::-webkit-scrollbar-corner {
  background-color: transparent;
}
```

**Comment by liamdebeasi** [comment] 2019-07-02 13:35
Thanks for the issue! This is a known limitation. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/17685. Please follow that thread for updates regarding this topic.

Thanks!

**Closed by liamdebeasi** 2019-07-02 13:35 UTC
Labels: triage
