### ISSUE TITLE
Pushing back to map view, shows only blank (Repo provided)

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionic#12987] opened 2017-09-26 10:21 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

**Current behavior:**
In `view 1` I have the map, when I push `view 1` to `view 2` then when I try to go from `view 2` to `view 1` by doing `.setRoot()` I get a blank view !

**Expected behavior:**
It Should show the map

**Steps to reproduce:**

Here is a BitBucket repo you may clone to reproduce the issue : 
https://Mzzika@bitbucket.org/Mzzika/testmap.git

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.8.0
    ionic (Ionic CLI) : 3.8.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v8.1.3
    npm        : 5.4.2 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by kensodemann** [comment] 2017-09-27 21:41
Hello! Thank you for opening an issue with us!

The problem is that you are opening `about` as a modal on top of `home`. When you do this, `home` still exist. When you do a `setRoot()` back to home you are creating a second 'HomePage' as the first one was never destroyed (you can verify this by running your app on an iOS device and then using Web Inspector to look at the elements (and Android device / Chrome)). So at that point you have two divs that have the id of "map" and it will probably re-draw the map in the first div it finds while you are actually looking at the second div with that id.

You will also see that this messes around with the title bar, etc.

You should use consistent navigation. So, since you open the modal with `viewCtrl.present()` you should close it by injecting the controller into the modal and calling `viewCtrl.dismiss()`.

Similar if you push a page you should pop it to close, etc.

It seems the about should have also drawn a map on creation based on your code, but I didn't look into that as that is no Ionic Framework related. For that, you may want to ask a question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/) open an issue in the ionic-native repo if it turns out to be a bug in the plugin.

Thank you for using Ionic

**Closed by kensodemann** 2017-09-27 21:41 UTC
