### ISSUE TITLE
ionic4 ion-footer can't display in ios10.3.1

### ISSUE THREAD

**Issue by yanghaomeng** [ionic-team/ionic#16328] opened 2018-11-15 07:03 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
        "@angular/common": "~6.1.1",
        "@angular/core": "~6.1.1",
        "@angular/forms": "~6.1.1",
        "@angular/http": "~6.1.1",
        "@angular/platform-browser": "~6.1.1",
        "@angular/platform-browser-dynamic": "~6.1.1",
        "@angular/router": "~6.1.1",
        "@ionic-native/app-version": "5.0.0-beta.21",
        "@ionic-native/browser-tab": "5.0.0-beta.21",
        "@ionic-native/camera": "5.0.0-beta.21",
        "@ionic-native/code-push": "5.0.0-beta.21",
        "@ionic-native/core": "5.0.0-beta.21",
        "@ionic-native/device": "5.0.0-beta.21",
        "@ionic-native/diagnostic": "5.0.0-beta.21",
        "@ionic-native/file-transfer": "5.0.0-beta.21",
        "@ionic-native/in-app-browser": "5.0.0-beta.21",
        "@ionic-native/keyboard": "5.0.0-beta.21",
        "@ionic-native/screen-orientation": "5.0.0-beta.21",
        "@ionic-native/social-sharing": "5.0.0-beta.21",
        "@ionic-native/splash-screen": "5.0.0-beta.21",
        "@ionic-native/status-bar": "5.0.0-beta.21",
        "@ionic/angular": "4.0.0-beta.13",
        "@ionic/storage": "^2.2.0",
```

**Describe the Bug**
ion-footer can't display in ios10.3.1, others display normal.

**Steps to Reproduce**
1.  run ios10.3.1
2. ion-footer can't work

**Comment by dylanvdmerwe** [comment] 2018-11-16 09:46
Please can you provide some code in order for us to reproduce this.

**Comment by bryce13950** [comment] 2018-12-05 14:59
Is this still an issue with the current beta?

**Comment by ermamud** [comment] 2018-12-24 06:21
I can confirm this still an issue with the latest ionic 4 version `4.0.0-rc.0`. 
I have an APP in PROD environment right now with some clients complaining about this since I have my login form in a footer,  all of those having iOS 10.3, can't see the footer, so they can't log in. If you like to see app working, please install the app called `Megaconecta` (https://itunes.apple.com/us/app/megaconecta/id1000791688?mt=8)

as per code example, it's just any page with content and footer. This is my current login page:
```
<ion-header></ion-header>

<ion-content padding>
    <ion-grid>
        <ion-row>
            <ion-col size="12">
                <h1 class="form-title font-30">
                    <ion-icon name="md-arrow-back" color="dark" routerLink="/" routerDirection="back"></ion-icon>
                </h1>
                <h1 class="form-title font-30">
                    <ion-text color="secondary">
                        <span>Welcome</span>
                    </ion-text>
                </h1>
            </ion-col>
        </ion-row>
    </ion-grid>
</ion-content>

<ion-footer>
    <form (ngSubmit)="submitForm()">
        <ion-grid padding>
            <ion-row>
                <ion-col size="12">
                    <ion-item>
                        <ion-icon slot="start" name="person" color="secondary"></ion-icon>
                        <ion-input type="tel" name="username" [(ngModel)]="username" required placeholder="Phone"></ion-input>
                    </ion-item>
                </ion-col>
            </ion-row>
            <ion-row>
                <ion-col size="12" class="mb-20">
                    <ion-item>
                        <ion-icon slot="start" name="unlock" color="secondary"></ion-icon>
                        <ion-input [type]="type" name="password" [(ngModel)]="password" required placeholder="Password"></ion-input>
                        <ion-icon slot="end" [name]="icon" color="medium" (click)="changeInputType()"></ion-icon>
                    </ion-item>
                </ion-col>
            </ion-row>
            <ion-row>
                <ion-col size="12">
                    <div class="mb-20">
                        <ion-button type="submit" class="no-radius" expand="block" color="secondary">
                            LOG IN
                        </ion-button>
                        <ion-button type="button" class="no-radius" fill="clear" expand="block" color="secondary" routerLink="/forgot-password" routerDirection="forward">
                            Forgot your password?
                        </ion-button>
                    </div>
                </ion-col>
            </ion-row>
        </ion-grid>
    </form>
</ion-footer>
```

Please any help as soon as possible, would be greatly appreciated.

Regards,
Ernesto

**Comment by bryce13950** [comment] 2018-12-24 14:42
I think this has to do with the calculated height. I noticed that a lot of wrapper elements were given heights of 568px when they had height 100% set on them, even though they were in a container that had a header, which should have given it a height somewhere around 520px. This then causes the footer to be pushed down just below the bottom of the screen. In my case I had a login form on the only page where I also had a footer. Activating any element on this page would then cause a manual recalculation of the height, and the footer would then appear for as long as the page was open.

**Comment by ermamud** [comment] 2018-12-24 16:31
@bryce13950 what do you mean by activating any element? Can you show me some sample code of your solution? 
Thank you

**Comment by bryce13950** [comment] 2018-12-26 13:54
I mean that if you have an input element, and then click on that input, the screen will resize the content, and the footer will start showing. Not a solution, but probably a hint as to what is going on.

**Comment by charlesRms** [comment] 2019-01-10 14:23
solved my problem by changing css of the component inside my footer :

 **page.html**
```
[...]
<ion-footer class="spaceFooter">
    <custom-component></custom-component>
</ion-footer>
```

**custom-component.scss**
```
    position : fixed;
    width :100%;
    bottom:0
```

**global.scss**
```
.spaceFooter{
    margin-top: 53px;
}
```

After that, I had a problem with every pages that had a bigger height than the screen. it was impossible to scroll to the end of the page. I had to create a component that add a 100px div if the device is ios10 and insert it before every </ion-content> tag.

now it's working both in ios (10 and 11) and android, but this is far from optimal.

Looks like there is a compatibility problem with ionic 4 and ios 10...

Hope it will be fixed

**Comment by epicazo** [comment] 2019-02-05 16:02
Do we have any news on the subject? 

For me it's not only the footer that can't be displayed but I can't scroll to the end of my menu, fab buttons positioned at the bottom of the page are out of screen, and my tabs don't show up aswell...

I tested it on a physical iPhone 5c running ios 10.3.3 and with the Xcode simulator an iPhone 5s on 10.3.1

**Comment by supperdsj** [comment] 2019-03-17 15:39
same issure in iphone7/iphone7 plus with ios10

**Comment by diogomachado** [comment] 2019-03-30 02:46
I'm have the same problem in ios 10, iPhone 6s, when the app show keyboard, the footer component not stay in bottom position

**Comment by amosbaby** [comment] 2019-05-21 02:07
same issues in  iOS 10.3.3 , I solved this by adding display:flex to ion-content. you can try it

**Comment by alyleite** [comment] 2019-05-27 20:18
> same issues in iOS 10.3.3 , I solved this by adding display:flex to ion-content. you can try it

@amosbaby Thank you. It worked here

**Comment by ermamud** [comment] 2019-06-12 03:18
@amosbaby Thank you, your solution worked for me as well. But later I noticed there is an issue with loading spinner. Are you having the same issue?

![Simulator Screen Shot - iPhone 6 - 2019-06-11 at 23 16 47](https://user-images.githubusercontent.com/11084100/59321222-3c3f9780-8c9f-11e9-97af-85a690bd2918.png)

**Comment by royanon** [comment] 2019-08-21 17:14
Test on ionic 4.7.4 same problem in ios 10.3.1

**Comment by liamdebeasi** [comment] 2020-02-13 19:11
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.

**Closed by liamdebeasi** 2020-02-13 19:11 UTC
Labels: needs: investigation, package: core
