### ISSUE TITLE
bug [ionic 5]: swipeable modal is moving the parent page 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20607] opened 2020-02-25 07:59 UTC
# Bug Report

**Ionic version:**

[X] **5.x**

**Current behavior:**

When you swipe overlay modal then it is also swiping the parent page as you can see in below pics 
Tested on: Iphone 6 iOS: 12.4.4

![image](https://user-images.githubusercontent.com/23274631/75226618-ae76ee80-57d2-11ea-8d3d-e35b2b1e0f41.png)

![image](https://user-images.githubusercontent.com/23274631/75226677-c3ec1880-57d2-11ea-9471-e4b59152507a.png)

**Expected behavior:**

It should not swipe content of parent page.

**Steps to reproduce:**

**Related code:**

Repo: https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/tree/ionic-5
Dashboard: Click on first ion-item to open swipeable modal.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   ios-deploy : 1.9.4
   NodeJS     : v12.13.0 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61


```

**Comment by liamdebeasi** [comment] 2020-02-25 14:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19746. (The linked issue refers to the action sheet, but the underlying bug is the same).

**Closed by liamdebeasi** 2020-02-25 14:14 UTC
Labels: triage
