### ISSUE TITLE
bug: virtualScroll doesn't work inside a div

### ISSUE THREAD

**Issue by edcampos** [ionic-team/ionic#12112] opened 2017-06-20 14:07 UTC
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When the virtualScroll  is inside a div the list doesn't show.

GitHub url : 
https://github.com/edcampos/ionicVirtualScroll</span>

<span is-issue-template></span>

**Comment by edcampos** [comment] 2017-06-20 14:09
This is my configuration:

Cordova CLI: 6.4.0
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v8.1.2
Xcode version: Not installed

I'm using Angular 4

**Comment by edcampos** [comment] 2017-06-20 14:16
Removing the div in contacts.html (src\pages\contacts\contacts.html), the list appear, but I need to put the virtual scroll inside many divs.

**Comment by jgw96** [comment] 2017-06-21 16:00
Hello! Thanks for opening an issue with us. I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/10148 as this is caused by the same issue. I will also update that issue with the info that this not only happens when virtualscroll is nested in a menu, but when it is nested in a div.

**Closed by jgw96** 2017-06-21 16:00 UTC
