### ISSUE TITLE
feat(range): Custom knob values

### ISSUE THREAD

**Issue by Daskus1** [ionic-team/ionic#20926] opened 2020-03-31 16:23 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Currently it is only possible to display numbers on the range knobs. 
It would be great to allow custom formatting of knob/pin values.

**Describe Preferred Solution**

It could work similarly to how [Angular Material's slider](https://material.angular.io/components/slider/overview#formatting-the-thumb-label) works by allowing the user to specify a function:
`displayWith: (value: number) => string | number`

It could be used as follows:
```javascript
letters = ["A", "B", "C", "D"];
convertToLetter = (value: number) => letters[value];

<ion-item>
  <ion-range pin="true" min="0" max="3" [displayWith]="convertToLetter"></ion-range>
</ion-item>
```

**Additional Context**
Could look like this:
![ion-range-knob](https://user-images.githubusercontent.com/16157888/78050450-83a52a80-737c-11ea-9a64-34607429f899.png)

**Comment by liamdebeasi** [comment] 2020-03-31 19:39
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18767.

**Closed by liamdebeasi** 2020-03-31 19:39 UTC
Labels: triage
