### ISSUE TITLE
DateTimePicker not refreshing days when months change

### ISSUE THREAD

**Issue by swavans** [ionic-team/ionic#17447] opened 2019-02-08 23:46 UTC
This issue also occurs on ionic 4
https://github.com/ionic-team/ionic-v3/issues/80

**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 
[ x] bug report
[ ] feature request

**Current behavior:**
When opening a date time picker in for example february. The day cannot go past 28 whatever month it is. This also occurs when a minimum date has been set. So let's say you mark today as minimum then it can never go before the 8th untill the date is saved and reopened later.

**Expected behavior:**
When scrolling through months the days should adjust accordingly with account of month day length and minimum date.

**Comment by liamdebeasi** [comment] 2019-02-13 13:56
Hi there,

Thanks for opening an issue with us. I am going to close this as a duplicate of #14233.

Please note that the referenced issue was closed and consolidated into a master list here: https://github.com/ionic-team/ionic/issues/16630

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-13 13:56 UTC
Labels: triage
