### ISSUE TITLE
bug: Input focus + scroll + keyboard + chrome version 76.x

### ISSUE THREAD

**Issue by prescindivel** [ionic-team/ionic#19015] opened 2019-08-06 22:42 UTC
# Bug Report

**Ionic version:**

[x] **3.x**

**Current behavior:**
This happened after chrome updated to version 76.x

![image](https://media.giphy.com/media/KCMp2j8KsrYz4DgOTe/giphy.gif)

**Expected behavior:**

![image](https://media.giphy.com/media/eiSWoxW29by1DlDA1n/giphy.gif)

**Steps to reproduce:**

Run ionic application on device with chrome version 76.x

**Other information:**

I'm use cordova-plugin-ionic-keyboard@2.1.3 and cordova-plugin-ionic-webview@4.1.1

**Ionic info:**

```
╰─ ionic info                                      

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/Users/victor/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/victor/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/Users/victor/.nvm/versions/node/v10.15.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by siddharth-pand8y** [comment] 2019-08-07 08:56
I am facing a similar issue with my Ionic application as well. Ever since the update to chrome to 76.x , the view-port does not get resized. The html hides behind the keyboard and after closing the keyboard, the screen area where the keyboard was becomes a blank white screen.

**Comment by liamdebeasi** [comment] 2019-08-07 12:27
Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

**Comment by prescindivel** [comment] 2019-08-07 14:34
@liamdebeasi I create a repository here: https://github.com/prescindivel/ionic-chrome76-bug

**Comment by alampali** [comment] 2019-08-07 21:22
We are also having similar issue with Ionic Application on Android as soon as chrome got updated to 76.0.3809.89

**Comment by lilianfelismino** [comment] 2019-08-09 19:16
Having the same issue with ionic and chrome 76.x on Android

**Comment by smxdevst** [comment] 2019-08-13 17:44
Same issue on Android 9 Samsung A8. Any solution yet?

**Comment by liamdebeasi** [comment] 2019-08-14 13:13
Thanks for the follow up. It looks like this is an Ionic 3 issue, so I am going to transfer this to the v3 repo.

There is a similar v4 issue here: https://github.com/ionic-team/ionic/issues/19065.

Thanks!

**Closed** 2019-08-14 13:13 UTC
Labels: ionitron: v3, triage
