### ISSUE TITLE
feat: Unfocus Buttons when finger goes away on iOS

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21192] opened 2020-05-02 09:32 UTC
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Buttons should unfocus when the finger goes away.

**Describe Preferred Solution**

Buttons like ``ion-button``, ``ion-menu-button``, ``ion-back-button``, ... should unfocus when the finger goes away from button, but keep touching display on iOS. It would look more native, because Native iOS Apps have this feature.

**Comment by liamdebeasi** [comment] 2020-05-04 13:11
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21052.

Please see https://github.com/ionic-team/ionic/issues/21052#issuecomment-614906540 for more information regarding the button focus state.

**Comment by BerkeAras** [comment] 2020-05-04 13:12
But it does not work on buttons.

**Closed by liamdebeasi** 2020-05-04 13:11 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2020-05-04 13:14
Yes, that's what https://github.com/ionic-team/ionic/issues/21052#issuecomment-614906540 explains.

This is not something we currently have planned as the custom gesture required to apply this to all buttons would incur a large performance hit for all apps.

Ideally there would be a CSS-only way of doing this, but no good solutions exists right now.
