### ISSUE TITLE
The select Icon inner should have spacing between the textbox in RTL

### ISSUE THREAD

**Issue by Newbie012** [ionic-team/ionic#16297] opened 2018-11-12 08:20 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Eliya\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.7
   @angular-devkit/schematics    : 0.8.7
   @angular/cli                  : 6.2.7
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (E:\android-sdk)
   NodeJS            : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Describe the Bug**
If we set `[dir="rtl"]` then the selects icon inner would be too much tight.

**Steps to Reproduce**
1. Set `[dir="rtl"]`
2. Create a simple select.
3. See occurrence

**Related Code**
```
  <html dir="rtl">
  ...
  <ion-item>
    <ion-label>Gender</ion-label>
    <ion-select placeholder="Select One">
      <ion-select-option value="f">Female</ion-select-option>
      <ion-select-option value="m">Male</ion-select-option>
    </ion-select>
  </ion-item>
```

**Expected Behavior**
The should be spacing between the text and the select icon.

**Additional Context**

RTL:

![image](https://user-images.githubusercontent.com/10504365/48334808-91152400-e664-11e8-893b-33c8860c9260.png)

LTR:

![image](https://user-images.githubusercontent.com/10504365/48334816-983c3200-e664-11e8-81d7-ff9a9e682d9e.png)

**Comment by brandyscarney** [comment] 2019-01-03 16:22
Closing as a duplicate of #16212

**Closed by brandyscarney** 2019-01-03 16:22 UTC
Labels: needs: investigation, package: core
