### ISSUE TITLE
bug: Too many ngDoCheck() calls reload the application

### ISSUE THREAD

**Issue by szymonograbek** [ionic-team/ionic#18483] opened 2019-06-07 12:02 UTC
# Bug Report

**Ionic version:**
[x] **4.2**

**Current behavior:**
App reloads webview after too many `ngDoCheck()` calls at once

**Expected behavior:**
The app shouldn't reload/lag

**Steps to reproduce:**
1. Implement `app-list`, that renderes `app-entry` using `ngFor` like this:
```
<app-entry *ngFor="let entry of entries$ | async; trackBy: trackEntries" [entry]="entry"></app-entry>
```
and add a button/infinite scroll that will call this method:
```
getData(): void {
    this.entries$.next([...this.entries$.getValue(), ...new Array(25).fill({ name: "test" })]);
}
```
2. Load more data and the app will reload after a while. If the `app-entry` consist of a single `div` then it may take a while, but if it's more complicated it will happen quickly

**Related code:**

Can't share the code I have now, but later on I may try to reproduce it on fresh project. 

**Other information:**
I think it's because of `ngDoCheck()` but I'm not 100% sure. If you render a simple `div` instead of `app-entry` it works fine.
In XCode when the reload happens it says 
```
[ProcessSuspension]  0x282d43b80 - ProcessAssertion() Unable to acquire assertion for process with PID 0
```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13970661/59102545-b3d29700-892c-11e9-95dd-dd15483d356b.gif)
This is just simple recreation, it happens way sooner when the `app-entry` is more complex.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.0
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic 5.3.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 17 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/szymonograbek/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v8.11.4 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment] 2019-06-07 13:08
Hi there,

Thanks for the issue! Are there any Ionic-specific components that you think are causing this issue? `ngDoCheck` is part of the Angular lifecycle, and is typically called when Angular's change detection is run.

Additionally, are you able to reproduce this in a standalone Angular application (without Ionic)? 

Thanks!

**Comment by szymonograbek** [comment] 2019-06-07 13:23
> Hi there,
> 
> Thanks for the issue! Are there any Ionic-specific components that you think are causing this issue? 
> 
> Additionally, are you able to reproduce this in a standalone Angular application (without Ionic)?
> 
> Thanks!

No, there is no need for any ionic components, but I can't reproduce it on standalone Angular application, because it's iOS specific. Android app and website work fine. 

> `ngDoCheck` is part of the Angular lifecycle, and is typically called when Angular's change detection is run.
Yes, but when I have a list rendered by `ngFor` and I keep loading more items it calls `ngDoCheck()` on every item and I think that causes the app reload. Although I'm not entirely sure.

**Comment by liamdebeasi** [comment] 2019-06-07 13:30
Thanks for the follow up! Ionic tries to not interfere with change detection (with some exceptions to routing), so I don't think this is an Ionic bug. 

I would recommend ensuring that your component is only being re-rendered when it absolutely needs to be. Additionally, I would recommend looking into using the `OnPush` change detection strategy for your Angular components: https://angular.io/api/core/ChangeDetectionStrategy.

I am going to close this as this sounds like more of an infrastructure issue than a bug in Ionic. If you are able to demonstrate that this issue might be caused by something Ionic specific, feel free to reply here, and I'll be happy to investigate 🙂.

Thanks!

**Closed by liamdebeasi** 2019-06-07 13:30 UTC
Labels: triage
