### ISSUE TITLE
Unable to set attribute: autocapitalize on an ion-input

### ISSUE THREAD

**Issue by kelvindart** [ionic-team/ionic#12614] opened 2017-08-08 10:16 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently, `ion-input` does not support the attribute `autocapitalize`.

**Expected behavior:**
For the `ion-input` to set this behaviour, and to copy this attribute to the native `input` element. I am raising this issue to support a PR I am raising.

**Steps to reproduce:**
N/A

**Related code:**

```
<ion-input autocapitalize="sentences"></ion-input>
```

**Other information:**
N/A - raised for a PR.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/kelvindart/src/myApp/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/kelvindart/src/myApp/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/kelvindart/src/myApp/node_modules/ionic)

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.2.1 Build version 8C1002 
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    npm               : 5.3.0
```

**Comment by brandyscarney** [comment] 2017-08-08 16:07
I'm not able to reproduce this using the following markup on iOS 10.2:

```

  <ion-item>
    <ion-label>Ionic: default</ion-label>
    <ion-input placeholder="no autocapitalize"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label>Ionic: none</ion-label>
    <ion-input autocapitalize="none" placeholder="none"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label>Ionic: on</ion-label>
    <ion-input autocapitalize="on" placeholder="on"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label>Ionic: sentences</ion-label>
    <ion-input autocapitalize="sentences" placeholder="sentences"></ion-input>
  </ion-item>

  <ion-item>
    <ion-label>Native: default</ion-label>
    <input ngProjectAs="ion-input" placeholder="no autocapitalize"/>
  </ion-item>

  <ion-item>
    <ion-label>Native: none</ion-label>
    <input ngProjectAs="ion-input" autocapitalize="none" placeholder="none"/>
  </ion-item>

  <ion-item>
    <ion-label>Native: on</ion-label>
    <input ngProjectAs="ion-input" autocapitalize="on" placeholder="on"/>
  </ion-item>

  <ion-item>
    <ion-label>Native: sentences</ion-label>
    <input ngProjectAs="ion-input" autocapitalize="sentences" placeholder="sentences"/>
  </ion-item>
```

<img width="250" src="https://user-images.githubusercontent.com/6577830/29081942-0ae0f596-7c32-11e7-9193-bbb83deecff9.jpg">


Both the `ion-input` and the native `input` elements behave exactly the same, and I am able to see `autocapitalize` being passed down to the native input. Could you provide a plunker or steps to reproduce this? Thanks :)

**Comment by jgw96** [comment] 2017-08-23 20:56
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-08-23 20:56 UTC
Labels: needs info, v3

**Comment by kelvindart** [comment] 2017-08-24 07:30
Hi guys,

Agreed - this is not an issue, I (incorrectly!) based it on my experiences with `ion-searchbar`.

Thanks
Kelvin
