### ISSUE TITLE
RC.0 - ion-back-button with child in tabs starter goes to wrong tab 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic#16923] opened 2018-12-31 23:35 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Using `ion-back-button` from a tab other than first tab takes you to first tab, not tab that launched the child.

**Expected behavior:**

The `ion-back-button` should take you back to the tab from whence you came.

**Steps to reproduce:**

1. use tab starter
1. add a child page with default ion-back-button config in toolbar
1. go to child from tab two or three
1. hit back button
1. end up on tab one...

**Related code:**

https://github.com/kensodemann/issue-tabs-back-button-

1. clone
1. npm start
1. go to tab 2
1. hit the "have a baby" button
1. child open
1. hit back button on child
1. you are now on tab one instead of two

**Ionic info:** 

```
~/Projects/Issues/issue-tabs-back-button (master): ionic info

Ionic:

   ionic (Ionic CLI)             : 4.6.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.2 (/home/kensodemann/.nvm/versions/node/v10.14.2/bin/node)
   npm    : 6.4.1
   OS     : Linux 4.15
```

**Comment by supperdsj** [comment] 2019-01-04 10:00
same here

**Comment by supperdsj** [comment] 2019-01-04 10:06
`<ion-back-button (click)="navCtrl.goBack()"></ion-back-button>`
NavController.goBack() can go back to the right page.

**Comment by RHinderiks** [comment] 2019-01-09 13:04
@supperdsj This still causes issues with our app, as far as i know setting a click on a back button does not prevent it from executing its normal behaviour, so in this case your triggering your own goBack and the default behaviour of the back button ?

**Comment by supperdsj** [comment] 2019-01-10 03:09
@kensodemann hope you share more detail about your "hard coded" solution :)

**Comment by hiepxanh** [comment] 2019-01-11 10:35
`navCtrl.goBack()` that function causing my tab view being destroyed

**Comment by supperdsj** [comment] 2019-01-14 10:00
`<ion-button color="primary" fill="clear" (click)="navCtrl.goBack();">
        <ion-icon slot="start" name="arrow-back"></ion-icon>back
      </ion-button>`
work for me

**Comment by paulstelzer** [comment] 2019-01-15 09:42
I close this as duplicate of #15216

I think my gif demonstrate the issue well -> https://github.com/ionic-team/ionic/issues/15216#issuecomment-447334318 (after navigating back it opens the first tab)

and I think it's the same issue like described here

**Closed by paulstelzer** 2019-01-15 09:42 UTC
Labels: needs: investigation, package: angular

**Comment by kensodemann** [comment] 2019-01-15 22:39
You are correct sir!! (locking this as well to avoid further discussion here)
