### ISSUE TITLE
bug: (Android) tab-bar moves to middle of the screen when using searchbar

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic#19308] opened 2019-09-09 14:13 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When using `ion-searchbar`, `ion-tab-bar` moves to the middle of the screen when the keyboard is opened and doesn't return to the bottom, when the keyboard is closed.

**Expected behavior:**

`ion-tab-bar` doesn't stay in the middle of the screen.

**Steps to reproduce:**

1.  Use an `ion-searchbar` inside a tabs page
2.  Click on the searchbar so the keyboard opens
3.  Click on an `ion-item` in the search
4.  App routes to detail screen
4. Tab-Bar stays in the middle of the screen

**Related code:**

I'm using this code to generate the searchbar
```html
<ion-header>
  <ion-toolbar>
    <ion-searchbar
      [(ngModel)]="queryString"
      placeholder="Suche"
      (ionInput)="onInput()">
    </ion-searchbar>
  </ion-toolbar>
</ion-header>
```

I use this code to show some search results and get notified when the wanted item is clicked
```html
<ion-item button (click)="itemClicked(result)" *ngFor="let result of searchResults">
    ....
</ion-item>
```

And the page is a child of this tabs-page
```html
<ion-tabs>

  <ion-tab-bar #tab slot="bottom">

    <ion-tab-button tab="home">
      <ion-icon name="home"></ion-icon>
    </ion-tab-button>

    <ion-tab-button tab="search">
      <ion-icon name="search"></ion-icon>
    </ion-tab-button>

    ...

    <ion-tab-button tab="menu">
      <ion-icon name="menu"></ion-icon>
    </ion-tab-button>

  </ion-tab-bar>

</ion-tabs>
```

**Other information:**

I've tried the solution proveded [here](https://github.com/ionic-team/ionic/issues/16419#issuecomment-441415372) but that didn't have any effect.

Here's a screenshot that illustrates the problem:
![Screenshot_20190909-155837](https://user-images.githubusercontent.com/4333261/64537716-a4902a80-d31b-11e9-8160-df6c5482c140.png)

I have done a small workaround that solves this issue for now. Before routing to the detail page after the `ion-item`-click, I now wait 250ms for the keyboard to close.
This leads to the expected behavior on all Android devices I could test with

```js
    if (this.keyboard.isVisible) {
      this.keyboard.hide();
      await this.wait(250);
    }
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.0
   @angular-devkit/schematics    : 8.3.0
   @angular/cli                  : 8.3.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 15 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.2 (update available: 0.2.8)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

```

**Comment by liamdebeasi** [comment] 2019-09-10 12:49
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

**Closed by liamdebeasi** 2019-09-10 12:49 UTC
Labels: triage
