### ISSUE TITLE
document title is not updated

### ISSUE THREAD

**Issue by ildar-icoosoft** [ionic-team/ionic#13436] opened 2017-11-15 19:10 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**
document title is not changed if I execute navCtrl.push() or app.setTitle()

**Expected behavior:**
title should be changed (the content of the <title> element in an HTML document)

**Steps to reproduce:**
create a project using ionic cli command: `ionic start myApp tutorial`. Go to the list of items. The document title will not be changed

Here is github repo: https://github.com/ildar-icoosoft/ionic-starter-tutorial

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.6.0
    npm  : 5.3.0
    OS   : Windows 7

Misc:

    backend : legacy
```

**Comment by kensodemann** [comment] 2017-11-16 02:36
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by ildar-icoosoft** [comment] 2017-11-16 05:37
@kensodemann I created repo for you: https://github.com/ildar-icoosoft/ionic-starter-tutorial
I created this project using command: `ionic start someName tutorial`

**Comment by pwespi** [comment] 2017-11-16 08:57
Possibly related to https://github.com/ionic-team/ionic/issues/9398 and https://github.com/ionic-team/ionic/issues/9124.

**Comment by qcnguyen** [comment] 2017-11-19 07:29
hi, I encounter the same issue.
Please fix.
It also happen to new project too. Check out this command to see:

ionic start myApp sidemenu

Thanks.

**Comment by vellengs** [comment] 2017-12-30 00:46
@kensodemann  
I have same issue.   
The title cannot changed whatever.
even use 
```
the.app.setTitle('xxxxxx'),   
```
tested reproduce   by  tabs ／ supper   .

**Comment by kensodemann** [comment] 2018-01-04 00:42
Hello! Thank you for opening an issue with us!

At some point, `app.setTitle()` stopped working even though the code did not change. It is a simple pass-through to Angular's Title service, and using it directly _does_ work, so for now you can inject Angular's Title service and use it (https://angular.io/api/platform-browser/Title). I have tested that and it works.

Looking at the next version of Ionic, we will be directly setting `document.title` via `app.setTitle()`. Setting the `document.title` automatically on navigation is something that should also work in the next major release.

I am going to close this issue because it will not be fixed in v3 but should be fixed in the next major release of Ionic and Ionic for Angular. If it is not fixed in that release, please let us know.

Thank you for using Ionic

**Closed by kensodemann** 2018-01-04 00:42 UTC

**Comment by ildar-icoosoft** [comment] 2018-01-04 07:22
Why don't you fix this bug in current release? It is a bug. It works in previos versions and it does not work in current release

**Comment by kensodemann** [comment] 2018-01-04 12:15
@ildar-icoosoft - it will not be fixed in the current release because there are no plans to have another v3 release. All effort is being put into getting the "v4" release out the door.

**Comment by jfougere** [comment] 2018-03-13 10:16
I know you closed the issue but we are now upgrading our app from v2 to v3 and having title not working anymore is a blocking issue.

You said that using directly the Title component from angular works so I tested and yes it works as long as you inject it in the page constructor.
I tried with the same code you have in App component (ie newTitle(DOCUMENT).setTitle("xxx") and this does not work. 

So I guess the fix in v3 would be pretty simple instead of creating a new Title you just need to inject it in App component and voila !

Any chance to see a v3 fix so ?
