### ISSUE TITLE
ionic v4 Custom style in pages missing after migration from v3

### ISSUE THREAD

**Issue by goelectricstations** [ionic-team/ionic#14951] opened 2018-07-31 07:21 UTC
now CSS from pages get merged in one file html, I really do not like this new way of v4.

anyway, the issue is that v4 add to styles "[_ngcontent-c0]" in the name of the class. why?

**Comment by brandyscarney** [comment] 2018-08-06 20:08
I'm not sure I understand your first statement. Are you talking about the minified CSS that needs to be included for fonts/colors to work? We found this was the best way to only include the CSS that you need in your app, without having it included multiple times, since the CSS for a component is only included when that component is used. Some more details on that here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#theming

The `ngcontent` attributes are added by Angular. There is more on this here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#including-sass

Angular Component Styles: https://angular.io/guide/component-styles
View Encapsulation: https://angular.io/guide/component-styles#view-encapsulation

Setting the `encapsulation` in your component will remove these attributes:

```
@Component({
  selector: 'page-login',
  templateUrl: 'login.html',
  styleUrls: ['./login.scss'],
  encapsulation: ViewEncapsulation.None
})
```

I'm going to close this since it's more of a support question but if you have more questions please use our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks!

**Closed by brandyscarney** 2018-08-06 20:08 UTC
Labels: triage

**Comment by goelectricstations** [comment] 2018-08-20 16:40
@brandyscarney ok but changes the css classes then the style does not work anymore. How to fix and still have encapsulation?

**Comment by brandyscarney** [comment] 2018-08-20 18:10
Please use our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for questions on using the framework.

It's helpful to provide code examples, images, and what you're expecting to happen when asking for help. 

I am able to style an Ionic component using the following markup:

*about.html*:

```
<ion-content>
  <ion-grid>
    <ion-row class="my-row">
      <ion-col>Col</ion-col>
      <ion-col>Col</ion-col>
      <ion-col>Col</ion-col>
      <ion-col>Col</ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```

*about.scss*:

```
.my-row {
  background: blue;
}
```

Without setting `ViewEncapsulation` to anything, it will generate the following:

<img width="1218" alt="screen shot 2018-08-20 at 2 08 58 pm" src="https://user-images.githubusercontent.com/6577830/44358316-9e19e100-a482-11e8-9fb8-20244f85a3d5.png">

This is the expected behavior. If you're still having issues regarding `ViewEncapsulation` please read the links I posted. Thanks.
