### ISSUE TITLE
bug: Tabbar flickers when opening keyboard

### ISSUE THREAD

**Issue by chvonrohr** [ionic-team/ionic#20262] opened 2020-01-22 09:19 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When keyboard appears, tabbar flickers shortly on top of keyboard (see video here: https://www.youtube.com/watch?v=RFi4PDXApzY&list=UUpeOaulS7pfzELKMOBRHg1A)
-> it does not occur every time! I guess the `keyboard-show` event, that adds a class to hide the tabbar is too slow - but only a guess.

**Expected behavior:**
No flicker - tabbar hidden when keyboard opens

**Steps to reproduce:**
- create a new ionic app from tab template
- add an ion-input on tab2
- run in android simulator
- click in/out input to open keyboard (multiple times)

**Comment by liamdebeasi** [comment] 2020-01-22 15:02
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The framework does not have control over when/how the keyboard opens, so we cannot prevent the keyboard from opening until the tabbar is hidden. The flickering is happening because sometimes the browser can hide the tabbar in the same frame, other times it needs to hide it in the next frame.

The reason why this behavior occurs is because in Cordova apps the webview will attempt to resize itself when the keyboard is open. One option is to disable the resizing. You should be able to add something like the following to your `config.xml`:

```xml
<platform name="android">
  ...
  <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application/activity">
    <activity android:windowSoftInputMode="adjustPan" />
  </edit-config>
</platform>
```

Hope this helps!

**Closed by liamdebeasi** 2020-01-22 15:02 UTC
Labels: triage

**Comment by chvonrohr** [comment] 2020-01-23 13:43
thank you @liamdebeasi - it works perfectly like that and we don't need content shrinking.
is there a reason, this is not default?
