### ISSUE TITLE
Toggle disabled="true" still interactive 

### ISSUE THREAD

**Issue by mflmartin** [ionic-team/ionic#11850] opened 2017-05-29 15:01 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`<ion-toggle checked="false" disabled="true"></ion-toggle>`
It can still be toggled

**Expected behavior:**
Can't touch it (na, na, na ♫)
It shouldn't be possible to toggle it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by jgw96** [comment] 2017-05-30 15:11
Hello, thanks for using Ionic! Unfortunately, I cannot reproduce this issue locally. Would you be able to share a plunker or repo we could use to reproduce this?

**Comment by jgw96** [comment] 2017-06-05 15:01
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-05 15:01 UTC
Labels: needs info, v3

**Comment by kaoecoito** [comment] 2017-10-27 20:40
I have the same problem more in the tests that I did what happens is that if I use the ion-toogle inside an ion-item the disable works, however if it is used inside the ion-header> ion-buttons it stays active even with the disable
