### ISSUE TITLE
(PWA) (Deeplinker?) Back button, followed by forward button on browser causes inconsistent state

### ISSUE THREAD

**Issue by kelvinhokk** [ionic-team/ionic#11597] opened 2017-05-10 14:59 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When using the ionic blank app on platform browser,  the ionic page goes into a inconsistent state after a user clicks on back, followed by forward button.

On my project, this causes components not to work properly and variables not to be initialised properly on the template.  

**Expected behavior:**

When you click on forward and then back, the page should be in a consistent state.
![screen shot 2017-05-10 at 10 58 26 pm](https://cloud.githubusercontent.com/assets/7766953/25905295/36bdd66a-35d4-11e7-88fb-9a4e3a8a25bc.png)

**Steps to reproduce:**
Please refer to testBug repository based on blank app on github.
https://github.com/kelvinhokk/ionicBug11597

1. Check out project.
2. ionic serve.
3. Go from home page to test form page (red button)
4. Input "a@b.com" into input.  Notice that validation is ok.
5. Press back button and then forward button on browser.  Notice that validation is still ok.

6. ionic cordova platform add browser
7. ionic cordova run browser.
8. repeat steps 1-5.
9. notice that the validation is not ok, and the page is inconsistent state.

**Related code:**

(I suspect this has something to do with the page not popping properly on back, when doing elementary debugging, the following section is never evaluated to be true on back button.)

```
if (view && view.id === segment.id) {
        // hooray! we've already got a view loaded in the stack
        // matching the view they wanted to show
       ....
          nav.popTo(view, {
            animate: false,
            updateUrl: false,
          }, done);
 }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Bug reproduced on browsers on Chrome 58.0.3029.96 and Safari Version 10.1 (12603.1.30.0.34)

Bug also happens on latest ionic 3.2.0

```

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.2 
```

**Comment by jgw96** [comment] 2017-06-05 16:14
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11469

**Closed by jgw96** 2017-06-05 16:14 UTC
Labels: navigation, v3
