### ISSUE TITLE
Official Progress Bar Component

### ISSUE THREAD

**Issue by Domvel** [ionic-team/ionic#14716] opened 2018-07-05 09:09 UTC
# Feature Request

**Ionic Info**

```
cli packages: (C:\Users\<Username>\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\sdk

Misc:

    backend : legacy
```

**Describe the Feature Request**
In my opinion Ionic needs an official progress bar. Like all other UI frameworks have.

**Describe Preferred Solution**
A progress bar aka bar-graph or loading-bar with several options like 
- horizontally or vertically oriented
- with or without display the value (e.g. percentage)
- easy to set color (color attribute)
- responsive / ionic like.
- An indeterminate mode. (optional: buffer, query)
- (optional) Clickable on the bar to set the value by user input.
- Easy change the width of the bar graph.

Use cases: 
- Display an installation or download progress.
- Video or audio position.
- User input.

**Describe Alternatives**
There are tutorials on the net, how to create you own progress bar. 
This is a basic component for an UI framework. It's time to finally implement it.

**Additional Context**
What is the best progress bar for ionic? I can't say it. There are so many different features and styles. I'm sure we all know how a basic progress bar looks like. Maybe let you inspire by the angular material progress bar.

**Comment by kerosin** [comment] 2018-07-05 10:19
Duplicate of https://github.com/ionic-team/ionic/issues/6669
(also see https://github.com/ionic-team/ionic/pull/12010)

**Comment by brandyscarney** [comment] 2018-07-05 17:32
Thanks for the issue! Closing as a duplicate of #6669. This is definitely something we want to get added but we're currently working hard to get v4 out. Let me know if it's something you'd like to submit a PR for and I can help out as much as possible. 🙂

**Closed by brandyscarney** 2018-07-05 17:32 UTC
Labels: triage
