### ISSUE TITLE
bug: why click the ion-back-button previous url query param is disappear?

### ISSUE THREAD

**Issue by yangjunfocus** [ionic-team/ionic#18094] opened 2019-04-22 06:22 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

example: previous url is `localhost:8100/test?type=1`,current url is `localhost:8100/news`,then click then `ion-back-button` navigates back previous url,but the url become `localhost:8100/test`,now the url query param is disappear.why?
**Expected behavior:**

i want to click back button navigates back prervious url query param is full
**Steps to reproduce:**

**Related code:**
page:localhost:8100/news 
![image](https://user-images.githubusercontent.com/23710467/56486243-962aa900-6509-11e9-93b8-6c4ee89dda9a.png)

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

![image](https://user-images.githubusercontent.com/23710467/56486282-b6f2fe80-6509-11e9-8603-955da64202ef.png)

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2019-04-22 12:38
Thanks for the issue! This is a known issue, so I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16744.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-22 12:38 UTC
Labels: triage
