### ISSUE TITLE
android build fails on latest update - Theme.AppCompat

### ISSUE THREAD

**Issue by nhhockeyplayer** [ionic-team/ionic#20985] opened 2020-04-07 12:35 UTC
coming on 7 days for this one still no solution
android build is taking me down

=============
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  error: resource style/Theme.AppCompat (aka io.ionic.myapp:style/Theme.AppCompat) not found.
  error: failed linking references.
========================

meanstack@meanstacks-MacBook-Pro myap % ionic info

Ionic:

   Ionic CLI                     : 6.4.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.6, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)

Utility:

   cordova-res                          : 0.11.0
   native-run (update available: 1.0.0) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/meanstack/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v13.6.0 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.4 Build version 11E146

=================

gradle plugin is 5.6.4
android studio is 3.6.2

top level buld.gradle for android platform shows classpath 'com.android.tools.build:gradle:3.3.0'

any help is appreciated

**Comment by nhhockeyplayer** [comment] 2020-04-07 14:16
I have watched this industry evolve 16 years java 10 yrs C++ to cusotm private maven repo' to present day web

and its striking/obvious to me that the folks developing gradle and android studio and into ionic
are predominantly juniors who never knew what they were doing
why?
because ONLY they know how the gradle version HELL works with its winding over engineered over complicated twists and turns
scared for their jobs this is the only way they know how to create job security
because THEY are the on ones that know how to make it all work
and they refuse to document otherwise either
ad the proof is in the pudding

and for management to go along with it is even more pitiful

and this carries on for years and years

https://discuss.gradle.org/t/trying-to-get-3-3-working-android-studio-and-other-bugs/21200

so I challenge any of you

inspire me

impress me

im not impressed and the amount of time spent on build issues far outweighs any time spent on business logic

this is pre angular CLI

likely wont be fixed r re-architected anytime soon

explain why iOS flies thru no trouble

yeah

but its open source...
sorry if you cant do it dont do it

**Comment by nhhockeyplayer** [comment] 2020-04-07 14:29
can anyone explain why there is no CONFIG.XML top level preference for 
   o.  android gradle plugin
   o.  android studio version
   o.  gradle version

the wrapper looks like a hideous design flaw when alot of this could be resolved with environment variables instead of taking out build environments across version to version

and some on the fly fixup logic & warnings/preventions to boot

I have seen android studio launch and ask to upgrade gradle and the developer hwo knows nothing about artifacts and transient dependencies or corrupted repo's CLICKs it and are lost for a week when their production build needs to be delivered

this has to get better some how the issues span back to 2015
and im not blaming ionic totally but it seems everyone got in their 0.02cents mostly android studio

**Comment by liamdebeasi** [comment] 2020-04-07 14:50
Thanks for the issue! I am going to close this as this is not a bug in Ionic Framework. Ionic Framework does not manage your native dependencies nor does it manage building a standalone Capacitor/Cordova application. This is likely either a configuration issue with your project, or an issue with other tooling.

For further help with this issue, I recommend posting on our [forums](http://forum.ionicframework.com/).

**Closed by liamdebeasi** 2020-04-07 14:50 UTC
Labels: triage

**Comment by nhhockeyplayer** [comment] 2020-04-07 15:16
dont hesitate to comment on the problem

top level CONFIG.XML preferences to manage this

keep passing the buck its job security
