### ISSUE TITLE
bug: width of scrollable segment buttons not exceeding 90 pixels

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic#20836] opened 2020-03-20 22:55 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If you have a scrollable segment on a device that has less width as the total width of all segment buttons combined, the GUI is unusable.
As soon as you have text in a segment button that exceeds 90 pixels, it is overlapping other button texts.

**Expected behavior:**
The width of each segment button should be as large as necessary if the segment has scrollable=true.

**Steps to reproduce:**
https://stackblitz.com/edit/ionic-angular-v5-7nvjse

Make sure to restrict the width of your browser when testing.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.0 (/usr/local/bin/node)
   npm     : 6.14.3
   OS      : macOS Catalina
   Xcode   : Xcode 11.3.1 Build version 11C504
```

**Comment by andreas-aeschlimann** [comment] 2020-03-20 23:12
So the problem is that `<ion-segment-button>` has the css property `flex-shrink: 1`.

This fixes the problem:
```
    ion-segment {
        ion-segment-button {
            flex-shrink: 0;
        }
    }
```

Could you implement this in the component?

**Comment by asadullazadeh** [comment] 2020-03-21 20:00
You can fix with `min-width`. (global or app.component.scss)

```
ion-segment-button {
    min-width: auto !important;
}
```

**Comment by liamdebeasi** [comment] 2020-03-23 13:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20566. A fix has been completed and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-03-23 13:18 UTC
Labels: triage
