### ISSUE TITLE
bug: SSR "TypeError: Cannot read property 'width' of undefined" when updating from Ionic 5.0.5 to Ionic 5.1.0

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic#21203] opened 2020-05-04 14:47 UTC
Bug Report

**Ionic version:**
5.1.0  

**Current behavior:**
Error message when prerendering:
"TypeError: Cannot read property 'width' of undefined"

**Expected behavior:**
SSR + prerender should work

**Steps to reproduce:**
Update ionic from 5.0.5 to 5.1.0

**Related code:**
I build a small example to reproduce the bug:
https://github.com/KevinBassaDevelopment/ionic-ssr-bug

**Comment by liamdebeasi** [comment] 2020-05-04 16:52
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21138.

**Closed by liamdebeasi** 2020-05-04 16:52 UTC
Labels: triage

**Comment by KevinBassaDevelopment** [comment] 2020-05-05 07:41
Ok, I thought it might be something different because I'm not using slider and because this issue was not present with Ionic 5.0.5

**Comment by liamdebeasi** [comment] 2020-05-06 13:24
Yeah for some reason `ion-slides` is always pre-rendered even if you aren't using it in your app. It's probably related to how we bundle Swiper with Ionic.
