### ISSUE TITLE
[4.0.0-rc.0] 'ion-tab' is not a known element

### ISSUE THREAD

**Issue by idan003** [ionic-team/ionic#16877] opened 2018-12-25 00:36 UTC
# Bug Report

**Ionic version:**
[] 3.x 
[x] 4.x

**Current behavior:**
i upgrade from beta 19 to the last update 4.0.0-rc.0 and then i got an error in the tab section in my app

```
Uncaught Error: Template parse errors:
'ion-tab' is not a known element:
1. If 'ion-tab' is an Angular component, then verify that it is part of this module.
2. If 'ion-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<ion-tabs>

  [ERROR ->]<ion-tab tab="video">
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>
"): ng:///AppModule/TabsPage.html@2:2
'ion-tab' is not a known element:
1. If 'ion-tab' is an Angular component, then verify that it is part of this module.
2. If 'ion-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <ion-router-outlet name="home"></ion-router-outlet>
  </ion-tab>
  [ERROR ->]<ion-tab tab="ebook">
    <ion-router-outlet name="ebook"></ion-router-outlet>
  </ion-tab>
"): ng:///AppModule/TabsPage.html@5:2
'ion-tab' is not a known element:
1. If 'ion-tab' is an Angular component, then verify that it is part of this module.
2. If 'ion-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    <ion-router-outlet name="ebook"></ion-router-outlet>
  </ion-tab>
  [ERROR ->]<ion-tab tab="settings">
    <ion-router-outlet name="settings"></ion-router-outlet>
  </ion-tab>
"): ng:///AppModule/TabsPage.html@8:2
    at syntaxError (compiler.js:2427)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:20311)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:25857)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:25844)
    at compiler.js:25787
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:25787)
    at compiler.js:25697
    at Object.then (compiler.js:2418)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:25696)
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2
```

**Comment by paulstelzer** [comment] 2018-12-25 08:11
Duplicate of #16796

**Closed by paulstelzer** 2018-12-25 08:11 UTC
Labels: triage
