### ISSUE TITLE
bug: Ionic/react tutorial application failed to be built in Android Studio on MacOSX

### ISSUE THREAD

**Issue by GeoffreyOnRails** [ionic-team/ionic#20236] opened 2020-01-18 18:19 UTC
# Bug Report

**Ionic version:**
[x] **4.11.8**

**Current behavior & Steps to reproduce :**
I've cloned the following project https://github.com/ionic-team/photo-gallery-capacitor-react as described in the tutorial https://ionicframework.com/docs/react/your-first-app/6-deploying-mobile

> git clone https://github.com/ionic-team/photo-gallery-capacitor-react.git
> npm install
> ionic cap open android

(I've also tested 
> rm -rf android 
> ionic cap add android
> ionic cap open android with the same result)

Android studio opens, but an error appears on the build tab in android sync failed > Run Build > Configure Build : 

![Capture d’écran 2020-01-18 à 19 16 26](https://user-images.githubusercontent.com/4128473/72668436-2eb57180-3a27-11ea-928b-1842927849d4.png)

The graddle file in /private/var/folders/y9/t_0m49hs1f7_wlh_tn0wnm5h0000gp/T/sync.java.lib.gradle:7 is the following : 

```
initscript {
    dependencies {
        classpath files(['/Applications/Android Studio.app/Contents/plugins/android/lib/sdk-tools.jar', '/Applications/Android Studio.app/Contents/plugins/android/lib/sdk-tools.jar', '/Applications/Android Studio.app/Contents/lib/kotlin-stdlib-1.3.50.jar'])
    }
}
allprojects {
    apply plugin: com.android.java.model.builder.JavaLibraryPlugin
}
```

I would expect the breaking line to be, instead (but I'm not an expert in Graddle so I might be entirely wrong) : 

`apply plugin: 'com.android.java.model.builder.JavaLibraryPlugin'`

**Expected behavior:**
I would expect the project to be able to build, produce a SDK... 

**Other information:**
Whether it's a bug with Ionic or an issue with my Android Studio installation / configuration, I think it would be helpful to describe/give a reference on how to make a clean/standard installation of Android Studio in the tutorial.

I also add that I am able to build and emulate a native application from an Android Studio template.

**Ionic info:**

```

Ionic:

   Ionic CLI       : 5.4.15 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.8

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   NodeJS : v12.3.1 (/usr/local/Cellar/node/12.3.1/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina

```

**Comment by elylucas** [comment] 2020-01-20 14:33
Hi @GeoffreyOnRails,

We do have a guide on getting Android Studio setup here: https://ionicframework.com/docs/installation/android.

Thanks for the suggestion on adding a reference to this on the guide, we will look into that.

If you get a chance, let us know if following the guide helps fix the issue. Im going to close this issue as its not a bug on the framework, but we can continue to chat here.

**Closed by elylucas** 2020-01-20 14:33 UTC
Labels: triage
