### ISSUE TITLE
Border in backdrops

### ISSUE THREAD

**Issue by RidClick** [ionic-team/ionic#21250] opened 2020-05-07 15:42 UTC
**Description:**

In the latest version I have encountered an unwanted border when launching toast, alerts and any component that has a backdrop.
I have not been able to delete it using css.

**Steps to Reproduce:**

I have created a new project from 0 with the current version 6.8.0 and the same is still happening, using cordova and angular.

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 6.8.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.4
   @angular-devkit/schematics    : 9.1.4
   @angular/cli                  : 9.1.4
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 16 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/rid/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v12.16.3 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a
```

**Comment by liamdebeasi** [comment] 2020-05-08 17:00
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21199.

Please see https://github.com/ionic-team/ionic/issues/21199#issuecomment-623396644 for a workaround.

**Closed by liamdebeasi** 2020-05-08 17:00 UTC
Labels: triage
