### ISSUE TITLE
ion-toggle unnecessarily triggers `change` event when default value is true

### ISSUE THREAD

**Issue by cubicleWar** [ionic-team/ionic#7806] opened 2016-08-20 22:45 UTC
_This is reposting of issue #6144 from beta 4 it appears to have made its way back into beta 11_

**Short description of the problem:**

ion-toggle unnecessarily triggers change event when the default value is true

**What behavior are you expecting?**

The change event should not fire until the user presses the toggle

Steps to reproduce:
1. Create an ion-toggle with ngModel bound to a variable with a default value of true
2. Observe change event firing without any user input

toggle: boolean = true;

<ion-toggle [(ngModel)]="toggle" (ionChange)="onUpdateToggle()"></ion-toggle>

**Other information: (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)**
- This appears to be the same issue as #6144 
- This only fires when the default value is true.

**Which Ionic Version? 1.x or 2.x**

2.0.0-beta.11

**Plunker that shows an example of your issue**

_Note this is the plunk of the original issue there seems to be no plunk template for beta 11 and this is not an issue in beta 10. I have attached a [sample project](https://github.com/driftyco/ionic/files/428539/TestToggle.zip) to demonstrate the problem in beta 11_

http://plnkr.co/edit/f2NSVLP1DETbkyFmpSN8?p=preview

**Run ionic info from terminal/cmd prompt: (paste output below)**

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3 Build version 7D175

**Comment by Greali** [comment] 2016-10-01 16:58
It happens to me too! :S Fix please

**Comment by manucorporat** [comment] 2016-10-08 16:34
@jvelo @Greali I can't reproduce this issue in RC0. Can you provide the TS code and markup?

**Comment by jvelo** [comment] 2016-10-08 16:37
@manucorporat Yes, I'll try and assemble a test case. FYI for me it appends only with iOS mode.

**Comment by manucorporat** [comment] 2016-10-08 17:38
#8578

**Comment by Greali** [comment] 2016-10-13 13:35
@manucorporat I have this problem in RC0 too. You can try here http://plnkr.co/edit/f2NSVLP1DETbkyFmpSN8?p=preview . 
If you set toogle: as false then the event (change) will be not triggered when the app starts, but as true will be triggered, that's not make sense. I use (ionChange) but same effect. This event must be triggered only when the state of toggle changes.

**Comment by 7freaks-otte** [comment] 2016-10-18 08:04
Same Problem:
I have an ionToggle with ngModel and an ionChange Event. Once the user clicks the toggle a request is sent to the server. If something goes wrong the toggle should be reset to its previous state. So if I set the value of ngModel in the request callback/catch-Function ionChange gets triggered again and I'm trapped in an infinite loop.

**Comment by 7freaks-otte** [comment] 2016-11-04 00:14
I wrote a wrapper component as **short-term workaround** until this is fixed.
Just in case someone is interested: 
https://gist.github.com/7freaks-otte/d46bbc2a0c5ad25d1468e3fbb8b0acff

**Comment by Greali** [comment] 2016-11-05 19:05
@7freaks-otte Thanks! I hope this problem will be fixed soon. When I have free time I will try your temporary fix :) thanks again

**Comment by abierbaum** [comment] 2016-12-09 22:44
This is happening for my application as well.

**Comment by no1done** [comment] 2017-02-01 16:26
I was having a similar issue with a pushed page triggering the ionChange event when the value was true.

`[(ngModel)]="item.enabled" (ionChange)="toggleEnabled(item.id)"`

The console log showed that _after_ page load, it ran through each item and fired the ionChange event.  

I've managed to work around this by using the angular ngModelChange option and splitting the two way binding for the model. It's not ideal but it's working.

`[ngModel]="item.enabled" (ngModelChange)="toggleEnabled(item.id)"`

This is with ionic 2.2.1

**Comment by kr105** [comment] 2017-02-05 09:59
I had the issue that @7freaks-otte described (the infinite loop) and @no1done 's changes fixed it, thanks!

**Comment by ajaygupta7** [comment] 2017-02-08 08:15
Thanks, @no1done  it's a great solution for me...!!!

**Comment by mosca90** [comment] 2017-02-16 10:28
Thanks @no1done, that problem was so annoying, hope they fix soon!

**Comment by daveywc** [comment] 2017-04-04 21:23
I had a similar issue with the ionChange event firing for a radioGroup when I initalized the page and set the bound value.  I resolved the issue by changing to use the ngModelChange binding instead.

**Comment by fdambrosio** [comment] 2017-10-18 13:26
I have the same problem with Ionic 3.7.1

**Comment by 7freaks-otte** [comment] 2017-10-19 07:13
@fdambrosio To be honest, I haven't checked yet in Ionic 3.7.1 though I'm already using it. In special cases where I need that change event on a toggle I still rely on my *workaround*. Just updated the GIST to the version that I'm currently using with 3.7.1: https://gist.github.com/7freaks-otte/d46bbc2a0c5ad25d1468e3fbb8b0acff

**Comment by cmer4** [comment] 2018-02-13 16:35
ionic 3.9.2 - we still have this issue across many components...in my app its ion-range. And the same story...

**Comment by Devqon** [comment] 2018-08-05 15:41
Still happening in Ionic V4. Sadly the workaround @no1done mentioned doesn't seem to work here though. I have a http request fired when toggling  a button, but it also listens to an open socket, so the infinite loop will be triggered.

**Comment by Devqon** [comment] 2018-08-06 15:05
For those who are struggling with this in Ionic 4, the events have changed a bit. This works in v4:
```
@Component({
    template: '<ion-toggle (ionChange)="changed($event)" [(ngModel)]="value"></ion-toggle>'
})
export class MyComponent {

    value = false;

    changed(evt) {
        // the value now is on $event.detail
        if (evt.detail.value !== this.value) {
            // do things
        }
    }
}
```

**Closed** 2018-11-28 21:46 UTC
Labels: ionitron: v3, platform:ios, toggle, v2
