### ISSUE TITLE
bug: ios11 upper sideslip return problem

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19779] opened 2019-10-29 02:02 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

On iPhone 7 IOS11.4, there's a flicker problem with sideslip return, and clicking the back button doesn't

**Expected behavior:**

Sideslip return to normal on all models

**Other information:**

![bug20191029 2019-10-29 09_56_48](https://user-images.githubusercontent.com/20217449/67731428-18ed6d00-fa33-11e9-9124-2847d13be558.gif)

**Comment by liamdebeasi** [comment] 2019-10-29 12:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19405#issuecomment-535056187.

**Closed by liamdebeasi** 2019-10-29 12:41 UTC
Labels: triage
