### ISSUE TITLE
bug: Toast appears at wrong position

### ISSUE THREAD

**Issue by lhfongaa** [ionic-team/ionic#21184] opened 2020-05-01 16:23 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

The toast component appears at wrong position. It appears at the bottom first but suddenly goes to the top position.

**Expected behavior:**

The toast should appear at the bottom until timeout properly.

**Steps to reproduce:**

**Related code:**

```
async presentExitToast() {
    const toast = await this.toastCtrl.create({
      message: 'Press once more to exit',
      duration: 2000,
      position: 'top',
      cssClass: 'exitToast',
    });
    toast.present();
  }
```
```
.exitToast {
  --background: rgba(255, 255, 255, 0.95);
  --color: rgba(0, 0, 0);
  --border-radius: 15px;
  --max-width: 200px;
  --max-height: 60px;
  text-align: center;
  position: fixed;
  top: 87.5%;
}
```

**Other information:**

Screenshot
https://im7.ezgif.com/tmp/ezgif-7-465f2d338df4.gif
or
https://gfycat.com/exhaustedappropriatelemming

**Ionic info:**

```
Ionic:
   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.4
   @angular-devkit/schematics    : 9.1.4
   @angular/cli                  : 9.1.4
   @ionic/angular-toolkit        : 2.2.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)
```

**Comment by liamdebeasi** [comment] 2020-05-01 16:51
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The enter/close animation on the toast takes the `position` property into account. Your example provides `position: 'top'`, which will position the toast at the top of the screen, but your CSS forces the toast to the bottom of the screen. The animation styles always take precedence which is why the toast appears to jump. When positioning the toast, we recommend you stick with the `position` property only.

Alternatively, if you are using `top: 87.5%` to give a different animation effect to the toast, we recommend providing a custom animation instead: https://ionicframework.com/docs/utilities/animations#overriding-ionic-component-animations.

**Closed by liamdebeasi** 2020-05-01 16:51 UTC
Labels: triage

**Comment by lhfongaa** [comment] 2020-05-01 17:17
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.
> 
> The enter/close animation on the toast takes the `position` property into account. Your example provides `position: 'top'`, which will position the toast at the top of the screen, but your CSS forces the toast to the bottom of the screen. The animation styles always take precedence which is why the toast appears to jump. When positioning the toast, we recommend you stick with the `position` property only.
> 
> Alternatively, if you are using `top: 87.5%` to give a different animation effect to the toast, we recommend providing a custom animation instead: https://ionicframework.com/docs/utilities/animations#overriding-ionic-component-animations.

but this is work in Ionic 4...

**Comment by liamdebeasi** [comment] 2020-05-01 19:27
There were several internal animation updates between Ionic 4 and Ionic 5, and this approach is no longer recommended. You are essentially telling Ionic to position the toast one way and then having your CSS work against that. Thanks!
