### ISSUE TITLE
ion-label position stacked making items in ion-item vertically aligned

### ISSUE THREAD

**Issue by Majed93** [ionic-team/ionic#16334] opened 2018-11-15 20:13 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (C:\Users\Majed\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Describe the Bug**
I've upgrade from ionic 4 beta.8 to beta.15 and now one of the issues i'm seeing is where the label position attribute seems to have broke when i set it to be stacked. The text used to be aligned horizontally but now it's vertical. I've attached my code and screenshot of the issue.

**Steps to Reproduce**
(See code)

**Related Code**
```
<ion-list>
    <ion-item-sliding>
        <ion-item>
            <ion-label>
                left
            </ion-label>
            <ion-label>
                test
                <ion-label position="stacked">stacked</ion-label>
            </ion-label>
            <ion-label>
                right
            </ion-label>
        </ion-item>
    </ion-item-sliding>
</ion-list>
```

**Expected Behavior**
All text to be aligned horizontally not vertically.

**Additional Context**
Image of issue:
![image](https://user-images.githubusercontent.com/6452588/48578728-5f28e980-e912-11e8-85f6-a7784086e626.png)

**Comment by brandyscarney** [comment] 2018-11-28 23:10
Thanks for the issue. We do not recommend using multiple `ion-label` elements inside of an `ion-item`. You may want to use one label with multiple divs or a grid inside of it to achieve what you're looking for. Please reach out on our [forums](http://forum.ionicframework.com/) if you need style help.

As for the original issue, I am not able to reproduce this in latest `4.0.0-beta.16` so I will be closing this. See this codepen: https://codepen.io/brandyscarney/pen/BGqGMM. Thanks!

**Closed by brandyscarney** 2018-11-28 23:10 UTC
Labels: triage
