### ISSUE TITLE
bug: ionicon used internal in ion-reorder, ion-searchbar

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic#20405] opened 2020-02-07 10:50 UTC
# Bug Report

**Ionic version:**

[x] **5.0.0-rc.2**

**Current behavior:**

when disabling ion-icons usage i got error while using some components that depends on it like
ion-reorder, ion-saerchbar
**GET http://localhost:8100/svg/reorder-two-sharp.svg 404 (Not Found)**

**Expected behavior:**

the component should not be depending on ion-icons
and if not, there must be a way to override that behavior to disable the icon or change it.

**Steps to reproduce:**

1. remove ion icons import and use font-awesome instead.
2. use ion-reorder component or ion-searchbar
3. you will get this error message in the console
GET http://localhost:8100/svg/reorder-two-sharp.svg 404 (Not Found)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.11 (C:\Users\sheri\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.0.0-rc.2
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 9.0.0-rc.14
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 16 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\sheri\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-02-07 14:52
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. We use certain Ionicons in internal components; however, we do not have plans to expose the ability to use different icon sets with out internal components.

Developers are able to import their own icons (such as Font Awesome) to use in their applications. You will not have to load all of Ionicons as we only load the icons you need (such as the icon for ion-searchbar or ion-reorder).

**Closed by liamdebeasi** 2020-02-07 14:52 UTC
Labels: triage

**Comment by SherifMoShalaby** [comment] 2020-02-07 15:30
so when importing the ionicons
it is only getting the svgs of the used component only ?

**Comment by liamdebeasi** [comment] 2020-02-07 15:32
Yes, that is correct. If your app is using `ion-searchbar`, it will only load the ionicons that `ion-searchbar` needs, not the entire ionicons collection.
