### ISSUE TITLE
bug: Undefined is not an object (evaluating 's.$imageEl.transition')

### ISSUE THREAD

**Issue by PanBachynskyi** [ionic-team/ionic#20327] opened 2020-01-29 11:25 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Steps to reproduce:**

Insert slider inside another slider with few images

**Related code:**

![image](https://user-images.githubusercontent.com/12164390/73352403-b5751480-4299-11ea-90bc-75af6574f3fe.png)

![image](https://user-images.githubusercontent.com/12164390/73352764-7eebc980-429a-11ea-95a9-5f513c62cbfa.png)

![image](https://user-images.githubusercontent.com/12164390/73352799-91660300-429a-11ea-9968-57426099a865.png)

Please add conditions:
- to `gesture.$imageEl` in `core/src/components/slides/swiper/swiper.bundle.js:5083`
- to `gesture.$imageEl` in `core/src/components/slides/swiper/swiper.bundle.js:5839`

**Other information:**

```
"@ionic/react": "^4.11.5",
"@ionic/react-router": "^4.11.5",
```

**Ionic info:**

```
Ionic:
   Ionic CLI : 5.4.13
Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v10.15.1
   npm    : 6.4.1
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-01-29 13:56
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20033.

**Closed by liamdebeasi** 2020-01-29 13:56 UTC
Labels: triage
