### ISSUE TITLE
bug: IonInput focus delay in mobile (ios) in 5.0.7 compared to 5.0.5 when in IonContent below keyboard

### ISSUE THREAD

**Issue by dborstelmann** [ionic-team/ionic#20922] opened 2020-03-31 07:11 UTC
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**
The delay on focus for ios keyboard animation of IonInput is significantly longer in 5.0.7 than 5.0.5.

**Expected behavior:**
Smooth transition on selecting inputs in mobile.

**Steps to reproduce:**
Open this app: https://github.com/ionic-team/ionic-react-conference-app/blob/master/package.json
Add this code to ScheduleView somewhere in the IonContent.  Make sure the input is below where the keyboard would show on mobile so just put it at the bottom of the IonContent.
```
<IonInput placeholder="test"></IonInput>
```
Open chrome dev tools and hop into mobile view.  Click on the input and watch how long it takes to focus.  Should be smooth.  Now, upgrade to 5.0.7 for ionic/core and ionic/react.  Reload app.  Check out how slow the focus is on that input.

**Comment by liamdebeasi** [comment] 2020-03-31 19:47
Thanks for the issue. The scroll assist you are referring to was broken pre v5.0.6, so I am unable to compare the behaviors using the repo provided. Do you have an example where the scroll assist was working?

**Comment by dborstelmann** [comment] 2020-04-01 02:53
Could you provide a little more information on what you mean by scroll assist and what you mean by broken?  I'm a bit new to Ionic.

I'm happy to make an example, it will just take a little work (my code is private so will have to create one).  My point was that when you click on an IonInput in the bottom half of the screnn on your iPhone when using 5.0.7 vs 5.0.5 there is a delay in focus on the element (the animation pointer-events: none style takes extra time to disappear is the only thing I can see changing in the DOM, has-focus happens as you would expect).

**Comment by liamdebeasi** [comment] 2020-04-01 13:12
When you focus an input that appears below the keyboard, Ionic Framework will automatically scroll the content so the input appears above the keyboard. The utility is called the "scroll assist". Other users have indicated that it has been broken since v4.9 (https://github.com/ionic-team/ionic/issues/19589). Is this the behavior that you are referring to?

**Comment by nncl** [comment] 2020-04-02 01:04
Hello, I'm sorry for getting into the middle of this, but I'd like to be up to date on this too and help to clarify the issue.

I'm experiencing something like this, not sure yet if it's the same thing reported above. Anyway, when focusing on the input it takes some time until it gets focused and also for the screen goes up.

Also, scroll animation isn't smooth, as you can see below:

![RPReplay-Final1585788402](https://user-images.githubusercontent.com/6740387/78199966-8f1f5100-7463-11ea-838e-db30d70e6858.gif)

Ionic info:

```
Ionic:

   Ionic CLI                     : 6.3.0
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0
```

I appreciate your help and time.

**Comment by dborstelmann** [comment] 2020-04-02 04:08
So yeah it's really two parts.  It's the delay that really bothered me.  That's what @nncl showed nicely in his screen video.  This is solved by moving from 5.0.5 to 5.0.7.

The second part is scroll assist being choppy (the screen moving up is not smooth but happens all at once at the end of the keyboard moving up).  This is broken in 5.0.5 and 5.0.7.  It works, but it's pretty annoying.

**Comment by liamdebeasi** [comment] 2020-04-02 13:26
Yeah keyboards + inputs in a webview have always been pretty annoying. I'll mark this as an enhancement since it sounds like we need to find a new way of bringing inputs into view.

**Comment by dborstelmann** [comment] 2020-04-03 04:10
That's fine with me, thanks.  However, it is a regression that will prevent me from upgrading to later versions FYI, I don't know how you guys prioritize on the Ionic side.

**Comment by mvberg** [comment] 2020-04-04 19:59
Hi all, 

another video similar to @nncl's that shows the difference in input focus speed between 5.0.5 and then 5.0.7 for iOS.

what I am seeing is that focusing input elements in 5.0.7 is actually _much_ slower for "time to input" than 5.0.5 ...

in the second recording below, you can see the time-to-input delay for the second field (Password) is much longer - additionally, when toggling between the fields, you can see the caret is slow to render in the second field as well.

this example is just a simple angular formgroup: https://gist.github.com/mvberg/449d09f8b40fe180b8cf2024818a7427

### Good:

![ionic_5_0_5](https://user-images.githubusercontent.com/649509/78459971-a25c3780-7682-11ea-9bc6-63caf1ea4858.gif)

```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : not installed
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina
```

### Bad:

![ionic_5_0_7](https://user-images.githubusercontent.com/649509/78460039-231b3380-7683-11ea-8901-1a1cecf4e9de.gif)


```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : not installed
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina
```

**Comment by 7freaks-otte** [comment] 2020-04-07 07:36
I had to stay at 5.0.6 because of important fixes in this version and modal positioning bugs in 5.0.7 but it almost takes 1sec on a real device between tap and actual focus on an input element that is not perfectly in view.

I'd really love to see this fixed soon

**Comment by 7freaks-otte** [comment] 2020-04-07 08:28
Temporary workaround that fixed it for me. Put the following line somewhere in your code:
```
window.addEventListener('keyboardDidShow', (e) => {
  window.dispatchEvent(new Event('resize')); //temporary scroll-assist fix
}, false);
```

**Comment by liamdebeasi** [comment] 2020-04-07 12:39
@7freaks-otte Good thought. I will give that a try 😄.

**Comment by liamdebeasi** [comment] 2020-04-07 14:53
Can everyone try the following dev build and let me know if it resolves the issue?

Ionic Angular:
`npm i @ionic/angular@5.1.0-dev.202004071444.acaa1d9`

Ionic React:
`npm i @ionic/react@5.1.0-dev.202004071444.acaa1d9`

I changed two things:

1. Added a listener for the `keyboardWillShow` event which typically gets fired before the `resize` event. This should improve response time for those running their app in Cordova/Capacitor.
2. Changed the fallback timer (in case neither `resize` nor `keyboardWillShow` get fired) from 1000ms to 300ms. This should improve response time for those running their app in a mobile web browser.

**Comment by mvberg** [comment] 2020-04-07 15:24
> Can everyone try the following dev build and let me know if it resolves the issue?

@liamdebeasi Thanks! So from what I can tell things are better (tested angular version), there is still the 300ms delay as you noted (notice the keyboard and the the input rendering after), but the input boxes now scroll into view ... overall it's an improvement over 5.0.7, IMO 

![ionic_5 1 dev](https://user-images.githubusercontent.com/649509/78686384-92c63400-78b8-11ea-92cc-2aa2a8c6fcf5.gif)

for comparison though, below is 5.0.5 with the workaround posted by @7freaks-otte - you can see the keyboard and input rendering are in sync

![ionic_505_workaround](https://user-images.githubusercontent.com/649509/78687450-c9507e80-78b9-11ea-9a47-1d4178f27325.gif)

**Comment by liamdebeasi** [comment] 2020-04-07 15:39
It looks like you are running this app in Mobile Safari. `keyboardDidShow` is only fired when running the app in Cordova/Capacitor, so I am not sure how the issue is fixed for you by adding the workaround.

I have a PR that will add an `ionKeyboardDidShow` event (https://github.com/ionic-team/ionic/pull/18478) when running your app in a browser. My plan is to merge this fix in, and then integrate it with the `ionKeyboardDidShow` event in the PR I linked to. This should help further improve responsiveness in Mobile Safari.

The reason why we have to scroll asynchronously is due to some weird quirk in WebKit, so we won't be able to get rid of the 300ms delay entirely (though the `ionKeyboardDidShow` event should help a lot here).

**Comment by 7freaks-otte** [comment] 2020-04-07 15:45
I just tested in Capacitor and it seems perfect to me. No 300ms in capacitor, just instant. ionKeyBoard-Event for Browsers sounds cool. Thx @liamdebeasi

**Comment by liamdebeasi** [comment] 2020-04-07 15:48
Great! Yeah the 300ms timeout should only apply to the browser for now since Capacitor will fires the `keyboardWillShow` event.

**Comment by mvberg** [comment] 2020-04-07 16:01
> keyboardDidShow is only fired when running the app in Cordova/Capacitor,

@liamdebeasi right, was unrelated, my b.

and yes, cap looks good.

**Comment by liamdebeasi** [comment] 2020-04-07 16:20
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20987 and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-04-07 16:20 UTC
Labels: package: core, type: feature request
