### ISSUE TITLE
Ion-segment: ion-segment-button doesnt work properly with *ngIf.

### ISSUE THREAD

**Issue by Kopleman** [ionic-team/ionic#11728] opened 2017-05-19 10:43 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
`ion-segment-button` doesnt work properly with `*ngIf`. If `*ngIf` statement changes over time the button is shown but cant be activated.

**Expected behavior:**
Works in the same way as without `*ngIf`.

**Steps to reproduce:**

http://plnkr.co/edit/DUk01R?p=preview

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

```

**Comment by Kopleman** [comment] 2017-05-19 10:44
The possible workaround is to use `*ngIf` with `ion-segment` itself but it doesnt look nice.

**Comment by jgw96** [comment] 2017-05-19 15:19
Thanks for using Ionic, we will look into this.

**Comment by brandyscarney** [comment] 2017-07-21 15:43
Thanks for the issue! Closing as a duplicate of #6923.

**Closed by brandyscarney** 2017-07-21 15:43 UTC
Labels: v2
