### ISSUE TITLE
[rc2] spinner stops in safari when angular change detected

### ISSUE THREAD

**Issue by MarkChrisLevy** [ionic-team/ionic#17202] opened 2019-01-22 09:05 UTC
# Bug Report

**Ionic version:**

[x] **4.0 rc2**

**Current behavior:**
In Safari (both on iOS and Mac) spinner stops spinning when data are loaded. Data are loaded from firebase + angular fire + observable. It looks like it is related with change detection in angular. Very likely it also affects other components, that are animated. I've made a video (https://drive.google.com/file/d/1dmtEEBcO3RiapbP5t0pnss7UwSGY8pQc/view?usp=sharing), that shows what is happening and you can reproduce it with the repo below. What you can't see in the video is that when safari loaded the app (spinner stopped) and you open new tab and go back the previous tab (with the app loaded) the spinner spins again. 

It was working properly in rc0, I'm not sure about rc1.

My Safari version is 12.0.2 (14606.3.4).

**Expected behavior:**
Spinner is spinning.

**Steps to reproduce:**
1. Download https://github.com/MarkChrisLevy/ionic-spinner-issue
2. npm install && npm run start
3. open safari and go to localhost:4200
4. the app should load and when the data are loaded (few seconds) you should see that spinner stopped spinning.

**Comment by mhartington** [comment] 2019-01-22 18:12
Hmm, interesting. So it appears the visual glitch doesn't actually stop the animations. If you inspect the DOM, you can see the highlights of the animation still happening.

Also, it seems to only happen when the changeDetection is triggered in the same element.
This is not limited to ion-spinner, but any keyframe animations.

**Comment by MarkChrisLevy** [comment] 2019-01-22 19:11
@mhartington Exactly! I tried with with angular 7.2.1 and 7.1.4 and no difference, so it has to be somewhere in ionic and I'm almost sure, that it didn't happen in rc0 (or I didn't notice that). Safari is killing me with those glitches... "Webkit really needs to get their shit together..." by @manucorporat 
 (https://twitter.com/manucorporat/status/1082639050509475840)

**Comment by Gargamil** [comment] 2019-05-22 17:13
Still an issue.. Having the same problem here :-(. Someone has a workaround or sth?

**Comment by malwatte** [comment] 2019-07-19 11:55
I'm having this issue as well. Added the spinner to a page. spinner freezes as soon as page navigation transition completes.
Appreciate if someone can share a workaround.

**Comment by mat1** [comment] 2019-07-29 14:05
We have the same issue. Is there a workaround?

**Comment by peterpan666** [comment] 2019-08-07 14:40
Yup same here, after debugging, it seems that navigation between tabs aren't affected by this.

As a workaround, which I'm absolutely not happy with, I navigate to other pages from the one with animation (like spinners) like they are tabs (but not really).

**Comment by midripps** [comment] 2019-10-19 16:39
Given that, will park for now.

**Comment by RamonSchmitt** [comment] 2019-10-22 14:51
<ion-spinner [paused]="paused"></ion-spinner>

public paused = true;

ionViewDidEnter() {
    this.paused = false; 
}

**Comment by Gargamil** [comment] 2019-12-13 10:37
This works for me:
```
private spinner: IonSpinner;

    @ViewChild('spinner', {read: IonSpinner}) set content(content: IonSpinner) {
        if (content && !this.spinner) {
            this.spinner = content;
            this.spinner.paused = true;
            setTimeout(() => {
                this.spinner.paused = false;
            }, 200);
        }

    }
``` 
Idea: spinner is initiated, restart it.

**Comment by liamdebeasi** [comment] 2020-02-20 14:58
Hi everyone,

I wanted to provide an update regarding this issue. We have determined that this is a bug in WebKit (https://bugs.webkit.org/show_bug.cgi?id=201048). Recently, this issue was fixed and released as part of the latest Safari Technology Preview (release 101 at the time of writing).

We do not have a timeline as to when the fix will become available for all users as that release schedule is controlled by Apple.

**Closed by liamdebeasi** 2020-02-20 14:58 UTC
Labels: package: angular

**Comment by josh-m-sharpe** [comment] 2020-02-20 17:49
@liamdebeasi Aside from the fact that there is almost always a half-decent workaround for issues such as this.... Why is it acceptable to close this issue without making note of the issue in the docs? Because what we have now is a main component of ionic that flat out doesn't work on iOS. And your response is to just shoulder shrug and close the issue?

I realize you folks have a lot of issues to deal with... but that response is quite amateur.

**Comment by liamdebeasi** [comment] 2020-02-20 20:52
We close issues here when any code that is responsible for fixing a bug has been merged (either into an Ionic repo or a 3rd party repo). In this case, code was merged into the WebKit repo that fixed this issue.

The workarounds that have been provided here should do the trick until Apple can ship this fix out. I realize the workarounds are not as ideal as having a fix right now, but we do not control WebKit's release process.

**Comment by josh-m-sharpe** [comment] 2020-02-20 20:54
@liamdebeasi If you had encountered this issue while building the feature for its initial release, would you have released the feature?

**Comment by liamdebeasi** [comment] 2020-02-20 21:04
I understand that having this unexpected behavior is frustrating, but I am not going to comment on that. I am going to lock this thread as I think the discussion regarding this issue has been resolved.

For any additional bugs or feature requests, please create a new issue. Thanks!
