### ISSUE TITLE
RTL for item-sliding api component not supporting

### ISSUE THREAD

**Issue by 95deepan** [ionic-team/ionic#12154] opened 2017-06-26 08:57 UTC
Ionic info:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.4.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
OS: Windows 10
Node Version: v6.9.2

I was trying to implement RTL  (Arabic language) in Ionic (v3.4.2),
I faced few issues in few pages, but I fixed with the help of CSS, But this API component is creating big trouble, what could be the fix for this ? 
Link for the above mentioned ionic component.
[https://ionicframework.com/docs/api/components/item/ItemSliding/](url)

**Comment by AmitMY** [comment] 2017-06-26 12:02
- Please fill the issue template 
- What is the issue with the API? what method is giving you trouble? Can you create a reproduction in plunker?

**Comment by 95deepan** [comment] 2017-07-03 01:49
- When the selected language is english...

![1](https://user-images.githubusercontent.com/22617586/27775379-f04a686e-5fbe-11e7-9eeb-b2ec1f1ab2de.png)
**********************************************************
- When the item is slided towards left...

![2](https://user-images.githubusercontent.com/22617586/27775414-68accc20-5fbf-11e7-8d4a-14cd0dd1c85e.png)
**********************************************************
- When the selected language is Arabic..

![3](https://user-images.githubusercontent.com/22617586/27775430-8dbbc1a6-5fbf-11e7-8bdd-cc8016403bc9.png)
**********************************************************
- When the item is slided towards left...

![4](https://user-images.githubusercontent.com/22617586/27775444-a72f98ec-5fbf-11e7-8844-e6d039567683.png)
**********************************************************

Is the issue clear now?

**Comment by AmitMY** [comment] 2017-07-03 06:08
Cool, thanks, we'll look into it

**Comment by iryna-kovalchuk** [comment] 2018-06-01 07:52
@AmitMY hi!

Any updates on this issue?

**Comment by iryna-kovalchuk** [comment] 2018-06-01 08:29
@AmitMY could you share the fix pls?

**Comment by AmitMY** [comment] 2018-06-01 08:42
I didn't publish as a PR, and I can't seem to find it right now, and anyway, it was a fix to the core framework.
Make sure you use the latest version of ionic 3 (because Sijav did create a partial fix that was merged, not sure to what extent it fixed it), and use directions "start" and "end" instead of "right" and "left" respectively.
Sorry I have no better news for you.

**Comment by iryna-kovalchuk** [comment] 2018-06-01 08:43
Thanks :)

**Closed** 2018-11-01 19:51 UTC
Labels: ionitron: v3, rtl, v3
