### ISSUE TITLE
Help,In an ionic2 ios App,how to open another ios app?

### ISSUE THREAD

**Issue by HaHaHaHaHaHaHaaaaaa** [ionic-team/ionic#12445] opened 2017-07-23 10:03 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by wbhob** [comment] 2017-07-24 01:47
Thank you for opening an issue with Ionic (fyi, I am not officially an Ionic team member... yet...)! However, this seems a support request, not a bug report or feature request. Please close this issue and either ask your question on the Ionic forums (https://forum.ionicframework.com/) or on the Ionic Worldwide Slack (http://ionicworldwide.herokuapp.com/).

**Comment by HaHaHaHaHaHaHaaaaaa** [comment] 2017-07-24 02:32
thanks

**Closed** 2017-07-24 02:31 UTC
