### ISSUE TITLE
bug: lifecycles methods not fired

### ISSUE THREAD

**Issue by vahid18u** [ionic-team/ionic#20797] opened 2020-03-17 12:11 UTC
Hello guys. I tried to use react lifecycles both through Class component and function component but none of methods are fired.
I’m using @ionic/react version 5.0.0

class component example : 
```
import React from "react";
 import {
  withIonLifeCycle
} from "@ionic/react";

class NewProduct extends React.Component {
  ionViewWillEnter() {
    console.log("ionViewWillEnter event fired");
  }
 render(){
     return(<div></div>);
 }
}
export default withIonLifeCycle(NewProduct);
```

**Comment by liamdebeasi** [comment] 2020-03-17 13:24
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. In order for Ionic Lifecycle events to work, you need to use the `IonPage` component, otherwise the components are not seen as Ionic pages.

Your render function should look like this: 

```jsx
import { IonPage } from '@ionic/react';

...

render() {
 return (
    <IonPage>
      <div></div>
    </IonPage>
  )
}
```

**Closed by liamdebeasi** 2020-03-17 13:24 UTC
Labels: triage
