### ISSUE TITLE
Change dayValues and yearValues for another languages like Persian, Arabic

### ISSUE THREAD

**Issue by shahramSo** [ionic-team/ionic#14222] opened 2018-03-23 15:08 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

**Current behavior:**

I define dayValues as Arabic, Persian numbers to display the days as Arabic or Perisan as follows:
dayValues = ["۰۱","۰۲","۰۳","۰۴","۰۵","۰۶","۰۷","۰۸","۰۹","۱۰","۱۱","۱۲","۱۳","۱۴","۱۵","۱۶","۱۷","۱۸","۱۹","۲۰","۲۱","۲۲","۲۳","۲۴","۲۵","۲۶","۲۷","۲۸","۲۹","۳۰","۳۱"];

**Expected behavior:**

I expected the day numbers is displayed as Persian numbers. but always get an error message:
Invalid "dayValues". Must be an array of numbers, or a comma separated string of numbers.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
dayValues = ["۰۱","۰۲","۰۳","۰۴","۰۵","۰۶","۰۷","۰۸","۰۹","۱۰","۱۱","۱۲","۱۳","۱۴","۱۵","۱۶","۱۷","۱۸","۱۹","۲۰","۲۱","۲۲","۲۳","۲۴","۲۵","۲۶","۲۷","۲۸","۲۹","۳۰","۳۱"];
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Invalid "dayValues". Must be an array of numbers, or a comma separated string of numbers.
```
Is there any way to show day's and years numbers to other than Latin languages like Arabic, Persian?
Thanks

**Comment by liamdebeasi** [comment] 2019-11-11 16:58
Thanks for the issue. I am going to close this as this is not a bug in Ionic. To display day values in different languages, you need to be using `dayNames` or `dayShortNames`. The `dayValues` property is to limit which days are shown in the datetime. The `dayNames` and `dayShortNames` properties are responsible for the format in which the days are displayed. For more information see: https://ionicframework.com/docs/api/datetime#properties

**Closed by liamdebeasi** 2019-11-11 16:58 UTC
Labels: package: core, type: feature request
