### ISSUE TITLE
bug: IonTextarea with autoGrow={true} has 0 height when in a modal with an IonButton 

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic#21177] opened 2020-04-30 23:49 UTC
# Bug Report

**Ionic version:**
[x] **5.1.0-react**

**Current behavior:**
Having a modal with an IonTextarea as well as an IonButton makes the IonTextarea have a height of 0 when autoGrow is enabled.

**Expected behavior:**
The IonTextarea should have as many rows as the "rows" prop indicates, and then grow from there.

**Steps to reproduce:**
Just have an IonTextarea with autoGrow and an IonButton in the same modal.

**Related code:**
StackBlitz: https://stackblitz.com/edit/ionic-v5-1-0-textgrow
 
**Other information:**
This was an issue with 4.11.8 and supposedly autoGrow was fixed with 5.1.0 but it has not fixed this problem. 

Previous issue: https://github.com/ionic-team/ionic/issues/20167

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.6.0 (/Users/evan/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.1.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.10.1 (/usr/local/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-05-01 13:36
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20167.

**Closed by liamdebeasi** 2020-05-01 13:36 UTC
Labels: triage
