### ISSUE TITLE
bug: ion-select selected option is not rendered when using observables

### ISSUE THREAD

**Issue by vially** [ionic-team/ionic#18288] opened 2019-05-16 13:56 UTC
# Bug Report

**Ionic version:**

[x] **4.4.0**

**Current behavior:**

Building the `<ion-select-option>` list from an (async) observable makes the `<ion-select>` component not pick up the selected option. 

**Expected behavior:**

`<ion-select>` should properly display the selected option when using observables to build the options list.

**Steps to reproduce:**

1. Clone and run: https://github.com/vially/ionic-bugs-demos/tree/master/ion-select-bug
1. Open the app in the browser and notice how the `Broken ion-select` selection is empty while it should be "Foo".

![localhost_4200_tabs_tab1 (1)](https://user-images.githubusercontent.com/433598/57860138-92caca80-77f4-11e9-95c5-31b70cdcaa06.png)

**Related code:**

Source code demo: [ion-select-bug-demo](https://github.com/vially/ionic-bugs-demos/tree/master/ion-select-bug)

Sample code that demonstrates the bug:

```ts
const demoOptions = [
  { label: 'Foo', selected: true },
  { label: 'Bar', selected: false }
]

this.options$ = of(demoOptions).pipe(
  delay(500),
  startWith([])
)
```

```html
<ion-select>
  <ion-select-option
    *ngFor="let option of options$ | async"
    [selected]="option.selected"
  >
    {{option.label}}
  </ion-select-option>
</ion-select>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/vially/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.3 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 5.0
```

**Comment by liamdebeasi** [comment] 2019-05-16 14:23
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17344.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-16 14:23 UTC
Labels: triage
