### ISSUE TITLE
Repo is now private?

### ISSUE THREAD

**Issue by DovahBrownies** [ionic-team/ionic#14207] opened 2018-03-21 12:49 UTC
Not really an issue but more of a 'concern' (I guess is the right word?).
I've noticed recently that the repository, that holds the source code for the demos shown on the [Ionic Components page](https://ionicframework.com/docs/api/components), has been made private because I'm being met with a 404 when trying to access them.
Is there any reason for this? Will the repo be public again?

**Comment by perrygovier** [comment] 2018-03-21 15:19
Thanks, I'm working on this today. Closing as a dupe of #1335

**Closed by perrygovier** 2018-03-21 15:19 UTC
Labels: triage
