### ISSUE TITLE
bug: ionic cordova build android with prod flag fails unexpectedly

### ISSUE THREAD

**Issue by LaurentiuGabriel** [ionic-team/ionic#18283] opened 2019-05-15 17:24 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

ionic 4.10.3

**Current behavior:**

When running ionic cordova build android --prod on my project it fails unexpectedly with the following issue:
typescript error
Unexpected value 'null' declared by the module 'AppModule in app/app.module.ts'
The following is the complete log with --verbose flag:

ionic cordova build android --prod --verbose
ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
ionic:lib CLI global options: { _: [ 'cordova', 'build', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, prod: true, project: null, '--': [] } +11ms
ionic:lib:project Project type from config: Ionic 2/3 (ionic-angular) +0ms
ionic:lib:project Project details: { configPath: '/media/laur/project/ionic.config.json', errors: [], context: 'app', type: 'ionic-angular' } +1ms
ionic Context: { binPath: '/home/laur/.config/versions/node/v8.3.0/lib/node_modules/ionic/bin/ionic', libPath: '/home/laur/.config/versions/node/v8.3.0/lib/node_modules/ionic', execPath: '/media/laur/project/', version: '4.10.3' } +0ms
ionic:lib:integrations:cordova:config Using config.xml: /media/laur/project/config.xml +0ms
ionic:lib:telemetry Sending telemetry for command: 'ionic cordova build' [ 'android', '--prod', '--verbose', '--interactive', '--color' ] +0ms
ionic:lib:hooks Looking for ionic:build:before npm script. +0ms
ionic:lib:project:ionic-angular:build Looking for ionic:build npm script. +0ms
ionic:lib:project:ionic-angular:build Found ionic:build, but it is the default. Not running. +7ms

ionic-app-scripts build --prod --target cordova --platform android
[22:09:26] ionic-app-scripts 3.2.1
[22:09:26] build prod started ...
[22:09:26] clean started ...
[22:09:26] clean finished in 3 ms
[22:09:26] copy started ...
[22:09:27] deeplinks started ...
[22:09:27] deeplinks finished in 270 ms
[22:09:27] ngc started ...
[22:09:41] typescript error
Unexpected value 'null' declared by the module 'AppModule

When running the same command using --release flag, it works and it generates the .apk file.

**Expected behavior:**

I expect to get the .apk file after running the command.
The .apk isn't generated as it is when using the release flag. Also, no detailed information is displayed about the issue even when using the verbose flag. I have found some info on some stackoverflow threads about using ionic serve before running this command. I tried this as well but with no luck.

**Steps to reproduce:**

Install all dependencies from npm, Ionic, cordova and attempt to perform the following command:

Define the following app.module file:

Here is the app.module.ts file that I use:

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { HttpModule, JsonpModule } from '@angular/http';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { HelpPage } from "../pages/help/help";
import { IngredientsPage } from '../pages/ingredients/ingredients';
import RecipesPage from '../pages/recipes/recipes';
import { EdamamApiProvider } from '../providers/edamam-api/edamam-api';
import { File } from '@ionic-native/file';
import { IonicStorageModule } from '@ionic/storage';
import { PreferencesPage } from '../pages/preferences/preferences';
import { SQLite } from '@ionic-native/sqlite';
import { NutritionCalculatorComponent } from '../components/nutrition-calculator/nutrition-calculator';
import { RecipesSingleton } from '../pages/recipes/recipesSingleton';

@NgModule({
declarations: [
MyApp,
HomePage,
IngredientsPage,
RecipesPage,
HelpPage,
PreferencesPage,
NutritionCalculatorComponent
],
imports: [
BrowserModule,
IonicModule.forRoot(MyApp),
HttpModule,
JsonpModule,
IonicStorageModule.forRoot()
],
bootstrap: [IonicApp],
entryComponents: [
MyApp,
HomePage,
IngredientsPage,
RecipesPage,
HelpPage,
PreferencesPage
],
providers: [
StatusBar,
SplashScreen,
{provide: ErrorHandler, useClass: IonicErrorHandler},
EdamamApiProvider,
File,
{provide: ErrorHandler, useClass: IonicErrorHandler},
SQLite,
RecipesSingleton
]
})
export class AppModule {}

ionic cordova build android --prod --verbose

In my case, it crashes with the following error:

[22:09:41] typescript error
Unexpected value 'null' declared by the module 'AppModule

Though it doesn't have any null values and it works with the release flag. 

**Related code:**

<!-- If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

A sample application via GitHub: https://github.com/GrepDev/kitchen-mobile

Version information
I'm using ionic cli 4.10.3, android studio 24.4, cordova 8.0.0, Ubuntu machine v.18.04.

**Comment by liamdebeasi** [comment] 2019-05-15 18:07
Hi there,

Thanks for the issue. I am going to close this as this is more of a support question.

This error is usually caused by a typo in `app.module.ts` (an extra comma, a misspelled component name) or an invalid import (i.e. doing `import { MyComponent } from '../my-component'` when the component does not exist at that location).

Using `--prod` will cause the Angular CLI to run some extra build steps when compiling your application, so that may be why you only see this error when using the `--prod` flag.

For further help debugging your application, feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Closed by liamdebeasi** 2019-05-15 18:07 UTC
Labels: triage
