### ISSUE TITLE
Setting a tabs page as root does not load the first root page

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionic#12625] opened 2017-08-09 11:19 UTC
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Opening a tabs page by setting it as the root page **does not** open the first tabs page.
It only replaces the tabs bar.

**Expected behavior:**
Opening a tabs page by setting it as the root page will open the selected tabs page and also load its first tab page.

In other words:
When clicking on a main menu button, I expect not only the tabs bar to change but also to load the first tab from that tab bar.

**Steps to reproduce:**
1. Open a terminal.
1. `git clone https://github.com/Eraldo/tabsIssue.git`
1. cd tabsIssue
1. `ionic serve`
1. Press `ENTER` to install the dependencies.
=> Wait until install finishes and your browser opens `http://localhost:8100/`
1. Click on "Toggle Menu" button.
1. Click on "Tabs2" button.
=> url is now: `http://localhost:8100/#/tabs2/first2/first2`
1. Click on "Menu" button (three lines top left corner).
1. Click on "Tabs" button.
=> url is now: `http://localhost:8100/#/tabs/first/first2`
The page from the previous tabs page (`First2Page`) is still open!
I expected `FirstPage` to be open.
In other words I would have expected `http://localhost:8100/#/tabs/first/first`

**Related code:**
https://github.com/Eraldo/tabsIssue

**Other information:**
I have also created a video demoing the issue in another project:
![tabsissue 2018-08-02](https://user-images.githubusercontent.com/73378/29118665-344b2ccc-7d03-11e7-86de-a4f7416e923c.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/eraldo/inbox/temp/tabsIssue/node_modules)

    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.2.1
    OS                : macOS Sierra
    Xcode             : Xcode 8.0 Build version 8A218a 
    npm               : 5.3.0 
```

**Comment by jgw96** [comment] 2017-08-09 14:25
Thanks for opening an issue with us, we will look into this.

**Comment by shajeeck** [comment] 2017-08-09 14:32
I am experiencing same issue, it happens when navigating from one page with tabs to another page with tabs

**Comment by DavidStrausz** [comment] 2017-08-09 18:30
The issue occurs since Ionic 3.6.0 (nav url refactoring) for me. In my case it looks like this:
`<div [ngSwitch]="isLoggedIn">
  <ion-tabs
    selectedIndex="1"
    *ngSwitchDefault>
    <ion-tab [root]="page1" tabTitle="page1"></ion-tab>
    <ion-tab [root]="page2" tabTitle="page2"></ion-tab>
  </ion-tabs>

  <ion-tabs
    selectedIndex="1"
    *ngSwitchCase="true">
    <ion-tab [root]="page1" tabTitle="page1"></ion-tab>
    <ion-tab [root]="page3" tabTitle="page3"></ion-tab>
    <ion-tab [root]="page4" tabTitle="page4"></ion-tab>
  </ion-tabs>
</div>`

When the ion-tabs are switched by the "isLoggedIn" variable the selected tab (in this case at index 1) will not get pushed a new root (page3 in this case), page2 will stay on the nav-stack.

**Comment by ajonp** [comment] 2017-08-12 18:06
@jgw96 I tried this also programatically with 
```
ionViewDidEnter() {
  this.tabRef.select(2);
 }

}
```
Still does not load view.

**Comment by Eraldo** [comment] 2017-08-13 00:27
Doing it twice works. (Workaround)

On Aug 12, 2017 8:07 PM, "Alex Patterson" <notifications@github.com> wrote:

@jgw96 <https://github.com/jgw96> I tried this also programatically with

ionViewDidEnter() {
  this.tabRef.select(2);
 }

}

Still does not load view.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ionic-team/ionic/issues/12625#issuecomment-321996821>,
or mute the thread

**Comment by ajonp** [comment] 2017-08-13 15:45
@Eraldo this will work for my app in Dev, but obviously I just lost all deeplink capability, so def need to get this fixed ;)

**Comment by Eraldo** [comment] 2017-08-13 17:42
Yes @ajonp, I was just sharing it since I use it as a **workaround** until it is fixed. :)

**Comment by shajeeck** [comment] 2017-08-26 11:21
there are now bunch of issues referring to similar problems with tabs, here are some I could find

- #12697

- #12684

- #12687

- #12740

- #12680

- #12666

- #12639

- #12631

Though we understand that bug resolving is currently paused until v4 release, this issue seems very annoying and core functionality for any ionic app design with tabs. And knowing that there is no timeline for v4 release is a bit scarier

@jgw96 
Hope ionic team is working on resolving this issue with next release of this awesome framework.

Did anyone find a promising work around for this issue as a temporary fix ?

**Comment by Eraldo** [comment] 2017-09-22 11:58
I would appreciate someone from the team providing a status update. :)

**Comment by danbucholtz** [comment] 2017-09-29 02:16
Hi,

We'll take a look at this ASAP.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2017-10-06 03:42
Hello,

This issue is fixed. Can you try it out and let me know if the issue still exists?

```
npm install ionic-angular@3.7.1-201710060319
```

Thanks,
Dan

**Closed by danbucholtz** 2017-10-06 03:42 UTC
Labels: v3

**Comment by DavidStrausz** [comment] 2017-10-06 09:19
Hi @danbucholtz , thanks for looking into it. At least in [my case here](https://github.com/ionic-team/ionic/issues/12625#issuecomment-321342387) the issue is still present.

**Comment by ajonp** [comment] 2017-10-12 10:16
@danbucholtz I can confirm this has fixed the issue. Huge win!!
```
cli packages: (/Users/gap4/Documents/WEB/drinkpublic.com/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1-201710060319

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    Node              : v6.11.4
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : pro
```

**Comment by machadoapoena** [comment] 2017-10-17 18:42
still not working on 3.13.1`    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1
    Node              : v6.11.3
    npm               : 5.4.2
    OS:   Windows 10

Misc:

    backend : legacy

**Comment by kensodemann** [comment] 2017-10-18 17:29
@machadoapoena - based on your ionic info, you are not using the nightly build that @danbucholtz [references above](https://github.com/ionic-team/ionic/issues/12625#issuecomment-334650345).

```
npm install ionic-angular@3.7.1-201710060319
```

Also, you reference `3.13.1` in your comment, but that is the version of the CLI and not of `ionic-angular` (this project). The naming gets confusing, but the CLI version should not affect this issue (I hope... lol)

**Comment by DavidStrausz** [comment] 2017-10-18 17:44
@kensodemann As you are already re-checking this issue, did you also check the issue with my use-case wich I referenced in my [comment](https://github.com/ionic-team/ionic/issues/12625#issuecomment-334703614).

**Comment by kensodemann** [comment] 2017-10-18 17:47
@DavidStrausz - actually, not really re-checking this issue so much as trying to see if some other issue is a duplicate of this that could be fixed via the not-yet-released nightly. I'll have a quick look when I get a chance, though.

**Comment by kensodemann** [comment] 2017-10-18 18:00
@DavidStrausz - do you have a GitHub repo with a sample app for this?

Given the use of the ```ngSwitch``` this may be different enough from the original issue to justify its own issue.

**Comment by DavidStrausz** [comment] 2017-10-18 18:07
@kensodemann I'll try to create a minimal example and let you know here!

**Comment by DavidStrausz** [comment] 2017-10-19 13:45
@kensodemann You can find the example repository [here](https://github.com/DavidStrausz/lazy-tab-roots) (it is based on the ionic2-starter-tabs upgraded to the ionic-angular and ionic-app-scripts nightly version). `npm install`, `ionic serve` and then watch. The tabs are switched every 7.5 seconds.

While putting the repo together I noticed that the underlying problem is the naming of the ts-class (and module) of the Tabs component. Naming it `tabs.ts` works just fine but re-naming it to e.g. `TabsContainer.ts` creates the problem. I guess this is because the name is used for generating the DeepLink config/the URL.

With `tabs.ts` after switching the tabs for the first time the the URL is:
`http://localhost:8100/#/tabs/contact/contact`
which is correct.

With `TabsContainer.ts` after switching the tabs for the first time the URL is:
`http://localhost:8100/#/TabsContainer/contact/about`
which is incorrect.

**Comment by kensodemann** [comment] 2017-10-19 19:14
You can work around this via the following code in `TabsContainer.ts`:

```ts
@IonicPage({ priority: 'high', segment: 'tabs' })
```

This bug is sufficiently different from the originally reported issue to justify its own issue if you would like to open one.

**Comment by AlessandroSchneiderSignUP** [comment] 2017-11-02 17:59
I get the same error when I use:
{ component: TabsPage, name:'TabsPages', segment:'tabs'},

But I have to use the segment "tabs-page" to make the Browser-Back-Button work correctly.

How can I fix this?

**Comment by ajonp** [comment] 2017-11-03 09:23
@danbucholtz 3.7.1-201710201922 makes this work...3.8.0 will not work.

**Comment by Eraldo** [comment] 2017-11-06 09:33
I can confirm that it works with the 3.7 nightly build.
I am using 3.8 as well and there it does not work as you mentioned.
Thank you @ajonp for pointing that out.

**Comment by christian-hager** [comment] 2017-11-08 16:13
3.7 nightly builds works for me too. Any Info on when this will be included in a regular release?

**Comment by koenoe** [comment] 2017-11-28 08:41
I'm using 3.9.2 and this is still an issue for me.

**Comment by Eraldo** [comment] 2017-12-09 01:23
Same here.. still an issue!
Please reopen this issue. ;)

**Comment by hqp6684** [comment] 2017-12-22 09:24
@Eraldo I tried this and it seems to work https://github.com/ionic-team/ionic/issues/12697#issuecomment-332970073

**Comment by Eraldo** [comment] 2017-12-26 03:06
Thank you @hqp6684 I have not tried if it works for me too because I switched to `ionic2-super-tabs` in the meantime. If I am running into issues there, I will try to switch back. :)

**Comment by jasonz1987** [comment] 2018-01-01 08:22
i used super tabs ,and it's not work for me too..

**Comment by christian-hager** [comment] 2018-01-31 10:10
Is there any info yet on when this will be included in a regular release?

**Comment by gatsinski** [comment] 2018-02-13 09:11
I can confirm that the workaround provided by @kensodemann works for me. I tried switching between different versions of `ionic-angular` mentioned here and at other places without any result. The only thing that fixed the problem for now is 

`@IonicPage({ priority: 'high', segment: 'tabs' })`

In my case it seems to work as expected but it's too early to say for sure. Thanks.

**Comment by ajonp** [comment] 2018-02-22 03:23
I want to upgrade to 3.9.2, but it still breaks tabs, I am sitting at 3.7.1-201710201922 currently.

I am using @gatsinski / @kensodemann solution with 
```
@IonicPage({
  priority: 'high'
})
```
I can confirm this works so far in my testing.

**Comment by HiranHabiff** [comment] 2018-03-04 06:12
Good night, a solution I found to insert the code in TabsPage:

```
	ionViewWillEnter() {
		this.tabRef.select(0);
	}

	ionViewDidEnter() {
		this.tabRef.select(0);
	}
```
Full version in my case

```
import { Component,ViewChild } from '@angular/core';
import { IonicPage, NavController, Tabs } from 'ionic-angular';

@IonicPage({
  priority: 'high', segment: 'tab'
})
@Component({
  selector: 'page-tab',
  templateUrl: 'tab.html'
})
export class TabPage {

	@ViewChild('myTab') tabRef: Tabs;

	TabPage1Root = 'TabPage1Page'
	TabPage2Root = 'TabPage2Page'
	TabPage3Root = 'TabPage3Page'


	constructor(public navCtrl: NavController) {

	}

	ionViewWillEnter() {
		this.tabRef.select(0);
	}

	ionViewDidEnter() {
		this.tabRef.select(0);
	}


}

```

**Comment by christian-hager** [comment] 2018-03-09 08:00
Is there yet any Info on when this will integrated in a regular release? The forementioned workaround only seem to work for tabs but as I stated earlier this is also an issue when using Splitview.

**Comment by iget-master** [comment] 2018-03-10 21:14
@HiranHabiff Thanks for your workaround, it solved my issue.

**Comment by HiranHabiff** [comment] 2018-03-14 18:13
@christian-hager I do not know how to report correctly, I'm not a specialist, I broke my mind and I found this temporary solution ...

**Comment by crebuh** [comment] 2018-04-06 09:13
Same issue for me for lazy loaded pages. The fix from @HiranHabiff unfortunatley is not working :(

**Comment by marcosseki** [comment] 2018-04-13 13:57
+1 Same problema with the latest version. The fix will be available soon?

**Comment by Moae** [comment] 2018-04-24 09:53
+1 Same problem, I tried all the solutions proposed but nothing, when from a side menu i navigate to the new page with tabs (from another with tabs) it loads the tabs but the page remain the previous one.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.1
    Node              : v6.11.4
    npm               : 3.10.10 
    OS                : Linux 4.13
```

**Comment by mraible** [comment] 2018-04-26 13:45
I was able to get deep-linking working in my tabs-based app by using `[selectedIndex]="getSelectedIndex()"`:

```html
<ion-tabs [selectedIndex]="getSelectedIndex()">
```

In my `TabsPage`, I have the `getSelectedIndex()` method:

```ts
export class TabsPage {
  tab1Root: any = Tab1Root;
  tab2Root: any = Tab2Root;
  tab3Root: any = Tab3Root;

  tab1Title = " ";
  tab2Title = " ";
  tab3Title = " ";

  constructor(public navCtrl: NavController, public translateService: TranslateService) {
    translateService.get(['TAB1_TITLE', 'TAB2_TITLE', 'TAB3_TITLE']).subscribe(values => {
      this.tab1Title = values['TAB1_TITLE'];
      this.tab2Title = values['TAB2_TITLE'];
      this.tab3Title = values['TAB3_TITLE'];
    });
  }

  getSelectedIndex() {
    let page = location.hash.substring(location.hash.lastIndexOf('/') + 1);
    page = page.charAt(0).toUpperCase() + page.substring(1) + 'Page';
    const tabs = [this.tab1Root, this.tab2Root, this.tab3Root];
    const index = tabs.indexOf(page);
    const entitiesTab = tabs.indexOf(this.tab2Root);
    if (location.hash.includes('entities')) {
      return entitiesTab;
    } else if (index > -1) {
      return index;
    }
  }
}
```

The special behavior on the `entities` tab is so I can do deep linking. My `EntityPage` has the following that facilitates this:

```ts
ionViewWillLoad() {
  let page = location.hash.substring(location.hash.lastIndexOf('/') + 1);
  let urlParts = location.hash.split('/');
  page = page.charAt(0).toUpperCase() + page.substring(1) + 'Page';
  let destination;
  this.entities.forEach(entity => {
    if (entity.component === page) {
      destination = entity.component;
    }
  });
  if (destination) {
    this.nav.push(destination);
  } else if (urlParts.length === 5) {
    // convert from URL to page name: foo-detail to FooDetailPage
    const detailPage = this.urlToTitleCase(urlParts[3]) + 'Page';
    this.nav.push(detailPage, {id: urlParts[4]})
  }
}

private urlToTitleCase(str) {
  return str.replace(/(-|^)([^-]?)/g, (_, prep, letter) => {
    return (prep && '') + letter.toUpperCase();
  });
}
```

All this code is contained in the [ionic-jhipster-starter](https://github.com/oktadeveloper/ionic-jhipster-starter).

**Comment by stvmachine** [comment] 2018-06-07 05:40
Using 3.9.2 and still don't works

+1

**Comment by stephan-strate** [comment] 2018-06-18 10:36
Did someone find a proper solution for this problem? 
The solution from @HiranHabiff works, but causes some performance issues. Some pages will be called 3 times in a row, which causes weird laggs.

**Comment by Eraldo** [comment] 2018-07-21 03:16
I am also still struggling with this issue. :|
