### ISSUE TITLE
bug: ion-item not highlight invalid item while calling angular formGroup.markAllAsTouched()

### ISSUE THREAD

**Issue by livelazily** [ionic-team/ionic#21462] opened 2020-06-09 09:16 UTC
# Bug Report

**Ionic version:**
5.1.1

**Current behavior:**
`ion-item` not highlight invalid item while angular `formGroup.markAllAsTouched()` mark all invalid , not touched control as touched.

**Expected behavior:**
`ion-item` should higlight those invalid items

**Steps to reproduce:**
Open sample stackblitz in below and wait the preview window finished, click the `SUBMIT` button.

**Related code:**
https://stackblitz.com/edit/ionic-form-test

**Other information:**
If you dont' click the `SUBMIT` button, and just click the requreired field and leave, the invalid higlight is working as normal

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.0 (/Users/livelazily/.local/nvm/versions/node/v12.18.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2020-06-09 13:25
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20650.

**Closed by liamdebeasi** 2020-06-09 13:25 UTC
Labels: triage
