### ISSUE TITLE
[Ionic 4] - no indication for selected option (RTL)

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic#16197] opened 2018-11-02 12:56 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (C:\Users\eelnasi\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : not available

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10

```

**Describe the Bug**
![image](https://user-images.githubusercontent.com/6171883/47916557-3c78e880-deaf-11e8-8e07-57cea8f5c74e.png)
.

**Steps to Reproduce**
use ion-select in RTL

**Related Code**
<ion-item>
              <ion-label>RANGE</ion-label>
              <ion-select [(ngModel)]="confession.ageRange" name="ageRange" required >
                <ion-select-option value="18-22">18-22</ion-select-option>
                <ion-select-option value="22-30">22-30</ion-select-option>
                <ion-select-option value="30+">30+</ion-select-option>
              </ion-select>
            </ion-item>

**Expected Behavior**
selected option should be marked

**Comment by paulstelzer** [comment] 2018-12-07 11:11
Thanks for your issue! Could you please check if this is still an issue in `beta.17`? That would be very nice :)

I know that are many issues related to RTL

**Comment by mohamedsharaf** [comment] 2018-12-28 15:50
i can confirm it still exists in rc0 and a lot of rtl problems

**Comment by abennouna** [comment] 2019-01-09 14:32
Please consider keeping only this issue or the newer #16295

**Comment by brandyscarney** [comment] 2019-01-11 16:39
Closing as a duplicate of #16295, please keep track on that issue. Thank you!

**Closed by brandyscarney** 2019-01-11 16:39 UTC
Labels: needs: investigation, package: core
