### ISSUE TITLE
bug: input focus on label click?

### ISSUE THREAD

**Issue by Sjoerrdd** [ionic-team/ionic#18582] opened 2019-06-20 13:31 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When I tap on the label of an input, it doesn't focus on the input

**Expected behavior:**

When I tap on the label of an input, it has to focus on the input

**Steps to reproduce:**

Create a form, add an label and input in an `ion-item` tag

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.9.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment] 2019-06-21 13:52
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17764.

**Closed by liamdebeasi** 2019-06-21 13:52 UTC
Labels: triage
