### ISSUE TITLE
[Ionic v4] ion-datetime cannot change month when max is set

### ISSUE THREAD

**Issue by ingljo** [ionic-team/ionic#17790] opened 2019-03-15 08:22 UTC
# Bug Report

**Ionic version:**

[x] 4.1.2-dev.201903141948.7d01207

**Current behavior:**

I have ion-datetime with max set to now.

When I change year from 2019 to 2018, it is not possible to select month to all months in 2018. The months are restricted to maxDate month.
Also, the current month (Mar) for 2018 has restricted days to 15 (today) and it is not possible to set HH:mm later than now for 2018.

Workaround is to click "Done", then pick date again. It is then possible to select all months for 2018.

**Expected behavior:**

Expected is to be able to select all months, and all days for current month when I change year to previous year.

**Steps to reproduce:**

**Related code:**
`<ion-item>
      <ion-label>Date</ion-label>
      <ion-datetime display-format="D. MMM, YYYY HH:mm" [max]="maxDate"></ion-datetime>
    </ion-item>`

`ngOnInit(): void {
    this.maxDate = new Date().toISOString();
  }`

Link to github repo:
[https://github.com/ingljo/ion-datetime](https://github.com/ingljo/ion-datetime)

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\ingvar.ljosland\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2-dev.201903141948.7d01207
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0

System:

   NodeJS : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10
```
** Screenshots **
![alt text](https://github.com/ingljo/ion-datetime/blob/master/screenshot/localhost_8101_home(iPhone%20X)%20(1).png?raw=true "When changed year")

**Comment by liamdebeasi** [comment] 2019-03-15 12:31
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15452. Please note that this issue has been closed and consolidated into a main "datetime bugs" thread here: https://github.com/ionic-team/ionic/issues/16630

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-03-15 12:31 UTC
Labels: triage
