### ISSUE TITLE
Ionic 5.0.0 IonSlides SlidesPerView bug

### ISSUE THREAD

**Issue by danieljameswilliams** [ionic-team/ionic#20451] opened 2020-02-12 12:53 UTC
Hello, When navigating to a page with IonSlides, slidesPerView is rendered as 1, but if reloaded it is 2.3 as intended.

I think it's a bug.

```
Ionic:

   Ionic CLI                     : 6.1.0
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

```
public slideOpts = {
    effect: 'flip',
    direction: 'horizontal',
    slidesPerView: '2.3',
    centeredSlides: false,
    loop: false
};
```

```
<ion-slides pager="false" [options]="slideOpts">
    <ion-slide>
    </ion-slide>
</ion-slides>
```

![image](https://user-images.githubusercontent.com/4445229/74337175-16bfdc00-4da0-11ea-8bf7-4a01cc663b0c.png)

![image](https://user-images.githubusercontent.com/4445229/74337253-39ea8b80-4da0-11ea-9e90-e82551e7ce7c.png)

**Comment by liamdebeasi** [comment] 2020-02-12 14:04
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by boengli** [comment] 2020-02-15 10:56
I'm having the same problem, see: [stackoverflow](https://stackoverflow.com/questions/60231278/ion-slides-wont-work-before-reloading-the-page)

**Comment by liamdebeasi** [comment] 2020-02-18 17:22
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20356.

**Closed by liamdebeasi** 2020-02-18 17:22 UTC
Labels: triage
