### ISSUE TITLE
feat: Expose Swiper's updateAutoHeight() method for autoHeight enabled slides

### ISSUE THREAD

**Issue by daem0ndev** [ionic-team/ionic#16711] opened 2018-12-12 17:22 UTC
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Current behavior:**
Currently the `ion-slides` component allows the ability to pass in any valid Swiper options, one of which is the `autoHeight` option. When set to true this will nicely adjust the height of the slides to match the height of the active slide. 

The issue is that if your slides contain data that could change, like waiting for a network request before loading items, the height of the active slide can change but the swiper will not update the height. There is a method available on the Swiper instance `updateAutoHeight()` that will update the height correctly after the fact.

**Expected behavior:**
The updateAutoHeight() method should be exposed on ion-slides component so a developer can trigger it after view changes to the active slide.

**Steps to reproduce:**
Create an ion-slides with 2 slides and set autoHeight to true. Have slide 1 contain nothing but a spinner and then after a set timeout switch to a list of 10 items. The height of the container will not update and will be whatever the height of the spinner was.

**Related code:**

```
<ion-slides [options]="{ autoHeight: true }">
...
</ion-slides>
```

**Other information:**

Swiper API: http://idangero.us/swiper/api/

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/daem0n/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.11
   @angular-devkit/build-angular : 0.8.3
   @angular-devkit/schematics    : 0.8.3
   @angular/cli                  : 6.2.3
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.1-nightly.2018.9.20.f8ed27c6 (cordova-lib@9.0.0-nightly.2018.9.20.63b26e63)
   Cordova Platforms     : Warning: using prerelease version 8.0.1-nightly.2018.9.20.f8ed27c6 (cordova-lib@9.0.0-nightly.2018.9.20.63b26e63), android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 20 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/daem0n/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v10.11.0 (/Users/daem0n/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.3 Build version 9E145
```

**Comment by mhartington** [comment] 2018-12-12 17:23
duplicate of https://github.com/ionic-team/ionic/issues/15079

**Closed by mhartington** 2018-12-12 17:23 UTC
Labels: triage
