### ISSUE TITLE
bug: preparing platform is missing cordova.js due to incorrect path

### ISSUE THREAD

**Issue by lancevo** [ionic-team/ionic#20347] opened 2020-01-30 22:11 UTC
When preparing a platform either android or ios with a **specific** version (e.g: `'ionic cordova prepare ios@5.0.0`), it will throw an unhandled exception:

```
An unhandled exception occurred: ENOENT: no such file or directory, open '/Users/me/dev/mobile-test/platforms/ios@5.0.0/platform_www/cordova.js'
``` 

Notice the path platforms/**ios@5.0.0**, the version number @5.0.0 is appended to the path which causing this exception. Whereas the correct path is `platforms/ios/..`.  When I prepare a platform without specifying a version, it works correctly, however it installs an older version. 

**Ionic version:**
[X] **5.4.13**

**I'm submitting a ...** 
[X ] bug report
[ ] feature request

**Current behavior:**
preparing platform throws exception when a version specified, because the version number is added to the path 

**Expected behavior:**
Expect the path to be `platforms/ios` or `platforms/android` 

**Steps to reproduce:**

```
ionic cordova prepare ios@5.0.0 
ionic cordova prepare android@8.0.0 
```

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 5.4.13 (/Users/me/.nvm/versions/node/v10.18.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk/)
   ios-sim           : 7.0.0
   NodeJS            : v12.14.1 (/Users/me/.nvm/versions/node/v12.14.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-02-04 17:54
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The framework does not deal with configuring/building a Cordova app.

**Closed by liamdebeasi** 2020-02-04 17:54 UTC
Labels: triage
