### ISSUE TITLE
bug: ion-input type="number" max and min attribute validation does not work

### ISSUE THREAD

**Issue by shamohai** [ionic-team/ionic#20163] opened 2020-01-08 12:30 UTC
The latest version of ionic 4, ion-input type="number", max and min attribute form validation does not work.

type="date"  max and min attribute form validation is success, it works fine.

**Comment by liamdebeasi** [comment] 2020-01-08 14:01
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by shamohai** [comment] 2020-01-09 01:57
ionic 4  angular

html:

`<ion-content>
  <form #ngForm="ngForm">
    <ion-grid>
      <ion-row>
        <ion-col size="12">
          <ion-label>Form Validation: {{ngForm.valid}}</ion-label>
        </ion-col>
      </ion-row>
      <ion-row>
        <ion-col size="4">
          Quantity:
        </ion-col>
        <ion-col size="8">
          <ion-input name="txtQuantity" #txtQuantity type="number" min="2" max="5" tabindex="1" [(ngModel)]="Quantity" required autofocus="true" placeholder="Quantity" class="roundedInput">
          </ion-input>
        </ion-col>
      </ion-row>
    </ion-grid>
  </form>
</ion-content>`

min: 2, max: 5, normally it should be a number between [2,5].
![QQ图片20200109095330](https://user-images.githubusercontent.com/7419781/72030996-fa72e000-32c5-11ea-8846-06cb4ceaa887.png)


The actual situation is this.
![QQ图片20200109095504](https://user-images.githubusercontent.com/7419781/72031082-3e65e500-32c6-11ea-8a3f-f7b232c5ab7a.png)


Seems to only verify the must, not verify min and max.

**Comment by tahaerden** [comment] 2020-01-09 11:27
I can confirm the issue. 
For text inputs, minlength, maxlength, required etc. works.
For number inputs, required still works. min/max doesn't.

Here is my form html:

`

        <form #f="ngForm" (ngSubmit)="createEmployee(f)">
          <ion-list lines="full" class="ion-no-margin ion-no-padding">
            <ion-item>
              <ion-label position="stacked"
                >Name <ion-text color="danger">*</ion-text></ion-label
              >
              <ion-input
                required
                minlength="2"
                type="text"
                ngModel
                name="name"
              ></ion-input>
            </ion-item>

            <ion-item>
              <ion-label position="stacked"
                >Salary <ion-text color="danger">*</ion-text></ion-label
              >
              <ion-input required type="text" ngModel name="salary"></ion-input>
            </ion-item>

            <ion-item>
              <ion-label position="stacked"
                >Age <ion-text color="danger">*</ion-text></ion-label
              >
              <ion-input
                required
                min="18"
                max="65"
                type="number"
                ngModel
                name="age"
              ></ion-input>
            </ion-item>

            <ion-item>
              <ion-label position="stacked">Avatar</ion-label>
              <ion-input type="text" ngModel name="profile_image"></ion-input>
            </ion-item>
          </ion-list>
          <div class="ion-padding">
            <ion-button
              expand="block"
              type="submit"
              class="ion-no-margin"
              [disabled]="!f.form.valid"
              >Create Employee</ion-button
            >
          </div>
        </form>

`

**Comment by tahaerden** [comment] 2020-01-31 09:16
Any update on this @liamdebeasi ?

**Comment by karthikrp** [comment] 2020-02-26 07:27
This is a major issue. Can we get any updates on this?

**Comment by liamdebeasi** [comment] 2020-02-26 14:21
Thanks for the follow up. I am going to close this as this is not a bug in Ionic Framework. min/max validation for number inputs does not appear to be working for template driven forms in Angular: https://github.com/angular/angular/issues/16352.

I have created an example here showing the same behavior using an Angular app without Ionic Framework: https://stackblitz.com/edit/angular-input-min-max?file=src/app/app.component.html

**Closed by liamdebeasi** 2020-02-26 14:21 UTC
Labels: triage
