### ISSUE TITLE
VirtualScroll dimensions not calculated

### ISSUE THREAD

**Issue by royibernthal** [ionic-team/ionic#12162] opened 2017-06-27 01:02 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Issue:**
I have a page with VirtualScroll where I scroll many images.
I have an ion-menu with a link that calls nav.setRoot(component).

Whenever I'm getting to the page with VirtualScroll via the link in ion-menu, the VirtualScroll's content is not visible.

It appears in elements but it seems its dimensions are not calculated.

If I'm browsing to the page with VirtualScroll via a normal link that's not in ion-menu everything works properly.

My guess is it's somehow related to VirtualScroll being blocked while the ion-menu is open, since I'm changing to the VirtualScroll's page and only then the menu starts closing while I'm already there.

My VirtualScroll code is very basic, it's similar to the example shown here: https://ionicframework.com/docs/api/components/virtual-scroll/VirtualScroll/

```
<ion-list [virtualScroll]="items">

  <ion-item *virtualItem="let item">
    {{ item }}
  </ion-item>

</ion-list>
```

except I'm using divs for containers and use them to display images.

It seems that the div with class="virtual-scroll" has style="height: ...px;" when it's initialized properly on page load.
When I get to that page via ion-menu that style is missing. Same happens when I navigate to that page after being on a different page that also has VirtualScroll.
If I set the style manually via the elements tab in the dev tools I can see the VirtualScroll elements, although spaces and such are no longer calculated properly.

Why does this happen and how do I fix it?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.5
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Comment by AmitMY** [comment] 2017-06-27 07:34
Can you create a plunker reproducing this? I can run the example just fine

**Comment by jgw96** [comment] 2017-06-27 15:11
Hello all!I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/10148

**Closed by jgw96** 2017-06-27 15:11 UTC

**Comment by royibernthal** [comment] 2017-06-27 15:13
That's not the same issue. In my case the VirtualScroll is not inside ion-menu. Please Re-Open.

**Comment by royibernthal** [comment] 2017-06-27 16:17
@AmitMY I wasn't able to reproduce the issue on Plunker:
http://plnkr.co/edit/QfIJYaviYhTMLGq6w5fm?p=preview

Perhaps if we change to the latest angular and ionic dependencies (which are what I'm using locally)? Do you know how to do that?

Are you open to doing remote control?

**Comment by AmitMY** [comment] 2017-06-27 16:32
@royibernthal Remote control is not an option, but if you can link us to your repository we can try to help if this is a bug.
As @jgw96 mentioned, this is a duplicate. I advise you to try their solution, and set `display: block` on the parent div. Setting it inside `ion-menu` is the same as inside a normal page, as both have an `ion-content`.

Changing versions on plunkr - you can change the systemjs config file

**Comment by royibernthal** [comment] 2017-06-27 16:57
Their workaround doesn't work for me. I guess the best solution is to use ion-list and ion-item and figure out how to adjust the css rather than wait for this issue to be solved https://github.com/ionic-team/ionic/issues/10148, it doesn't seem to have a high priority at the moment.
