### ISSUE TITLE
Error: framework delegate is missing  with angular 8 when using popover components

### ISSUE THREAD

**Issue by deepanjali11** [ionic-team/ionic#20162] opened 2020-01-08 11:44 UTC
# Bug Report

**Ionic version:* 4.0.2*
[x] **4.x**

**Current behavior:**

core.js:6014 ERROR Error: Uncaught (in promise): Error: framework delegate is missing
Error: framework delegate is missing
    at f.present
**Expected behavior:**
PopoverController  create method should take angular component (as type of  Function).
**Steps to reproduce:**
PopoverController  create method not accepting angular component. 
**Related code:**
async presentPopover(ev: any) {
    const popover = await this.popoverController.create({
      component: FavoritesPopover,
      event: ev,
      translucent: true
    });
    return await popover.present();
  }
when i pass angular component name its throws error framework delegate is missing. Could you please help me to resolve this error? Thanks in Advance.
it works when we pass as string or HTMLElement.
async function presentPopover(opts) {
      const popoverController = document.querySelector('ion-popover-controller');
      await popoverController.componentOnReady();
      const popoverElement = await popoverController.create({ component: 'translucent-page', event: event, translucent: true });
      return await popoverElement.present();
    }

class TranslucentPage extends HTMLElement {
      constructor() {
        super();
      }
      connectedCallback() {
        this.innerHTML = `
          <div padding>
            <h1>Translucent Popover</h1>
          </div>
        `;
      }
    }
    customElements.define('translucent-page', TranslucentPage);

**Comment by liamdebeasi** [comment] 2020-01-08 14:02
Thanks for the issue. Your issue states you are using Ionic 4.0.2. Can you try this again on the latest version of Ionic? (v4.11.7).

**Comment by manpreet1990** [comment] 2020-01-09 06:51
@liamdebeasi : I tried with ionic ((v4.11.7). Facing the same issue **Error: framework delegate is missing**

**Comment by liamdebeasi** [comment] 2020-01-09 14:17
Thanks for the follow up. Can you provide a repo with the code required to reproduce this issue?

**Comment by deepanjali11** [comment] 2020-01-10 14:33
Please find the attached  source code stackblitz  [(https://angular-duumze.stackblitz.io)]

**Comment by liamdebeasi** [comment] 2020-01-13 14:17
Thanks for the follow up. I am going to close this as  the `ion-popover-controller` component is not intended for usage in Ionic Angular applications.

Please follow the usage instructions in the "Angular" tab on the [ion-popover Usage Documentation](https://ionicframework.com/docs/api/popover#usage). You will need to import `PopoverController` from `@ionic/angular` and then use it via dependency injection.

**Closed by liamdebeasi** 2020-01-13 14:17 UTC
Labels: triage
