### ISSUE TITLE
NavbBar Break and Change position when rotate with TABS Placement

### ISSUE THREAD

**Issue by fcraveiro** [ionic-team/ionic#13325] opened 2017-11-03 04:56 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ X ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
The navbar changes places with the Tabs when rotate, when it returns to position a few times back normal others disappear
if you click on another tab the bar will return to the place,
when rotate, place change again, these errors started in this last versions

**Expected behavior:**
Normal Tabs

**Steps to reproduce:**

New Ionic Tabs

App.module.ts

    IonicModule.forRoot(MyApp, {
      modalEnter: 'modal-slide-in',
      modalLeave: 'modal-slide-out',
      tabsPlacement: 'top'
    })

**Related code:**

In Cel phone and Devapp

ANDROID 6.0.1
LG X POWER

![screenshot_2017-11-03-09-20-04](https://user-images.githubusercontent.com/31604881/32371545-6f92f14e-c078-11e7-8ec8-ebf1f909bb31.png)

![rotate](https://user-images.githubusercontent.com/31604881/32360969-36374728-c042-11e7-8542-a7ba21f99497.jpg)

![normal](https://user-images.githubusercontent.com/31604881/32360967-2ce2cb5c-c042-11e7-9a85-02a08fb8412c.jpg)

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\cfc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.4
    npm  : 3.10.10
    OS   : Windows 7

Misc:

    backend : pro

```

**Comment by kensodemann** [comment] 2017-11-03 17:08
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13241. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-11-03 17:08 UTC
