### ISSUE TITLE
bug:  ion-date with min max  shows all the months and days when you select another date

### ISSUE THREAD

**Issue by GerardoTovar** [ionic-team/ionic#18793] opened 2019-07-13 21:08 UTC
# Bug Report

**Ionic version:**
[x] [4.x]

**Current behavior:**
 ion-datetime with the property min / max, shows all the months and days when you select another date

**Expected behavior:**
with the property min / max should only show the years / months / days of the range

**Steps to reproduce:**

generate a blank project with the version **@ ionic / angular": "^ 4.1.0** and use ion-date with min/max  not working , i update to **4.6.2** but still not working

when you open it shows the corresponding months and days
![bug1](https://user-images.githubusercontent.com/35576675/61176483-e6e8f580-a57e-11e9-80ec-540aa94f0856.png)

but when you select another date it shows all the months and days
![bug2](https://user-images.githubusercontent.com/35576675/61177296-10118200-a58f-11e9-9b42-f669cd6d2c95.png)

**Related code:**

A sample application via GitHub

https://github.com/GerardoTovar/bugDate

```
  <ion-datetime
    displayFormat = "MM / DD / YYYY"
    pickerFormat = "MM DD YYYY"
    placeholder = "MM / DD / YYYY"
    min = "2019-05-13"
    max = "2019-07-13">
  </ ion-datetime>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\L_Z0K\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : 0.2.6

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.0.0
   OS     : Windows 10
```

English is not my native language, if something is not clear, please let me know

**Comment by ppjjzz** [comment] 2019-07-17 04:13
the same problem

**Comment by ippeiukai** [comment] 2019-07-18 01:08
https://github.com/ionic-team/ionic/issues/18776#issuecomment-512623174

> It's working with 4.5 but not working at 4.6.x

**Comment by liamdebeasi** [comment] 2019-07-18 14:39
Thanks! I was able to reproduce this. I debugged the issue a bit more and it looks like the internal data objects are correct (months 8-12 _are_ being marked as disabled), but the `picker-opt-disabled` class that actually hides the options is not being applied.

**Comment by manucorporat** [comment] 2019-07-22 13:59
is it a  4.5 regression?

**Comment by liamdebeasi** [comment] 2019-07-23 04:22
@manucorporat This issue is not present in 4.5 but is present in 4.6. There were a few issues around the time of Ionic 4.1 regarding min/max that I think some might be thinking of. I am unable to reproduce this issue in 4.1.

**Closed** 2019-07-24 16:04 UTC
Labels: package: angular, type: bug
