### ISSUE TITLE
Crash in WebThread on iOS

### ISSUE THREAD

**Issue by bushev** [ionic-team/ionic#12103] opened 2017-06-20 10:05 UTC
**Ionic version: 3.3.0**

**I'm submitting a bug report**

**Current behavior:** crash in WebThread.
```
WebThread (12)#0	0x0000000188f8c150 in objc_msgSend ()
#1	0x0000000190946064 in -[UIView(CALayerDelegate) _wantsReapplicationOfAutoLayoutWithLayoutDirtyOnEntry:] ()
#2	0x00000001906450b4 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#3	0x000000018d835274 in -[CALayer layoutSublayers] ()
#4	0x000000018d829de8 in CA::Layer::layout_if_needed(CA::Transaction*) ()
#5	0x000000018d829ca8 in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#6	0x000000018d7a534c in CA::Context::commit_transaction(CA::Transaction*) ()
#7	0x000000018d7cc3ac in CA::Transaction::commit() ()
#8	0x000000018d7cce78 in CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) ()
#9	0x000000018a4c49a8 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#10	0x000000018a4c2630 in __CFRunLoopDoObservers ()
#11	0x000000018a4c2a7c in __CFRunLoopRun ()
#12	0x000000018a3f2da4 in CFRunLoopRunSpecific ()
#13	0x000000018f0c4608 in RunWebThread(void*) ()
#14	0x00000001895d968c in _pthread_body ()
#15	0x00000001895d959c in _pthread_start ()
#16	0x00000001895d6cb4 in thread_start ()
```
**Expected behavior:**
Set root page.

**Steps to reproduce:**
Crash reproduces in 1 % times if I clicked the "Back" button in a top left corner.

**Related code:**

```
this.navCtrl.setRoot(ConnectionsPage, {}, {animate: true, direction: 'back'});
```

**Other information:**
iOS 10.3.2

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.1.0 
    npm        : 3.10.10 
```

**Comment by jgw96** [comment] 2017-06-21 15:21
Hello, thanks for using Ionic. Unfortunately, we have not seen this issue before. Does this happen with a sidemenu starter? Also, could you send a minimal repo we could use to reproduce this issue?

**Comment by bushev** [comment] 2017-06-21 16:01
Hello, Justin!

Unfortunately, it's the hard reproducible problem. I suspect it depends on how to click on the "Back" button. Or in the case when I click quickly several times. Not sure.

I will try to reproduce that on a Conference app on this week.

**Comment by jgw96** [comment] 2017-06-22 17:04
👍 thanks for the info.

**Comment by bushev** [comment] 2017-06-24 09:07
Unfortunately, I can't reproduce it with my application and with Ionic Conference...

**Comment by bushev** [comment] 2017-06-24 09:12
I found very similar crash report (double tap issue): https://forum.ionicframework.com/t/ios-fatal-crash-with-ionic-1/74378

**Comment by jgw96** [comment] 2017-06-26 15:12
Hello @bushev , thanks for all the info. Unfortunately, because neither you or we can reproduce this issue I am going to close it for now. The issue you linked to in the forum is an Ionic 1 issue so that does not really apply here. Thanks for using Ionic!

**Closed by jgw96** 2017-06-26 15:12 UTC
Labels: needs info, v2

**Comment by wngasinur** [comment] 2017-07-25 01:15
I have also similar crash in WebThread, it's also random crash. I'm not able to reproduce it. Aftermath, the application refuses to start again, I need to redeploy again from XCode to start the application.

```
Thread 4 name:  WebThread
Thread 4 Crashed:
0   libobjc.A.dylib               	0x00000001847241a0 objc_retain + 16
1   UIKit                         	0x000000018bdc77b8 -[UIView(Hierarchy) subviews] + 152
2   UIKit                         	0x000000018c0cf04c -[UIView(CALayerDelegate) _wantsReapplicationOfAutoLayoutWithLayoutDirtyOnEntry:] + 72
3   UIKit                         	0x000000018bdce0b4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1256
4   QuartzCore                    	0x0000000188fbe274 -[CALayer layoutSublayers] + 148
5   QuartzCore                    	0x0000000188fb2de8 CA::Layer::layout_if_needed(CA::Transaction*) + 292
6   QuartzCore                    	0x0000000188fb2ca8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
7   QuartzCore                    	0x0000000188f2e34c CA::Context::commit_transaction(CA::Transaction*) + 252
8   QuartzCore                    	0x0000000188f553ac CA::Transaction::commit() + 504
9   QuartzCore                    	0x0000000188f55e78 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 120
10  CoreFoundation                	0x0000000185c549a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
11  CoreFoundation                	0x0000000185c52630 __CFRunLoopDoObservers + 372
12  CoreFoundation                	0x0000000185c52a7c __CFRunLoopRun + 956
13  CoreFoundation                	0x0000000185b82da4 CFRunLoopRunSpecific + 424
14  WebCore                       	0x000000018a84d608 RunWebThread(void*) + 456
15  libsystem_pthread.dylib       	0x0000000184d6968c _pthread_body + 240
16  libsystem_pthread.dylib       	0x0000000184d6959c _pthread_body + 0
17  libsystem_pthread.dylib       	0x0000000184d66cb4 thread_start + 4
```
