### ISSUE TITLE
bug: ion-toggle accessibility issue using android voice-over

### ISSUE THREAD

**Issue by sorenfruergaard** [ionic-team/ionic#21080] opened 2020-04-20 11:16 UTC
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
Using voiceover on android version 10 (possibly other versions also), ion-toggle makes users tab twice to go to next element. This also makes the reading of the element wrong.
Issue can be reproduced on https://ionicframework.com/docs/demos/api/toggle/index.html?ionic:mode=md

**Expected behavior:**
Users should only swipe once to go the next element.

**Steps to reproduce:**
1. Go to https://ionicframework.com/docs/demos/api/toggle/index.html?ionic:mode=md
2. Activate Androids talkback
3. Swipe through the elements on the page and notice that you need to swipe twice to go past a togglebutton

**Comment by liamdebeasi** [comment] 2020-04-20 16:32
Thanks for the issue. Can you provide a repo with the code required to reproduce the issue? I am unable to reproduce this on a device running Android 10.

**Comment by sorenfruergaard** [comment] 2020-04-26 19:24
You can use this repo: https://github.com/sorenfruergaard/ionic-toggle

Let me know if you need further details about how to reproduce the error.

**Comment by liamdebeasi** [comment] 2020-04-28 19:30
Thanks! I was able to reproduce the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.1.0-dev.202004281926.3cc78c1`

**Comment by sorenfruergaard** [comment] 2020-04-29 07:22
Yes, it resolves the issue - thank you.
I don't have an iOS device for the moment, so I was not able to perform a test on iOS, which I think is necessary.

**Comment by liamdebeasi** [comment] 2020-05-08 15:59
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21168, and a fix will be available in an upcoming release of Ionic Framework.

**Closed** 2020-05-08 15:59 UTC
Labels: package: core, type: bug
