### ISSUE TITLE
Ionic 3 browser back and forth while loading view creates runtime error

### ISSUE THREAD

**Issue by nitinpund** [ionic-team/ionic#11873] opened 2017-05-31 08:46 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have used deep-linking in my app. when I run the app on web browser and then use browser navigation keys for back and forth with fast click, I get the ```
Runtime Error
Uncaught (in promise): invalid views to insert

**Expected behavior:**
When I click on back and forth, app should not throw the error. 

**Steps to reproduce:**
create an app with deep linking  implementation and the use browser navigation buttons to go back and forth with fast click.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```
![bug](https://cloud.githubusercontent.com/assets/4629680/26623559/c5b3261c-460b-11e7-8b68-dfdb3b36dd5a.png)

**Comment by jgw96** [comment] 2017-05-31 14:56
Hello, thanks for using Ionic. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/11374.

**Closed by jgw96** 2017-05-31 14:56 UTC
