### ISSUE TITLE
@ionic/vue build failing due to issue #15810

### ISSUE THREAD

**Issue by alyjak** [ionic-team/ionic#16959] opened 2019-01-04 17:12 UTC
# Bug Report

**Ionic version:**

[x] **4.0.0-rc.0**

**Current behavior:**

I'm experimenting with ionic v4 using @ionic/core and @ionic/vue. `npm run build` is failing due to a typescript error, similar to what's documented in #15810, here's a snippet: 

```
    error  in [..]/node_modules/@ionic/vue/node_modules/@ionic/core/dist/types/components.d.ts

    ERROR in [..]/node_modules/@ionic/vue/node_modules/@ionic/core/dist/types/components.d.ts
    5625:13 Interface 'HTMLIonInputElement' cannot simultaneously extend types 'IonInput' and 'HTMLStencilElement'.
      Named property 'focus' of types 'IonInput' and 'HTMLStencilElement' are not identical.
        5623 |   };
        5624 |
      > 5625 |   interface HTMLIonInputElement extends Components.IonInput, HTMLStencilElement {}
             |             ^
        5626 |   var HTMLIonInputElement: {
        5627 |     prototype: HTMLIonInputElement;
        5628 |     new (): HTMLIonInputElement;

     error  in [..]/node_modules/@ionic/vue/node_modules/@ionic/core/dist/types/components.d.ts
```
This is because `@ionic/vue/package.json` specifies @ionic/core v4.0.0-beta.12, which is the release exactly prior to when #15810 was fixed. Bumping @ionic/vue's core dependency to v4.0.0-rc.0 fixes this issue and results in successful vue-based builds.

**Expected behavior:**

Expected behavior is for the build to succeed without typescript errors.

**Steps to reproduce:**

See bug report

**Related code:**

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI) : 4.6.0

System:

   NodeJS : v10.15.0
   npm    : 6.4.1
   OS     : Linux 4.15
```

**Comment by johnbwoodruff** [comment] 2019-01-04 22:45
Can confirm this is happening for me as well, and I've verified that I'm also getting `@ionic/core` v4.0.0-beta.12.

**Comment by paulstelzer** [comment] 2019-01-11 08:10
The vue package is not updated since weeks, so it has the old ionic/core inside. If you `npm install @ionic/core@latest` it should overwrite it and you can work with it. Could you check it? In near future ionic/vue will be updated, too of course. It's just a workaround until it's updated.

So I close this here because as soon as ionic/vue is updated, the issue is fixed too :)

**Closed by paulstelzer** 2019-01-11 08:10 UTC
Labels: triage
