### ISSUE TITLE
bug:  Cannot pass data to popover with componentProps

### ISSUE THREAD

**Issue by Bforsyth1234** [ionic-team/ionic#19985] opened 2019-11-23 21:54 UTC
# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 5.4.6 (/Users/brooks.forsyth/.nvm/versions/node/v12.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/Users/brooks.forsyth/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.12.0
   OS     : macOS Mojave

[x] **4.x**

**Current behavior:**

There is no data being passed through the componentProps using the popover controller
**Expected behavior:**

Data to be passed

**Steps to reproduce:**

click pop button in example project and not console.log.

https://github.com/Bforsyth1234/popoverionic4
**Related code:**

```
  async presentPopover() {
    const popover = await this.popoverController.create({
      component: PopovercomponentComponent,
      componentProps: {
        test: 'test'
      },
      translucent: true
    });
    return await popover.present();
  }
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2019-11-25 14:31
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

When using `componentProps` in Ionic Angular, each key in the object becomes an input. In your example app, you pass in the following:

```
componentProps: {
  test: 'test'
}
```

To access this data in your popover component, you would need to access `@Input() test;`. However, in your example repo you have `@Input() data;`. Changing this to be `@Input() test;` resolves the issue.

**Closed by liamdebeasi** 2019-11-25 14:31 UTC
Labels: triage
