### ISSUE TITLE
bug: ionViewWillLeave not called on specific tab page, when entire TabsPage leaves

### ISSUE THREAD

**Issue by gregor-srdic** [ionic-team/ionic#18109] opened 2019-04-23 18:20 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I have an empty tabs template project and I've added a settings page outside of tabs.
When I navigate between tabs, lifecycle methods ionViewWillEnter and ionViewWillLeave are called appropriately on each specific tab page (e.g. '/tabs/tab1', '/tabs/tab2', ...).
But when I move to external page (e.g. '/settings') lifecycle methods are not called on the specific tab page, only on the parent TabsPage.

**Expected behavior:**
Navigating from '/tabs/tab1' to '/settings' would invoke ionViewWillLeave on Tab1Page and navigating back would again invoke ionViewWillEnter on Tab1Page.

**Steps to reproduce:**
Run the demo app than navigate to settings and back to tabs. Compare console log to the one when switching between tabs.

**Related code:**

https://github.com/gregor-srdic/ionic4-ionviewwillenter-tabs-bug

```
[Tab1Page] enter
[TabsPage] enter
[Tab1Page] leave
[Tab2Page] enter
[Tab2Page] leave
[Tab1Page] enter
[TabsPage] leave
                             <-- missing [Tab1Page] leave
[SettingsPage] enter
[SettingsPage] leave
[TabsPage] enter
                             <-- missing [Tab1Page] enter
```

When entering and leaving settings page, no events are invoked on Tabs1Page (last active specific tab page).

**Other information:**
This behaviour is very problematic in case of user sign out - I want to redirect user to "/login" when signing out, but then I want to reload user data after logging back in and navigating to tabs.

**Ionic info:**

```
Ionic:
   ionic (Ionic CLI)             : 4.12.0 
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1
System:
   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by taipeiwu** [comment] 2019-05-04 11:29
Same problem here. Did Ionic team notice this bug? Thanks

**Comment by taipeiwu** [comment] 2019-05-15 03:29
Also related #16834

**Comment by liamdebeasi** [comment] 2019-05-20 18:53
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16834.

There is a fix in the works, and we hope to have it out soon.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-20 18:53 UTC
Labels: triage
