### ISSUE TITLE
bug: Ionic4 CSS properties of parent element are not transmitted

### ISSUE THREAD

**Issue by lcavero** [ionic-team/ionic#18573] opened 2019-06-18 16:04 UTC
# Bug Report

**Ionic version:**

[x] **4.5**

**Current behavior:**

<ion-content>
<ion-item style="--background: red; background: red;">
    <ion-label class="label-form" color="light" position="floating">Email</ion-label>
    <ion-input [debounce]="500" type="email"></ion-input>
</ion-item>
</ion-content>

In Android 6+ the ion-input gets the background color of the ion-item.
In Android 5- the ion-input background color is white;

**Expected behavior:**

The ion-input gets the background color of the ion-item always

Edit:
In Android 5 you can upgrade the Webview apk and that solves the problem, but in Android 4.4 (Webview version 34) that is not possible. Any idea to solve this problem? a polifyll or something?
Thanks

**Comment by liamdebeasi** [comment] 2019-06-19 13:12
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17781. We hope to have this issue resolved with some upcoming fixes to Stencil.

Please refer to that thread for further updates.

Thanks!

**Closed by liamdebeasi** 2019-06-19 13:12 UTC
Labels: triage
