### ISSUE TITLE
Tabs starter project broken (ionic 4.0.0-rc.4)

### ISSUE THREAD

**Issue by miguelyoobic95** [ionic-team/ionic#14429] opened 2018-05-04 17:02 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

The bug appears on the Tabs starter template when created with the latest version of the Ionic CLI. The navigation between tabs is broken, the path changes in the URL but I am still looking at the same page. The issue was not present a couple of weeks ago since I was trying to reproduce nother bug and it worked fine.

**Expected behavior:**

Pressing any tab should show the relevant page.

**Steps to reproduce:**

Install the latest ionic cli: `npm i -g ionic@rc`

Create an Ionic-Angular project (4+) using the tabs starter. `ionic start`

Serve the application (`ionic serve`) and the bug is present without any changes being made.

**Related code:**

<!-- If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

A sample application via GitHub.

Here is a copy of the project for reference: https://github.com/miguelyoobic95/TabsStarterBug

**Comment by thedang** [comment] 2018-05-06 15:28
Because Ionic team used RouteReuseStrategy.
Just remove it.

**Comment by alexcheng1982** [comment] 2018-05-07 14:29
Remove following line in the `AppModule`.

`{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy }`

**Comment by mhartington** [comment] 2018-05-07 19:52
Hm, I can reproduce this when pulling the latest release, but including the code locally does not cause and issue. RC4 did include some errors, so I'm wondering if that has anything to do with it 🤔 

Will investigate. Thanks for reporting!

**Comment by mhartington** [comment] 2018-05-07 20:17
Alright, this looks to be fixed in master. Thanks

**Closed by mhartington** 2018-05-07 20:17 UTC
Labels: triage

**Comment by miguelyoobic95** [comment] 2018-05-09 08:30
Thanks for the help guys! 👍
