### ISSUE TITLE
bug: swipe to go back not working on ion-item-sliding

### ISSUE THREAD

**Issue by gr99t** [ionic-team/ionic#20773] opened 2020-03-13 10:21 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
- **ion-item-sliding and swipe back gesture**
Swipe back is not possible _(Web, Android)_

- **ion-item-options with item lines set to none**
Sliding options still show a line (bottom border)

**Expected behavior:**
- **ion-item-sliding and swipe back gesture**
Swipe back is working
- **ion-item-options with item lines set to none**
Sliding options do not show a line

**Steps to reproduce:**

- Open the list page
- **ion-item-sliding and swipe back gesture**
  1. Try to swipe back while on any item
- **ion-item-options with item lines set to none**
  1. Swipe to open the options of one item without lines, best visible if you swipe the item far away 

**Related code:**
Github Repo (https://github.com/gr99t/ionic-5-item-sliding)
Github Pages (https://gr99t.github.io/ionic-5-item-sliding)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.2.0
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.1 
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-03-13 15:11
Thanks for the issue. I was able to reproduce the swipe to go back behavior.

Setting `lines="none"` on `ion-item` is only going to affect `ion-item` since `ion-item-options` is a sibling of `ion-list` not a parent. To get the behavior you are looking for, you should set `lines="none"` on the parent `ion-list`.

**Comment by gr99t** [comment] 2020-03-13 16:02
Thanks for the reply.
Alright, then wrapping the `ion-item` and `ion-item-options` inside an extra `ion-list` will do the trick😄 
Maybe this should get added to the docs?

```html
<ion-list>

    <!-- some sliding items with lines -->  
    <!--  ...  -->

    <!-- one without lines -->
    <ion-item-sliding>
      <ion-list lines="none">

        <ion-item>
          <ion-label>Item without lines</ion-label>
        </ion-item>

        <ion-item-options>
          <ion-item-option color="danger">
            <ion-icon slot="icon-only" name="call"></ion-icon>
          </ion-item-option>

          <ion-item-option color="dark">
            <ion-icon slot="icon-only" name="mail"></ion-icon>
          </ion-item-option>
        </ion-item-options>

      </ion-list>
    </ion-item-sliding>

</ion-list>
```

**Comment by liamdebeasi** [comment] 2020-03-13 17:08
Regarding the swipe to go back bug, can you try the following dev build and let me know if it resolves the issue? `npm i @ionic/angular@5.1.0-dev.202003131705.2982c95`

**Comment by gr99t** [comment] 2020-03-13 18:25
Yes, perfect!

**Comment by liamdebeasi** [comment] 2020-03-17 15:00
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20777 and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-03-17 15:00 UTC
Labels: package: core, type: bug
