### ISSUE TITLE
bug: tab component is not destroyed

### ISSUE THREAD

**Issue by piernik** [ionic-team/ionic#19739] opened 2019-10-24 08:40 UTC
# Bug Report
I have `tabs` with `router-outlet`. Navigating is not destroying component.

**Ionic version:**
[x] **4.8.1**

**Current behavior:**
Navigation between tabs is not destroying component

**Expected behavior:**
When navitating out of a tab should destroy component.

**Steps to reproduce:**

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-destroy?file=src/app/tab3/tab3.page.ts
Example. Go to tab3 - in console is `init`. Navigate out - should be `destroy` in console log.

**Comment by liamdebeasi** [comment] 2019-10-24 13:32
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. It's typically faster to just keep the tabs in the DOM in case users want to flip between tabs quickly. Additionally, this is the behavior of tabs in native mobile apps as well. Thanks!

**Closed by liamdebeasi** 2019-10-24 13:32 UTC
Labels: triage

**Comment by piernik** [comment] 2019-10-24 17:50
That's unfortunate and wierd. The is router change after all. It could drive to memory leaks - all unsubscribed async pipes in templates (as in my case).
I hope You will change Your mind
