### ISSUE TITLE
bug: Mutation Observer not finding DOM element

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#18763] opened 2019-07-11 13:40 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Mutation Observer can't find DOM nodes of the V4 Ionic Elements.

**Expected behavior:**

To trigger the event and listen to mutations

**Steps to reproduce:**

1. create html template with <ion-content>
2. in between place a <ion-grid> with <ion-row> and <ion-col>
3. make a `new MutationObserver()` instance and try to observe DOM change

**Related code:**
```html
<ion-content #content>
  <ng-container *ngIf="messages$.length; else loading">
    <ion-grid>
      <ion-row *ngFor="let message of messages$">
        <ion-col
          *ngIf="id === message.id"
          size="9"
          offset="3"
          class="message my-message"
          [ngStyle]="{ background: message.isUrgent ? 'var(--ion-color-danger)' : 'var(--ion-color-primary)' }"
        >
        </ion-col>
      </ion-row>
    </ion-grid>
  </ng-container>

```
```typescript
  private mutationObserver: MutationObserver;

  @ViewChild(IonContent) private content: IonContent;
  @ViewChild(IonCol, { read: ElementRef }) private chatList: ElementRef;
//note I've tried IonCol/Row/Grid, with the change from V3(which this worked previously) I was able to just use List or Col

  public ngAfterViewInit(): void {
    this.mutationObserver = new MutationObserver((mutations: MutationRecord[]): void => {
      console.log('here', mutations);
      this.content.scrollToBottom();
    });
    this.mutationObserver.observe(this.chatList.nativeElement, {
      childList: true,
    });
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   NodeJS : v12.5.0 (/usr/local/Cellar/node/12.5.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment] 2020-06-09 20:10
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. All Ionic components are regular Web Components. If they are rendered in the DOM they should be usable with MutationObserver. I would recommend ensuring that `this.chatList` is defined when you construct the MutationObserver. Thanks!

**Closed by liamdebeasi** 2020-06-09 20:10 UTC
Labels: triage
