### ISSUE TITLE
JSX element type 'Route<{ path: "/tab1"; component: FC<{}>; exact: true; }>' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by UCN0** [ionic-team/ionic#21109] opened 2020-04-22 17:01 UTC
I just installed ionic react, I did not install any package. At the time of test I receive this error. It has been long I am trying to fix, but I can't find a solution for it. Shouldn't it work fine with the tabs?

The types returned by 'render()' are incompatible between these types.
```
[react-scripts]     Type 'ReactNode' is not assignable to type 'false | Element | null'.
[react-scripts]       Type 'undefined' is not assignable to type 'false | Element | null'.  TS2605
[react-scripts]     41 |         <IonRouterOutlet>
[react-scripts]     42 |         <React.Fragment>
[react-scripts]   > 43 |           <Route path="/tab1" component={Tab1} exact={true} />
[react-scripts]        |           ^
[react-scripts]     44 |           <Route path="/tab2" component={Tab2} exact={true} />
[react-scripts]     45 |           <Route path="/tab3" component={Tab3} />
[react-scripts]     46 |           <Route path="/" render={() => <Redirect to="/tab1" />} exact={true} />
```

When I highlight <Route> it shows:

```
'Route' cannot be used as a JSX component.
  Its instance type 'Route<{ path: "/tab1"; component: FC<{}>; exact: true; }>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.ts(2786) 
```

**Comment by liamdebeasi** [comment] 2020-04-22 17:13
How are you creating your application? Are you using one of our starter apps?

**Comment by UCN0** [comment] 2020-04-22 17:23
I create like this: `ionic start app-name tabs --type=react --capacitor`

**Comment by liamdebeasi** [comment] 2020-04-22 17:28
I am not getting that error when running that command. Can you provide a full repo that I can reproduce the issue with?

**Comment by UCN0** [comment] 2020-04-22 19:22
Please have look at this repo: https://github.com/UCN0/IonicReact-Bug.git

**Comment by liamdebeasi** [comment] 2020-04-22 20:16
Did you add the correct code? It looks like the tab pages did not get uploaded.

**Comment by UCN0** [comment] 2020-04-22 20:32
It wasn't uploaded, but I added everything in as zip.

**Comment by liamdebeasi** [comment] 2020-04-22 20:38
Thanks - all the files appeared in the zip. Unfortunately, I am still unable to reproduce the issue you are describing. Can you provide some steps to reproduce the issue?

**Comment by UCN0** [comment] 2020-04-22 20:47
If I comment out this:

 ```
         <Route path="/tab1" component={Tab1} exact={true} />
          <Route path="/tab2" component={Tab2} exact={true} />
          <Route path="/tab3" component={Tab3} />
          <Route path="/" render={() => <Redirect to="/tab1" />} exact={true} />
```
The app launchs. Perhaps the problem is with the Route

**Comment by UCN0** [comment] 2020-04-22 20:49
In VS Route and Redirect is highlighting as if there is syntax error, and when hovered it shows this: 

```
(alias) class Route<T extends RouteProps = RouteProps>
import Route
'Route' cannot be used as a JSX component.
  Its instance type 'Route<{ path: "/tab1"; component: FC<{}>; exact: true; }>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.ts(2786)
```

**Comment by liamdebeasi** [comment] 2020-04-22 20:54
What version of VS Code are you using? I am using version 1.44.2 on macOS, and I do not see that error.

**Comment by UCN0** [comment] 2020-04-22 20:55
These are my specs:
```
Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by liamdebeasi** [comment] 2020-04-22 21:04
I tried your application on VS Code for Windows and got no error there either (v1.44.2). Try updating VS Code from 1.44.1 to 1.44.2, and see if the issue goes away. You might also want to post on the [Ionic Forums](http://forum.ionicframework.com/). Someone there may be able to help you debug a bit more.

I am going to close this issue as I cannot reproduce the error you are reporting. If you are able to find a way to reliably reproduce the issue feel free to reply here, and I can re-open the issue. Thanks!

**Closed by liamdebeasi** 2020-04-22 21:04 UTC
Labels: triage

**Comment by UCN0** [comment] 2020-04-23 15:14
I have updated nodejs and VS, but still, what about this error that comes before the route? 

` [react-scripts] TypeScript error in C:/Users/xxx/Documents/nodeJs-Apps/test-mobile-v1/src/App.tsx(42,11):`
