### ISSUE TITLE
ion-list ion-grid screen flickering

### ISSUE THREAD

**Issue by jratiwanich** [ionic-team/ionic#17342] opened 2019-02-01 03:39 UTC
# Bug Report

**Ionic version:**

[x] **4.10.1**

**Current behavior:**
Mobile screen flicker when the list or array is being populated. This only happens on a real mobile device, not the web browser emulator. Device tested - iphone7, iphone X

**Expected behavior:**
Screen should be smooth where the data is being populated on the screen.

**Steps to reproduce:**

1. Build an Ionic blank app
2. Create an array with some data
3. Populate the array on the html using ion-item or ion-grid
4. Deploy on a device

**Related code:**

**Ionic HTML:**
```
<ion-item  *ngFor="let item of mylist" >
                {{item.time}} , {{item.name}}
  </ion-item>
```
**Angular:**
```
 interval(1000).subscribe(() => { this.updateMyArrayData(); });
...
...
updateMyArrayData(){
    this.mylist = [
                          {time: new Date(), name: "ABC"}, 
                          {time: new Date(), name: "XYZ"}, 
                           ];
}

```

**Other information:**
Only test this in a real phone to see the impact. Only see this with an array populating a list. 

If I replace Ionic component with a primitive HTML tags, the bug will go away.

**This code will not cause screen to flicker**
```
<div  *ngFor="let item of mylist" class="some-nice-css">
           {{item.time}} , {{item.name}}
  </div>
```

So the question is, why ion-item cause the screen to flicker?

**Comment by KillerCodeMonkey** [comment] 2019-02-01 08:04
hey this has nothin to do with ionic. More with angular lists.

Checkout the `trackBy` functionality of angulars `*ngForOf` to cache list items and reuse them.
Your flickering should be gone.
https://angular.io/api/core/TrackByFunction
https://angular.io/api/common/NgForOf#description

**Comment by jratiwanich** [comment] 2019-02-01 19:09
Thank you. `TrackByFunction` fixes with the screen flickering. 
But I still wonder why it only flickers on Ionic components and not native HTML without Angular put the list in the cache.

**Comment by paulstelzer** [comment] 2019-06-04 06:51
Thanks for the issue! I think it flickers only on Ionic components because the component will be updated, if you have the same complex component build with Angular, it will flicker here too. But I close this here because the issue is related to Angular

**Closed by paulstelzer** 2019-06-04 06:51 UTC
Labels: triage
