### ISSUE TITLE
bug: Ionic 4 ion-searchbar not showing clear text icon

### ISSUE THREAD

**Issue by chilupa** [ionic-team/ionic#20794] opened 2020-03-17 05:05 UTC
# Bug Report

**Ionic version:**

[x] **4.11.7**

**Current behavior:**

Clear text icon is not showing in the search bar as described in the docs in Ionic 4 app.

**Expected behavior:**

I was expecting a clear text icon in the search bar which was not showing up.

**Steps to reproduce:**

Paste the `ion-searchbar` code that is in Ionic docs in your Ionic 4 app.
```
<ion-searchbar></ion-searchbar>
``` 

**Related code:**

```
  <ion-toolbar mode="ios">
    <ion-grid>
      <ion-row>
        <ion-searchbar></ion-searchbar>
      </ion-row>
    </ion-grid>
  </ion-toolbar>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/pavanchilukuri/.nvm/versions/node/v10.18.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.3.0
   @capacitor/core           : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   NodeJS : v10.18.1 (/Users/pavanchilukuri/.nvm/versions/node/v10.18.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
   Xcode  : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-03-17 13:16
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce the issue using the code snippet provided.

**Comment by chilupa** [comment] 2020-03-27 02:05
I've reproduced the issue in [Stackblitz](https://stackblitz.com/edit/ionic4-ion-searchbar?file=src%2Fapp%2Fpages%2Fhome%2Fhome.component.html)

However, in my app, below is what I did to make it work. It's resolved.
```
<ion-searchbar clear-icon="close-sharp"></ion-searchbar>
```

**Comment by liamdebeasi** [comment] 2020-03-27 13:39
Thanks for the issue. I am going to close this as your StackBlitz is using a beta version of Ionic Framework. This issue does not occur in the latest version of Ionic Framework.

**Closed by liamdebeasi** 2020-03-27 13:39 UTC
Labels: triage
