### ISSUE TITLE
bug: Ionic/Angular@4.9.0 Android multiple menu animations errors

### ISSUE THREAD

**Issue by cparkinsonMYCM** [ionic-team/ionic#19274] opened 2019-09-05 09:40 UTC
# Bug Report

**Ionic version:**
[x] **4.9.0**

**Current behavior:**

Error when ion-menu closes:
```
TypeError: Cannot read property 'updateTiming' of undefined
    at getWebAnimations.forEach.animation (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:702:1)
    at Array.forEach (<anonymous>)
    at updateWebAnimation (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:701:1)
    at Object.update (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:744:1)
    at childAnimations.forEach.animation (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:740:1)
    at Array.forEach (<anonymous>)
    at update (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:739:1)
    at Object.direction (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:416:1)
    at Menu.startAnimation (c:\...\node_modules\@ionic\core\dist\esm\ion-menu_4-md.entry.js:215:1)
    at Menu._setOpen (c:\...\node_modules\@ionic\core\dist\esm\ion-menu_4-md.entry.js:188:1)
animation-d0becaea.js:702
```

Error when swiping from left to open menu:
```
TypeError: Cannot read property 'getComputedTiming' of undefined
    at getWebAnimations.forEach.animation (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:685:1)
    at Array.forEach (<anonymous>)
    at setAnimationStep (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:684:1)
    at Object.progressStep (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:771:1)
    at childAnimations.forEach.animation (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:768:1)
    at Array.forEach (<anonymous>)
    at Object.progressStep (c:\...\node_modules\@ionic\core\dist\esm\animation-d0becaea.js:767:1)
    at Menu.onMove (c:\...\node_modules\@ionic\core\dist\esm\ion-menu_4-md.entry.js:264:1)
    at onMove (c:\...\node_modules\@ionic\core\dist\esm\ion-menu_4-md.entry.js:100:1)
    at fireOnMove (c:\...\node_modules\@ionic\core\dist\esm\index-2c4a5477.js:479:1)
```

**Other information:**

Introduced in 4.9.0, was not present in 4.8.1.
Found in Android Emulator, not found in iOS Simulator.

`ion-menu-button` works fine to open the menu, no errors.
When menu is open the error occurs on close, menu items still function, content behind menu changes correctly, the menu just doesn't close.

Opening menu by swiping from the left errors and app becomes unresponsive.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\...\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 9 other plugins)

Utility:

   cordova-res : 0.5.2
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\...\AppData\Local\Android\Sdk)
   NodeJS            : v12.3.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 10
```

**Comment by cparkinsonMYCM** [comment] 2019-09-05 09:42
looks like same as #19272, didn't appear in search.

**Comment by liamdebeasi** [comment] 2019-09-05 12:41
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19272.

**Closed by liamdebeasi** 2019-09-05 12:41 UTC
Labels: triage
