### ISSUE TITLE
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

### ISSUE THREAD

**Issue by bogomips** [ionic-team/ionic#12065] opened 2017-06-16 12:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
After I've upgraded to the latest 3.4.0 ionic serve does not work anymore.
That's what I get: Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : https://registry.npmjs.org/@ionic/app-scripts/-/app-scripts-1.3.7.tgz
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.4.0

System:

    Node       : v8.1.2
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3 
```

**Comment by bogomips** [comment] 2017-06-16 12:52
I downgraded node to 7.7.1 and everything works again.
For what I've understood it's a compatibility problem with app-scripts, is that right? 
Any plan to make it compatible?

**Comment by danielsogl** [comment] 2017-06-16 13:08
@bogomips Yes the app-scripts package are not compatible with NPM5. We will release a new version soon to fix this issue.

**Comment by jgw96** [comment] 2017-06-19 14:18
Hello all! Closing this as a duplicate of https://github.com/ionic-team/ionic-app-scripts/issues/1039

**Closed by jgw96** 2017-06-19 14:18 UTC

**Comment by pmurpmur** [comment] 2017-07-13 19:32
I started a new project with npm 5 and all of ionics latest updates and I am still having this exact issue. It makes sense to me if npm 5 is the issue but in the changelog for ionic-app-scripts 1.3.10 it says:
> Ionic updated to npm 5 across the board, so please update to npm 5 to utilize our lock file when contributing. 

(https://github.com/ionic-team/ionic-app-scripts/blob/master/CHANGELOG.md#1310-2017-06-28)

I find this confusing and am wondering if this is still a bug or not?

**Comment by darmali** [comment] 2017-07-17 07:10
I discovered the project name should be in alpha letters and it works for me

**Comment by shopexdream** [comment] 2017-07-20 07:28
thsk

**Comment by AlirezaHaghshenas** [comment] 2017-08-09 07:23
@darmali What is "alpha letters"?

**Comment by darmali** [comment] 2017-08-09 11:23
@AlirezaHaghshenas that mean you should create the project name  without special characters like ( _ , + - ..... etc)
