### ISSUE TITLE
Device Motion Event Dispatched every 60ms +-

### ISSUE THREAD

**Issue by maantje** [ionic-team/ionic#12563] opened 2017-08-03 09:53 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Currently working on an application and was trying to increase the "speed" of the app for a smoother experience. While trying to find what is causing the UI to delay I attached the Safari time line debugger to the IPAD (4th gen) and I am noticing a Device Motion Event Dispatched every 60ms +-

<img width="962" alt="screen shot 2017-08-03 at 11 38 49" src="https://user-images.githubusercontent.com/9058265/28915984-0d225b8c-7841-11e7-9d26-04e3daa44591.png">

The application I built does nothing with device orientation on its own so I am going to guess this is from the Ionic core itself. 

**Expected behavior:**
Looking at the code on ion-dev.js:412 
``` js
window.addEventListener('devicemotion', function(ev) {
      var current = ev.accelerationIncludingGravity;
      var currentTime;
      var timeDifference;
      var deltaX = 0;
      var deltaY = 0;
      var deltaZ = 0;

      if (self.shakeX === null) {
        self.shakeX = current.x;
        self.shakeY = current.y;
        self.shakeZ = current.z;
        return;
      }

      deltaX = Math.abs(self.shakeX - current.x);
      deltaY = Math.abs(self.shakeY - current.y);
      deltaZ = Math.abs(self.shakeZ - current.z);

      if (((deltaX > threshold) && (deltaY > threshold)) || ((deltaX > threshold) && (deltaZ > threshold)) || ((deltaY > threshold) && (deltaZ > threshold))) {
        currentTime = new Date();
        timeDifference = currentTime.getTime() - self.shakeTime.getTime();

        if (timeDifference > timeout) {
          self.optionsMenu(true);
          self.shakeTime = new Date();
        }
      }

      self.shakeX = current.x;
      self.shakeY = current.y;
      self.shakeZ = current.z;
    });
``` 
I would suggest the expected behaviour is not to register a new event listener every 60 ms.

**Other information:**
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : not installed
    npm        : 4.2.0
```

**Comment by jgw96** [comment] 2017-08-03 15:19
Hello (: are you running a dev build in this case? We use the device motion api to enable shaking the device to pull up a dev menu when you are running a dev build on a device. With a production build (which you should be using for perf testing) you will not get this. Also, that timeline does not show that we are adding an event listener every 60ms +-, thats just saying that the event was firing, but we only have one listener for that event.

**Comment by jgw96** [comment] 2017-08-07 15:51
Hello all! I am going to close this issue for now since it is expected behavior and i cannot reproduce it in prod builds. Thanks for using Ionic!

**Closed by jgw96** 2017-08-07 15:51 UTC
Labels: needs info, v3
