### ISSUE TITLE
issue: Method 'getTab' does not exist on 'IonTabs'

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/ionic#20051] opened 2019-12-09 21:42 UTC
# Bug Report

**Ionic version:**
[x] **4.8.1**

**Current behavior:**
The IonTabs object does not have a method `getTab(tab: string)` though it is listed in [the documentation](https://ionicframework.com/docs/api/tabs)

**Expected behavior:**
The method should be available in the IonTabs object.

**Related code:**
html
```
<ion-tabs #myTabs (ionTabsDidChange)="selectTab($event.tab)">
  <ion-tab-bar>
    <ion-tab-button
      tab='tab1'
      [selected]="selectedTab === 'tab1'" >
      <ion-label>Tab 1</ion-label>
    </ion-tab-button>

    <ion-tab-button
      tab='tab2'
      (click)="changeTab('tab2')"
      [selected]="selectedTab === 'tab2'" >
      <ion-label>Tab 2</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```
ts
```
  selectedTab: string;
  @ViewChild('myTabs', { static: true }) tabs: IonTabs;

  async selectTab(selectedTab: string) {
    this.selectedTab = selectedTab;
    // the following line throws
    const tab = await this.tabs.getTab(selectedTab);
  }
```
d
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.9
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.9.1 (/Users/matthewbarr/.nvm/versions/node/v12.9.1/bin/node)
   npm    : 6.10.2
   OS     : macOS Catalina
   Xcode  : Xcode 11.2.1 Build version 11B500
```

**Comment by liamdebeasi** [comment] 2019-12-10 14:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19918.

**Closed by liamdebeasi** 2019-12-10 14:02 UTC
Labels: triage
