### ISSUE TITLE
the search bar delay hide when navigate to another page

### ISSUE THREAD

**Issue by baorr** [ionic-team/ionic#11990] opened 2017-06-09 08:57 UTC
Ionic version:3.2.0

I'm submitting a bug report

Current behavior:
1. I have two pages, one is home page and another page is search page
home page:
![image](https://user-images.githubusercontent.com/553038/26967998-fd323ad2-4d32-11e7-9856-ba49b3059b22.png)
search page:
![image](https://user-images.githubusercontent.com/553038/26968025-21ce9bec-4d33-11e7-8494-d9712ed244f0.png)

2. I searchbar like below example:
    a. when I click the search button in the home page, it looks good.
    b. when I click the back button in the search page to back to home page, the bug is up, 

       
<img width="520" alt="5c4f48fb-2f09-4710-ae4e-c3816f4ddeec" src="https://user-images.githubusercontent.com/553038/26968376-67beaf7e-4d34-11e7-8a73-48eb90fdb6de.png">

**Expected behavior:**
do not delay hide the search bar.

**Comment by jgw96** [comment] 2017-06-09 14:53
Hello, thanks for using Ionic! Would you be able to provide a minimal repo we could use to reproduce this?

**Comment by jgw96** [comment] 2017-06-14 19:27
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-14 19:27 UTC
Labels: needs info, v2
