### ISSUE TITLE
[4.0.0-beta.17] Segment in header not animated when navigating

### ISSUE THREAD

**Issue by edotassi** [ionic-team/ionic#16540] opened 2018-11-30 16:47 UTC
# Bug Report

**Ionic Info**
```
   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.17
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.1.0

System:

   NodeJS : v11.2.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS
```

**Describe the Bug**
Gif attached

**Steps to Reproduce**
```
<ion-header>
    <ion-toolbar [title]="'Invoice'" [color]="'primary'">
        <ion-buttons slot="start">
            <ion-back-button></ion-back-button>
        </ion-buttons>
        <ion-title *ngIf="!loadingInvoice">
            Fattura n°
        </ion-title>
    </ion-toolbar>
    <ion-toolbar>
        <ion-segment (ionChange)="segmentChanged($event)">
[...]
```

**Additional Context**
![out](https://user-images.githubusercontent.com/3192179/49302602-d8563e00-f4c7-11e8-8b58-d1c2d517941d.gif)

**Comment by edotassi** [comment] 2018-11-30 17:01
this works:
```
<ion-header>
    <ion-grid no-padding>
        <ion-row>
            <ion-col no-padding>
                <ion-toolbar [title]="'Invoice'" [color]="'primary'">
                    <ion-buttons slot="start">
                        <ion-back-button></ion-back-button>
                    </ion-buttons>
                    <ion-title *ngIf="!loadingInvoice">
                        Fattura n°
                    </ion-title>
                </ion-toolbar>
            </ion-col>
        </ion-row>
        <ion-row style="background-color: white;">
            <ion-col>
                <ion-segment (ionChange)="segmentChanged($event)">
[...]
```

**Comment by brandyscarney** [comment] 2018-11-30 18:19
Thanks for the issue! Closing as a duplicate of https://github.com/ionic-team/ionic/issues/16262

**Closed by brandyscarney** 2018-11-30 18:19 UTC
Labels: triage
