### ISSUE TITLE
Lazy loading tabs with locationStrategy 'path' not working

### ISSUE THREAD

**Issue by jouke** [ionic-team/ionic#12538] opened 2017-08-01 16:35 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have an app (in development) that uses tabs that are lazy loaded. Everything worked until I changed the locationStrategy to 'path', which resulted in a 404 when navigating to lazy-loaded tabs
```
Error: Uncaught (in promise): Error: Loading chunk 1 failed.
Error: Loading chunk 1 failed.
    at HTMLScriptElement.onScriptComplete (http://localhost:8100/build/vendor.js:104:24)
    at HTMLScriptElement.o (http://localhost:8100/build/polyfills.js:2:24344)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at HTMLScriptElement.invoke (http://localhost:8100/build/polyfills.js:3:10945)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
    at Tab.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:43272:16)
    at Tab.NavControllerBase._failed (http://localhost:8100/build/vendor.js:43260:14)
    at http://localhost:8100/build/vendor.js:43315:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
```
**Expected behavior:**
The behaviour should be the same when using either locationStrategy

**Steps to reproduce:**
Just use the tabs starter, refer to the tab pages by passing strings (to trigger the lazy loading) and change the app.module.ts file to add:

```
    IonicModule.forRoot(MyApp, {
      locationStrategy: 'path'
    }),

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 
    @ionic/cli-utils                : 1.6.0 
    ionic (Ionic CLI)               : 3.6.0 

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node  : v6.9.4
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b
    npm   : 3.10.10
```

**Comment by jgw96** [comment] 2017-08-01 18:23
Hello all! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/10565

**Closed by jgw96** 2017-08-01 18:23 UTC
