### ISSUE TITLE
Platform ready and no network : Async is not considered

### ISSUE THREAD

**Issue by tgensol** [ionic-team/ionic#11810] opened 2017-05-27 11:05 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When having a bad or no network, the platforn.ready() takes a serious long time on iOs and Android if you have externals scripts (Facebook pixel, google maps), even with the "async" attributes
To compare, the deviceready event of Cordova will always fire after couple of seconds (with Wifi, or no network). But the platform ready of Ionic will not... and if you are waiting for it to change your rootPage or some others codes (like splashscreen.hide(), set the language of the ngx-translate,..., it can take a really really long time (30-60seconds sometimes.., especially if you have not network at all)

**Expected behavior:**
On deviceready event, I can see (on my app at least), every cordova plugins and ionic components/lazy loading are working well. So what plt.ready is waiting ? I replaced every plt.ready in my app with the deviceready event and the app looks way faster if you do not have a wifi connection (80% of my users).

**Steps to reproduce:**
1. Use the conference ionic starter
2.  Cut your internet on your iPhone or simulator
3. Launch your app
4. Just see when the platform.ready promise is resolved

It looks like the async attributes is not considered. Or something like that

**Other information:**

![show](https://cloud.githubusercontent.com/assets/7864896/26512536/6038c73a-4267-11e7-89b6-765672acb8b5.jpg)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by jgw96** [comment] 2017-05-30 13:50
Hello, thanks for using Ionic! Could you provide a repo we could use to reproduce this?

**Comment by tgensol** [comment] 2017-05-30 14:29
@jgw96 Actually you only need the conference starter 

https://github.com/ionic-team/ionic-conference-app

Cut your network, and launch the app. External javascript scripts will block the platform ready promise

**Comment by tgensol** [comment] 2017-06-02 16:43
@jgw96 What do you need from me ?

I am using Ionic from the beta version, and this is the worst issue I can tell I had, especially when you are using a mobile phone (because the launching time can just be crazy...). From the v1, I always  thought it was Cordova that was not working in offline, but I just found it was Ionic when you are using externals libraries.

Thanks

**Comment by jgw96** [comment] 2017-06-05 14:58
Hello @tgensol , sorry but I am not able to reproduce this issue on my devices. I'm using a moto g and a Nexus 6 with airplane mode on. With the latest version of the conference app i see no difference in the startup time when its on the network or off. Are you saying that you are using some external libraries that are trying to make network requests?

**Comment by tgensol** [comment] 2017-06-05 16:00
@jgw96 Hello, thanks for your reply.

I just tried again, and I cannot reproduce the issue. But last time I tried I could do it every time I tried.
I can say that when I am using my app, I can feel that the Platform.ready event is kind of "related" to my network speed. I put some trackers and I can also see it on my users, the event will be delayed with a bad network. I changed every Platform.ready event for deviceready and the lauching time is now really faster and the UX really better.

I will try to do more tests, I thought it was the externals dependencies (or maybe an update of something fixed it), and see if it is still there

**Comment by jgw96** [comment] 2017-06-06 16:41
👍 sounds good. Since you are not able to reproduce the issue anymore I am going to close this issue for now but, if you are able to reproduce it again feel free to open another issue. Thanks for using Ionic 😃

**Closed by jgw96** 2017-06-06 16:41 UTC
Labels: needs info, v3

**Comment by danielflippance** [comment] 2017-06-06 23:12
I've noticed that when running the app in livereload mode and connecting logging information using the `-lsc` options, once the app is disconnected from wifi, it will not reach the Platform.ready() event in app.component:

    $ ionic run android -lsc --device

If I rebuild the app and deploy it without livereload/logging and in production mode then remove wifi, the Platform.ready() is fired as expected:

    $ ionic run android --prod --device
