### ISSUE TITLE
searchBar for iOS with Native Chinese input method issue

### ISSUE THREAD

**Issue by xyh67** [ionic-team/ionic#11843] opened 2017-05-29 06:29 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
when I use the iOS10 native Chinese input method enter to searchBar the letter will show in the searchBar,such as when I typing "你好",I need typing "nihao" on input method ,but on the searchBar I get "nnini hni hani hao",and I choose the word on the input method I get "nnini hni hani hao你好".

**Expected behavior:**
When I typing in iOS native Chinese input method just get the word which I typing,such as when I typing "你好","你好" will show in the searchBar.

**Steps to reproduce:**
use iOS native Chinese input method typing any Chinese word on searchBar

**Related code:**
I just use the document example 

<ion-searchbar
  [(ngModel)]="myInput"
  [showCancelButton]="shouldShowCancel"
  (ionInput)="onInput($event)"
  (ionCancel)="onCancel($event)">
</ion-searchbar>

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : not installed

**Comment by jgw96** [comment] 2017-05-30 14:56
Hello, thanks for using Ionic, I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11566.

**Closed by jgw96** 2017-05-30 14:56 UTC
