### ISSUE TITLE
ionic 5: Status Bar Scroll To Top doesn't end current Scroll

### ISSUE THREAD

**Issue by HansKrywaa** [ionic-team/ionic#20468] opened 2020-02-13 14:10 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

I Created a topic for this in v4: #20423 
It is not fixed in v5 

**Expected behavior:**

See related Issue

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 53 other plugins)

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run                            : 0.3.0

System:

   Android SDK Tools : 25.2.3 (/Users/hanskrywalsky/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-02-13 14:12
Closing as a duplicate of https://github.com/ionic-team/ionic/issues/20423. Ionic 5 is a continuation of the work we did in Ionic 4, so no need to open 2 issues. Thanks!

**Closed by liamdebeasi** 2020-02-13 14:12 UTC
Labels: triage
