### ISSUE TITLE
Ionic v3.8.0 - Images in list are not rendering correctly

### ISSUE THREAD

**Issue by smubarak-ali** [ionic-team/ionic#13601] opened 2017-12-07 04:26 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
The images in any list are not displayed correctly on IOS only. The images look distorted, color seems off and any random one image from the list is overriding the wholes list images. On android its' working fine, its' just the issue with after ios 11 updates.

![ios 11 list bug_1](https://user-images.githubusercontent.com/11365385/33695743-d27ef3f8-db39-11e7-9d12-4e71bf33266a.jpg)

![ios 11 list bug_2](https://user-images.githubusercontent.com/11365385/33695744-d2afb862-db39-11e7-8f92-34020c216393.jpg)

![ios11_bug_1](https://user-images.githubusercontent.com/11365385/33696547-b970b7b2-db3d-11e7-9e6d-be4ae54888db.gif)

**Expected behavior:**
As can be view in both screenshot, the images are not correctly rendered. It all happens after ios 11 update, our app going for pre-live testing in like a week. Please help!!!

**Steps to reproduce:**
So far on ios 11, there are no steps required, it just happens like that. Whereas in android no issue

**Related code:**

events-page.html
```
<ion-content>
   <div *ngIf="(data.length > 0)">
    <div class="wrapper" text-center *ngFor="let d of data" (click)="goToDetails(d.guid)">
      <img [src]="getImage(d.customFieldDtoList)" alt="" />
      <p>
        {{d.name}}
      </p>
    </div>
    <h3 *ngIf="!(data.length > 0)" text-center class="topPadding">
      No Upcoming Events
    </h3>
</ion-content>
```
event-page.scss
```
.topPadding {
    padding-top: 5%;
    margin-top: 0%;
    margin-bottom: 0%;
  }
  .wrapper {
    position: relative;
    padding: 0%;
    img {
      width: 100% !important;
      height: 100% !important;
      margin-bottom: -6.5px;
      filter: brightness(85%);
    }
    p {
      bottom: 1px;
      color: white;
      left: 0;
      font-weight: bolder;
      padding: 5px 15px;
      position: absolute;
      margin-bottom: 0px;
    }
  }
  .bar-button-default,
  .bar-button-clear-default,
  .bar-button-default {
    color: #424242;
    background-color: transparent;
    padding: 0px;
  }
  .content-ios .scroll-content {
    padding-top: 0px !important;
  }
```

**Ionic info:**

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    Node       : v9.2.0
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment] 2017-12-07 12:19
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13485. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.

As of now, this is believed to be a Safari rendering bug and not an issue with Ionic. However, I am leaving that other issue open until more is known. I believe there is a potential work-around posted in there that may work for you as well.

Thank you for using Ionic

**Closed by kensodemann** 2017-12-07 12:19 UTC

**Comment by smubarak-ali** [comment] 2017-12-07 12:50
@kensodemann 
Thank you for the response... I will check the issue and try to apply the solution... Hope that it work out as I have a deadline to release.... I will update on the issue accordingly
