### ISSUE TITLE
bug: ion-Slides and ion-segment-button mode="ios" does not go pretty well together

### ISSUE THREAD

**Issue by MilotH2** [ionic-team/ionic#21133] opened 2020-04-26 14:24 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

I have added iOS Mode to the ion-segment and ion-segment-buttons that I have used, inside of ion-slides, while if the user slides on the button, it slides ion-slide and it stuck between, so basically it does not get the slide event to trigger, i tried to add ionFocus but the event is not firing.

**Expected behavior:**

I need it not to have an issue with ion-slide so that when user swipes it swipes for the ion-slide and not for the ion-segment-button. i want the ion-segment-button to be only clickable. i tried swipeable="false", but did not work.

**Steps to reproduce:**

I want to have an option to disable the slide in ion-segment, which i could not find any option, or so that we can have an ionFocus and ionBlur event so that we know when to disable/enable the ion-slide to swipe. This way i think that when the user is on focus of that button i can disable it and when it blurs out i can enable the swipe, or have an option for mode="ios" so that the ion-segment wont be swipeable.

**Related code:**

[Youtube VIdeo Link here](https://www.youtube.com/watch?v=lqVKD3VZGvc&feature=youtu.be)
https://www.youtube.com/watch?v=lqVKD3VZGvc&feature=youtu.be
```
<ion-slides pager="false" (ionSlideWillChange)="slideChanged($event)" #slides [options]="slideOpts" style="z-index: 100;">
 
  <ion-slide >
<div style="padding-top: 20px;">

          <ion-segment mode="ios" (ionChange)="slide1Segment($event)" value={{slide1Segmenti}} >
            <ion-segment-button mode="ios"  value="yes">
              <ion-label>{{'yes' | translate}}</ion-label>
            </ion-segment-button>
            <ion-segment-button mode="ios"  value="no">
              <ion-label>{{'no' | translate}}</ion-label>
            </ion-segment-button>
          </ion-segment>
          </div>

</ion-slide>
</ion-slides>
```

```
Ionic:

   Ionic CLI                     : 6.3.0 (C:\Users\Milot\AppData\Roaming\nvm\v12.16.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.13.0) : 0.10.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (D:\Cache\Sdk)
   NodeJS            : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.4
   OS                : Windows 10
```

**Comment by DavidStrausz** [comment] 2020-04-26 17:30
Try adding `scrollable=true` to your `ion-segment`. According to the [docs](https://ionicframework.com/docs/api/segment) this should disable the swipe possibility:

**scrollable**
> If true, the segment buttons will overflow and the user can swipe to see them. _In addition, this will disable the gesture to drag the indicator between the buttons in order to swipe to see hidden buttons._

Note that this will only work if you do not have many segments which will again cause a clash of the two swipe gestures.

**Comment by liamdebeasi** [comment] 2020-04-27 13:38
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Nesting components that use conflicting gestures is not something we recommend or support. You can use the workaround provided in https://github.com/ionic-team/ionic/issues/21133#issuecomment-619591001 to disable the swipe gesture.

**Closed by liamdebeasi** 2020-04-27 13:38 UTC
Labels: triage
