### ISSUE TITLE
Router redirectTo not working in ionic angular 5.0.7

### ISSUE THREAD

**Issue by manojbharti** [ionic-team/ionic#21103] opened 2020-04-22 11:39 UTC
ionic info
Ionic:

   Ionic CLI                     : 6.5.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res (update available: 0.12.2) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/home/neoark-4/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.14.4
   OS                : Linux 4.15

**Comment by liamdebeasi** [comment] 2020-04-22 12:07
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by manojbharti** [comment] 2020-04-22 12:21
I can show you my app-routing.module.ts file below. I want to redirect on home route by default but it is not redirecting only shows white blank page.


import { NgModule } from '@angular/core';
import { AuthGuard } from './auth.guard';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { AppinfoGuard } from '../app/gaurds/appinfo.guard';

const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  {
    path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomePageModule)
  },
  {
    path: 'signin',
    loadChildren: () => import('./signin/signin.module').then(m => m.SigninPageModule)
  },
  {
    path: 'signup',
    loadChildren: () => import('./signup/signup.module').then(m => m.SignupPageModule)
  }
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule],
  providers: [AuthGuard]
})
export class AppRoutingModule { }

**Comment by liamdebeasi** [comment] 2020-04-22 12:24
It would be helpful to have a full reproduction. Your routing file has a similar configuration to our starter applications, so it is hard to say what the issue is without having a full reproduction.

**Comment by manojbharti** [comment] 2020-04-24 05:52
For setting default route I checked url in app.component.ts file below is code. Please let me know is it right method or not.

if (window.location.pathname === "/") {
      this.router.navigateByUrl('/home');
    }

**Comment by liamdebeasi** [comment] 2020-04-24 13:50
Thanks for the follow up. For setting the default route we recommend using Angular's routing config: https://angular.io/guide/router#set-up-redirects.

I am going to close this issue as I am unable to reproduce the original issue.

**Closed by liamdebeasi** 2020-04-24 13:50 UTC
Labels: triage
