### ISSUE TITLE
bug: ionic input component in @ionic/core/@5.0.6+ is not backward compatible

### ISSUE THREAD

**Issue by beenotung** [ionic-team/ionic#20957] opened 2020-04-03 04:28 UTC
# Bug Report

**Ionic version:**

[x] **@ionic/core@5.x**

@stencil/core@1.8.x
@ionic/core@5.0.6-5.0.7

**Current behavior:**

When using @stencil/core@1.8.x and @ionic/core/@5.0.7 the ionic input doesn't work properly.
In specific, ion-label inside ion-item doesn't align properly, also the popup of ion-select cannot be clicked.

The inappropriate layout in the current release:
![2](https://user-images.githubusercontent.com/6007292/78324030-1674dd80-75a6-11ea-9563-3e7400715ece.png)

**Expected behavior:**

The ion-label should align consistently, and the pop up of ion-select should be clickable as in 5.0.5. 

The working appearance in previous release:
![1](https://user-images.githubusercontent.com/6007292/78324039-1b399180-75a6-11ea-884d-e27f6c8115cc.png)

**Steps to reproduce:**

Try to run the project with below library version combination

| @stencil/core | @ionic/core | works or not |
|---|---|---|
| 1.8.8 | 5.0.5 | Y |
| 1.8.11 | 5.0.5 | Y |
| **1.8.11** | **5.0.6** | **N** |
| **1.8.11** | **5.0.7** | **N** |
| 1.8.11 | 5.0.5 | Y |
| 1.12.1 | 5.0.6 | Y |
| 1.12.1 | 5.0.7 | Y |

**Related code:**

```tsx
<ion-list>
  <ion-item>
    <ion-label position='stacked'> Label 1 </ion-label>
    <ion-select>
      <ion-select-option value='1'> option 1 </ion-select-option>
      <ion-select-option value='2'> option 2 </ion-select-option>
    </ion-select>
  </ion-item>
  <ion-item>
    <ion-label position='stacked'> Label 2 </ion-label>
    <ion-input type='text'/>
  </ion-item>
  <ion-item>
    <ion-label position='stacked'> Label 3 </ion-label>
    <ion-textarea/>
  </ion-item>
</ion-list>
```

**Other information:**

The bug appears on desktop Firefox, Chrome and Android Chrome. (not tested other environment)

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.3.0 

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.11.0
   native-run  : not installed

System:

   NodeJS : v12.13.0 
   npm    : 6.14.4
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment] 2020-04-03 13:31
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by beenotung** [comment] 2020-04-04 06:41
@liamdebeasi Here is the demo repo, with screenshot and hosted demo.
https://github.com/beenotung/ionic-input-demo

**Comment by liamdebeasi** [comment] 2020-04-06 14:06
Thanks for the follow up. I am going to close this as this is not a bug in Ionic Framework. This is likely due to a version mismatch.

We recently updated Ionic Framework to use a newer version of Stencil, but since you are installing an older version, there might be some issues. I would recommend updating your version of Stencil to use the latest version. If you feel there is a bug on the Stencil side of things, feel free to open an issue on the Stencil repo. Thanks!

**Closed by liamdebeasi** 2020-04-06 14:06 UTC
Labels: triage

**Comment by beenotung** [comment] 2020-04-07 16:37
Understandable. Why I'm staying with the old version of stencil because the post 1.8 version doesn't support symbolic links pointing outside the project. I'll mark it as separate issue.
