### ISSUE TITLE
Ionic 3 ion-datetime stopped working for Chrome v69 Desktop

### ISSUE THREAD

**Issue by meetdshah007** [ionic-team/ionic#15758] opened 2018-09-26 10:20 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : not installed

local packages:
    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:
    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro

```

**Describe the Bug**
Datetime stopped displaying the content on datetime selector. Modal appears on the screen but numbers and month name are not visible. I inspected and Dom have values as well in there. This happens only on browser.
[http://www.screencast.com/t/vDX179ufVt](http://www.screencast.com/t/vDX179ufVt)

**Related Code**
```
<ion-item>
  <ion-label fixed>Start Date</ion-label>
  <ion-datetime displayFormat="DD/MMM/YYYY" name="startsat"></ion-datetime>
 </ion-item>
```

**Expected Behavior**
It should display the Selector and we able to select the values for Date.

**Additional Context**
Chrome is giving following not sure if it's relevant or not.
> [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

**Comment by mhartington** [comment] 2018-09-26 20:34
I'm using chrome 69 right now and I am not seeing this in my tests. 

https://stackblitz.com/edit/ionic-ijx8sg?file=pages/home/home.html

The `/deep/` selector issue is not really related to anything Ionic as we do not use that in V3. Please check your code and validate that everything is working as well.

Going to close this as I cannot reproduce the issue. Feel free to post on the forum is you are running into any other issues.

http://forum.ionicframework.com

**Closed by mhartington** 2018-09-26 20:34 UTC
Labels: triage
