### ISSUE TITLE
bug: ionic pwa sample does not work on ios

### ISSUE THREAD

**Issue by guggens** [ionic-team/ionic#19019] opened 2019-08-07 10:27 UTC
# Bug Report

**Ionic version:**
[x] **4.7.1**

**Current behavior:**
Sample app from https://github.com/ionic-team/ionic-pwa-toolkit
does work fine on desktop. 
When I deploy it and open it on an IOS device (IPhone 7, IOS 12.4), it just shows a blank white screen. Unfortunately, can't debug, since I don't have a mac.

**Expected behavior:**
Sample app shows and works as on desktop

**Steps to reproduce:**
Get code from: 
https://github.com/ionic-team/ionic-pwa-toolkit

npm init stencil ionic-pwa

Build steps:
    - npm install
    - npm run build
    - copy www folder to server.

**Comment by lucasmendes2105** [comment] 2019-11-17 14:22
up

**Comment by liamdebeasi** [comment] 2020-05-22 19:40
Thanks for the issue. I tried this on devices running iOS 12.4 and iOS 13.4 and was unable to reproduce the issue. I am going to close this, but if you are able to reproduce this with the latest version of Ionic Framework please feel free to open a new issue. Thanks!

**Closed by liamdebeasi** 2020-05-22 19:40 UTC
Labels: triage
