### ISSUE TITLE
Ion-toggle in IOS mode does not offer the possibility to remove the toggle icon border

### ISSUE THREAD

**Issue by StriderRanger** [ionic-team/ionic#17533] opened 2019-02-19 16:03 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

It is not possible to remove the border of the ion-toggle that is shown by default in the IOS mode
![image](https://user-images.githubusercontent.com/15088185/53027233-753bce00-345c-11e9-9125-3bb70d60be15.png)

**Expected behavior:**

Since the toggle-icon is part of the shadow dom, It would be helpful to provide some CSS property that controls the background-color of the toggle-icon, or the apparent border of the ion-toggle
![image](https://user-images.githubusercontent.com/15088185/53028373-a5846c00-345e-11e9-8730-02843d11ffb6.png)

**Steps to reproduce:**

**Related code:**

```
<ion-toggle mode="ios"></ion-toggle>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.7.1
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

```

**Comment by AlekNiebla** [comment] 2019-04-20 22:48
Hey can I take a look at this problem?

**Comment by praveenraji2i** [comment] 2019-04-27 07:29
@StriderRanger Use below variable to override default toggle style in ios.

`$toggle-ios-border-color-off: #F00;`
`$toggle-ios-background-color-off: #000;`
`$toggle-ios-handle-background-color: #0F0;`

**Comment by pyro366** [comment] 2019-07-02 05:07
> @StriderRanger Use below variable to override default toggle style in ios.
> 
> `$toggle-ios-border-color-off: #F00;`
> `$toggle-ios-background-color-off: #000;`
> `$toggle-ios-handle-background-color: #0F0;`

This is for older versions of the framework and not applicable for Ionic 4. We have black design of our application and I would appreciate such possibility too, as it looks very strange now with white border,

**Comment by seravifer** [comment] 2019-10-19 15:12
I couldn't reproduce the problem. I don't see any border in the iOS toggle.

**Comment by brandyscarney** [comment] 2020-04-29 23:13
Thanks for the issue! I'm going to close this as the most recent version of the framework does not have a border on the toggle.

**Closed by brandyscarney** 2020-04-29 23:13 UTC
Labels: help wanted, package: core, type: feature request
