### ISSUE TITLE
First item of ion-select-option not showing after selection

### ISSUE THREAD

**Issue by ReaperTech** [ionic-team/ionic#18373] opened 2019-05-23 21:25 UTC
**Describe the bug**
First ion-select-option selected from ion-select list (generated with *ngFor) not shown

**To Reproduce**
Make an ion-select element and use *ngFor to generate ion-select-option's from an array. Select the first option -> only three dots shown instead of the text. Select any other option -> the selected text is shown.

**Expected behavior**
All options must be shown

**Screenshots**
**Fist option selected**
![image](https://user-images.githubusercontent.com/43549638/58014677-aed2b280-7af9-11e9-887a-100c206c7e69.png)
![image](https://user-images.githubusercontent.com/43549638/58014732-c873fa00-7af9-11e9-8b18-4817f5354a74.png)

**Any other option selected**
![image](https://user-images.githubusercontent.com/43549638/58014797-eb9ea980-7af9-11e9-8efc-20aa6cd32b38.png)
![image](https://user-images.githubusercontent.com/43549638/58014836-096c0e80-7afa-11e9-8b90-9006a681649e.png)

**Console Logs**
none

**Plugin Version**
(node:17752) ExperimentalWarning: The fs.promises API is experimental
cordova-android-firebase-gradle-release 1.0.3 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 1.4.4 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"

**Desktop (please complete the following information):**
  - Browser Chrome 74.0.3729.157

 ```
<ion-select formControlName="selectedSepaCountry" >
              <ion-select-option
                *ngFor="let sepaCountryOption of sepaCountries" 
                [value]="sepaCountryOption"
                >
                {{sepaCountryOption}}
                
              </ion-select-option>
</ion-select>
```
```
export const sepaCountries = [
    'AT',
    'BE',
    'DK',
    'FI',
    'FR',
    'DE',
    'IE',
    'IT',
    'LU',
    'NL',
    'NO',
    'PT',
    'ES',
    'SE',
    'CH',
    'GB',
];
```

**Additional context**
Using reactive forms
Ionic:

   ionic (Ionic CLI)             : 4.7.1 
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.1.0 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2019-05-24 12:55
Hi there,

Thanks for the issue! I am not able to reproduce this (tested on Ionic 4.0.2 and the latest version of Ionic). Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by ReaperTech** [comment] 2019-05-24 17:38
@liamdebeasi Hello, thanks for the reply. I am not able to share my code. I decided to use the ion-picker and feed the pick value into my reactive form. The picker is also not working properly (it doesn't cancel) but it is better than the ion-select issue.

**Comment by brandyscarney** [comment] 2019-05-24 19:24
Thanks for the issue! As Liam was unable to reproduce it using the code provided, I am unable to reproduce it in our core component (see https://codepen.io/brandyscarney/pen/ZNxPrX?editors=0010), and there is no additional code to reproduce I will be closing this. If anyone reading this can reproduce, please create a new issue.

Please take a look at your CSS to see if you are setting a width on the `ion-select`. Usually the text adds an ellipsis (...) when the text is too long to display in the available width, so that may be happening. For additional support with styling, please visit our [forums](http://forum.ionicframework.com/) or [Slack](https://ionicworldwide.herokuapp.com/) channel. Thanks!

**Closed by brandyscarney** 2019-05-24 19:24 UTC
Labels: triage
