### ISSUE TITLE
bug: incompatible reuse strategy providing a custom Strategy

### ISSUE THREAD

**Issue by casper5822** [ionic-team/ionic#20510] opened 2020-02-17 10:57 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

"@ionic/angular": "^5.0.0",
"@ionic-native/core": "^5.19.1",
ionic cli: 5.4.16

**Current behavior:**

Just define a custom reuse strategy and when you move between pages, this error occurs:

core.js:6014 ERROR Error: Uncaught (in promise): Error: incompatible reuse strategy
Error: incompatible reuse strategy
    at IonRouterOutlet.detach (ionic-angular.js:2501)
    at ActivateRoutes.detachAndStoreRouteSubtree (router.js:3898)
    at ActivateRoutes.deactivateRouteAndItsChildren (router.js:3881)
    at router.js:3923
    at forEach (router.js:1410)
    at ActivateRoutes.deactivateRouteAndOutlet (router.js:3918)
    at ActivateRoutes.deactivateRouteAndItsChildren (router.js:3884)
    at ActivateRoutes.deactivateRoutes (router.js:3869)
    at router.js:3826
    at Array.forEach (<anonymous>)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
defaultErrorLogger @ core.js:6014
handleError @ core.js:6066
next @ core.js:40558
schedulerFn @ core.js:35336
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35298
(anonymous) @ core.js:39738
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:39572
onHandleError @ core.js:39735
handleError @ zone-evergreen.js:363
runGuarded @ zone-evergreen.js:137
api.microtaskDrainDone @ zone-evergreen.js:663
drainMicroTaskQueue @ zone-evergreen.js:566
invokeTask @ zone-evergreen.js:469
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
**Expected behavior:**

Just use my reuse strategy.

**Steps to reproduce:**

**Related code:**
Thisi is my reuse strategy:
In my module:
  { provide: RouteReuseStrategy, useClass: CustomReuseStrategy },

The class:

import { ActivatedRouteSnapshot, RouteReuseStrategy, DetachedRouteHandle } from '@angular/router';

export class CustomReuseStrategy implements RouteReuseStrategy {

   routesToCache: string[] = ["home","archivio","wall","faq","tvpodcasts"];

   storedRouteHandles = new Map<string, DetachedRouteHandle>();

   // Decides if the route should be stored
   shouldDetach(route: ActivatedRouteSnapshot): boolean {
      if (!route.routeConfig || route.routeConfig.loadChildren) {
           return false;
      }
      return this.routesToCache.indexOf(route.routeConfig.path == "" ? route.data.path : route.routeConfig.path) > -1;
   }

   //Store the information for the route we're destructing
   store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
      this.storedRouteHandles.set(route.routeConfig.path == "" ? route.data.path : route.routeConfig.path, handle);
   }

  //Return true if we have a stored route object for the next route
   shouldAttach(route: ActivatedRouteSnapshot): boolean {
     if (route.routeConfig.path == "login" || route.data.path == "login") {
         this.storedRouteHandles.clear();
      }
      return this.storedRouteHandles.has(route.routeConfig.path == "" ? route.data.path : route.routeConfig.path);
   }

   //If we returned true in shouldAttach(), now return the actual route data for restoration
   retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
      if (!route.routeConfig) return null;
      if (route.routeConfig.loadChildren || route.routeConfig.children ) return null;
      return this.storedRouteHandles.get(route.routeConfig.path == "" ? route.data.path : route.routeConfig.path);
   }

   //Reuse the route if we're going to and from the same route
   shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
      return future.routeConfig === curr.routeConfig;
   }
}

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-02-17 14:09
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17673.

**Closed by liamdebeasi** 2020-02-17 14:09 UTC
Labels: triage
