### ISSUE TITLE
bug: ion-input has ion-invalid and ng-valid classes after clearing errors

### ISSUE THREAD

**Issue by dmironiuk** [ionic-team/ionic#20874] opened 2020-03-25 23:05 UTC
# Bug Report
I use reactive form in Angular and custom form validation function passed to `FormBuilder.group` function. In the validator I clear errors using `AbstractControl.setErrors` function. The problem is that the `ion-invalid` class is not removed from the control if it is not edited control.

In my case I have two inputs
 - password
 - repeated password
The `ion-invalid` class does not disappear from repeated password even if values are the same when I edit "password".

Here is a screenshot from element inspector:
https://pasteboard.co/J0Ncc1M.png
where you can see `ion-invalid` and `ng-valid` next to each other.

The form validation status is correct thou.

**Ionic version:**

[x] **5.0.4**

**Current behavior:**

**Expected behavior:**

Paired classes:
`ion-invalid`  and `ng-invalid`
`ion-valid` and `ng-valid`

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-03-26 14:18
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20650.

**Closed by liamdebeasi** 2020-03-26 14:18 UTC
Labels: triage
