### ISSUE TITLE
cannot build browser

### ISSUE THREAD

**Issue by lvdatri1** [ionic-team/ionic#13248] opened 2017-10-26 09:08 UTC
cannot build browser even the browser platform was added.
I sitll can build  IOS and Android 
Here is the details.
$ ionic cordova build browser
> cordova platform add browser --save
Using cordova-fetch for cordova-browser@~5.0.1
Error: Platform browser already added.
[ERROR] Exception:

------
Ionic info:
 @ionic/cli-utils  : 1.15.0
    ionic (Ionic CLI) : 3.15.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : browser 5.0.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 7

![image](https://user-images.githubusercontent.com/20944725/32044459-d1298a24-ba67-11e7-860e-06c1a1dc529c.png)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment] 2017-10-26 11:06
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an Ionic Framework issue but an Ionic CLI issue. Also, it is a duplicate of an existing CLI issue: https://github.com/ionic-team/ionic-cli/issues/2826

On another note, we do not suggest using the Cordova browser platform. Rather, we suggest not using Cordova at all for web installations.

If your code base supports both Native iOS/Android builds and web builds, we suggest using web API calls when in web rather than trying to use Cordova plugins. See the "plugins" section of the following document for details: https://ionicframework.com/docs/developer-resources/desktop-support/

Here is a good resource for what you can do from web APIs to avoid having to use plugins: https://whatwebcando.today/ 

For deployment on the web, we suggest doing `npm run ionic:build -- --prod` and then installing from the `www` directory.

Thank you for using Ionic

**Closed by kensodemann** 2017-10-26 11:06 UTC
