### ISSUE TITLE
Gesture and scroll not working on Ionic 3.7.0

### ISSUE THREAD

**Issue by polfernandez** [ionic-team/ionic#12926] opened 2017-09-19 09:59 UTC
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.7.0**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Scroll not working on list with elements containing gestures (press, swipe...).
**Expected behavior:**

List with elements containing gestures such as press, or swipe, enables scrolling.

**Steps to reproduce:**

**Related code:**

```
<ion-content>
<ion-list>
  <ng-container *ngFor="let chat of chats$ | async">
   <button
         ion-item
          tappable
          *ngIf="getContact(chat) | async as contact; else loadingContact"
          (click)="showChat(chat, $event)"
          (press)="showActionSheet(chat, $event)"
        </button>

      </ng-container>
  </ion-list>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.2
    OS                : Windows 10
    npm               : 5.0.3
```

**Comment by kensodemann** [comment] 2017-09-19 10:07
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having?

Also, can you please fill in the `ionic info` output?

Thanks for using Ionic!

**Comment by mburger81** [comment] 2017-09-20 04:18
I would suggest updating ionic-cl and ionic-angular to latest. Latest ionic cli removed aso some plugins.

**Comment by kensodemann** [comment] 2017-09-20 19:35
I tried markup very similar to what you nave in a sample application and it worked just fine. I am going to close this since it is not reproducible. If provide a sample application via GitHub that duplicates the issue I will be happy to reopen this.

**Closed by kensodemann** 2017-09-20 19:35 UTC
Labels: needs info

**Comment by shamank** [comment] 2017-10-03 22:31
This should not be closed. I can't find gestures in the docs for newer 3.7.x version. I think they were removed from core.
