### ISSUE TITLE
When IonicModule and IonicPageModule exist at the same time, an error occurs

### ISSUE THREAD

**Issue by ctc1995** [ionic-team/ionic#11487] opened 2017-05-03 02:52 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Reported an error：
      ERROR TypeError: Cannot read property '_getPortal' of undefined

**Expected behavior:**

Popover does not need to be loaded on demand, loaded when the current component is open

**Steps to reproduce:**

**Related code:**

### about.ts
`import { Component } from '@angular/core';

import { IonicPage, PopoverController } from 'ionic-angular';
import { PopoverPage } from '../about-popover/about-popover'
@IonicPage()
@Component({
  selector: 'page-about',
  templateUrl: 'about.html'
})
export class AboutPage {
  conferenceDate = '2047-05-17';

  constructor(public popoverCtrl: PopoverController) { }

  presentPopover(event: Event) {
    let popover = this.popoverCtrl.create(PopoverPage);
    popover.present({ ev: event });
  }
}`

### about.module.ts
`
import { NgModule } from '@angular/core';
import { AboutPage } from './about';
import { PopoverPage } from '../about-popover/about-popover'
import { IonicPageModule, IonicModule } from 'ionic-angular';

@NgModule({
	declarations: [
		AboutPage,
		PopoverPage
	],
	imports: [
		**IonicPageModule.forChild(AboutPage),
		IonicModule.forRoot(PopoverPage)**
	],
	entryComponents: [
		AboutPage,
		PopoverPage
	]
})
export class AboutPageModule {}

`
### about-popover.ts
`
import { Component } from '@angular/core';

import { App, IonicPage, NavController, ModalController, ViewController } from 'ionic-angular';

@Component({
  template: `
    <ion-list>
      <button ion-item (click)="close('http://ionicframework.com/docs/v2/getting-started')">Learn Ionic</button>
      <button ion-item (click)="close('http://ionicframework.com/docs/v2')">Documentation</button>
      <button ion-item (click)="close('http://showcase.ionicframework.com')">Showcase</button>
      <button ion-item (click)="close('https://github.com/driftyco/ionic')">GitHub Repo</button>
      <button ion-item (click)="support()">Support</button>
    </ion-list>
  `
})
export class PopoverPage {

  constructor(
    public viewCtrl: ViewController,
    public navCtrl: NavController,
    public app: App,
    public modalCtrl: ModalController
  ) { }

  support() {
    this.app.getRootNav().push('SupportPage');
    this.viewCtrl.dismiss();
  }

  close(url: string) {
    window.open(url, '_blank');
    this.viewCtrl.dismiss();
  }
}
`

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Reported an error：
      ERROR TypeError: Cannot read property '_getPortal' of undefined

**Expected behavior:**

Popover does not need to be loaded on demand, loaded when the current component is open

**Steps to reproduce:**

**Related code:**

`import { Component } from '@angular/core';

import { IonicPage, PopoverController } from 'ionic-angular';
import { PopoverPage } from '../about-popover/about-popover'
@IonicPage()
@Component({
  selector: 'page-about',
  templateUrl: 'about.html'
})
export class AboutPage {
  conferenceDate = '2047-05-17';

  constructor(public popoverCtrl: PopoverController) { }

  presentPopover(event: Event) {
    let popover = this.popoverCtrl.create(PopoverPage);
    popover.present({ ev: event });
  }
}`

`
import { Component } from '@angular/core';

import { App, IonicPage, NavController, ModalController, ViewController } from 'ionic-angular';

@Component({
  template: `
    <ion-list>
      <button ion-item (click)="close('http://ionicframework.com/docs/v2/getting-started')">Learn Ionic</button>
      <button ion-item (click)="close('http://ionicframework.com/docs/v2')">Documentation</button>
      <button ion-item (click)="close('http://showcase.ionicframework.com')">Showcase</button>
      <button ion-item (click)="close('https://github.com/driftyco/ionic')">GitHub Repo</button>
      <button ion-item (click)="support()">Support</button>
    </ion-list>
  `
})
export class PopoverPage {

  constructor(
    public viewCtrl: ViewController,
    public navCtrl: NavController,
    public app: App,
    public modalCtrl: ModalController
  ) { }

  support() {
    this.app.getRootNav().push('SupportPage');
    this.viewCtrl.dismiss();
  }

  close(url: string) {
    window.open(url, '_blank');
    this.viewCtrl.dismiss();
  }
}
`
![image](https://cloud.githubusercontent.com/assets/17734754/25646638/ddf036f0-2fec-11e7-8c5e-64b5abc8a661.png)

**Comment by jgw96** [comment] 2017-05-03 14:14
Hello, thanks for using Ionic! Could you post a minimal repo we could use to reproduce this issue, please?

**Comment by ctc1995** [comment] 2017-05-04 03:10
@jgw96 
You can get a demo from [ionic-conference-app-lazy-load](https://github.com/driftyco/ionic-conference-app/tree/lazy-load )

I tried to do somthing:
1. Cancel the popover module
2. Clear @IonicPage from popover.ts
3. **`import {PopoverPage} from popover.ts `**in About.module.ts
4. In the About.ts **`import {PopoverPage} from popover.ts`**, and through this.popoverCtrl.create (PopoverPage), to use it;

As a result, I will get a mistake `Cannot read property '_getPortal' of undefined`

What should I do when I want to cancel the lazy load on the About page Popover?

**Comment by sfabriece** [comment] 2017-05-07 00:07
When can we expect a fix for this issue?

**Comment by sfabriece** [comment] 2017-05-07 00:08
PS: This issue is probably wrongly labeled, shouldn't it be `v3`?

**Comment by ctc1995** [comment] 2017-05-08 00:15
@sfabriece  I also think it should be defined as V3 tags

**Comment by ctc1995** [comment] 2017-05-08 00:16
@jgw96 Any progress?  Please feedback. Thanks!

**Comment by rapropos** [comment] 2017-05-08 23:14
What happens if you swap just `IonicModule` for where you currently have `IonicModule.forRoot(PopoverPage)`?

**Comment by ctc1995** [comment] 2017-05-09 01:48
@rapropos I can get  ` ERROR TypeError: Cannot read property '_getPortal' of undefined `

**Comment by liuren78** [comment] 2017-05-14 03:16
I have the same problem too.
If the lazy loading pages used present() Method of the Controller，the error "ERROR TypeError: Cannot read property '_getPortal' of undefined"  was happened.

**Comment by paolocezar91** [comment] 2017-05-15 16:24
I am having a similar issue when using [ionic2autocomplete](https://github.com/kadoshms/ionic2-autocomplete). 
According to the autocomplete docs, i have to add its Module to the page Module. When I do that the plugin works fine, but when i try to call .present() on either a toast element or a loading element it crashes with the same error as described above. 

Perhaps because the ionic2autocomplete loads the IonicModule?

**Comment by ctc1995** [comment] 2017-05-21 11:59
@jgw96 Can you help us ? or any info.

**Comment by jgw96** [comment] 2017-06-05 14:43
Hello all! Update on this issue: We are currently doing a big overhaul of our navController and how it works with lazy loading. We are also working with the angular team on improving how code splitting works with Angular. We are hoping to have these fixes in the next release if testing of it goes well.

**Comment by ag14774** [comment] 2017-08-16 11:52
Any news on this? When should we be expecting the next release?

**Comment by ioshackeru** [comment] 2017-09-26 20:06
this solved the problem for me:

```
imports: [
    IonicModule
  ],

```
instead of:
```
imports: [
 IonicModule.forRoot(PopoverPage)
]
```

**Comment by toffebjorkskog** [comment] 2017-10-27 08:31
@ioshackeru That did the trick for me

**Comment by kensodemann** [comment] 2018-01-03 03:20
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 03:20 UTC
Labels: needs info, v3

**Comment by beerinho** [comment] 2018-05-29 14:12
@iligzar found the solution on this thread https://github.com/twinssbc/Ionic2-Calendar/issues/283 
at least it was able to sort the issue I was having.
