### ISSUE TITLE
iOS (click) fires twice on device iphone 7 iOS 10.3.1.

### ISSUE THREAD

**Issue by jorgemejia** [ionic-team/ionic#11510] opened 2017-05-04 16:49 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
click event fires twice.

**Expected behavior:**
 Click event have to be fired once 

**Steps to reproduce:**
Click on the button Alert -> first time works fine
Click again the button Alert -> this event fires twice 👎 

**Related code:**

I'm using the following code in my home.html

```
<div padding>
    <button ion-button full (click)="TestAlert()">Alert</button>
  </div>
```

And this is the home.ts

```
TestAlert(){

     console.log('Hola');
     alert('Hola');
  }
```

**Other information:**

This is the repo for the project for taste it and reproduce it.

[Project](https://github.com/jorgemejia/PersonalProject2)

**Ionic info:**

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.3.2 Build version 8E2002

```

**Comment by jgw96** [comment] 2017-05-04 19:03
Hello, thanks for using Ionic, we will look into this.

**Comment by jgw96** [comment] 2017-06-05 15:37
Hello @jorgemejia is this still an issue with the latest release of Ionic ?

**Comment by jgw96** [comment] 2017-06-06 16:48
Hello all! Because I can no longer reproduce this issue I am going to close this for now. Thanks for using Ionic!

**Closed by jgw96** 2017-06-06 16:48 UTC
Labels: needs info, platform:ios, tap/click, v3
