### ISSUE TITLE
Badge color in ion-tab not working (Ionic 4 beta 11)

### ISSUE THREAD

**Issue by russcarver** [ionic-team/ionic#15767] opened 2018-09-27 00:07 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/rc101077/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.11.4 (/Users/rc101077/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
The badgeColor attribute/input property in ion-tab is not coloring the badge.

**Steps to Reproduce**
1. Create a basic Ionic tabs project.
2. Add a tab with a badge and badgeColor
3. The badge color remains that of `--ion-color-primary`

**Related Code**
```
<ion-tab [hidden]="!authenticated" label="Messages" [show]="authenticated" (ionSelect)="tabsChanged('messages')" icon="mail" [badge]="2" [badgeColor]="'#ff0000'" href="/tabs/(tabM:messages)">
  <ion-router-outlet name="tabM"></ion-router-outlet>
</ion-tab>
```

**Expected Behavior**
The badge color should be red in the example above.

**Additional Context**
I've also tried the following without success:
`[badgeColor]="danger"`
`[badgeColor]="red"`
`[badgeColor]="#ff0000"`
`[badgeColor]="ff0000"`
`[badgeColor]="rgb(255,0,0)"`

These add single quotes inside the string
`[badgeColor]="'danger'"`
`[badgeColor]="'red'"`
`[badgeColor]="'#ff0000'"`
`[badgeColor]="'ff0000'"`
`[badgeColor]="'rgb(255,0,0)'"`

`badge-color="danger"`
`badge-color="red"`
`badge-color="#ff0000"`
`badge-color="ff0000"`
`badge-color="rgb(255,0,0)"`

These add single quotes inside the string
`badge-color="'danger'"`
`badge-color="'red'"`
`badge-color="'#ff0000'"`
`badge-color="'ff0000'"`
`badge-color="'rgb(255,0,0)'"`

**Comment by brandyscarney** [comment] 2018-09-27 14:19
Thank you for the issue! Closing as a duplicate of https://github.com/ionic-team/ionic/issues/14840. Please track this problem on that issue. 🙂

**Closed by brandyscarney** 2018-09-27 14:19 UTC
Labels: triage
