### ISSUE TITLE
No space between ion-icon and text inside a ion-list element when using "rtl"

### ISSUE THREAD

**Issue by arLevi** [ionic-team/ionic#12629] opened 2017-08-09 21:28 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[X] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm using `$app-direction: rtl;`
When using 
```
<ion-list>
                <ion-list-header> Generic </ion-list-header>
                <ion-item (click)="setCategory('back')">
                    <ion-icon item-start name="alarm"></ion-icon>
                    Alarm
                </ion-item>
</ion-list>
```
The text is being converted into: `ion-icon` & `ion-label`, but the CSS it receive is:
```
# main.css
[dir="rtl"] .label-ios {
  margin-right: 0;
  margin-left: 8px;
}
```
So there's no space between the icon and the text ...
I also tried to use `margin-horizontal` on `ion-icon` tag - but that didn't do anything.

**Expected behavior:**
For some reason, setting `margin-right: 0;` -> `margin-right: 8px;` fixes the issue, 
but according to the docs - you were trying to keep "right" as a real "right" in rtl ...

**Steps to reproduce:**
too bad the plunker doesn't use SCSS ... :/

![screen shot 2017-08-10 at 12 26 14 am](https://user-images.githubusercontent.com/1129836/29144708-8fc29202-7d62-11e7-9d31-ad3eb690033f.png)

**Comment by AmitMY** [comment] 2017-08-10 07:44
Can you please make a reproduction in StackBlitz? (create an ionic project, and set it up like you have set up your project).
It is odd, and I feel like you must be doing something wrong, as look at the images here - http://blog.ionic.io/ionic-and-rtl/ - seems great on RTL, including the toggle, icons, etc.
[This](https://github.com/AmitMY/ionic-rtl-demo) is the project those screenshots were taken from.

Unrelated Tip:
Always use `<ion-label>` inside `ion-item`, as it will become mandatory in the next major release (^4.0.0), because of web components constraints

**Comment by AmitMY** [comment] 2017-08-10 07:46
Actually nevermind. I just now saw that you are using version 2.
We did RTL support in 3.4.0, and it is a simple upgrade process (go over the changelog since v3, and do the steps)

**Comment by jgw96** [comment] 2017-08-10 17:30
Hello all! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12630

**Closed by jgw96** 2017-08-10 17:30 UTC

**Comment by arLevi** [comment] 2017-08-11 12:13
This is a great tool: https://stackblitz.com/edit/ionic-ekw7sa?file=pages%2Fhome%2Fhome.html
But has no SCSS support, only CSS, so I'm not sure how I'm suppose to add `$app-direction: rtl;`

I'll take a look at the links you've added - and try to make a plunker
