### ISSUE TITLE
bug: ionic cordova build build.gradle 

### ISSUE THREAD

**Issue by hakanguzel** [ionic-team/ionic#18031] opened 2019-04-14 16:53 UTC
When I run

ionic cordova build android --prod --release code error

it produces

Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Hakan\AppData\Local\Android\sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :CordovaLib
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Ionic\ProjeName\platforms\android\CordovaLib\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 2s
**C:\Ionic\ProjeName\platforms\android\gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.**

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Ionic\ProjeName\platforms\android\CordovaLib\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**BU�LD FAILED in 2s
[ERROR] An error occurred while running subprocess cordova.**

        cordova build android --release exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by liamdebeasi** [comment] 2019-04-15 13:07
Hi there,

I am going to close this as it is an issue with running `cordova build android`, not something with Ionic Framework. For help with this issue feel free to post on our [forums](https://forum.ionicframework.com/) or our [slack](https://ionicworldwide.herokuapp.com/). Additionally, it looks like the problem is with the `com.github.dcendents.android-maven` plugin, so you might want to try Googling the error in relation to that.

Thanks!

**Closed by liamdebeasi** 2019-04-15 13:07 UTC
Labels: triage

**Comment by morfeoo** [comment] 2019-04-21 21:25
merhaba hocam problemi çözebildiniz mi ben de aynı şeyi yaşıyorum?

**Comment by serdartaylan** [comment] 2019-05-10 20:02
sorunu çözebien varmı?

**Comment by light8822** [comment] 2019-05-31 21:41
did you find any solution I'm having the same issue

**Comment by mervfar** [comment] 2019-06-01 12:53
I have same problem,is there any solution?
