### ISSUE TITLE
bug: Ionic doesn't recognise visual studio android emulator

### ISSUE THREAD

**Issue by GuerrillaCoder** [ionic-team/ionic#20573] opened 2020-02-20 18:28 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When running `ionic cordova run android --verbose` with VS android emulator running the following error occurs:

> [native-run] 2020-02-20T18:19:17.813Z native-run Caught fatal error: RunException [Error]: No targets devices/emulators available. Cannot create AVD because there is no suitable API installation. Use --sdk-info to reveal missing packages and other issues.
> [native-run]     at selectDevice (C:\nvm\v12.13.0\node_modules\native-run\dist\android\run.js:97:19) {
> [native-run]   code: 'ERR_NO_TARGET',
> [native-run]   exitCode: 1,
> [native-run]   data: undefined
> [native-run] }

**Expected behavior:**

Expected behaviour would be for it to detect the visual studio emulator and launch the app on it.  The visual studio android emulator docs say that it should act like a normal phone connected to a computer and I have read articles saying it can be done with Ionic but I am unable to get Ionic to recognise the emulator as a device.

I use Hyper-V to run the API so I really need to be able to get the app working in a Hyper-V compatible emulator so I can debug API and app together.

**Steps to reproduce:**

1. Launch visual studio emulator for android
2. click play on the prefrerred image (i have tried multiple all with same results)
3. enable usb debugging on device
4. run  `ionic cordova run android --verbose`

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (C:\nvm\v12.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.2.2
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 8 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2020-02-20 18:31
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. As the error states, your app cannot be run on the device because you do not have the appropriate version of the Android SDK installed (`Cannot create AVD because there is no suitable API installation.`).

You should use the `--sdk-info` flag as the error suggests to see the packages you are missing.

**Closed by liamdebeasi** 2020-02-20 18:31 UTC
Labels: triage

**Comment by GuerrillaCoder** [comment] 2020-02-20 18:42
Can you re-read it please and double check that is the case.  I am not trying to launch android emulator.  The pertinent issue is it doesn't recognise the device.  I 100% have the correct SDK installed (I can connect to actual device, but not the VS emulator).

I think what you say would be correct if I was trying to use the android studio emulator but I am not.  I am first initiating the visual studio for android emulator as it runs on Hyper-V.

Thank you for your time.

Here is the SDK I have installed

```
native-run --sdk-info

  Usage: native-run [ios|android] [options]

  Options:

    -h, --help ........... Print help for the platform, then quit
    --version ............ Print version, then quit
    --verbose ............ Print verbose output to stderr
    --list ............... Print connected devices and virtual devices

PS E:\Clients\campbelloil\campbelloil-app> native-run android --sdk-info
SDK Location:         C:\Users\Mike\AppData\Local\Android\Sdk
AVD Home:             C:\Users\Mike\.android\avd

API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  4
                      Sources for Android 29  sources;android-29  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-29;google_apis_playstore;x86  /.+/


API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Sources for Android 28  sources;android-28  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  /.+/


API Level:            27
Packages:             Android SDK Platform 27  platforms;android-27  3
                      Sources for Android 27  sources;android-27  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-27;google_apis_playstore;x86  /.+/


API Level:            26
Packages:             Android SDK Platform 26  platforms;android-26  2
                      Sources for Android 26  sources;android-26  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-26;google_apis_playstore;x86  /.+/


API Level:            23
Packages:             Android SDK Platform 23  platforms;android-23  3
                      Sources for Android 23  sources;android-23  1


API Level:            22
Packages:             Android SDK Platform 22  platforms;android-22  2
                      Sources for Android 22  sources;android-22  1


API Level:            21
Packages:             Android SDK Platform 21  platforms;android-21  2
                      Sources for Android 21  sources;android-21  1


API Level:            20
Packages:             Android SDK Platform 20  platforms;android-20  2
                      Sources for Android 20  sources;android-20  1


API Level:            19
Packages:             Android SDK Platform 19  platforms;android-19  4
                      Sources for Android 19  sources;android-19  2


API Level:            18
Packages:             Android SDK Platform 18  platforms;android-18  3
                      Sources for Android 18  sources;android-18  1


API Level:            17
Packages:             Android SDK Platform 17  platforms;android-17  3
                      Sources for Android 17  sources;android-17  1


API Level:            16
Packages:             Android SDK Platform 16  platforms;android-16  5
                      Sources for Android 16  sources;android-16  2


Tools:

Android Emulator  emulator  30.0.0
Android SDK Build-Tools 29.0.3  build-tools;29.0.3  29.0.3
Android SDK Platform-Tools  platform-tools  29.0.6
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1
```

**Comment by liamdebeasi** [comment] 2020-02-20 20:44
Ionic Framework does not manage deploying your app to a device. Adding `ionic` at the beginning of the command just compiles your app before deploying. A good check would be to see if `cordova run android --verbose` works.

**Comment by GuerrillaCoder** [comment] 2020-02-20 21:20
OK, I will raise issue in cordova.  Thanks
