### ISSUE TITLE
In Mobile device ion-content background set to default White Color

### ISSUE THREAD

**Issue by anup5708** [ionic-team/ionic#13739] opened 2017-12-31 08:56 UTC
Hi Team,

Below is my code.
```
<ion-content style="background-color: #c93e393d">
</ion-content>
```
After that I added Android platform and run the command `ionic cordova run android`.

While `ionic serve` , in browser it reflects the color what I expected.
But in mobile device there is no change found ion-content background-color still it show me white background color.

**Comment by Crystal0** [comment] 2018-01-01 05:25
Create and copy your code into the new project. Build and run it...
I had the same issue

**Comment by kensodemann** [comment] 2018-01-02 22:41
Hello! Thank you for opening an issue with us!

I am closing this as it is not an issue with Ionic Framework. The issue is that your color specification uses the alpha channel which is not well supported on mobile devices (see the mobile tab of browser compatibility section here: https://developer.mozilla.org/en-US/docs/Web/CSS/background-color).

When I run code with your background color on an Android device and examine it in Chrome's remote debug, it tells me the color is not being used because it is invalid.

When I run the same code on my iPhone 7, it shows a background color, just not the one I would expect, because it is not properly handling the alpha channel.

If you remove the alpha channel and just specify a pure color it works fine.

Thank you for using Ionic

**Closed by kensodemann** 2018-01-02 22:41 UTC
