### ISSUE TITLE
bug: android page-back animation ends with "flash" of previous page (since 4.10.0)

### ISSUE THREAD

**Issue by chriswep** [ionic-team/ionic#19552] opened 2019-10-04 16:04 UTC
# Bug Report

**Ionic version:**
[x] **4.10.0**

**Current behavior:**
When navigation back, the previous page briefly flashes over the destination page after animation ended.

**Expected behavior:**
no flash of previous page after page-back animation

**Comment by liamdebeasi** [comment] 2019-10-04 16:05
Thanks for the issue. Can you provide steps to reproduce? Also which device are you testing this on?

**Comment by liamdebeasi** [comment] 2019-10-04 16:43
Never mind, I was able to reproduce this 🙂. Looks like this is a duplicate of https://github.com/ionic-team/ionic/issues/19491, so I am going to close this issue in favor of that one.

I will post any updates on that thread. Thanks!

**Closed by liamdebeasi** 2019-10-04 16:43 UTC
Labels: needs: reply

**Comment by chriswep** [comment] 2019-10-04 16:45
> Never mind, I was able to reproduce this 

ok @liamdebeasi , anyway, since i was already writing this, maybe it helps debugging: 

currently tested on API 26 and 29 emulator. iOS works fine, chrome (77) and firefox(70) browsers also work. i did an additional test on a (very slow) API 22 device and there i can't see the issue.

for me it happens on every page when navigating back. sometimes the effect is more "prominent", sometimes more subtle. So it feels like sort of a timing issues with the animations. on 4.8.1 the animation is fine, if i switch to 4.10.0 the issue appears (both on production and dev build).

**Comment by liamdebeasi** [comment] 2019-10-04 16:50
Ok thanks! Do you notice the issue on 4.9.0 at all?

**Comment by chriswep** [comment] 2019-10-04 17:24
> Ok thanks! Do you notice the issue on 4.9.0 at all?

seems fine on 4.9.1

**Comment by liamdebeasi** [comment] 2019-10-04 18:32
Can you try this dev build and let me know if this fixes the issue for you? `npm i @ionic/angular@4.11.0-dev.201910041827.7768ab2`

**Comment by chriswep** [comment] 2019-10-04 22:27
> Can you try this dev build and let me know if this fixes the issue for you? `npm i @ionic/angular@4.11.0-dev.201910041827.7768ab2`

seems to work

**Comment by bZez** [comment] 2019-10-17 13:09
Same here with 4.11.1...

![demot](https://i.ibb.co/hdBZBhD/demo.gif)
