### ISSUE TITLE
bug: ionic-angular, after opening my app through dynamic link the view will not update correctly

### ISSUE THREAD

**Issue by armanhadifatah** [ionic-team/ionic#20928] opened 2020-03-31 20:35 UTC
# Bug Report

**Ionic version:**
 ionic 5.0.7

**Current behavior:**
    First my app is work perfect on the  web browser on my computer but this but occur when i test dynamic links on my android device capacitor app.

    i have an app which shows listing of properties when someone click on the dynamic link it will open the app and show that property but when you navigate back and see the listing and want to scroll for more property it will not show properties that fetched form server so i tested every thing its getting new items the array will update but the view will not show any thing till i go to an other tab an come back it will show those listing which was fetched but for new fetching it will not show.

I came around with a fix when i fetch new listing i run NgZone then it will show 

As i mentioned this is just happening if the app is close then open through dynamic link.

I think if this bug happening for dynamic link it will happen also for push notification!

**Expected behavior:**
show the listing when array got new data ( update the view )

**Steps to reproduce:**
Have an app with dynamic link , then open a specific item with dynamic link , after it open click on back button for example to go to home tab then scroll to see more data the view will not update

**Related code:**

This is just a code for my solution when i fetch more data to make view update

 ```
loadData(event) {
    this.zone.run(()=>{
        this.searchService.setIsOnSearch(true);
        this.estateService.addPageNumber();
        this.getEstates().then(
          value => { event.target.complete(); }
        );
      }
    );
  }

```

**Ionic info:**
   ```
Ionic:

   Ionic CLI                     : 6.4.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.901.0
   @angular-devkit/schematics    : 9.1.0
   @angular/cli                  : 9.1.0
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Cordova:

   Cordova CLI       : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/arman/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v12.16.1 (/usr/local/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4 Build version 11E146
```

**Comment by liamdebeasi** [comment] 2020-03-31 21:13
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Ionic Framework does not manage dynamic links or native plugins.

For help with this issue, I recommend posting on our [forums](http://forum.ionicframework.com/).

**Closed by liamdebeasi** 2020-03-31 21:13 UTC
Labels: triage
