### ISSUE TITLE
bug: ion-select multiple does not update value when [(ngModel)] is updated asynchronously in code

### ISSUE THREAD

**Issue by reed-lawrence** [ionic-team/ionic#21353] opened 2020-05-21 15:15 UTC
# Bug Report

**Ionic version:**
Ionic Version 5.0.5

**Current behavior:**
An ion-select component does not display the matching value when the value is updated from code. Clicking on the ion-select component triggers the detection and the correct value will be displayed.

**Expected behavior:**
The ion-select should reflect the correct value according to the provided comparewith function and the ngModel.

**Related code:**
Example here. The ion-select shows empty upon page load, when the foobar function is actually modifying the [(ngModel)] 100ms after loading. However, this is not reflected in the ion-select until you click it.

https://stackblitz.com/edit/ionic-angular-v5-sfo7yj

**Comment by liamdebeasi** [comment] 2020-05-21 15:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19324. (The specific issue is different, but I think both have the same underlying cause.)

**Closed by liamdebeasi** 2020-05-21 15:24 UTC
Labels: triage
