### ISSUE TITLE
ion-virtual-scroll does not update after an element is removed from the items array.

### ISSUE THREAD

**Issue by 18certel** [ionic-team/ionic#17371] opened 2019-02-03 20:19 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When removing an element from the array associated with the [items] property of an ion-virtual-scroll, the item is not removed from the view.

**Expected behavior:**

The view should be updated and remove the item from the list. This was the behavior before upgrading to v4.

**Steps to reproduce:**

**Related code:**

```
  <ion-virtual-scroll [items]="items" approxItemHeight="100px">
    <ion-item-sliding *virtualItem="let item">

      <ion-item>
        <ion-thumbnail slot="start">
          <ion-img src="{{ item.image }}"></ion-img>
        </ion-thumbnail>

        <p>{{ item.title }}</p>
      </ion-item>

      <ion-item-options side="end">
        <ion-item-option (click)="remove(item)">Remove</ion-item-option>
      </ion-item-options>

    </ion-item-sliding>
  </ion-virtual-scroll>


  remove(item) {
    this.items.splice(this.items.indexOf(item), 1);
  }

```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5, osx 4.0.2
   Cordova Plugins       : cordova-plugin-ionic 5.2.1, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/caseertel/Library/Android/sdk)
   NodeJS            : v8.9.0 (/usr/local/bin/node)
   npm               : 5.5.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by norbertbede** [comment] 2019-02-05 21:13
same here.

**Comment by Silvest89** [comment] 2019-02-06 16:27
Have you tried 
```
this.items.splice(this.items.indexOf(item), 1);
this.items = [...this.items];
```

**Comment by Arieru** [comment] 2019-03-13 12:31
same here.

**Comment by Mazus** [comment] 2019-03-19 14:18
Still the case in 4.1.1

**Comment by DavidWiesner** [comment] 2019-03-20 05:31
Recreating the items array like @Silvest89 suggest work for me. I can not reproduce this issue

**Comment by marko-gledic** [comment] 2019-03-22 23:32
Still the case in 4.1.2

**Comment by Mazus** [comment] 2019-03-23 08:42
It's true that @Silvest89 workaround works, but that's still an issue, right ?

**Comment by Silvest89** [comment] 2019-03-23 09:31
Angular does not detect the change until the variable value gets a new value. It's about immutability. Mutating an array is not a new value (still the same array)

**Comment by Mazus** [comment] 2019-03-23 09:57
@Silvest89, still if you use ngFor directive and do the exact same thing, it works. So angular do detect the change. So it must be related to the virtual-scroll component.

**Comment by martijnlutgens** [comment] 2019-04-12 14:15
I am currently on Ionic 4.2.0. and I have the same kind of problem with just a regular *ngFor. But only when when updating the list async (I normally use Observables). Even when spreading the array the list doesn't update until a click on the page.

@liamdebeasi I have made an example here: https://github.com/martijnlutgens/ionicListRemoveItem/.

Somehow removing an item works only the first time. After that you have to click on the page to trigger changeDetection.

Any idea when this will be on deck?

**Comment by liamdebeasi** [comment] 2019-04-12 14:23
Hi everyone,

Thanks for bringing this to our attention. For performance reasons, Stencil (the web component compiler that Ionic uses) only compares references for running change detection, not the data inside of arrays or objects.

This means that the standard mutable array operations such as `this.items.splice(this.items.indexOf(item), 1);` will not trigger change detection.

In this scenario, you will want to do what @Silvest89 suggested above:

```
this.items.splice(this.items.indexOf(item), 1);
this.items = [...this.items];
```

The `...` is the Spread operator which "expands" the given object in place: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

You can learn more about how Stencil handles change detection here: https://stenciljs.com/docs/reactive-data

I am going to close this, but for further questions feel free to post on our [forum](http://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Closed by liamdebeasi** 2019-04-12 14:23 UTC

**Comment by martijnlutgens** [comment] 2019-04-12 15:12
Ok but in my example I am using the Spread operator and still changeDetection is not triggered....

**Comment by liamdebeasi** [comment] 2019-04-12 16:43
Hi @martijnlutgens,

The issue you are describing appears to be a different issue. It looks like NgZone is not picking up on changes fired via an alert handler. 

I filed a new bug report for it here: https://github.com/ionic-team/ionic/issues/18025

As a temporary workaround, you can do:

```
import { NgZone } from '@angular/core';

...

constructor(private zone: NgZone) {}

...

removeItem() {
   ...
  handler: () => {
    setTimeout(() => {
      this.zone.run(() => {
        ...
      });
    }, 500);
  }
   ...
}
