### ISSUE TITLE
Virtual scroll with responsive list items not refreshing layout

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic#12258] opened 2017-07-05 07:28 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I have a list of responsive items, so that on a narrow screen we have a single list, and on a wider, (e.g. landscape) we have 2 or more. I now wish to make this list virtual however I find when I switch from portrait to landscape, the items to not fresh to now show two columns (or sometimes one of two rows will show 2 columns). It is close to working. If you load the app while in landscape, and change to portrait, it will adjust correctly, though sometimes you need to scroll to refresh it to see the items. 

If you open the app on portrait, and change to landscape, it normally just shows the single column of items.

**Expected behavior:**
The list updates it's layout when a phone changes orientation.

**Steps to reproduce:**
I have attempted to reproduce in a plunk [here](http://plnkr.co/edit/1d7gDF?p=preview), but it does not seem to quite work as I see it when running in a proper Ionic project (eg either in the browser using Ionic serve, or built and running on a device). I have a public repo [here](https://Peterjc2007@bitbucket.org/Peterjc2007/virtualscrollpublic.git) that shows it better. 

I have a post about it [here](https://stackoverflow.com/questions/44714783/ionic-virtual-scroll-with-responsive-list-items) and [here](https://forum.ionicframework.com/t/ionic-virtual-scroll-with-responsive-list-items/95890)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
mm00845:virtualviewtest Development$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 3.10.10 
```

**Comment by AmitMY** [comment] 2017-07-05 09:04
Compliments (but not really a duplicate) of https://github.com/ionic-team/ionic/issues/12133

**Comment by jgw96** [comment] 2017-07-05 15:17
Hello all! I have made #12133 more generalized as this issue and that issue are both caused by the same underlying bug, just slightly different symptoms. I am going to close this issue but will be copying the information from this issue to that one. Thanks!

**Closed by jgw96** 2017-07-05 15:17 UTC
