### ISSUE TITLE
ion-datetime and ion-label position="floating" don't behave as expected

### ISSUE THREAD

**Issue by Aljumaily** [ionic-team/ionic#18937] opened 2019-07-29 20:15 UTC
I have the following code snippet:
```
<form>
    <ion-item>
        <ion-label position="floating">Full Name</ion-label>
        <ion-input type="text"></ion-input>
    </ion-item>
    <ion-item>
        <ion-label position="floating">Date of Birth</ion-label>
        <ion-datetime>displayFormat="MMM DD YYYY" </ion-datetime>
    </ion-item>
</form>
```

The problem is that as soon the compilation completes, the label _Date of Birth_ is small as if the user has tapped on it. For consistency reasons, I think it should have the same effect as the _Full Name_ text box as shown below:

![Output](https://user-images.githubusercontent.com/44656681/62079065-f1142080-b21b-11e9-950a-d39ba2aaa907.gif)

**Comment by GerardoTovar** [comment] 2019-07-31 11:30
try this code

<ion-datetime displayFormat="MMM DD YYYY" value="null"></ion-datetime>

**Comment by Aljumaily** [comment] 2019-07-31 19:03
> try this code
> `<ion-datetime displayFormat="MMM DD YYYY" value="null"></ion-datetime>`

Thank you soooo much! It works as expected :)

**Comment by brandyscarney** [comment] 2020-01-08 17:49
Thanks for the issue! I'm not able to reproduce this with latest so I am going to close this, but if you're still running into it please provide steps to reproduce: https://codepen.io/brandyscarney/pen/xxbYoQa

**Closed by brandyscarney** 2020-01-08 17:49 UTC
Labels: triage
