### ISSUE TITLE
v4: cli rc 11 get white screen on android

### ISSUE THREAD

**Issue by c350156378** [ionic-team/ionic#14810] opened 2018-07-20 01:31 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (D:\Users\Administrator\AppData\Roaming\nvm\v8.11.1\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.2
   @angular-devkit/schematics : 0.7.0-rc.2
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 7

Environment:

   ANDROID_HOME : C:\Users\Administrator\AppData\Local\Android\sdk
```

**Describe the Bug**
generate project with cli rc11, run it on my android phone ,get whitescreen;
rm webview plugin and readd the beta version, run again. still whitescreen;

**Steps to Reproduce**
1. run cli, choose angular type
2. rm cordova-plugin-ionic-webview
3. readd cordova-plugin-ionic-webview@beta
4. run the app on android, get white screen

**Related Code**
inspect with chrome and get the error below
```
 Uncaught SyntaxError: Unexpected token function     vendor.js:65052
```
which refers to the async function attachComponent in
```
/***/ "./node_modules/@ionic/core/dist/collection/utils/framework-delegate.js":
```

**Comment by kinggolf** [comment] 2018-07-21 04:09
@c350156378 I just upgraded an active development to ionic/angular to 4.0.0-alpha.11 & is working OK. I did see the 'white screen' previously, but OK now.
Ionic info:
```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.11
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.11
   @ionic/schematics-angular  : 1.0.0-rc.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0 ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.1 (/usr/local/bin/node)
   npm               : 6.1.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/golftocs/Library/Android/sdk
```
Ran following commands:
`ionic cordova plugin rm cordova-plugin-ionic-webview`
`ionic cordova plugin add cordova-plugin-ionic-webview@beta`
I think your issue is known - see [here](https://github.com/ionic-team/ionic-cli/issues/3363).

**Comment by c350156378** [comment] 2018-07-21 05:44
@kinggolf try your way,the same issue.
btw, i checked with 4.0.0-rc7, the way you suggested works.

**Comment by c350156378** [comment] 2018-08-02 08:08
WebView 49.0.2623.91, i got this when remote debug with chrome, it seems with this.what can i do?

**Comment by dzik1331** [comment] 2018-08-14 11:10
Hi i have similar problem but on IOS
<pre>
Ionic:
   ionic (Ionic CLI)          : 4.0.6
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular/core              : 6.1.1
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.6
   @ionic-native/core         : 5.0.0-beta.15
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:
   NodeJS            : 8.11.3
   npm               : 5.6.0
   OS                : macOS High Sierra 10.13.6
</pre>

<span>**_SyntaxError: Unexpected keyword 'function'_**</span> and white screen

**Comment by pinne65** [comment] 2018-08-20 05:53
ionic start myApp tabs --type=angular
cd myApp
ionic serve =>
White screen
framework-delegate.js:1Uncaught SyntaxError: Unexpected token function

BUT
ionic start myAppNoAng
cd myAppNoAng
ionic serve =>
OK


Ionic:
   ionic (Ionic CLI)          : 4.1.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.11.4 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : Linux 4.4 (Ubuntu 16.04)

**Comment by c350156378** [comment] 2018-08-24 13:26
refers to #15191

**Comment by mhartington** [comment] 2018-09-17 16:05
closing as duplicate of https://github.com/ionic-team/ionic/issues/15438

**Closed by mhartington** 2018-09-17 16:05 UTC
Labels: triage
