### ISSUE TITLE
Ionic 2 rc3 after modal close another input focus and keyboard open

### ISSUE THREAD

**Issue by ykonstant** [ionic-team/ionic#9474] opened 2016-12-03 06:44 UTC
I have input 
<ion-input type="text" formControlName="trip_id" placeholder="Tag Trip" (tap)="showAutoFill()" (focus)="showAutoFill()" [(ngModel)]="trip.title" readonly></ion-input>

when we select search item modal close, and another input is focused & keyboard is open

**Comment by jgw96** [comment] 2016-12-05 15:52
Hello, thanks for opening an issue with us! Would you be able to provide a [plunker]( http://plnkr.co/edit/GJte2b?p=preview) that I can use to reproduce this issue?

**Comment by Tobiaswk** [comment] 2016-12-13 19:40
Can also confirm this. It only happens on iOS not Android. Here's a plunker; http://plnkr.co/edit/0RpQAN15SKOAYjO7BDUo

If the keyboard is up and you call dismiss on the ViewController the keyboard stays up. This behavior only happens on iOS. You can only get the keyboard down again if you select another input somewhere.

**Comment by kensodemann** [comment] 2018-01-03 20:31
Hello all! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-03 20:31 UTC
Labels: needs reply, v2
