### ISSUE TITLE
bug: Vertical slides rendering incorrect layout with ion-tabs and Keyboard

### ISSUE THREAD

**Issue by mateusduraes** [ionic-team/ionic#19306] opened 2019-09-09 12:53 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When the page is rendered for the first time, everything is ok. But, when the Keyboard is toggled (opened and then closed), the layout gets completely broken. Seems like the `ion-content` element starts to fill the entire page (including the space that was reserved for `ion-tabs`).

**Expected behavior:**

The rendering of the ion-content / ion-slides or any element should not be impacted by the delay of rendering of the ion-tabs or the keyboard toggle issues.

**Steps to reproduce:**

Just run the following application in an Android device, open the console inside the inspector and trigger the keyboard directly from the code.

```
Keyboard.show()
Keyboard.hide()
Keyboard.show()
Keyboard.hide()
```

**Related code:**

[Example Application to illustrate the bug](https://github.com/mateusduraes/ionic4-vertical-slider)

**Other information:**

I wrote an example application to show the bug. You will need to trigger the Keyboard from the console. But, of course, in my real application, there is `ion-inputs / ion-textarea` to trigger the Keyboard. If the page is rendered in the DOM, I can trigger the layout for another page/modal to replicate the bug.

I tried many solutions but didn't have success in any one of the following:

* Change ion-slides / ion-slide for another wrapper of swiper.js
* Listen to `keyboardHide` and call a function called `slides.update()`
* Listen to `keyboardHide` and call a function called `changeDetectorRef.detectChanges()`

Guys, I think this is a serious bug. Now I have an application published with this problem. I tried to give a lot of details to help with this issue. 

I also [uploaded](http://www.yourfilelink.com/get.php?fid=2141949) here a video showing the error. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/mduraes/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.11.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment] 2019-09-10 13:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

**Closed by liamdebeasi** 2019-09-10 13:05 UTC
Labels: triage
