### ISSUE TITLE
ion-searchbar can't spell chinese correctly 

### ISSUE THREAD

**Issue by hope7th** [ionic-team/ionic#12129] opened 2017-06-22 01:16 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

in the ion-searchbar when i still spell the chinese,the english letter aready finish filled in the input box,how can i do it?

**Expected behavior:**

when i finish spell my chinese word,search this words.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment] 2017-06-22 12:17
Duplicate of https://github.com/ionic-team/ionic/issues/11566
Please fill your `ionic info` in the question body so we can see if this was really closed in 3.4.0+, or is it still a bug.

**Comment by leon9608** [comment] 2017-06-27 02:25
Hi, I still have the same problem with #11566 . This is my version.
@ionic/cli-utils : 1.4.0
Cordova CLI      : 7.0.1 
Ionic CLI        : 3.4.0

@ionic/app-scripts              : 1.3.7
@ionic/cli-plugin-cordova       : 1.4.0
@ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : none
Ionic Framework                 : ionic-angular 3.3.0

Node       : v6.11.0
OS         : macOS Sierra
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 3.10.10

**Comment by leon9608** [comment] 2017-06-27 02:29
Hi, I still have the same problem with #11566 . This is my version.
ionic/cli-utils : 1.4.0
Cordova CLI      : 7.0.1 
Ionic CLI        : 3.4.0

ionic/app-scripts              : 1.3.7
ionic/cli-plugin-cordova       : 1.4.0
ionic/cli-plugin-ionic-angular : 1.3.1
Cordova Platforms               : none
Ionic Framework                 : ionic-angular 3.3.0

Node       : v6.11.0
OS         : macOS Sierra
Xcode      : not installed
ios-deploy : not installed
ios-sim    : not installed
npm        : 3.10.10

**Comment by AmitMY** [comment] 2017-06-27 07:31
@leon9608 That PR was merged AFTER 3.3.0, so please try 3.4.0+ (3.4.2 is latest)

**Comment by leon9608** [comment] 2017-06-27 09:15
Sorry, I am a bit blur. How should I update the existing project? Must I manually change the pacakage.json file and then use npm install?

**Comment by danielsogl** [comment] 2017-06-27 09:22
Yes, you have. Check out my update guide: https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-x/87516

**Comment by jgw96** [comment] 2017-06-28 16:08
As this seems to have evolved into more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/). Thanks for using Ionic!

**Closed by jgw96** 2017-06-28 16:08 UTC
Labels: needs info, v3
