### ISSUE TITLE
Custom menu doesn't show in production

### ISSUE THREAD

**Issue by agarciaiglesias** [ionic-team/ionic#13495] opened 2017-11-23 17:36 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I am in a big project in Deloitte making a library of ionic components to publish it in a private npm. 
I have a custom menu and custom header created and published in npm. In other project I import those elements and header is shown but when I clicked in the menu button it doesn’t show the menu.

It only happens in production. I am running ionic cordova run android --aot to see errors without minification.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**
The module of the npm project is this:
```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { IonicModule } from 'ionic-angular';

import { CustomHeader } from "./components/extended/header/header";
import { CustomMenu } from "./components/extended/menu/menu";
import { MenuService } from "./components/extended/menu/menu.service";

@NgModule({
  imports: [
    IonicModule.forRoot(CustomHeader),
    IonicModule.forRoot(CustomMenu)
  ],
  exports: [
    CustomHeader,
    CustomMenu
  ],
  declarations: [
    CustomHeader,
    CustomMenu
  ],
  entryComponents: [
    CustomHeader,
    CustomMenu
  ],
  providers: [
    MenuService
  ],
})
export class ComponentsModule {

}
```

And the module where I imported the project:

```
import { NgModule, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';

import { HomePage } from '../pages/home/home';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { ComponentsModule } from 'components';



@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    ComponentsModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

```

```
insert short code snippets here
```

**Other information:**

The error in console is this:
```
ERROR Error: Uncaught (in promise): TypeError: menuTypes[type] is not a constructor
TypeError: menuTypes[type] is not a constructor
    at Function.MenuController.create (main.js:47449)
    at Menu._getType (main.js:73100)
    at main.js:73122
    at new t (polyfills.js:3)
    at Menu.setOpen (main.js:73120)
    at Menu.toggle (main.js:73290)
    at MenuToggle.toggle (main.js:93544)
    at Object.handleEvent (main.js:78096)
    at Object.handleEvent (main.js:12290)
    at Object.handleEvent (main.js:13014)
    at Function.MenuController.create (main.js:47449)
    at Menu._getType (main.js:73100)
    at main.js:73122
    at new t (polyfills.js:3)
    at Menu.setOpen (main.js:73120)
    at Menu.toggle (main.js:73290)
    at MenuToggle.toggle (main.js:93544)
    at Object.handleEvent (main.js:78096)
    at Object.handleEvent (main.js:12290)
    at Object.handleEvent (main.js:13014)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at Menu.setOpen (main.js:73120)
    at Menu.toggle (main.js:73290)
    at MenuToggle.toggle (main.js:93544)
    at Object.handleEvent (main.js:78096)
    at Object.handleEvent (main.js:12290)
    at Object.handleEvent (main.js:13014)
    at dispatchEvent (main.js:8883)
    at main.js:9494
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ionic info

cli packages: (C:\Users\agarciaiglesias\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.5.2
    @ionic/cli-utils        : 1.18.0
    ionic (Ionic CLI)       : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.5.0
    npm               : 5.3.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME     : C:\Users\agarciaiglesias\AppData\Local\Android\Sdk
    HTTP_PROXY       : not set
    http_proxy       : not set
    HTTPS_PROXY      : not set
    https_proxy      : not set
    IONIC_HTTP_PROXY : not set
    PROXY            : http://{agarciaiglesias}:{A!varito0}@10.74.244.72:8080/
    proxy            : http://{agarciaiglesias}:{A!varito0}@10.74.244.72:8080/

Misc:

    backend : pro
```

**Comment by mjwheatley** [comment] 2017-11-27 18:55
I am also experiencing this issue.  I am using MeteorJS.  Everything is running in development mode, but when I use `meteor run --production` I receive the error `Uncaught TypeError: menuTypes[type] is not a constructor at Function.MenuController.create`.  I also had to remove the minify package to see the true error.

MeteorJS uses CommonJS.  Does this package need to be specially compiled to support CommonJS?

```
"dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/forms": "^5.0.3",
    "@angular/http": "^5.0.3",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/router": "^5.0.3",
    "@ionic-native/contacts": "^4.3.3",
    "@ionic-native/core": "4.4.2",
    "@ionic-native/email-composer": "^4.3.3",
    "@ionic-native/sim": "^4.3.3",
    "@ionic-native/sms": "^4.3.3",
    "@ionic-native/splash-screen": "4.4.2",
    "@ionic-native/status-bar": "4.4.2",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "9.0.1",
    "@ngx-translate/http-loader": "^2.0.0",
    "angular2-meteor": "0.8.0",
    "babel-runtime": "^6.20.0",
    "bcrypt": "^1.0.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "meteor-rxjs": "0.4.8",
    "moment": "^2.17.1",
    "ng2-responsive": "^0.8.4",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.16"
  }
```

**Comment by kensodemann** [comment] 2017-11-27 19:53
This issue was moved to ionic-team/ionic-app-scripts#1329

**Comment by kensodemann** [comment] 2017-11-27 20:00
What does `meteor` use to build the application?

**Comment by mjwheatley** [comment] 2017-11-27 20:19
Not exactly sure what system it uses under the hood.  I can run `meteor build --directory ../build/` to bundle the app, or use `meteor run --production`.

I received this comment from @ardatan on a recent issue I had with another package in production mode. https://github.com/Urigo/angular-meteor/issues/1755
"they have to make a bundle for commonjs like other Angular libraries, but some libraries AGM, covalent, ionic doesn’t support commonjs(which is only import method supported by Meteor bundler), so we will use rollup to solve that problem."

**Comment by kensodemann** [comment] 2017-11-27 20:27
Interesting. I will ask around internally what we would like to do with our build output regarding this. Reopening for now even though this is not really an issue with the Ionic Framework code, but we don't really have a better list to put this into.

**Comment by ardatan** [comment] 2017-11-27 20:38
In the previous version of ionic-native and current version of ionic-angular, there are commonjs bundles. However, @ionic/native doesn’t have this.

**Comment by mjwheatley** [comment] 2017-11-27 20:38
I've been on Ionic v2.3.0 for a while now and has seemed to be pretty stable.  It wasn't until I tried to update to Ionic v3.8.0 (and therefore Angular v4.x) that I started having problems with a production build.

**Comment by kensodemann** [comment] 2017-11-27 20:51
Closing again as not an issue with Ionic Framework code per se. Please feel free to continue discussion here, though, if it is helpful. Otherwise you might get a wider audience including other Meteor JS users on either our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Closed by kensodemann** 2017-11-27 20:51 UTC

**Comment by ardatan** [comment] 2017-11-27 21:22
@kensodemann Ionic doesn’t support UMD/CommonJS now while previous versions support. I recommend you to look at ngx-translate issues which they’ve solved this recently before making a final decision without understanding the issue.

**Comment by kensodemann** [comment] 2017-11-27 21:29
@ardatan - are you talking about ionic-angular?

**Comment by ardatan** [comment] 2017-11-27 23:28
I mean `ionic-native` and `ionic-angular` have commonjs/umd bundles; `@ionic/native` doesn't have.

**Comment by kensodemann** [comment] 2017-11-27 23:33
OK, cool. Thx for the clarification. In that case, an issue explaining why this is a problem should probably be opened against the https://github.com/ionic-team/ionic-native repo since this repo and issue list only deals with `ionic-angular` at this time (that may change after v4 is released, but even then `@ionic/native` will likely remain a separate project).

**Comment by mjwheatley** [comment] 2017-11-27 23:34
The `MenuController` (don't know if this is the only controller effected, or just the first one to throw an error) is part of the `ionic-angular` package.  So if `ionic-angular` has a commonjs/umd bundle, then is this error caused by something else?

**Comment by mjwheatley** [comment] 2017-11-27 23:41
Is it a transpiling issue from es6 / other?
https://stackoverflow.com/questions/10107198/javascript-not-a-constructor-exception-while-creating-objects

**Comment by mjwheatley** [comment] 2017-11-27 23:45
This seems to be the offending code snippet:
```
MenuController.create = function (type, menuCmp, plt) {                                                          
        return new menuTypes[type](menuCmp, plt);                                                                      
    }; 
```
It is complaining about `new menuTypes[type]()` as it cannot find a constructor for menuTypes[type].  I am unsure what the selector `type` value is.

**Comment by agarciaiglesias** [comment] 2017-11-28 11:03
@mjwheatley , I have the error exactly at the same line that you: 
```
MenuController.create = function (type, menuCmp, plt) {                                                          
        return new menuTypes[type](menuCmp, plt);                                                                      
    }; 
```
I think that ionic is not working correctly in the library of ionic components. I think that the error may be caused by the module to export, but I dont know how to export a Ionic libreary correctly.
Someone knows?

**Comment by mjwheatley** [comment] 2017-11-28 16:50
@kensodemann other controllers don't seem to exhibit the same behavior and are working properly.  The NavController, AlertController, and ModalControllers all seem to be working fine.  Any idea what is different about the MenuController that would be causing this behavior?

**Comment by agarciaiglesias** [comment] 2017-11-28 16:57
@mjwheatley - I have working on this all day and I doscover this:
My component header had properties set to private, when I made the propertie public it starts to work.
Aot compilation doesn`t allow private properties if this porperties are called from template. So I change all properties in all my components to public and it works!.
I hope it may help you.

**Comment by mjwheatley** [comment] 2017-11-28 17:44
@agarciaiglesias unfortunately that did not help.  I not trying to do AOT, at least I don't think Meteor is trying to do that by default.

**Comment by ardatan** [comment] 2017-11-28 18:09
You can disable AOT by enviromental variable AOT=0 which can be seen in the source code;
https://github.com/Urigo/angular-meteor/blob/bf3705c22ae1dfea0be8c2fa0a56561d2c851ea8/atmosphere-packages/angular-typescript-compiler/index.js#L56

**Comment by mjwheatley** [comment] 2017-11-28 18:14
Here is my boilerplate repo that I am trying to get working: <ul>https://github.com/mjwheatley/ionic2-meteor-boilerplate</ul>

```
git clone https://github.com/mjwheatley/ionic2-meteor-boilerplate
meteor npm install
npm run start:prod
```

Go to http://localhost:3000
Open Chrome dev tools
Click on the menu hamburger at the top left.
You will see the reported error.

**Comment by mjwheatley** [comment] 2017-11-28 18:18
@ardatan I tried 
`AOT=0 meteor run --production`
(make sure to run `npm start` at least once to make sure the stylesheets have been compiled)

Still did not make a difference.

**Comment by mjwheatley** [comment] 2017-11-28 18:53
I just pushed commits including updates to the `angular-compilers` package.
`meteor run --production` loads the app, but still does not fix the issue with the MenuController.

However, `AOT=0 meteor run --production` breaks the app with the following error:
```
Unhandled Promise rejection: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: IonicApp,AppComponent ("
<body>

  [ERROR ->]<ion-app></ion-app>


"): ng:///client/imports/app/app.component.html@14:2 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: IonicApp,AppComponent ("
<body>

  [ERROR ->]<ion-app></ion-app>


"): ng:///client/imports/app/app.component.html@14:2
    at syntaxError (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:112454)
    at TemplateParser.parse (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:136317)
    at JitCompiler._parseTemplate (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145745)
    at JitCompiler._compileTemplate (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145720)
    at modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145622
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145622)
    at modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145492
    at ZoneDelegate.invoke (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:82879)
    at Zone.run (modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:82629) Error: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: IonicApp,AppComponent ("
<body>

  [ERROR ->]<ion-app></ion-app>


"): ng:///client/imports/app/app.component.html@14:2
    at syntaxError (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:112454:34)
    at TemplateParser.parse (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:136317:19)
    at JitCompiler._parseTemplate (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145745:37)
    at JitCompiler._compileTemplate (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145720:23)
    at http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145622:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145622:19)
    at http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:145492:19
    at ZoneDelegate.invoke (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:82879:26)
    at Zone.run (http://localhost:3000/packages/modules.js?hash=357ca52d3bad331d0a89b265113bb7081e327ea2:82629:43)
```

**Comment by mjwheatley** [comment] 2017-11-28 18:55
@kensodemann would love to here from you again regarding any of my comments since your last post.

**Comment by ardatan** [comment] 2017-11-28 19:06
@mjwheatley it’d better to continue that on angular-meteor, and could you reproduce a repository for this?

**Comment by mjwheatley** [comment] 2017-11-28 19:17
@ardatan Agreed for the `angular-compilers` issue, and please see my previous posts for the repository I am working with.

**Comment by mjwheatley** [comment] 2017-11-28 19:42
Error:
```
TypeError: menuTypes[type] is not a constructor
    at Function.MenuController.create (modules.js?hash=767c3f797ae494c89cb939bacaadc796f1a58d14:formatted:103657)
    at Menu._getType (modules.js?hash=767c3f797ae494c89cb939bacaadc796f1a58d14:formatted:123585)
```

Code:
```
MenuController.create = function(type, menuCmp, plt) {
    return new menuTypes[type](menuCmp,plt);
}
```
`var type = 'overlay'`
So `menuTypes.overlay` is not a constructor.
How was `menuTypes.overlay` registered?
```
MenuController.registerType = function(name, cls) {
    menuTypes[name] = cls;
};
```
Where `name = 'overlay'` and `cls = MenuOverlayType`
```
menu_controller_1.MenuController.registerType('overlay', MenuOverlayType);
```
`menuTypes.overlay = MenuOverlayType`, therefore `MenuOverlayType` is not a constructor.
```
var MenuOverlayType = function(_super) {
            __extends(MenuOverlayType, _super);
            function MenuOverlayType(menu, plt) {
                var _this = _super.call(this, plt) || this;
                var closedX, openedX;
                var width = menu.width();
                if (menu.isRightSide) {
                    // right side                                                                                          
                    closedX = 8 + width + 'px';
                    openedX = '0px';
                } else {
                    // left side                                                 
                    closedX = -(8 + width) + 'px';
                    openedX = '0px';
                }
                var menuAni = new animation_1.Animation(plt,menu.getMenuElement());
                menuAni.fromTo('translateX', closedX, openedX);
                _this.ani.add(menuAni);                var backdropApi = new animation_1.Animation(plt,menu.getBackdropElement());
                backdropApi.fromTo('opacity', 0.01, 0.35);
                _this.ani.add(backdropApi);
                return _this;
            }
            return MenuOverlayType;
        }(MenuType);
```

The offending line of code can be translated as follows:
```
MenuController.create = function(type, menuCmp, plt) {
    return new menuTypes[type](menuCmp,plt); // return new MenuOverlayType(menuCmp, plt);
}
```

Switching the device type over to iOS and `type = 'reveal'` produces the same error.
```
MenuController.create = function(type, menuCmp, plt) {
    return new menuTypes[type](menuCmp,plt); // return new MenuRevealType(menuCmp, plt);
}
```

What needs to happen to get `new MenuOverlayType(menuCmp, plt);` to not throw an error?

**Comment by mjwheatley** [comment] 2017-11-28 20:33
There is an es2015 folder in the `ionic-angular` package.
I found `node_modules/ionic-angular/components/menu/menu-type.js` this contains the following code:
```
class MenuOverlayType extends MenuType {
    constructor(menu, plt) {
        super(plt);
        let closedX, openedX;
        const width = menu.width();
        if (menu.isRightSide) {
            // right side
            closedX = 8 + width + 'px';
            openedX = '0px';
        }
        else {
            // left side
            closedX = -(8 + width) + 'px';
            openedX = '0px';
        }
        const menuAni = new Animation(plt, menu.getMenuElement());
        menuAni.fromTo('translateX', closedX, openedX);
        this.ani.add(menuAni);
        const backdropApi = new Animation(plt, menu.getBackdropElement());
        backdropApi.fromTo('opacity', 0.01, 0.35);
        this.ani.add(backdropApi);
    }
}
MenuController.registerType('overlay', MenuOverlayType);
```

@ardatan how can I get Meteor to use this version of the code? Or is this code being transpiled into what I'm seeing in the browser?

**Comment by mjwheatley** [comment] 2017-11-29 17:41
@ardatan please note new issue created on `angular-meteor` rep https://github.com/Urigo/angular-meteor/issues/1792

**Comment by mjwheatley** [comment] 2017-11-29 17:59
Solution:
Find all `from 'ionic-angular'` replace with `from 'ionic-angular/es2015'`

Example `app.module.ts`:
Before
```
import {IonicApp, IonicModule, IonicErrorHandler} from 'ionic-angular';
```
After
```
import {IonicApp, IonicModule, IonicErrorHandler} from 'ionic-angular/es2015';
```
