### ISSUE TITLE
bug: IonInput not support property of type="file"

### ISSUE THREAD

**Issue by joaoeudes7** [ionic-team/ionic#21383] opened 2020-05-27 06:21 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Type `file` is not assignable of property type in IonInput
Link in doc: https://ionicframework.com/docs/api/input

**Expected behavior:**

Accept type file and open context of files

**Related code:**
![image](https://user-images.githubusercontent.com/16367752/82984524-b8261300-9fc8-11ea-8779-bd4bfcdd716f.png)

**Ionic info:**
![image](https://user-images.githubusercontent.com/16367752/82984625-e6a3ee00-9fc8-11ea-99f0-a45d38948c2c.png)

**Comment by liamdebeasi** [comment] 2020-05-27 13:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-docs/issues/814.

**Closed by liamdebeasi** 2020-05-27 13:14 UTC
Labels: triage
