### ISSUE TITLE
bug: White Background overlay view on Keyboard hide on Android 

### ISSUE THREAD

**Issue by Shamran-Gouse** [ionic-team/ionic#19307] opened 2019-09-09 13:58 UTC
# Bug Report

**Ionic version:**
5.2.7

**Current behavior:**
When an input field selected and ion-select selected key leaves an overlay, a white background is shown after the keyboard closes. The recorded video link is below:
https://imgur.com/o04R8AE

image: https://i.imgur.com/GTIJxZP.png

**Expected behavior:**
It shouldn't happen

**Steps to reproduce:**
step 1: select an input
step 2: click ion-select

**Related code:**
https://github.com/Shamran-Gouse/demoapp

**Ionic info:**
```
Ionic:
   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2019-09-10 12:48
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19065.

**Closed by liamdebeasi** 2019-09-10 12:48 UTC
Labels: triage
