### ISSUE TITLE
Noticeable delay of invoking Modal.onDidDismiss() after modal already disappeared visually

### ISSUE THREAD

**Issue by bennyng** [ionic-team/ionic#12187] opened 2017-06-28 08:36 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a modal is being closed (by viewCtrl.dismiss()), there is a noticeable delay between the callback Modal.onDismiss() being invoked and the modal "disappear" visually.

**Expected behavior:**
When a modal is being closed (by viewCtrl.dismiss()), the callback Modal.onDismiss() should be invoked when the modal "disappear" visually.

**Steps to reproduce:**
1. present a ionic modal
2. dismiss it by viewCtrl.dismiss
3. modal disappearing, onDidDismiss invoked about 300ms after view disappeared

**Related code:**

```
// 1. Create and present modal
const modal = this.modalCtrl.create();

modal.onDidDismiss(() => {
  // this bit got invoked a bit delayed after view disappeared
  console.debug('SelectSubCategoryModal.onDidDismiss', params);
});

modal.present();

// 2. Dismiss modal
this.viewCtrl.dismiss({subCategory});
```

**Other information:**
Guess it's something to do with some delay of general page transition. However setting config *pageTransitionDelay* to *0* did not help. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by bennyng** [comment] 2017-06-28 08:46
short video for illustrating the delay. excuse for the not so good quality.
 
![ionic2_modal_dismiss_delay](https://user-images.githubusercontent.com/241646/27628287-22a0570c-5c21-11e7-8ce8-db410dca7781.gif)

**Comment by jgw96** [comment] 2017-06-28 15:48
Hello, thanks for using Ionic. Could you share a minimal repo or plunker we could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-07-10 15:15
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-07-10 15:15 UTC
Labels: needs info, v2

**Comment by refron** [comment] 2017-11-24 15:47
Hi bennyng. I´m having a similar situation with a loadingControler.
When I call loading.dismiss() it takes a little less than 1 second until loading.onDidDismiss() callback gets called. Could you find how to fix it?
Thanks

**Comment by bennyng** [comment] 2017-11-25 15:03
@refron sorry bro but unfortunately was no luck on my side. It wasn't a blocking issue in the project so had decided to move on.
