### ISSUE TITLE
ion-datetime popup with proposed date

### ISSUE THREAD

**Issue by pyummm** [ionic-team/ionic#12846] opened 2017-09-08 21:29 UTC
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[*] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[*] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
<ion-datetime [(ngModel)]="planned" min="2014" max="2020" displayFormat="DD MMM YYYY" placeholder="Placeholder"></ion-datetime>
planned variable undefined.
Date picker opens at 01 Jan 2020

**Expected behavior:**
Open picker with some proposed date, not related to [(ngModel)]="planned", and if user decide to save this defined date, "planned" variable will be filled, otherwice will stay undefined.

**Steps to reproduce:**
**Related code:**

usual 
<ion-datetime [(ngModel)]="planned" min="2014" max="2020" displayFormat="DD MMM YYYY" placeholder="Placeholder"></ion-datetime>

**Other information:**
Will be good to have handler for click event.
I have custom digital keyboard, which can stay under datepicker popup, "click" handler will be abble to remove it.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

cli packages: (/Users/macbook/IOS/PremoveExpert/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1
    ios-sim           : 5.1.0
    Node              : v6.11.0
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9M189t

**Comment by kensodemann** [comment] 2017-09-08 23:05
Hello! Thank you for opening an issue with us!

I believe this is fundamentally a duplicate of #12280, which has already been transferred to the feature request list for prioritization. Can you please have a look at that other issue and let me know if what you are describing is fundamentally the same or not.

Thank you for using Ionic

**Closed by kensodemann** 2017-09-08 23:05 UTC
