### ISSUE TITLE
bug: Ion-Slider Issue with Modal with Image

### ISSUE THREAD

**Issue by EyadIT94** [ionic-team/ionic#21502] opened 2020-06-11 12:44 UTC
# Bug Report

**Ionic version:**
[x] **5.2.0**

**Current behavior:**
When I open a model that had a photo inside a Swiper, I cannot zoom in and zoom out and it looks like the swiper in free mode, even when I press the buttons of zoom in and out and same.

**Expected behavior:**
It should be zooming in and out without any issues

**Steps to reproduce:**
Press into a photo, It will opens a modal, then try to zoom in/zoom out.

**Related code:**

You can see this the example application I upload it in my GitHub

https://github.com/EyadIT94/GalleryExampleAppIonic

```
modalimage.html

<ion-content fullscreen>

  <ion-item class="close-fake ion-text-center" lines="none">


    <ion-button (click)="close()" fill="clear">
      <ion-icon slot="start" name="close"></ion-icon>
      Back
    </ion-button>

    <ion-button (click)="zoom(true)" fill="clear">
      <ion-icon slot="start" name="add"></ion-icon>
      in
    </ion-button>

    <ion-button (click)="zoom(false)" fill="clear">
      <ion-icon slot="start" name="remove"></ion-icon>
      out
    </ion-button>

  </ion-item>

  <ion-slides class="slides" [options]="sliderOpts" #slider>
    <ion-slide>
      <div class="swiper-zoom-container">
        <img [src]="img">
      </div>
    </ion-slide>
  </ion-slides>

</ion-content>



modalimage.page.ts

import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { NavParams, ModalController } from '@ionic/angular';

@Component({
  selector: 'app-modalimage',
  templateUrl: './modalimage.page.html',
  styleUrls: ['./modalimage.page.scss'],
})
export class ModalimagePage implements OnInit {

  img:any;

  @ViewChild('slider', {read: ElementRef}) slider: ElementRef;

  sliderOpts ={
    zoom: {
      maxRatio: 3
    }
  }

  constructor(private navParams: NavParams, private modalController: ModalController) { }

  ngOnInit() {
    this.img = this.navParams.get('img');
  }

  zoom(zoomIn: boolean){
    let zoom = this.slider.nativeElement.swiper.zoom;
    if(zoomIn){
      zoom.in();
      console.log("zoomin");
      
    }
    else{
      zoom.out();
      console.log("zoomout");
    }
  }

  close(){
    this.modalController.dismiss();
  }

}

```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.2 (C:\Users\OJP1\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2020-06-11 15:19
Thanks for the issue. I am unable to reproduce the issue you are describing. Pressing the zoom in/out buttons is working for me in the example app you provided. Can you please clarify your steps to reproduce the issue?

**Comment by EyadIT94** [comment] 2020-06-11 15:26
> Thanks for the issue. I am unable to reproduce the issue you are describing. Pressing the zoom in/out buttons is working for me in the example app you provided. Can you please clarify your steps to reproduce the issue?


Hi, I have been attached this demonstration photo below, you can see it please.

**Noted this in Chrome browser, and I tested it in the android emulator and it's the same.**

![screengif](https://user-images.githubusercontent.com/27927741/84405451-2f8ab200-ac19-11ea-965e-60a4d56e04c1.gif)

**Comment by liamdebeasi** [comment] 2020-06-11 16:44
Thanks for the follow up. I am still unable to reproduce the behavior in the gif. What version of Chrome are you testing this in?

**Comment by EyadIT94** [comment] 2020-06-11 16:48
My chrome version is: **Version 83.0.4103.97 (Official Build) (64-bit)**

Is there any solution of this issue? it is related to SwiperJS?

Thanks

**Comment by liamdebeasi** [comment] 2020-06-11 16:49
It may be an issue with Swiper, but I cannot say for certain since I am unable to reproduce the issue. Can you please provide some steps to reproduce?

**Comment by EyadIT94** [comment] 2020-06-11 16:52
If you make
ionic serve
then the page is open, for example you make it as iPhone X, refresh the browser and try to make the steps that is shown in the GIF that I upload it

**Comment by liamdebeasi** [comment] 2020-06-11 16:54
Can you please list out the steps you are doing in the GIF?

**Comment by EyadIT94** [comment] 2020-06-11 16:54
Okay, Just a min

**Comment by EyadIT94** [comment] 2020-06-11 17:00
You can see this GIF I have been uploaded below.

![screengif2](https://user-images.githubusercontent.com/27927741/84417327-7f23aa80-ac26-11ea-95fd-343f9deec423.gif)

**Comment by liamdebeasi** [comment] 2020-06-11 17:09
Thanks for the issue. I am still unable to reproduce the issue you are describing. For me, the slide bounces back whenever I drag and let go of it. In the GIF, it looks like it is staying put. How do I get the behavior that is in your GIF?

**Comment by EyadIT94** [comment] 2020-06-11 17:13
Did you refresh the google chrome after you changes the layout to iPhone X for example?
Because if I didn't refresh the issue will not occurs, also when I test it in the Android Emulator it's the same problem I got it in my side :(

**Comment by liamdebeasi** [comment] 2020-06-11 17:57
Thanks for the follow up. This appears to be a duplicate of https://github.com/ionic-team/ionic/issues/19638. Please see that thread for a temporary workaround.

**Closed by liamdebeasi** 2020-06-11 17:57 UTC
Labels: triage
