### ISSUE TITLE
bug: ion-select bound to form control doesn't open in browser, but works in emulator

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/ionic#18929] opened 2019-07-29 04:05 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
I have an ion-select component bound to a form field.
```
          <ion-item lines="inset">
            <ion-label position="stacked">Agent</ion-label>
            <ion-select formControlName="agent">
              <ion-select-option *ngFor="let data of agents" [value]="data.code">{{data.desc}}</ion-select-option>
            </ion-select>
          </ion-item>
```
When I run the code in the browser with `ionic serve`, nothing happens when I click on the ion-select element, apart from the control being momentarily highlighted.

But when I run the app in the Android emulator, the ion-select opens and presents an alert containing the options as expected.

**Expected behavior:**

Select should open in the browser and display options the same as in the emulator.

**Steps to reproduce:**

See https://github.com/AndrWeisR/ion-select-bug
Run the app in the browser and try to click the "Agent" drown.

**Related code:**

https://github.com/AndrWeisR/ion-select-bug

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\weisean\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : android 7.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 8 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Android)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 8.1
```

**Comment by liamdebeasi** [comment] 2019-07-29 15:16
Thanks for the issue. I am unable to reproduce the issue with the repo you have provided. Which browser are you testing this on?

**Comment by AndrWeisR** [comment] 2019-07-29 23:57
> Thanks for the issue. I am unable to reproduce the issue with the repo you have provided. Which browser are you testing this on?

Firefox 68.0.1

**Comment by liamdebeasi** [comment] 2019-10-28 19:25
Apologies for the delay in response. Is this still an issue with Ionic 4.11.2? I am testing in Firefox, and everything seems to be working.

**Comment by AndrWeisR** [comment] 2019-10-29 06:25
I just updated to Ionic 4.11.2 and the bug is gone.

**Comment by liamdebeasi** [comment] 2019-10-29 12:40
Glad to hear the issue is fixed! I am going to close this issue. Thanks!

**Closed by liamdebeasi** 2019-10-29 12:40 UTC
Labels: triage
