### ISSUE TITLE
feat(react): expose modal overlay events didPresent, willDismiss and willPresent

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic#20130] opened 2019-12-31 08:26 UTC
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
According the Ionic React [documentation](https://ionicframework.com/docs/api/modal) of the modal, following `events` should be exposed:

| Event  | Description  |
|---|---|
| ionModalDidDismiss | Emitted after the modal has dismissed. |
| ionModalDidPresent | Emitted after the modal has presented. |
| ionModalWillDismiss | Emitted before the modal has dismissed. |
| ionModalWillPresent | Emitted before the modal has presented. |

But actually, currently, only one of them is exposed, respectively `onDidDismiss`:

```
export interface ReactControllerProps {
    isOpen: boolean;
    onDidDismiss?: (event: CustomEvent<OverlayEventDetail>) => void;
}
```

Therefore I suggest to expose also the missing events.

**Workaround**
Possible workaround: Add an event listener on the document and pass the state to the modal as property:

```
useIonViewDidEnter(() => {
    document.addEventListener('ionModalDidPresent', () => setModalPresented(true), false);
  });

  useIonViewDidLeave(() => {
    document.removeEventListener('ionModalDidPresent', () => setModalPresented(true), true);
  });

<IonModal>
    <MyModal myPresentedProp={modalPresented}></ClientsModal>
</IonModal>
```

**Comment by elylucas** [comment] 2020-01-22 21:49
closing as this is a duplicate of #19923 and will be fixed in 4.11.9 release

**Closed by elylucas** 2020-01-22 21:49 UTC
Labels: package: react
