### ISSUE TITLE
bug: ion-datetime min value using meridiems

### ISSUE THREAD

**Issue by mateuszRybczonek** [ionic-team/ionic#21545] opened 2020-06-16 09:14 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When using `ion-datetime` formatted to include meridiems (`picker-format="h:mm a"`) and `min` value set, all time values lower that min value are not available. The component seems not to recognize meridiems.

Eg. min value set to 11:00 cuts off all hour values lower than 11, that means only 11-12 am and 11-12 pm are available.

**Expected behavior:**
The component should take meridiems into account when calculating available options. When the min value is set to 11:00 it should allow 11-12 am and 1-12 pm.

**Related code:**
```
<ion-datetime
  display-format="h:mm a"
  picker-format="h:mm a"
  min="2020-06-17T11:15Z"
  value="2020-06-17T12:00Z"
/>
```
https://stackblitz.com/edit/ionic-v4-angular-tabs-zrwyp9

**Comment by liamdebeasi** [comment] 2020-06-16 12:59
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18908. We are tracking all issues in https://github.com/ionic-team/ionic/issues/16630, so I will add this issue there. Thanks!

**Closed by liamdebeasi** 2020-06-16 12:59 UTC
Labels: triage
