### ISSUE TITLE
bug (ion-segment-button): none of border property is getting applied 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#20909] opened 2020-03-29 17:00 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

border color is getting inherit from color checked and width is not getting applied.
![image](https://user-images.githubusercontent.com/23274631/77855206-9567c000-720c-11ea-9e29-46e8bf7478a0.png)

**Expected behavior:**

It should have
  --border-width: 80%;
  --border-radius: 20px;
  --border-style: 1px solid black;
  --border-color: green;

**Steps to reproduce:**

https://stackblitz.com/edit/ionic-angular-v5-qedttq?file=src%2Fapp%2Fapp.component.html
**Related code:**

html.
```
    <ion-segment (ionChange)="segmentChanged($event)" value="friends">
  <ion-segment-button value="friends">
    <ion-label>Friends</ion-label>
  </ion-segment-button>
  <ion-segment-button value="enemies">
    <ion-label>Enemies</ion-label>
  </ion-segment-button>
</ion-segment>
```
css 
```
ion-segment-button {
  --border-width: 80%;
  --border-radius: 20px;
  --border-style: 1px solid black;
  --border-color: green;
  --color-checked: red;
  --color: blue;
  --color-hover: red;
  --margin-bottom: -10px;
}
```
**Other information:**

**Ionic info:**

```
  "@ionic/angular": "^5.0.5",
```

**Comment by liamdebeasi** [comment] 2020-03-30 13:56
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Your `--border-style` usage is incorrect which is causing the border to not be rendered properly.

`--border-style` refers to the line style for all four sides of an element's border (such as `dotted` or `solid`). See https://developer.mozilla.org/en-US/docs/Web/CSS/border-style for more information.

**Closed by liamdebeasi** 2020-03-30 13:56 UTC
Labels: triage

**Comment by indraraj26** [comment] 2020-03-30 18:19
other border property is also not getting applied like --border-width can you check stackblitz

**Comment by liamdebeasi** [comment] 2020-03-30 20:58
`border-width` does not support percentages: https://stackoverflow.com/questions/13474754/how-to-set-borders-thickness-in-percentages
