### ISSUE TITLE
bug: Slow iOS inputs when more than one row/column

### ISSUE THREAD

**Issue by simonbarker** [ionic-team/ionic#21409] opened 2020-06-01 13:08 UTC
# Bug Report

**Ionic version:**
[x] **5.1.1**

**Current behavior:**
If a page has more than one row/column pair then all but the first ion-input is slow to enable/select.

**Expected behavior:**
All inputs as fast to enable/select as the first.

**Steps to reproduce:**
Download this repo: [https://github.com/simonbarker/input-test](https://github.com/simonbarker/input-test)
`cd` into it, `npm i`, `ionic serve`, go to home page, select both fields, first will be fast, second will be slow.
Open `home.page.html` comment out lines 18 through 22 as per the instructional comment, reload page as see that both fields are now fase

**Related code:**

A sample application via GitHub: Download this repo: [https://github.com/simonbarker/input-test](https://github.com/simonbarker/input-test)

**Other information:**
This is a brand new project created today just to recreate this problem. It is happening in my main larger project. Both work fine on Android.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.9.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by simonbarker** [comment] 2020-06-01 13:25
Have updated the example repo with:

`<ion-item class="ion-no-padding" lines="none">
     <ion-label>Section label</ion-label>
 </ion-item> `

in between the two ion-inputs as this also recreates the issue, even if all rows and columns are removed

**Comment by simonbarker** [comment] 2020-06-01 13:31
The main form I am using this in is very complex and has rows and columns to lay it out and labels to high light different areas, there is no way I can code around this by not using any other rows/columns or labels. All works perfectly on Android.

In desktop Chrome (iPhoneX dev mode) and on Android tabbing/next works so that avoids this slow down but as the shadow-dom inputs in items webkit issue is blocking that on iOS at the moment this form is borderline unusable on iOS.
![Uploading Screenshot 2020-06-01 at 14.28.25.png…]()

**Comment by liamdebeasi** [comment] 2020-06-01 19:34
Thanks for the issue. What device are you testing this on? I am testing this on my iPhone 11 running iOS 13.5 and am unable to reproduce the behavior you are describing.

**Comment by simonbarker** [comment] 2020-06-01 20:03
Ok, this ones on me - I built the project with 5.0.7 first to check it was an issue as in my main project, ran that on the phone. Then rebuilt with 5.1.1 - got distracted and thought I had pushed it to the phone .... I hadn't.

I've just tested again and you're right the issue isn't there with 5.1.1.

Interestingly it is still there on Chrome when running in iPhone X mode.
Version 83.0.4103.61 (Official Build) (64-bit) on MacOS Catalina

![Screen Recording 2020-06-01 at 20 52 51](https://user-images.githubusercontent.com/1485965/83449000-c356c400-a44a-11ea-8640-1a6fb02be06d.gif)

**Comment by liamdebeasi** [comment] 2020-06-01 20:39
It looks like this has something to do with our scroll assist utility. It is incorrectly guessing that the input needs to scroll, and so it is going to wait for the "keyboard show" event to be fired. But since this is the browser and there is no keyboard to show, we wait for the 1000ms timeout to fire instead.

**Comment by liamdebeasi** [comment] 2020-06-01 21:04
Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.2.0-dev.202006012048.5f2001c`

**Comment by simonbarker** [comment] 2020-06-01 21:16
Yeah that's fixed it, much better in Chrome and still responsive on iOS. Looks like this may have been tied in with 20922 in someway?

One minor thing with the cursor behaviour whilst comparing the two. In chrome the cursor always starts its flashing in the '|' phase rather than the ' ' phase when selecting a text box. On iOS it often starts in the ' ' phase even though the text field is immediately active (the keyboard changes from text to number so I can tell).

It's like the cursor is on its own flash period in iOS regardless of the text box, rather than reseting the cursor phase back to '|' on text box change like in Chrome. I imagine this is a webkit thing rather than Ionic but it does make it appear that the fields are laggy when they aren't.

Thanks for getting on this so quickly, it's been driving me mad for weeks!

**Comment by liamdebeasi** [comment] 2020-06-01 21:24
Glad it's working now. Yeah, scrolling to an input in a mobile web app is tricky. We have a scroll assist utility that, on input focus, will:

a) Clone the input.
b) Move the original input offscreen so Safari does not attempt to scroll the entire page.
c) Move the original input back to its original position.
d) Attempt to scroll `ion-content` such that the input is in view.

For part d, we need to wait for the `ionKeyboardDidOpen` event to fire. However, when running in Chrome on macOS, there is no keyboard to open, so the event does not fire. This causes the timeout fallback to fire after 1000ms, leading to the visual delay you saw. Ionic checks to see if an input needs to be scrolled and breaks early if it does not. The dev build fixes a few false positives with that detection.

**Comment by liamdebeasi** [comment] 2020-06-03 14:01
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21416, and a fix will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-06-03 14:01 UTC
Labels: package: core, type: bug
