### ISSUE TITLE
fuck fuck fuck searchbar,don't input chinese word.

### ISSUE THREAD

**Issue by shenmingxuanyi** [ionic-team/ionic#11885] opened 2017-06-01 08:48 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[*] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment] 2017-06-01 09:01
This is very inappropriate, and the issue is empty, so please close it, or fix the title and the content.

**Comment by CloverEc** [comment] 2017-06-01 10:14
ion-searchbar bug on 3.1.0, 3.1.1, 3.2.0 for non-latin languages. #11566

**Closed** 2017-06-01 13:35 UTC
