### ISSUE TITLE
App taken a long time to compile

### ISSUE THREAD

**Issue by stilren** [ionic-team/ionic#17553] opened 2019-01-24 16:46 UTC
Compiling this app takes a really long time (1 min or more) for me - when I added ionic react bindings to my private project the compile time went up in a similar fashion. Is it just me or is this a known issue?

**Comment by idhard** [comment] 2019-06-05 09:48
hello , is there some update in regards building time? after adding ionic components in a react app  with create-react-app scripts i see building times considerably more slower

**Comment by elylucas** [comment] 2019-06-06 19:35
Hi @idhard, how much would you say the compile times are going up when you add Ionic? Is your react app a blank slate or existing app?

Personally not seeing long build times, so want to weigh the differences.

Look for another react beta release coming soon with updates to core which should help compile times as well.

**Comment by idhard** [comment] 2019-06-10 09:52
hello @elylucas will try to  set a repo with basic setup to run some analytics on it  for better insights on performance , currently don't have the numbers but my impression is that adding basic ionic components , just layout, increase the building time on 20% to 30% , again i would like to provide you concise numbers rather than personal appreciation. Although i will keep tune  for the new beta release

**Comment by elylucas** [comment] 2019-08-15 23:31
Going to close this issue. If the issue is still happening on the latest ionic/react release, let us know.

Thanks

**Closed by elylucas** 2019-08-15 23:31 UTC
Labels: package: react
