### ISSUE TITLE
bug: [Ionic 5 & Capacitor] hardware back button not closing the app on Android...

### ISSUE THREAD

**Issue by Incubbus** [ionic-team/ionic#20717] opened 2020-03-07 18:52 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Hardware back button does not close the app.

**Expected behavior:**
Hardware back button should close the app, when back at the first page & no overlays are open (e.g. modals).

**Steps to reproduce:**
````
* ionic start someName blank --capacitor
* (choose angular)
* ionic build
* ionic capacitor copy android
* npx cap open android
* Run on device
* press back button
````

**Other information:**

It is super frustrating that a bug like this still exists. Why bother releasing new version of ionic if you haven't even fixed the issues for ionic 4?
Like this ionic can only be used as a playground and not for serious apps to be released to customers.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.0 (C:\Users\jp\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.2
   OS     : Windows 10
```

**Comment by NikolaPeevski** [comment] 2020-03-07 18:57
Duplicate of https://github.com/ionic-team/ionic/issues/16611

**Closed** 2020-03-07 20:12 UTC
Labels: triage
