### ISSUE TITLE
bug:  ionic cordova build build.gradle

### ISSUE THREAD

**Issue by SirmaXX** [ionic-team/ionic#19348] opened 2019-09-15 22:11 UTC
# Bug Report
gradle -v  :Gradle 5.6.2 
ionic -v :5.2.8
cordova -v  :9.0.0 (cordova-lib@9.0.1)
npm -v  :6.11.3 

when i typed ionic cordova build android  .İt gave this error ( i guess its a bug )                                  Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :CordovaLib
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/deniz/Masaüstü/masaüstü/istatistikyazılımı/apache cordova/ionicdeneme/myApp/platforms/android/CordovaLib/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 35s
/home/deniz/Masaüstü/masaüstü/istatistikyazılımı/apache cordova/ionicdeneme/myApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/deniz/Masaüstü/masaüstü/istatistikyazılımı/apache cordova/ionicdeneme/myApp/platforms/android/CordovaLib/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by liamdebeasi** [comment] 2019-09-16 13:11
Thanks for the issue. I am going to close this as this is not a bug in Ionic. The error seems to indicate there is a problem with one of the plugins you are using.

For further help with this issue I recommend you post on our [forums](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com). Thanks!

**Closed by liamdebeasi** 2019-09-16 13:11 UTC
Labels: triage

**Comment by SirmaXX** [comment] 2019-09-16 15:33
@liamdebeasi   but it asked a few times in these issues .No one havent solved this thing .Please write clues for users :(
