### ISSUE TITLE
bug: Safari/iOS block animation after navigating between pages

### ISSUE THREAD

**Issue by peterpan666** [ionic-team/ionic#19018] opened 2019-08-07 09:12 UTC
# Bug Report

[x] **4.7**

**Current behavior:**
On Safari or iOS
- I've got a spinner on page 1
- I navigate to page 2 with the `routerLink` attribute or using the `NavController`
- On page 2, I go back to page 1, the spinner isn't animated anymore

**Expected behavior:**
The spinner should still rotate

**Steps to reproduce:**
![Sans-titre](https://user-images.githubusercontent.com/4153168/62610382-e20c2d00-b903-11e9-9433-7f2cfcac8817.gif)

**Related code:**

https://stackblitz.com/edit/ionic-v4-angular-tabs-ytvf9w

**Other information:**
I've tried to debug this and it seems that changing the visibility of the spinner allow him to rotate again.

When the spinner is stopped, you can add `display: none !important` to its style, it disappears, then remove the display: none, the spinner starts rotating again.

**Ionic info:**
This is from my local project which has the bug, but the bug is still here in newer versions (see the stackblitz)

```

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 8 other plugins)

Utility:

   cordova-res : 0.2.0 (update available: 0.6.0)
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1
   ios-sim           : 7.0.0
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

```

**Comment by liamdebeasi** [comment] 2019-08-07 12:23
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17202.

**Closed by liamdebeasi** 2019-08-07 12:23 UTC
Labels: triage
