### ISSUE TITLE
bug: Scroll on iOS not smooth and bouncing in a strange way

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic#21446] opened 2020-06-07 10:44 UTC
![Senza nome_low](https://user-images.githubusercontent.com/18414951/83966969-ef949980-a8bd-11ea-9469-0c7c790bf4a1.gif)

# Bug Report

In some pages, and i don't know why, the scroll on iOS (both safari and Chrome) is not smooth and the boucing is not working properly. You can testing it visiting this web page using an iPhone: [https://roomlessrent.com/en/annunci-affitto](https://roomlessrent.com/en/annunci-affitto).
I already tried with forceOverscroll on ion-content, no effect.

**Ionic version:**

[x] **5.1.1**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

I don't really know how to reproduce it, i can just show you the page giving the problem [https://roomlessrent.com/en/annunci-affitto](https://roomlessrent.com/en/annunci-affitto)
 and you can insect the code. I think it is relate to something with ion-content but i don't really know, you can test also the other pages and they are not having issues.

It is a private repository, if some of you wants the access just ask.

**Related code:**

```

<ion-header *ngIf="GlobalFields.isMobile || GlobalFields.isTablet" [class]="'animated ' + headerClass"
            style="border-bottom: 2px solid rgb(247, 247, 247) !important; padding-bottom: 2px;">
  <ion-toolbar>
    <ion-row class="filters">
      <div class=buttonsHeaderSearchTabs>
        <button class="btn-search" (click)="openLocationsModal()">
          <i class="fal fa-search"></i>
          <span *ngIf="GlobalFields.placeSelected; else emptySearch">{{GlobalFields.placeSelected.name}}</span>
          <ng-template #emptySearch>{{"CITY_UNIVERSITY_OTHER" | translate}}</ng-template>
        </button>
        <button (click)="openFilter()" style="width: 80px"><i class="fal fa-filter"></i> {{"FILTERS" | translate}}
        </button>
      </div>
    </ion-row>
  </ion-toolbar>
</ion-header>

<ion-content class="cards-bg social-cards" *ngIf="GlobalFields.isMobile || GlobalFields.isTablet">
  <div class="mainContentDesktop" style="padding-top: 15px; padding-bottom: 80px;">

<!-- CONTENT -->
</div>
</ion-content>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, browser 5.0.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.2, (and 13 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.6.0
   native-run (update available: 1.0.0)   : 0.2.8

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.0
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Catalina
   Xcode      : Xcode 11.3 Build version 11C29
```

**Comment by roman-rr** [comment] 2020-06-07 17:52
Seem's bug is Safari related with cross overflow scrolling. Two scrolling are activated in one time.  
Answer should be at http://webkit.org/ community

**Comment by liamdebeasi** [comment] 2020-06-08 13:30
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I looked at the structure of your app via dev tools, and I noticed that there were elements behind `ion-content` that received scroll events as well. This is likely the source of the problem -- there should be only 1 scrollable element per-page.

**Closed by liamdebeasi** 2020-06-08 13:30 UTC
Labels: triage

**Comment by ilprima** [comment] 2020-06-08 13:34
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. I looked at the structure of your app via dev tools, and I noticed that there were elements behind `ion-content` that received scroll events as well. This is likely the source of the problem -- there should be only 1 scrollable element per-page.

What do you mean with "elements behind ion-content that received scroll events as well"? Can you give me an example?

**Comment by liamdebeasi** [comment] 2020-06-08 13:45
I was not able to identify which element in particular, but if you add a `scroll` event listener on `window`, you should occasionally notice some events being logged that are not related to scrolling on `ion-content`. I do not know if this is _the_ reason why this issue is occurring, but it appears related.

The app looks fairly complex, so I would recommend trying to reproduce this issue in a blank application that way you can pinpoint where the jumping is coming from. Ionic Framework does not alter the scroll position of your scrollable content, so it is possible your code is doing something that is causing some unexpected re-paints in Safari.

**Comment by ilprima** [comment] 2020-06-08 13:55
Thank you. The issue is not on Safari but on iOS in general. I'm 99% sure it is a ionic bug, something is breaking the iOS bouncing but I don't really know what.
I added infinite scroll but I removed it so I don't think that is the problem because this causes a lot of problems (eg no browser status bar hidden on scroll). I didn't add code related to scroll.
Ionic doesn't let the scroll to be handled by the browser as should be and this is why I think the problem is ionic/ion-content. I can give you access to my code and I can tell you which component has the problem.
I'm 2 months trying to fix it and yes, the project is complex, I tried to reproduce it with no success

**Comment by liamdebeasi** [comment] 2020-06-08 13:58
Sorry, I meant to say WebKit not Safari. WebKit is the engine that powers the webview, Safari, etc. 

> Ionic doesn't let the scroll to be handled by the browser as should be and this is why I think the problem is ionic/ion-content.

This is incorrect. Ionic Framework lets the browser handle all scrolling -- there is no JS scrolling involved.

If you can reproduce this behavior in a blank Ionic app, I am happy to take another look.
