### ISSUE TITLE
bug: Ionic icons fetching does not consider base-href value

### ISSUE THREAD

**Issue by heinzburgstaller** [ionic-team/ionic#18737] opened 2019-07-09 08:15 UTC
# Bug Report

**Ionic version:**

[x] **4.6**

**Current behavior:**

With the CLI you have the option to run the Ionic App in a sub path:
`ionic build -- --base-href "/subpath/"`

JS Files are correctly fetched with prefixed path, but icons are not.

Example log from server:

```
"GET /subpath/9.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
"GET /svg/md-arrow-dropdown.svg" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
"GET /svg/md-arrow-dropdown.svg" Error (404): "Not found"
```
As you can see in the log the JS file `9.js` is resolved correctly, but the icon `md-arrow-dropdown.svg` is not resolvable.

**Expected behavior:**

Prepend the base-href value to the GET request when fetching icons:

```
"GET /subpath/9.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
"GET /subpath/svg/md-arrow-dropdown.svg" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

**Steps to reproduce:**

Compile an ionic app with ``ionic build -- --base-href "/subpath/"`` and put the content of the `www` folder to the subpath `subpath` of a http-server. Check if an `<ion-icon>` is visible.

 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/home/user/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.0 (/home/heinz/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.4.1
   OS     : Linux 5.0

```

**Comment by liamdebeasi** [comment] 2019-07-09 13:06
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18650.

Additionally, this issue has been fixed and will be in Ionic 4.6.1.

**Closed by liamdebeasi** 2019-07-09 13:06 UTC
Labels: triage

**Comment by heinzburgstaller** [comment] 2019-07-09 13:09
When is the  4.6.1 release?

**Comment by liamdebeasi** [comment] 2019-07-09 13:11
Assuming all goes well, today 🙂
