### ISSUE TITLE
[Ionic V4.0.0-beta.7] Create alert or other popover components but not present

### ISSUE THREAD

**Issue by favrio** [ionic-team/ionic#15489] opened 2018-09-07 02:38 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.0
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.3
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
Create a alert from service,but not present it, the backdrop will froze the screen, i cant do anything any more. Check the dom tree, the backdrop of the alert is visible already.

**Steps to Reproduce**
1. Create any alert, but not present.
2. The backdrop is visible.

**Comment by manucorporat** [comment] 2018-09-07 14:19
Why are you not presenting the overlay?

**Comment by cdllqos** [comment] 2018-09-10 06:35
@Manduro but sometimes, we need two or more overlay to display different message in the same page, we want to initialize one overlay and use it in different function.

**Comment by liamdebeasi** [comment] 2019-02-15 15:30
Hi @favrio,

Thanks for opening an issue with us! Would you be able to try this on the latest version of Ionic `v4.0.1` and let me know if you are still running into this issue?

Thanks for using Ionic!

**Comment by liamdebeasi** [comment] 2020-06-29 21:00
Thanks for the issue. I am going to close this due to lack of a reply. If this is still an issue with the latest version of Ionic Framework, please open a new issue and include a repo we can use to reproduce the issue.

**Closed by liamdebeasi** 2020-06-29 21:00 UTC
Labels: needs: reply, type: feature request
