### ISSUE TITLE
ion-button click event on ios doesn't work when pressing on icon

### ISSUE THREAD

**Issue by kienbanh** [ionic-team/ionic#15960] opened 2018-10-16 01:42 UTC
Say you have the following button:

```
<button ion-button (click)="add()">
<ion-icon name="add"></ion-icon>
</button>
```

The button DOESN'T work when the icon is "touched". It works when you meticulously press ABOVE AND BELOW the icon (but still within the button). I have tried this on iPhone 8 & iPhone X - both 12.0. 

Also, this applies to all auto generated back button in ion-header.

Any thoughts? Bugs?

**Comment by bb128b** [comment] 2018-10-22 15:22
Also getting this issue. However, I get the same issue for the back button and an icon location on a full height screen at the top. It seems like there is an invisible bar across the header of the screen as when I give my button a margin-top of about 50px it is clickable once again.

```
    <div class="info-icon-container foreground-fix"
         margin-top
         text-right>
        <img src="../../assets/icons/info.png"
             (tap)="openWalkthrough()">
    </div>
```

**Comment by bb128b** [comment] 2018-10-23 15:46
Hi @kienbanh, after much research I think this is the root cause of the issue -> https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2459. If you are not using Google maps plugin then I don't know what is causing your issue.

**Comment by kienbanh** [comment] 2018-10-24 13:30
@bb128b that's exactly what it was. A co-worker of mine discovered that too and we downgraded the googlemaps plugin. Thanks!

**Comment by brandyscarney** [comment] 2018-10-25 15:34
Thanks for the issue. I'm going to close this since it seems you found a solution, but let me know if you're still running into it and I'll reopen. 🙂

**Closed by brandyscarney** 2018-10-25 15:34 UTC
Labels: triage
