### ISSUE TITLE
bug: new haptic drag gesture does not work for ion-select with action-sheet interface

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21488] opened 2020-06-10 18:23 UTC
# Bug Report

**Ionic version:**

[x] **5.2**

**Current behavior:**

The new haptic drag gesture does not work for ion-select with `interface="action-sheet"`.

**Expected behavior:**

It should work the same as ion-action-sheet.

**Steps to reproduce:**

Just open ion select with `interface="action-sheet"`.

**Comment by BerkeAras** [comment] 2020-06-11 07:08
@liamdebeasi I can not make an Ajax Call, but I could get the output and put it in a variable. Then there is the bug again. See: [https://codepen.io/BerkeAras/pen/mdVVabK?editors=1010](https://codepen.io/BerkeAras/pen/mdVVabK?editors=1010)

**Comment by liamdebeasi** [comment] 2020-06-11 14:50
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

The haptic gesture does not support scrollable action sheets. If you were to remove select options in your CodePen such that the action sheet is _not_ scrollable, the gesture would work. This is in line with what native action sheets on iOS do. Thanks!

**Closed by liamdebeasi** 2020-06-11 14:50 UTC
Labels: ionitron: needs reproduction

**Comment by BerkeAras** [comment] 2020-06-11 15:14
Oh, it was my fault! Im sorry!
