### ISSUE TITLE
ionic2 slides keyboard bug

### ISSUE THREAD

**Issue by KingsDevelopment** [ionic-team/ionic#5571] opened 2016-02-23 15:05 UTC
#### Short description of the problem:

I got a couple of slides, and the last one of them has a login form. whenever I try to type in the input fields, the keyboard pops up and the slides are broken, they're auto resized to the space left, and after closing the keyboard they stay that way.
#### What behavior are you expecting?

I am expecting it to be pushed up (like usual phone behavior I guess?) and make it possible to use form fields in slides.

**Steps to reproduce:**
1. Create a view with slides
2. add a form to one of the slides (even one input fiels will do)
3. Tap the input field, tada.

```
        <ion-slide>
            <img src="img/superbuddy_logo.png" class="slide-img"/>
            <h2 class="slide-title">Let's get started!</h2>
            <ion-item>
                <ion-label>username</ion-label>
                <ion-input></ion-input>
            </ion-item>
            <ion-item>
                <ion-label>password</ion-label>
                <ion-input type="password"></ion-input>
            </ion-item>
            <button full>Log in</button>
            <div class="divider"></div>
            <button outline>
                <ion-icon name="logo-facebook"></ion-icon>
                Log in with facebook
            </button>
            <div class="divider"></div>
            <button clear>Create new account?</button>
        </ion-slide>
```

**Ionic Version**: 1.x / 2.x
2

**Browser & Operating System**: iOS / Android / Chrome
All of them.

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: Not installed
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v5.5.0
```

**Comment by alpotapov** [comment] 2016-03-18 19:21
Any progress on this issue?

**Comment by EvanWillms** [comment] 2016-04-10 21:47
Given this description of space being suddenly claimed by the keyboard when an input field is tapped and then not released afterward, this sounds like another effect of #5432.

@HazeDevelopment, @alpotapov:  You might be able to make use of the workaround I found to let the keyboard slide **over** the content, preventing it from getting permanently squished:
https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/5?u=evanwillms

@brandyscarney: I would guess that this issue shares a root cause with #5432 and is unrelated to potential work in #6007, but you should probably have someone more familiar verify.

**Comment by jgw96** [comment] 2016-04-12 16:48
related to #5744

**Comment by dylanvdmerwe** [comment] 2016-04-20 09:10
An plunkr example of a form with various input components within an `<ion-slides>`: http://plnkr.co/edit/i0MIv8mlQ5WljUJxlBAs?p=preview

**Comment by jgw96** [comment] 2016-04-20 14:25
Hey everyone! Just wanted to let the community know that we are currently making alot of changes to slides for beta.5, along with some much better docs, so look out for fixes for slides in beta.5! (:

**Comment by jlsuarezs** [comment] 2016-06-07 23:22
Any news about this bug? I having exactly the same problem....:(

**Comment by jgw96** [comment] 2016-06-30 17:56
Hello all! Is this still an issue with Ionic 2 beta.10? Thanks!

**Comment by jgw96** [comment] 2016-07-06 16:50
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by satully89** [comment] 2016-08-08 19:06
Still experiencing this issue as well

**Comment by Ionitron** [comment] 2016-08-08 19:13
Greetings @KingsDevelopment!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment] 2016-08-08 19:13
Greetings @KingsDevelopment!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by kaziuk** [comment] 2016-10-18 10:58
Is there any solutions to this issue yet? I am using Ionic 2 RC1 and having this problem. I put my login form on a slider, then on iPhone if I tap on the input box then if I move away the focus from the textbox and tap again then the form moves up. Please see the screenshot.
I tried Keyboard.disableScroll(true) but didn't work. I am not sure how to use scrollAssist and autoFocusAssist with RC1 though.

![img_5115](https://cloud.githubusercontent.com/assets/16180941/19474850/68970086-9529-11e6-841d-5fdfa49b59d8.PNG)

**Comment by vejja** [comment] 2016-11-10 23:07
Same here.
Here are a couple of screenshots, first on simulator, then on device

## On Simulator
----------------

### Initial screen = normal
![simulator screen shot 10 nov 2016 a 23 15 43](https://cloud.githubusercontent.com/assets/7295259/20197245/b8da3bf8-a79e-11e6-8a18-33d0a9c2a07e.png)

### Entering first field = content goes mostly off screen, almost all blank, second field disappeared
![simulator screen shot 10 nov 2016 a 23 16 05](https://cloud.githubusercontent.com/assets/7295259/20197256/c59077ae-a79e-11e6-8ce7-46871b3bd816.png)

### Entering second field = content goes again off screen, biiiiig time !!
![simulator screen shot 10 nov 2016 a 23 16 22](https://cloud.githubusercontent.com/assets/7295259/20197262/c9296fd8-a79e-11e6-9c3e-80a689de8d5a.png)

### Typing in second field = first field has been pushed up again
![simulator screen shot 10 nov 2016 a 23 16 27](https://cloud.githubusercontent.com/assets/7295259/20197263/ccd7788c-a79e-11e6-880b-4f364eaf393d.png)

### Leaving second field =  back to normal
![simulator screen shot 10 nov 2016 a 23 16 33](https://cloud.githubusercontent.com/assets/7295259/20197269/d14c4ea6-a79e-11e6-80df-6d88cbe35e0b.png)

## On Device

### Initial screen = normal
![img_0448](https://cloud.githubusercontent.com/assets/7295259/20197606/b6df65a6-a7a0-11e6-8f8f-10420f5679c4.PNG)

### Entering first field = content goes mostly off screen, now we can see why (keyboard), second field has disappeared also
![img_0449](https://cloud.githubusercontent.com/assets/7295259/20197278/dbad4f30-a79e-11e6-81f7-47f66fcdb814.PNG)

### Exiting first field = second field label re-appears
![img_0450](https://cloud.githubusercontent.com/assets/7295259/20197280/dce24d24-a79e-11e6-9704-6cd461546329.PNG)

### Entering second field = not pushed as much as on simulator
![img_0451](https://cloud.githubusercontent.com/assets/7295259/20197282/de516ff0-a79e-11e6-9e98-016d1fb11ab9.PNG)

### Leaving second field = back to normal !
![img_0452](https://cloud.githubusercontent.com/assets/7295259/20197285/e25fa102-a79e-11e6-9012-f36b222a9157.PNG)

### Re-entering second field = biiiiiig mess
![img_0453](https://cloud.githubusercontent.com/assets/7295259/20197288/e373170e-a79e-11e6-8614-d77b9fb33759.PNG)

## Info

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62
```


## HTML

```
<ion-content class="init">
	<ion-slides pager #slider [options]="options">
		<ion-slide>
			<ion-toolbar>
				<ion-buttons end>
					<button ion-button (click)="letSlide()">Next</button>
				</ion-buttons>
			</ion-toolbar>
			<h2 class="slide-title">Welcome</h2>
			<p>
				Click next to begin the initialization.
			</p>
		</ion-slide>
		<ion-slide>
			<h2 class="slide-title">Credentials</h2>
			<p>Please enter your serial number and email address</p>
			<form [formGroup]="credentialsForm" (ngSubmit)="submitCredentials(credentialsForm.value)">
				<ion-item>
					<ion-label floating>Serial</ion-label>
					<ion-input type="text" formControlName="serial"></ion-input>
				</ion-item>
				<ion-item>
					<ion-label floating>Email</ion-label>
					<ion-input type="email" formControlName="email" clearInput></ion-input>
				</ion-item>
				<div padding>
					<button ion-button color="primary" block type="submit" [disabled]="!credentialsForm.valid">Validate</button>
				</div>
			</form>
		</ion-slide>
                <ion-slide>
                   Whatever
                </ion-slide>
		<ion-slide>
			<h2 class="slide-title">Ready to Play?</h2>
			<button ion-button large clear (click)="initDone()">
				Continue
				<ion-icon name="arrow-forward"></ion-icon>
			</button>
		</ion-slide>
	</ion-slides>
</ion-content>
```

## TypeScript

```
import { Component, ViewChild } from '@angular/core';
import { NavController, Slides } from 'ionic-angular';
import { Validators, FormBuilder, FormGroup } from '@angular/forms';
import { HomePage } from '../../pages/home/home';


@Component({
    templateUrl: 'init.html',
})
export class InitPage {
    @ViewChild('slider') slider: Slides;
    nav: NavController;
    credentialsForm: FormGroup;
    slides: any;
    options: any;

    constructor(public navCtrl: NavController, public fb: FormBuilder) {
        this.nav = navCtrl;
        this.credentialsForm = this.fb.group({
            serial: ['', [Validators.required, Validators.pattern('^[A-Fa-f0-9]{16}$')]],
            email: ['', [Validators.required, Validators.pattern('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')]]
        });
        this.options = {
            pager: true,
            onlyExternal: true
        };
    }


    letSlide(self: any = this): void {
        self.slider.slideNext();
    }

    submitCredentials(data): void {
        this.letSlide(this));
    }

    initDone(): void {
        this.navCtrl.setRoot(HomePage);
    }
}

**Comment by vejja** [comment] 2016-11-11 11:29
@manucorporat There is a very helpful gist by @EvanWillms 
https://gist.github.com/EvanWillms/8773f8cfa12f469fabf0bdd7a75723e7
I am pretty sure it can help nail down the root cause of the issue.

**Comment by Daskus1** [comment] 2017-01-02 22:57
Is there any progress on this issue? I have the same problem, when typing on an input inside a slide the slide is broken

**Comment by hotforfeature** [comment] 2017-02-03 17:39
I've been using `<ion-slides>` with form inputs for a while now. The problem is that the slider wasn't designed for use with assistive scroll.

I have a workaround described in #10258. It involves making the slider `ion-fixed` and using `<ion-content>` inside each `<ion-slide>`.

The one caveat is that `<ion-content>` also wasn't designed to deal with multiple content elements on a page. There's a patch in the linked issue that you'll want to call on your ViewController when you create your component.

**Comment by sufiiiyan** [comment] 2017-04-07 13:48
I'm still facing this issue
when I is use input with ion-slide.
Is there any solution or any updates

**Comment by pablozandona** [comment] 2017-05-11 15:48
+1

**Comment by douglasmoraisdev** [comment] 2017-11-06 16:12
This workaround worked for me in app.modules.ts:

```
imports...

@NgModule({

	declarations: [
		...
	],

        imports: [
		IonicModule.forRoot(MyApp, {
			scrollAssist: false
		}),
		...
	],
```
Source:
https://forum.ionicframework.com/t/disable-scroll-ionic2-ios9-not-working/44847/9

**Comment by krunal9421** [comment] 2017-11-23 03:46
I am facing this issue in android case. Any solution for it.

**Comment by aymehri** [comment] 2017-12-03 11:35
Hello i'm facing the same issue. Any update?

**Comment by fishme** [comment] 2018-02-01 06:43
I have the same issue. 2 years old bug...

**Comment by polfernandez** [comment] 2018-02-21 10:41
Hi guys, I still have the issue. Any update? 

attached 2 pictures showing the problem:

**--- Normal Screen ---**
![captura de pantalla 2018-02-21 a las 11 36 43](https://user-images.githubusercontent.com/32094365/36475664-a71f7252-16fb-11e8-826b-cc0c9e908eee.png)

**--- Screen goes up when keyboard appears ---**
![captura de pantalla 2018-02-21 a las 11 36 53](https://user-images.githubusercontent.com/32094365/36475662-a6fc4c96-16fb-11e8-80cd-efd9d921ffa8.png)

My code:

`
<ion-header>
  <ion-navbar>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ion-list no-lines> 
      <ng-container>
      </ng-container>
  </ion-list>
</ion-content>

<ion-footer>
 <ion-toolbar>
  <ion-item>
    <div item-content>
      <ion-textarea 
                    fz-elastic
                    (ionFocus)="_onFocus($event)"
                    (ionBlur)="_onBlur($event)"
                    (ionChange)="_onChange($event)"
                    (keypress)="_onKeypress($event)"
                    [disabled]="disabled"
                    [placeholder]="placeholder">
      </ion-textarea>
    </div>
  </ion-item>
 </ion-toolbar>
</ion-footer>

`

**Closed** 2018-11-01 19:53 UTC
Labels: ionitron: v3, keyboard, platform:android, platform:ios, slides, v2
