### ISSUE TITLE
ionic v4 No height ion-button expand="full" 

### ISSUE THREAD

**Issue by DmytroKurapin** [ionic-team/ionic#14573] opened 2018-06-04 18:21 UTC
```
@ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

global packages:

   cordova (Cordova CLI) : 8.0.0

local packages:

   @ionic/app-scripts : 3.1.9
   Cordova Platforms  : none
   Ionic Framework    : ionic-angular 3.9.2

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.10.0
   npm               : 6.1.0
   OS                : Windows 10

Environment Variables:

   ANDROID_HOME : C:\Android\android-sdk

```

**Describe the Bug**

**Steps to Reproduce**
1. Use `ion-button`
2. Set `expand="full`
3. Run `ionic serve`

**Expected Behavior**
A full width button should be visible with inherited from ion-toolbar height

**Result**
Height set as 2px 

```<ion-footer no-shadow>
  <ion-toolbar>
    <ion-button id="send-answer-btn" expand="full" (click)="sendAnswer(answerStr.value)">Отправить</ion-button>
  </ion-toolbar>
</ion-footer>
```

**Comment by mhartington** [comment] 2018-06-04 21:04
So a few things here:

1) ion-button as an element is not available in V3, which you have listed in your ionic info
2) using the correct markup does not recreate the same issue

https://stackblitz.com/edit/ionic-r1d3vt?file=pages%2Fhome%2Fhome.html

Closing as I am unable to reproduce.

**Closed by mhartington** 2018-06-04 21:04 UTC
Labels: triage

**Comment by DmytroKurapin** [comment] 2018-06-05 16:55
Updated version. Please check it.I
This issue happened only if I choose on Chrome Android based smartphone. On IPhone everything is ok.
Please check the pic
![image](https://user-images.githubusercontent.com/15969137/40990680-48d678de-68fa-11e8-933f-a0be24f02d52.png)

![image](https://user-images.githubusercontent.com/15969137/40990729-6d6f0134-68fa-11e8-877f-ddddd87e2fb3.png)

**Comment by mhartington** [comment] 2018-06-05 17:31
Again, not able to replicate this.


![screen shot 2018-06-05 at 1 30 26 pm](https://user-images.githubusercontent.com/2835826/40992367-9d93f526-68c4-11e8-91a9-badfcf65debf.png)


Though it looks like you have some custom CSS being applied. 
I would debug this further and post on the forum or slack.
