### ISSUE TITLE
ion-datetime allows invalid dates

### ISSUE THREAD

**Issue by devnetics** [ionic-team/ionic#13287] opened 2017-10-30 18:56 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

1) When the datetime picker opens, if you select January 31, then scroll the month to February, it stays on 31st. You can click done, and the date saves as February 31st. Then, when you reopen the picker, the options only go to 28, even though the ngModel value is 31st.

2) Set the picker to February 28. Save it. Then open the picker again. Move the Month field to January. The day options do not update to allow up to 31, they stay limited to 28th.

3) Set the picker to January 28th. Save it. Then open the picker again. Move the Month field to February. The day options do not update to only allow up to 28, they stay limited up to the 31st.

**Expected behavior:**
The picker should be appropriately updated to show the correct number of days in a given month, for all months. It should not be possible to save dates such as Feb 31.

**Steps to reproduce:**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6577282/32190802-616c0e0c-bd85-11e7-8b14-8eca239872ec.gif)

**Related code:**
https://github.com/devnetics/datetime-demo

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
dev/myapp [master] » ionic info

cli packages: (/Users/a6277/.nvm/versions/node/v6.11.0/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : macOS Sierra

Misc:

    backend : legacy
```

**Comment by devnetics** [comment] 2017-10-30 19:17
Sorry about the slow gif, updated it with a faster one.

**Comment by kensodemann** [comment] 2017-10-30 19:29
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #12533. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-10-30 19:29 UTC

**Comment by devnetics** [comment] 2017-10-30 19:34
Ah thank you!

**Comment by francesco-taioli** [comment] 2018-08-02 17:18
anyone know how to fix this?
