### ISSUE TITLE
ionic support Chinese problem

### ISSUE THREAD

**Issue by baorr** [ionic-team/ionic#11886] opened 2017-06-01 09:26 UTC
when I type Chinese once, the result showed below:

<img width="396" alt="ad934d6f-b3c9-4155-b4eb-b411326646a2" src="https://cloud.githubusercontent.com/assets/553038/26672412/a0cb0960-46eb-11e7-817e-255347c5b80a.png">

**Comment by baorr** [comment] 2017-06-01 09:27
by the way, the demo happened
http://ionicframework.com/docs//components/#searchbar also

**Comment by CloverEc** [comment] 2017-06-01 10:54
ion-searchbar bug on 3.1.0, 3.1.1, 3.2.0 for non-latin languages. #11566

**Comment by jgw96** [comment] 2017-06-01 13:35
Hello all, closing this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11566

**Closed by jgw96** 2017-06-01 13:35 UTC
