### ISSUE TITLE
bug: translucent toolbar blurred during page transition

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/ionic#19158] opened 2019-08-22 11:26 UTC
# Bug Report

**Ionic version:**

[x] **4.8**

**Current behavior:**

Title in toolbar is blurred during page transition.

**Expected behavior:**

Title should be clear.

**Steps to reproduce:**

1. Checkout conference app, add translucent="true" to `ion-header` and `fullscreen` to `ion-content.
2. Click a link to go to another back
3. Go back
4. Observe title is blurred until transition/animation is done

**Related code:**
```html
<ion-header translucent="true">
	<ion-toolbar>
		<ion-title>Title is blurred during transition</ion-title>
	</ion-toolbar>
</ion-header>

<ion-content fullscreen>
	Content
</ion-content>
```

![image](https://user-images.githubusercontent.com/230182/63511039-6ce24f80-c4e0-11e9-8070-8c97f3e3225c.png)

**Comment by liamdebeasi** [comment] 2019-08-22 13:12
Thanks for the issue. If you downgrade to Ionic 4.7.4, does this issue still occur?

**Comment by biesbjerg** [comment] 2019-08-26 09:47
I can confirm 4.7.4 also have this issue.

**Comment by DavidStrausz** [comment] 2020-01-24 10:10
@liamdebeasi Will this get addressed before the v5 release? Makes translucent headers kind of unusable as it causes ugly flickers.

I may be able to help with a PR if needed.

**Comment by liamdebeasi** [comment] 2020-01-24 13:56
A PR would be great if you are willing!

**Comment by DavidStrausz** [comment] 2020-01-27 17:23
@liamdebeasi Cool, whats the design decision thats needed to get started? Or as you probably already thought about possible solutions internally, whats the preferred way of resolving this?

**Comment by liamdebeasi** [comment] 2020-01-27 20:50
I had some time today to take a look. Can you try the following dev build and let me know if the issue is resolved for you: `5.0.0-dev.202001272042.c9dfe30`.

It looks like this issue is happening because a) the backdrop filter is not being applied to the correct element and b) we are not transitioning the toolbar background properly during nav transitions.

**Comment by DavidStrausz** [comment] 2020-01-28 13:58
@liamdebeasi Oh great - dev build fixes the transition! Thanks!

**Comment by liamdebeasi** [comment] 2020-01-29 20:12
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20314 and will be available in an upcoming release of Ionic Framework.

**Closed** 2020-01-29 20:12 UTC
Labels: needs: design decision, package: core, type: bug
