### ISSUE TITLE
bug: Ionic 4 Native Push .on("notification") not triggered

### ISSUE THREAD

**Issue by sreerajkarippala** [ionic-team/ionic#18202] opened 2019-05-05 06:10 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When an notification receive and clicked, the .on("notification") is not triggering, my code is
```
this.platform.ready().then(async () => {
      const options: PushOptions = environment.PushNotification;
      const pushObject: PushObject = this.push.init(options);
      pushObject.on('notification').subscribe(notification => {
        console.log('Received a notification', notification);
      });
      pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    });
```
Notification payload is
```
{
    "registration_ids": [_push_token_],
    "priority": "high",
    "content_available": true,
    "data": {
        "title": "A short string describing the purpose of the notification",
        "body": "The text of the alert message",
        "style": "picture",
        "picture": "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg",
        "summaryText": "The internet is built on cat pictures"
    }
}
```
**Expected behaviour:**
`console.log('Received a notification', notification);` should display log `data` from notification.

**Steps to reproduce:**

Using Ionic 4 native push example code(https://ionicframework.com/docs/native/push) in my code
**Related code:**

```
import { Push, PushObject, PushOptions } from '@ionic-native/push/ngx';

constructor(private push: Push) { }

...


// to check if we have permission
this.push.hasPermission()
  .then((res: any) => {

    if (res.isEnabled) {
      console.log('We have permission to send push notifications');
    } else {
      console.log('We do not have permission to send push notifications');
    }

  });

// Create a channel (Android O and above). You'll need to provide the id, description and importance properties.
this.push.createChannel({
 id: "testchannel1",
 description: "My first test channel",
 // The importance property goes from 1 = Lowest, 2 = Low, 3 = Normal, 4 = High and 5 = Highest.
 importance: 3
}).then(() => console.log('Channel created'));

// Delete a channel (Android O and above)
this.push.deleteChannel('testchannel1').then(() => console.log('Channel deleted'));

// Return a list of currently configured channels
this.push.listChannels().then((channels) => console.log('List of channels', channels))

// to initialize push notifications

const options: PushOptions = {
   android: {},
   ios: {
       alert: 'true',
       badge: true,
       sound: 'false'
   },
   windows: {},
   browser: {
       pushServiceURL: 'http://push.api.phonegap.com/v1/push'
   }
}

const pushObject: PushObject = this.push.init(options);


pushObject.on('notification').subscribe((notification: any) => console.log('Received a notification', notification));

pushObject.on('registration').subscribe((registration: any) => console.log('Device registered', registration));

pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 12 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.10.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment] 2019-05-06 13:06
Hi there,

Thanks for the issue. Does this issue still occur if you subscribe to the notification using the raw Cordova plugin command? (See: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback)

Thanks!

**Comment by sreerajkarippala** [comment] 2019-05-06 13:20
i change the code to
```
this.platform.ready().then(async () => {
      const options: PushOptions = environment.PushNotification;
      const pushObject: PushObject = this.push.init(options);
      pushObject.on('notification', (notification) => {
        console.log('Received a notification', notification);
      });
      pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    });
```
is that i need to do ? it gives an IDE give an error `Expected 1 arguments, but got 2.`

**Comment by liamdebeasi** [comment] 2019-05-06 13:39
Hi there,

I am trying to determine if this is an issue with the Ionic Native wrapper or with the Cordova plugin. Please give your code a try using the plugin's methods directly (without using the wrapper): https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#api

So you'll need to call the init method using something like `PushNotification.init` (or whatever variable the plugin is exposed as) and then do the rest of your business logic.

**Comment by sreerajkarippala** [comment] 2019-05-10 04:53
> Hi there,
> 
> Thanks for the issue. Does this issue still occur if you subscribe to the notification using the raw Cordova plugin command? (See: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback)
> 
> Thanks!

i change the code to
```
this.platform.ready().then(async () => {
      const options: PushOptions = environment.PushNotification;
      const pushObject: PushObject = this.push.init(options);
      pushObject.on('notification', (notification) => {
        console.log('Received a notification', notification);
      });
      pushObject.on('error').subscribe(error => console.error('Error with Push plugin', error));
    });
```
is that i need to do ? it gives an IDE give an error `Expected 1 arguments, but got 2.`

**Comment by liamdebeasi** [comment] 2019-05-10 14:01
Hi there,

I am going to close this issue as this is an implementation issue, not a bug with Ionic. The Ionic Native wrapper exposes Observables that you can subscribe to, so doing `pushObject.on('notification', (notification) => {` is going to throw an error. Please review the [Push - Ionic Native Documentation](https://ionicframework.com/docs/native/push) for more information.

For further help implementing your code, feel free to post on our [forum](forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

Thanks!

**Closed by liamdebeasi** 2019-05-10 14:01 UTC
Labels: triage
