### ISSUE TITLE
bug: iOS app closes suddenly

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#20954] opened 2020-04-02 17:43 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

the happens only with iOS and works fine with Android. When launching the app after launch I try to show an array of objects (in this instance an array of messages) the App locks up when trying to show or render any array. An array of users, it freezes and closes completely, an array of messages (that only contain one object) freezes and closes.

*edit* it happens after the app has been open for more than 5 seconds... I have tried to log the issue but there is a silent crash nd provides me no more information

**Expected behavior:**

for it not to close or at least throw an error

**Steps to reproduce:**

try and render an array of objects

**Related code:**
I can't really show as this issue is *ONLY* with iOS

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.4.0 (/Users/christianfrancia/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.9.0
   native-run                             : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/christianfrancia/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.11.0 (/usr/local/Cellar/node/13.11.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-04-02 17:51
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by ctfrancia** [comment] 2020-04-05 18:34
so there isn't anything that appears to be ionic's fault? The issue was solved after deleting the app and re-installing... Which shouldn't be the solution in real life. I tried getting the crash logs bug nothing was generated. I just don't see why when people are asking me why the app is crashing I need to steel them to delete the app and re install it.

**Comment by liamdebeasi** [comment] 2020-04-06 13:13
Without seeing your application and without knowing if this is caused by Ionic Framework or not, it is hard to say for certain. I am going to close this as the issue sounds more application-specific, but if you find something that suggests this is a bug in Ionic Framework please feel free to open a new issue. Thanks!

**Closed by liamdebeasi** 2020-04-06 13:13 UTC
Labels: triage
