### ISSUE TITLE
bug: Ionic 5.0.1 ion-segment not working in mobile browser

### ISSUE THREAD

**Issue by JoeBoxr** [ionic-team/ionic#20574] opened 2020-02-20 19:38 UTC
# Bug Report

**Ionic version:**

[x] 5.0.1

**Current behavior:**
With 2 or more ion-segments you are unable to click the other segments in the mobile browser.
Works as expected on desktop browser.

**Expected behavior:**
ion-segments would display the associated segment when clicked.

**Steps to reproduce:**
1. ionic start myApp tabs
2. add the following to a tab...
`<ion-segment>
    <ion-segment-button value="guest">
      <ion-icon name="person"></ion-icon>
      <ion-label>Guest Login</ion-label>
    </ion-segment-button>
    <ion-segment-button value="profile">
      <ion-icon name="person-add"></ion-icon>
      <ion-label>Profile Login</ion-label>
    </ion-segment-button>
  </ion-segment>`

3. ionic serve
4. open developer tools in chrome and toggle device toolbar
5. try to click a different segment button than the one selected

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-02-20 19:52
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20466.

**Closed by liamdebeasi** 2020-02-20 19:52 UTC
Labels: triage
