### ISSUE TITLE
ion-datetime doesn't allow day selection before specified min value

### ISSUE THREAD

**Issue by dafi** [ionic-team/ionic#17636] opened 2019-02-28 06:19 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Set minimum value for example to 27 February 2019, then trying to select March 2 2019 it's impossible.
The days of month lower than 27 are not selectable for month higher the minimum

**Expected behavior:**

Scrolling to month (or year) higher than min but allow to select all days of month

**Steps to reproduce:**

**Related code:**

```xml
<ion-datetime 
           display-format="DD/MM/YYYY"
           min="2019-02-27"
           value="2019-02-27">
</ion-datetime>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.9.0 (/usr/local/Cellar/node/10.9.0/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment] 2019-02-28 13:33
Hi there,

Thanks for opening an issue with us! I am going to close this as a duplicate of #17060. Please note that issue has been merged into #16630 which we are using to track all datetime issues.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-28 13:33 UTC
Labels: triage
