### ISSUE TITLE
bug: ion-content going behind ion-tabs randomly

### ISSUE THREAD

**Issue by Mautriz** [ionic-team/ionic#21303] opened 2020-05-14 20:49 UTC
# Bug Report

**Ionic version:**
^5.0.0

**Current behavior:**
Absolute positioning behavior is different in the first loaded tab from the others
ion-content "content" takes consideration of the first ion-tabs-toolbar for the first loaded tab, while ignoring it and going behind it when switching tabs

This seems to happen only with the md styles, the ios styles ion-content always ignores the tabs-toolbar

**Expected behavior:**
Every tab should behave the same, It's not really important if it ignores the tabs or not, just consistent behavior

**Steps to reproduce:**
> ionic start {name} tabs --type=angular --capacitor
> ionic serve
(literally haven't changed anything, I tried changing cli from 6.7 to 6.9, restarting, recreating the project multiple times, nothing seemed to change)

**Environment**
MacOS 10.15.4
Chrome (Last Version)
Firefox
Safari

**Related code:**
As stated above, the standard tab template

These images demonstrate the behavior, the only thing I did to make it superclear is changing the "explore-container.component.scss" from having #container { top: 50% } to { bottom: 0 }

First page load
<img width="351" alt="app1" src="https://user-images.githubusercontent.com/48245404/81984464-1bad5980-9635-11ea-9d15-a1c4f9a2d3a0.png">
After moving to template 2 and 3
<img width="360" alt="app2" src="https://user-images.githubusercontent.com/48245404/81984469-1cde8680-9635-11ea-8248-58ce6674d42e.png">
<img width="367" alt="app3" src="https://user-images.githubusercontent.com/48245404/81984472-1d771d00-9635-11ea-859b-85fba37cf399.png">
This is after reloading the page, starting at the third tab position
<img width="360" alt="app4" src="https://user-images.githubusercontent.com/48245404/81984473-1e0fb380-9635-11ea-8693-de3cf1bee4fe.png">

**Comment by liamdebeasi** [comment] 2020-05-15 13:01
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/21130.

**Closed by liamdebeasi** 2020-05-15 13:01 UTC
Labels: triage
