### ISSUE TITLE
Ionic overlay components cause rendering bugs

### ISSUE THREAD

**Issue by JustasKuizinas** [ionic-team/ionic#12633] opened 2017-08-10 09:08 UTC
**Ionic version:**  (check one with "x")
[ x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report

**Current behavior:**
Opening alert modal and then menu, causes strange app rendering bugs.

**Expected behavior:**
Opened menu shouldn't cause any rendering weirdness.

**Steps to reproduce:**
1. Download https://github.com/ionic-team/ionic-conference-app
2. run `npm install`
3. run `ionic serve`
4. Open in chrome and toggle device mode
5. Set width 320px and height 500px
6. Go to tab 'About'
7. Scroll to bottom
8. Open location select
9. Push on backdrop to close location select
10. Then open menu
11. Drag menu left with mouse and rendering bug appears

**Other information:**
Adding some screen recording

![screencast 12-00 10-08-2017](https://user-images.githubusercontent.com/5862640/29163238-86171982-7dc4-11e7-9211-329698bed93a.gif)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (D:\Projects\Testing stuff\ionic-conference-app\node_modules\@ionic\cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (D:\Projects\Testing stuff\ionic-conference-app\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (D:\Projects\Testing stuff\ionic-conference-app\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (D:\Projects\Testing stuff\ionic-conference-app\node_modules\ionic)

global packages:

    Cordova CLI : 6.4.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.3
    Node              : v7.4.0
    OS                : Windows 10
    npm               : 5.3.0
```

**Comment by jgw96** [comment] 2017-08-10 17:27
Hello! Thanks for using Ionic! Unfortunately I am not able to reproduce this issue. I made a screencast here to show my results https://drive.google.com/file/d/0Bzwe5hrqVKjhOGlkRkx1UmRVMVk/view?usp=sharing

**Comment by JustasKuizinas** [comment] 2017-08-10 18:19
HI ,

@jgw96  when you opened About page have you pressed location select? :)

Try to pen About page. press location select, close location popup clicking on backdrop, then open menu

**Comment by kensodemann** [comment] 2017-08-17 20:58
This appears to be an issue with the Blink engine. What I did was ran @JustasKuizinas 's test, including pressing the location select, on the following browsers:

1. Chrome
2. Opera
3. Firefox
4. Safari

The issue only occurred on Chrome and Opera, which both use the Blink engine

**Comment by kensodemann** [comment] 2017-10-05 20:19
Last time I looked at this, I could only replicate the issue on browsers using the Blink engine. I just retried today on Chrome 61 and the issue is now much harder to duplicate there, though it still can be.

I am closing this as something that is not an issue with the Ionic Framework, but is apparently a minor issue with specific rendering engines.

**Closed by kensodemann** 2017-10-05 20:19 UTC
Labels: needs info, v2
