### ISSUE TITLE
Focusing ion-textarea inside ionslides

### ISSUE THREAD

**Issue by lordsteggu** [ionic-team/ionic#13573] opened 2017-12-04 15:40 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I have a form setup inside the ion-slides component, when deploying to android (OnePlus3T Oreo) and selecting the ion-textarea from within the form, the keyboard pops up, but it also pushes the entire content out of view.

If I take the form outside of the ion-slides, and then select the notes field, the content is selected as expected

**Expected behavior:**
Having a form inside an ion-slide should behave the same as outside when it comes to display the keyboard

**Steps to reproduce:**
Deploy the attached demo project to an android device
Click on the notes field
keyboard will push entire content out of view

comment out the slides wrapping around the form
update formgroup to currentObservation.FormGroup from observation.FormGroup
deploy to android
click notes field
notice the content is not thrown out of view

Here is the link to the git repo https://github.com/lordsteggu/KeyboardDemo, if it is something I am doing wrong then just let me know. 

Cheers 

:)

```
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.4.0
    npm  : 5.3.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by comfortme** [comment] 2017-12-06 08:51
this an old unsolved issue https://github.com/ionic-team/ionic/issues/9553

**Comment by lordsteggu** [comment] 2017-12-06 09:24
Hi,

Thank you for directing me to this. 
To get around it at the moment I have just overridden the ion-slides css with position absolute and the desired top left and right settings, this is not ideal by any means. 

Fortunately I am using it in a modal which means the absolute positioning is not much of an issue.

I guess it's just a case of wait until one of the team can fix the issue.

Cheers

**Comment by mlynch** [comment] 2018-01-05 23:21
Closing as duplicate of #9553

**Closed by mlynch** 2018-01-05 23:21 UTC
