### ISSUE TITLE
Android Side menu not closed after upgrade ionic - 4.9.0

### ISSUE THREAD

**Issue by pandeeswaran** [ionic-team/ionic#19284] opened 2019-09-06 11:01 UTC
Android -  Side menu not closed after upgrade ionic - 4.9.0 . It was working well in iOS
/main-es2015.6213d8ceb27509fb7230.js:84382 Uncaught (in promise) TypeError: Cannot read property 'updateTiming' of undefined
    at getWebAnimations.forEach.animation (/main-es2015.6213d8ceb27509fb7230.js:84382)
    at Array.forEach (<anonymous>)
    at updateWebAnimation (/main-es2015.6213d8ceb27509fb7230.js:84381)
    at Object.update (/main-es2015.6213d8ceb27509fb7230.js:84424)
    at childAnimations.forEach.animation (/main-es2015.6213d8ceb27509fb7230.js:84420)
    at Array.forEach (<anonymous>)
    at update (/main-es2015.6213d8ceb27509fb7230.js:84419)
    at Object.direction (/main-es2015.6213d8ceb27509fb7230.js:84096)
    at Menu.startAnimation (/100-es2015.bf54cbdbd0c6f32d2ae4.js:238)
    at Menu._setOpen (/100-es2015.bf54cbdbd0c6f32d2ae4.js:211)
getWebAnimations.forEach.animation @ /main-es2015.6213d8ceb27509fb7230.js:84382
updateWebAnimation @ /main-es2015.6213d8ceb27509fb7230.js:84381
update @ /main-es2015.6213d8ceb27509fb7230.js:84424
childAnimations.forEach.animation @ /main-es2015.6213d8ceb27509fb7230.js:84420
update @ /main-es2015.6213d8ceb27509fb7230.js:84419
direction @ /main-es2015.6213d8ceb27509fb7230.js:84096
startAnimation @ /100-es2015.bf54cbdbd0c6f32d2ae4.js:238
_setOpen @ /100-es2015.bf54cbdbd0c6f32d2ae4.js:211
/main-es2015.6213d8ceb27509fb7230.js:16249 ERROR Error: Uncaught (in promise): JSON error
    at resolvePromise (/polyfills-es2015.651225db28f4e5ead140.js:806)
    at resolvePromise (/polyfills-es2015.651225db28f4e5ead140.js:765)
    at zone.scheduleMicroTask (/polyfills-es2015.651225db28f4e5ead140.js:867)
    at ZoneDelegate.invokeTask (/polyfills-es2015.651225db28f4e5ead140.js:413)
    at Object.onInvokeTask (/main-es2015.6213d8ceb27509fb7230.js:46101)
    at ZoneDelegate.invokeTask (/polyfills-es2015.651225db28f4e5ead140.js:412)
    at Zone.runTask (/polyfills-es2015.651225db28f4e5ead140.js:181)
    at drainMicroTaskQueue (/polyfills-es2015.651225db28f4e5ead140.js:583)

**Comment by liamdebeasi** [comment] 2019-09-06 11:17
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19272.

**Closed by liamdebeasi** 2019-09-06 11:17 UTC
Labels: triage
