### ISSUE TITLE
ionic 4.2.0 bottom  tabs  Jump subpages  back  Will point to HOME

### ISSUE THREAD

**Issue by lccWEBApp** [ionic-team/ionic#17995] opened 2019-04-08 10:32 UTC
ionic 4.2.0 bottom  tabs  Jump subpages  back  Will point to HOME，It's really a headache to ask for improvements to this feature, or to give an official solution, ionic4's use is not as good as previous generations.

Ionic:

   ionic (Ionic CLI)             : 4.10.2 (D:\npmConfig\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : not available

**Comment by liamdebeasi** [comment] 2019-04-08 14:58
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17278.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-08 14:58 UTC
Labels: triage
