### ISSUE TITLE
bug: undefined error with production build

### ISSUE THREAD

**Issue by jeffersonveloso** [ionic-team/ionic#19733] opened 2019-10-23 14:28 UTC
Testing the app with the ionic cordova run browser command it works normally when I generate the production build with the ionic build --prod --release command and send it to my hosting as the documentation says or using firebase hosting generates the console errors.

main-es2015.bbc63cf846c6411c3ada.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined
    at main-es2015.bbc63cf846c6411c3ada.js:1
    at a.invoke (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvoke (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invoke (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.run (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at polyfills-es2015.558cb2cc942b93a94480.js:1
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvokeTask (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.runTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at P (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at polyfills-es2015.558cb2cc942b93a94480.js:1
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvokeTask (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.runTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at _ (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at c.invokeTask [as invoke] (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at y (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at HTMLHeadingElement.k (polyfills-es2015.558cb2cc942b93a94480.js:1)

main-es2015.bbc63cf846c6411c3ada.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'platform' of undefined
TypeError: Cannot read property 'platform' of undefined
    at main-es2015.bbc63cf846c6411c3ada.js:1
    at a.invoke (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvoke (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invoke (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.run (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at polyfills-es2015.558cb2cc942b93a94480.js:1
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvokeTask (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.runTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at P (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at polyfills-es2015.558cb2cc942b93a94480.js:1
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at Object.onInvokeTask (main-es2015.bbc63cf846c6411c3ada.js:1)
    at a.invokeTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at t.runTask (polyfills-es2015.558cb2cc942b93a94480.js:1)
    at _ (polyfills-es2015.558cb2cc942b93a94480.js:1)

main-es2015.bbc63cf846c6411c3ada.js:1 Native: InAppBrowser is not installed or you are running on a browser. Falling back to window.open.

**Ionic info:**
Ionic:
   Ionic CLI                     : 5.4.4 (C:\Users\Pichau\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-webview 4.1.2, (and 10 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Pichau\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment] 2019-10-23 14:49
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The minified errors don't really tell us too much information.

**Comment by jeffersonveloso** [comment] 2019-10-23 14:53
> Obrigado pelo problema. Você pode fornecer um repositório com o código necessário para reproduzir esse problema? Os erros minimizados não nos dizem muita informação.

I have a console image after page load, can it be? About informing the repository I need to check because it is a private project of the company.


> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The minified errors don't really tell us too much information.

**Comment by jeffersonveloso** [comment] 2019-10-23 14:54
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The minified errors don't really tell us too much information.

I have a console image after page load, can it be? About informing the repository I need to check because it is a private project of the company.

**Comment by jeffersonveloso** [comment] 2019-10-23 16:25
> Obrigado pelo problema. Você pode fornecer um repositório com o código necessário para reproduzir esse problema? Os erros minimizados não nos dizem muita informação.



> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? The minified errors don't really tell us too much information.

Can it be a project link on google drive or does it need to be on github?

**Comment by liamdebeasi** [comment] 2019-10-23 17:06
A project link on Google Drive is fine.

**Comment by jeffersonveloso** [comment] 2019-10-23 17:17
> Um link de projeto no Google Drive está bom.



> A project link on Google Drive is fine.

Attached is the link -> https://drive.google.com/open?id=1-5CSYIoZbc-jRqwcL5r4rg2ZQp26bez7

**Comment by liamdebeasi** [comment] 2019-10-23 17:30
Thanks for the follow up. It looks like you have a bug in `user.service.ts:38`:

```javascript
const devicePlatform = platform.win.device.platform.toLowerCase();
```

`platform` is undefined. This might be a variable that is only defined when running as a standalone app in Cordova. The other `subscribe` error also appears to be a bug in your code. I would recommend reviewing your app to ensure that these properties/variables are defined before accessing them.

I am going to close this issue as this is not a bug in Ionic Framework.

**Closed by liamdebeasi** 2019-10-23 17:30 UTC
Labels: triage
