### ISSUE TITLE
Add css property for ion-select to change opacity of placeholder

### ISSUE THREAD

**Issue by ArkeshGKalathiya** [ionic-team/ionic#19829] opened 2019-11-03 11:01 UTC
Currently placeholder's opacity of ion-select can't be changed directly, it would be good to have some css variables.

**Comment by bryplano** [comment] 2019-11-08 18:37
Closing this as a dupe of https://github.com/ionic-team/ionic/issues/17446.

**Closed by bryplano** 2019-11-08 18:37 UTC
Labels: package: core, type: feature request
