### ISSUE TITLE
bug: Modal border radius 0

### ISSUE THREAD

**Issue by assman** [ionic-team/ionic#20878] opened 2020-03-26 09:25 UTC
<img width="1021" alt="Screen Shot 2020-03-26 at 5 19 34 PM" src="https://user-images.githubusercontent.com/14093665/77630843-aa332200-6f86-11ea-87f0-528b61409f22.png">

When I first open the modal, the border radius is fine. However, after I scroll down within the modal to view the content, the border radius of the bottom corners disappears

**Comment by liamdebeasi** [comment] 2020-03-26 14:12
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by assman** [comment] 2020-03-26 14:30
> Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

Yes, here it is.

https://github.com/assman/ticket-ionic

**Comment by liamdebeasi** [comment] 2020-03-26 15:51
Thanks for the follow up. It looks like this is a quirk with Safari. I will put up a PR to account for this, but as a temporary workaround you can add the following CSS to `global.scss`:

```css
ion-modal .ion-page {
  border-radius: inherit;
}
```

**Comment by assman** [comment] 2020-03-28 06:13
Thank you very much Liam. Your help is greatly appreciated. On a side note, may I ask if there is a way to hide the scroll bar or to customize its styling? When the app runs in dark mode, the scroll bar still appears white in color which makes the app look broken and unfinished.

**Comment by liamdebeasi** [comment] 2020-03-30 15:56
There is a discussion regarding customizing scrollbars here: https://github.com/ionic-team/ionic/issues/17685#issuecomment-587633556

In general though, the device you are using should take care of scrollbar styling on dark mode automatically (at least macOS/iOS does).

**Comment by liamdebeasi** [comment] 2020-03-30 15:57
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20887 and will be available in an upcoming release of Ionic Framework.

**Closed** 2020-03-30 15:56 UTC
Labels: package: core, type: bug

**Comment by assman** [comment] 2020-03-30 16:35
> There is a discussion regarding customizing scrollbars here: https://github.com/ionic-team/ionic/issues/17685#issuecomment-587633556
> 
> 
> 
> In general though, the device you are using should take care of scrollbar styling on dark mode automatically (at least macOS/iOS does).

Agreed. Unfortunately in the Ionic app that I’m working on, the scroll bar shows white in color even when dark mode is active throughout the app. Could this be another bug particular to safari ?

**Comment by liamdebeasi** [comment] 2020-03-30 18:08
Hmm that might be the case. Can you open a separate issue with a reproduction? I can take a look.
