### ISSUE TITLE
Calendar picker for datetime component

### ISSUE THREAD

**Issue by LokeSonne** [ionic-team/ionic#12341] opened 2017-07-13 09:09 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The datetime component is generally very good for touch based interfaces but not suitable for web/mouse based interfaces. Would you consider adding a template with calendar+time based UI? Ionic is now pretty useful for desktop web apps, and this would be a very useful feature. 

Kate Mihalikova made a very useful (one)[https://github.com/katemihalikova/ion-datetime-picker] for ionic v1, but so far I have not been able to find one for ionic v2+

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by AmitMY** [comment] 2017-07-13 09:18
Duplicate of https://github.com/ionic-team/ionic/issues/12336

**Comment by jgw96** [comment] 2017-07-13 14:23
Hello all! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12336.

**Closed by jgw96** 2017-07-13 14:23 UTC
