### ISSUE TITLE
bug: ion-select not updating div.select-text value on API update

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic#19728] opened 2019-10-22 19:46 UTC
The bug reported in #17225 still persists.

# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Populating an ion-select from a method that does an async call (for example API) to get all options does not work as expected.
I can properly set the actual form value, but the div.select-text is empty until I open the select. In the moment the select is opened, the div.select-text is filled with the expected value.

**Expected behavior:**
Fill the div.select-text as soon as the select's value is set. This bug leads to users thinking they have not filled in the select yet, even if they did.

**Steps to reproduce:**
- Take an ion-select
- Do an API call (or big delay) to fill in the select options and the default value
- This bug can not be reproduced in the browser, it needs to be on Android or iOS
- Chrome shows the bug on Mac OS when an Android or iOS device is selected in the dev tools

**Ionic info:**

```
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.803.9
   @angular-devkit/schematics    : 8.3.9
   @angular/cli                  : 8.3.9
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

Utility:

   cordova-res : 0.8.0 
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by iamkinetic** [comment] 2019-10-22 22:14
Same problem as these two?
* #19436
* #19324

**Comment by andreas-aeschlimann** [comment] 2019-10-22 22:41
Ah damn, missed those. It is indeed pretty likely that I have the same problem.

**Comment by liamdebeasi** [comment] 2019-10-23 12:52
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19324.

**Closed by liamdebeasi** 2019-10-23 12:52 UTC
Labels: triage
