### ISSUE TITLE
Tabs don't load when upgrading from Angular 6 to 6.1

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic#15155] opened 2018-08-13 11:30 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.4

System:

   NodeJS : v10.8.0 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : not set
```

**Describe the Bug**
I've updated my app from Angular 6 to Angular 6.1, because the `ionic-conference-app` got this update too.
Before the update, the lazy loaded tabs were displayed and everything was working fine. Now, only the TabsPage is loaded, all lazy loaded tabs are not.

**Steps to Reproduce**
1.  Checkout `ionic-conference-app` on branch `core-update`
2.  Modify the `routes` described in `tabs-page-routing.module.ts` to use lazy loading:

This is the route configuration, that does work with Angular 6.0.2 and 6.1.2
```
{
    path: 'schedule',
    component: SchedulePage,
    outlet: 'schedule'
},
```

This one only works with Angular 6.0.2:
```
{
    path: 'schedule',
    outlet: 'schedule',
    loadChildren: '../schedule/schedule.module#ScheduleModule'
}
```
3.  See, that the Schedule page is not being loaded anymore

I've used [this](https://www.joshmorony.com/creating-a-tabs-layout-with-angular-routing-and-ionic-4/) article to create tabs that are lazy loaded

**Expected Behavior**
The tabs get loaded with Angular 6 and 6.1

**Comment by EWBears** [comment] 2018-08-13 19:28
Hi Carston - my understanding is that you generally shouldn't be upgrading either Angular or Typescript versions unless the ionic team pushes out an update to support the new versions.

I believe that you should be upgrading ionic-native, cordova platforms, cordova plugins, and app scripts, but leave the Angular and Typescript alone because upgrade often cause unexpected breaking changes in ionic.  Hopefully someone from the ionic team can correct me if this is incorrect!

**Comment by kensodemann** [comment] 2018-08-13 19:35
Ionic v4 should work just fine with Angular 6.1. AAMOF, I am working on two different projects right now that use Ionic v4 with Angular 6.1, one is currently using beta.1 the other beta.0 (I have not upgraded them to beta.2 yet).

I have not tried the conference app yet.

**Comment by EWBears** [comment] 2018-08-13 19:37
Gotcha - thanks for the correction Ken! Sorry for the misunderstanding/misinformation.

**Comment by kensodemann** [comment] 2018-08-13 20:04
I should also note that I am not using lazy loading. I am in the process of switching the simplest of my apps over to that now to see if I can duplicate the issue.

**Comment by carstenbaumhoegger** [comment] 2018-08-14 05:33
hey @EWBears:
You're absolutely right, I was just trying to update to the Angular version used in die Ionic conference app. That's why I'm surprised the exact same combination of versions doesn't work when using lazy loading.

@kensodemann thanks for looking into this!

**Comment by MrSparklle** [comment] 2018-08-14 14:35
@carstenbaumhoegger I created a new project using default ionic tabs template (`ionic start NewApp tabs type=angular` and it works fine using lazy loading. 

After project created, I update Angular to latest version 6.1.2 without any troubles. Everything works fine for me.

**Comment by kensodemann** [comment] 2018-08-15 11:36
@MrSparklle - could you upload one of those samples to a GitHub repo? I have some apps that are only slightly modified from the starter (other than making it lazy loading on the individual tab pages, which the starter does not do), and it did not work for me. I would like to have a look at what you did.

**Comment by MrSparklle** [comment] 2018-08-15 16:18
@carstenbaumhoegger @kensodemann Sorry guys. I tought the lazy loading was implemented the default in tabs started but it seems it's not. I made a research this morning and this issue is being treated in this issue https://github.com/ionic-team/ionic/issues/14566

**Comment by mhartington** [comment] 2018-09-12 21:50
Closing as duplicate of https://github.com/ionic-team/ionic/issues/14566

**Closed by mhartington** 2018-09-12 21:50 UTC
Labels: triage
