### ISSUE TITLE
bug: ion-infinite-scroll not emit after changing to another tab and back

### ISSUE THREAD

**Issue by caothuong** [ionic-team/ionic#21440] opened 2020-06-05 09:43 UTC
**Ionic version:**
"@ionic/angular": "^4.7.1",
 "@angular/core": "~8.1.2",
 "@angular/forms": "~8.1.2",

I have three tabs use the one content together as bellow:
`<ion-content>
  <ng-container [ngSwitch]="true">
    <ng-container *ngSwitchCase="selectedTab == constant.ReminderpanelValue.Overview">
      <app-reminder-overview [reminder]="reminders"></app-reminder-overview>
    </ng-container>
    <ng-container *ngSwitchCase="selectedTab == constant.ReminderpanelValue.Overdue || selectedTab == constant.ReminderpanelValue.Today || selectedTab == constant.ReminderpanelValue.Future">
      <ion-refresher slot="fixed" (ionRefresh)="refresh($event)">
        <ion-refresher-content pullingText="{{ 'COMMON.PULL_TO_REFRESH' | translate }}" refreshingSpinner="crescent">
        </ion-refresher-content>
      </ion-refresher>
    <app-reminder-list [reminders] = "reminder?.Reminders" >
  </app-reminder-list>
  <ion-infinite-scroll threshold="200px" (ionInfinite)="loadMore($event)"></ion-infinite-scroll>
    </ng-container>
  </ng-container>
</ion-content>`

  loadMore(event) {
      this.getReminder().finally(() => event.target.complete());
  }

the first open screen that it work but when switch to another tab then ionInfinite event not effect.

**Comment by caothuong** [comment] 2020-06-11 03:33
Hi @liamdebeasi can you help me reproduction and fix it as soons as possible i need to apply to my project. Thanks you!

**Comment by liamdebeasi** [comment] 2020-06-11 13:38
Hi there,

The easiest way to create a reproduction is to take a blank Ionic starter application, and add the minimum amount of code needed to make the bug appear again.

In this case, you should use a blank Ionic tabs starter application. We have a code reproduction guide you can follow too: https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction. This gives you tips on how to make an easy to use reproduction.

**Comment by caothuong** [comment] 2020-06-15 09:05
Thanks @liamdebeasi so much for supporting, I found my mistake :) I forgot set complete event in case else.

**Comment by liamdebeasi** [comment] 2020-06-15 12:59
Glad to hear the issue is resolved! I am going to close this issue.

**Closed by liamdebeasi** 2020-06-15 12:59 UTC
Labels: ionitron: needs reproduction
