### ISSUE TITLE
ion footer not showing in ios 10.3

### ISSUE THREAD

**Issue by royanon** [ionic-team/ionic#18771] opened 2019-07-12 06:28 UTC
**Ionic version:**
[x] **4.6.2**

**I'm submitting a ** 
[x] bug report
[ ] feature request

**Current behavior:**
ion footer not showing in ios 10.3, but it work on ios 11.0.x or above.
![image](https://user-images.githubusercontent.com/16112016/61106847-f0a42780-a4b0-11e9-8c76-f565937906ce.png)

**Expected behavior:**
ion footer should be shown
![image](https://user-images.githubusercontent.com/16112016/61106561-1da40a80-a4b0-11e9-878f-1ce60caa4cf3.png)

**Steps to reproduce:**
1. start a blank project
2. add ion footer

**Related code:**
<ion-footer></ion-footer>

**Ionic info:** 
   Ionic CLI                     : 5.2.2 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

**Comment by kelvindart-certua** [comment] 2019-07-17 07:49
Are you using [`cordova-plugin-ionic-webview`](https://github.com/ionic-team/cordova-plugin-ionic-webview) 4+? If so, there's a minimum requirement of iOS 11+ (I'm not sure what the Ionic framework's minimum requirements are however).

**Comment by maxtacco** [comment] 2019-07-27 16:15
Looks like a duplicate of https://github.com/ionic-team/ionic/issues/16328

**Comment by liamdebeasi** [comment] 2020-05-19 14:25
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

For anything regarding our supported platforms, please open a new issue.

**Closed by liamdebeasi** 2020-05-19 14:25 UTC
Labels: triage
