### ISSUE TITLE
Ionic Issued when Start a new project

### ISSUE THREAD

**Issue by alfredoizjr** [ionic-team/ionic#12173] opened 2017-06-27 13:37 UTC
Hi I have problem when I try to start a new project , Before I cut create a easy new project but not now.

this is ionic info

```
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

System:

    Node       : v8.1.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3

```
this is the error

```
C:\Users\Alfredo\Desktop>ionic start appstore sidemenu
? The directory appstore contains file(s) that could conflict. Would you like to overwrite the directory with this new
project? Yes
✔ Creating directory .\appstore - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template sidemenu (https://github.com/ionic-team/ionic2-starter-sidemenu/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm ERR! code 1
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
        npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
        npm ERR!

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Alfredo\AppData\Roaming\npm-cache\_logs\2017-06-27T13_24_41_639Z-debug.log

```
some one can help me I am not only one with this problem
https://forum.ionicframework.com/t/error-when-start-new-project/95878

**Comment by jgw96** [comment] 2017-06-27 14:45
Hello all! We are actively looking into this issue. I am setting up the oldest similar issue as a tracking issue and therefore and closing this issue as a duplicate of https://github.com/ionic-team/ionic/issues/12158. Thanks!

**Closed by jgw96** 2017-06-27 14:45 UTC

**Comment by jlahare** [comment] 2017-10-09 06:28
@jgw96 : Can you please confirm in which thread this issue is resolved ? its keep navigating to different issues ant resolution is not available !!!
