### ISSUE TITLE
bug: Ionic app no longer resizes on Chrome

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#19281] opened 2019-09-05 18:42 UTC
# Bug Report

**Ionic version:**

[x] **4.9.0**

**Current behavior:**

On Google Chrome my Ionic app no longer resizes when the window size changes.  It only does this when there is an element with position:fixed on the same page.  I have no idea why it all of the sudden started doing this.

**Expected behavior:**

The Ionic app should resize on Google Chrome.

**Steps to reproduce:**

Create an Ionic app and a button with these styles:
```
{
  position: fixed;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  margin: 0 0 16px 0;
  z-index: 1;
}
```
Now resize the browser window on Chrome v76.

**Related code:**

Change window size in stackblitz

https://stackblitz.com/edit/ionic-v4-app-not-resizing

![ionic-not-resizing](https://user-images.githubusercontent.com/25699262/64370521-9fb23a80-cfec-11e9-9139-8ba8cd318f52.gif)

**Other information:**

I am using Google Chrome Version 76.0.3809.132.  I tried reverting back to Ionic 4.7.4 and that had no affect.  Also it works in Safari.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.802.1
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.2.1
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment] 2019-09-05 19:27
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19281.

Please note that we believe this to be a bug in Chrome 76 and not a bug with Ionic. See the linked issue for more information as well as potential workarounds.

**Closed by liamdebeasi** 2019-09-05 19:27 UTC
Labels: triage

**Comment by kyleabens** [comment] 2019-09-05 19:31
I don’t think you linked the right issue since that one is mine.

**Comment by liamdebeasi** [comment] 2019-09-05 19:31
Sorry, I just updated the comment with the correct link 🙂 

Here is the correct one: https://github.com/ionic-team/ionic/issues/19065
