### ISSUE TITLE
big bug with nav on browser

### ISSUE THREAD

**Issue by yozman** [ionic-team/ionic#11871] opened 2017-05-31 06:41 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.3.0**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

-> page A 
-> nav.Push('B')
-> nav.Push('C')
-> browser back = now Page B
-> back on navbar = now Page C

**Expected behavior:**

-> page A 
-> nav.Push('B')
-> nav.Push('C')
-> browser back = now Page B
-> back on navbar = now should be Page A

**Steps to reproduce:**

check with Expected behavior

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.1
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

by the way I'm use with `locationStrategy: 'path'`
wish ur guys fix as soon as posible

**Comment by jgw96** [comment] 2017-05-31 14:55
Hello, thanks for using Ionic! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/11469

**Closed by jgw96** 2017-05-31 14:55 UTC

**Comment by yozman** [comment] 2017-05-31 15:54
@jgw96 
so when will u fix that?
it's important for us who make pwa with ionic
