### ISSUE TITLE
Run ionic 4 in android 4.4 and 5

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#16716] opened 2018-12-13 05:53 UTC
I developed a app with ionic 4 but problem for deploy and distribution.
because not run in android 4.4 and 5 correctly and show blank screen.
This problem is very important to me.
Does anyone know when this problem is resolved?

**Comment by amitairos** [comment] 2018-12-13 06:46
Duplicate of #https://github.com/ionic-team/ionic/issues/15438#issue-356264387

**Closed** 2018-12-13 07:20 UTC
Labels: triage
