### ISSUE TITLE
bug: Ionic 4 android 4.4 does not work

### ISSUE THREAD

**Issue by deniscesar** [ionic-team/ionic#18113] opened 2019-04-23 21:51 UTC
In the ionic documentation has support for Android 4.4+

But the reality is not quite what it seems … when trying to run a sidemenu app on an android 4.4.4 - 512mb the menu does not work.

I solved the menu by changing the core.

But when navigating between routes the click response time is very slow.

**Comment by ingljo** [comment] 2019-04-24 06:47
Did you comment in polyfills in polyfills.ts?
Also, there is an issue in Android < 7.0 where overriding css variables does not work:
https://github.com/ionic-team/ionic/issues/17781

You can also try to disable custom elements in zone.ts and see if that improves performance on click.
https://github.com/ionic-team/ionic/issues/18020

**Comment by deniscesar** [comment] 2019-04-24 21:39
When creating a start template sidemenu zone.js is already disabled custom elements.

The menu I resolved by changing the animator.ts file

`elements[i].style.setProperty('-webkit-transform', finalTransform);`


I'm studying switching to react... ionic 4 will not work well in android 4.4

**Comment by netsesame2** [comment] 2019-04-25 07:50
Not only android 4.4, android 5.1 is also not work in some device.

**Comment by liamdebeasi** [comment] 2019-04-25 13:59
Hi there,

Can you provide some more info? Are you trying to build an Ionic app with Angular? (or React?)

If you are building with Angular, please make sure you are on version 7.3 of the Angular CLI. As of that version, there are polyfills that are automatically generated that help with Android 4.4 and 5.1 support.

I can confirm that Ionic 4 does support Android 4.4 and Android 5.1 devices, but you will likely need some extra configuration as the webviews those versions use are outdated.

There is a known issue with the sidemenu not appearing on Android 4.4 here: https://github.com/ionic-team/ionic/issues/17729

Please let me know if having the polyfills included solves your issue. Thanks!

**Comment by liamdebeasi** [comment] 2019-04-25 16:01
Hi everyone,

Just wanted to provide a quick update: 

The side menu issue has been resolved via https://github.com/ionic-team/ionic/pull/18128. I have published a nightly build of Ionic if people are in need of the fix immediately (`npm i @ionic/angular@dev`).

Thanks!

**Comment by deniscesar** [comment] 2019-04-27 02:24
Hi @liamdebeasi 

The side menu worked in version dev.

But the navigation between routes is very slow.

**Comment by membering** [comment] 2019-04-27 11:39
ion-datetime also not working correctly on android 4.4
![a503482e-5418-11e6-9490-036c3dbd73e0](https://user-images.githubusercontent.com/13030926/56849201-cadc9d00-691b-11e9-833f-77703f0f0015.png)

**Comment by clembou590** [comment] 2019-04-27 17:14
@liamdebeasi 
I just tested on my phone (moto G) with android 4.4 and with "emulator: api 19, android 4.4" 
the side menu opens now correctly on both device THAT IS GREAT!

however it does not close when "tapping" on the side...
it also does not close when clicking on the "back button"...

**Comment by membering** [comment] 2019-04-28 15:29
somethings more,
- toast not working on android browser 4.4 and not correctly with direction top, bottom on real device
- item-sliding also not working with android 4.4

**Comment by paulstelzer** [comment] 2019-05-02 12:11
We had the discussion about Android 4.4 support long time ago :) The problem is that up to Android 4.4 the webview is connected hardly to OS. With Android 5.5 there is a Webview App that is updating via Google Play.

Ionic 4 uses a lot of new things (custom properties, ...) that has no good support in this old version of webview which is using Chromium behind.

You have to add a lot of polyfills to make it work, but it still will be slow. I would suggest to update the documentation that Android 5+ is needed to run an app.

**Comment by osben** [comment] 2019-09-09 10:19
Cool, but what about for example devices with chrome 44 even on android 6
For example, a real project, devices for example

`Mozilla/5.0 (Linux; Android 6.0; M5s Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 5.1; m3 note Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 6.0; U10 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.147 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 6.0; PRO 6s Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.146 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 6.0; MEIZU_M5 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.147 Mobile Safari/537.36`

and there are enough such devices (

I connected js polyfills, but there is no polyfills on css variables. (((

**Comment by neekey** [comment] 2020-01-28 07:37
OK I kept seeing people mention `polyfills.ts` but the demo project (`ionic-react-conference-app`) for `react` does not contain this file at all.

I am getting `undefined is not a function` error on my android 5 emulator, and I found out it's the `assign` function not definied, so def needs a polyfill for that. I wonder why this is not well documented.

**Comment by SSuarezBrooktec** [comment] 2020-02-13 12:48
same problem here, we have a lot of issues with Android 5.0.1 and Animations (toast, modals, select) they not show :(

**Comment by liamdebeasi** [comment] 2020-02-13 19:08
Thanks for the issue! We recently released Ionic Framework v5 which brings a lot of exciting new features to the framework. In keeping with how iOS and Android are evolving, we have decided to drop support for Android 4.4 and iOS 10 with this latest release.

Because all our efforts are now focused on Ionic 5, Ionic 4 will only receive security patches moving forward. As a result I am going to close this issue.

Please see https://ionicframework.com/docs/intro/browser-support  for an up to date list of supported browsers and platforms.

Additionally, please see https://ionicframework.com/blog/announcing-ionic-5/ for more info regarding Ionic Framework v5.

**Closed by liamdebeasi** 2020-02-13 19:08 UTC
Labels: triage
