### ISSUE TITLE
Date Picker layout is not correct

### ISSUE THREAD

**Issue by kumaresan-cgvak** [ionic-team/ionic#10190] opened 2017-01-26 17:32 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Date Picker allignment is not good in iPad Mini. Where the date overlaps with the line in picker.

**Expected behavior:**
Properly alligned, as like in iPhone.

**Steps to reproduce:**
Include Data Picker along with other inputs and open the date picker in iPad Mini 4 with iOS 10.2.1.

![img_0001](https://cloud.githubusercontent.com/assets/5547152/22342749/bb7e6076-e3f5-11e6-9680-26f4296a7d5f.PNG)

**Comment by kumaresan-cgvak** [comment] 2017-01-26 17:32
It is happening in the Final release as well

**Comment by jgw96** [comment] 2017-01-26 17:57
Hello, thanks for using Ionic! So when you say `along with other inputs` does that mean that this issue only happens when its opened over an input? Also, does this only happen on iOS?

**Comment by mhartington** [comment] 2017-01-26 23:16
Hmm, not able to reproduce with an ipad mini


![img_0016](https://cloud.githubusercontent.com/assets/2835826/22354391/27e9503e-e3f3-11e6-88cd-83d6cc671ec8.PNG)

**Comment by kumaresan-cgvak** [comment] 2017-01-27 08:23
@jgw96 Yes it happen only in iOS. In my case it is the last field along with 5 fields.

```
<ion-content padding>
  <h5 text-center padding>CUSTOMER SEARCH</h5>
  <ion-list>
    <ion-item>
      <ion-label stacked>CUSTOMER ID</ion-label>
      <ion-input type="number" [(ngModel)]="customerID"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label stacked>FIRST NAME</ion-label>
      <ion-input type="text" [(ngModel)]="firstName"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label stacked>LAST NAME</ion-label>
      <ion-input type="text" [(ngModel)]="lastName"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label stacked>EMAIL ID</ion-label>
      <ion-input type="email" [(ngModel)]="email"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label stacked>MOBILE NO</ion-label>
      <ion-input type="tel" [(ngModel)]="mobile"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label stacked>DATE OF BIRTH</ion-label>
      <ion-datetime displayFormat="YYYY-MMM-DD" pickerFormat="YYYY-MMM-DD" [(ngModel)]="dateOfBirth"></ion-datetime>
    </ion-item>
  </ion-list>
</ion-content>
```

**Comment by fspugna** [comment] 2017-10-18 14:48
Hi, any news about thiis issue? I'm facing the same problem on IOS.
Thanks!

**Comment by kensodemann** [comment] 2018-01-03 22:15
I am going to close this as something that I cannot duplicate. I just tried it with `3.9.2` on an iPhone 7.

If you can provide a sample application via GitHub I will be happy to reopen the issue and have a look. At this point, however, it is doubtful that there will be another v3 release so it would be best to wait until the next major release of Ionic and Ionic for Angular and to create a new issue (with sample repo) if this issue is still exhibited in that version.

**Closed by kensodemann** 2018-01-03 22:15 UTC
Labels: needs reply, platform:ios, v2
