### ISSUE TITLE
Android deffered long running task

### ISSUE THREAD

**Issue by Muneem** [ionic-team/ionic#13122] opened 2017-10-12 09:56 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

In android when i do scrolling. It stops my timer. Then when scrolling ends this timer is resumed. but its too slow. I am using observable.timer and i am calling function after 1 seconds. After scrolling there is a delay of 3 seconds. This is happening only in android. I want to do scrolling with out stopping my timer

**Expected behavior:**

This process should be smooth. Timer should be working when i am doing scrolling.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by kensodemann** [comment] 2017-10-12 10:56
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by kensodemann** [comment] 2017-10-12 10:59
Note that this is likely the same issue as #13080, in which case the only viable solution is to work around it in your code and in the design of your app as Android is simply going to do this if it needs to in an attempt to speed up scrolling (for example, if you are scrolling lots of images or other intensive actions like that on a slower and/or older device).

**Comment by Muneem** [comment] 2017-10-12 12:55
This is not that code issue. Chrome has upgraded its version and it has set low priority to settimer. This is not the case with IOS

**Comment by kensodemann** [comment] 2017-10-12 15:05
Do you have a sample application I can you for testing on a device?

**Comment by kensodemann** [comment] 2017-10-21 13:13
Closing due to lack of sample application we can use to troubleshoot. Also, this is very likely not an Ionic Framework issue but an issue related to performance on an older device and the strategies Chrome implements to deal with that. In that case, Ionic v4's performance improvements may offer some help depending on the cause of the performance issues.

**Closed by kensodemann** 2017-10-21 13:13 UTC
Labels: needs info

**Comment by danielsig** [comment] 2018-07-21 21:46
I'm having this problem too on android and chrome via ionic serve (not an issue in firefox). Not only are timers stopping but all javascript code stops running and not even scroll-end event is triggered until a few second later. The back button doesn't even work for a few seconds. I used the profiler to check out all the timers that are running during this observed lag and they take less than 0.7ms, that's 70 times below the threshold. The only thing that stands out as abnormal in the profiler is this huge ~1600ms idle frame with no activity. This has been the case since the very start of my ionic project (always used ionic v4).

Are you going to tell me that this is not an ionic issue? If not then it must be an issue with some technology that ionic uses.

I attached two profiles that you can open in chrome via dev-tools>Performance>Load Profile

[Profiles.zip](https://github.com/ionic-team/ionic/files/2216519/Profiles.zip)

**Comment by danielsig** [comment] 2018-07-21 22:09
I did two more profiles, 10sec each, comparing scrolling up and down on google.com vs my app via ionic serve. In both cases I created a simple timer using the console like so
`setInterval( () => console.log("hey"), 500)`
Almost everything looks the same except in the ionic app everything freezes (including the timer) during the inactive frames.
[scroll-ionic-vs-google.zip](https://github.com/ionic-team/ionic/files/2216533/scroll-ionic-vs-google.zip)
