### ISSUE TITLE
bug: ion-button size attribute overwrites round attribute

### ISSUE THREAD

**Issue by oleh-kolinko** [ionic-team/ionic#18108] opened 2019-04-23 15:40 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Not possible to combine attributes `shape` and `size`
`border-radius` is overwritten by `.button-small` / `.button-large` class

**Expected behavior:**
Able to have **small/large** and **rounded** buttons 

**Steps to reproduce:**
1. Create simple button
```html
<ion-button>Test</ion-button>
```

2. Add `shape` attribute
```html
 <ion-button shape='round'>Test</ion-button>
```
<img width="92" alt="Screen Shot 2019-04-23 at 11 33 38 AM" src="https://user-images.githubusercontent.com/25316409/56595040-e9f5ca80-65bb-11e9-8f00-d186f52ca080.png">

3. Add `size` attribute
```html
 <ion-button shape='round' size='small'>Test</ion-button>
```
<img width="53" alt="Screen Shot 2019-04-23 at 11 35 05 AM" src="https://user-images.githubusercontent.com/25316409/56595051-eeba7e80-65bb-11e9-982b-997bdbff45fd.png">

**Related code:**

```html
<!-- shape is round CORRECT -->
<ion-button shape='round'>Test</ion-button>

<!-- shape is not round INCORRECT -->
<ion-button shape='round' size='small'>Test</ion-button>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/oleh/.nvm/versions/node/v11.11.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic 5.3.0, (and 9 other plugins)

System:

   NodeJS : v11.11.0 (/Users/oleh/.nvm/versions/node/v11.11.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by brandyscarney** [comment] 2019-04-23 17:11
Thanks for the issue! I am able to reproduce this in `ios` mode but it seems to be working in `md` mode. Marking as a bug. 🙂

**Comment by abennouna** [comment] 2019-04-25 10:51
Working on it :)

**Closed** 2019-04-25 15:32 UTC
Labels: help wanted, package: core, type: bug
