### ISSUE TITLE
bug: Cant lock scrolling in ion-content

### ISSUE THREAD

**Issue by joshoconnor89** [ionic-team/ionic#19610] opened 2019-10-10 01:52 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Ion-content provides scrollX and scrollY but no option to lock the scrolling.  The user is able to scroll diagonally

**Expected behavior:**
In the past the user was able to add a `locking` property to true which locked the scrolling to x or y while it is scrolling.

**Comment by liamdebeasi** [comment] 2019-10-10 15:17
Thanks for the follow up. Ionic does not provide built in mechanisms for doing this. The current ways of preventing diagonal scrolling are typically pretty hacky, so we avoid recommending them to users.

I am going to close this issue as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2019-10-10 15:17 UTC
Labels: triage
