### ISSUE TITLE
bug: overlay clears input focus

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic#21387] opened 2020-05-27 14:39 UTC
# Bug Report

**Ionic version:**[x] **5.1.1**

**Current behavior:**

Setting the focus to an input control within a modal overlay does not retain the focus.

**Expected behavior:**

For a modal dialog running on a desktop browser it should be possible to set the focus to an input control.

**Related code:**

In `overlays.ts` the present method uses the following code:

```tsx
  if (overlay.keyboardClose) {
    overlay.el.focus();
  }
```

If an input has focus, this will cause the input to blur and the overlay to get the focus.

Changing the `keyboardClose` option to false will prevent this behavior but this does not seem like the expected impact of this option (especially since it defaults to true).

**Comment by liamdebeasi** [comment] 2020-05-27 15:07
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. Focusing the modal is a change we made to better improve the accessibility of overlay components.

Prior to this change, you could present an overlay by clicking a button; however, the focus on that button was retained, so hitting "Enter" would present more overlays.

In addition, users that relied on screen readers had a difficult time using the modal since the modal was not focused. As a result, users could not easily tab into different inputs/buttons in the modal.

You are right, the `keyboardClose` option is probably not the best name for this. It was an old option that we repurposed since we could not change the name without causing a breaking change. I will look into adding docs to clarify this, and we will look into choosing a better name for this API in the next major release. Thanks!

**Closed by liamdebeasi** 2020-05-27 15:07 UTC
Labels: triage

**Comment by cjorasch** [comment] 2020-05-27 16:27
Another idea for the docs is the fairly common case of wanting to set focus to an input control (at least on the desktop).  I had to walk through the Ionic source code to track down this recent behavior since it is very difficult to find the code source for blur events.  I think the accessibility issue still exists for desktop forms so I am still not completely sure how to handle this the right way.

A possible way to handle the accessibility issue is to check if `document.activeElement` is inside the modal and skip setting focus in that case (since the focus is already in the modal).
