### ISSUE TITLE
The height of VirtualScroll may not be updated

### ISSUE THREAD

**Issue by pikotea** [ionic-team/ionic#11928] opened 2017-06-05 16:13 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my application, I use VirtualScroll and infiniteScroll.
Occasionally the height of VirtualScroll will not be updated and the following record may be hidden.

**Related code:**

https://github.com/ionic-team/ionic/blob/master/src/components/virtual-scroll/virtual-util.ts#L533

In the current code, the height of VirtualScroll is mother number of denominator. Then, as the height becomes very high, the response to the update of the height becomes bad.

The situation in my application is as follows.

- lastCell.record: 135
- totalRecords: 143
- percentToBottom: 0.9507042253521126

`percentToBottom > .995` => false

- newHeight: 33356
- diff: 4408
- difference: 0.25 (fixed value)

`diff > (newHeight * difference)` => false

Despite the addition of 4408px in height, the height of VirtualScroll did not change.

**Comment by jgw96** [comment] 2017-06-05 16:22
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/9765

**Closed by jgw96** 2017-06-05 16:22 UTC

**Comment by pikotea** [comment] 2017-06-05 19:39
@jgw96 Thanks for your response. But, this issue is different #9765. This problem is occurring in ionic 3.3. Please confirm again.

I am sorry that English is not good and it is difficult to understand. ;-)
