### ISSUE TITLE
ERROR Error: Uncaught (in promise): nav controller was destroyed

### ISSUE THREAD

**Issue by giscafer** [ionic-team/ionic#12401] opened 2017-07-18 15:51 UTC
**Ionic version:**  (check one with "x")

 **3.5.3**

**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior:**
ngIf show different tabs，**at the first time**，occurs the error`nav controller was destroyed`;

**Expected behavior:**
no error，change page normal

**Steps to reproduce:**

tabs page default property:` segment: string="newTask";`
click  one button to navigate to the tabs page pass params segment='repaire';

debug `NavControllerBase.prototype._failed ` function

**Related code:**

```html
<super-tabs id="newTaskTabs" #SuperTabs *ngIf="segment === 'newTask'" [style.display]="segment === 'newTask'?'block':'none'" [config]="{ sideMenu: 'left' }" scrollTabs toolbarColor="orange"
        toolbarBackground="white" indicatorColor="orange" badgeColor="yellow" (tabSelect)="onTabSelect($event)">
        <super-tab [swipeBackEnabled]="false" [root]="waitAcceptPage" title="待受理({{newTaskCountObj.distributionWaitAccept}})" status="waitAcceptPage"></super-tab>
        <super-tab [root]="waitAppointmentPage" title="待预约({{newTaskCountObj.waitAppointment}})" status="waitAppointmentPage"></super-tab>
        <super-tab [root]="waitPickupPage" title="待提货({{newTaskCountObj.waitPickUp}})" status="waitPickupPage"></super-tab>
        <super-tab [root]="waitSignPage" title="待签收({{newTaskCountObj.waitSign}})" status="waitSignPage"></super-tab>
        <super-tab [root]="hadSignPage" title="已签收({{newTaskCountObj.doSign}})" status="hadSignPage"></super-tab>
        <super-tab [root]="cancelledPage" title="已取消({{newTaskCountObj.invalid}})" status="cancelledPage"></super-tab>
        <super-tab [root]="allTaskPage" title="全部({{newTaskCountObj.all}})" status="allTaskPage"></super-tab>
    </super-tabs>
    <!--维修任务-->
    <super-tabs id="repaireTabs" #SuperTabs toolbarColor="orange" toolbarBackground="white" indicatorColor="orange" badgeColor="yellow"
        (tabSelect)="onTabSelect($event)" *ngIf="segment === 'repaire'">
        <super-tab [swipeBackEnabled]="false" [root]="repaireWaitAcceptPage" title="待受理({{repaireCountObj.waitAccept}})" id="repaireWaitAcceptPage"></super-tab>
        <super-tab [root]="repaireWaitAppointmentPage" title="待预约({{repaireCountObj.waitAppointment}})" id="repaireWaitAppointmentPage"></super-tab>
        <super-tab [root]="repaireWaitSignPage" title="待签收({{repaireCountObj.waitSign}})" badge="" id="repaireWaitSignPage"></super-tab>
        <super-tab [root]="repaireHadSignPage" title="已签收({{repaireCountObj.sign}})" id="repaireHadSignPage"></super-tab>
        <super-tab [root]="repaireAllTaskPage" title="全部({{repaireCountObj.all}})" id="repaireAllTaskPage"></super-tab>
    </super-tabs>

```

 `this._queue` is pointer to the destroy page 'newTask'，then fire errors

```ts
    /**
     * @param {?} rejectReason
     * @param {?} ti
     * @return {?}
     */
    NavControllerBase.prototype._failed = function (rejectReason, ti) {
// this is pointer to the destroy page 'newTask'，then fire errors
        if (this._queue === null) {
            this._fireError('nav controller was destroyed', ti);
            return;
        }
        this._trnsId = null;
        this._queue.length = 0;
        // let's see if there's another to kick off
        this.setTransitioning(false);
        this._swipeBackCheck();
        this._nextTrns();
        this._fireError(rejectReason, ti);
    };
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.0.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.0

```

**it's work fine in the old version.**

**Comment by jgw96** [comment] 2017-07-19 19:25
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic/issues/11454.

**Closed by jgw96** 2017-07-19 19:25 UTC

**Comment by raminfosys** [comment] 2017-11-23 04:41
core.js:1350 ERROR Error: Uncaught (in promise): invalid views to insert
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4629)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
defaultErrorLogger @ core.js:1350

**Comment by raminfosys** [comment] 2017-11-23 04:42
core.js:1350 ERROR Error: Uncaught (in promise): invalid views to insert
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4629)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
defaultErrorLogger @ core.js:1350

**Comment by raminfosys** [comment] 2017-11-23 04:44
core.js:1350 ERROR Error: Uncaught (in promise): invalid views to insert
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:223)
    at NavControllerBase._failed (nav-controller-base.js:216)
    at nav-controller-base.js:263
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4629)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
defaultErrorLogger @ core.js:1350
