### ISSUE TITLE
[4.0.0-beta.16] Android hardware back button & cancelling camera usage

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16505] opened 2018-11-29 12:40 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.4.0 (/Users/os/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/os/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.13.0 (/usr/local/Cellar/node@10/10.13.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

**Describe the Bug**
Exiting the device's camera feature (made available via cordova plugin) via the hardware back button, **results in both** closing the camera & popping the nav history stack.
However, the **router should disregard the back button** in case of camera exit.

**Steps to Reproduce**
1. build basic app with camera feature (eg bar code reader)
2. call camera from 2nd page (nav stack should have an entry!)
3. cancel out of camera by pressing hardware back button
4. notice that router also navigated to previous page (1st page)

**Expected Behavior**
Cancelling the camera on Android should not interfere with app nav/routing.

**Additional Context**
Suggestion: Perhaps add a nav/router option to temporarily suppress 'can-go-back' via hardward button.

**Comment by bryce13950** [comment] 2018-11-29 12:46
Do you have project files that you could attach, so it's easier to recreate?

**Comment by olivermuc** [comment] 2018-11-29 12:51
I'm in-midst of a larger project, unfortunately due to NDA I can't post any code.
But the above is generic, ie. I would expect this behavior in any ionic Android app that deals with camera usage. Btw this was already an issue with v3 for which I created a workaround by hijacking the back-button handling.
This however is not possible anymore due to the nature of back-button event subscription (vs exclusively 'owning' the handling).

This is the culprit imho:

https://github.com/ionic-team/ionic/blob/e8e71838b34be3bcbb63a944ec12ce1f6e14e07e/angular/src/providers/nav-controller.ts#L33

**Comment by bryce13950** [comment] 2018-11-29 13:00
Well if you could take your app, and remove everything but the bare bones then it would probably go a long way in getting this solved quicker. You have provided very good steps on how to recreate the bug, but someone is still going to have to spend time recreating the bug. If you do have the ability to provide a small project with the flow already implemented then that would be greatly appreciated.

**Comment by olivermuc** [comment] 2018-11-29 22:03
https://github.com/olivermuc/android-hw-back-button-test

Here you go. Plain vanilla template app + bar code scanner plugin.
Tested it locally and it behaves the same way.

**Comment by olivermuc** [comment] 2018-11-30 08:31
Just food for thought: What if we protected the `goBack()` call by a controller variable:

```
goBack(animated?: boolean) {
  if (this.disableAndroidBackButton) {
    this.setDirection('back', animated);
    return this.location.back();
  } else {
    return null;
  }
}
```

**Comment by bryce13950** [comment] 2018-11-30 13:46
Thanks for the suggestion we will definitely think about it. It seems like it could be a good solution, but we are going to mull it over, and get back to you.

**Comment by olivermuc** [comment] 2018-12-21 12:33
@bryce13950 any updates? It's been 22 days and even a temporary workaround such as manually disabling the `platform.backButton.subscribeWithPriority(..)`routine would help.
Otherwise camera usage is significantly impacted. Thx.

**Comment by elylucas** [comment] 2019-02-13 22:48
Hi @bryce13950, I am investigating this issue and am not able to reproduce it on the latest Ionic (4.0.1) and Ionic Native (5.0). Clicking the back button on Android while the camera plugin is open leaves me at the page I expect when it closes the native view. Would you mind checking again on the latest and let us know? Or if I'm missing something here?

Thanks

**Comment by bryce13950** [comment] 2019-02-14 16:40
@elylucas If you have tested this on the example project that @olivermuc created, and it is working properly, then it is probably working fine now.

**Comment by liamdebeasi** [comment] 2019-04-25 15:41
Hi there,

I have tested the example project on Ionic 4.3.0, and tapping the back button leaves the camera view and brings me back to the page I was on before.

I am going to close this issue as it looks like the problem has been resolved. If you are running into any new back button issues, feel free to open a new bug report.

Thanks!

**Closed by liamdebeasi** 2019-04-25 15:41 UTC
Labels: needs: design decision, package: angular, type: bug
