### ISSUE TITLE
ion-radio show the checkmark before popup is loaded.

### ISSUE THREAD

**Issue by shivalipawar** [ionic-team/ionic#13280] opened 2017-10-30 06:25 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
Ionic 2.2.1

I'm submitting a feature request

**Current behavior:**
When on a click the popup having radio button opens up there's a delay between popup shown and checkmark shown.

**Expected behavior:**
On click first pop up should come then only check mark of selected radio item should be shown.

**Steps to reproduce:**
Create a button and on it's click opens up ionic-popup having io-radio.
When we click on the button, with some delay the checkmark of selected radio button is shown first then the popup is shown up.

**Related code:**

https://codepen.io/addi90/pen/aNroNN?editors=1010
```

**Comment by kensodemann** [comment] 2017-10-30 10:49
Hello! Thank you for opening an issue with us!

I am somewhat confused by your issue:

1. You have this marked as a feature request but it reads more like a bug. If you are requesting a specific feature, I do not see what it is.
2. Your code sample seems to work just fine. I click to open the popup and the popup animates in smoothly. If any one thing draws before any other one thing, it is not perceptible in real time
3. You have the version listed as Ionic `2.2.1`. Have you been able to duplicate this with `3.8.0`? 

Are you perhaps throttling performance in order to see this?

Also, can you please provide the output of your `ionic info` command as per the issue template?

Thank you for using Ionic

**Comment by shivalipawar** [comment] 2017-11-06 10:31
Hello @kensodemann ,
I wasn't sure whether it should be under bug request or feature request. So raised it under feature request.
We have our project using 2.2.1 so we haven't tried using ionic 3.8.0. Yes it feels like performance issue for particular device i guess.

**Comment by kensodemann** [comment] 2017-11-06 11:55
Given what you are describing, I would call it a "Bug" rather than a feature request.

Trying your CodePen on Edge in Windows, I barely see the check-mark render slightly before the rest of the screen animates in, but I only actually notice it if I am looking for it. Otherwise, it just looks like a popover that is animating in. Perhaps this effect is more pronounced on slower hardware. I have an older Android device I can try it on later.

In the future (probably some time after the initial Ionic v4 release), we are going to be doing a review of our styles, animations, etc. I have marked this as something to include in that review.

**Comment by shivalipawar** [comment] 2017-11-14 04:31
I have tried this on Samsung J7 with android 6.0 or older one. You might be able to reproduce it on those devices.

**Comment by mkoczka** [comment] 2017-12-11 23:05
I can reproduce this bug on OSX, Chrome Version 62.0.3202.94 (Official Build) (64-bit) in the example above, but the example is written in Ionic 1. 

You have listed ionic version 2.2.1 which seems doesn't even exist. Can you please double check your ionic version? And also run `ionic info` and provide the output.

**Closed** 2019-01-11 19:05 UTC
Labels: needs: design decision
