### ISSUE TITLE
bug: ion-grid no-padding removes paddings from ion-col

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic#20338] opened 2020-01-30 10:14 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

Applying `ion-no-padding` to `ion-grid` removes padding to children `ion-col`

**Expected behavior:**

components should have independent padding/margin , or at least a trigger/class for inheritance

**Steps to reproduce:**

**Related code:**

`<ion-grid class="ion-no-padding"></ion-grid>` 

**Other information:**

![Screenshot 2020-01-30 at 12 12 01](https://user-images.githubusercontent.com/12111716/73440424-eb79cd80-4359-11ea-8118-60319ace7cd1.png)

![Screenshot 2020-01-30 at 12 12 49](https://user-images.githubusercontent.com/12111716/73440434-efa5eb00-4359-11ea-8c88-3f38c622d09e.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.0-rc.1
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 8.3.23
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.13.6
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment] 2020-01-30 15:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

As per the docs (https://ionicframework.com/docs/layout/grid), it says that "padding can be removed from the grid and columns by adding the ion-no-padding class to the grid."

There was a bug where this was not happening previously (https://github.com/ionic-team/ionic/issues/17459) and we merged a PR to fix this issue (https://github.com/ionic-team/ionic/pull/19592).

**Closed by liamdebeasi** 2020-01-30 15:01 UTC
Labels: triage
