### ISSUE TITLE
feat: Allow more granular positions for ion-toast.

### ISSUE THREAD

**Issue by cesaresantiago** [ionic-team/ionic#21649] opened 2020-06-29 14:28 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The Ion-toast component allows only for three positions: top, bottom, middle. For some applications this can be bothersome, as the toaster can end up in the middle of populated sections of the app. Pre Ionic 4, we were able to get by this by defining custom CSS for ion-toast, making it appear on an area we would know was safe (say, just right over the tabs).

**Describe Preferred Solution**

It'd be useful to add more flexibility on the "position" attribute as to where the toaster should appear, (say, a given distance from the bottom). Alternatively, a Shadow Part that allowed us to modify the position would be acceptable as well.

**Describe Alternatives**

Before, it was possible to get by this with custom css for the component, but this is no longer possible with the use of Shadow Dom for the Ionic components after Ionic 4.

**Related Code**

Before, we could directly modify the bottom attribute.

ion-toast.toast-wrapper.toast-bottom {
    bottom: 5.5rem;
}
Now this is not possible. An attribute that let us do something similar as part of the exposed CSS of the toaster would work.

**Additional Context**

**Comment by liamdebeasi** [comment] 2020-06-29 20:49
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17499.

**Closed by liamdebeasi** 2020-06-29 20:49 UTC
Labels: triage
