### ISSUE TITLE
bug: swipable modals status bar color

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic#21418] opened 2020-06-02 08:04 UTC
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
The background of the statusbar (iOS) does not change when opening swipable modals

**Expected behavior:**
The background of the statusbar should be black.

**Steps to reproduce:**
Open a swipable modal on an iOS device.

**Other information:**
Here is an image:
![IMG_2533](https://user-images.githubusercontent.com/36629890/83495802-78739580-a4b8-11ea-9756-8e27d508b6d3.PNG)

**Comment by liamdebeasi** [comment] 2020-06-02 12:53
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20501.

**Closed by liamdebeasi** 2020-06-02 12:53 UTC
Labels: triage

**Comment by BerkeAras** [comment] 2020-06-02 14:17
Oh, im sorry. Thanks for helping!
