### ISSUE TITLE
bug: ion-select doesn't work inside a ion-item tag

### ISSUE THREAD

**Issue by JoseChirivella14** [ionic-team/ionic#20179] opened 2020-01-09 18:41 UTC
# Bug Report

**Current behavior:**
Implementing a `ion-select` inside a `ion-item` tag, but upon clicking, nothing happens.
If I remove the `ion-item` tag, the `ion-select` works as expected.

It's confusing because the [Docs](https://ionicframework.com/docs/api/select) shows that you  can use a `ion-select` under a `ion-item` tag.

**Expected behavior:**
I would expect the `ion-select` to work inside a `ion-item` tag according to the docs.

**Related code:**

Works:
```html
<!-- <ion-item> -->
      <ion-label>Gender</ion-label>
      <ion-select placeholder="Select One">
        <ion-select-option value="f">Female</ion-select-option>
        <ion-select-option value="m">Male</ion-select-option>
      </ion-select>
    <!-- </ion-item> -->

    <!-- <ion-item> -->
      <ion-label>Hair Color</ion-label>
      <ion-select value="brown" okText="Okay" cancelText="Dismiss">
        <ion-select-option value="brown">Brown</ion-select-option>
        <ion-select-option value="blonde">Blonde</ion-select-option>
        <ion-select-option value="black">Black</ion-select-option>
        <ion-select-option value="red">Red</ion-select-option>
      </ion-select>
    <!-- </ion-item> -->
```

Doesn't work:
```html
<ion-item>
      <ion-label>Gender</ion-label>
      <ion-select placeholder="Select One">
        <ion-select-option value="f">Female</ion-select-option>
        <ion-select-option value="m">Male</ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item>
      <ion-label>Hair Color</ion-label>
      <ion-select value="brown" okText="Okay" cancelText="Dismiss">
        <ion-select-option value="brown">Brown</ion-select-option>
        <ion-select-option value="blonde">Blonde</ion-select-option>
        <ion-select-option value="black">Black</ion-select-option>
        <ion-select-option value="red">Red</ion-select-option>
      </ion-select>
    </ion-item>
```
**Other information:**

**Ionic info:**
```bash
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v12.13.0
   npm    : 6.13.4
   OS     : macOS Mojave
```

**Comment by liamdebeasi** [comment] 2020-01-09 20:28
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by JoseChirivella14** [comment] 2020-01-10 14:40
@liamdebeasi So, I did some digging and found out that it's an issue with Firefox Developer Edition v73.0b2 (64-bit). With Chrome works fine.

**Comment by liamdebeasi** [comment] 2020-01-10 14:43
Can you try on `v73.0b3`? I just tried it on my end, and it works fine.

**Comment by JoseChirivella14** [comment] 2020-01-10 14:45
@liamdebeasi ok, updated and found out that it doesn't work on my end if "touch simulation" is activated in the dev tools.
I'm emulating Pixel 2 XL

**Comment by liamdebeasi** [comment] 2020-01-10 16:19
Thanks for the follow up. I created a reproduction of the same issue without using any Ionic components: https://codepen.io/liamdebeasi/pen/zYxjvdw

It looks like it has something to do with particular CSS being applied to interactive elements in the Shadow DOM. I am going to close this as this does not appear to be a bug in Ionic Framework; however, we will look into reporting this issue to the Firefox team. Thanks!

**Closed by liamdebeasi** 2020-01-10 16:19 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2020-05-28 15:35
Hey there, I filed a bug with the Firefox team: https://bugzilla.mozilla.org/show_bug.cgi?id=1640189. Looks like this has been fixed in Firefox 78, so a fix should be available whenever that ships.
