### ISSUE TITLE
ion-item-sliding: options of the opposite direction of sliding is shown too

### ISSUE THREAD

**Issue by SherifMoShalaby** [ionic-team/ionic#17822] opened 2019-03-19 11:56 UTC
# Bug Report

**Ionic version:**

[x] **4.0.2**

**Current behavior:**

adding an ion-item-sliding to an ion-item with ion-item-options both sides, when sliding the item from left to right (or vise versa) to the end of the item, the right icons shown up while it should not.
so now both options from both sides will be shown in any swiping direction

**Expected behavior:**

when swiping from left to right or vise versa, only icons from the side i`m sliding should be shown

**Steps to reproduce:**

1. create new project with version 4.0.2.

2. in app.component.html add the sample example found in ionic documentation regards ion-item-sliding 

3. swipe from left to right or vise versa, issue will be generated.

**Other information:**

the issue was not presented in version 4 beta 7

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\sshalaby\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.2
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-03-20 14:00
Hi there,

Thanks for the issue. Is this the behavior you are describing?

![zf3gqstXst](https://user-images.githubusercontent.com/2721089/54690061-01daba00-4af7-11e9-8d4b-2875e3d783bf.gif)

**Comment by SherifMoShalaby** [comment] 2019-03-20 14:18
> Hi there,
> 
> Thanks for the issue. Is this the behavior you are describing?
> 
> ![zf3gqstXst](https://user-images.githubusercontent.com/2721089/54690061-01daba00-4af7-11e9-8d4b-2875e3d783bf.gif)

Yes.

**Comment by brandyscarney** [comment] 2019-04-02 15:18
The issue is most likely somewhere in this:

```
.item-sliding-active-slide {
  @include rtl() {
    &.item-sliding-active-options-start ion-item-options:not(.item-options-end) {
      width: 100%;

      visibility: visible;
    }
  }

  ion-item-options {
    display: flex;
  }

  &.item-sliding-active-options-start .item-options-start,
  &.item-sliding-active-options-end ion-item-options:not(.item-options-start) {
    width: 100%;

    visibility: visible;
  }
}
```

https://github.com/ionic-team/ionic/blob/master/core/src/components/item-options/item-options.scss#L69-L88

**Comment by masimplo** [comment] 2019-04-06 21:27
The issue is that the opposite item-options are not hidden so both are displayed. I just opened PR  #17986 that remedies that by hiding the opposite sides item-options

```
  &.item-sliding-active-options-end .item-options-start,
  &.item-sliding-active-options-start .item-options-end {
    display: none;
  }
```

**Comment by brandyscarney** [comment] 2019-04-16 19:35
Merged in and fixed by https://github.com/ionic-team/ionic/commit/f13722cc206ce7f9661647c710fdc21e7c96eb72. This will be in the `4.3.0` release, thank you!

**Closed by brandyscarney** 2019-04-16 19:35 UTC
Labels: help wanted, package: core, type: bug
