### ISSUE TITLE
bug: ion-searchbar incorrectly applying --keyboard-offset to ion-content

### ISSUE THREAD

**Issue by leszekkadlof** [ionic-team/ionic#18375] opened 2019-05-24 01:01 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The ion-content is incorrectly being resized for the hardware keyboard leading to blank area above the keyboard when an ion-searchbar is in focus. However, focusing on an ion-input is fine and the resizing is correct.  

It appears the --keyboard-offset being applied twice.

Below are screenshots - red area is just a div inside the ion-content. You will note the Input field correctly adjusts the content while the searchbar adds more offset.

Initial State:
![Initial State](https://user-images.githubusercontent.com/32826006/58295029-6aecef80-7e10-11e9-8df6-e635cfe8503a.png)

Search bar in focus:
![Search Bar in focus](https://user-images.githubusercontent.com/32826006/58295045-7dffbf80-7e10-11e9-90e1-c078da885c8a.png)

Input in focus:
![Input in focus](https://user-images.githubusercontent.com/32826006/58295057-8d7f0880-7e10-11e9-81c5-3074761d6156.png)

It seems ion-searchbar applies a "--keyboard-offset" to the style attribute of the ion-content which may be causing the issue while ion-input does not . These tests and experience were done on an iOS iPhone XR 12.2 emulator and iPhone device.

--keyboard-offset style being applied to ion-content by ion-searchbar (If I clear this value then the ion-content is correctly sized):
![searchbar-keyboard-offset](https://user-images.githubusercontent.com/32826006/58295724-fddb5900-7e13-11e9-9568-d4ff1bb2acc4.png)

--keyboard-offset style being not applied to ion-content by ion-input field:
![input-keyboard-offset](https://user-images.githubusercontent.com/32826006/58295741-0e8bcf00-7e14-11e9-88ce-a3698527d86f.png)

**Expected behavior:**

The ion-content ought to resize the same for ion-searchbar as it does for ion-input

**Steps to reproduce:**

1. Run the test app with either iOS emulator or on an iPhone device (be sure to enable hardware keyboard display on emulator)
2. Click on the 'Search Bar' text field, then
3. Click on the 'Input' text field

You will note in the case of the searchbar the content area is not being adjusted to sit just above the keyboard.

**Related code:**

Create the test yourself: 
Create a new ionic 4 'blank' project and replace 'home.page.html' with:
```
<ion-content padding>
  <div style="height: 100%; background: red; padding-top: 20px">
    <ion-label>Search Bar</ion-label>
    <ion-searchbar ></ion-searchbar>
    <ion-label>Input</ion-label>
    <ion-input type="text" style="border: 2px solid black; border-radius: 5px;"></ion-input>
  </div>
</ion-content>
```
Also, test available on github: [GitHub ion-searchbar-keyboard-offset](https://github.com/leszekkadlof/ion-searchbar-keyboard-offset)

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.14.2 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

```
This issue occurs both on a vanilla ionic project and one with all latest npm updates.

**Comment by liamdebeasi** [comment] 2019-05-24 12:48
Hi there,

Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18007 (note: this issue references fixed content, but `ion-searchbar` should not receive the keyboard offset in neither scrolling nor fixed contexts).

Thanks!

**Closed by liamdebeasi** 2019-05-24 12:48 UTC
Labels: triage
