### ISSUE TITLE
bug: Animation between tabs doesn't work

### ISSUE THREAD

**Issue by Zanluca** [ionic-team/ionic#20214] opened 2020-01-15 16:50 UTC
# Bug Report

**Ionic version:**

[x] **4.11.8**

**Current behavior:**

When I change tab there is no transition animation. This issue ([https://github.com/ionic-team/starters/pull/905](https://github.com/ionic-team/starters/pull/905)) says the component `ViewManager` is under the Tabs, but doesn't exist animation.

**Expected behavior:**

Animation between tabs

**Steps to reproduce:**

Create a project with the Ionic CLI and select option tabs. So test change tab and see no animation

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.4 (C:\Users\gabri\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 4.11.8

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by elylucas** [comment] 2020-01-15 18:22
Hi @Zanluca,

When moving between tabs, there is no animations by default or in the starters.

Going to close this as its not a bug.

Thanks

**Closed by elylucas** 2020-01-15 18:22 UTC
Labels: triage

**Comment by iamgbayer** [comment] 2020-01-15 18:43
Hi @elylucas, I work with @Zanluca.

Can you tell us a way to animate tabs transitions with React Ionic? Some doc reference.

**Comment by elylucas** [comment] 2020-01-15 19:05
@iamgbayer we don't have any docs or guidance on it at the moment, but do stay tuned as we have a lot of great animation functionality coming soon in v5 and will talk about it more.
