### ISSUE TITLE
bug: IONIC 4 source map files out of sync

### ISSUE THREAD

**Issue by informatikTirol** [ionic-team/ionic#18280] opened 2019-05-15 04:00 UTC
**Ionic version:**
[x] **4.4**

**Current behavior:**
Debugging with Webstorm: debugger stops at wrong line or does not stop at all. 
IONIC 3 is no problem, so i think it is an Ionic 4 source map files problem. 

**Ionic info:**
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/aj/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 8.0.1
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by liamdebeasi** [comment] 2019-05-15 12:37
Hi there,

Thanks for the issue. Can you provide a repository where this is happening? 

Thanks!

**Comment by informatikTirol** [comment] 2019-05-16 05:02
HI @liamdebeasi,
unfortunately no, I have a non-disclosure agreement on this project. 
But to reproduce you just have to start a new project and start debugging. 
Then add a few lines of code. After that the debugger in Webstorm is out of sync.

Thanks!

**Comment by liamdebeasi** [comment] 2019-05-16 13:20
Hi there,

I do not need your project's code, but rather a sample repo with code the shows this happening. Without a code example, I am unable to reproduce this issue.

Thanks!

**Comment by informatikTirol** [comment] 2019-05-17 04:58
Hi, 

here is a dummy project with this supposed bug: https://www.dropbox.com/s/4rokw2vue9d7iq8/18280.zip?dl=0

I dded an AuthGuard, copy and paste some code lines, after a while the debugger from Webstorm got out of sync, see attached image.... The chrome debugger is still in sync, the real line number for "return false" is 49. If i set the breakpoint in Webstorm on line 61, it does not get hit. 

Thanks

![fxNQ](https://user-images.githubusercontent.com/16346085/57903981-22ae5a00-7871-11e9-8a84-e105518a480e.jpg)

**Comment by liamdebeasi** [comment] 2019-05-17 13:11
Hi there,

Thanks for the follow up. If Chrome is parsing the source maps correctly and hitting breakpoints where it should this probably is not an Ionic issue. There seem to be a few posts on the JetBrains website and StackOverflow for similar issues after looking this issue up on Google.

For further help with this feel free to post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com).

I am going to close this as this is not an Ionic issue. Thanks!

**Closed by liamdebeasi** 2019-05-17 13:11 UTC
Labels: triage

**Comment by informatikTirol** [comment] 2019-05-18 04:45
HI, 
my description was wrong. The real line number is 61, so Google chrome hits the wrong line, the source maps did not get updated correctly. 

Thanks
