### ISSUE TITLE
bug: (picker) text-overlapping each other

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic#19880] opened 2019-11-10 13:46 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

text overlapping each other if you click inside anywhere in picker then it will be okay

![image](https://user-images.githubusercontent.com/23274631/68544971-93809a00-03ee-11ea-8917-0347ea464fb1.png)

**Expected behavior:**

By default it should be scrollable

**Steps to reproduce:**

1. Open picker again and again.

**Related code:**

Html : 
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.html
Ts : 
https://github.com/indraraj26/ionic4-starter-tabs-sidemenu/blob/picker/src/app/home/home.page.ts
```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
D:\ionicv4-github\ionic4-tabs-sidemenu>ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


D:\ionicv4-github\ionic4-tabs-sidemenu>
```

**Comment by liamdebeasi** [comment] 2019-11-11 16:02
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17664.

**Closed by liamdebeasi** 2019-11-11 16:02 UTC
Labels: triage
