### ISSUE TITLE
Content losing margin-top after coming back from a view where the keyboard was opened.

### ISSUE THREAD

**Issue by rfoel** [ionic-team/ionic#13183] opened 2017-10-18 19:41 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Updated the angular and ionic packages to the latest version and whenever I use the keyboard on Android and go back to he previous view using the phone back button, the `fixed-content` and `scroll-content` divs loses the `margin-top` attribute, making the content shifts below the header. 

**Expected behavior:**
Keep the `margin-top` with the `height` of the `ion-header`.

**Steps to reproduce:**
Create a new Ionic app, add a `ion-textarea` or `ion-input` to a view that you'll push to, type whatever or nothing at all (just let the keyboard slides in) and use the phone back button, not the app back button (this is important to reproduce the bug).

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/home/rafael/.nvm/versions/node/v8.7.0/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v8.7.0
    npm               : 4.6.1 
    OS                : Linux 4.10

Misc:

    backend : pro
```

![image](https://user-images.githubusercontent.com/19496473/31739080-7d78ec36-b42b-11e7-81de-b6363bc7daa9.png)

**Comment by kensodemann** [comment] 2017-10-18 19:55
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13028. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

**Closed by kensodemann** 2017-10-18 19:55 UTC
