### ISSUE TITLE
floating label does not float on template-driven forms data change

### ISSUE THREAD

**Issue by pickfire** [ionic-team/ionic#14396] opened 2018-04-27 01:38 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

After the `ngModal` data is changed, the floating label does not float, then both label and input are on the same line.

**Expected behavior:**

After the `ngModal` data is changed, the floating label should float, IIRC v3 and material angular works.

**Steps to reproduce:**

See below sample code.

**Related code:**

```html
<ion-content>
  <form>
    <ion-label>
      <ion-item position="floating">Question</ion-item>
      <ion-input [(ngModel)]="data.answer"></ion-input>
    </ion-label>
  </form>
</ion-content>
```

```typescript
import { Component } from '@angular/core';

import { Service } from '../../../providers';

@Component({
  selector: 'page-form',
  templateUrl: 'page-form.html'
})
export class FormPage {

  data = {};

  constructor(private service: Service) { }

  ionViewDidEnter() {
    this.service.get().subscribe(data => this.data = data);
  }

}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/share/.config/yarn/global/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.5
   ionic (Ionic CLI) : 4.0.0-rc.5

local packages:

   @angular-devkit/core       : 0.5.7
   @angular-devkit/schematics : 0.5.7
   @angular/cli               : 6.0.0-rc.5
   @ionic/schematics-angular  : 1.0.0-rc.5
   Ionic Framework            : @ionic/angular 4.0.0-alpha.2

System:

   NodeJS : v9.11.1
   npm    : 5.8.0
   OS     : Linux 4.16

```

**Comment by brandyscarney** [comment] 2018-10-26 20:35
I am not able to reproduce this in latest (`4.0.0-beta.13`). Note that I did have to change your html a bit (the label and item were switched):

```
<ion-content>
  <form>
    <ion-item>
      <ion-label position="floating">Question</ion-label>
      <ion-input name="answer" [(ngModel)]="answer"></ion-input>
    </ion-item>
  </form>
</ion-content>
```

I am going to close this, but if you're still running into this on latest please create a new issue with how we can reproduce. Thanks!

**Closed by brandyscarney** 2018-10-26 20:35 UTC
Labels: triage
