### ISSUE TITLE
bug: ion-segment does not work correctly together with ion-toolbar

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/ionic#21543] opened 2020-06-16 08:54 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
A page contains an ion-segment and is rendered into a router-outlet inside ion-content. 
An ion-toolbar is changing the page to be rendered and the first time it renders the mentioned page, it correctly displays the checked ion-segment. However, as soon as navigating over the toolbar, when the page is opened again, it does not show the previous selected segment. This is because, the angular 'value' variables are not set on the ion-segment and its children, when the component is instantiated again. 

**Expected behavior:**
The ion-segment should be working as expected and correctly style the previous selected segment.

**Steps to reproduce:**
1. Go To Tab1
2. Change selected segment
3. Go to Tab2
4. Go to Tab1 -> The ion-segment does not mark the, in step 2, selected segment.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-gr3xoq

**Comment by liamdebeasi** [comment] 2020-06-16 12:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The type of `tabService.activeSegment` is being set to a string, whereas you are asking Angular to interpret  the values in the segment buttons as integers using `[value]="1"`. This will cause strict equality checks to fail because `"2"` (the string) does not equal `2` (the integer) when using `===`.

To get around this, either cast `tabService.activeSegment` to an integer or remove the square brackets around `value`.

**Closed by liamdebeasi** 2020-06-16 12:55 UTC
Labels: triage

**Comment by NisStrom** [comment] 2020-06-16 13:02
I have updated the stackblitz example to use a string instead of an integer. However, the problem is the same: When you change to tab two and return back to the initial tab, the active tab is no longer selected.

**Comment by liamdebeasi** [comment] 2020-06-16 13:15
Sorry, what I meant was change the `value` on `ion-segment-button` to _not_ use square brackets. It looks like you updated `ion-segment` to use square brackets.

**Comment by liamdebeasi** [comment] 2020-06-16 13:17
Changing it like this worked for me:

```html
<ion-segment (ionChange)="segmentChanged($event)" [value]="tabService.activeSegment" mode="ios">
    <ion-segment-button value="1">
        <ion-icon name="send"></ion-icon>
    </ion-segment-button>
    <ion-segment-button value="2">
        <ion-icon name="send"></ion-icon>
    </ion-segment-button>
    <ion-segment-button value="3">
        <ion-icon name="send"></ion-icon>
    </ion-segment-button>
    <ion-segment-button value="4">
        <ion-icon name="send"></ion-icon>
    </ion-segment-button>
  </ion-segment>
```

**Comment by NisStrom** [comment] 2020-06-16 13:30
You're right, I misread what you wrote the first time. I've updated the example again to better depict our problem: 
The values of the ion-segment-buttons are defined as an enum which we also use at several different places in our code. We would very much like to keep it like this. Also with Ionic 4 it worked perfectly fine.

**Comment by liamdebeasi** [comment] 2020-06-16 13:32
In that case, you should do `this.tabService.activeSegment = parseInt(event.detail.value)` to change the active tab from a string to an integer.

**Comment by NisStrom** [comment] 2020-06-16 13:47
The problem occurs always when Angular data-binding is used, it does not matter what data type we use. Here is an example with integers: https://stackblitz.com/edit/ionic-v4-angular-tabs-9ghx2b

We've already found a workaround, we just wanted to report this to help improve the code.

**Comment by liamdebeasi** [comment] 2020-06-16 14:02
It looks like the underlying issue is that you are not switching tabs properly. Tabbed navigation should be using `ion-tabs` along with `ion-tab-bar`, but your application does not use that. Switching to use that format seems to resolve the issue for me (I was able to reproduce the behavior using the old format though).

**Comment by NisStrom** [comment] 2020-06-18 15:31
Here is an example of our HTML using Angular routing
```
<ion-header>
	<ion-toolbar class="tab-bar">
		<ion-buttons>
			<ion-button class="tab-button" routerLink="tab1" queryParamsHandling="preserve">
				<ion-label>Tab One</ion-label>
			</ion-button>
			<ion-button class="tab-button" routerLink="tab2" queryParamsHandling="preserve">
				<ion-label>Tab Two</ion-label>
			</ion-button>
		</ion-buttons>
	</ion-toolbar>
</ion-header>
<ion-content>
        <router-outlet></router-outlet>
</ion-content>
```
in comparison to a solution with ion-tabs
```
<ion-tabs>
    <ion-tab-bar>
        <ion-tab-button tab="tab1">
            <ion-label>Tab One</ion-label>
        </ion-tab-button>
        <ion-tab-button tab="tab2">
            <ion-label>Tab Two</ion-label>
        </ion-tab-button>
    </ion-tab-bar>
</ion-tabs>
```
We know that the problem does not occur if we would use ion-tabs. However we don't want to use them for the following reasons:

**1. Angular places the content of the router-outlet on the same level as the router-outlet where as Ionic places it within ion-router-outlet. We would like to follow Angular standards.**

_Angular_
```
<router-outlet></router-outlet>
<our-component></our-component>
```
_ion-tabs_
```
<ion-router-outlet>
	<our-component></our-component>
</ion-router-outlet>
```

**2. Ionic does not destroy components of inactive tabs. For our application lifecycle we depend on Angular's ngOnDestroy.**

- Open first tab:
_Angular_
```
<router-outlet></router-outlet>
<our-component-tab1></our-component-tab1>
```
_ion-tabs_
```
<ion-router-outlet>
	<our-component-tab1></our-component-tab1>
</ion-router-outlet>
```
- Open second tab:
_Angular_
```
<router-outlet></router-outlet>
<our-component-tab2></our-component-tab2>
```
_ion-tabs_
```
<ion-router-outlet>
	<our-component-tab1 class="ion-page-hidden"></our-component-tab1>
	<our-component-tab2></our-component-tab2>
</ion-router-outlet>
```
- Open first tab again:
_Angular_
```
<router-outlet></router-outlet>
<our-component-tab1></our-component-tab1>
```
_ion-tabs_
```
<ion-router-outlet>
	<our-component-tab1></our-component-tab1>
	<our-component-tab2 class="ion-page-hidden"></our-component-tab2>
</ion-router-outlet>
```

**3. Changing tabs with ion-tabs does not preserve query params**

- Open first tab:
_Angular_
url: …/tab1?world=aworld&center=2600000,1200000&scale=2835
_ion-tabs_
url: …/tab1?world=aworld&center=2600000,1200000&scale=2835

- Open second tab:
_Angular_
url: …/tab2?world=aworld&center=2600000,1200000&scale=2835
_ion-tabs_
url: …/tab2

- Open first tab again:
_Angular_
url: …/tab1?world=aworld&center=2600000,1200000&scale=2835
_ion-tabs_
url: …/tab1?world=aworld&center=2600000,1200000&scale=2835

As far as we could observe, the problem with ion-segments always occurs when we use Angular's router-outlet instead of ion-router-outlet (we also use it when navigating over ion-menu). 
Can you maybe explain why ion-router-outlet was implemented this way?
