### ISSUE TITLE
[4.0.0.-beta-7] Menu does not open by swipe gesture

### ISSUE THREAD

**Issue by michaeltintiuc** [ionic-team/ionic#15404] opened 2018-08-30 18:04 UTC
Menu can not be opened by a swipe gesture, it can however be opened programmatically via the controller's `open` method.
When open, the menu responds to touch events correctly and can be closed, but can not be reopened afterwards.

**Steps to Reproduce**
1. Try to swipe open the menu
2. Notice menu not responding to gesture
3. Trigger the menu programmatically
4. Close the menu with the swipe gesture
5. Try to swipe open the menu
6. Notice menu not responding to gesture

**Expected Behavior**
Menu should respond to touch gestures

**Comment by brandyscarney** [comment] 2018-08-30 18:13
Thanks for the issue! This is a duplicate of https://github.com/ionic-team/ionic/issues/15386

**Comment by manucorporat** [comment] 2018-09-04 14:37
Fixed in master!  will be available in next release!

**Closed by manucorporat** 2018-09-04 14:38 UTC
