### ISSUE TITLE
Ionic 4 Old page overlays over current page after navigation

### ISSUE THREAD

**Issue by pjoriginal** [ionic-team/ionic#15619] opened 2018-09-16 11:20 UTC
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```

Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/home/prasun/.npm-global/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.2, (and 9 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/prasun/Android/Sdk)
   NodeJS            : v8.12.0 (/usr/bin/node)
   npm               : 6.4.0
   OS                : Linux 4.15

```

**Describe the Bug**
After a few page navigations, when I navigate to the home page using angular's router navigate, one of the following things happen:
1. The navigation works fine.
2. A previous page in the navigation stack overlays the current page
3. A previous page in the navigation stack overlays the current page but is invisible. Because of this, the user can't tap anywhere the overlay page has elements.

Upon further investigation, I've found that this happens because the app-home has a z-index of 99 whereas the previous page has a z-index of 100

![screenshot from 2018-09-16 17-02-36](https://user-images.githubusercontent.com/20941445/45595878-79a61b80-b9d2-11e8-8135-2764527123e4.png)

Here, app-home is the current page, but the pages above it in the navigation stack are causing problems

**Expected Behavior**
Other pages which are not in the route should not overlay the current page

**Comment by AIxiuxiu** [comment] 2018-09-25 09:33
I also have this problem, tap the current page it disappeared

**Comment by mhartington** [comment] 2018-09-28 15:20
Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

**Comment by pjoriginal** [comment] 2018-10-07 05:41
> Hi there! This appears to be an issue, but there's no information on how to recreate or how to debug this. Could you please provide some more information or a demo in the form of a github repo? Thanks!

Hello @mhartington, 

Sorry for the late reply. I can't post the code. I will, however, try to recreate the the navigation scenario and post it here.

**Comment by Guillerbr** [comment] 2018-10-07 13:40
ok

**Comment by hiepxanh** [comment] 2018-11-06 09:04
tracking issue here, causing of transplie module [PROPER PACKAGE FOR ANGULAR #15191](https://github.com/ionic-team/ionic/issues/15191)

**Comment by hiepxanh** [comment] 2018-11-14 04:16
@mhartington  I make an small report here:
[github repo](url)

# Testing on Emulator device (Part 1): 

Step to reproduce:
- Generate a new project from ionic cli: ionic start ionic-error
- select `side menu template`
- run `ionic cordova run android` 
- testing on emulator: android 7.1.1, chrome 52
- emulator run successful **without error** but got `ion-page-invisible`

![image](https://user-images.githubusercontent.com/16970990/48457997-1cbeba00-e7f7-11e8-9b99-ba765d51a1bc.png)
![image](https://user-images.githubusercontent.com/16970990/48458030-352ed480-e7f7-11e8-836c-5126c797730d.png)

#Testing on Chrome directly:

I realize that ionic running on android depend on chrome version, that help me test faster without open real device. So I download few portable chrome that match with few specfic android version and make some test:

- chrome 30 (matching with android 4.4): doom is empty with error 
![image](https://user-images.githubusercontent.com/16970990/48459758-25ff5500-e7fe-11e8-97cf-35ad463d7512.png)
`Viewport argument key "viewport-fit" not recognized and ignored. home:9
Uncaught TypeError: Object [object Array] has no method 'fill' gesture.js:5`
![image](https://user-images.githubusercontent.com/16970990/48459791-534c0300-e7fe-11e8-897d-9ad745f738b0.png)

- chrome 46 (matching with android 5): no error with  `ion-page-invisible`
![image](https://user-images.githubusercontent.com/16970990/48459817-6b238700-e7fe-11e8-9ef2-6e0528f9c98d.png)

- chrome 70 : no error and it working

p/s: you can download [chrome portable here](https://drive.google.com/file/d/102-bRGGuedgFnycK4UHJakAT4UOb4koC/view?usp=sharing)

**Comment by hiepxanh** [comment] 2018-11-14 04:30
I belive that, even taking the time to create a good product we are not doing, how do we deserve to ask them to help us faster?

**Comment by hiepxanh** [comment] 2018-11-14 05:43
### Test on Emulator device part 2:
- Android 4.4, API level 19, chrome version 30 error:
![image](https://user-images.githubusercontent.com/16970990/48460660-a1fb9c00-e802-11e8-8a23-7988ac8e5a15.png)
![image](https://user-images.githubusercontent.com/16970990/48460686-c2c3f180-e802-11e8-86b5-457efd302645.png)

- Android 5, chorme version 39 error: 
![image](https://user-images.githubusercontent.com/16970990/48460883-a8d6de80-e803-11e8-90e2-c99030b1dea5.png)
![image](https://user-images.githubusercontent.com/16970990/48460904-b8eebe00-e803-11e8-8775-318790092e77.png)

- Android 6, chrome version 44:
![image](https://user-images.githubusercontent.com/16970990/48461319-b5f4cd00-e805-11e8-9d64-457cf9fe4284.png)
![image](https://user-images.githubusercontent.com/16970990/48461361-f05e6a00-e805-11e8-9438-ffa416ee18eb.png)

- Android 7, chrome 55: working without `ion-page-invisible`
![image](https://user-images.githubusercontent.com/16970990/48462476-e2f7ae80-e80a-11e8-99c8-05fc68a87f81.png)

**Comment by bryce13950** [comment] 2018-11-20 01:22
@hiepxanh Just for some info, the undefined fill functions are fixed by including the array polyfill, but even with that the app still fails.

**Comment by bryce13950** [comment] 2018-11-20 02:17
Also, using crosswalk basically solved all of my issues. Maybe not a long term solution, but it works for the time being.

**Comment by mhartington** [comment] 2018-11-20 21:07
@hiepxanh this is not the same as the original issue. Please follow #15438. @pjoriginal  did you ever happen to make a reproducible test case for this?

**Comment by Axdron** [comment] 2018-12-18 18:14
Hi all! 

I think I'm having the same problem. I doesn't happen always, just sometimes, I could reproduce the behavior during going forwards and backwards very fast (it doesn't happen when done slowly). I've tried using routerLink directive or the NavController, it happens in both cases. Looks like the problem happens because I'm pushing the page  before the last transition ends, then it gets stuck.

![navigation-stuck](https://user-images.githubusercontent.com/35466619/50173899-e38ad580-02df-11e9-8e1b-da2323b8e0d9.gif)


[navigation stuck.zip](https://github.com/ionic-team/ionic/files/2691705/navigation.stuck.zip)

**Comment by paulstelzer** [comment] 2018-12-20 08:30
@Axdron what you describe I can confirm, but I not tested it with the latest rc.0 - Maybe it's resolved now because there made changes. Could you test it?

**Comment by Axdron** [comment] 2018-12-20 10:15
@paulstelzer Sure! I'll update and test.

**Comment by Axdron** [comment] 2018-12-20 11:21
@paulstelzer Visually, it's solved, the "current" page is always on top. But now, when the same error happens, the pages are accumulating in the outlet, they aren't destroyed (only when the error occurs, normally they're being destroyed when I go back). It's not something critical because I don't expect the user behave like in the simulated situation.

![image](https://user-images.githubusercontent.com/35466619/50281659-5f4b6600-0437-11e9-8093-dabc958303b6.png)


An off-topic question: I was using the Content from @ionic/angular to scroll in a chat page and it's removed in rc.0 (I've had to remove the references to simulate). Am I supposed to use the infinite scroll to get the same result as scrollToBottom() from Content?

**Comment by paulstelzer** [comment] 2018-12-23 09:10
I close this here because it seems that many issues are mixed here - part of it is already solved. So if you have still an issue with "Old page overlays over current page after navigation" please open a new issue so we can investigate it further

**Closed by paulstelzer** 2018-12-23 09:10 UTC
Labels: triage
