### ISSUE TITLE
bug: iOS mode not working as expected in Safari (macOS and iOS)

### ISSUE THREAD

**Issue by cperezabo** [ionic-team/ionic#19988] opened 2019-11-25 01:09 UTC
# Bug Report

**Ionic version:**
**4.11.5**

**Current behavior:**
Animations, transitions, navigation in Safari (macOS / iOS) are not smooth at all, in fact they are very rough.
In Chrome everything work as expected without do anything so it's not a problem of my code because in Chrome it just works.
It didn't happened in Ionic 3, and based on the tests I have been done it only happens with the `ios` mode with Safari. The `md` mode works as expected in both browsers.
![issue](https://user-images.githubusercontent.com/3604722/69505096-bdfe4700-0f06-11ea-96d8-c0e8a9ad3435.gif)

**Expected behavior:**
The `ios` mode to work the same in Chrome and Safari.

**Steps to reproduce:**
> ionic start test sidemenu --type=angular 
> cd test
> ionic serve

1. Open Safari http://localhost:8100
2. Choose a iOS User Agent from "Developer" menu
3. Edit `src/app/list/list.page.html` and add a <ion-spinner> wherever you want.
4. Now in the menu click "Home" "List" "Home" "List" until you see the spinner gets frozen and the menu item gets with the background frozen in gray...

**Other information:**
As you can see it's not a bug in my app specifically, the problem is reproducible just creating a new project. 

This happens both in iOS 13 and macOS Catalina. 

**Ionic info:**
```

Ionic:

   Ionic CLI                     : 5.4.6 (/Users/cristian/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (/Users/cristian/.n/bin/node)
   npm    : 6.9.0
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment] 2019-11-25 14:12
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17649.

Please see https://github.com/ionic-team/ionic/issues/17649#issuecomment-542204919 for an explanation of the issue.

**Closed by liamdebeasi** 2019-11-25 14:12 UTC
Labels: triage
