### ISSUE TITLE
bug: buttons inside overflow div cause strange lag

### ISSUE THREAD

**Issue by matejkramny** [ionic-team/ionic#19017] opened 2019-08-07 05:52 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**

Apologies, this is quite hard to describe. We've made a slow motion video of the bug: https://photos.app.goo.gl/b2uEAyUEKDfr6omdA

9 to 11 seconds in you can see the effect this is causing.

The scroll isn't very smooth when it gets towards the end of the content.

**Expected behavior:**

The scroll animation would be smooth, having a bouncing effect from the edge as expected on ios devices

**Steps to reproduce:**

We have `<ion-button>` elements inside a `div` with some `overflow-x`

**Related code:**

Illustrated in the video, hope this might shine some light on what's going on.

```
insert short code snippets here
```

**Other information:**
The buttons have <ion-ripple-effect> inside.

We're assuming that might have something to do with it, although not sure how. It might be a delayed effect from releasing the button (hover) incidentally having the same timing as reaching the end of the scroll.

**Ionic info:**

```
cli 5.2.2
framework @ionic/angular 4.1.2
capacitor 1.0.0
```

**Comment by liamdebeasi** [comment] 2019-08-07 12:25
Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

**Comment by matejkramny** [comment] 2019-08-07 15:36
Sorry does the video show the issue? I'm unable to view on google photos.. We'll provide a code sample tmr.

Thanks!

/cc @fauziku2

**Comment by liamdebeasi** [comment] 2020-05-22 19:36
Thanks for the issue. I am going to close this due to lack of a code reproduction. If this is still a bug with the latest version of Ionic Framework, please create a new issue, and include a code sample we can use to reproduce the issue. Thanks!

**Closed by liamdebeasi** 2020-05-22 19:36 UTC
Labels: triage
