### ISSUE TITLE
bug: ionic-react does not support cordova-plugin-ios-keychain?

### ISSUE THREAD

**Issue by CodeDreamfy** [ionic-team/ionic#20516] opened 2020-02-17 15:45 UTC
# Bug Report

**Ionic version:**
ionic/react : ^4.11.0

**Current behavior:**
When I added Keychain according to the official instructions, I found that it was not found in the plugins

**Expected behavior:**
Expect to be able to register successfully and use Keychain

**Steps to reproduce:**

**Related code:**
I used the following commands to install:
```shell
npm install -s @ ionic-native/keychain

npm install cordova-plugin-ios-keychain

npx cap sync

#  use: npx cap ls
Found 0 Capacitor plugins for ios:
  Found 1 Cordova plugins for ios:
   cordova-plugin-ios-keychain（3.0.1）
```

After installation
On the page

```js
import {Plugins} from '@ capacitor/core';
const {Keychain} = Plugins;
```

But found `Keychain` to be undefied

**Comment by liamdebeasi** [comment] 2020-02-17 16:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `Plugins` import from `@capacitor/core` imports the core plugins that ship with Capacitor by default.

For other Cordova plugins w/ Ionic Native, please follow this guide: https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/

**Closed by liamdebeasi** 2020-02-17 16:25 UTC
Labels: triage

**Comment by CodeDreamfy** [comment] 2020-02-17 16:36
> Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The `Plugins` import from `@capacitor/core` imports the core plugins that ship with Capacitor by default.
> 
> For other Cordova plugins with Ionic Native, please follow this guide: https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/

I used it according to this document, but I didn't find it. Can you help me? I can't find this plugin in plugins , I will be very grateful.

**Comment by liamdebeasi** [comment] 2020-02-17 16:53
You are not supposed to use the Keychain plugin via the `Plugins` import from `@capacitor/core`. You will still need to do:

```
import { Keychain } from '@ionic-native/keychain/ngx';
```

See: https://ionicframework.com/docs/native/keychain

For additional help implementing this, I recommend asking your question on our [forums](http://forum.ionicframework.com/).

**Comment by CodeDreamfy** [comment] 2020-02-18 02:10
> You are not supposed to use the Keychain plugin via the `Plugins` import from `@capacitor/core`. You will still need to do:
> 
> ```
> import { Keychain } from '@ionic-native/keychain/ngx';
> ```
> 
> See: https://ionicframework.com/docs/native/keychain
> 
> For additional help implementing this, I recommend asking your question on our [forums](http://forum.ionicframework.com/).
Yes, I have used it like this, but I have n’t introduced how to use it in the next step after importing it. Is there a specific method that I ca n’t understand the official usage method, do I need to instantiate? Because I use react, it seems to provide ng usage.

**Comment by liamdebeasi** [comment] 2020-02-18 14:13
Ah I did not realize you were using Ionic React. Currently Ionic Native has support for Ionic Angular. In that case, you should just import the Cordova plugin directly.
