### ISSUE TITLE
ToastCtrll will not disappear in ionic-angular3.5.0。

### ISSUE THREAD

**Issue by WangRongda** [ionic-team/ionic#12269] opened 2017-07-06 03:22 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v8.1.3
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3
```
insert the output from ionic info here
```
**When I update ionic-angular to latest 3.5.0 from 3.4.0，the toast will not disappear when create a new toast if the previous toast has not disappear. Then the toast will break down. New toast will not appear and old toast will not disappear.**
**ionic-angular3.5.0 :**
![3 5](https://user-images.githubusercontent.com/22711444/27894151-0b296df8-623d-11e7-89d5-2910146e491b.gif)

**ionic-angular3.4:**
![3 4](https://user-images.githubusercontent.com/22711444/27894170-2a58f554-623d-11e7-9cfc-26d8f9946884.gif)

**Comment by 5im0n** [comment] 2017-07-06 11:00
Same issue in my application due to the v3.5.0 migration: 

```
presentToast() {
  let toast = this.toastCtrl.create({
    message: 'User was added successfully',
    duration: 3000,
    position: 'top'
  });

   toast.present();
}
```

If the previous toast is not remove, and some new ones are created new they will never disappear

**Comment by pwespi** [comment] 2017-07-06 11:47
The same issue can be seen in the [ionic conference app](https://github.com/ionic-team/ionic-conference-app). When you pull down the schedule to refresh, a toast is shown. If you pull down again before the toast is dismissed then it will never disappear.

**Comment by jgw96** [comment] 2017-07-06 14:33
Thanks for opening an issue with us. We will look into this.

**Comment by jgw96** [comment] 2017-07-06 16:13
Hello all! After debugging this i can report that this has actually already been fixed and is in the latest nightly release of `ionic-angular`. To install nightly you can run `npm install ionic-angular@nightly --save`. This fix will be in the next release. Thanks for using Ionic!

**Closed by jgw96** 2017-07-06 16:13 UTC
Labels: v3

**Comment by uzumakinaruto123** [comment] 2017-07-31 11:03
@jgw96 I have tested this nightly + stable build. I can still reproduce this on `"ionic-angular": "^3.5.3-201707261447"` and latest the greatest  `"ionic-angular": "^3.6.0"`
