### ISSUE TITLE
Can't go back to edit previous field after filling it and changing fields

### ISSUE THREAD

**Issue by Gaabe** [ionic-team/ionic#13606] opened 2017-12-07 15:20 UTC
**Ionic version:** 
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...** 
[ x ] bug report
[ ] feature request

**Current behavior:**
On some devices, after selecting a text input field, filling it with text, and then proceeding to the next input field, i can't type anymore in the first field, it wont even let me select the field by tapping on it

**Expected behavior:**
It should be able to go back to the previous fields without problems

**Steps to reproduce:**
Create project and in a page put 2 text input fields, fill the first one, then fill the second one, and after that try to go back to the first one

**Other information:**
Happens when testing on some android devices, like Moto G5

**Ionic info:** 

cli packages: (/myApp/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.5.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.7.0
    npm               : 5.5.1 
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /opt/android-sdk-linux

Misc:

    backend : pro

**Comment by kensodemann** [comment] 2017-12-08 12:17
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13587. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.

At this time, this all evidence points to this being a bug in certain versions of Chrome.

Thank you for using Ionic

**Closed by kensodemann** 2017-12-08 12:17 UTC
