### ISSUE TITLE
ion-img not set value in src property in img tag in android 7.1.0[ionic4rc2]

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#17172] opened 2019-01-18 18:42 UTC
in my app show multiple image with following code : 

      <ion-col size="4" *ngFor="let cat of categoryList">
            <div text-center tappable (click)="goToCategoryList(cat)">
               <div>
                    <ion-img [src]="cat.icon" style="width:40px;margin: 0 auto 0 auto;"></ion-img>
               </div>
               <p style="margin-top:0;">{{cat.title}}</p>
           </div>
      </ion-col>

in browser and many android devices work correctly but in android 7.1.0 not work correctly and not set value in src property in img tag.<br>
the following code created with ion-img:<br>

     <ion-img style="width:40px;margin: 0 auto 0 auto;" class="sc-ion-img-h hydrated">
       <img decoding="async" class="sc-ion-img">
     </ion-img>

**Comment by chrisbinnefeld** [comment] 2019-01-19 11:03
I can confirm this bug. It looks like a problem with older WebView versions. I think there are still some polyfills missing. I tried to add a polyfill for the _IntersectionObserver_. After that the src property was added to the <img> but still not shown.

see https://github.com/ionic-team/ionic/issues/16337#issuecomment-449408567

**Comment by paulstelzer** [comment] 2019-01-19 17:48
Thanks for the issue. I close this as duplicate of #16337

**Closed by paulstelzer** 2019-01-19 17:48 UTC
Labels: triage
