### ISSUE TITLE
Support text area in alert .

### ISSUE THREAD

**Issue by tawfiek** [ionic-team/ionic#15561] opened 2018-09-12 11:42 UTC
# Feature Request

**Ionic Info**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.0
    ionic (Ionic CLI) : 3.9.0

global packages:

    Cordova CLI : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.10.0
    npm               : 3.5.2 
    OS                : Linux 4.15


```

**Describe the Feature Request**

Adding text area input in alert to  make   user able to add more than one line in inputs  in alert controller .

**Comment by brandyscarney** [comment] 2018-09-12 17:40
Duplicate of #14153

**Closed by brandyscarney** 2018-09-12 17:40 UTC
Labels: triage
