### ISSUE TITLE
bug: [iOS] Side menu close animation not behaving correctly

### ISSUE THREAD

**Issue by Reqven** [ionic-team/ionic#21186] opened 2020-05-01 17:37 UTC
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
When the `ion-content` doesn't have the `fullscreen` attribute set to `true`, the side menu closes itself instantly without any animation if the iOS device has the low power mode enabled. See the attached gif below. (only occurs on iOS)

![ios](https://user-images.githubusercontent.com/17118398/80824055-f86abf00-8bdd-11ea-9ae9-6db457716efd.gif)

**Expected behavior:**
The side menu should smoothly close itself, having the low power mode enabled or not.

**Steps to reproduce:**
- Create a new Ionic project using `ionic start`  
- Choose the `side-menu` template
- Open the file src/app/folder/`folder.page.html`
- Remove `[fullscreen]="true"` on `<ion-content>`
- Prepare and add the iOS platform with `ionic cordova prepare ios`
- Open Xcode and run the app on a real device
- Enable the low power mode

**Related code:**
I have found a temporary fix to keep the animation no matter what :
- Set the `fullscreen` attribute to true
- Use some CSS to avoid the fullscreen effect

```
<ion-content [fullscreen]="true">
```
```
ion-content {
  --offset-top: 0px !important;
  --offset-bottom: 0px !important;
}
```
While this works, this is clearly not ideal.

**Other information:**
iPhone X running iOS `13.2.2`.
I couldn't test on another iOS device/version.

Works fine on iOS if the low power mode is disabled.
Works fine either way on Android/Browser.

**Ionic info:**
```
Ionic:
   Ionic CLI                     : 6.7.0 (/Users/reqven/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:
   cordova-res (update available: 0.14.0) : 0.10.0
   native-run (update available: 1.0.0)   : 0.2.8

System:
   Android SDK Tools : 26.1.1 (/Users/reqven/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.16.1 (/Users/reqven/.nvm/versions/node/v12.16.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by liamdebeasi** [comment] 2020-05-01 19:22
Thanks for the issue. Can you provide a full repo? I tested this on my device and am unable to reproduce the issue.

**Comment by Reqven** [comment] 2020-05-01 22:49
> Thanks for the issue. Can you provide a full repo? I tested this on my device and am unable to reproduce the issue.

You can reproduce the issue with the following repo [Ionic-sidemenu-animation-bug](https://github.com/Reqven/Ionic-sidemenu-animation-bug)  
I've attached the steps and a new gif in the README to reproduce the issue.
Pay attention to the gif as it explicitly shows the issue.

Again, it only occurs on iOS.
Thank you.

**Comment by liamdebeasi** [comment] 2020-05-04 13:27
Thanks for the follow up. I tried your repo on a device running iOS 12.4 and a device running iOS 13.4 and was unable to reproduce the issue in low power mode on either device.

I followed these steps:

1. With low power mode disabled, go from `First` to `Second`.
2. Go from `Second` to `First`.
3. Enable low power mode.
4. Go from `First` to `Second`.

Every time I navigated I got a closing animation. Am I following the correct steps?

**Comment by Reqven** [comment] 2020-05-06 12:25
Yes, these are the correct steps.
A coworker of mine couldn't reproduce the issue either on iOS 13.4.1
Updating my iPhone to the latest iOS version fixed the issue.

Pretty sure this was related to my device, it's been a while I haven't factory reset/updated it.
Thanks for investigating, I guess you can close this issue now.

**Closed** 2020-05-06 13:20 UTC
Labels: triage
