### ISSUE TITLE
feat: Scrollable ion-datetime

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic#20724] opened 2020-03-09 10:16 UTC
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
As a Ionic app is also deployable to desktop the ion-datetime component isn't really ergonomic when used with a mouse (on desktop, and mouse support on tablet), it would be really nice for it to be scrollable, currently we have to "swipe" but with the mouse.

**Describe Preferred Solution**
Make ion-datetime scrollable with a mouse wheel

**Comment by liamdebeasi** [comment] 2020-03-09 13:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15505.

**Closed by liamdebeasi** 2020-03-09 13:15 UTC
Labels: triage
