### ISSUE TITLE
bug: The ios drop-down refresh is a little bit wobbly

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19352] opened 2019-09-16 06:09 UTC
bug: The ios drop-down refresh is a little bit wobbly

# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When `ion-refresher` is used to slow down, the distance of 10px or so bounces back to the top, before it is normal to continue

**Expected behavior:**

Smooth pull down

**Steps to reproduce:**

ios,iPhone X 12.4

**Related code:**

```
<ion-content>
    <ion-refresher slot="fixed" pullFactor="0.4" pullMax="1000" (ionRefresh)="doRefresh($event)">
      <ion-refresher-content></ion-refresher-content>
    </ion-refresher>
  <ion-list>
    <ion-item>aaa</ion-item>
    <ion-item>aaa</ion-item>
    <ion-item>aaa</ion-item>
    <ion-item>aaa</ion-item>
    <ion-item>aaa</ion-item>
  </ion-list>
</ion-content>
```

**Other information:**
![filename (1)](https://user-images.githubusercontent.com/20217449/64937075-62bb3300-d88b-11e9-8722-0766938f106a.gif)

**Ionic info:**

**Comment by eternityBUG** [comment] 2019-10-06 06:32
I was in the same situation

**Comment by eternityBUG** [comment] 2019-10-06 06:33
I was in the same situation

**Comment by liamdebeasi** [comment] 2019-10-14 12:46
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19163.

**Closed by liamdebeasi** 2019-10-14 12:46 UTC
Labels: triage
