### ISSUE TITLE
v4: ion-button with href not styled as anchor

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic#14777] opened 2018-07-15 02:49 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.11 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-alpha.9
   @angular-devkit/core       : 0.7.0-rc.1
   @angular-devkit/schematics : 0.7.0-rc.1
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.10
   @ionic/schematics-angular  : 1.0.0-rc.10

System:

   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
Breaking changes documentation says "Ionic will determine when to render an anchor tag based on the presence of an href attribute."
https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md

However, an ion-button with an href or routerLink attribute looks the same as a button and is not styled like an anchor tag.

**Steps to Reproduce**
1. Add ion-button with href or routerLink attribute.
2. Displays as button and not an anchor

**Related Code**
```
<ion-button href="/about">About</ion-button>
<ion-button routerLink="/about" routerDirection="forward">About</ion-button>
```

**Expected Behavior**
Expecting element to look like an anchor e.g.underlined text.

**Comment by brandyscarney** [comment] 2018-07-16 16:55
Thanks for the issue! So the `ion-button` component is working as intended. This element should always look like a button element, even if it is rendering an `anchor` tag underneath. 

We have another element called an `ion-anchor` that should work the same with the router, but I just noticed it is not getting the correct styles. I'll be pushing a fix for this shortly and then we'll have that in the next release. 🙂

**Closed** 2018-07-16 16:58 UTC
Labels: triage
