### ISSUE TITLE
bug: ion-note with mode ios does not fully apply the style

### ISSUE THREAD

**Issue by Terordar** [ionic-team/ionic#21233] opened 2020-05-07 09:23 UTC
Hello everyone, I hope you are doing good! I'm not sure if this is a bug really, but it doesn't seem to be the expected behavior.

# Bug Report

**Ionic version:**

[x] **5.1.0**

**Current behavior:**
When setting the _mode_ property of ion-note to ios, only the color is applied (and not the font size difference) on any other device : 
![image](https://user-images.githubusercontent.com/10707857/81277088-32134e00-9054-11ea-8da1-5deed8fa030a.png)

But when rendering the application using an iOS device, you can see that the font size of the ion-note is completely different :
![image](https://user-images.githubusercontent.com/10707857/81277020-1d36ba80-9054-11ea-8c9d-684717ebda6c.png)

**Expected behavior:**
When using mode ios, the ion-note styling should be the same on iOS devices and other devices.

**Steps to reproduce:**
Add an ion-note and apply the ios mode.

**Related code:**

https://stackblitz.com/edit/ionic-angular-v5-trzue5

```
<ion-note mode="ios">Test</ion-note>
```

Have a nice day everyone!

**Comment by liamdebeasi** [comment] 2020-05-07 13:18
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The font-size for `ion-note` when slotted inside of `ion-item` is controlled by the `ion-item` CSS: https://github.com/ionic-team/ionic/blob/master/core/src/components/item/item.md.scss#L150-L156.

Since the `ion-item` mode is not changing, the font-size will not change either. You can see the difference by setting `mode="ios"` on `ion-item`.

If you want to change the font-size of the note, you should set it on the note directly. Hope this clears things up!

**Closed by liamdebeasi** 2020-05-07 13:18 UTC
Labels: triage

**Comment by Terordar** [comment] 2020-05-07 13:39
Thank you very much @liamdebeasi ! :)
