### ISSUE TITLE
bug: --background-focused not working on fab button

### ISSUE THREAD

**Issue by gailu** [ionic-team/ionic#19876] opened 2019-11-09 17:12 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
--background-focused custom css property of ion-fab-button is not working.

**Expected behavior:**
--background-focused custom css property of ion-fab-button should change the background of ion-fab-button when in focussed

**Steps to reproduce:**
set --background-focused property to any color (other than primary) for ion-fab-button

**Related code:**
scss code

`    [fab-icon] {
      --background: #FF9900;
      --background-focused: #32313B;
      --background-activated: #32313B;
    }`

html code
`<ion-content>
  <ion-fab vertical="top" horizontal="end" slot="fixed">
    <ion-fab-button fab-icon>
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
  </ion-fab>
</ion-content>`

**Other information:**
while --background and --background-activated are working fine, --background-focused takes no effect and focused color is always primary

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.1 (C:\Users\vipin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 15 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by brandyscarney** [comment] 2019-11-11 16:13
Thanks for the issue! I'm not able to reproduce on latest. The focused state appears when tabbing to the fab button. Are you able to provide a repo to reproduce this?

Here's my codepen: https://codepen.io/brandyscarney/pen/LYYBmoL

**Comment by gailu** [comment] 2019-11-12 04:29
The issue is clearly visible on on your codepen link. If you see the css file --background is orange (#ff9900) while --background-focused and --background-activated both set to same values of Grey color (#32313b). However when we take mouse to button instead of grey color it shows **blue color** so  **--background-focused** is not working. Although when pressing button the background changes to grey (#32313b) so --background-activated seems to be working fine. Can you please just recheck behaviour on your codepen link, else I will capture a video from your codepen link

**Comment by brandyscarney** [comment] 2019-11-13 15:55
Are you confusing the hover state with the focused state? As I said, tabbing to the fab button (which is what triggers a focused state) is working properly. If you're looking to change the background when the mouse is on top of the button (hover) you would use the following: `--background-hover`. Updated Codepen to reflect the added hover state variable.

**Comment by gailu** [comment] 2019-11-14 04:25
Thanks for your help and support. It was indeed --background-hover that I was looking for but since I did not find it in [documentation ](https://beta.ionicframework.com/docs/api/fab-button), I assumed that --background-focused is suppose to do the job. My apologies. 
Documenation only talks about --background, --background-activated and --background-focused. --background-hover is not documented but it is working fine. Hope someone can update this property in documentation also.

Thanks again for your help and really sorry for misunderstanding the properties of fab button.

**Comment by brandyscarney** [comment] 2019-11-14 16:26
That's okay! It looks like you're visiting a beta version of the docs (https://beta.ionicframework.com/docs/api/fab-button). Since Ionic 4 was released you should be able to visit the site without the `beta.` in front to see the most recent docs: https://ionicframework.com/docs/api/fab-button

I am going to close this since that should solve everything, thanks for reporting! 🙂

**Closed by brandyscarney** 2019-11-14 16:26 UTC
Labels: triage
