### ISSUE TITLE
bug: pulling ion-refresher causes large title to be collapsed

### ISSUE THREAD

**Issue by gbrunow** [ionic-team/ionic#20676] opened 2020-03-03 00:00 UTC
# Bug Report

**Ionic version:**

v5.0.4

**Current behavior:**

When `ionic-refresher` is pulled it interferes with the collapsible titles.
![Ionic App](https://user-images.githubusercontent.com/5505621/75728737-5fd3c380-5cae-11ea-8cc1-5eddc97e11df.gif)

**Expected behavior:**
`ionic-refresher` shouldn't after the state of collapsible titles, thus leaving the large title active.
![Ionic App (1)](https://user-images.githubusercontent.com/5505621/75728903-d375d080-5cae-11ea-88b8-50c927b26193.gif)

**Steps to reproduce:**

1. Create a component that contains a collapsible title
2. Add an ion-refresher
3. Add an `ng-content` tag so it can be used in another page
4.. Use it as a page template, injecting content through `ng-content`

**Related code:**
- Template:
```html
<ion-header translucent="true">
  <ion-toolbar>
    <ion-buttons slot="end">
      <ion-button>
        <ion-icon name="person-circle-outline"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-title>{{title}}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">

  <ion-refresher slot="fixed" pullFactor="0.5" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>

  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">{{title}}</ion-title>
    </ion-toolbar>
  </ion-header>

  <ng-content></ng-content>
</ion-content>
```

**Other information:**

- This does not happen if all the HTML is part of the same page (as shown in the sample for [Tab 2](https://github.com/gbrunow/ionic-bug/blob/master/src/app/tab2/tab2.page.html))  like so:
```html
<ion-header translucent="true">
  <ion-toolbar>
    <ion-title>Tab 2</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">

  <ion-refresher slot="fixed" pullFactor="0.5" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>

  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Tab 2</ion-title>
    </ion-toolbar>
  </ion-header>

  ...

</ion-content>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.7.0 (/usr/bin/node)
   npm    : 6.14.1
   OS     : Linux 4.4
```

**Comment by elvisgraho** [comment] 2020-03-03 09:41
As far as I know Ion-header must be outside of ion-content. What ion-refresher does ist that it pulls whole ion-content down. Please put ion-header outside and above of ion-content and report if that fixed the issue.

**Comment by gbrunow** [comment] 2020-03-03 14:09
This is a sample straight from the documentation:
```html
<ion-header translucent="true">
  <ion-toolbar>    
    <ion-title>Settings</ion-title>               
  </ion-toolbar>
</ion-header>

<ion-content fullscreen="true">
  <ion-header collapse="condense">              
    <ion-toolbar>      
      <ion-title size="large">Settings</ion-title>
    </ion-toolbar>
    <ion-toolbar>
      <ion-searchbar></ion-searchbar>
    </ion-toolbar>
  </ion-header>

  ...

</ion-content>
```
https://ionicframework.com/docs/api/title

I believe that notation is required for collapsible titles.

**Comment by liamdebeasi** [comment] 2020-03-03 16:01
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. When using your own custom components that wrap an Ionic page, you need to ensure that the dimensions for the page are correct. 

In the case of your application the dimensions of your `hype-tab-page` component had a height of only 44px. The large title and the refresher both rely on these dimensions being correct in order to work properly. By default, all Ionic pages receive the `ion-page` class, so just adding the `ion-page` class to `hype-tab-page` should fix the issue.

**Closed by liamdebeasi** 2020-03-03 16:01 UTC
Labels: triage

**Comment by gbrunow** [comment] 2020-03-03 16:09
@liamdebeasi that actually makes a lot of sense, thank you for your time!

**Comment by gbrunow** [comment] 2020-03-03 19:45
### In case anyone else ends up having the same issue.
@liamdebeasi's suggestion indeed solved the `ion-refresher` issue I was seeing.
However,  it caused another problem that seems related to using ionic components inside custom components.

Notice the behavior I see in the header section:
![Ionic App](https://user-images.githubusercontent.com/5505621/75812317-9e6f8980-5d53-11ea-8180-01f4ad0a8c2e.gif)

And again when I remove the class `ion-page`
![Ionic App](https://user-images.githubusercontent.com/5505621/75812973-c9a6a880-5d54-11ea-90ea-3cb821e2d3a8.gif)

In order to get around that I'm not adding the `ion-page` class as suggested, but instead just forcing the page template to fill up the screen as required by doing so:
```css
:host {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
}
```
**Obs.: the repository has been update with these changes**
