### ISSUE TITLE
bug: ion-slide swipe and click

### ISSUE THREAD

**Issue by kalicki** [ionic-team/ionic#17981] opened 2019-04-06 01:06 UTC
# Bug Report

**Ionic version:**
[x] 4.2.0

**Current behavior:**
Hey, has a bug in `ion-slide` when I do a swipe and hold and click at the same time it shows error in the `transform`

Video: 
https://streamable.com/1evdl

Screenshot:
![Screenshot_20190405-111834_Cooktop](https://user-images.githubusercontent.com/3674885/55662935-e35f0900-57ee-11e9-8869-9494b3288049.jpg)

**Steps to reproduce:**
Swipe to right/left and click with swipe active

**Related code:**

Simple code:
```
<ion-slides pager="false" [options]="slideOptions" #tagSlides>
        <ion-slide *ngFor="let tag of tags">
          <ion-card class="tag-image" mode="ios" (click)="goPage(tag)">
            <img src="{{tag.image}}" alt="" />
          </ion-card>
          <h2>{{tag.title}}</h2>
        </ion-slide>
      </ion-slides>
```
```
slideOptions = {
    loop: false,
    initialSlide: 0,
    slidesPerView: 1,
    centeredSlides: false,
    spaceBetween: 10
  };
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/kalicki/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.19
   @capacitor/core           : 1.0.0-beta.19

System:

   NodeJS : v10.15.3 (/Users/kalicki/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment] 2019-04-08 15:07
Hi there,

Thanks for the issue. I am unable to reproduce the issue you are reporting. Can you clarify the steps you are taking to reproduce this issue?

Thanks!

**Comment by kalicki** [comment] 2019-04-08 19:26
Hi,

We have a slideshow with cards. So when the person gives a swipe to the right or left and hold on (in the swipe) and give a touch that error is shown.
I think in the video you can see the problem well and the interaction of swipe with click.

**Comment by liamdebeasi** [comment] 2019-04-09 12:52
Hi there,

Are you able to reproduce this on a clean starter application? Given the code you provided, I am unable to reproduce the issue you are experiencing.

**Comment by kalicki** [comment] 2019-04-09 15:38
In this other video has another problem, two clicks with two fingers.

https://streamable.com/1pje4

**Comment by liamdebeasi** [comment] 2019-04-09 19:53
Hi there,

Thanks for the follow up. You need to wrap the content in your `ion-slide` component in `<div class="swiper-zoom-container"></div>` since your swiper instance has zooming enabled. From what it looks like, I think having the two fingers on the screen at the same time is trying to trigger something with zooming, but that zoom container div isn't present and an error is being thrown as a result.

I am going to close this as it is not a bug, but I will make sure the `ion-slides` docs are updated to make note of this.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-09 19:53 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2019-04-09 19:56
Actually, changed my mind. I think it's pretty easy enough for `ion-slide` to include the wrapper, so I'll update the slides component to do that.

In the meantime, the code I posted previously will work!
