### ISSUE TITLE
bug: ngFor not working async

### ISSUE THREAD

**Issue by Sjoerrdd** [ionic-team/ionic#18393] opened 2019-05-27 13:37 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The field is empty

**Expected behavior:**

The dropdown menu is empty

**Steps to reproduce:**

Create an object and put it into a var

**Related code:**
```js
// This doesn't work
<ion-select-option *ngFor="let klantproject of user.projects  | async">{{ klantproject.projectnr }}</ion-select-option>

// This works, but takes WAY to long
<ion-select-option *ngFor="let klantproject of user.projects">{{ klantproject.projectnr }}</ion-select-option>
```

**Other information:**

**Ionic info:**

```

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0-dev.201905231504.7ab9479
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.9.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

```

**Comment by liamdebeasi** [comment] 2019-05-28 13:47
Hi there,

Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17344.

Also linking https://github.com/ionic-team/ionic/issues/18288.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-28 13:47 UTC
Labels: triage
