### ISSUE TITLE
Platform Specific Styles in the app's config not working in RC1

### ISSUE THREAD

**Issue by gigocabrera** [ionic-team/ionic#8806] opened 2016-10-19 17:49 UTC
#### Short description of the problem:

From the [Platform Specific Styles](https://ionicframework.com/docs/v2/theming/platform-specific-styles/) docs and the [Config API](https://ionicframework.com/docs/v2/api/config/Config/) docs, I'm trying to force a popover control to use material design style for my app, regardless of platform selected. But it does not seem to be working even on browser (Chrome)
#### What behavior are you expecting?

I expect the popover control in my app to use the material design style when I add the following entries to the config

```
imports: [
    IonicModule.forRoot(MyApp, {
      popoverEnter: 'popover-md-pop-in',
      popoverLeave: 'popover-md-pop-out'
    }),
    AngularFireModule.initializeApp(firebaseConfig, firebaseAuthConfig)
  ],
```

**Which Ionic Version?** 2.x
#### Other information

The [official demo here](https://ionicframework.com/docs/v2/api/config/Config/) doesn't eve work

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.33
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by gigocabrera** [comment] 2016-12-09 17:24
???

**Comment by jgw96** [comment] 2017-06-05 16:48
Hello @gigocabrera . I am going to close this issue for now as I cannot reproduce this issue in the latest version of Ionic. Thanks!

**Closed by jgw96** 2017-06-05 16:48 UTC
Labels: css, v2

**Comment by philipgriffin** [comment] 2017-12-09 20:05
I believe I am facing this issue now although I am trying to set the style to ios.

I do not get the ios popover but if I attempt to get the md popover across devices it works.

The code I am using is
```
IonicModule.forRoot(MyApp, {
      popoverEnter: 'popover-pop-in',
      popoverLeave: 'popover-pop-out'
    }),
```
What I receive is..

**(Android on the left, iOS on the right)**

![Output](https://i.imgur.com/69E6aEb.png)

What I expect to see is the arrow like point towards the button that opened the popover being showed on both devices (not just the iOS device, seen on the right in the image)

Ionic info:
@ionic/app-scripts : 3.1.5
@ionic/cli-plugin-proxy: 1.5.6
@ionic/cli-utils: 1.19.0
ionic (Ionic CLI): 3.19.0

**Comment by gamboaweb** [comment] 2017-12-16 00:00
With me is happening the same as it does with philipgriffin...
I'm running Ionic 3.9.2.
It also shows a blank popover and NO arrow towards the button...

**Comment by alaa-alshamy** [comment] 2017-12-16 06:36
@philipgriffin @gamboaweb i think u have some misunderstanding about what "popoverEnter" and "popoverLeave" does, those to override only the transition of popover while present or leave not to override the design

**Comment by philipgriffin** [comment] 2017-12-16 16:07
@alaa-alshamy - ah I see. I have misunderstood it then. Does that mean there is no way to specify the design of the popover? (Without manually changing css)

**Comment by alaa-alshamy** [comment] 2017-12-17 05:56
yea i think so, There is currently no way to set a single component to match the styles of a different platform. u can change the whole app design only

**Comment by mugavri** [comment] 2018-05-18 00:52
any update?
