### ISSUE TITLE
bug: ion-menu-button is not hidden when using SplitPane

### ISSUE THREAD

**Issue by scrpgil** [ionic-team/ionic#18666] opened 2019-06-29 04:38 UTC
# Bug Report

**Ionic version:**

[x] **~4.5.x**

**Current behavior:**

Ion-menu-button is not hidden when using SplitPane. The icon is not displayed like the image, but the width(48px) for the icon has been present.

![Screen Shot 2019-06-29 at 13 26 12](https://user-images.githubusercontent.com/26167770/60379654-97c89e00-9a71-11e9-9a1b-ecd3b08ab0bb.png)

**Expected behavior:**

Please execute the following command.
Up to v 4.4.0 was displayed as below.

![Screen Shot 2019-06-29 at 13 32 15](https://user-images.githubusercontent.com/26167770/60379696-55539100-9a72-11e9-9c07-7eeda4b57783.png)

**Steps to reproduce:**

```
ionic start test-sidemenu sidemenu
cd test-sidemenu 
ionic serve
```

Please see the launched application on your PC.

**Related code:**

This code seems to be the cause.

https://github.com/ionic-team/ionic/blob/45b82dc466e3b5a9cc020456c224a45ef8dff0c5/core/src/components/menu-button/menu-button.md.scss#L14

There is no issue if you write CSS as follows.

```
:host {
  button {
    width: 48px;
    height: 48px;
  }
}
```

**Other information:**

I want to fix this issue!

I've committed the fix for this issue to my forked repository. If there is no problem I want to create a pull request with the same one! 
https://github.com/scrpgil/ionic/commit/ee4716a6db9755b81ffbb91f1445bc550edbba51

**Comment by kensodemann** [comment] 2019-06-29 11:46
We have a PR for this one. It is https://github.com/ionic-team/ionic/pull/18564

@brandyscarney left a comment that it looks good, but has not merged it yet. I am not sure where that stands, but just documenting that we may already have a fix for this waiting...

**Comment by scrpgil** [comment] 2019-06-29 11:59
Oh, did you already have a pull request ....
However, I think that the menu-button will be hidden even if the property of auto-hide is true if the change of the pull request.

**Comment by simonhaenisch** [comment] 2019-06-29 21:13
Was just about to write sth about this before I found this issue... here's a reproduction I already created:

| `4.4.0` | `4.5.0` |
|-|-|
| ![image](https://user-images.githubusercontent.com/3410759/60389487-177e5900-9ac2-11e9-8159-0a6d005e8cfb.png) | ![image](https://user-images.githubusercontent.com/3410759/60389492-2a912900-9ac2-11e9-93ca-10468886f492.png) |
| https://jsfiddle.net/simonhaenisch/31xpv57s/ | https://jsfiddle.net/simonhaenisch/qon16xfd/ |

And as @scrpgil already said I also think it's because of this change from #18434:

> * moves width and height to the host element

**Comment by joelmeaders** [comment] 2019-07-02 18:45
It's odd, but if you wrap the menu button in a menu toggle it works perfectly. I was pretty annoyed when I ran into this also.
```
<ion-menu-toggle color="light">
	<ion-menu-button color="light"></ion-menu-button>
</ion-menu-toggle>
```

**Comment by brandyscarney** [comment] 2019-07-03 14:48
@joelmeaders The reason your workaround fixes it is because the `ion-menu-toggle` has the logic to hide / show based on the split pane / menu being active. The menu button has a child `ion-menu-toggle` so that is working to hide the inner button but the host element is still visible.

I moved the logic up so the `ion-menu-button` will be able to handle this for itself instead of relying on the child `ion-menu-toggle`. This will be better for accessibility too so the menu-button can get `aria-hidden` on the host element instead. Here is the PR for this: https://github.com/ionic-team/ionic/pull/18702

**Closed** 2019-07-03 15:51 UTC
Labels: package: core, type: bug
