### ISSUE TITLE
Ionic V4 - Flashing back-button on iOS with short lists

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic#17022] opened 2019-01-09 20:54 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

The toolbar icon is flashing once after navigating with back-button.
video: https://youtu.be/I25h7LRzmcg

**Expected behavior:**
No flashing :)

**Steps to reproduce:**

- Open the App on iOS or with devApp (on iOS; there is no problem in the browser!)
- Click to the list menu
- Click to "Long page", then click "back". It's OK
- Click to "Short page", this page contains only 2 ion-items, so the height less then 100% (I think this is the problem). Click "back". The menu will flash once every time when you go back.

Sample code on github: https://github.com/petrot/ionic-v4-flashing-menu-bug

**Related code:**

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.7.1 (/Users/tomi/.nvm/versions/node/v10.14.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/tomi/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.14.1 (/Users/tomi/.nvm/versions/node/v10.14.1/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by ronanjia** [comment] 2019-01-14 06:13
same _issue :(

**Comment by Frotty** [comment] 2019-01-16 08:17
Dito. If using a custom back button instead if ion-back-button the whole toolbar of the old screen stays for me when navigating back.

**Comment by mora260** [comment] 2019-01-24 15:27
I have the same problem, is a minor issue, but really annoying. Maybe something with the routing system replacement?

**Comment by dromedaryCase** [comment] 2019-01-27 09:52
I have been seeing this flickering since beta through RC releases until now.

This problem applies only to the ios mode but can be reproduced in browser and in native (Capacitor) builds. The animation glitch has nothing to do with lists of any kind.

To verify this I started a blank project with this info and added just one page to push to.

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

System:

   NodeJS : v10.14.2 (/usr/local/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

The glitch can be best observed when the "pushing" page has no ion-toolbar albeit an existing toolbar is not preventing it.

![flicker](https://user-images.githubusercontent.com/47076618/51799424-0e424500-2221-11e9-96df-8bd56b5d8101.gif)

**Comment by proartti** [comment] 2019-02-14 17:58
We are having this problem as well. It seems to only affect iOS and the previews page’s header blinks over even if the current page doesn’t have the header/toolbar.

**Comment by petrot** [comment] 2019-02-15 08:05
@proartti I have header/toolbar on each pages.. :/

**Comment by jaswantjatav** [comment] 2019-02-15 12:33
Me too facing same issue , please help to fix it.
I am switching page from tab page to details page but when come back to tabs page by click back  toolbar flashing once after navigating with back-button. 

Thanks in advance.

**Comment by bolivir** [comment] 2019-02-21 10:48
Same issue here, when navigating back from a page the toolbar flashes.

**Comment by lehtaku** [comment] 2019-02-24 22:56
Same issue here. Toolbar flashes when navigating to previous page even if it don't have toolbar in it. Have anyone find solution to this yet?

**Comment by brandyscarney** [comment] 2019-03-04 16:37
Closing as a duplicate of #16988 please track this issue there, thanks!

**Closed by brandyscarney** 2019-03-04 16:37 UTC
Labels: needs: investigation
