### ISSUE TITLE
Data Grid for Ionic 4

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionic#19433] opened 2019-09-24 06:50 UTC
Can any one implement Data Grid for Ionic 4 like Kendo UI Grid?

**Comment by liamdebeasi** [comment] 2019-09-25 12:20
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17629.

**Closed by liamdebeasi** 2019-09-25 12:20 UTC
Labels: triage

**Comment by rtpHarry** [comment] 2019-10-02 15:34
You can use Angular grids in Ionic, for example I got this working in a clients project: https://github.com/swimlane/ngx-datatable
