### ISSUE TITLE
The bug is https://github.com/ionic-team/ionic/issues/15579 occurring on ionic version 5.2.7

### ISSUE THREAD

**Issue by NomiJ** [ionic-team/ionic#19222] opened 2019-08-29 07:19 UTC
# Bug Report

**Ionic version:**
[x] **5.2.7**

**Current behavior:**
When the picker is opened the individual column items all stack on top of each other.

**Expected behavior:**
When the picker is opened the individual column stay does not stack on top of each other.

**Steps to reproduce:**
Create a simple ionic picker and click on twice.

![ionic_ui_issue](https://user-images.githubusercontent.com/8808212/63918998-2f9e3480-ca81-11e9-98df-e836e6a848d0.png)

**Related code:**
 https://github.com/NomiJ/ionic-picker-styling-issue

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.4.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm    : 6.11.2
   OS     : macOS Mojave

```

**Comment by liamdebeasi** [comment] 2019-08-29 12:58
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17664

**Closed by liamdebeasi** 2019-08-29 12:58 UTC
Labels: triage
