### ISSUE TITLE
Angular 8 and new Ionic 4.5 support on new project creation

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic#18546] opened 2019-06-14 11:14 UTC
Hi,

I have used this CLI to create a new project:

`ionic start myApp tabs --type=angular`

But still it uses ` "@ionic/angular": "^4.1.0",` and `"@angular/core": "^7.2.2",`. Can you tell me why?

My expectation here is Ionic `4.5.0` and `Angular 8+`. Is that not supported yet or?

**Comment by liamdebeasi** [comment] 2019-06-14 13:13
Thanks for the issue. This is the correct behavior. 

Angular 8 support is coming, but is not quite done yet. See: https://github.com/ionic-team/ionic/issues/18414

The caret(^) means `npm` will match the most recent minor version. So your package.json has `^4.1.0`, but it will install `4.5.0` since that is the latest minor version.

I am going to close this as this is not a bug. Thanks!

**Closed by liamdebeasi** 2019-06-14 13:13 UTC
Labels: triage
