### ISSUE TITLE
bug: Text area not auto grow with default value

### ISSUE THREAD

**Issue by pookdeveloper** [ionic-team/ionic#20045] opened 2019-12-06 10:06 UTC
# Bug Report

**Ionic version:**
![image](https://user-images.githubusercontent.com/3384734/70312979-0118be00-1815-11ea-8d77-356e2dd195af.png)

**Current behavior:**
When the text area field has a default value only expands the first time

**Expected behavior:**
Always auto growed with a default value

**Steps to reproduce:**
Use text area with default value

Example
https://stackblitz.com/edit/ionic-v4-text-area-autogrow

**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI : 5.4.9

Utility:

   cordova-res : 0.3.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   NodeJS : v12.4.0
   npm    : 6.13.2
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment] 2019-12-06 14:16
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18993. (The linked issue references a modal, but both issues seem to stem from the same bug)

**Closed by liamdebeasi** 2019-12-06 14:16 UTC
Labels: triage
