### ISSUE TITLE
Trigger area of ion-select is overlapping the whole ion-item

### ISSUE THREAD

**Issue by sneko** [ionic-team/ionic#17565] opened 2019-02-21 15:46 UTC
Hi,

I'm using Ionic 4.0 and I try to put a ion-input and ion-select side by side, like that:
```
            ion-item
              ion-input()
              ion-select(value='a')
                ion-select-option(value='a') a
                ion-select-option(value='b') b
                ion-select-option(value='c') c
                ion-select-option(value='d') d
```

But when clicking on the input it will trigger the select and the list will show up. That's the same when I tried to set `slot='start/end'` 😢 .

What is the proper way to manage that? I could force having 2 ion-item side by side but it seems not the right solution to go with.

Thank you,

**Comment by liamdebeasi** [comment] 2019-02-21 20:55
Hi there,

Thanks for opening an issue with us! I am going to close this as a duplicate of #15850.

I can confirm that this is an issue, and we will look into it. In the meantime, I'd suggest just wrapping the input and the select in a div and seeing if that works. Additionally, another community member suggested this workaround: https://github.com/ionic-team/ionic/issues/17220#issuecomment-457278020. Hope this helps! 🙂 

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-21 20:55 UTC
Labels: triage
