### ISSUE TITLE
  New Ionic + new Cordova no longer work for debugging (with livereload)

### ISSUE THREAD

**Issue by marciusbezerra** [ionic-team/ionic#13737] opened 2017-12-30 01:56 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

New Ionic + new Cordova no longer work for debugging (with livereload)

**Expected behavior:**
run normally with cordova in livereload mode

**Steps to reproduce:**

On a new computer, I installed:

* Java
* Ant
* Andrioid Studio
* NodeJs
* Ionic and
* Cordova

And after everything configured just like the Ionic documents, I created a new basic app:

`ionic start myApp tabs`

The application even runs normally, but when I go to debug:

`ionic cordova run android -lc`

I get the following message:

```
console.warn: Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
console.warn: Native: tried calling SplashScreen.hide, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
```

**Related code:**

Normal code, generated by Ionic's own standard template tabs

**Other information:**

```
cli packages: (C:\Users\marci\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : d:\AndroidSdk

Misc:

    backend : pro
```

Cordova requirements:

```
Android Studio project detected

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-26,android-25,android-24,android-23,Google Inc.:Google APIs:23
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle
```

**Comment by DoubleMalt** [comment] 2018-01-05 08:29
Same here :(

**Comment by SteveKennedy** [comment] 2018-01-19 02:13
I'm pretty sure this is related to https://github.com/ionic-team/ionic-app-scripts/issues/1354

**Comment by pistou** [comment] 2018-03-12 14:08
Still a thing 👎

**Comment by itslenny** [comment] 2018-03-17 05:25
As a workaround you can edit

```
node_modules/@ionic/app-scripts/dist/dev-server/serve-config.js
```

replace

```
exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'assets', 'www');
```

with

```
exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'app', 'src', 'main', 'assets', 'www');
```

[From this StackOverflow question](https://stackoverflow.com/questions/40815183/ionic-2-cordova-is-not-available-make-sure-to-include-cordova-js-or-run-in-a-d)

**Comment by rich186** [comment] 2018-03-21 11:14
I had the same problem and ended up downgrading from `ionic@3.20.0` to `ionic@3.18.0`. Fixed the issue.

**Comment by gaurav-chandra** [comment] 2018-03-22 08:03
Any update on this? This is very annoying.

**Comment by distante** [comment] 2018-03-30 08:06
Same here
```
cli packages: (C:\Users\myUser\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.0
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\myUser\AppData\Local\Android\sdk

Misc:

    backend : legacy
```

**Comment by SteveKennedy** [comment] 2018-03-31 00:59
I made a Cordova hook that you can add to your config.xml. It will edit the file that @itslenny  mentions above. If you don't know what Cordova Hooks are, you can find more information at https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/. I recommend adding it like this

`<hook src="scripts/fixcordova7issue.js" type="before_prepare" />`

The code for the webhook is in this gist: https://gist.github.com/SteveKennedy/a9964b291afa51f820b5d73b687eeb34

**Comment by Maevus** [comment] 2018-04-11 11:27
Still an issue with Ionic 3.20.0. 

The fix described [here on stackoverflow](https://stackoverflow.com/questions/40815183/ionic-2-cordova-is-not-available-make-sure-to-include-cordova-js-or-run-in-a-d) worked for me.

> FIX: You need go to node_modules/@ionic/app-scripts/dist/dev-server/serve-config.js and replace
> exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'assets', 'www');
> to
>exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'app', 'src', 'main', 'assets', 'www');

**Comment by msholly** [comment] 2018-04-12 21:58
@SteveKennedy This is probably the best solution, since its not always a good idea to edit anything in the node_modules folder. But I have a change to your gist. 

Line 37 should be 

`var targetFileString = "exports.ANDROID_PLATFORM_PATH = path.join('platforms', 'android', 'app', 'src', 'main', 'assets', 'www');"`

While your current code makes sense, the hook did nothing unless I changed it to above. But once changed, everything is working well in Corvoda 7.1.0. Thanks for your contribution!

**Comment by distante** [comment] 2018-04-13 12:45
While the gist and/or the suggested edit works it makes the normal `ionic serve` think it is on a device with live reload too.

**Comment by msholly** [comment] 2018-04-13 16:48
Interesting! Ultimately its a bug that will be addressed in the future by Ionic or Cordova teams, but this fix at least let me continue working on the emulator.

**Comment by giladrom** [comment] 2018-04-18 21:20
You would think that this bug would be at the top of their queue. Strange.

**Comment by fernandocode** [comment] 2018-04-23 00:09
This is a problem that should be treated as a priority because it is a **BUG**. Today I lost 3~4 hours until I get here, not to mention that when leaving the project of the repositiorio we will have to remember to edit the file.

**Comment by distante** [comment] 2018-04-23 10:56
[Here](https://github.com/ionic-team/ionic-app-scripts/issues/1354#issuecomment-383426931) says that there is a new update with the fix.

**Comment by nlzet** [comment] 2018-04-24 12:56
Yes, I believe this merged PR should solve this issue: https://github.com/ionic-team/ionic-app-scripts/pull/1407

**Comment by gubbigubbi** [comment] 2018-06-16 04:06
I imagine the team is pretty busy with the v4. I can confirm that with ionic v3.2 this is still an issue - @msholly 's instructions fix the problem. gang gang.

**Comment by wilsolutions** [comment] 2018-07-10 17:06
I'm testing ionic 4 and I have the same problem =(

**Comment by gleysonlf** [comment] 2018-08-01 22:36
I'm testing ionic 4 and I have the same problem. Now in the file "server-config.js" it looks like this:

> exports.ANDROID_PLATFORM_PATHS = [
>     path.join('platforms', 'android', 'assets', 'www'),
>     path.join('platforms', 'android', 'app', 'src', 'main', 'assets', 'www')
> ];

The warn persists.

**Comment by kodeine** [comment] 2018-08-07 22:19
im getting the same error even though my server-config.js has updated paths.

```
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.2.1
    npm               : 6.1.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

```

**Comment by maris144** [comment] 2018-08-23 13:34
I have a same problem 

My info

Ionic:

   ionic (Ionic CLI) : 4.1.1

System:

   NodeJS : v8.11.1
   npm    : 6.4.0
   OS     : Windows 10

**Comment by giuseeFG** [comment] 2018-09-04 14:47
same here

**Comment by zypro** [comment] 2018-09-05 16:39
Is there a workaround for debugging or testing faster?

**Comment by vipin-developer** [comment] 2018-10-19 07:02
I am not able to find this file what should i do
--------------------------------------------------------------------------------------------
FIX: You need go to node_modules/@ionic/app-scripts/dist/dev-server/serve-config.js
------------------------------------------------------------------------------------------------

**Comment by intersides** [comment] 2018-10-19 09:41
node_modules/@ionic does only contains 3 folders, angular, angular-toolkit and core . There is no trace of app-script

**Comment by tgirgin23** [comment] 2018-10-28 15:10
I started having the same issue when upgrading from ionic 4.0.0-beta.11 to 4.0.0-beta.12. Decided to downgrade for the time being until the next beta version.

Just had some time to upgrade to 4.0.0-beta.13, and this is still an issue.

**Comment by AniciusM** [comment] 2018-10-28 15:37
try ./node_modules/.bin/ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build

**Comment by RafaelKr** [comment] 2018-10-30 10:13
@tgirgin23 I also tried to downgrade to @ionic/4.0.0-beta.11 but for me it's not working.
I also removed node_modules, reinstalled and removed and added the platform android.

**Comment by tgirgin23** [comment] 2018-10-30 14:58
@RafaelKr Here is my ionic info (nodejs version is actually 10+, just had to switch for another project in the meantime). Hopefully this can help you.

```
✔ Gathering environment info - done!
Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.11
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 7 other plugins)

System:

   NodeJS : v9.11.1 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
   Xcode  : Xcode 9.4.1 Build version 9F2000```

**Comment by RafaelKr** [comment] 2018-10-31 09:22
@tgirgin23 thanks for sharing!

I tried to mirror your environment as close as possible, but after uninstalling `@ionic/angular-toolkit@1.0.0` it says `Error: Could not find module "@ionic/angular-toolkit" from /path/to/my/project`

```
[ERROR] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/home/rafael/.nvm/versions/node/v9.11.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.11
   @angular-devkit/build-angular : 0.7.5
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 6.1.5
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/rafael/android-sdk-linux)
   NodeJS            : v9.11.1 (/home/rafael/.nvm/versions/node/v9.11.1/bin/node)
   npm               : 5.6.0
   OS                : Linux 4.10
```

**Comment by tgirgin23** [comment] 2018-10-31 14:30
@RafaelKr Yes, I got the same error. Everything is still working fine though... weird.

**Comment by zzdumeng** [comment] 2018-11-02 01:12
I am using Ionic 4.3.0, and still got this issue.
Hope this will have high priority in ionic team.

Ionic:

   ionic (Ionic CLI)             : 4.3.0 (/Users/user/.config/yarn/global/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.13
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 6 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.9.0 (/Users/user/.nvm/versions/node/v10.9.0/bin/node)
   npm        : 6.2.0
   OS         : macOS
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by RafaelKr** [comment] 2018-11-03 14:02
## It works again!
### They just fixed it with an angular-toolkit update. Install it with
`npm i @ionic/angular-toolkit@1.1.0`

Source: https://github.com/ionic-team/angular-toolkit/blob/master/CHANGELOG.md

**Comment by tgirgin23** [comment] 2018-11-04 02:42
Installing the new ionic angular-toolkit has sadly not fixed the issue for me on 4.0.0beta15.

@RafaelKr Could you please post an ionic info so that I could compare?

**Comment by RafaelKr** [comment] 2018-11-05 09:59
@tgirgin23 nice to hear it's working! I have added my `ionic info` anyway.

**Comment by collindutter** [comment] 2018-11-09 01:33
Not sure why but transferring all my files to a fresh project worked for me too!

**Closed** 2018-11-29 15:32 UTC
