### ISSUE TITLE
bug: Programmatically focus an ion-button

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/ionic#21439] opened 2020-06-05 07:18 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
There is no .setFocus() Method on an ion-button element. The only method I found that could focus the element, was IONELEMENT.el.focus(). Unfortunately this method does not focus the button (checked with document.activeElement). Its a huge problem when trying to build an accessible app.

**Expected behavior:**
Either a .setFocus() method (like on an ion-input) or a .focus() method on the 'el' property, that focus the button correctly.

**Steps to reproduce:**
Access the button in TS Code and call the .focus() method on the 'el' property.

**Related code:**
```
@ViewChild(IonButton) button;
...
this.button.el.focus();
```

**Comment by liamdebeasi** [comment] 2020-06-05 13:43
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

Many browsers will not let you programmatically focus an element if it does not have `tabindex` on it. This is true for Ionic components including `ion-button`. To get around this, you should set `tabindex="0"` on the `ion-button`.

I created a CodePen with an example: https://codepen.io/liamdebeasi/pen/gOPbqmG

Open the console, and you should see the `ion-button` as the focused element. For more information about focusing elements, please see: https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex.

**Closed by liamdebeasi** 2020-06-05 13:43 UTC
Labels: triage

**Comment by AE1NS** [comment] 2020-06-05 14:46
This is working as expected, thank you. But theres another thing that breaks now. When I add the tabindex="0" I can focus the item programmatically but the action is not called (i.e. click event) when I press space or enter on it. When I remove the tabindex, I can tab to the ion-button (I dont understand why, because there is no tabindex) and the action is called when pressing space/enter (like a click). Is this a bug, or is there another thing I am missing?

**Comment by liamdebeasi** [comment] 2020-06-05 14:50
What browser are you testing this on? I am testing this in my CodePen, and a click event I added is being called properly.

**Comment by AE1NS** [comment] 2020-06-08 05:19
I am testing with the latest Firefox. Angular/Ionic application.
```
<ion-button (click)="onClick()" tabindex="0">TestButton</ion-button>
...
onClick() {
    alert('clicked');
}
```

Without tabindex I can move to the button with tab and call the event with enter/space when focused. With tabindex, I have two tab targets on the same button. I can tab to the button but the event is not triggered with enter/space. Then I tab again and the button is still focused (also document.activeElement is showing me ion-button again) and then the event gets triggered. Is it a bug that the button is focusable two times with tabindex?

**Comment by AE1NS** [comment] 2020-06-16 05:50
@liamdebeasi were you able to to investiagte the described behavior?

**Comment by liamdebeasi** [comment] 2020-06-16 12:47
This looks like how Firefox handles focussed buttons in the Shadow DOM. This is probably something we can improve with [delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus), but Firefox does not support this yet.

**Comment by AE1NS** [comment] 2020-06-17 05:33
Alright, thanks for the clarification.
