### ISSUE TITLE
bug: Menu does not animate open when closed without animation

### ISSUE THREAD

**Issue by nickwinger** [ionic-team/ionic#20602] opened 2020-02-24 16:19 UTC
# Bug Report

**Ionic version:**

[x] **4.11.10**

**Current behavior:**

When an ion-menu gets opened with animation and then gets closed with no animation.
Then when you open it again it does not animate...

**Expected behavior:**

Ion-Menu should open with animation when it was closed without animation

**Steps to reproduce:**

just create the sample project with a menu.
then programmtically with a click handler close the menu using it's reference with the parameter false (no animation) and then open it again.

**Related code:**
menu.close(false);
menu.open(true); // no animation

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment] 2020-02-24 16:26
Thanks for the issue. Can you try this on the latest version of Ionic Framework? (v5.0.1)

**Comment by nickwinger** [comment] 2020-02-24 16:43
Hi, yes i just tried it with that latest 5.0.1
Still is there.
I guess some CSS style properties get not resetted correctly when closing without animation.
because when you open then it pops in without animation, when you close it then with animation, after that it opens up again with animation.

So i guess something gets not resetted corretly when closing without animation, but with this shadow-dom stuff everything becomes a black box and workaround/debugging gets hard...

**Comment by liamdebeasi** [comment] 2020-02-24 16:45
Can you provide a repo with the code required to reproduce this issue? I am unable to reproduce this on Ionic Framework 5.0.1.

**Comment by nickwinger** [comment] 2020-02-24 16:52
it's pretty easy, just use the sidemenu starter project of ionic:
ionic start test sidemenu

inside app.component.html
replace
`<ion-menu contentId="main-content" type="overlay">
      <ion-content>
        <ion-list id="inbox-list">
          <ion-list-header>Inbox</ion-list-header>`

with
`<ion-menu #menu contentId="main-content" type="overlay">
      <ion-content>
        <ion-list id="inbox-list">
          <ion-list-header (click)="menu.close(false)">Inbox</ion-list-header>`

after that open the menu, click on the inbox header (the menu closes without animation) and then open the  menu again (it gets opened without animation)

**Comment by liamdebeasi** [comment] 2020-02-24 16:58
Thanks for the follow up. I am following those steps, but am unable to reproduce the behavior you are describing. Opening the menu and clicking the header does indeed close the menu without the animation, but opening it again after that is opening the menu with the animation. What browser/device are you testing this on?

**Comment by nickwinger** [comment] 2020-02-24 17:02
ok that's strange...
i use chrome version 79.0.3945.130 with the developer tools opened

**Comment by liamdebeasi** [comment] 2020-02-24 17:06
Can you provide a full repo with the code required to reproduce this issue?

**Comment by nickwinger** [comment] 2020-02-24 17:15
here is the repo:
https://github.com/nickwinger/ionicMenuBug.git

but as i have written above, it's just the little html change

**Comment by liamdebeasi** [comment] 2020-02-26 19:41
Looks like the key was testing this on Windows 10 -- Chrome for macOS does not exhibit this behavior.

Can you try the following dev build and let me know if it resolves the issue? `npm i @ionic/angular@5.1.0-dev.202002261936.11d8c14`

**Comment by nickwinger** [comment] 2020-02-27 11:51
it's working with this version, you fixed it ^^

**Comment by liamdebeasi** [comment] 2020-02-27 16:17
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/20627 and will be available in an upcoming release of Ionic Framework.

**Closed by liamdebeasi** 2020-02-27 16:17 UTC
Labels: package: core, type: bug
