### ISSUE TITLE
bug: Unable to close modal/alert/bottomsheet on back or forth navigation ionic 4 (PWA)

### ISSUE THREAD

**Issue by AkshayKanchan** [ionic-team/ionic#18801] opened 2019-07-15 11:31 UTC
# Bug Report

**Ionic version:**

[x] **4.6.2**

**Current behavior:**
In browser (Mobile & Desktop) when a modal/Alert/BottomSheet is open and user navigates back using back button on browser, the modal stays open and background page is navigated anyway. There's no official way to handle the back button event programatically.

**Expected behavior:**
Any kind of overlays/Modals should be closed on back navigation.

**Steps to reproduce:**
Open a Modal/Alert/bottomSheet and navigated back or forth from browser using browser buttons (Navigation url should be of same Application) . 

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.16.0 (/usr/bin/node)
   npm    : 6.9.0
   OS     : Linux 4.15
```

**Comment by liamdebeasi** [comment] 2019-07-15 14:15
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/15422. Feel free to follow that thread for any updates.

**Closed by liamdebeasi** 2019-07-15 14:15 UTC
Labels: triage

**Comment by AkshayKanchan** [comment] 2019-07-16 06:15
I guess its a bug not a feature request. Modal should be closed on back navigation instead of just navigating background page.
