### ISSUE TITLE
bug: ion-picker column options overlapping

### ISSUE THREAD

**Issue by pppp0836** [ionic-team/ionic#18575] opened 2019-06-19 01:33 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
AddEventListener to catch ionPickerColChange event, when a Column item changed, filter another column, but those itmes overlapping
below is screen shot
https://ibb.co/wKsPGWx

**Expected behavior:**
I try set selectedIndex = 0,still not work

**Steps to reproduce:**

**Related code:**
I have uploaded demo code to github
https://github.com/pppp0836/testPicker

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\51158\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.7.0
   OS     : Windows 10
```

**Comment by sirtobey** [comment] 2019-06-19 15:28
I have the same problem. 
```Ionic:

   ionic (Ionic CLI)             : 4.12.0 (~/.nvm/versions/node/v11.9.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (~/Android/Sdk)
   NodeJS            : v11.9.0 (~/.nvm/versions/node/v11.9.0/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.15
```

**Comment by nvahalik** [comment] 2019-06-19 18:22
Funny. I was just trying to find this issue because this is an older issue.

**Comment by pppp0836** [comment] 2019-06-20 02:01
@nvahalik  That does not fix my issue,I have tried this .

**Comment by nvahalik** [comment] 2019-06-20 02:04
@pppp0836 Not suggesting it as a fix, just noting in your ticket that this is an old issue.

**Comment by pppp0836** [comment] 2019-06-20 02:08
@nvahalik  dude,thanks anyway

**Comment by pppp0836** [comment] 2019-06-25 08:03
@liamdebeasi  Could you help me to have a look,Thank you

**Comment by liamdebeasi** [comment] 2019-06-25 13:33
Thanks for the issue! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17664. Please follow that thread for any updates regarding this issue.

I tried to find a quick workaround, but I have not been able to find something that worked reliably. I will update the thread I linked to when I have more information to share.

Thanks!

**Closed by liamdebeasi** 2019-06-25 13:33 UTC
Labels: triage
