### ISSUE TITLE
bug(animation): triggering button effect twice

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic#11054] opened 2017-04-04 23:18 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Consistently, clicking a button for navigation will show the click animation, and then after a sec show it again. (when action takes a long time, like open a new page)

**Expected behavior:**
A single click effect per click

**Steps to reproduce:**
From a menu, of `ion-list` containing `button ion-item` elements, click on one of the buttons. it will show a click effect once, and just before it opens the page it will show again.

**Other information:**
I have a video showing the issue in one case, but I can't share it publicly. Is there a way to share it with devs only?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed
```

**Comment by jgw96** [comment] 2017-04-05 16:34
Hey, thanks for opening an issue with us! You can share the video to justin@ionic.io but if you can provide a repo we could use to reproduce the issue that would be even better (:

**Comment by kensodemann** [comment] 2018-01-02 19:43
Hello! As it seems it has been a while since there was any activity on this issue I am closing it for now. Feel free to comment if you are still running into this issue.

If you are still having the issue, please be sure to include a GitHub repo with a sample application.

Thanks for using Ionic!

**Closed by kensodemann** 2018-01-02 19:43 UTC
Labels: needs info, v2
