### ISSUE TITLE
[4.0.0-rc.2] clicking on ion-back-button directly when entering page freezes application

### ISSUE THREAD

**Issue by perkka** [ionic-team/ionic#17145] opened 2019-01-17 15:01 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Navigating to a new page and then directly either swipe or click on the ion-back-button sends you back to the previous page, but the application freezes. The ion-back-button also seems to be stuck in the header as the only thing you can still click at.

**Expected behavior:**

You should be sent back to the previous page and the application should not be stuck.

**Steps to reproduce:**

Navigate to a page with router.navigateToUrl or router.navigate. Directly when entering page either swipe or click at ion-back-button in header.  ( Video here https://streamable.com/try6z )

**Related code:**

```
 //navigate to page 
public navigateToGroupPage() {
   this.router.navigateByUrl('/group');
}

---

// html of group page
<ion-header>
  <ion-toolbar>
    <ion-title>
      {{groupName}}
    </ion-title>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**Other information:**

**Ionic info:** 

```

Ionic:

   ionic (Ionic CLI)             : 4.8.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.2.2
   @angular/cli                  : 7.2.2
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 15 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v11.6.0 (/Users/Perkka/.nvm/versions/node/v11.6.0/bin/node)
   npm        : 6.5.0-next.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by paulstelzer** [comment] 2019-01-17 17:38
Closed as duplicate of https://github.com/ionic-team/ionic/issues/16449

**Closed by paulstelzer** 2019-01-17 17:38 UTC
Labels: triage
