### ISSUE TITLE
[Ionic V4-beta.12] Bug router-outlet destroyed

### ISSUE THREAD

**Issue by Anthony2539** [ionic-team/ionic#15798] opened 2018-09-28 12:09 UTC
# Bug Report

**Ionic Info**

```
   ionic (Ionic CLI)          : 4.1.2 (C:\Users\ariefolo\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.2.3
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1
```

**Describe the Bug**
In my app, i navigate between two pages.
My first page is a list of stations and my second page display details station.
For navigate to details station i use this:
```
this.router.navigate(['station'], {queryParams: station});
```
And for go back:
```
this.location.back();
```
In my detail page i get the station like this:

```
let stationObservable = this.route.queryParamMap.pipe(
      switchMap(params => {
        this.station = params["params"];
        console.log("STATION ========> "+this.station.name);
        return this.ginkoService.fetchTempsLieu(this.station.name);
      })
    );
    stationObservable.subscribe((stationAttente) =>{
   
    });
```
when I navigate several times between the two pages and change stations, sometimes the station does not change while the url has changed. At this moment i can see in the debug console
```
router-outlet destroyed
```

**Steps to Reproduce**
1. Navigate between two pages.
2. Change station
4. Sometimes the station doesn't change
5. Router-outlet destroyed

**Additional Context**
This is my route:
```
const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule', canActivate: [AuthGuard] },
  { path: 'tabs', loadChildren: './tabs/tabs.module#TabsPageModule', canActivate: [AuthGuard] },
  { path: 'station', loadChildren: './pages/station/station.module#StationPageModule', canActivate: [AuthGuard] },
  { path: 'schedule', loadChildren: './pages/schedule/schedule.module#SchedulePageModule', canActivate: [AuthGuard] }
];
```

**Comment by zuperm4n** [comment] 2018-09-29 11:10
I also have this issue on `v4.0.0-beta.11`. It occurs only if I go from the initial module that loads for my app to a different module, and then try to navigate to a route from the initial module.

i.e.
- App starts and loads Module A, showing Component 1
- Press a button and be navigated to Module B, showing Component 2
- Press the back button and come back to Module A Component 1
- Press a button to be navigated to Module A, Component 3 - but this doesnt work. The URL changes but the screen remains the same.

Occurs in Chrome when running `ionic serve`, iOS 12 iPhone X simulator, and iPhone 6S iOS 12 real device.

**Comment by lapachuka** [comment] 2018-10-02 21:36
+1

**Comment by naveedahmed1** [comment] 2018-10-03 15:58
I think Angular Router in Ionic 4 Beta 12 requires a complete review its very unstable. And navigation is the core of any applications so Angular routing should be very robust.

**Comment by lapachuka** [comment] 2018-10-13 08:13
Temporary i'm using <router-outlet> instead of <ion-router-outlet>. Don't know if it would be solution for you .

**Comment by zuperm4n** [comment] 2018-10-13 09:32
I temporarily resolved this by creating a StartupModule that is loaded when the app is opened. It shows a loading spinner whilst the user’s location is determined and then it navigates to my original start module. 

This resolves the issue for me, but only really works because I need to determine the user’s location anyway. Perhaps as a temporary work-around you could just show the splash screen in the StartupModule for one second before navigating to the original module. 

I believe you may also be able to use NavController.navigateRoute() to set the original module as the root screen to avoid the user being able to press back and find themselves back at the StartupModule.

**Comment by Chethannp** [comment] 2018-10-22 17:49
Any update on this ??

**Comment by ddsurf123** [comment] 2018-10-22 20:40
Same issue, very unstable with multiple routers router-outlet destroyed is contant issue if pulling any data from api. If simple page loads static empty no issues.

**Comment by Franky238** [comment] 2018-11-16 15:01
this issue appear if you forgot to close some html tag. for example: `ion-header`

**Comment by m0nzderr** [comment] 2018-11-25 00:42
Just upgraded from beta.11 and now my app navigation is broken :(  Any suggestion for a temporary fix ? (instead of rolling back to beta.11 :-/ )

**Comment by umberto12345** [comment] 2018-11-30 16:23
router outlet destroyed is a problem?

**Comment by mxhrtm** [comment] 2018-12-04 10:37
Same here...

**Comment by urbanjoe** [comment] 2018-12-07 14:19
+1

**Comment by paulstelzer** [comment] 2018-12-13 18:08
`router outlet destroyed` is no problem in general, it only shows that the component with the ion-router-outlet has been removed. This is normal behaviour if you use different general layouts (with sidebar / without sidebar etc).

So to take a deeper look into this issue, could someone create a repo to show the issue?

**Comment by urbanjoe** [comment] 2018-12-14 12:34
here we go:
https://github.com/sloschi/ionic-angular-routing-test

**Comment by paulstelzer** [comment] 2018-12-14 12:46
@urbanjoe could you plese tell me what I should look at? I am starting it and it's just a title there - no navigation or something like that
![firefox_2018-12-14_13-46-06](https://user-images.githubusercontent.com/20501666/50004181-9be61000-ffa6-11e8-90c5-21a047c31496.jpg)

**Comment by urbanjoe** [comment] 2018-12-14 12:49
ups, just swipe from the right.. there is the menu:
![git_screenshot_1](https://user-images.githubusercontent.com/36068556/50004280-07c87880-ffa7-11e8-8b00-13b28559df1f.png)

**Comment by paulstelzer** [comment] 2018-12-14 12:57
@urbanjoe Alright: Your issue is because of two things:
1) You are using two ion-split-panes. Here it's normal that one will be destroyed if you leave the page with it (e.g. with the tasks). 

2) You are using href, please always use routerLink and always absolute paths (this you already did)

If you doing step 2, it will work okay. For example I changed it for the object lists and then it's looking good (see gif). And if I leave the page, it's normal that router-outlet destroyed arrives because the objects list with the split-pane will be destroyed and so this log occurs
![firefox_2018-12-14_13-46-06](https://user-images.githubusercontent.com/20501666/50004667-33982e00-ffa8-11e8-8236-7ee655fc4d6b.jpg)

**Comment by urbanjoe** [comment] 2018-12-14 13:01
@paulstelzer Yes, u are right, the repo has no update to the beta 18 (routerLink) right now, but locally i already updated.

Please try to navigate between taks and object (both are childs), the the destroyed appears. If u go to a root page and then to another child page everything is ok :-/

**Comment by paulstelzer** [comment] 2018-12-14 13:04
@urbanjoe Ah okay, what you now describe is what I already created as seperate issue -> #16411

**Comment by urbanjoe** [comment] 2018-12-14 13:07
Perfect, i'll give it a shoot

**Comment by urbanjoe** [comment] 2018-12-14 13:23
@paulstelzer  Same there, router-outlet destroyed message in the console:

![dummy_test](https://user-images.githubusercontent.com/36068556/50005736-abb42300-ffab-11e8-9fca-2507323171e6.gif)

**Comment by paulstelzer** [comment] 2018-12-14 16:19
I talked with @manucorporat and he said that I am right. So I summarize it here and will close the issue because of the following:

- "router-outlet destroyed" is not a bug, it's only shows you that the component with  `<ion-router-outlet>` inside is destroying
- What are the reasons this happening? In general you are using more than one `<ion-router-outlet>`  or using `ion-tabs`. If a component will be destroyed (removed from the dom - ngOnDestroy() also calls) and there is  `<ion-router-outlet>` inside (or ion-tabs), the "router-outlet destroyed"  will be displayed in the console
- Another reason: You are using different layouts (with sidebar, then a fullscreen layout) and every contains a `<ion-router-outlet>`. If you now destroy the parent component,  "router-outlet destroyed" will be displayed in the console

But also keep in mind: 
- If you have more than one `<ion-router-outlet>` and / or more than one `<ion-split-pane>` inside your code, this can lead to some issues, we are already aware of, e.g. #16411 or #15538
- If you are using ion-tabs and you switch from tabs to another router, you will also get "router outlet destroyed" because inside the tabs, there is used another `<ion-router-outlet>` , but as said at the beginning, that is not a bad sign
- If you have only one `<ion-router-outlet>` (and no tabs) and you still get "router outlet destroyed" then you should check your routing if you destroy the ion-router-outlet for some reasons.

I hope that I described it in detail so everyone knows what happens. And as I said that you get problems, has not to do with the logs, the root cause is something else :)

And because the root cause is not "router-outlet destroyed", it's better to open a issue for every problem. So if your problem is not #16411 or #15538, please make a short search (maybe there is already an issue for) and if not, **please create a new issue and include a repo so we can check it!**

**Closed by paulstelzer** 2018-12-14 16:19 UTC
Labels: triage
