### ISSUE TITLE
feat: Mobile browser-bar (of chrome etc.) should collapse on scroll

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [ionic-team/ionic#20829] opened 2020-03-20 11:57 UTC
# Feature Request
**Ionic version:**
[x] **5**

**Describe the Feature Request**

All modern mobile browsers hide their address bar when the user scrolls down on a page.
For ionic websites, this is not happening.

**Describe Preferred Solution**
The address bar of mobile browsers should automatically hide when the user scroll down in ion-content.

Check this example, with reddit.com on the mobile chrome browser:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11556950/77161232-726d3b80-6aa9-11ea-8770-31bf93ca0f73.gif)

**Additional Context**
I know this is probably not very important, but this would be a huge jump for good looking ionic websites. Having the address bar blocking the top part of the screen (additionally to the header) makes it look old.

It was already a request on Ionic 1, and the answer was that it will be looked at with Ionic 2
https://github.com/ionic-team/ionic-v1/issues/22
I could not find any update since then.

**Comment by liamdebeasi** [comment] 2020-03-20 13:24
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19081.

**Closed by liamdebeasi** 2020-03-20 13:24 UTC
Labels: triage
