### ISSUE TITLE
bug: When the button is clicked, a border is displayed

### ISSUE THREAD

**Issue by angelofan** [ionic-team/ionic#21340] opened 2020-05-19 15:20 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

![image](https://user-images.githubusercontent.com/20255750/82343032-e59d1a80-9a24-11ea-9d75-162fe61f87d3.png)
The animation for navigating to a new page via button routing is loading, and the border is added along with the button.
Get this problem only on iOS devices.
I use Capacitor build.
```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1
```

**Expected behavior:**

Buttons should not have borders when clicked.

**Steps to reproduce:**

**Related code:**

```
<ion-button [routerLink]="['/detail']">Go</ion-button>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run                             : not installed

System:

   NodeJS : v12.13.0 (/usr/local/bin/node)
   npm    : 6.12.0
   OS     : macOS Catalina
```

**Comment by angelofan** [comment] 2020-05-19 15:46
![Screen recording video](https://user-images.githubusercontent.com/20255750/82347899-c7d2b400-9a2a-11ea-9f7a-b0740a2f3882.gif)

**Comment by angelofan** [comment] 2020-05-20 02:23
I created a [sample repository](https://github.com/angelofan/ionic-issues-21340) for this

**Comment by sergiocarneiro** [comment] 2020-05-21 03:42
That seems a standard usability feature to show the button is focused, has nothing to do with ionic.

If you want to remove it, add this to a css file:

```css
:focus {
    outline: none;
}
```

**Comment by angelofan** [comment] 2020-05-21 04:32
This affects the interface style of using ionic. The border after the button is focused should be unshow the outline in the ionic global style sheet.

For me, I add this code in `src/global.scss`
```
ion-button:focus{
  outline: none;
}
```

**Comment by angelofan** [comment] 2020-05-21 04:46
@sergiocarneiro Why is it normal if the button is not bound to a route jump? This is just the problem that appears on the button bound to the routing action.

**Comment by liamdebeasi** [comment] 2020-05-26 15:28
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20632. Please see https://github.com/ionic-team/ionic/issues/20632#issuecomment-592118144 for an explanation of the issue and a temporary workaround. Thanks!

**Closed by liamdebeasi** 2020-05-26 15:28 UTC
Labels: triage
