### ISSUE TITLE
bug: Scroll bar cannot be hidden in ionic 4 with chrome browser.

### ISSUE THREAD

**Issue by Manojdreams** [ionic-team/ionic#20391] opened 2020-02-06 07:30 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by Manojdreams** [comment] 2020-02-06 07:30
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Dreamuser\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 7.0.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.7

System:

   Android SDK Tools : 26.1.1 (C:\Users\Dreamuser\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10

**Comment by Manojdreams** [comment] 2020-02-06 07:35
Just let me know how to hide the scroll bar in the browser platform

![scrollbar](https://user-images.githubusercontent.com/48427190/73915402-4b83ed00-48e1-11ea-9d37-784e8246d4d8.png)

**Comment by NikolaPeevski** [comment] 2020-02-06 07:37
@Manojdreams Check this out, you can hide it with CSS http://jsfiddle.net/5GCsJ/954/ :)

**Comment by Manojdreams** [comment] 2020-02-06 07:39
Hi @NikolaPeevski  But in ionic 4 we cannot access the scrollbar using css. I have already tried method but it doesn't work.

**Comment by NikolaPeevski** [comment] 2020-02-06 07:46
@Manojdreams Can you provide a repo where you're trying to hide the scrollbar ?

**Comment by Manojdreams** [comment] 2020-02-06 07:55
Sorry @NikolaPeevski  I don't have access to share the repo. I am trying to hide the scroll bar in the web browsers using ionic 4 but it is not accessible. Can you tell any solution for this it will be very helpful for me.

**Comment by NikolaPeevski** [comment] 2020-02-06 07:58
@Manojdreams  Do you want to hide all scrollbars or just  the top one level one?

**Comment by Manojdreams** [comment] 2020-02-06 08:00
I need to hide all the scrollbars. I can hide it using 

`ion-content {
--overflow: hidden;
}`

but when I give like this I cannot scroll the page. I need to hide only the scrollbars in all pages.
@NikolaPeevski

**Comment by liamdebeasi** [comment] 2020-02-07 17:37
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/17685.

**Closed by liamdebeasi** 2020-02-07 17:37 UTC
Labels: triage
