### ISSUE TITLE
feat: Input Prefix and Suffix

### ISSUE THREAD

**Issue by jaipresto** [ionic-team/ionic#18089] opened 2019-04-21 09:21 UTC
Currently the only ways to do this include using Material or other libraries, and ugly css. 

The first isn't ideal and requires even more work to get rendering and styling consistent with Ionic. The second, nobody likes and isn't reliable and/or consistent across devices/browsers.

One option would be like Material: _prefix_ and _suffix_ directives that can be added to text-based elements within the mat-form-field.

The better way would be as attributes just like placeholder and color.

**Comment by liamdebeasi** [comment] 2019-04-22 12:54
Hi there,

The behavior you are describing already exists in Ionic. You can use `slots` to place icons or buttons within an item in conjunction with an input.

I created a CodePen demo of it here: https://codepen.io/liamdebeasi/pen/YMjQbZ
Here's a link to the documentation explaining more: https://ionicframework.com/docs/api/item#item-placement

Does this resolve your issue?

**Comment by jaipresto** [comment] 2019-04-22 14:38
Of course - Thanks! I've just tried it with other text-based elements (including ion-text) and it works nicely. But the documentation should be better on this, like specifically using the terms _prefix_ and _suffix_ in, say, the ion-input section or something.

**Comment by liamdebeasi** [comment] 2019-04-22 17:50
Hi there,

Thanks for the feedback. The "prefix" and "suffix" terms appear to be specific to Angular Material. We use the terms `slots` since that is what they are called in the Web Components spec: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot.

I'm glad the `slots` solution is working! I am going to close this as the issue is resolved.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-22 17:50 UTC
Labels: triage
