### ISSUE TITLE
IOS - Failure while building the project environment

### ISSUE THREAD

**Issue by royibernthal** [ionic-team/ionic#12192] opened 2017-06-28 14:35 UTC
Packaging for IOS used to work fine for me until yesterday, which reminds me a bit of https://github.com/ionic-team/ionic-cloud/issues/32.

`ionic serve` and `ionic cordova run android --device` work without problems.

**ionic package info 15 --verbose**

> [DEBUG] Loading global plugin @ionic/cli-plugin-proxy
> [DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy
> [DEBUG] Loading local plugin @ionic/cli-plugin-cordova
> [DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
> ✔ Retrieving information about build 15 - done!
> 
> id       | 15
> status   | FAILED
> platform | iOS
> mode     | debug
> profile  | dev
> started  | 2017-06-27T17:47:17.050Z
> finished |
> 
> output:
> Failure while building the project environment

I'm guessing the problem could be this line?

> [DEBUG] Throwing PLUGIN_NOT_INSTALLED for global @ionic/cli-plugin-proxy

**ionic info**

> global packages:
> 
>     @ionic/cli-utils : 1.4.0
>     Cordova CLI      : 7.0.1
>     Ionic CLI        : 3.4.0
> 
> local packages:
> 
>     @ionic/app-scripts              : 1.3.8
>     @ionic/cli-plugin-cordova       : 1.4.0
>     @ionic/cli-plugin-ionic-angular : 1.3.1
>     Cordova Platforms               : android 6.2.3 ios 4.4.0
>     Ionic Framework                 : ionic-angular 3.1.1
> 
> System:
> 
>     Node       : v6.9.5
>     OS         : Windows 10
>     Xcode      : not installed
>     ios-deploy : not installed
>     ios-sim    : not installed
>     npm        : 3.10.10

**Comment by jgw96** [comment] 2017-06-28 14:52
Hello! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic-cloud/issues/223

**Closed by jgw96** 2017-06-28 14:52 UTC
