### ISSUE TITLE
Virtual Scroll does not refresh when the array of datas is emptied

### ISSUE THREAD

**Issue by RomainFallet** [ionic-team/ionic#12159] opened 2017-06-26 18:08 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.4.2**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

The virtual scroll list does not refresh the displayed elements when the array of datas is emptied.
![virtal-scroll-bug](https://user-images.githubusercontent.com/6952638/27553546-90088214-5aab-11e7-94f6-f3a2855b6fbe.gif)

**Expected behavior:**

The virtual scroll list must behave like a normal list and refresh the view when the array of datas is changing.

**Steps to reproduce:**
HomePage
```javascript
import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';

@IonicPage()
@Component({
    selector: 'page-home',
    templateUrl: 'home.html'
})
export class HomePage {

    products = ['test1', 'test2', 'test3', 'test4', 'test5'];
    constructor() {}

    emptyList(): void {
        this.products = [];
    }
}
```

HomePageTpl
```html
<ion-content>
    <ion-row>
        <ion-col>
            <h2>Virtual list</h2>
            <ion-list [virtualScroll]="products">
                
                <ion-item *virtualItem="let product">
                    {{ product }}
                </ion-item>
            
            </ion-list>
        </ion-col>
        <ion-col>
            <h2>Normal list</h2>
            <ion-list>
                
                <ion-item *ngFor="let product of products">
                    {{ product }}
                </ion-item>
            
            </ion-list>
        </ion-col>
    </ion-row>
    <button ion-button (click)="emptyList()">Empty my list</button>
</ion-content>
```

**Related code:**
Here is a repo that show this behavior :
https://github.com/RomainFallet/ionic-virtual-scroll-bug

**Comment by masimplo** [comment] 2017-06-26 18:12
Duplicate of #12034

**Comment by Simpler1** [comment] 2017-06-26 21:05
And a duplicate of [#7210](https://github.com/ionic-team/ionic/issues/7210)

**Comment by jgw96** [comment] 2017-06-27 14:53
Hello all. Closing this as a duplicate of https://github.com/ionic-team/ionic/issues/12034

**Closed by jgw96** 2017-06-27 14:53 UTC
