### ISSUE TITLE
platform.registerBackButtonAction()  problem in Android browser 

### ISSUE THREAD

**Issue by qtzheng** [ionic-team/ionic#11938] opened 2017-06-06 09:00 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
1、create app: ionic start MyIonicProject tabs
1、app.component.ts
export class MyApp {
    constructorprivate platform: Platform) {
        this.platform.registerBackButtonAction(()=>{
            alert('1');
        },10000);
    }
}
2、build this app for browser platform: ionic build browser
3、publish
4、run this app with browser,when I click  the back button,it didn't work

**Comment by jgw96** [comment] 2017-06-06 16:30
Hello, thanks for opening an issue with us. Could you provide a repo we could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-06-13 15:29
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-06-13 15:29 UTC
Labels: needs info, v3
