### ISSUE TITLE
There's no way to use gesture events in ionic5.x

### ISSUE THREAD

**Issue by phonegap100** [ionic-team/ionic#21374] opened 2020-05-26 10:14 UTC
There's no way to use gesture events in ionic5.x。

How to use tap press rotate pinch in ionic5.x?

Hammerjs can be used in ionic4.x but not in ionic5.x

```
<ion-button (tap)="goBack()">
        <ion-icon slot="icon-only" name="arrow-back" color="dark"></ion-icon>
  </ion-button>

```

**Comment by liamdebeasi** [comment] 2020-05-26 12:55
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. HammerJS does not come pre-loaded with Ionic Framework anymore. You will need to install and configure it yourself in your application.

**Closed by liamdebeasi** 2020-05-26 12:55 UTC
Labels: triage
