### ISSUE TITLE
Background scrollable while sliding Side Menu

### ISSUE THREAD

**Issue by felix9607** [ionic-team/ionic#13354] opened 2017-11-08 10:03 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While sliding a Side Menu, it's still possible to scroll the current page. This feels and looks wiered sometimes. This behavior occured for me on devices (android/ios) only.

**Expected behavior:**
As soon as the Side Menu begins to slide, the current page should be looked or sth similiar.

**Steps to reproduce:**
Works with the simplest side menu of ionic.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\SCHUL256\AppData\Roaming\npm\node_modules)

    @ionic/cli-plugin-proxy : 1.4.12
    @ionic/cli-utils        : 1.13.0
    ionic (Ionic CLI)       : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.7.1

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : pro
```

**Comment by kensodemann** [comment] 2017-11-08 12:16
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #13282. Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.  Thank you for using Ionic

The only difference I see is that #13282 does not occur on Android. If you could provide a sample app via GitHub where this occurs also in Android that would be very helpful. I will also re-test #13282 on an Android device when I get a chance just to make sure.

**Closed by kensodemann** 2017-11-08 12:16 UTC
