### ISSUE TITLE
bug: Autofocus not working in Chrome 79 when using fragments (useHash: true)

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic#20318] opened 2020-01-28 10:52 UTC
# Bug Report

**Ionic version:**
Latest

**Current behavior:**

Using `autofocus` attribute on `ion-input` or any other `input` element results in chrome throwing this log: `Autofocus processing was blocked because a document's URL has a fragment`

**Expected behavior:**

Correctly focus the element with `autofocus `attribute

**Steps to reproduce:**

Create a basic app with `ion-input` with `autofocus="true"` and `useHash: true` for the `RouterModule`. Open in latest Chrome

**Comment by liamdebeasi** [comment] 2020-01-28 15:02
Thanks for the issue. I was able to reproduce this outside of Ionic Framework, so it looks like a new behavior in Chrome 79. I have opened an issue on the Chromium bug tracker and will post an update here when I have more info.

**Comment by liamdebeasi** [comment] 2020-02-04 14:04
I am going to close this issue as it is currently being handled by the Chromium team. 

To summarize, this behavior appears to be part of the HTML specification; however, there is discussion about potentially changing this functionality. You can follow the thread here: https://bugs.chromium.org/p/chromium/issues/detail?id=1046357

Thanks!

**Closed by liamdebeasi** 2020-02-04 14:04 UTC
Labels: triage
