### ISSUE TITLE
Multiple clickable controls inside ion-item don't work as expected

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic#17220] opened 2019-01-23 07:27 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

 When there are two controls, ion-select and ion-button inside ion-item clicking on ion-button will always open ion-select control.

**Expected behavior:**

Clicking on a button should trigger the button handler and clicking on the ion-select should trigger opening this select

**Steps to reproduce:**

1) create new blank app using
```
ionic start myApp blank
```
2) replace the ion-content in the  main Home.html template to be as below
```
<ion-content padding>
  <ion-item>
    <ion-label position="stacked">
      TEST
    </ion-label>
    <ion-select placeholder="Select One">
      <ion-select-option value="f">Female</ion-select-option>
      <ion-select-option value="m">Male</ion-select-option>
    </ion-select>
    <ion-button slot="end" color="primary" (click)="test();">
      TEST
    </ion-button>
  </ion-item>
</ion-content>
```
3) add a test handler function inside Home.ts
4) run the app and click on TEST button
Note that it will ALWAYS open a select dialog and will never invoke test function

**Related code:**
See above

StackBlitz (https://stackblitz.com)
```
StackBlitz does not support the latest Ionic v4 releases - see https://github.com/ionic-team/ionic/issues/16354
```

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.5.0 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.14.2 (/Users/alexryltsov/.nvm/versions/node/v10.14.2/bin/node)
   npm    : 6.5.0
   OS     : macOS Mojave
```

**Comment by paulstelzer** [comment] 2019-01-23 10:45
Thanks for the issue! I can confirm this issue. The question is: Should a button allowed in ion-item if there is an ion-select or not

**Comment by ryaa** [comment] 2019-01-23 12:00
My use case is that there is select/combo box with the button next to it allowing to reset/clear the selection. I thought that the optimal layout would be to have the both ion-select and ion-button (with slot="end) inside the same ion-item.

Please note that as a workaround, to make the button to work, I added z-index: 10 to it which enabled the button handler for the layout that I added in the initial post above.

Thank you

**Comment by zakton5** [comment] 2019-01-24 17:11
I had this issue with `ion-datetime` @ryaa. As a quick workaround, you might be able to set the `position` of the ion-select in the scss. This has the downside of making the select not open if you click the label.

```scss
ion-select {
  position: relative;
}
```

**Comment by liamdebeasi** [comment] 2019-02-13 14:16
Hi there,

Thanks for opening an issue with us! I am going to close this as a duplicate of: #15850

Please note the referenced issue has been consolidated in to a master list here: https://github.com/ionic-team/ionic/issues/16630

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-13 14:16 UTC
Labels: needs: design decision, package: core
