### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by adviraj** [ionic-team/ionic#18198] opened 2019-05-04 11:51 UTC
<ion-row>

     <ion-col size="6">

      <ion-item>

        <ion-label> Color</ion-label>

        <ion-select value="brown" okText="Okay" cancelText="Dismiss" (ionChange)="checks()">

          <ion-select-option value="brown">Brown</ion-select-option>

          <ion-select-option value="blonde">Blonde</ion-select-option>

          <ion-select-option value="black">Black</ion-select-option>

          <ion-select-option value="red">Red</ion-select-option>

        </ion-select>

      </ion-item>

     </ion-col>

     <ion-col size="6">

      <ion-item>

        <ion-label>Well Color</ion-label>

        <ion-select #selects value="1" [(ngModel)]="ddddd" okText="Okay" cancelText="Dismiss" >

              <ion-select-option*ngFor="let x of data" value="{{x}}">
                 {{x}} </ion-select-option>

        </ion-select>

      </ion-item>

    </ion-col>

   </ion-row>

when I am fire checks() method then I data variable values changed ion-option is updating I can see in HTML inspect but alert still showing old values after the change event second ion-select show [1,2,3,4,5] but i was showing old values in alert.

**Comment by adviraj** [comment] 2019-05-06 06:29
I am still waiting for response but didn't get
please let me know

**Comment by adviraj** [comment] 2019-05-06 06:30
how can i resolve this issues?

**Comment by liamdebeasi** [comment] 2019-05-06 13:11
Hi there,

Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/16453. 

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-06 13:11 UTC
Labels: triage
