### ISSUE TITLE
ionic  angular4.1.2 Place multiple < ion-slides > pages to find bugs

### ISSUE THREAD

**Issue by lccWEBApp** [ionic-team/ionic#17859] opened 2019-03-22 02:06 UTC
**Description:**

**Steps to Reproduce:**

When two < ion-slides > slides are placed on the page, even if I bind one of them (ionSlide DidChange), rolling any one of them will execute (ionSlide DidChange). Please improve this problem.

**Output:**

**My `ionic info`:**

```
<paste here>
```Ionic:

   ionic (Ionic CLI)             : 4.10.2 (D:\npmConfig\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : not available



**Other Information:**
<!--
e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links,
forum links, etc
-->

**Comment by liamdebeasi** [comment] 2019-03-22 20:13
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by lccWEBApp** [comment] 2019-03-28 01:46
> 嗨，您好，
> 
> 谢谢你的问题。您是否可以提供存储库以及重现此问题所需的代码？
> 
> 谢谢！

My program   HTML 

![qqq](https://user-images.githubusercontent.com/39893766/55123449-99ff2180-513d-11e9-9b9f-e7f20e38fe03.png)

When I Slide either of the two clocks<ion-slides>  (ionSlideDidChange)="onSlideDidChange()"  trigger，But the second<ion-slides>No  (ionSlideDidChange)  Slide  same trigger onSlideDidChange()，This is a headache

**Comment by liamdebeasi** [comment] 2019-03-29 12:47
Hi there,

Thanks for the follow up. Unfortunately, a sceenshot of your HTML does not give me a lot of insight into how your application is set up. It would be great if you could post a repository with a basic application that shows this bug happening.

Thanks!

**Comment by lccWEBApp** [comment] 2019-04-01 09:36
> 嗨，您好，
> 
> 感谢您的跟进。不幸的是，HTML的一个场景并没有让我对你的应用程序的设置方式有很多了解。如果您可以使用显示此错误的基本应用程序发布存储库，那将是很棒的。
> 
> 谢谢！

Hello！My program did not report errors    So let me ask from a different angle. When my HTML Above  Placed  Two <ion-slides>  As shown below
![image](https://user-images.githubusercontent.com/39893766/55317999-49bcf200-54a4-11e9-8650-834894655dcb.png)

The cause of my headache  Scroll one of them  <ion-slides>  ionSlideDidChange  Triggered twice，Please help me to answer the correct way to use it.

**Comment by liamdebeasi** [comment] 2019-04-01 13:41
Hi there,

Can you post the contents of the TypeScript `.ts` file for this page?

Thanks!

**Comment by lccWEBApp** [comment] 2019-04-02 09:13
> 嗨，您好，
> 
> 你可以发布`.ts`这个页面的TypeScript 文件的内容吗？
> 
> 谢谢！

Here's mine  ts

![4545455](https://user-images.githubusercontent.com/39893766/55390460-d978a400-5569-11e9-98e1-0307b6215b58.png)
Red marking   Only in one.  <ion-slides>  binding    Not monitored<ion-slides> It also triggers ionSlideDidChange   
Can't I have more than two < ion-slides > on my HTML？

**Comment by liamdebeasi** [comment] 2019-04-02 13:13
Hi there,

Thanks for the follow up. I am still unable to reproduce the issue you are seeing. When I slide the first slider, the `onSlideDidChange` method is called like I would expect. Sliding the second slider does not call `onSlideDidChange` as I would expect as well.

Like I mentioned previously, a full reproduction of the bug you are seeing would be very incredible useful. Otherwise, the help I am able to give will be limited.

In regards to your last point, you can have more than one `ion-slides` on a page. I would also recommend double checking your code to ensure things were implemented properly.

Thanks!

**Comment by lccWEBApp** [comment] 2019-04-03 03:37
> 嗨，您好，
> 
> 感谢您的跟进。我仍然无法重现您所看到的问题。当我滑动第一个滑块时，该`onSlideDidChange`方法被调用，就像我期望的那样。滑动第二个滑块不会`onSlideDidChange`像我期望的那样调用。
> 
> 就像我之前提到的，你看到的bug（通过GitHub repo）的完整复制将非常有用。否则，我能给予的帮助将是有限的。
> 
> 关于你的最后一点，你可以`ion-slides`在一个页面上有多个。我还建议仔细检查您的代码，以确保正确实施。
> 
> 谢谢！

Thank you for your patient explanation.  I reviewed my code again. The problem arises as follows
HTML
 
![image](https://user-images.githubusercontent.com/39893766/55451082-05e0fe80-5604-11e9-8c28-50a869cc442b.png)

TS 
![image](https://user-images.githubusercontent.com/39893766/55451117-35900680-5604-11e9-8f0f-094f0d4fa91f.png)

When I slide  id="slides1"   id="slides2"   Will trigger  id="father"  ionSlideDidChange，
My program is  Nested  <ion-slides>

**Comment by liamdebeasi** [comment] 2019-04-08 15:22
Hi there,

Thanks for the update. We do not currently support nested `ion-slides`.

I am going to close this, but if you would like to see this in a future version of Ionic, feel free to [open a Feature Request](https://github.com/ionic-team/ionic/issues/new?assignees=&labels=&template=feature_request.md&title=feat%3A+).

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-08 15:22 UTC
Labels: triage
