### ISSUE TITLE
bug: URGENT- Blocks software update - Menu disappear when navigate between multiple menus

### ISSUE THREAD

**Issue by yjacques940** [ionic-team/ionic#19280] opened 2019-09-05 18:16 UTC
# Bug Report

**Ionic version:**

[x] **4.8**
### It blocks my next ionic update for my mobile app. I need a fast Bug Fix on this.
**Current behavior:**

I have a left side menu(menu 1). When I click on one of the buttons in the menu, it brings me to another page with a different menu (menu 2). I can navigate in this menu (menu 2)(what it suppose to do.) In this menu, I'm having a 'back' button to return to the last page (which contains menu 1). When I click on this button, we back to the page of the menu 1, **but the menu disappear and we can't open it in any ways.** When I refresh the page, the menu 1 is back and everything is Ok.
   
**Expected behavior:**

When I click on menu 2 'back' button to return to menu 1, it returns and shows the first menu correctly, then we can click on 'go to menu 2' etc.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\yannick.jacques\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.2.2
   @angular/cli                  : 8.2.2
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.3.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment] 2019-09-05 19:24
Thanks for the issue. Please try this again on Ionic 4.9.0.

**Comment by iamkinetic** [comment] 2019-09-05 19:41
Unless I've misunderstood, I believe this is the same bug I have since the end of july: 
* My issue : https://github.com/ionic-team/ionic/issues/18974
* Bug repo: https://github.com/iamkinetic/ionic4-multiple-menus-bug
I guess @yjacques940 could confirm if this is indeed the same bug.

I've first discovered that issue when I updated to Ionic 4.7.0.  I've tried Ionic 4.9 yesterday and the issue is still there.  I've just push the ionic 4.9 update in my bug reproduction repository so you can reproduce it.

I thought i had found a workaround, but it's not working as good as I first thought, so I'm also waiting for a true fix so I can go ahead and update my applications that currently have that issue.

**Comment by yjacques940** [comment] 2019-09-05 20:27
I've tried v4.9 and nothing has changed. I tried @iamkinetic repo, the navigation is different but the bug is the same.

**Comment by liamdebeasi** [comment] 2019-09-05 20:29
@yjacques940 Thanks for the follow up. Just so I understand, are you saying this bug is the same as https://github.com/ionic-team/ionic/issues/18974?

**Comment by yjacques940** [comment] 2019-09-05 20:29
Yes.

**Comment by liamdebeasi** [comment] 2019-09-05 20:31
Ok great, thanks for the follow up. In that case I'm going to close this issue in favor of https://github.com/ionic-team/ionic/issues/18974, but I will be sure to link the two issues. I'm going to dig into this and see what I can find.

Thanks!

**Closed by liamdebeasi** 2019-09-05 20:31 UTC
Labels: triage
