### ISSUE TITLE
ionic4 autocomplete component missing

### ISSUE THREAD

**Issue by sivakumar55** [ionic-team/ionic#17440] opened 2019-02-08 14:25 UTC
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by bossjon** [comment] 2019-02-10 18:04
duplicate of [#17181](https://github.com/ionic-team/ionic/issues/17181)

**Comment by liamdebeasi** [comment] 2019-02-15 13:58
I am going to close this as a duplicate of #17181. Thanks for using Ionic!

**Closed by liamdebeasi** 2019-02-15 13:58 UTC
Labels: triage
