### ISSUE TITLE
Navbar overlays statusbar

### ISSUE THREAD

**Issue by jbw91** [ionic-team/ionic#13144] opened 2017-10-14 04:01 UTC
**Ionic version:**  (check one with "x")
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I upgraded to 3.7.1 from 3.6.0 and noticed that the toolbar on iOS now overlaps the statusbar. Image below:

![img_1463](https://user-images.githubusercontent.com/5883616/31572242-63d3f418-b05e-11e7-9c62-46591a5fdbb7.jpg)

**Expected behavior:**

The toolbar should not overlap the statusbar. Image below shows how it should be. (from before upgrading)

![img_1464](https://user-images.githubusercontent.com/5883616/31572267-2d3247a6-b05f-11e7-8243-3e75e30cfbcc.jpg)

**Steps to reproduce:**

I upgraded from 3.6.0 to 3.7.1.

**Ionic info:**

```
cli packages: (/path/to/app/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2
    Node       : v7.10.1
    npm        : 5.4.2
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235

Misc:

    backend : pro
```

**Comment by kensodemann** [comment] 2017-10-16 15:17
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by levesquejf** [comment] 2017-10-17 01:24
Hello! I have the same issue with the "tabs" starter project. To reproduce:

`$ ionic start my-tabs tabs`
`$ cd ./my-tabs`
`$ ionic lab`

If I open the lab url with Safari (v11.0), I have the issue:

<img width="401" alt="screen shot 2017-10-16 at 21 21 15" src="https://user-images.githubusercontent.com/28109127/31642252-00a9366c-b2b8-11e7-9943-a61c3593d57b.png">

However, if I open the lab url with Chrome (v61.0.3163.100), no issues:

<img width="401" alt="screen shot 2017-10-16 at 21 22 35" src="https://user-images.githubusercontent.com/28109127/31642282-2a6d86d8-b2b8-11e7-8d7e-0b72abecd9a4.png">

I tested with Ionic view and I have the issue on iPhone 7 IOS v11.0.3.

**Comment by jbw91** [comment] 2017-10-17 02:22
@kensodemann I can confirm that this happens with a newly started project as demonstrated by @levesquejf

**Comment by TehCrucible** [comment] 2017-10-17 07:57
Just wanted to chime in and confirm that we've noticed the same issues on 3.7.1 but only after updating to iOS 11.  I assume that's relevant.

I have a hunch these are also related:  #13152 #13160

**Comment by ThomasKientz** [comment] 2017-10-17 08:08
I experienced the exact same issue.

**Comment by gigocabrera** [comment] 2017-10-17 12:53
I opened [issue 24](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/24) and it looks like it is happening on ALL projects (existing and new) after upgrading to WKWEBVIEW and iOS 11. Screenshots below are from an iPhone 7 plus

**Conference app**

![wkwebview_03](https://user-images.githubusercontent.com/6364855/31665717-ca33846a-b317-11e7-8241-69e68ccd0d3c.jpg)

<br>
<br>
<br>
Tabs starter app
<br>

![wkwebview_02](https://user-images.githubusercontent.com/6364855/31665716-c89d6c24-b317-11e7-86e2-13ac0fbffa46.jpg)

**Comment by hugodes** [comment] 2017-10-17 14:00
#13054

**Comment by mhartington** [comment] 2017-10-17 14:44
Thank you for the issue report. So there are a few things happening here...

1) The statusbar padding being off in safari/ionic-lab but not in chrome.

The new releases of Ionic (3.7 and up) use the css constant/env features in iOS/Safari. This is how we can properly size the header on iOS 11 and iPhone X without any issues. Since this is supported in Safari, it just happens to work in lab, but is set to 0. Will have to fix this on the Lab side of things.


2) App deployed to Device/sim not sized correctly.

This Im not able to recreate myself actually. I have started a blank tabs app, upgraded to the latest nightly build of `ionic-angular` (which includes more ios11 list fixes) and deployed to iPhone-7-Plus and it works as expected. This includes the latest WKWebview as well.

![screen shot 2017-10-17 at 10 39 22 am](https://user-images.githubusercontent.com/2835826/31671465-0e8b0fce-b328-11e7-9794-9ea8ef069616.png)


If someone can provide a clear list of steps or starter project that can recreate this issue, that would be great.

**Comment by gigocabrera** [comment] 2017-10-17 14:55
@mhartington you mentioned you upgraded to the latest nightly build. What do I need to do to upgrade to the latest nightly build? If that doesn't fix the issue I can give you access to my private repo where you should be able to recreate it

> upgraded to the latest nightly build of ionic-angular (which includes more ios11 list fixes)

**Comment by mhartington** [comment] 2017-10-17 15:02
`npm i ionic-angular@nightly @ionic/app-scripts@nightly`

**Comment by gigocabrera** [comment] 2017-10-17 15:51
@mhartington I'm getting all kinds of errors after I upgraded to latest nightly. Let me give you access to my  repo. 
https://github.com/gigocabrera/LiveVault

**Comment by mhartington** [comment] 2017-10-17 16:23
Those are mostly lint errors.

I was able to run your app without any issues.
![screen shot 2017-10-17 at 12 19 48 pm](https://user-images.githubusercontent.com/2835826/31676556-01851ed8-b336-11e7-81fe-61d907c25eef.png)

And everything worked as expected.

**Comment by gigocabrera** [comment] 2017-10-17 16:41
@mhartington are you running ionic 4? or ionic 3?

**Comment by gigocabrera** [comment] 2017-10-17 16:47
I'm getting this error

```
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

```
```
http://localhost:8101/build/vendor.js:95445:16
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/vendor.js:155238:43
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/vendor.js:155057:43
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/vendor.js:46089:98
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/vendor.js:69713:84
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/main.js:4629:100
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/main.js:4368:93
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
http://localhost:8101/build/main.js:4338:89
__webpack_require__@http://localhost:8101/build/vendor.js:55:34
webpackJsonpCallback@http://localhost:8101/build/vendor.js:26:42
global code@http://localhost:8101/build/main.js:1:13

```

```
Ionic Framework: ^3.7.1-201710101557
Ionic App Scripts: 3.0.0-201710161925
Angular Core: 4.4.4
Angular Compiler CLI: 4.4.4
Node: 8.5.0
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
```

**Comment by jbw91** [comment] 2017-10-17 17:13
I have a public repo that has this issue: https://github.com/jbw91/toolbar-issue

Here's my environment info from running `ionic info`:

```
cli packages: (/Users/john/dev/ionic/toolbar-issue/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    Node       : v7.10.1
    npm        : 5.4.2 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0.1 Build version 9A1004 

Misc:

    backend : pro
```

Here is a screenshot from my iPhone 7 Plus device I ran it on using `ionic cordova run ios --livereload`

![img_1473](https://user-images.githubusercontent.com/5883616/31678466-81e47a20-b32b-11e7-90bc-e4ffd2f4e099.PNG)

And here is a screenshot of me running it in an emulator after building the project with `ionic cordova build ios`

![screen shot 2017-10-17 at 11 12 41 am](https://user-images.githubusercontent.com/5883616/31678713-3ba2f856-b32c-11e7-82db-36b387d755ec.png)

**Comment by mhartington** [comment] 2017-10-17 18:02
@jbw91  Your app was missing several important things.

1) Viewport fit: you're viewport meta tag is missing `viewport-fit=cover` 
2) Statusbar plugin: You're using the older plugin which does not contain fix required

This is cover in the [iOS 11 Checklist blog post](http://blog.ionic.io/ios-11-checklist/)

Updating those 2 things produces this.

<img width="535" alt="screen shot 2017-10-17 at 2 02 06 pm" src="https://user-images.githubusercontent.com/2835826/31680939-cd99dc9a-b343-11e7-90d0-a138d6698781.png">

**Comment by jbw91** [comment] 2017-10-17 19:10
Yep that was it. I was just following the Ionic CHANGELOG, didn't see the blog post. Good to know. Thanks.

**Comment by gigocabrera** [comment] 2017-10-17 19:14
@mhartington 

1. I was able to build my app with the latest
npm i ionic-angular@nightly @ionic/app-scripts@nightly
2. Reinstalled the Statusbar plugin to make sure I was not using the old one
3. Deployed to device and still get the same issue

I know it worked for you but could it be something in my environment?

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0-201710161925
    Cordova Platforms  : ios 4.5.2
    Ionic Framework    : ionic-angular 3.7.1-201710101557

System:

    ios-sim : 4.1.1
    Node    : v8.5.0
    npm     : 2.15.12
    OS      : OS X El Capitan
    Xcode   : Xcode 8.2.1 Build version 8C1002

Misc:

    backend : legacy
```

**Comment by mhartington** [comment] 2017-10-17 19:14
Awesome, closing then as this was the original issue/poster.
If anyone is have other issues, please open a **new** issue.

**Closed** 2017-10-17 19:13 UTC
Labels: iOS 11, needs info, needs reply

**Comment by mhartington** [comment] 2017-10-17 19:24
@gigocabrera Please use the statusbar from github/master.
Make sure you have **everything** in the ios 11 checklist blog post covered.

I'm not able to replicate it at all on my end.
