### ISSUE TITLE
ion-fab in tab bar 'edge' position incorrect

### ISSUE THREAD

**Issue by Frotty** [ionic-team/ionic#17130] opened 2019-01-16 08:48 UTC
# Bug Report

**Ionic version:**
[x] **4-beta1.9** (also tried with rc1)

**Current behavior:**
The fab button sits between the footer and the bottom of the screen

**Expected behavior:**
The fab button should sit between footer and content, like it used to

**Steps to reproduce:**
Use 'edge' on a fab button inside a tab bar

**Related code:**

```
<ion-tabs class="tab-fullwidth">
  <ion-fab vertical="bottom" horizontal="end" slot="fixed" edge>
    <ion-fab-button>
      <ion-icon name="add">
      </ion-icon>
    </ion-fab-button>
    <ion-fab-list side="top">
    </ion-fab-list>
  </ion-fab>
    
  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="home">
      <ion-icon name="home"></ion-icon>
      <ion-label>Home</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="myEvents">
      <ion-icon name="calendar"></ion-icon>
      <ion-label>Meetings</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="myMoots">
      <ion-icon name="logo-buffer"></ion-icon>
      <ion-label>moots</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="">
    </ion-tab-button>

  </ion-tab-bar>
</ion-tabs>
```

**Other information:**
This used to work fine back with beta 13 or so, having the FAB between content and footer. Only due to a recent update the position is now wrong.

![](https://i.imgur.com/Ilfjnt3.png)

If I put it into the home page, the position seems correct, but it's rendering behind the tab bar:

![](https://i.imgur.com/gCqtZUn.png)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.8.0 (/Users/run-e/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.19
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.2.1
   @angular/cli                  : 7.2.1
   @ionic/angular-toolkit        : not installed

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.9.2
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by abennouna** [comment] 2019-01-16 10:51
Duplicate of #16780 — fixed by #17048

**Closed** 2019-01-16 11:02 UTC
Labels: triage
