### ISSUE TITLE
bug: ion-textarea spellcheck is behind iOS keyboard

### ISSUE THREAD

**Issue by patrickbussmann** [ionic-team/ionic#18798] opened 2019-07-14 23:01 UTC
# Bug Report

**Ionic version:**
[x] **4.3.2**

**Current behavior:**
The spellcheck of iOS device on ion-textarea is visible behind the real keyboard.

**Expected behavior:**
The spellcheck is placed at right position.

**Steps to reproduce:**
Write something wrong in the ion-textarea.

**Related code:**
```
<ion-footer>
  <ion-toolbar no-border>
    <div class="toolbar">
      <div class="input-block">
        <ion-textarea #messageInput spellcheck="on" autocomplete="on" autocorrect="on" auto-resize [(ngModel)]="msg" rows="1" placeholder="Enter a message"></ion-textarea>
        <ion-buttons right class="button-submit">
          <ion-button type="submit" [disabled]="!msg.length" fill="clear" size="small" color="primary">
            Send
          </ion-button>
        </ion-buttons>
      </div>
    </div>
  </ion-toolbar>
</ion-footer>
```

**Ionic info:**

```
[ERROR] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'

Ionic:

   Ionic CLI                     : 5.2.1 (C:\Users\Patrick\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : not installed

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.2
   Cordova Plugins   : no whitelisted plugins (2 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.7.0
   OS     : Windows 10
```

![IMG_3284](https://user-images.githubusercontent.com/15617021/61190406-0de91980-a69c-11e9-8c69-9e8d9993e783.jpg)

**Comment by liamdebeasi** [comment] 2019-07-19 13:22
Thanks for the issue. Are you seeing this on a browser or when running in Cordova/Capacitor? If Cordova/Capacitor, are you using the Ionic Keyboard Plugin?

**Comment by patrickbussmann** [comment] 2019-07-19 13:50
Hi @liamdebeasi, this is on iOS device on a app built with Cordova.
I'm using:

```xml
    <plugin name="cordova-plugin-ionic-webview" spec="^4.1.1" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.3" />
```

**Comment by liamdebeasi** [comment] 2019-07-19 16:33
Thanks for the follow up. I was able to reproduce this outside of Ionic: https://codepen.io/liamdebeasi/pen/NQPEQQ

This issue looks like some kind of bug in Safari/WebKit. I am going to close this as this is not an Ionic issue, but we are going to look into reporting this bug to Apple to see if there is a workaround. Thanks!

**Closed by liamdebeasi** 2019-07-19 16:33 UTC
Labels: triage

**Comment by patrickbussmann** [comment] 2019-07-19 16:58
Ok but thanks for testing.
Then I'll open an issue on apple's side.
I had the hope that you have another idea. :)
Thanks.
