### ISSUE TITLE
bug: Chrome iOS app issues

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic#17963] opened 2019-04-04 22:49 UTC
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**
Ionic app is displayed incorrectly on the Chrome iOS app and none of the animations work.   It works fine on every other browser / platform as well as Chrome on Android.

**Expected behavior:**
Ionic app should appear and animate the same on Chrome iOS as it does every other browser app.

**Steps to reproduce:**
1. Create an Ionic app.
2. Host the app
3. Visit the url pointing to the app on the Chrome iOS app.

You will notice right away that all toolbars are being pushed down which I assume is because it's detecting iOS as the platform and is adjusting the content around the center camera and speaker (idk just a guess).

![IMG_1522](https://user-images.githubusercontent.com/25699262/55593565-4d51b280-570a-11e9-95c9-6b86a5022794.PNG)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 15 other plugins)

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Comment by daem0ndev** [comment] 2019-04-05 02:31
Potential duplicate of https://github.com/ionic-team/ionic/issues/17956

**Comment by liamdebeasi** [comment] 2019-04-05 12:17
Hi there,

I am going to close this as a duplicate of #17956.

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-04-05 12:17 UTC
Labels: triage
