### ISSUE TITLE
bug: ion-datetime not showing

### ISSUE THREAD

**Issue by KreLou** [ionic-team/ionic#18196] opened 2019-05-03 06:52 UTC
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
I want to use an ion-datetime to select a date and bind it to the value.
But on click, no input is showing, so I added a method to open the datepicker, but i cant see the picker on the browser.

**Expected behavior:**

I expect the visible datetime-pciker

**Steps to reproduce:**

**Related code:**

```

    <ion-item lines="full">
      <ion-label>Datum:</ion-label>
      <ion-button icon-right (click)="openDateTimePicker(datePicker)">
        <ion-datetime #datePicker placeholder="Date" display-format="YYYY-MM-DD" picker-format="YYYY-MM-DD" [(ngModel)]="date"></ion-datetime>
        <ion-icon name="calendar"></ion-icon>
      </ion-button>
    </ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\KreLou\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.12.2
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment] 2019-05-06 13:13
Hi there,

Please try this using a stable version of Ionic. There have been numerous changes during the beta/RC phase of Ionic, so it's possible this has already been fixed.

Thanks!

**Comment by KreLou** [comment] 2019-05-07 08:37
Hey,

I updated to the following version:
```

Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

But the problems is not fixed.

**Comment by liamdebeasi** [comment] 2019-05-07 13:54
Hi there,

What does your code for `openDateTimePicker` look like? I am trying your code and the datepicker opens.

**Comment by KreLou** [comment] 2019-05-07 16:24
Hey,
here is the code:
```
openDateTimePicker(picker: IonDatetime){
    picker.open().then(() => {
    }).catch(() => {
    })
  }
```

**Comment by liamdebeasi** [comment] 2019-05-07 16:38
Hi there,

Thanks for the follow up. If you remove `(click)="openDateTimePicker(datePicker)"` from the button, does the datepicker still open? The click event should propagate down to the `ion-datetime` element.

Thanks!

**Comment by KreLou** [comment] 2019-05-07 17:39
Hi,
I removed this part, but nothing happend.

I splitted the screen the inspect the html-sourcecode. If I click on the button,  the class `class="backdrop-no-scroll"` will added to the body.

**Comment by liamdebeasi** [comment] 2019-05-07 18:02
Hi there,

Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by KreLou** [comment] 2019-05-07 18:26
Hi,

here you can find the online-repositoy on github:
[Page](https://github.com/KreLou/BAGCST/tree/insertFood/app/src/app/pages/admin-create-or-edit-food-menu)

**Comment by liamdebeasi** [comment] 2019-05-07 19:50
Hi there,

So when I click the ion-item, I see the datetime component get opened twice; however, I would expect this to happen since `openDateTimePicker` opens a datepicker and then the click event propagates to the `ion-datetime` component, which in turn opens another datepicker.

I am not seeing the issue you originally described. Can you double check your code and ensure that you are implementing `ion-datetime` correctly?

Thanks!

**Comment by KreLou** [comment] 2019-05-07 20:02
Hi,
I removed the openDateTimePicker in the current version, and I removed (click), but i dont see the picker.

What is the correct implemention?

**Comment by liamdebeasi** [comment] 2019-05-07 20:07
Hi there,

Please take a look at the [ion-datetime Documentation](https://ionicframework.com/docs/api/datetime) for the correct implementation. 

Additionally, I was unable to navigate to the page where the datepicker was while running your application, so I had to pull your code out into a standalone application.

If the issue is still happening, please provide instructions on how to navigate to that page in app.

**Comment by KreLou** [comment] 2019-05-08 04:52
Hi,

 I implemented the datetime like the documentation.

For navigation, click on the menu on the tab-bar, and then select the pen in the header, finally click the blue (+) in the lower right corner.

Thanks for your help.

**Comment by KreLou** [comment] 2019-05-08 17:50
Hi,

thanks for your support.
I made some changes in the page.ts so know you can navigate to the specific file.

**Comment by KreLou** [comment] 2019-05-08 18:01
Hi,

thanks for your support.

I made some small changes in the page.ts, so you can click the (+) button now.

**Comment by KreLou** [comment] 2019-05-08 18:02
Hi,
thanks for your support.

I made some small changes, so you can visit the side now without api access.

**Comment by liamdebeasi** [comment] 2019-05-08 19:03
Hi there,

I was able to take a look at your app after you pushed your changes. It looks like you have not implemented tabbed routing properly. Tabs create a separate router context, but since they were not implemented correctly, the `ion-datetime` component was being added to the default router context (which sits under the tabs content when using tabs).

I am going to close this as this is not an Ionic issue, but I would recommend you look at the [Ionic Tabs Starter](https://github.com/ionic-team/starters/tree/master/angular/official/tabs) for an example of how to properly implement tabs. 

You will need to do the following:

- Remove the `ion-header` from `app.component.html`
- Remove the `ion-tabs` from `app.component.html` and place it in `tabs/tab.page.html`
- Update `app-routing.module.ts` to redirect to the tabs page (you can see how to do this in the tabs starter)
- Update `tabs/tabs.router.module.ts` with all of your routes nested in the `tabs` path. (You can also see how to do this in the tabs starter)

Thanks!

**Closed by liamdebeasi** 2019-05-08 19:03 UTC
Labels: triage

**Comment by liamdebeasi** [comment] 2019-05-08 19:06
<img width="418" alt="Messages Image(3452073314)" src="https://user-images.githubusercontent.com/2721089/57401032-cd07ec80-71a2-11e9-8837-0e4cf7626090.png">

Also apparently I can time travel in this thread 🤔
