### ISSUE TITLE
[bug]Cannot enter Chinese in the SearchBar

### ISSUE THREAD

**Issue by iSteveLiu** [ionic-team/ionic#11973] opened 2017-06-08 09:18 UTC
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.3.0**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When I enter Chinese in the SearchBar, there are redundant English characters.

**Related code:**

```
<ion-searchbar [animated]=true [autocomplete]="on" (ionInput)="onSearchInput($event)" [(ngModel)]="currentSearchCondition.name"></ion-searchbar>
```

**Comment by AmitMY** [comment] 2017-06-08 09:23
Dup: https://github.com/ionic-team/ionic/issues/11566

**Comment by jgw96** [comment] 2017-06-08 14:15
Hello! Closing this as a duplicate of #11566. We plan on having this issue fixed for the next release. Thanks!

**Closed by jgw96** 2017-06-08 14:15 UTC
