### ISSUE TITLE
Item - Can't move to the next input/datetime/select on Android

### ISSUE THREAD

**Issue by Newbie012** [ionic-team/ionic#16936] opened 2019-01-02 17:19 UTC
# Bug Report

**Ionic version:**

**4.x**

**Current behavior:**

While using an Android device (untested in iOS), navigating between inputs fields is not possible (i.e There's no "next" button in the keyboard, just "go").

**Expected behavior:**

While focusing an input/select/datetime/etc, there should be a "next" button (in the native keyboard) instead of "go" button (i.e should move to the next form control instead of submitting).

**Steps to reproduce:**

 - Create a new Ionic app.
 - Create a basic form.
 - Run `ionic cordova run android -l`.
 - Try to move to the next form control.
 - See occurance.

**Related code:**

```
<form>
  <ion-item>
    <ion-input autofocus></ion-input>
  </ion-item>
  <ion-item>
    <ion-input></ion-input>
  </ion-item>
  <ion-item>
    <ion-select>...</ion-select>
  </ion-item>
</form>
```

**Other information:**

My guess is it happens because the real `input` is nested inside the Shadow DOM.

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (...)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (...)
   NodeJS            : v10.11.0 (...)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by paulstelzer** [comment] 2019-01-02 17:58
I can confirm this issue!

**Comment by KevinKelchen** [comment] 2019-01-03 14:47
May be related to #16498. 🙂

**Comment by Newbie012** [comment] 2019-01-03 15:09
@KevinKelchen Yea... it's because of the Shadow DOM. Most of the issues I posted were because of it :(

**Comment by m0nzderr** [comment] 2019-01-09 15:52
@KevinKelchen , I believe this issue and #16498, #15682 are related, and the problem is indeed a shadow DOM encapsulation. IMHO, there is no good solution unless there is a way to place all inputs within the same shadow container or just opt out from using shadow DOM (see discussion #15682). 

@paulstelzer, I'd suggest to reopen #15682 and/or create a special thread to concentrate all shadow DOM-related issues until an actual solutions is provided. We all know that hacking around with event handlers may help to cover some symptoms, still being an inferior UX solution.

**Comment by paulstelzer** [comment] 2019-01-09 15:58
@m0nzderr You should be right. As answered here https://github.com/ionic-team/ionic/issues/15682#issuecomment-445709650, i will not reopen #15682 because we already have two issues about this topic

#15136: Button does not trigger ngSubmit
#16498: Prev / Next button on mobile keyboard

So this issue is a duplicate of #16498 and so I will close it here, so we have only two about this shadow dom related topic.

The bad news is that no browser currently support it correct right now and so the developer has to add the handler by his own. How to solve #16498 is something I don't know

**Closed by paulstelzer** 2019-01-09 15:58 UTC
Labels: needs: investigation, package: core
