### ISSUE TITLE
ionic4 --color css propery of ion-label is not usable

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic#17775] opened 2019-03-13 16:22 UTC
**Ionic version:**
[x] **4.1.2**

**Current behavior:**
on a simple 
```
<ion-list>
    <ion-item>
        <ion-label position="floating">Username</ion-label>
        <ion-input formControlName="username" type="text" (keydown.enter)="doSave()"></ion-input>
    </ion-item>
</ion-list>
```
with a css file
```
ion-label {
    --color: blue;
}
```
does not overwrite the color of a label, see the styles adapted by chrome
![image](https://user-images.githubusercontent.com/3778892/54295971-542a5100-45b4-11e9-84ae-3aae2e7436cc.png)

ALSO IMO:
an ion-label with an floating position should have a `rgba(0,0,0,.6)` as `color`, like MD adopts in `angular-material`

**Comment by mburger81** [comment] 2019-03-13 16:46
You can do in css
ion-item > ion-label...
But this is not what I'm expecting reading documentation

**Comment by liamdebeasi** [comment] 2019-03-13 21:13
Hi there,

Thanks for the issue! I am going to close this as a duplicate of #17425. As a temporary workaround you will need to do:

```
ion-label {
  --color: blue !important;
}
```

Thanks for bearing with us as we investigate this issue! 🙂

**Closed by liamdebeasi** 2019-03-13 21:13 UTC
Labels: triage
