### ISSUE TITLE
Allow the user to clear a date time picker

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionic#12979] opened 2017-09-25 11:39 UTC
**Resources:**
Before submitting an issue, please consult our troubleshooting guide (http://ionicframework.com/docs/troubleshooting/) and developer resources (http://ionicframework.com/docs/developer-resources/)

Please make sure you are posting an issue pertaining to the Ionic Framework. If you are having an issue with the Ionic Pro services (Ionic View, Ionic Deploy, etc.) please consult the Ionic Pro support portal (http://support.ionicjs.com)

**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When a user accidentally picks a date he is unable to undo/remove the date via the date picker.

**Expected behavior:**
A clear cross icon or something which also allows the user to remove the current set value

**Steps to reproduce:**
Create a date picker component and set a date

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:

    @ionic/cli-utils  : 1.6.0 (ionic-app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI) : 3.6.0 (ionic-app/node_modules/ionic)

global packages:

    Cordova CLI : 6.5.0

local packages:

    @ionic/app-scripts              : 2.1.4
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.6.0

System:

    Node       : v8.2.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.1.0
    npm        : 5.4.2
```

**Comment by kensodemann** [comment] 2017-09-26 01:12
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #11961, which itself has been moved to the feature request list as feature request number 248.

Thank you for using Ionic

**Closed by kensodemann** 2017-09-26 01:12 UTC
