### ISSUE TITLE
Modals can only be imported in app.module.ts

### ISSUE THREAD

**Issue by martinlombana** [ionic-team/ionic#18411] opened 2019-05-29 16:31 UTC
Hi,

I am using ionic 4, and working with modals.

The problem I have is that my modals only work, in a given page, when I import them directly in the app.module.ts, but If load them in the page’s module (in order for the modals to be loaded when that module loads), then they don’t work.

This is my modal module:
```
@NgModule({
	declarations: [ScanListModal],
	imports: [
		CommonModule,
		FormsModule,
		IonicModule,
		BasePageModule
	],
	entryComponents: [ScanListModal]
})
export class ScanListModalModule {
}

```
And this is my page’s module, when loading the modal:

```
const routes: Routes = [
	{
		path: '',
		component: ScanSessionPage
	}
];

@NgModule({
	imports: [
		CommonModule,
		FormsModule,
		IonicModule,
		RouterModule.forChild(routes),
		BasePageModule,
		CommonComponentsModule,
                ScanListModalModule
	],
	declarations: [ScanSessionPage],
	providers: [],
	entryComponents: [],
	exports: []
})
export class ScanSessionPageModule {
}
```
And that does not work. But if I remove the import there, and import the modal’s module in app.module.ts, it works.

But my guts tells me that I should just load that modal in the modules that actually use them, not globally for the app, right? It looks like a bug.

Any help would be appreciated.

Thanks!

Ionic Info:
```
   ionic (Ionic CLI)             : 4.12.0 (C:\Users\marti\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\marti\AppData\Local\Android\sdk)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Comment by liamdebeasi** [comment] 2019-05-30 13:52
Hi there,

Thanks for the issue! I am going to close this as this is more of a support request and not a bug in Ionic.

In terms of importing the modal, I would recommend looking at how the Ionic Conference App imports modals. I can confirm that you should not be forced to only import a modal into your `app.module.ts` file.

Here is the relevant code for the conference app:

Schedule Page: https://github.com/ionic-team/ionic-conference-app/tree/master/src/app/pages/schedule
Schedule Filter Modal: https://github.com/ionic-team/ionic-conference-app/tree/master/src/app/pages/schedule-filter

Thanks for using Ionic!

**Closed by liamdebeasi** 2019-05-30 13:52 UTC
Labels: triage

**Comment by martinlombana** [comment] 2019-05-30 22:11
The example you provided does not use Lazy Loading.

I changed the title. Is it or not an issue now?

Thanks,

**Comment by liamdebeasi** [comment] 2019-06-06 20:48
Hi there,

This is possible. If you have a `modal` component and a `home` page, you will need to import `modal.module.ts` into `home.module.ts` and declare it `imports`.

So it would look something like this:


```
...

import { ModalModule } from '../components/modal/modal.module';

...

@NgModule({
  imports: [
    ModalModule,
    ...
  ]
});
export class HomePageModule {}
```

**Comment by martinlombana** [comment] 2019-06-06 20:51
Yes.
That is the theory. But it does not work.


-- 

___________________________________

*Martín Lombana *

*TODOLOGIC.COM <http://TODOLOGIC.COM> *

*+34 633 63 02 35  |   *+34 946 759 137

*INSTAGRAM *→* @ <https://instagram.com/todologic>TODOLOGIC
<https://instagram.com/todologic>*

**Comment by liamdebeasi** [comment] 2019-06-06 21:00
Hi there,

I would recommend posting on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com/) as this is really more of a support question and not a bug with Ionic.

Additionally, I would recommend reading this article: https://medium.com/@david.dalbusco/how-to-declare-and-use-modals-in-ionic-v4-4d3f42ac30a3 It covers how to declare/use modals (including how to do it with lazy loading).

Thanks!

**Comment by liamdebeasi** [comment] 2019-06-06 21:02
Also forgot to mention that there is a section on this in the `ion-modal` documentation: https://ionicframework.com/docs/api/modal#lazy-loading

Hope this helps!
