### ISSUE TITLE
v4: menu > header "md" mode missing shadow during animation

### ISSUE THREAD

**Issue by ghybs** [ionic-team/ionic#14722] opened 2018-07-06 07:20 UTC
# Bug Report

**Ionic Info**
Using @ionic/core version 4.0.0-alpha.7 directly from npm / unpkg CDN.
Chrome Mobile 67.0.3396.87 (Android 8.0.0)
Chromium (desktop) 66.0.3359.181 (64 bits) Ubuntu 16.04.4 LTS with "device toolbar" enabled.

**Describe the Bug**
When opening an `<ion-menu>` with `<ion-header>`, the latter's bottom shadow in `"md"` mode appears only at the end of the sliding animation.
Same for `"push"` type (and `"overlay"` by default), but appears fine for `"reveal"` type.

**Steps to Reproduce**
1. Go to https://beta.ionicframework.com/docs/content/api//menu-demo.html using Mobile Chrome or with Desktop Chrome with device toolbar enabled (make sure it displays as `"md"` mode).
2. Click on the 'Open start menu' button.
3. While the menu opens, the header misses its shadow, but it appears at the end of the animation.
4. Click on the 'Set push' button.
5. Re-open the start menu: same issue.

No issue with the end menu and the `"reveal"` type for both menus.

**Related Code**
Same in version 4.0.0-alpha.7: https://beta.ionicframework.com/docs/content/api/4.0.0-alpha.7/menu-demo.html
But works fine in version 4.0.0-alpha.6: https://beta.ionicframework.com/docs/content/api/4.0.0-alpha.6/menu-demo.html

**Expected Behavior**
The menu header bottom shadow should always be displayed, even during the animation.

**Additional Context**
Looks like it is caused by the `.scroll-inner` element with `min-height: 100%` CSS rule, which seems to also be the cause of issue https://github.com/ionic-team/ionic/issues/14720.
When this rule is removed, the shadow appears correctly during the animation.

In the docs preview, the end menu seems unaffected because its content has a padding:
https://github.com/ionic-team/ionic/blob/v4.0.0-alpha.7/core/src/components/menu/test/preview/index.html#L62

**Comment by jgw96** [comment] 2018-07-12 14:36
Hello! With alpha.10 I am no longer able to reproduce this issue. Because of this I will be closing this issue for now. Thanks!

**Closed by jgw96** 2018-07-12 14:36 UTC
Labels: triage

**Comment by ghybs** [comment] 2018-07-13 05:08
Hi again,

Well, I _do_ see a clear improvement!
- On desktop there is no issue at all, like previously.
- On desktop with "device toolbar" enabled, I no longer see the issue (i.e. the menu header toolbar shadow is always there even during the animation).
- On actual mobile device (Chrome 67.0.3396.87 on Android 8.0.0), the demo app (which seems updated to use latest release version 4.0.0-alpha.10) works _better_ but still not perfect:
  - https://beta.ionicframework.com/docs/content/api//menu-demo.html
  - Like previously, only in the `"overlay"` and `"push"` types, the shadow is initially missing at the beginning of the menu appearing animation, but it then appears faster (somewhere mid-animation). Therefore it is like "flashing". Whereas in alpha.7, it was appearing only at the very end of the animation, making its absence much more obvious.
  - By using the swipe gesture to draw the menu in, open it slowly and you can have _most of the time_ the shadow missing as long as the menu is half open (in the `"overlay"` and `"push"` types). As soon as you release the touch, the shadow appears.

![screenshot_20180713-084925_chrome](https://user-images.githubusercontent.com/12232803/42673349-0892ca58-867c-11e8-966e-6bcd3940fbca.png)

BTW there is also an edge case bug: while swiping the menu in, use another finger / hand to touch the menu => it becomes stuck half way open, and touching the backdrop overlay does not close it. Therefore there is no way to close it back if it does not include a close button itself. That is how I have been able to make the above screenshot. I will open a separate issue for that.

**Comment by ghybs** [comment] 2018-07-13 05:11
BTW like previously I could never trigger that bug with the end menu, if that can be of any help.

**Comment by ghybs** [comment] 2018-07-13 05:32
I have been able to reproduce it on desktop Chrome (67.0.3396.99 64-bit) on Win10 (no need to enable the "device toolbar" mode):

<img width="227" alt="screenshot_ionic_bug_menu_missing_header_shadow" src="https://user-images.githubusercontent.com/12232803/42674029-361ba6c2-867f-11e8-9bca-713c726a5b7f.png">

After injecting the alpha.10 CSS into the demo app:

<img width="226" alt="screenshot_ionic_bug_menu_missing_header_shadow2" src="https://user-images.githubusercontent.com/12232803/42674141-8934eaee-867f-11e8-97ef-9d503ed6b3ba.png">
