### ISSUE TITLE
bug: ion-item-option does not register first click

### ISSUE THREAD

**Issue by eddyouedraogo** [ionic-team/ionic#21511] opened 2020-06-12 13:40 UTC
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.26.0**

**Current behavior:**

I have an ion-virtual-scroll in which I use an ion-item-sliding I then have an ion-item-options that hosts my ion-item-option. The problem here is that 3 times out of 4 the first click on the ion-item-option does not register I have to click a second time in order to trigger the event. 

**Expected behavior:**

After sliding the item the first click should be register.

**Steps to reproduce:**

**Related code:**

```
<ion-virtual-scroll #itemList
                        [items]="allItems"
                        [trackBy]="identify"
                        [headerFn]="showGroupHeader"
                        [headerHeight]="headerHeight"
                        [approxHeaderHeight]="approxHeaderHeight">

<ion-item-sliding #slidingItem *virtualItem="let item; let i = index">
        
        <ion-item-options side="end">
          <ion-item-option expand="full" class="sliding-item-button"
                      [hidden]="isHidden"
                      [disabled]="isOptionDisabled(item)"
                      (click)="doSomething(item, slidingItem)">
            <span>Item Button</span>
          </ion-item-option>
        </ion-item-options>
      </ion-item-sliding>
</ion-virtual-scroll>
```

**Comment by eddyouedraogo** [comment] 2020-06-12 15:30
I have made a repository where you can find the reproduction of this bug : https://github.com/eddyouedraogo/slidin-item-issue-reprod

Please note that the behaviour is more visible on mobile devices.

1. In order to reproduce the error I would suggest you install the app on a mobile device and try it.
2. Once the items of the list are generated slide any item to the left and press button that appears.
3. To better reproduce the problem do the previous step and click as fast as possible on the button once the sliding-item is fully opened

**Comment by liamdebeasi** [comment] 2020-06-19 19:12
Thanks for the follow up. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/20502.

**Closed by liamdebeasi** 2020-06-19 19:12 UTC
Labels: ionitron: needs reproduction
