### ISSUE TITLE
bug: Modal backdrop click prevented by .modal-shadow element (mode: 'ios')

### ISSUE THREAD

**Issue by hoi4** [ionic-team/ionic#21426] opened 2020-06-03 08:50 UTC
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When using a modal with `mode: 'ios'`, the `.modal-shadow` element prevents clicking the backdrop to dismiss the modal

**Expected behavior:**
The backdrop should be clickable to dismiss the modal.

**Demo code:**
https://stackblitz.com/edit/ionic-4-angular-8-start-template-ejcn8f

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.9.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 23 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.2.3

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.0 (/usr/local/Cellar/node@12/12.16.0/bin/node)
   npm     : 6.14.5
   OS      : macOS Catalina
   Xcode   : Xcode 11.5 Build version 11E608c
```

**Comment by roman-rr** [comment] 2020-06-03 11:56
@hoi4 
**Ion-modal** component should be used with full height to prevent any further issues.

**Comment by liamdebeasi** [comment] 2020-06-03 13:19
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework.

To get this to work, you can add the following to your global CSS:

```css
ion-modal .modal-shadow {
  pointer-events: none;
}
```

**Closed by liamdebeasi** 2020-06-03 13:19 UTC
Labels: triage

**Comment by hoi4** [comment] 2020-06-03 13:44
Only out of interest: Why was this behaviour changed? I upgraded from version 5.0.1 to 5.1.1 and before the upgrade, this css was not necessary. 🤔

**Comment by liamdebeasi** [comment] 2020-06-03 13:45
The `.modal-shadow` is a new div we added to better support the card-style modal.
