### ISSUE TITLE
Migration guide from v8 to v10

### ISSUE THREAD

**Issue by ashinpaugh** [ionic-team/ionic#14774] opened 2018-07-14 00:53 UTC
After upgrading from v8 to v10 I've come across the same issues as [this guy](https://github.com/ionic-team/ionic/issues/14748), but in a `sidemenu` project. Custom styles were wiped out because shadow dom started showing up and I haven't changed the encapsulation settings (set to None). 

I started poking around I found this in a bunch of definition files:
"../../../../../../../../Users/adam/git/ionic/core/src/interface"

Don't know if they are related but I figured I'd post it because I doubt it was intentional.

> Ionic:
> 
>    ionic (Ionic CLI)          : 4.0.0-rc.11 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework            : @ionic/angular 4.0.0-alpha.10
>    @angular-devkit/core       : 0.7.0-rc.1
>    @angular-devkit/schematics : 0.7.0-rc.1
>    @angular/cli               : 6.0.8
>    @ionic/ng-toolkit          : 1.0.0-rc.11
>    @ionic/schematics-angular  : 1.0.0-rc.11
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : ios 4.5.4
> 
> System:
> 
>    Android SDK Tools : 26.1.1
>    NodeJS            : v8.11.3 (/usr/local/Cellar/node@8/8.11.3_1/bin/node)
>    npm               : 6.1.0
>    OS                : macOS High Sierra
>    Xcode             : Xcode 9.4.1 Build version 9F2000
> 
> Environment:
> 
>    ANDROID_HOME : /Users/developer/Library/Android/sdk
>

**Comment by brandyscarney** [comment] 2018-08-31 15:48
Thanks for the issue! I'm going to close this as a duplicate of #14748. Please put any comments on that issue if this is still a problem, including how we can reproduce it. Thanks!

**Closed by brandyscarney** 2018-08-31 15:48 UTC
Labels: triage
