### ISSUE TITLE
bug: Pixel 4 XL registering platform as tablet device type 

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic#21593] opened 2020-06-21 18:51 UTC
# Bug Report

**Ionic version:**
[X] **4.11.10**

**Current behavior:**
platform.platforms() returns `Tablet` for Pixel 4 XL device

**Expected behavior:**
platform.platforms() should not list `Tablet`

**Steps to reproduce:**
platform.platforms() returns wrong values

**Related code:**

```
import { Platform } from '@ionic/angular';
platform.platforms()
```

**Comment by liamdebeasi** [comment] 2020-06-22 13:14
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/19737.

**Closed by liamdebeasi** 2020-06-22 13:14 UTC
Labels: triage
