### ISSUE TITLE
[Ionic v4.0.0-rc.0] backdrop doesn't close menu on Edge

### ISSUE THREAD

**Issue by siege089** [ionic-team/ionic#17076] opened 2019-01-12 17:54 UTC
**Ionic Info**

Ionic:

   ionic (Ionic CLI)             : 4.7.1 
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular/cli                  : 7.1.4

System:

   NodeJS : v11.6.0
   npm    : 6.5.0
   OS     : Windows 10
   Edge : 42.17134.1.0

**Describe the Bug**
When a menu is opened and the backdrop is clicked the menu does not dismiss.

**Related Code**
See https://beta.ionicframework.com/docs/api/menu/ the preview phone when in md mode shows same behavior.

**Expected Behavior**
Same as Chrome, close menu.

**Comment by paulstelzer** [comment] 2019-01-13 07:46
Thanks! But this is a a duplicate of #14767, so I close it here :)

**Closed by paulstelzer** 2019-01-13 07:46 UTC
Labels: triage
