### ISSUE TITLE
ion-button changes disabled state only once in ionic 5 it works when resize screen

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/ionic#21007] opened 2020-04-10 14:11 UTC
Hello sir

Here is my sample code 

`<ion-content [scrollEvents]="true" #content (ionScrollStart)="common.on_scroll_ion_content(content)"  (ionScrollEnd)="common.on_scroll_ion_content(content)">`
  `<form login-form (ngSubmit)="login()" action="#" novalidate>`
    `<ion-list>`
      `<ion-item>`
        `<ion-input placeholder="Email Address" type="email" id="login_email" [(ngModel)]="loginform.email" autocomplete="off" (ngModelChange)="LoginFieldsCheck()"
          name="email"></ion-input>`
      `</ion-item>`
      `<ion-item>`
        `<ion-input placeholder="Password" type="password" id="login_password" [(ngModel)]="loginform.password" autocomplete="off"
          (ngModelChange)="LoginFieldsCheck()" name="password" clearOnEdit="false"></ion-input>`
      `</ion-item>`
    `</ion-list>`
    `<ion-button color="primary" expand="block" type="submit" id="login_button" [disabled]="LoginFieldsCheck()">SIGNIN <i class="fas fa-sign-in-alt"></i></ion-button>`
  `</form>`
`</ion-content>`

and here is ts file code

`loginform = { email: '', password: '' };

LoginFieldsCheck() {
	if (!this.loginform.email || this.loginform.email == '' || this.loginform.email.trim() == '' || this.common.isEmail(this.loginform.email) == false) {
	  console.log('invalid case 1');
	  return true;
	}
	else if (!this.loginform.password || this.loginform.password == '' || this.loginform.password.length < 6) {
	  console.log('invalid case 2');
	  return true;
	}
	else {
	  console.log('valid case, enable login btn');
	  return false;
	}
}`

here is ionic info

Ionic:

   Ionic CLI                     : 6.3.0 (C:\Users\himansu\AppData\Roaming\npm\n
ode_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 7`
`

now when i am go to login page first time all working fine, but now when i go to second time login page and if even both email and password condition meet that submit button not enabled, and if i just resize my window screen it enable, really i checked same thing into my mac PC also with latest ionic angular 5.0.7 but it also have same issue.

here is video preview for our case
https://www.loom.com/share/5131ea8da7d944418ea72d64d4cb16e5

Can you please help us to fix that issue?

Thanks in advance.

**Comment by liamdebeasi** [comment] 2020-04-10 14:22
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by NikolaPeevski** [comment] 2020-04-10 23:59
You need to use a onPush strategy I'd assume https://angular.io/api/core/ChangeDetectionStrategy which is what you're doing by resizing the window, forcing a repaint/change detection.

**Comment by herobarua** [comment] 2020-04-11 09:58
@NikolaPeevski How to use the strategy in IONIC 5? Because I see same type issue my end also when I was migrate ionic 3 to ionic 5.

**Comment by NikolaPeevski** [comment] 2020-04-11 11:39
@herobarua It does work without the onPush, I still kept the example commented out. Check this out https://github.com/NikolaPeevski/ion-button-disabled-state-change

**Comment by herobarua** [comment] 2020-04-11 11:48
@NikolaPeevski Thanks reply.

Yes I am following the as your mention way using variable. for make it work perfect, is it necessary to add "this.changeRef.detectChanges();" ?

**Comment by NikolaPeevski** [comment] 2020-04-11 11:49
Nah, I just kept it there so you see how you can do onPush changes as an example.

**Comment by herobarua** [comment] 2020-04-11 11:51
@NikolaPeevski Thanks for your support and prompt reply.

**Comment by ipehimanshu** [comment] 2020-04-11 12:09
@NikolaPeevski 
thank you so much. now i have used that this.changeRef.detectChanges() after function call and used variable and it seems working.

**Comment by NikolaPeevski** [comment] 2020-04-11 16:30
Because the browser/webview/whatever does not detect that there is a change of the binded variable. With detectChanges you're forcing a shakedown on the DOM tree effectivelly, another way of doing it is wrapping the change in ngZone.run which forces a tree shake as well. Its quirky and I wouldn't blame ionic on it but rather the internal angular's change detection, just remember that it sometimes happens.

**Comment by liamdebeasi** [comment] 2020-04-13 14:47
Thanks for the issue. I am going to close this as it seems the original issue is resolved. Thanks for the help @NikolaPeevski! 😊

**Closed by liamdebeasi** 2020-04-13 14:47 UTC
Labels: triage
