### ISSUE TITLE
bug: ionInfinite in ion-infinite-scroll is never called

### ISSUE THREAD

**Issue by Abrissirba** [ionic-team/ionic#18739] opened 2019-07-09 12:40 UTC
# Bug Report

**Ionic version:**
@ionic/angular 4.6.0

**Current behavior:**
 ionInfinite in ion-infinite-scroll is never called. 

**Expected behavior:**
ionInfinite in ion-infinite-scroll should be called when the user scroll to the bottom of the page.

**Steps to reproduce:**
Add an ion-infinte-scroll element at the bottom of the page and scroll down. the function defined in ionInfinite is never called

**Related code:**

https://github.com/Abrissirba/ion-infinite-scroll-bug

The example in the docs doesn't seem to work either, https://ionicframework.com/docs/api/infinite-scroll

**Comment by liamdebeasi** [comment] 2019-07-09 13:05
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/18632.

Additionally, this issue has already been fixed and will be in Ionic 4.6.1.

**Closed by liamdebeasi** 2019-07-09 13:05 UTC
Labels: triage
