### ISSUE TITLE
Modal - possible memory leak

### ISSUE THREAD

**Issue by jbgomez21** [ionic-team/ionic#13336] opened 2017-11-04 18:26 UTC
Hi

I have a problem with my application in Ionic 3.8.0.
I have a page with a button that open the Modal page, this works fine, but when I repeatedly open and close my phone crash due to lack of memory.

I have done a PoC simpler and I see the following in Chrome Memory tool: 
After open and close repeatedly 10 times.

![home](https://user-images.githubusercontent.com/3789684/32408286-5c0971f0-c174-11e7-8c00-dcc9e5fe146f.png)

![modal](https://user-images.githubusercontent.com/3789684/32408288-6acde004-c174-11e7-981d-f843f5831273.png)

Why DrawPage (the Modal page) doesn’t garbage collected?
After I took the heap snapshot, DrawPage still exists yet!

Is it a memory leak or am I understanding wrong?

  ```
  @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.2.4
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.1 
    Node              : v8.3.0
    npm               : 5.4.2 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004 
```

Regards

**Comment by Sampath-Lokuge** [comment] 2017-11-05 03:14
Hope you need to do this test on the `device` in `debug` mode.

**Comment by jbgomez21** [comment] 2017-11-05 03:55
Hi @Sampath-Lokuge 
Thx for your reply....

1. I will try that and tell you what happened.
2. My app has one HomePage and several modal that open from this one. As you open and close these Modal page, the above occurs. 

On the device works until the application restarts, WKWebView restart my app, it does not close, it simply restarts.

Regards!

**Comment by longgt** [comment] 2017-11-05 23:57
Same issue as #12574

**Comment by longgt** [comment] 2017-11-06 00:18
Modal component should destroy the following object if existed before creating new.

const componentRef = this._viewport.createComponent(componentFactory, this._viewport.length, this._viewport.parentInjector, []);

**Comment by kensodemann** [comment] 2017-11-06 11:43
Hello! Thank you for opening an issue with us! I am closing this issue because it is a duplicate of Issue #12574 (thank-you @longgt for finding that). Please track that issue for further updates. Also please comment on that issue with any new information you may have to share.

Neither this issue nor #12574 have a sample app provided via GitHub that duplicates the issue. If someone could provide that and then share the link in #12574, that would greatly help whoever picks this up.

Thank you for using Ionic

**Closed by kensodemann** 2017-11-06 11:43 UTC
