### ISSUE TITLE
Ionic platform check not working properly

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [ionic-team/ionic#12472] opened 2017-07-26 04:44 UTC
**Platforms**
android - on a device running Android.
cordova - on a device running Cordova.
core - on a desktop device.
ios - on a device running iOS.
ipad - on an iPad device.
iphone - on an iPhone device.
mobile - on a mobile device.
mobileweb - in a browser on a mobile device.
phablet - on a phablet device.
tablet - on a tablet device.
windows - on a device running Windows.

**Code**
if (this.platform.is('core') || this.platform.is('mobileweb')) {
// login page 
}else{
// Home page
}

**Issue**
This above conditional block not satisfied in mobile browser. Actually "mobileweb" platform indicates the browser on a mobile device. But condition not satisfied. Whats wring with this or API issues ? How to resolve ? Help please.

**Comment by jgw96** [comment] 2017-07-27 14:09
Hello, thanks for opening an issue with us. What browser are you having issues with? Also, could you post a repo we could use to reproduce this issue?

**Comment by jgw96** [comment] 2017-08-01 15:38
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Closed by jgw96** 2017-08-01 15:38 UTC
Labels: accessibility, needs info

**Comment by sundaramoorthyjeeva** [comment] 2017-08-04 07:15
Sorry for the delay reply. Yes. I am using chrome browser. Still I am facing this issue. Platform "mobileweb" returns false. What to do ?

**Comment by karansharma27** [comment] 2017-10-27 07:39
I am facing the same issue, what's the solution?
