### ISSUE TITLE
ion-back-button goes to wrong route for tabs

### ISSUE THREAD

**Issue by rafalschmidt97** [ionic-team/ionic#17278] opened 2019-01-26 19:59 UTC
# Bug Report

**Ionic version:**

[x] **4.0.0**

**Current behavior:**

How you can see below it goes to wrong tab. I've tried to figure it out with outlet and later with child routes but I failed twice.

![screen recording 2019-01-26 at 20 20 07](https://user-images.githubusercontent.com/14861637/51792041-71de5b00-21ac-11e9-8a48-e1b4a7949cbb.gif)

**Expected behavior:**

Back button should redirects me to "profile2".

**Steps to reproduce:**

**Related code:**

Nothing special:

- at least two tabs
- another page in app route

![screenshot 2019-01-26 at 20 22 09](https://user-images.githubusercontent.com/14861637/51792100-ff21af80-21ac-11e9-9f9f-ceb3564647fb.png)

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 2 other plugins)

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by georgechr** [comment] 2019-02-06 11:49
This is indeed an issue and needs to be addressed.
At the moment I am working around it by adding/removing a subscription to the tabs change event on ionic view enter/leave, saving the last known tab and navigating to it when the view enters again.

Ionic does try to enforce the selection to the first tab so you see a small flicker while this happens. This can be solved by also attaching a subscription to the tabs change through the view template and if this event fires while the 1st subscription is closed then force selection to the last known tab instead. Jeez....

**Comment by victorcarvalhosp** [comment] 2019-02-12 13:48
Same problem here!

**Comment by juanmigonzalez** [comment] 2019-02-18 14:00
I have the same problem. Can we expect a solution in the next release?

**Comment by EugeneNews** [comment] 2019-02-21 08:29
I temporarily solved this with specific `routerLink` on `ion-back-button` - to force opening needed tab.

**Comment by bossjon** [comment] 2019-03-15 20:31
duplicate of #15216

**Comment by rafalschmidt97** [comment] 2019-03-22 12:46
Solved by removing default route. Quite weird but it must be connected somehow with outlet maybe. Dunno 🤷‍♂️

![Screenshot 2019-03-22 at 13 43 32](https://user-images.githubusercontent.com/14861637/54823653-c8e24700-4ca8-11e9-8e3a-7566adbccf20.png)

**Comment by JustasKuizinas** [comment] 2019-03-31 19:02
Have same problem when using <ion-back-button></ion-back-button>

**Comment by manojpatel0217** [comment] 2019-04-03 10:38
> Solved by removing default route. Quite weird but it must be connected somehow with outlet maybe. Dunno 🤷‍♂️
> 
> ![Screenshot 2019-03-22 at 13 43 32](https://user-images.githubusercontent.com/14861637/54823653-c8e24700-4ca8-11e9-8e3a-7566adbccf20.png)

Thanks it work for me

**Closed** 2019-04-10 20:19 UTC
Labels: package: angular, type: bug

**Comment by liamdebeasi** [comment] 2019-04-10 20:23
Hi there,

This issue has been resolved, and I have published a nightly build of Ionic with the fix. You can install it with `npm i @ionic/angular@dev`.

Please let me know if you are still running into any issues with this. 

Thanks!
