### ISSUE TITLE
v4: ion-datetime not working, ngModel/ionChange/ngModelChange not working as well!

### ISSUE THREAD

**Issue by gogo217** [ionic-team/ionic#14697] opened 2018-07-02 21:32 UTC
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

*ion-datetime* doesn't work in v4, unable to bind via *ngModel*, *ionChange* and *ngModelChange* doesn't trigger any events.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
<ion-item>
   <ion-label position="stacked">Event Time</ion-label>
   <ion-datetime displayFormat="h:mm A" [(ngModel)]="eventTime" (ngModelChange)="save()" (ionChange)="timeChanged($event)" pickerFormat="h mm A"></ion-datetime>
</ion-item>
<ion-button (click)="save()" expand="block" fill="outline">Save</ion-button>


export class HomePage implements DoCheck {
  eventTime: any;

  save() {
    console.log(this.eventTime);   //undefined
  }

  timeChanged(event: any) {
    console.log(event);                 //undefined
  }

  ngDoCheck() {
    console.log(this.eventTime);
  }
}

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic (Ionic CLI)          : 4.0.0-rc.9 (C:\Users\albertc\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework            : @ionic/angular 4.0.0-alpha.7
@angular-devkit/core       : 0.7.0-rc.0
@angular-devkit/schematics : 0.7.0-rc.0
@angular/cli               : 6.0.8
@ionic/ng-toolkit          : 1.0.0-rc.9
@ionic/schematics-angular  : 1.0.0-rc.9
```

**Comment by mburger81** [comment] 2018-07-03 12:43
Are there some exception? Did you import FormsModule to get work ngModel?

**Comment by gogo217** [comment] 2018-07-07 07:14
not sure what you mean, never heard it worked without importing **FormsModule**.
had to do by:
```
document.getElementById('startDate') as any).value
```

**Comment by geo242** [comment] 2018-07-31 20:43
I can also confirm that this is not working correctly. Not getting any calls to the ngModelChange handler on ion-datetime.

**Comment by turnono** [comment] 2018-09-02 07:30
Not working for me too, ionChange does not fire, cannot select first values i.e. 01, January and whichever year appears first in the list.

**Comment by nikolayr1** [comment] 2018-09-02 10:13
Not working for me too. ionChange does not emmit no event.

**Comment by tuxicoman** [comment] 2018-09-02 15:50
I had the same issue in 4.0.0-beta.0, fixed by updating to 4.0.0-beta7.

NB: there are **breaking changes** when updating, see [beta 5](https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.5) and [beta 6](https://github.com/ionic-team/ionic/releases/tag/v4.0.0-beta.6)

**Comment by ngrealish** [comment] 2018-09-04 03:05
Having the same issue, upgraded to 4.1.1 with no help.  I initially set the datetime properly:

`
    this.eventModel = {
      type: 'event',
      id: null,
      data: {
        timestamp: moment().startOf('day').toISOString(true),
        ...
      }
    }
`

`
    <ion-datetime
      display-format="MMM DD, YYYY"
      picker-format="MMM DD YYYY"
      min="2010"
      max="2030"
      class="form__group__item--input has-value"
      placeholder="Select Date"
      formControlName="date"
      [(ngModel)]="eventModel.data.timestamp"
      (ngModelChange)="test('1')"
      (ionChange)="test('2')"
    ></ion-datetime>
`

The `(ngModelChange)` fires its function when the `ion-datetime` is rendered, but when I go to change the date and click "done" absolutely nothing happens.  The date does not update when I "submit" either.

**Comment by ngrealish** [comment] 2018-09-04 03:26
had to write in a simple converter using the `pickerOptions` and moment.js to get my date needed.

```
    this.dateTimeOptions = {
        buttons: [{
            text: 'Cancel',
        },{
            text: 'Done',
            handler: (dateModel) => {
                const dateTime = moment(dateModel.month.text + " " + dateModel.day.text + "," + dateModel.year.text).toISOString(true);
                this.eventModel.data.timestamp = dateTime;
            }
        }]
    };
```

```
    <ion-datetime
        display-format="MMM DD, YYYY"
        picker-format="MMM DD YYYY"
        min="2010"
        max="2030"
        class="form__group__item--input has-value"
        formControlName="date"
        placeholder="Select Date"
        [(ngModel)]="eventModel.data.timestamp"
        [pickerOptions]="dateTimeOptions"
    ></ion-datetime>
```

YMMV:  I only used a date picker selecting month, day and year.  If you are selecting times as well, you'll need to include that properly inside of moment with the returned dateModel

It's inconvenient and not exactly clean, but it works...

**Comment by brandyscarney** [comment] 2018-09-19 18:36
I am not able to reproduce the original issue by plugging the code into our [conference app](https://github.com/ionic-team/ionic-conference-app) running `4.0.0-beta.11`. 

- If you are still seeing this issue: run `ionic info` and make sure the **Ionic Framework** version matches `@ionic/angular 4.0.0-beta.11`.

<img width="675" alt="screen shot 2018-09-19 at 2 34 38 pm" src="https://user-images.githubusercontent.com/6577830/45773765-32f63280-bc19-11e8-896e-42a986cc4943.png">

- If you're seeing an issue other than the original one: search through our issues to see if one exists for it or create a [new issue](https://github.com/ionic-team/ionic/issues/new/choose) if one does not.

- If anyone is still seeing this issue on `4.0.0-beta.11`: please provide a way for me to reproduce or an example repository. Thanks!

**Comment by brandyscarney** [comment] 2018-09-28 14:18
@JuergsPona That is not related to the original issue. Please create a new issue.

**Comment by rafaelbatistamarcilio** [comment] 2018-09-29 02:09
The content is hiddem on the bottom of the page. I need to force padding-bottom to show the date picker elements

![image](https://user-images.githubusercontent.com/16135328/46239767-8bdd6d80-c373-11e8-85b5-be031e8aaedc.png)

**Comment by rafaelbatistamarcilio** [comment] 2018-09-29 03:29
I fix with this:

`
.picker-wrapper {
  padding-bottom: 900px !important;
}

.picker-toolbar {
  position: absolute !important;
}

.picker-columns {
  display: -webkit-box !important;
  contain: unset !important;
  overflow: initial !important;
}`

**Comment by gogo217** [comment] 2018-10-03 06:46
I think this issue was fixed in the past, but `formControlName` was not working with `ion-datetime` so had to use `formControl` instead, is this a new issue? 

```
<ion-datetime pickerFormat="MMM DD YYYY HH:mm" max="2030" displayFormat="MMM DD YYYY HH:mm" [formControl]="eventForm.controls['start']"></ion-datetime>
```

**Comment by kensodemann** [comment] 2018-10-03 14:20
I am unable to duplicate this issue at all using beta.12. This included testing the `ionChange` event and using `formControlName` as such.

If this problem persists for you, please open a new issue with a link to a repo containing a sample application that duplicates the issue.

Thank you for using Ionic!

**Closed by kensodemann** 2018-10-03 14:20 UTC
Labels: triage
