### ISSUE TITLE
bug: Android opens the app, presses the physical back button in tabs, and the app exits

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic#19740] opened 2019-10-24 09:44 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Android opens the app, presses the physical back button in tabs, and the app exits，If you switch to another page, or stay longer, you won't have a problem

**Expected behavior:**

Don't just quit the program

**Comment by liamdebeasi** [comment] 2019-10-24 12:54
Thanks for the issue. This is the default behavior for most apps that do not have anything in the navigation stack. Does this issue only occur on first launch, or after you have navigated?

**Comment by C-racker** [comment] 2019-10-24 13:07
> Thanks for the issue. This is the default behavior for most apps that do not have anything in the navigation stack. Does this issue only occur on first launch, or after you have navigated?

After entering the application for the first time without any operation, there will be a problem in returning directly. When you switch to another tabs page, or jump to another page and return to tabs, there will be no such problem.

**Comment by liamdebeasi** [comment] 2019-10-24 13:18
This is the default behavior for most Android apps (including native ones) and is typically what most users expect in terms of behavior. As a result, we do not recommend altering this behavior. I am going to close this as this is not a bug in Ionic Framework. Thanks!

**Closed by liamdebeasi** 2019-10-24 13:18 UTC
Labels: triage

**Comment by C-racker** [comment] 2019-10-25 00:03
> This is the default behavior for most Android apps (including native ones) and is typically what most users expect in terms of behavior. As a result, we do not recommend altering this behavior. I am going to close this as this is not a bug in Ionic Framework. Thanks!

But ionic3 doesn't exist in this problem :(

**Comment by liamdebeasi** [comment] 2019-10-25 20:23
Can you provide a reproduction of this in v3?
