### ISSUE TITLE
bug: Service worker doesn't work after building an app

### ISSUE THREAD

**Issue by PatrykJankowski** [ionic-team/ionic#20890] opened 2020-03-27 00:00 UTC
**Ionic version:**
[x] **5.0.5**

**Current behavior:**
Service worker can't be registered after building an app on a device.
It is working fine if you go to `www` directory and run `http-server -p 8080`

**Expected behavior:**
Service worker should be registered.

**Steps to reproduce:**
- create a new project `ionic start myApp tabs --capacitor` (for angular)
- add service worker `ng add @angular/pwa --project app`
- `ionic build --prod`
- `npx cap sync` and build an app in Android Studio
- open dev tools on Chrome to see an error

**Other information:**
After you add service worker and do `ionic build --prod` go to `www` directory and run `http-server -p 8080`. Service worker is registered and working in this case.

![obraz](https://user-images.githubusercontent.com/16896903/77707637-08cbc080-6fc6-11ea-8509-aa480d4050c4.png)

**Comment by liamdebeasi** [comment] 2020-03-27 16:25
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The loading of the service worker is not handled by Ionic Framework.

I spoke with a team member about this to get some more clarification. Chrome allows Service Workers to be loaded only over secure contexts. In this case, it considers `http://localhost` to be a secure context.

Since Capacitor uses a small web server to load your app, it treats all requests as actual network requests. As a result, your service worker request is blocked because `http://localhost` is being treated as an unsecure network request. You would likely run into the same issue if you used Cordova.

Since Service Workers are really geared towards PWAs and not standalone apps, it probably would be best to let the service worker loading gracefully fail in your Capacitor app. Hope this clears things up!

**Closed by liamdebeasi** 2020-03-27 16:25 UTC
Labels: triage
