### ISSUE TITLE
[4.0.0-beta.16] ios ion-header with toolbar not animating properly

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic#16363] opened 2018-11-18 18:58 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 0.7.5
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 12 other plugins)

System:

   NodeJS : v10.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Describe the Bug**
In ios mode, when you navigate back from a page that has an `ion-toolbar` in the `ion-header`, the `ion-toolbar` remains until the back page is loaded and then it magically vanishes. This is _very_ different from the animation when moving forward to a page that does not have an `ion-toolbar` and is incredibly jarring.

![input](https://user-images.githubusercontent.com/2852839/48676820-87b01e00-eb74-11e8-9bcb-192d267c8e23.gif)

**Steps to Reproduce**
Navigate to a page that has the following in the header:
```html
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button defaultHref='/home'></ion-back-button>
    </ion-buttons>
    <ion-title>My Bookings</ion-title>
    <ion-buttons slot="end">
      <ion-button (click)="viewHistory()">
        <ion-icon slot="icon-only" name="time"></ion-icon>
      </ion-button>
    </ion-buttons>
  </ion-toolbar>
  <ion-toolbar>
    <ion-segment [(ngModel)]="selectedView" color="light" (ionChange)="segmentChanged()">
      <ion-segment-button value="itinerary">
        <ion-label>Itinerary</ion-label>
      </ion-segment-button>
      <ion-segment-button value="calendar">
        <ion-label>Calendar</ion-label>
      </ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>
```

**Expected Behavior**
Animations should be smooth going forward and backward with `ion-toolbar` in the headers on both ios and md modes.

**Comment by sbannigan** [comment] 2018-11-19 16:40
duplicate of #16262

**Comment by brandyscarney** [comment] 2018-11-28 23:02
Thanks for the issue and for reporting the dup @sbannigan, closing a a duplicate of #16262.

**Closed by brandyscarney** 2018-11-28 23:02 UTC
Labels: triage
