### ISSUE TITLE
[Ionic4] Safari issues with var(--*-rgb) [RGB versions of CSS color variables]

### ISSUE THREAD

**Issue by olivermuc** [ionic-team/ionic#16123] opened 2018-10-29 09:51 UTC
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/Users/oliverseidel/.npm-packages/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/oliverseidel/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.9.1 (/usr/local/Cellar/node/8.9.1/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
Just a heads up in case anyone was wondering why Safari renders CSS in many places vastly different to Chrome:

This does not work:
```
border: 19px solid rgba(var(--ion-color-primary-rgb), 0.9);
```
This however does:
```
--workaround-border-color: 19px solid rgba(var(--ion-color-primary-rgb), 0.9);
border: var(--workaround-border-color);
```
Bottom line, currently Safari (Mac **and** iOS/cordova) doesn't render `*-rgb` values properly for
* border
* box-shadow
and probably more!

**Steps to Reproduce**
Just add above CSS sample code (or similar) to any of your apps, of course debugging in Safari.

**Related Code**
See example above.

**Expected Behavior**
Of course Safari should handle `*-rgb` injected variables the same way Chrome does, but since that may be way out, Ionic may be able to work around that.

**Comment by brandyscarney** [comment] 2018-10-31 19:00
Thanks for the issue! I am able to reproduce this using the code you provided. However, I'm unable to reproduce in an Ionic component. Did you have any components you were running into this on?

Also, here is the bug report in Safari: https://bugs.webkit.org/show_bug.cgi?id=185940

**Comment by olivermuc** [comment] 2018-10-31 22:12
Not sure there is an ionic component that makes use of the -rgb variables in such a way.
But I wanted to point out that there is a general usability issue, affecting the proper use of the -rgb variables and what they are intended for.

On top of those actual bugs/issues, I also noticed very noticable perfomance differences between Chrome and Safari. To the point where I wonder if large, real life production apps can be done in v4.
Encapsulation and CSS variables appear to slow down Safari/UX dramatically.

**Comment by brandyscarney** [comment] 2018-11-05 15:42
Thanks for the reply! So since this is a limitation of CSS variables with Safari I have created an issue to add this to our documentation: https://github.com/ionic-team/ionic-docs/issues/167

As for the performance differences, we have done a lot of work to improve performance leading up to the latest beta (https://blog.ionicframework.com/ionic-release-v4-beta-15-out-today/). We haven't noticed any issues between Chrome/Safari in this beta. If you are able to provide a way for us to reproduce the performance problems or a repository to clone we could look into it further.

I am going to close this issue as the main issue is currently a documentation problem. However, if you find any Ionic components with this bug please create a new issue with which components are affected. Thank you!

**Closed by brandyscarney** 2018-11-05 15:42 UTC
